### ISSUE TITLE
SEUS Renewed still fails to compile on Mesa drivers

### ISSUE THREAD

**Issue by TheDrifter363** [IrisShaders/Iris#1052]
### What happened?

SEUS renewed used to work, not anymore. Not sure why. Using AMD RX 6900 XT, was using Nvidia RTX 2060 before. Got the latest Iris and Sodium.

### Relevant log output

```shell
[02:33:52] [main/INFO]: Loading for game Minecraft 1.17.1
[02:33:52] [main/INFO]: Loading 67 mods:
	- com_moandjiezana_toml_toml4j 0.7.2
	- dynamicfps 2.0.6
	- fabric 0.44.0+1.17
	- fabric-api-base 0.4.0+cf39a74318
	- fabric-api-lookup-api-v1 1.4.0+cb9053d118
	- fabric-biome-api-v1 3.2.2+cf39a74318
	- fabric-blockrenderlayer-v1 1.1.6+cf39a74318
	- fabric-command-api-v1 1.1.4+cf39a74318
	- fabric-commands-v0 0.2.3+cf39a74318
	- fabric-containers-v0 0.1.13+cf39a74318
	- fabric-content-registries-v0 0.4.1+3447790d18
	- fabric-crash-report-info-v1 0.1.6+cf39a74318
	- fabric-dimensions-v1 2.0.13+cf39a74318
	- fabric-entity-events-v1 1.4.1+377137cc18
	- fabric-events-interaction-v0 0.4.12+e99fbe1218
	- fabric-events-lifecycle-v0 0.2.4+cf39a74318
	- fabric-game-rule-api-v1 1.0.8+cf39a74318
	- fabric-item-api-v1 1.3.0+6617390918
	- fabric-item-groups-v0 0.3.2+cf39a74318
	- fabric-key-binding-api-v1 1.0.6+2a2bb57318
	- fabric-keybindings-v0 0.2.4+cf39a74318
	- fabric-lifecycle-events-v1 1.4.6+0392f3a618
	- fabric-loot-tables-v1 1.0.5+cf39a74318
	- fabric-mining-level-api-v1 1.0.3+cf39a74318
	- fabric-mining-levels-v0 0.1.6+cf39a74318
	- fabric-models-v0 0.3.1+cf39a74318
	- fabric-networking-api-v1 1.0.14+cf39a74318
	- fabric-networking-blockentity-v0 0.2.12+cf39a74318
	- fabric-networking-v0 0.3.3+cf39a74318
	- fabric-object-builder-api-v1 1.11.0+f907116918
	- fabric-object-builders-v0 0.7.7+cf39a74318
	- fabric-particles-v1 0.2.5+cf39a74318
	- fabric-registry-sync-v0 0.7.13+cf39a74318
	- fabric-renderer-api-v1 0.4.5+cf39a74318
	- fabric-renderer-indigo 0.4.9+cf39a74318
	- fabric-renderer-registries-v1 3.2.6+cf39a74318
	- fabric-rendering-data-attachment-v1 0.1.6+cf39a74318
	- fabric-rendering-fluids-v1 0.2.1+cf39a74318
	- fabric-rendering-v0 1.1.7+cf39a74318
	- fabric-rendering-v1 1.10.1+377137cc18
	- fabric-resource-loader-v0 0.4.10+f09604ce18
	- fabric-screen-api-v1 1.0.5+cf39a74318
	- fabric-screen-handler-api-v1 1.1.9+cf39a74318
	- fabric-structure-api-v1 1.1.15+cf39a74318
	- fabric-tag-extensions-v0 1.2.3+cf39a74318
	- fabric-textures-v0 1.0.7+cf39a74318
	- fabric-tool-attribute-api-v1 1.3.2+cf39a74318
	- fabric-transfer-api-v1 1.5.3+cf39a74318
	- fabricloader 0.12.2
	- iris 1.1.3
	- java 17
	- lambdacontrols 1.7.1+1.17
	- litematica 0.0.0-dev.20211201.000016
	- lithium 0.7.5
	- malilib 0.10.0-dev.26
	- minecraft 1.17.1
	- modmenu 2.0.14
	- org_anarres_jcpp 1.4.14
	- org_aperlambda_lambdajcommon 1.8.1
	- org_joml_joml 1.10.2
	- org_slf4j_slf4j-api 1.7.12
	- sodium 0.3.3+build.8
	- spruceui 3.2.0+1.17
	- starlight 1.0.0+fabric.73f6d37
	- voicechat 1.17.1-2.1.11
	- xaerominimap 21.22.3
	- xaeroworldmap 1.18.4
[02:33:52] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/USER/.config/gdlauncher_next/datastore/libraries/net/fabricmc/sponge-mixin/0.10.3+mixin.0.8.4/sponge-mixin-0.10.3+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[02:33:52] [main/INFO]: Compatibility level set to JAVA_16
[02:33:52] [main/INFO]: Loaded configuration file for Lithium: 87 options available, 0 override(s) found
[02:33:52] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[02:33:53] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[02:33:56] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[02:33:56] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[02:33:57] [Render thread/INFO]: Setting user: TheDrifter363
[02:33:57] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zdk000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[02:33:57] [Render thread/INFO]: [LambdaControls] Initializing LambdaControls...
[02:33:57] [Render thread/INFO]: Compatibility version 12
[02:33:57] [Render thread/INFO]: Loading plugins
[02:33:57] [Render thread/INFO]: Loaded 0 plugin(s)
[02:33:57] [Render thread/INFO]: Initializing plugins
[02:33:57] [Render thread/INFO]: Initialized 0 plugin(s)
[02:33:57] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[02:33:57] [Render thread/INFO]: Loading Xaero's Minimap - Stage 1/2
[02:33:58] [Render thread/INFO]: Loading Xaero's World Map - Stage 1/2
[02:33:58] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[02:33:59] [Render thread/INFO]: [STDERR]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[02:33:59] [Render thread/INFO]: [STDERR]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[02:33:59] [Render thread/INFO]: [STDERR]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[02:33:59] [Render thread/INFO]: Using shaderpack: SEUS-Renewed-v1.0.1.zip
[02:33:59] [Render thread/INFO]: Hardware information:
[02:33:59] [Render thread/INFO]: CPU: 16x AMD Ryzen 7 3700X 8-Core Processor
[02:33:59] [Render thread/INFO]: GPU: AMD Radeon RX 6900 XT (SIENNA_CICHLID, DRM 3.42.0, 5.15.0-6.1-liquorix-amd64, LLVM 12.0.0) (Supports OpenGL 4.6 (Core Profile) Mesa 21.2.2)
[02:33:59] [Render thread/INFO]: OS: Linux
[02:34:00] [Render thread/WARN]: Method overwrite conflict for getNativeMemoryUsage in sodium.mixins.json:features.debug.MixinDebugHud, previously written by net.coderbot.iris.mixin.MixinDebugScreenOverlay. Skipping method.
[02:34:00] [Render thread/INFO]: Narrator library successfully loaded
[02:34:00] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Dynamic FPS, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Level API (v1), Fabric Mining Levels (v0), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking Block Entity (v0), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Object Builders (v0), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Structure API (v1), Fabric Tag Extensions (v0), Fabric Textures (v0), Fabric Tool Attribute API (v1), Fabric Transfer API (v1), Fabric Loader, Iris, LambdaControls, Litematica, Lithium, MaLiLib, Mod Menu, Sodium, SpruceUI, Starlight, Simple Voice Chat, Xaero's Minimap, Xaero's World Map), CreativeMusic.zip
[02:34:00] [Render thread/INFO]: [LambdaControls] Configuration loaded.
[02:34:00] [Render thread/WARN]: Unable to read property: east with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[02:34:00] [Render thread/WARN]: Unable to read property: south with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[02:34:00] [Render thread/WARN]: Unable to read property: north with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[02:34:00] [Render thread/WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[02:34:00] [Render thread/WARN]: Unable to read property: east with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[02:34:00] [Render thread/WARN]: Unable to read property: south with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[02:34:00] [Render thread/WARN]: Unable to read property: north with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[02:34:00] [Render thread/WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[02:34:00] [Render thread/INFO]: Loading Xaero's Minimap - Stage 2/2
[02:34:01] [Render thread/INFO]: [STDOUT]: Xaero's Minimap: World Map found!
[02:34:01] [Render thread/INFO]: [STDOUT]: No Optifine!
[02:34:01] [Render thread/INFO]: Loading Xaero's World Map - Stage 2/2
[02:34:01] [Render thread/INFO]: [STDOUT]: New world map region cache hash code: 132311591
[02:34:01] [Render thread/INFO]: Xaero's WorldMap Mod: Xaero's minimap found!
[02:34:01] [Render thread/INFO]: [STDOUT]: No Optifine!
[02:34:01] [Render thread/INFO]: [STDOUT]: No Vivecraft!
[02:34:02] [Render thread/INFO]: OpenAL initialized.
[02:34:02] [Render thread/INFO]: Sound engine started
[02:34:02] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[02:34:02] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[02:34:02] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[02:34:02] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[02:34:02] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[02:34:02] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[02:34:02] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[02:34:02] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[02:34:02] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[02:34:02] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[02:34:02] [Render thread/INFO]: [STDOUT]: Successfully reloaded the minimap shaders!
[02:34:02] [Render thread/INFO]: [STDOUT]: Successfully reloaded the world map shaders!
[02:34:12] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[02:34:12] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[02:34:12] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[02:34:12] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[02:34:12] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[02:34:12] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Tool Attribute API (v1))
[02:34:12] [Render thread/INFO]: Loaded 7 recipes
[02:34:12] [Render thread/INFO]: Loaded 1137 advancements
[02:34:12] [Render thread/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 1.168 ms
[02:34:12] [Render thread/INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
[02:34:13] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[02:34:13] [Server thread/INFO]: Starting integrated minecraft server version 1.17.1
[02:34:13] [Server thread/INFO]: Generating keypair
[02:34:13] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[02:34:13] [Render thread/INFO]: Preparing spawn area: 0%
[02:34:13] [Render thread/INFO]: Preparing spawn area: 6%
[02:34:14] [Server thread/INFO]: Using default voicechat socket implementation
[02:34:14] [VoiceChatServerThread/INFO]: Server started at port 51126
[02:34:14] [Render thread/INFO]: Time elapsed: 816 ms
[02:34:14] [Server thread/INFO]: Changing view distance to 11, from 10
[02:34:14] [Server thread/INFO]: TheDrifter363[local:E:4fe7aa97] logged in with entity id 48 at (-250.27793781313264, 64.20000004768372, 187.32704726033919)
[02:34:14] [Server thread/INFO]: TheDrifter363 joined the game
[02:34:14] [Render thread/INFO]: [STDOUT]: New minimap session initialized!
[02:34:14] [Render thread/INFO]: [STDOUT]: New world map session initialized!
[02:34:14] [Render thread/INFO]: Started 10 worker threads
[02:34:14] [Render thread/INFO]: Sending secret request to the server
[02:34:14] [Netty Server IO #1/INFO]: Received secret request of TheDrifter363 (12)
[02:34:14] [Netty Server IO #1/INFO]: Sent secret to TheDrifter363
[02:34:14] [Server thread/INFO]: Saving and pausing game...
[02:34:14] [Render thread/INFO]: Using 3 total BufferBuilder caches
[02:34:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Test]'/minecraft:overworld
[02:34:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Test]'/minecraft:the_nether
[02:34:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Test]'/minecraft:the_end
[02:34:15] [Render thread/INFO]: Loaded 153 advancements
[02:34:15] [Render thread/INFO]: Received secret
[02:34:15] [Render thread/INFO]: Connecting to server: '127.0.0.1:51126'
[02:34:15] [VoiceChatAuthenticationThread/INFO]: Trying to authenticate voice connection
[02:34:15] [VoiceChatPacketProcessingThread/INFO]: Successfully authenticated player fb5f4de6-2253-4e92-92eb-6f03c51e9c4b
[02:34:15] [VoiceChatConnectionThread/INFO]: Server acknowledged authentication
[02:34:15] [Render thread/INFO]: Creating pipeline OVERWORLD
[02:34:15] [Render thread/INFO]: OpenGL debug message: id=2, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='0:493(20): error: initializer of const variable `K_R' must be a constant expression'
[02:34:15] [Render thread/INFO]: OpenGL debug message: id=3, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='0:494(20): error: initializer of const variable `K_M' must be a constant expression'
[02:34:15] [Render thread/WARN]: Shader compilation log for composite.fsh: 0:493(20): error: initializer of const variable `K_R' must be a constant expression
0:494(20): error: initializer of const variable `K_M' must be a constant expression

[02:34:15] [Render thread/ERROR]: Couldn't load NewWorldRenderingPipeline, falling back to vanilla shaders.
java.lang.RuntimeException: Shader compilation failed!
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:244) ~[iris-mc1.17-1.1.3.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:102) ~[iris-mc1.17-1.1.3.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:211) ~[iris-mc1.17-1.1.3.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:427) ~[iris-mc1.17-1.1.3.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:32) [iris-mc1.17-1.1.3.jar:?]
	at net.minecraft.class_761.handler$zjo000$iris$beginLevelRender(class_761.java:5816) [intermediary-1.17.1.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1129) [intermediary-1.17.1.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1026) [intermediary-1.17.1.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:810) [intermediary-1.17.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1112) [intermediary-1.17.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568) [fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.12.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.2.jar:?]
Caused by: java.lang.RuntimeException: Failed to compile FRAGMENT shader for program composite.fsh
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:100) ~[iris-mc1.17-1.1.3.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:71) ~[iris-mc1.17-1.1.3.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:240) ~[iris-mc1.17-1.1.3.jar:?]
	... 18 more
Caused by: java.lang.RuntimeException: Shader compilation failed, see log for details
	at net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:44) ~[iris-mc1.17-1.1.3.jar:?]
	at net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:23) ~[iris-mc1.17-1.1.3.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:98) ~[iris-mc1.17-1.1.3.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:71) ~[iris-mc1.17-1.1.3.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:240) ~[iris-mc1.17-1.1.3.jar:?]
	... 18 more
[02:34:15] [Render thread/INFO]: [STDOUT]: No Iris!
[02:34:15] [Render thread/INFO]: [STDOUT]: No Iris!
[02:34:15] [Render thread/INFO]: [STDOUT]: Reloading entity icon resources...
[02:34:15] [Render thread/INFO]: [STDOUT]: Done!
[02:34:19] [Server thread/INFO]: Saving and pausing game...
[02:34:19] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Test]'/minecraft:overworld
[02:34:19] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Test]'/minecraft:the_nether
[02:34:19] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Test]'/minecraft:the_end
[02:34:20] [Render thread/INFO]: Clearing audio channels
[02:34:20] [Render thread/INFO]: Stopping microphone thread
[02:34:20] [Render thread/INFO]: Disconnecting voicechat
[02:34:20] [Render thread/INFO]: [STDOUT]: Minimap session finalized.
[02:34:20] [Render thread/INFO]: [STDOUT]: Finalizing world map session...
[02:34:20] [Thread-3/INFO]: [STDOUT]: World map force-cleaned!
[02:34:20] [Render thread/INFO]: [STDOUT]: World map session finalized.
[02:34:20] [Server thread/INFO]: TheDrifter363 lost connection: Disconnected
[02:34:20] [Server thread/INFO]: TheDrifter363 left the game
[02:34:20] [Server thread/INFO]: Disconnecting client TheDrifter363
[02:34:20] [Server thread/INFO]: Stopping singleplayer server as player logged out
[02:34:20] [Server thread/INFO]: Stopping server
[02:34:20] [Server thread/INFO]: Saving players
[02:34:20] [Server thread/INFO]: Saving worlds
[02:34:20] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Test]'/minecraft:overworld
[02:34:20] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Test]'/minecraft:the_nether
[02:34:20] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Test]'/minecraft:the_end
[02:34:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (Test): All chunks are saved
[02:34:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[02:34:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[02:34:20] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[02:34:20] [Render thread/INFO]: Stopping worker threads
[02:34:21] [Render thread/INFO]: Stopping!
```

### Iris and Minecraft Version

iris-mc1.17-1.1.3 for Minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Linux 5.15.0-6.1-liquorix-amd64

### What is your GPU?

AMD Radeon RX 6900 XT

### Java Version

Java 17

**Comment by coderbot16** [comment]
This is the shader pack's fault and the code here is just flat out wrong, but we've been trying to work around the many driver support issues in SEUS regardless. Seems like there's still more things that need to be addressed before SEUS will work fully on Linux Mesa drivers.

Apparently enabling `force_glsl_extensions_warn` in drirc works around this issue. Haven't tested that myself.

**Comment by TheDrifter363** [comment]
> 

Hey thanks coderbot.

How would I enable that extension? I use GDLauncher. Should I put that in some config file or something? So it is a compatibility with the shader pack and iris. Thing is, it was working fine before the recent update. When Iris and Sodium were bundled together. I also had a Nvidia GPU back then, recently got an AMD one. Don't know if there's a GPU incompatibility also. Thanks for the advice dude.

**Comment by coderbot16** [comment]
Not sure how to enable it. But switching from NVIDIA's drivers to Mesa drivers is why the error is happening to you now. It's still the shader pack's fault, since the developer only made it to work with NVIDIA drivers.

**Comment by TheDrifter363** [comment]
> 

Oooh so that's the issue! The shader pack is Nvidia exclusive? Crap, I thought I read it was GPU agnostic. Damn. I know the ray tracing one was nvidia exclusive, or at least I thought it was. Even the non ray tracing one is nvidia exclusive? Alright, if that's the case, I'll have to try a different shader. Thanks dude.

**Comment by rhjdvsgsgks** [comment]
you just need to type `force_glsl_extensions_warn=true /path/to/your/launcher` and it should works.
it would be easier if you are using polymc/multimc https://github.com/MultiMC/Launcher/issues/4308

**Comment by coderbot16** [comment]
Does this issue still occur on Iris 1.4 and above?

**Comment by Lolothepro** [comment]
no
