### ISSUE TITLE
Iris crashes upon loading a world

### ISSUE THREAD

**Issue by thefirethirteen** [IrisShaders/Iris#1069]
### Iris and Minecraft Version

iris-mc1.18-1.1.3.jar with Minecraft 1.18.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Linux (Pop!_OS 21.04) 5.13.0-7620-generic

### What is your GPU?

NVIDIA GeForce GTX 1650 Ti Mobile

### Java Version

openjdk version "17.0.1" 2021-10-19

### Reproduction Steps

1. Join any [singleplayer] world or server
2. Game Crashes

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 10/12/2021, 16:44
Description: Unexpected error

java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
	at net.minecraft.class_4587.method_23760(class_4587.java:65)
	at net.minecraft.class_757.redirect$zbi000$iris$saveBobbing(class_757.java:2541)
	at net.minecraft.class_757.method_3188(class_757.java:1025)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
	at net.minecraft.class_4587.method_23760(class_4587.java:65)
	at net.minecraft.class_757.redirect$zbi000$iris$saveBobbing(class_757.java:2541)
	at net.minecraft.class_757.method_3188(class_757.java:1025)

-- Affected level --
Details:
	All players: 1 total; [class_746['thefirethirteen'/218, l='ClientLevel', x=56.50, y=72.00, z=42.50]]
	Chunk stats: 1024, 444
	Level dimension: minecraft:overworld
	Level spawn location: World: (48,78,32), Section: (at 0,14,0 in 3,4,2; chunk contains blocks 48,-64,32 to 63,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 48 game time, 48 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) version 5.13.0-7620-generic
	Java Version: 17.0.1, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 1701496832 bytes (1622 MiB) / 5142216704 bytes (4904 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.20
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: CometLake-H GT2 [UHD Graphics]
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x9bc4
	Graphics card #0 versionInfo: unknown
	Graphics card #1 name: TU117M [GeForce GTX 1650 Ti Mobile]
	Graphics card #1 vendor: NVIDIA Corporation (0x10de)
	Graphics card #1 VRAM (MB): 288.00
	Graphics card #1 deviceId: 0x1f95
	Graphics card #1 versionInfo: unknown
	Virtual memory max (MB): 23937.20
	Virtual memory used (MB): 20434.41
	Swap memory total (MB): 16000.50
	Swap memory used (MB): 6286.86
	JVM Flags: 2 total; -Xms409m -Xmx8192m
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1650 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 470.86, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['thefirethirteen'/218, l='ServerLevel[New World]', x=56.50, y=72.00, z=42.50]]
	Data Packs: vanilla
```

### Additional context

[latest.log](https://github.com/IrisShaders/Iris/files/7693498/latest.log)
[crash-2021-12-10_16.44.05-client.txt](https://github.com/IrisShaders/Iris/files/7693499/crash-2021-12-10_16.44.05-client.txt)

* using the MultiMC Minecraft launcher
* sodium: sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar
* adding fabric `fabric-api-0.44.0+1.18.jar` (to satisfy some sodium soft dependencies) does not help

**Comment by thefirethirteen** [comment]
Dang it's the same thing as #1068 isn't it?

**Comment by thefirethirteen** [comment]
Yup. Also the public test build mentioned seems to work on 1.18.1 full.
