### ISSUE TITLE
Game crashes open shader pack settling while joining a world

### ISSUE THREAD

**Issue by SnooComics9452** [IrisShaders/Iris#1070]
### Iris and Minecraft Version

iris-mc1.16.5-1.1.3 for 1.16.2

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Intel(R) HD Graphics 4600

### Java Version

Included in launcher

### Reproduction Steps

1. Join any world
2. Go to options > Video settlings > Shader packs...
3. Game crashes instantly

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// You're mean.

Time: 21年12月10日 下午11:22
Description: mouseClicked event handler

java.lang.NoSuchMethodError: net.coderbot.iris.gui.element.ShaderPackSelectionList.method_31322(Z)V
	at Not Enough Crashes deobfuscated stack trace.(1.16.2+build.47)
	at net.coderbot.iris.gui.screen.ShaderPackScreen.init(ShaderPackScreen.java:69)
	at net.minecraft.client.gui.screen.Screen.init(Screen:325)
	at net.minecraft.client.MinecraftClient.openScreen(MinecraftClient:897)
	at me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.handler$zbo000$iris$onSetPage(SodiumOptionsGUI.java:547)
	at me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.setPage(SodiumOptionsGUI.java)
	at me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.lambda$rebuildGUIPages$0(SodiumOptionsGUI.java:135)
	at me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI$$Lambda$4532/165766986.run(Unknown Source)
	at me.jellysquid.mods.sodium.client.gui.widgets.FlatButtonWidget.mouseClicked(FlatButtonWidget.java:54)
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27)
	at net.minecraft.client.Mouse.method_1611(Mouse:92)
	at net.minecraft.class_312$$Lambda$4291/309394812.run(Unknown Source)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:435)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:92)
	at net.minecraft.client.Mouse.method_22686(Mouse:162)
	at net.minecraft.class_312$$Lambda$4290/61056079.run(Unknown Source)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:94)
	at net.minecraft.client.Mouse.method_22684(Mouse:162)
	at net.minecraft.class_312$$Lambda$3039/1083439555.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:102)
	at net.minecraft.client.util.Window.swapBuffers(Window:308)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1043)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:656)
	at net.minecraft.client.main.Main.main(Main:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected screen --
Details:
	Screen name: me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:438)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_312$$Lambda$4290/61056079.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at net.minecraft.class_312$$Lambda$3039/1083439555.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)
	at net.minecraft.class_1041.method_15998(class_1041.java:308)
	at net.minecraft.class_310.method_1523(class_310.java:1043)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
-- Affected level --
Details:
	All players: 1 total; [class_746['iskfgisg'/5, l='ClientLevel', x=481.47, y=67.25, z=17.85]]
	Chunk stats: Client Chunk Cache: 256, 72
	Level dimension: minecraft:overworld
	Level spawn location: World: (196,64,252), Chunk: (at 4,4,12 in 12,15; contains blocks 192,0,240 to 207,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 154237894 game time, 16530848 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 982672808 bytes (937 MB) / 1711276032 bytes (1632 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Suspected Mods: Iris (iris), Sodium (sodium), Fabric Loader (fabricloader)
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.9
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bendy-lib: Bendy api 1.1.0
		better_end_skies: Better End Sky 1.2
		carpet: Carpet Mod 1.4.44
		cleanview: CleanView 1.16.5-v1-fabric
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.11.26
		colormatic: Colormatic 2.2.9+mc.1.16.5
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		craftpresence: CraftPresence 1.7.2
		crowdin-translate: CrowdinTranslate 1.2
		damagetilt: Damage Tilt 1.16-fabric-0.1.2
		dark-loading-screen: Dark Loading Screen 1.6.3
		durabilityviewer: Giselbaers Durability Viewer 1.16.5-fabric0.30.0-1.10
		dynamicfps: Dynamic FPS 2.0.2
		emotecraft: Emotecraft 2.0.9
		enhancedblockentities: Enhanced Block Entities 0.4
		euclid: Euclid 1.1
		fabric: Fabric API 0.36.0+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+6aebe11a7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.10+3661eaa17d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.3+f941baf07d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+0ef801b67d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+ca0ef93d7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.3
		fabricskyboxes: FabricSkyBoxes 0.5.0
		fabriczero: Fabric Zero 0.2.1
		fastbench: FastBench 2.3
		fastchest: FastChest 1.2+1.16
		fastfurnace: FastFurnace 2.4
		fpsdisplay: FPS-Display 1.4.1+1.16.4
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		iris: Iris 1.1.3
		itemmodelfix: Item Model Fix 1.0.2+1.16
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kirin: Kirin UI 1.7-1.16.2
		lambdynlights: LambDynamicLights 1.3.4+1.16
		lazydfu: LazyDFU 0.1.2
		minecraft: Minecraft 1.16.2
		modmenu: Mod Menu 1.16.17
		multiconnect: MultiConnect 1.3.18
		multiconnect-api: MultiConnect API 1.3.18
		notenoughcrashes: Not Enough Crashes 3.2.0
		offlineskins: OfflineSkins 1.16.5-v1-fabric
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		presencefootsteps: Presence Footsteps r29+1.16.4
		rad: Reload Audio Driver 1.0.1
		replaymod: Replay Mod 1.16.4-2.6.1
		sodium: Sodium 0.2.0+build.4
		sodium-extra: Sodium Extra 0.3.5
		spruceui: SpruceUI 2.0.4+1.16
		starlight: Starlight fabric-1.0.0-RC2-82ae5ca
		swordblocking: Sword Blocking 1.0.0
		telepistons: Telepistons 1.0.2
		timetolive: Time To Live 0.2
		worldedit: WorldEdit 7.2.4+5723-e3bfc64
		xaerominimap: Xaero's Minimap 21.21.0
		xaeroworldmap: Xaero's World Map 1.18.1
	Launched Version: fabric-loader-0.11.3-1.16.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 20.19.15.5171, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, file/§9Mix §9Pack §932x §9New, file/Better+Rails+1.16.4-1.2.2, Fabric Mods, file/resources_announcements, file/resources
	Current Language: 繁體中文 (台灣)
	CPU: 4x Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
```

**Comment by IMS212** [comment]
1.16.2 is not supported, please update to 1.16.5. (If you’re playing on a 1.16.2 server, you can use the MultiConnect mod to join on 1.16.5.)

**Comment by coderbot16** [comment]
I sorta assumed 1.16.x all worked. But if older 1.16.x versions break, maybe we need to lock to 1.16.5.

**Comment by coderbot16** [comment]
We won't be fixing this crash, but I've explicitly marked the 1.16 version of the mod as only being compatible with 1.16.5. Thanks for the report.
