### ISSUE TITLE
NullPointerException in 1.18.1

### ISSUE THREAD

**Issue by Sneakometer** [IrisShaders/Iris#1077]
### Iris and Minecraft Version

iris-mc1.18.1-1.1.3 for Minecraft 1.18.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

RTX 3070

### Java Version

Java 17

### Reproduction Steps

1. Download & install latest iris release 1.1.3, sodium 1.18 0.4.0
2. Start the game
3. Join a world
4. Crash

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 11.12.21, 22:50
Description: Unexpected error

java.lang.NullPointerException: Cannot read field "field_3911" because "this.field_4015.field_1724" is null
	at net.minecraft.class_757.method_3188(class_757.java:1004)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_757.method_3188(class_757.java:1004)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 4096, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (-400,66,-64), Section: (at 0,2,0 in -25,4,-4; chunk contains blocks -400,-64,-64 to -385,319,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 66624 game time, 1178 day time
	Server brand: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.class_746.method_3135()" because "this.field_3729.field_1724" is null
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1937777712 bytes (1848 MiB) / 4328521728 bytes (4128 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 12
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3,60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x2484
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9709
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 3,20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 3,20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192,00
	Memory slot #2 clockSpeed (GHz): 3,20
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192,00
	Memory slot #3 clockSpeed (GHz): 3,20
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37549,07
	Virtual memory used (MB): 14935,58
	Swap memory total (MB): 4864,00
	Swap memory used (MB): 56,97
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.12.9-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 3.2.0 NVIDIA 497.09, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Sneakometer'/59, l='ServerLevel[1.18]', x=-1432.78, y=130.61, z=1164.25]]
	Data Packs: vanilla
```

**Comment by Soitora** [comment]
Using the latest Sodium (`sodium-fabric-mc1.18.1-rc1-0.4.0-alpha5+build.816.jar`) from their GitHub Actions as well as the latest test (`iris-mc1.18.1-rc2-1.1.3.jar`) from Discord; I still crash to this error.

**Comment by walllable** [comment]
I also have this issue when joining a world.

**Comment by Maja-dev** [comment]
I also experienced the same issue `java.lang.NullPointerException: Cannot read field "field_3911" because "this.field_4015.field_1724" is null` when using the "latest" Sodium and Iris from Github. However installing both Sodium and Iris using the launcher instead of doing both files manually solved the problem. https://github.com/IrisShaders/Iris-Installer/releases/download/2.0.3/Iris-Installer-2.0.3.jar
@walllable @Soitora @Sneakometer you should try the same. Others from Discord had the same problem and same solution.
