### ISSUE TITLE
Iris Shaders crashes when entering a world

### ISSUE THREAD

**Issue by Quizer9O8** [IrisShaders/Iris#1116]
### Minecraft Version

1.18.1

### Iris Version

iris-mc1.18.1-1.1.3

### Sodium Version

sodium-fabric-mc1.18.1-rc1-0.4.0-alpha5build.813

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GTX 1060

### Java Version

Java 17 

### Reproduction Steps

1. Install mods mentioned in Not Enough Crashes: https://crashy.net/sDKUFPEDmZt2Q0Dtbvj6
2. Start the game
3. Create/Load a world
4. Game crashes right before joining world

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 12/19/21, 10:34 PM
Description: Unexpected error

java.lang.NullPointerException: Cannot read field "field_3911" because "this.field_4015.field_1724" is null
	at net.minecraft.class_757.method_3188(class_757.java:1004)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_757.method_3188(class_757.java:1004)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 16384, 459
	Level dimension: minecraft:overworld
	Level spawn location: World: (64,74,128), Section: (at 0,10,0 in 4,4,8; chunk contains blocks 64,-64,128 to 79,319,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 3756 game time, 3756 day time
	Server brand: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.class_746.method_3135()" because "this.field_3729.field_1724" is null
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, xali's Enchanted Books v0.8.zip, xali's Potions v1.0.zip, xali's+Enhanced+Vanilla+v1.9.1.zip, xali's+Bushy+Leaves+v1.0.zip, EclecticTrove-1.18-1.0.1.zip

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1160773632 bytes (1107 MiB) / 2787115008 bytes (2658 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.21
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) UHD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x3e9b
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8682
	Graphics card #1 name: NVIDIA GeForce GTX 1060
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1c20
	Graphics card #1 versionInfo: DriverVersion=30.0.14.7212
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 23057.02
	Virtual memory used (MB): 18093.91
	Swap memory total (MB): 6826.88
	Swap memory used (MB): 580.34
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		advancementplaques: Advancement Plaques 1.4.3
		appleskin: AppleSkin mc1.18-2.2.0
		architectury: Architectury 3.2.51
		armorsoundtweak: Armor Sound Tweak 5.0.0
		authme: Auth Me 2.2.0
		betterfpsdist: Better FPS distance Mod 1.18-1.3
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.5.106
		citresewn: CITResewn 0.8.1-1.18
		clickadv: Clickable Advancements Mod 2.1
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		controlling: Controlling For Fabric 9.0.4
		dark-loading-screen: Dark Loading Screen 1.6.11
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.4
		dynview: Dynamic View Mod 1.18-1.5
		effective: Effective 1.0
		elativitymc_c2me-fabric_ver_1_18_libs_: libs 0.2.0+alpha.5.106
		enchdesc: EnchantmentDescriptions 9.0.2
		entityculling: EntityCulling-Fabric 1.3.3
		fabric: Fabric API 0.44.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9514
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335c8
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95c8
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95c8
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95c8
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378ac8
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9514
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
		fabricloader: Fabric Loader 0.12.12
		fallingleaves: Falling Leaves 1.8.1+1.18.1
		farsight: Farsight Mod 1.18-1.5
		fpsreducer: FPS Reducer 1.25-mc1.18
		highlighter: Highlighter 1.1.2
		horseinfo: Horse Info 0.4.1-1.18
		iceberg: Iceberg 1.0.27
		indium: Indium 1.0.2-alpha1+mc1.18
		inventoryhud: Inventory HUD + 3.4.2
		inventoryprofilesnext: Inventory Profiles Next 1.2.1
		iris: Iris 1.1.3
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.1.0+1.17
		legendarytooltips: Legendary Tooltips 1.1.5
		libzoomer: LibZoomer 0.3.0+1.17.1
		lightoverlay: Light Overlay 6.0.4
		lithium: Lithium 0.7.6
		megane: megane 6.1.2
		megane-base: megane-base 6.1.2
		megane-fabric-transfer: megane-fabric-transfer 6.1.2+1.5.4-b4f4f6cda9
		megane-runtime: megane-runtime 6.1.2
		megane-vanilla: megane-vanilla 6.1.2+1.18.1
		minecraft: Minecraft 1.18.1
		modmenu: Mod Menu 3.0.1
		mousetweaks: Mouse Tweaks 2.19
		namepain: Name Pain 1.4.0
		notenoughanimations: NotEnoughAnimations 1.4.0
		okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_joml_joml: joml 1.10.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		pride: Pride Lib 1.1.0+1.17
		roughlyenoughitems: Roughly Enough Items 7.1.356
		roughlyenoughresources: Roughly Enough Resources 2.3.0
		seedfix: Seed Fix 1.0.0
		skinlayers: 3d Skin Layers 1.3.1
		sodium: Sodium 0.4.0-alpha5+build.813
		spruceui: SpruceUI 3.3.0+1.17
		starlight: Starlight 1.0.0+fabric.d0a3220
		terralith: Terralith for Fabric 2.0_b0.1.8
		waterdripsound: Drip Sounds 1.18-0.3.0
		wthit: wthit 4.4.0
		xaerominimap: Xaero's Minimap 21.22.5
		xaeroworldmap: Xaero's World Map 1.18.7
	Launched Version: fabric-loader-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1060/PCIe/SSE2 GL version 3.2.0 NVIDIA 472.12, NVIDIA Corporation
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/xali's Enchanted Books v0.8.zip (incompatible), file/xali's Potions v1.0.zip (incompatible), file/xali's+Enhanced+Vanilla+v1.9.1.zip, file/xali's+Bushy+Leaves+v1.0.zip, file/EclecticTrove-1.18-1.0.1.zip
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Quizer9O8'/201, l='ServerLevel[Flat Void]', x=32.81, y=70.00, z=102.81]]
	Data Packs: vanilla, Fabric Mods
```

### Additional context

See crash log for more details:
https://crashy.net/sDKUFPEDmZt2Q0Dtbvj6

**Comment by IMS212** [comment]
Please send a full log file, preferably without Not Enough Crashes.

**Comment by Weightierharpy3** [comment]
I also have crashes, when entering the world.
### Minecraft Version
1.18.1

### Fabric Version
fabric-loader-0.12.12-1.18.1

### Iris Version
iris-mc1.18.1-1.1.3

### Sodium Version
sodium-fabric-mc1.18.1-rc1-0.4.0-alpha5+rev.5d364ed

### Operating System
Operating System: Linux (amd64) 
#### Kernel Version
5.10.85-1-lts

### What is your GPU?
Nvidia GeForce GTX 1060 Mobile

### Java Version
17.0.1-open
From SDKMAN

### Reproduction Steps
- Install Fabric
- Install mods mentioned (Sodium & Iris)
- Start the game
- Create/Load a world

Game crashes right before joining world

### Crash
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 12/20/21, 12:21 AM
Description: Unexpected error

java.lang.NullPointerException: Cannot read field "field_3911" because "this.field_4015.field_1724" is null
	at net.minecraft.class_757.method_3188(class_757.java:1004)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_757.method_3188(class_757.java:1004)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 4096, 441
	Level dimension: minecraft:overworld
	Level spawn location: World: (80,4,16), Section: (at 0,4,0 in 5,0,1; chunk contains blocks 80,-64,16 to 95,319,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 188642 game time, 1 day time
	Server brand: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.class_746.method_3135()" because "this.field_3729.field_1724" is null
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) version 5.10.85-1-lts
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2688880024 bytes (2564 MiB) / 5066719232 bytes (4832 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 2.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: HD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x591b
	Graphics card #0 versionInfo: unknown
	Graphics card #1 name: GP106M [GeForce GTX 1060 Mobile]
	Graphics card #1 vendor: NVIDIA Corporation (0x10de)
	Graphics card #1 VRAM (MB): 288.00
	Graphics card #1 deviceId: 0x1c20
	Graphics card #1 versionInfo: unknown
	Virtual memory max (MB): 7935.49
	Virtual memory used (MB): 11679.71
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 8 total; -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1060 with Max-Q Design/PCIe/SSE2 GL version 3.2.0 NVIDIA 495.46, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Weightierharpy3'/33, l='ServerLevel[Test]', x=101.19, y=4.00, z=22.97]]
	Data Packs: vanilla
```

Crash Report file
[crash-2021-12-20_00.21.51-client.txt](https://github.com/IrisShaders/Iris/files/7742402/crash-2021-12-20_00.21.51-client.txt)
Log file Compressed
[2021-12-20-1.log.gz](https://github.com/IrisShaders/Iris/files/7742410/2021-12-20-1.log.gz)
Log file Uncompressed
[2021-12-20-1.log](https://github.com/IrisShaders/Iris/files/7742412/2021-12-20-1.log)

**Comment by IMS212** [comment]
Please stop attempting to use Github Actions builds of Sodium with Iris, they will not work properly as Iris does delicate patching to Sodium.

**Comment by Weightierharpy3** [comment]
I actually built it with gradle, I'm sorry for clogging the comments, wasn't my intention.
And yeah using the latest sodium-fabric-mc1.18-0.4.0-alpha5+build.9 works. Sorry.

**Comment by IMS212** [comment]
No problem, just please test with the version of Sodium we recommend first.
