### ISSUE TITLE
Iris does not work on 1.18.1

### ISSUE THREAD

**Issue by An0nym0us-sh** [IrisShaders/Iris#1121]
### What happened?

Iris does not render the world in 1.18.1.
This was tested with the Fabric Loader using sodium, phosphorous and Lithium
It was also tested with just the Fabric Loader and Sodium.
The graphics mode was set to fast. I do not know if that had any bearing on the issue
Here is a section of the crash report:
java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
	at net.minecraft.class_4587.method_23760(class_4587.java:65)
	at net.minecraft.class_757.redirect$zja000$iris$saveBobbing(class_757.java:3041)
	at net.minecraft.class_757.method_3188(class_757.java:1025)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Looking at the Developer console it says that it successfully loaded the shaders ( Chocapic13 edit called yofps-low ):
[08:26:33] [Render thread/INFO]: [STDOUT]: Successfully reloaded the world map shaders!

But then appeared to throw the exception here just after loading the world before rendering anything:
[08:26:66] [Render thread/INFO]: [STDOUT]: New world map session initialized!
[08:26:92] [Render thread/INFO]: Started 2 worker threads
[08:26:46] [Render thread/INFO]: Loaded 183 advancements
[08:26:66] [Render thread/FATAL]: Unreported exception thrown!

It then threw the exception I took from the crash report.

This was on a third party launcher on windows 11 on the latest version of Java. The world was single player.
The iris version was mc1.18.1-1.1.3 downloaded from modrinth.

Also Merry Christmas!

### Relevant log output

```shell
[08:26:33] [Render thread/INFO]: [STDOUT]: Successfully reloaded the world map shaders!

[08:26:66] [Render thread/INFO]: [STDOUT]: New world map session initialized!
[08:26:92] [Render thread/INFO]: Started 2 worker threads
[08:26:46] [Render thread/INFO]: Loaded 183 advancements
[08:26:66] [Render thread/FATAL]: Unreported exception thrown!

java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
	at net.minecraft.class_4587.method_23760(class_4587.java:65)
	at net.minecraft.class_757.redirect$zja000$iris$saveBobbing(class_757.java:3041)
	at net.minecraft.class_757.method_3188(class_757.java:1025)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

### Minecraft Version

1.18.1

### Iris Version

mc1.18.1-1.1.3

### Sodium Version

sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar

### Operating System

Windows 11

### What is your GPU?

AMD Radeon

### Java Version

java version "1.8.0_311"  

### Additional context

The shaders used were Chocapic13 edit yofps-low

**Comment by IMS212** [comment]
You are using the 1.18 build of Iris on 1.18.1, which does not work.
