### ISSUE TITLE
Crash Loop

### ISSUE THREAD

**Issue by UltraBlackLinux** [IrisShaders/Iris#114]
Hey, there,
I am having a crash loop with SEUS shaders:
```
java.lang.RuntimeException: Shader compilation failed!
    at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7)
    at net.coderbot.iris.pipeline.ShaderPipeline.createPass(ShaderPipeline.java:252)
...
Caused by: java.io.IOException: Failed to compile fragment shader for program gbuffers_textured
    at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:55)
    at net.coderbot.iris.pipeline.ShaderPipeline.createPass(ShaderPipeline.java:248)
    ... 134 more
Caused by: java.io.IOException: Couldn't compile fragment program (iris, gbuffers_textured.fsh) : 0:245(20): error: initializer of const variable `K_R' must be a constant expression
0:246(20): error: initializer of const variable `K_M' must be a constant expression
    at net.minecraft.client.gl.GlShader.createFromResource(GlShader:62)
    at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:53)
    ... 135 more
    
```
What can I do about this?
Thanks!

**Comment by coderbot16** [comment]
SEUS shaders don't currently work with Iris. Also, SEUS does not support Mac or Intel, so if you're on those platforms you'll need to look into using a different shaderpack.

However, it would be helpful to have a log file.

**Comment by UltraBlackLinux** [comment]
> SEUS shaders don't currently work with Iris. Also, SEUS does not support Mac or Intel, so if you're on those platforms you'll need to look into using a different shaderpack.
> 
> However, it would be helpful to have a log file.

I am on Amd on Linux XD

**Comment by coderbot16** [comment]
Looks like this is a combination of NotEnoughCrashes relentlessly trying to keep the game running after crashes, and Iris handling issues with loading shaderpacks quite poorly.

**Comment by coderbot16** [comment]
Didn't mean to close the issue, I think the best fix to this will just be for Iris to handle shaderpack loading errors more gracefully in all cases.

**Comment by coderbot16** [comment]
This should be fixed - it will still crash, but it shouldn't have a crash loop anymore. The actual crash at hand can be looked into separately, but it is likely something related to SEUS perhaps not supporting Mesa drivers?
