### ISSUE TITLE
TME does not work in the end

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1146]
### What happened?

TME does not work in the end

### Relevant log output

```shell
15:50:39] [Render thread/ERROR]: Couldn't load NewWorldRenderingPipeline, falling back to vanilla shaders.
java.lang.IllegalArgumentException: Framebuffer must have at least one color buffer
	at net.coderbot.iris.rendertarget.RenderTargets.createGbufferFramebuffer(RenderTargets.java:149) ~[iris-mc1.18.1-1.1.3.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.createShader(NewWorldRenderingPipeline.java:378) ~[iris-mc1.18.1-1.1.3.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.createShader(NewWorldRenderingPipeline.java:374) ~[iris-mc1.18.1-1.1.3.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:293) ~[iris-mc1.18.1-1.1.3.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:427) ~[iris-mc1.18.1-1.1.3.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:32) [iris-mc1.18.1-1.1.3.jar:?]
	at net.minecraft.class_761.handler$zjj000$iris$beginLevelRender(class_761.java:5950) [client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1240) [client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1031) [client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:811) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1117) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602) [fabric-loader-0.12.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.9.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

### Minecraft Version

Minecraft 1.18.1

### Iris Version

iris-mc-1.18.1-1.1.4 RC2

### Sodium Version

sodium 0.4 alpha 5

### Operating System

Ubuntu 20.04

### What is your GPU?

GTX 1070

### Java Version

Java 17

**Comment by AlsoSylv** [comment]
TME is currently unsupported, and seems to fail for the same reasons as Chocapic13 in #1030

**Comment by Lolothepro** [comment]
oh, I knew that Chocapic13 might not work for this reason, sorry

**Comment by Lolothepro** [comment]
https://github.com/IrisShaders/Iris/blob/trunk/docs/supportedshaders.md?plain=1#L43

**Comment by Lolothepro** [comment]
Need to be reopened
