### ISSUE TITLE
Crash when the main player takes damage and inventory menu is opened

### ISSUE THREAD

**Issue by thesword53** [IrisShaders/Iris#1168]
### Minecraft Version

Minecraft 1.18.1

### Iris Version

iris-mc1.18.1-1.1.4-rc2+rev.2bd7443.jar (compiled against 2bd744309208548fc46514e72194e63e55589596)

### Sodium Version

sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar

### Operating System

Windows 10

### What is your GPU?

NVIDIA GeForce RTX 2080 SUPER

### Java Version

Java 17

### Reproduction Steps

1. Put an enchanted shield with a banner pattern in your left or right hand
2. Open your inventory
3. Take damage

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 05/01/2022 22:01
Description: Rendering entity in world

java.lang.IllegalArgumentException: Duplicate delegates
	at net.minecraft.class_4720$class_4589.<init>(class_4720.java:29)
	at net.minecraft.class_4720.method_24037(class_4720.java:15)
	at net.minecraft.class_918.method_29711(class_918.java:218)
	at net.minecraft.class_4730.method_30001(class_4730.java:50)
	at net.minecraft.class_823.method_23802(class_823.java:129)
	at net.minecraft.class_756.method_3166(class_756.java:156)
	at net.minecraft.class_918.method_23179(class_918.java:132)
	at net.minecraft.class_918.method_23177(class_918.java:273)
	at net.minecraft.class_759.method_3233(class_759.java:163)
	at net.minecraft.class_989.method_4192(class_989.java:61)
	at net.minecraft.class_5697.method_4192(class_5697.java:32)
	at net.minecraft.class_989.method_17162(class_989.java:40)
	at net.minecraft.class_989.method_4199(class_989.java:15)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_1007.method_4215(class_1007.java:64)
	at net.minecraft.class_1007.method_3936(class_1007.java:42)
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_490.method_29977(class_490.java:152)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1149)
	at net.minecraft.class_490.method_2486(class_490.java:152)
	at net.minecraft.class_490.method_2389(class_490.java:110)
	at net.minecraft.class_465.method_25394(class_465.java:101)
	at net.minecraft.class_485.method_25394(class_485.java:29)
	at net.minecraft.class_490.method_25394(class_490.java:90)
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_4720$class_4589.<init>(class_4720.java:29)
	at net.minecraft.class_4720.method_24037(class_4720.java:15)
	at net.minecraft.class_918.method_29711(class_918.java:218)
	at net.minecraft.class_4730.method_30001(class_4730.java:50)
	at net.minecraft.class_823.method_23802(class_823.java:129)
	at net.minecraft.class_756.method_3166(class_756.java:156)
	at net.minecraft.class_918.method_23179(class_918.java:132)
	at net.minecraft.class_918.method_23177(class_918.java:273)
	at net.minecraft.class_759.method_3233(class_759.java:163)
	at net.minecraft.class_989.method_4192(class_989.java:61)
	at net.minecraft.class_5697.method_4192(class_5697.java:32)
	at net.minecraft.class_989.method_17162(class_989.java:40)
	at net.minecraft.class_989.method_4199(class_989.java:15)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_1007.method_4215(class_1007.java:64)
	at net.minecraft.class_1007.method_3936(class_1007.java:42)
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_490.method_29977(class_490.java:152)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1149)
	at net.minecraft.class_490.method_2486(class_490.java:152)
	at net.minecraft.class_490.method_2389(class_490.java:110)
	at net.minecraft.class_465.method_25394(class_465.java:101)
	at net.minecraft.class_485.method_25394(class_485.java:29)
	at net.minecraft.class_490.method_25394(class_490.java:90)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 226
	Entity Name: Thesword53
	Entity's Exact location: 5.53, 61.00, 8.70
	Entity's Block location: World: (5,61,8), Section: (at 5,13,8 in 0,3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: -0.02, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_490.method_29977(class_490.java:152)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1149)
	at net.minecraft.class_490.method_2486(class_490.java:152)
	at net.minecraft.class_490.method_2389(class_490.java:110)
	at net.minecraft.class_465.method_25394(class_465.java:101)
	at net.minecraft.class_485.method_25394(class_485.java:29)
	at net.minecraft.class_490.method_25394(class_490.java:90)
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_1007@6fa56e19
	Location: 0.00,0.00,0.00 - World: (0,0,0), Section: (at 0,0,0 in 0,0,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_490.method_29977(class_490.java:152)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1149)
	at net.minecraft.class_490.method_2486(class_490.java:152)
	at net.minecraft.class_490.method_2389(class_490.java:110)
	at net.minecraft.class_465.method_25394(class_465.java:101)
	at net.minecraft.class_485.method_25394(class_485.java:29)
	at net.minecraft.class_490.method_25394(class_490.java:90)
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_490
	Mouse location: Scaled: (414, 235). Absolute: (1242.000000, 706.000000)
	Screen size: Scaled: (854, 480). Absolute: (2560, 1440). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Thesword53'/226, l='ClientLevel', x=5.53, y=61.00, z=8.70]]
	Chunk stats: 4096, 1021
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,69,0), Section: (at 0,5,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 138261 game time, 73965 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, thesword_ressources_1_17.zip, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2984562520 bytes (2846 MiB) / 4798283776 bytes (4576 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3,60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2080 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1e81
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9729
	Memory slot #0 capacity (MB): 16384,00
	Memory slot #0 clockSpeed (GHz): 3,20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384,00
	Memory slot #1 clockSpeed (GHz): 3,20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 32689,71
	Virtual memory used (MB): 16401,70
	Swap memory total (MB): 0,00
	Swap memory used (MB): 0,00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.12.11-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 497.29, NVIDIA Corporation
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/thesword_ressources_1_17.zip (incompatible)
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['Thesword53'/226, l='ServerLevel[1.18]', x=5.53, y=61.00, z=8.70]]
	Data Packs: vanilla
```

**Comment by IMS212** [comment]
caused by https://github.com/IrisShaders/Iris/commit/546b5b8d3044ff650f14b3343ad7a3df4e6196af

**Comment by IMS212** [comment]
Reverted the commit for now, since the entityColor code is generally bad and we plan to replace it in the future
