### ISSUE TITLE
Newest versions incompatible with WorldEditCUI

### ISSUE THREAD

**Issue by rlvandaveer** [IrisShaders/Iris#1230]
### Minecraft Version

1.18.1

### Iris Version

iris-mc1.18.1-1.1.4 - iris-mc1.18.1-1.2.0-pre

### Sodium Version

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14

### Operating System

MacOS 12.1

### What is your GPU?

AMD Radeon RX 5700

### Java Version

openjdk 17.0.1 2021-10-19

### Reproduction Steps

Use the command `//hpos1` or`//hpos2` which will cause WorldEditCUI to render a box around the targeted block

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 1/20/22, 4:32 PM
Description: Unexpected error

java.lang.NoSuchMethodError: 'net.coderbot.iris.pipeline.WorldRenderingPipeline net.coderbot.iris.pipeline.PipelineManager.getPipeline()'
	at eu.mikroskeem.worldeditcui.render.IrisPipelineProvider.lineShader(IrisPipelineProvider.java:61)
	at com.mojang.blaze3d.systems.RenderSystem.setShader(RenderSystem.java:1167)
	at eu.mikroskeem.worldeditcui.render.BufferBuilderRenderSink.flush(BufferBuilderRenderSink.java:234)
	at eu.mikroskeem.worldeditcui.render.BufferBuilderRenderSink.apply(BufferBuilderRenderSink.java:81)
	at com.mumfrey.worldeditcui.event.listeners.CUIRenderContext.apply(CUIRenderContext.java:81)
	at com.mumfrey.worldeditcui.render.shapes.Render3DBox.render(Render3DBox.java:67)
	at com.mumfrey.worldeditcui.render.points.PointCube.render(PointCube.java:60)
	at com.mumfrey.worldeditcui.render.region.CuboidRegion.render(CuboidRegion.java:51)
	at com.mumfrey.worldeditcui.WorldEditCUI.renderSelections(WorldEditCUI.java:134)
	at com.mumfrey.worldeditcui.event.listeners.CUIListenerWorldRender.onRender(CUIListenerWorldRender.java:98)
	at eu.mikroskeem.worldeditcui.FabricModWorldEditCUI.onPostRenderEntities(FabricModWorldEditCUI.java:191)
	at eu.mikroskeem.worldeditcui.FabricModWorldEditCUI.lambda$onInitialize$1(FabricModWorldEditCUI.java:109)
	at net.minecraft.class_761.handler$zgc000$onChunkDebugRender(class_761.java:4529)
	at net.minecraft.class_761.method_22710(class_761.java:1554)
	at net.minecraft.class_757.method_3188(class_757.java:1031)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at eu.mikroskeem.worldeditcui.render.IrisPipelineProvider.lineShader(IrisPipelineProvider.java:61)
	at com.mojang.blaze3d.systems.RenderSystem.setShader(RenderSystem.java:1167)
	at eu.mikroskeem.worldeditcui.render.BufferBuilderRenderSink.flush(BufferBuilderRenderSink.java:234)
	at eu.mikroskeem.worldeditcui.render.BufferBuilderRenderSink.apply(BufferBuilderRenderSink.java:81)
	at com.mumfrey.worldeditcui.event.listeners.CUIRenderContext.apply(CUIRenderContext.java:81)
	at com.mumfrey.worldeditcui.render.shapes.Render3DBox.render(Render3DBox.java:67)
	at com.mumfrey.worldeditcui.render.points.PointCube.render(PointCube.java:60)
	at com.mumfrey.worldeditcui.render.region.CuboidRegion.render(CuboidRegion.java:51)
	at com.mumfrey.worldeditcui.WorldEditCUI.renderSelections(WorldEditCUI.java:134)
	at com.mumfrey.worldeditcui.event.listeners.CUIListenerWorldRender.onRender(CUIListenerWorldRender.java:98)
	at eu.mikroskeem.worldeditcui.FabricModWorldEditCUI.onPostRenderEntities(FabricModWorldEditCUI.java:191)
	at eu.mikroskeem.worldeditcui.FabricModWorldEditCUI.lambda$onInitialize$1(FabricModWorldEditCUI.java:109)
	at net.minecraft.class_761.handler$zgc000$onChunkDebugRender(class_761.java:4529)
	at net.minecraft.class_761.method_22710(class_761.java:1554)
	at net.minecraft.class_757.method_3188(class_757.java:1031)

-- Affected level --
Details:
	All players: 1 total; [class_746['HangFire0331'/51097, l='ClientLevel', x=79.54, y=102.00, z=277.86]]
	Chunk stats: 1024, 615
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,113,0), Section: (at 0,1,0 in 0,7,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 180684 game time, 1817236 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, hangfire0331-vanilla-tweaks-1.17, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Mac OS X (x86_64) version 12.1
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 489003688 bytes (466 MiB) / 1845493760 bytes (1760 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.20
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Intel UHD Graphics 630
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 1536.00
	Graphics card #0 deviceId: 0x3e9b
	Graphics card #0 versionInfo: Revision ID: 0x0000, gMux Version: 5.0.0
	Graphics card #1 name: Radeon Pro 555X
	Graphics card #1 vendor: AMD (0x1002)
	Graphics card #1 VRAM (MB): 4096.00
	Graphics card #1 deviceId: 0x67ef
	Graphics card #1 versionInfo: Revision ID: 0x00e3, ROM Revision: 113-C980AL-075, VBIOS Version: 113-C97501P-005, EFI Driver Version: 01.A1.075, gMux Version: 5.0.0
	Graphics card #2 name: AMD Radeon RX 5700
	Graphics card #2 vendor: AMD (0x1002)
	Graphics card #2 VRAM (MB): 8192.00
	Graphics card #2 deviceId: 0x731f
	Graphics card #2 versionInfo: Revision ID: 0x00c4, ROM Revision: 113-EM22G8G-026, gMux Version: 5.0.0
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 33792.00
	Virtual memory used (MB): 13450.72
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 271.00
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.45.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd65
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d2957165
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f365
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9565
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.6+533be9ba65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d9565
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d9565
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a65
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9565
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a765
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f5565
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		iris: Iris 1.2.0-pre
		java: OpenJDK 64-Bit Server VM 17
		lithium: Lithium 0.7.7
		minecraft: Minecraft 1.18.1
		org_anarres_jcpp: jcpp 1.4.14
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		phosphor: Phosphor 0.8.1
		sodium: Sodium 0.4.0-alpha6+build.14
		worldedit: WorldEdit 7.2.8+6008-1246d61
		worldeditcui: WorldEditCUI 1.17.1+01-SNAPSHOT
	Launched Version: fabric-loader-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: AMD Radeon Pro 555X OpenGL Engine GL version 4.1 ATI-4.7.101, ATI Technologies Inc.
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/hangfire0331-vanilla-tweaks-1.17 (incompatible), Fabric Mods
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
```

**Comment by maximumpower55** [comment]
We can't fix this. This is something world edit needs to fix

**Comment by coderbot16** [comment]
Please update to WorldEditCUI 1.18.1+01: https://github.com/EngineHub/WorldEditCUI/releases/tag/1.18.1%2B01

Iris has now flagged the older versions as incompatible: 
- https://github.com/IrisShaders/Iris/commit/b5ae6626327b93e31e717118bcb55423a35cc1e9
- https://github.com/IrisShaders/Iris/commit/cd3174aa37fc76c5233b20f8a3dbdf9eb8d1e538

**Comment by rlvandaveer** [comment]
Thank you. I had been watching that repo for a while but there wasn't much/any activity. This is great.

> Please update to WorldEditCUI 1.18.1+01: https://github.com/EngineHub/WorldEditCUI/releases/tag/1.18.1%2B01
> 
> Iris has now flagged the older versions as incompatible:
> 
> * [b5ae662](https://github.com/IrisShaders/Iris/commit/b5ae6626327b93e31e717118bcb55423a35cc1e9)
> * [cd3174a](https://github.com/IrisShaders/Iris/commit/cd3174aa37fc76c5233b20f8a3dbdf9eb8d1e538)

Thank you. I had been watching that repo for a while but there wasn't much/any activity. This is great.

**Comment by coderbot16** [comment]
You're welcome!
