### ISSUE TITLE
Newest version incompatible with BedrockWaters

### ISSUE THREAD

**Issue by Heamaci** [IrisShaders/Iris#1239]
### Minecraft Version

1.18

### Iris Version

Iris 1.2.0

### Sodium Version

Sodium mc1.18.1-0.4.0-alpha6

### Operating System

Windows 10

### What is your GPU?

gtx 1060 6gb

### Java Version

17

### Reproduction Steps

1. Launch game with both BedrockWaters and Iris 

### Crash Report file and latest.log

```shell
[23:45:54] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[23:45:55] [main/WARN]: Mod resolution failed
[23:45:55] [main/INFO]: Immediate reason: [NEG_HARD_DEP iris 1.2.0-pre {breaks bedrockwaters @ [<=1.6.0]}, ROOT_FORCELOAD_SINGLE bedrockwaters 1.6.0+1.18.1, ROOT_FORCELOAD_SINGLE iris 1.2.0-pre]
[23:45:55] [main/INFO]: Reason: [NEG_HARD_DEP iris 1.2.0-pre {breaks bedrockwaters @ [<=1.6.0]}]
[23:45:55] [main/INFO]: Fix: add [], remove [], replace [[iris 1.2.0-pre] -> add:iris 1 ([(-?,?)])]
[23:45:55] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Iris' (iris) 1.2.0-pre (C:\Users\Heamaci\AppData\Roaming\gdlauncher_next\instances\1.18.1\mods\iris-mc1.18.1-1.2.0-pre.jar) with any version that is compatible with:
		 - bedrockwaters 1.6.0+1.18.1
Unmet dependency listing:
	 - Mod 'Iris' (iris) 1.2.0-pre is incompatible with version 1.6.0 or earlier of mod 'BedrockWaters' (bedrockwaters), but a matching version is present: 1.6.0+1.18.1!
		 - Mod 'BedrockWaters' (bedrockwaters) 1.6.0+1.18.1 is being loaded from C:\Users\Heamaci\AppData\Roaming\gdlauncher_next\instances\1.18.1\mods\bedrockwaters-1.6.0+1.18.1.jar
Inactive mods:
	 - mod 'Iris' (iris) 1.2.0-pre, reason: to replace
	 - mod 'Runtime Resource Pack' (advanced_runtime_resource_pack) 0.4.3, reason: newer version active
	 - mod 'Runtime Resource Pack' (advanced_runtime_resource_pack) 0.5.1, reason: newer version active
	 - mod 'Cloth Basic Math' (cloth-basic-math) 0.5.1, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.0.39, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.0.42, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.0.45, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.1.48, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.1.50, reason: same version active
	 - mod 'Cloth Config v4' (cloth-config2) 4.11.14, reason: unknown
	 - mod 'Cloth Config v4' (cloth-config2) 4.11.26, reason: unknown
	 - mod 'Cloth Config v4' (cloth-config2) 5.0.34, reason: unknown
	 - mod 'Cloth Config v5' (cloth-config2) 5.0.38, reason: unknown
	 - mod 'core' (com_electronwill_night-config_core) 3.6.3, reason: newer version active
	 - mod 'core' (com_electronwill_night-config_core) 3.6.5, reason: same version active
	 - mod 'toml' (com_electronwill_night-config_toml) 3.6.3, reason: newer version active
	 - mod 'toml' (com_electronwill_night-config_toml) 3.6.5, reason: same version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+c88702897d, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446388, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+c88702897d, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.0+65d505fc9c, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cdd0, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd65, reason: newer version active
	 - mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.1.6+3ac43d95c8, reason: newer version active
	 - mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.1.6+3ac43d9565, reason: newer version active
	 - mod 'Fabric Events Interaction (v0)' (fabric-events-interaction-v0) 0.4.16+bfa23f1765, reason: newer version active
	 - mod 'Fabric Item API (v1)' (fabric-item-api-v1) 1.3.0+691a79b5c8, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.5+65d505fc9c, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.8+c8aba2f314, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.8+c8aba2f3c8, reason: newer version active
	 - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.4.10+c15ca33565, reason: newer version active
	 - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.18+3ac43d9565, reason: newer version active
	 - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.4+7242e9d7c8, reason: newer version active
	 - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d95c8, reason: newer version active
	 - mod 'Fabric Rendering (v1)' (fabric-rendering-v1) 1.10.3+6b21378ac8, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.8+a00e834b88, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.9+65d505fc9c, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9565, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.4+cbda931888, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.7+3ac43d95c8, reason: newer version active
	 - mod 'Fabric Tag Extensions (v0)' (fabric-tag-extensions-v0) 1.2.5+3ac43d9565, reason: newer version active
	 - mod 'Mod Menu' (modmenu) 3.0.1, reason: newer version active
	 - mod 'jcpp' (org_anarres_jcpp) 1.4.14, reason: inactive parent mod (nested jar)
	 - mod 'slf4j-api' (org_slf4j_slf4j-api) 1.7.12, reason: inactive parent mod (nested jar)
	 - mod 'ThonkUtil' (thonkutil) 1.3, reason: same version active
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Iris' (iris) 1.2.0-pre (C:\Users\Heamaci\AppData\Roaming\gdlauncher_next\instances\1.18.1\mods\iris-mc1.18.1-1.2.0-pre.jar) with any version that is compatible with:
		 - bedrockwaters 1.6.0+1.18.1
Unmet dependency listing:
	 - Mod 'Iris' (iris) 1.2.0-pre is incompatible with version 1.6.0 or earlier of mod 'BedrockWaters' (bedrockwaters), but a matching version is present: 1.6.0+1.18.1!
		 - Mod 'BedrockWaters' (bedrockwaters) 1.6.0+1.18.1 is being loaded from C:\Users\Heamaci\AppData\Roaming\gdlauncher_next\instances\1.18.1\mods\bedrockwaters-1.6.0+1.18.1.jar
Inactive mods:
	 - mod 'Iris' (iris) 1.2.0-pre, reason: to replace
	 - mod 'Runtime Resource Pack' (advanced_runtime_resource_pack) 0.4.3, reason: newer version active
	 - mod 'Runtime Resource Pack' (advanced_runtime_resource_pack) 0.5.1, reason: newer version active
	 - mod 'Cloth Basic Math' (cloth-basic-math) 0.5.1, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.0.39, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.0.42, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.0.45, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.1.48, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.1.50, reason: same version active
	 - mod 'Cloth Config v4' (cloth-config2) 4.11.14, reason: unknown
	 - mod 'Cloth Config v4' (cloth-config2) 4.11.26, reason: unknown
	 - mod 'Cloth Config v4' (cloth-config2) 5.0.34, reason: unknown
	 - mod 'Cloth Config v5' (cloth-config2) 5.0.38, reason: unknown
	 - mod 'core' (com_electronwill_night-config_core) 3.6.3, reason: newer version active
	 - mod 'core' (com_electronwill_night-config_core) 3.6.5, reason: same version active
	 - mod 'toml' (com_electronwill_night-config_toml) 3.6.3, reason: newer version active
	 - mod 'toml' (com_electronwill_night-config_toml) 3.6.5, reason: same version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+c88702897d, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446388, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+c88702897d, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.0+65d505fc9c, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cdd0, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd65, reason: newer version active
	 - mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.1.6+3ac43d95c8, reason: newer version active
	 - mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.1.6+3ac43d9565, reason: newer version active
	 - mod 'Fabric Events Interaction (v0)' (fabric-events-interaction-v0) 0.4.16+bfa23f1765, reason: newer version active
	 - mod 'Fabric Item API (v1)' (fabric-item-api-v1) 1.3.0+691a79b5c8, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.5+65d505fc9c, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.8+c8aba2f314, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.8+c8aba2f3c8, reason: newer version active
	 - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.4.10+c15ca33565, reason: newer version active
	 - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.18+3ac43d9565, reason: newer version active
	 - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.4+7242e9d7c8, reason: newer version active
	 - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d95c8, reason: newer version active
	 - mod 'Fabric Rendering (v1)' (fabric-rendering-v1) 1.10.3+6b21378ac8, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.8+a00e834b88, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.9+65d505fc9c, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9565, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.4+cbda931888, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.7+3ac43d95c8, reason: newer version active
	 - mod 'Fabric Tag Extensions (v0)' (fabric-tag-extensions-v0) 1.2.5+3ac43d9565, reason: newer version active
	 - mod 'Mod Menu' (modmenu) 3.0.1, reason: newer version active
	 - mod 'jcpp' (org_anarres_jcpp) 1.4.14, reason: inactive parent mod (nested jar)
	 - mod 'slf4j-api' (org_slf4j_slf4j-api) 1.7.12, reason: inactive parent mod (nested jar)
	 - mod 'ThonkUtil' (thonkutil) 1.3, reason: same version active
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187) ~[fabric-loader-0.12.12.jar:?]
	... 3 more
```

### Additional context

It was compatible with the public beta versions from the discord, seems like the curseforge release broke compatiblity somehow.

**Comment by coderbot16** [comment]
This is not our bug. BedrockWaters has severe chunk loading issues with the more recent versions of Sodium (perhaps only when paired with Iris), and we've marked it as incompatible until it gets an update that fixes the issues.

See https://github.com/2Retr0/BedrockWaters/pull/12
