### ISSUE TITLE
Game crashing when using tab on servers

### ISSUE THREAD

**Issue by SushiLord** [IrisShaders/Iris#1273]
### What happened?

Game crashing when using "tab" on servers.
ye that's it

### Screenshots

![image](https://user-images.githubusercontent.com/99326831/153181119-cbb9eaa1-2ae8-4fd3-a3b8-1727e3845e6b.png)

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Why did you do that?

Time: 09/02/2022 11:11
Description: Rendering entity in world

com.mojang.authlib.minecraft.InsecureTextureException: Signature is missing from textures payload
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getTextures(YggdrasilMinecraftSessionService.java:144)
	at net.minecraft.client.texture.PlayerSkinProvider.handler$bhl000$loadSkin(PlayerSkinProvider:521)
	at net.minecraft.client.texture.PlayerSkinProvider.loadSkin(PlayerSkinProvider)
	at net.minecraft.client.network.PlayerListEntry.loadTextures(PlayerListEntry:106)
	at net.minecraft.client.network.PlayerListEntry.getSkinTexture(PlayerListEntry:78)
	at net.minecraft.client.network.AbstractClientPlayerEntity.getSkinTexture(AbstractClientPlayerEntity:84)
	at net.minecraft.client.render.entity.PlayerEntityRenderer.getTexture(PlayerEntityRenderer:143)
	at net.minecraft.client.render.entity.PlayerEntityRenderer.getTexture(PlayerEntityRenderer:42)
	at net.minecraft.client.render.entity.LivingEntityRenderer.getRenderLayer(LivingEntityRenderer:155)
	at net.minecraft.client.render.entity.LivingEntityRenderer.render(LivingEntityRenderer:136)
	at net.minecraft.client.render.entity.PlayerEntityRenderer.render(PlayerEntityRenderer:64)
	at net.minecraft.client.render.entity.PlayerEntityRenderer.render(PlayerEntityRenderer:42)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:135)
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer:1577)
	at net.minecraft.client.render.WorldRenderer.invokeRenderEntity(WorldRenderer)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderEntities(ShadowRenderer.java:583)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:482)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:506)
	at net.minecraft.client.render.WorldRenderer.handler$zop000$iris$renderTerrainShadows(WorldRenderer:6470)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1253)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1031)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:811)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1117)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at net.minecraft.client.main.Main.main(Main:238)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getTextures(YggdrasilMinecraftSessionService.java:144)
	at net.minecraft.class_1071.handler$bhl000$loadSkin(class_1071.java:521)
	at net.minecraft.class_1071.method_4652(class_1071.java)
	at net.minecraft.class_640.method_2969(class_640.java:106)
	at net.minecraft.class_640.method_2968(class_640.java:78)
	at net.minecraft.class_742.method_3117(class_742.java:84)
	at net.minecraft.class_1007.method_4216(class_1007.java:143)
	at net.minecraft.class_1007.method_3931(class_1007.java:42)
	at net.minecraft.class_922.method_24302(class_922.java:155)
	at net.minecraft.class_922.method_4054(class_922.java:136)
	at net.minecraft.class_1007.method_4215(class_1007.java:64)
	at net.minecraft.class_1007.method_3936(class_1007.java:42)
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1577)
	at net.minecraft.class_761.invokeRenderEntity(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderEntities(ShadowRenderer.java:583)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:482)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:506)
	at net.minecraft.class_761.handler$zop000$iris$renderTerrainShadows(class_761.java:6470)
	at net.minecraft.class_761.method_22710(class_761.java:1253)
	at net.minecraft.class_757.method_3188(class_757.java:1031)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.class_745)
	Entity ID: 99
	Entity Name: _Guzzyyyyy
	Entity's Exact location: -16.20, 104.00, -37.37
	Entity's Block location: World: (-17,104,-38), Section: (at 15,8,10 in -2,6,-3; chunk contains blocks -32,0,-48 to -17,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {AbsorptionAmount:0.0f,ActiveEffects:[{Ambient:1b,Amplifier:0b,Duration:32759,Id:1b,ShowIcon:1b,ShowParticles:1b}],Air:300s,Attributes:[{Base:20.0d,Name:"minecraft:generic.max_health"},{Base:0.10000000149011612d,Name:"minecraft:generic.movement_speed"}],Brain:{memories:{}},DataVersion:2865,DeathTime:0s,EnderItems:[],FallDistance:0.0f,FallFlying:0b,Fire:0s,Health:20.0f,HurtByTimestamp:0,HurtTime:0s,Inventory:[{Count:1b,Slot:0b,id:"minecraft:compass",tag:{display:{Lore:['{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Right-click to select your realm!"}],"text":""}'],Name:'{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Realm Selector"}],"text":""}'},hotbarItem:"server_selector"}}],Invulnerable:0b,Motion:[0.0d,0.0d,0.0d],OnGround:1b,PortalCooldown:0,Pos:[-16.196533203125d,104.0d,-37.368896484375d],Rotation:[-90.0f,9.84375f],Score:0,SelectedItemSlot:0,SleepTimer:0s,UUID:[I;0,0,590328,-1642183429],XpLevel:0,XpP:0.0f,XpSeed:0,XpTotal:0,abilities:{flySpeed:0.05f,flying:0b,instabuild:0b,invulnerable:0b,mayBuild:1b,mayfly:0b,walkSpeed:0.1f},foodExhaustionLevel:0.0f,foodLevel:20,foodSaturationLevel:5.0f,foodTickTimer:0}
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1577)
	at net.minecraft.class_761.invokeRenderEntity(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderEntities(ShadowRenderer.java:583)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:482)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:506)
	at net.minecraft.class_761.handler$zop000$iris$renderTerrainShadows(class_761.java:6470)
	at net.minecraft.class_761.method_22710(class_761.java:1253)
	at net.minecraft.class_757.method_3188(class_757.java:1031)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_1007@358529ff
	Location: -16.70,-2.62,3.13 - World: (-17,-3,3), Section: (at 15,13,3 in -2,-1,0; chunk contains blocks -32,0,0 to -17,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: -90.0
	Delta: 4.7683716E-6
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1577)
	at net.minecraft.class_761.invokeRenderEntity(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderEntities(ShadowRenderer.java:583)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:482)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:506)
	at net.minecraft.class_761.handler$zop000$iris$renderTerrainShadows(class_761.java:6470)
	at net.minecraft.class_761.method_22710(class_761.java:1253)
	at net.minecraft.class_757.method_3188(class_757.java:1031)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 2 total; [class_746['LordOfCheaters'/100, l='ClientLevel', x=0.50, y=105.00, z=-40.50], class_745['_Guzzyyyyy'/99, l='ClientLevel', x=-16.20, y=104.00, z=-37.37]]
	Chunk stats: 1024, 62
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,106,-41), Section: (at 0,10,7 in 0,6,-3; chunk contains blocks 0,0,-48 to 15,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 169933 game time, 12000 day time
	Server brand: Paper (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, 3d-totem-player-model, VanillaTweaks_r522006.zip, better netherite, Fabric Mods, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1032268680 bytes (984 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3,60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1f82
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5709
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 2,67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 32699,50
	Virtual memory used (MB): 13498,22
	Swap memory total (MB): 16384,00
	Swap memory used (MB): 70,50
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancementplaques: Advancement Plaques 1.4.3
		amecsapi: Amecs API 1.3.3+mc1.18-pre1
		appleskin: AppleSkin mc1.18-2.2.0
		architectury: Architectury 3.6.15
		armorchroma: Armor Chroma 1.2.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		coat: Coat 1.0.0-beta.15
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		cool_elytra: Cool Elytra 1.3.1
		crowdin-translate: CrowdinTranslate 1.4+1.18
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.18
		ecs: Elytra/Chestplate Swapper 1.2.0-MC1.18
		effective: Effective 1.1
		fabric: Fabric API 0.45.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd65
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d2957165
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f365
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9565
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.6+533be9ba65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d9565
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d9565
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a65
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9565
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a765
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f5565
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		forgeconfigapiport: Forge Config API Port 3.1.1
		iceberg: Iceberg 1.0.38
		inventoryhud: Inventory HUD + 3.4.2
		iris: Iris 1.2.0-rc1
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.1.0+1.17
		legendarytooltips: Legendary Tooltips 1.2.2
		litematica: Litematica 0.0.0-dev.20211203.013300
		malilib: MaLiLib 0.10.0-dev.26
		me_hypherionmc_simple-rpc-common: simple-rpc-common 1.0.17
		midnightlib: MidnightLib 0.3.1
		minecraft: Minecraft 1.18.1
		minecraftcapes: MinecraftCapes Mod 12.0.2
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 3.0.1
		mousewheelie: Mouse Wheelie 1.8.0+mc1.18-pre5
		notenoughanimations: NotEnoughAnimations 1.4.0
		notenoughcrashes: Not Enough Crashes 4.1.4+1.18.1
		org_anarres_jcpp: jcpp 1.4.14
		org_apache_httpcomponents_httpclient: httpclient 4.5.10
		org_apache_httpcomponents_httpcore: httpcore 4.4.12
		org_apache_httpcomponents_httpmime: httpmime 4.5.10
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		pride: Pride Lib 1.1.0+1.17
		randomblockplacement: RandomBlockPlacement 1.18-fabric0.43.1-1.1.2
		replaymod: Replay Mod 1.18.1-2.6.3
		roughlyenoughitems: Roughly Enough Items 7.1.390
		shulkerboxtooltip: Shulker Box Tooltip 3.0.5+1.18
		simple-rpc: Simple Rpc 2.7.1
		skinlayers: 3d Skin Layers 1.3.1
		skinswapper: Skin Swapper 3.0.0
		slotlock: SlotLock 1.0.4-BETA+1.18
		sodium: Sodium 0.4.0-alpha6+build.14
		spruceui: SpruceUI 3.3.0+1.17
		tweed4_annotated: tweed4_annotated 1.2.0
		tweed4_base: tweed4_base 1.3.1
		tweed4_data: tweed4_data 1.2.0
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.2
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.2
		waveycapes: WaveyCapes 1.0.4
		worldedit: WorldEdit 7.2.8+6008-1246d61
	Launched Version: fabric-loader-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1650/PCIe/SSE2 GL version 3.2.0 NVIDIA 457.09, NVIDIA Corporation
	Window size: 1920x1057
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/3d-totem-player-model, file/VanillaTweaks_r522006.zip, file/better netherite, Fabric Mods
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Iris (iris)
```

### Minecraft Version

Minecraft 1.18.1

### Iris Version

iris-mc1.18.1-1.2.0-pre

### Sodium Version

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14

### Operating System

Windows 10

### What is your GPU?

NVIDIA GeForce GTX 1650

### Java Version

Java 16

### Additional context

Im using some mods :  NOTE : **Only Iris is responsible for the crash, this list is for information only** :

Worldedit 7.2.8
WaveyCapes fabric 1.0.4-mc1.18-pre1
sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14
slotlock-1.0.4-BETA+1.18
simple-rpc-fabruc-1.18.x-2.7.1
skin-swapper-fabric-3.0.0
shulkerboxtooltip-3.0.5+1.18
RoughlyEnoughItems-7.1.390
replaymod-1.18.1-2.6.3
notenoughcrashes-4.1.4+1.18.1
randomblockplacement-1.18fabric0.43.1-1.1.2
notenoughanimations-fabric-1.4.0-mc1.18-pre1
mousewheelie-1.8.0+mc1.18-pre5
modmenu-3.0.1
MinecraftCapes+Fabric+1.18.1-12.0.2
malilib-fabric-1.18.0-0.10.0-dev.26
litematica-fabric-1.18.0-0.0.0-dev.20211203.013300
LegendaryTooltips-1.18.1-fabric-1.2.2
lambdynamiclights-2.1.0+1.17
InventoryHUD-fabric-[1.18]+-3.4.2
Iceberg-1.18.1-fabric-1.0.38
ForgeConfigAPIPort-v3.1.1-1.18.1-Fabric
fabric-api-0.45.0+1.18
elytra-chestplate-swapper-1.2.1-MC1.18
effective-1.1
DynamicSoundFilters-1.3.0+1.18
cool_elytra-1.3.1
cloth-config-6.1.48-fabric
armorchroma-1.2.0
architectury-3.6.15
appleskin-fabric-mc1.18-2.2.0
AdvancementPlaques-1.18-fabric-1.4.3
3dSkinLayers-Fabric-1.3.1

and iris-mc1.18.1-1.2.0-pre

**Comment by SushiLord** [comment]
NOTE : you can fix this by removing Iris, launch your minecraft without it, join a server, quit, quit minecraft, put iris back and it works fine until you hit tab

**Comment by NoComment1105** [comment]
Could you provide a log without Not Enough Crashes please. It's far easier for us to read the log and get the information we need without it.

**Comment by coderbot16** [comment]
Thinking about it more, this is almost certainly just Iris triggering some underlying race condition or other issue in Skin Layers 3D. Please report it there.

**Comment by SushiLord** [comment]
well it seems to have fixed itself, im using the same mod list and now it works, strange
thanks for helping
