### ISSUE TITLE
Some shader packs don't work

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1276]
### What happened?

Some shader packs don't work

### Relevant log output

```shell
[20:39:29] [Render thread/ERROR]: Failed to load the shaderpack "DrDestens.MinecraftShaders.v1.5.4.zip"!
[20:39:29] [Render thread/ERROR]: Catching
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at net.coderbot.iris.shaderpack.include.IncludeProcessor.process(IncludeProcessor.java:51) ~[iris-mc22w06a-1.2.1-preb9f7b136.jar:?]
	at net.coderbot.iris.shaderpack.include.IncludeProcessor.getIncludedFile(IncludeProcessor.java:26) ~[iris-mc22w06a-1.2.1-preb9f7b136.jar:?]
	at net.coderbot.iris.shaderpack.ShaderPack.lambda$new$3(ShaderPack.java:148) ~[iris-mc22w06a-1.2.1-preb9f7b136.jar:?]
	at net.coderbot.iris.shaderpack.ProgramSet.readProgramSource(ProgramSet.java:295) ~[iris-mc22w06a-1.2.1-preb9f7b136.jar:?]
	at net.coderbot.iris.shaderpack.ProgramSet.readProgramSource(ProgramSet.java:287) ~[iris-mc22w06a-1.2.1-preb9f7b136.jar:?]
	at net.coderbot.iris.shaderpack.ProgramSet.readProgramArray(ProgramSet.java:106) ~[iris-mc22w06a-1.2.1-preb9f7b136.jar:?]
	at net.coderbot.iris.shaderpack.ProgramSet.<init>(ProgramSet.java:87) ~[iris-mc22w06a-1.2.1-preb9f7b136.jar:?]
	at net.coderbot.iris.shaderpack.ShaderPack.loadOverrides(ShaderPack.java:222) ~[iris-mc22w06a-1.2.1-preb9f7b136.jar:?]
	at net.coderbot.iris.shaderpack.ShaderPack.<init>(ShaderPack.java:179) ~[iris-mc22w06a-1.2.1-preb9f7b136.jar:?]
	at net.coderbot.iris.Iris.loadExternalShaderpack(Iris.java:283) [iris-mc22w06a-1.2.1-preb9f7b136.jar:?]
	at net.coderbot.iris.Iris.loadShaderpack(Iris.java:207) [iris-mc22w06a-1.2.1-preb9f7b136.jar:?]
	at net.coderbot.iris.Iris.onRenderSystemInit(Iris.java:134) [iris-mc22w06a-1.2.1-preb9f7b136.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.handler$zbk000$iris$onRendererInit(RenderSystem.java:1948) [client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem.java:833) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:497) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:197) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

### Minecraft Version

Minecraft 1.18.1

### Iris Version

iris-mc-1.2.0-1.18.1

### Sodium Version

sodium 0.4 alpha 6

### Operating System

Ubuntu 20.04

### What is your GPU?

GTX 1070

### Java Version

Java 17

**Comment by NoComment1105** [comment]
Essentially a direct duplicate of #1030. Closing for this reason

**Comment by Lolothepro** [comment]
but DrDestens is not listed?

**Comment by NoComment1105** [comment]
It does not warrant an entirely different issue though. Adding a comment to the other issue would have sufficed.

**Comment by coderbot16** [comment]
Reopening because this appears to have a traceable crash report which I want to address. Once it's addressed I'll merge into #1030.

**Comment by coderbot16** [comment]
DrDesten's shaders still fail to load since https://github.com/DrDesten/DrDestens_McShader/commit/98abf260fb9b55420075b1786781d77f329206c3 has not been released yet, but the issue on the side of Iris has been resolved.
