### ISSUE TITLE
WHICH VERSION OF IRIS IS COMPATIBLE WITH COLOMATIC 2.40

### ISSUE THREAD

**Issue by DeezYeet198** [IrisShaders/Iris#1292]
### Minecraft Version

1.18.1

### Iris Version

NONE

### Sodium Version

NONE

### Operating System

WINDOWS 11

### What is your GPU?

INTEL(R) IRIS(R) XE GRAPHICS

### Java Version

JAVA 16 (IDK)

### Reproduction Steps

I just launch and this pop up shows

### Crash Report file and latest.log

```shell
ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
Replace mod 'Iris' (iris) 1.2.0-pre (C:\Users\Aryan Manegar\AppData\Roaming\.minecraft\mods\iris-mc1.18.1-1.2.0-pre.jar) with any version that is compatible with:
colormatic 2.4.0+mc.1.18
Unmet dependency listing:
Mod 'Iris' (iris) 1.2.0-pre is incompatible with version 3.0.0 or earlier of mod 'Colormatic' (colormatic), but a matching version is present: 2.4.0+mc.1.18!
Mod 'Colormatic' (colormatic) 2.4.0+mc.1.18 is being loaded from C:\Users\Aryan Manegar\AppData\Roaming\.minecraft\mods\colormatic-2.4.0+mc.1.18.jar
Mod 'ViaFabric for 1.14' (viafabric-mc114) 0.4.5+244-main requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
'Minecraft' (minecraft) 1.18.1 is an environment reference and usually requires installation or launcher changes to adjust
Mod 'ViaFabric for 1.15' (viafabric-mc115) 0.4.5+244-main requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
'Minecraft' (minecraft) 1.18.1 is an environment reference and usually requires installation or launcher changes to adjust
Mod 'ViaFabric for 1.16' (viafabric-mc116) 0.4.5+244-main requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
'Minecraft' (minecraft) 1.18.1 is an environment reference and usually requires installation or launcher changes to adjust
Mod 'ViaFabric for 1.17' (viafabric-mc117) 0.4.5+244-main requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
'Minecraft' (minecraft) 1.18.1 is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
mod 'Advancement Plaques' (advancementplaques) 1.4.3, reason: newer version active
mod 'Better Third Person' (betterthirdperson) 1.5.4, reason: newer version active
mod 'Chat Heads' (chat_heads) 0.5.1, reason: newer version active
mod 'Cloth Config v6' (cloth-config) 6.1.48, reason: newer version active
mod 'Clumps' (clumps) 8.0.3, reason: newer version active
mod 'Equipment Compare' (equipmentcompare) 1.2.9, reason: newer version active
mod 'Iris' (iris) 1.2.0-pre, reason: to replace
mod 'Runtime Resource Pack' (advanced_runtime_resource_pack) 0.5.4, reason: same version active
mod 'jankson' (blue_endless_jankson) 1.2.1, reason: same version active
mod 'Cloth Basic Math' (cloth-basic-math) 0.5.1, reason: newer version active
mod 'Cloth Config v6' (cloth-config) 6.0.42, reason: newer version active
mod 'Cloth Config v6' (cloth-config) 6.0.45, reason: newer version active
mod 'Cloth Config v6' (cloth-config) 6.1.48, reason: newer version active
mod 'Cloth Config v4' (cloth-config2) 5.0.34, reason: unknown
mod 'Cloth Config v5' (cloth-config2) 5.0.38, reason: unknown
mod 'Fabric API Base' (fabric-api-base) 0.3.0+c88702897d, reason: newer version active
mod 'Fabric API Base' (fabric-api-base) 0.4.0+65d505fc9c, reason: newer version active
mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active
mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cdc8, reason: newer version active
mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.1.6+3ac43d95c8, reason: newer version active
mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.1.6+3ac43d9514, reason: newer version active
mod 'Fabric Events Interaction (v0)' (fabric-events-interaction-v0) 0.4.13+65d505fc9c, reason: newer version active
mod 'Fabric Item API (v1)' (fabric-item-api-v1) 1.2.5+65d505fc9c, reason: newer version active
mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.5+65d505fc9c, reason: newer version active
mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.8+c8aba2f3c8, reason: newer version active
mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.4.7+65d505fc9c, reason: newer version active
mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.4.10+c15ca335c8, reason: newer version active
mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.16+65d505fc9c, reason: newer version active
mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.18+3ac43d95c8, reason: newer version active
mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.4+7242e9d7c8, reason: newer version active
mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d95c8, reason: newer version active
mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.8+a00e834b0a, reason: newer version active
mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.9+65d505fc9c, reason: newer version active
mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d95c8, reason: newer version active
mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.7+3ac43d95c8, reason: newer version active
mod 'Fabric Tag Extensions (v0)' (fabric-tag-extensions-v0) 1.2.3+65d505fc9c, reason: newer version active
mod 'Fabric Tool Attribute API (v1)' (fabric-tool-attribute-api-v1) 1.3.1+5521a5619c, reason: newer version active
mod 'MidnightLib' (midnightlib) 0.2.9, reason: newer version active
mod 'jcpp' (org_anarres_jcpp) 1.4.14, reason: inactive parent mod (nested jar)
mod 'slf4j-api' (org_slf4j_slf4j-api) 1.7.12, reason: inactive parent mod (nested jar)
mod 'ViaFabric for 1.14' (viafabric-mc114) 0.4.5+244-main, reason: unknown
mod 'ViaFabric for 1.15' (viafabric-mc115) 0.4.5+244-main, reason: unknown
mod 'ViaFabric for 1.16' (viafabric-mc116) 0.4.5+244-main, reason: unknown
mod 'ViaFabric for 1.17' (viafabric-mc117) 0.4.5+244-main, reason: unknown
mod 'ViaFabric for 1.8' (viafabric-mc18) 0.4.5+244-main, reason: unknown
<html>at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)<br/>at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)<br/>at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)<br/>at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)<br/>at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)<br/>at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)<br/>at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)</html>
```

**Comment by coderbot16** [comment]
Update to Colormatic 3.1.0

https://modrinth.com/mod/colormatic/versions
