### ISSUE TITLE
JCPP: Properties pre-processing failed (Bad token)

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1295]
### What happened?

Well, this is written in the logs with some shaders

### Relevant log output

```shell
org.anarres.cpp.InternalException: Bad token [#@15,167]:"#"
	at org.anarres.cpp.Preprocessor._token(Preprocessor.java:1919) ~[org_anarres_jcpp-1.4.14-443d06952b2fc491.jar:?]
	at org.anarres.cpp.Preprocessor.token(Preprocessor.java:2144) ~[org_anarres_jcpp-1.4.14-443d06952b2fc491.jar:?]
	at net.coderbot.iris.shaderpack.preprocessor.PropertiesPreprocessor.process(PropertiesPreprocessor.java:85) ~[iris-mc1.18.1-1.2.1-pre.jar:?]
	at net.coderbot.iris.shaderpack.preprocessor.PropertiesPreprocessor.preprocessSource(PropertiesPreprocessor.java:48) ~[iris-mc1.18.1-1.2.1-pre.jar:?]
	at net.coderbot.iris.shaderpack.ShaderProperties.<init>(ShaderProperties.java:77) ~[iris-mc1.18.1-1.2.1-pre.jar:?]
	at net.coderbot.iris.shaderpack.ShaderPack.lambda$new$0(ShaderPack.java:109) ~[iris-mc1.18.1-1.2.1-pre.jar:?]
	at java.util.Optional.map(Optional.java:260) [?:?]
	at net.coderbot.iris.shaderpack.ShaderPack.<init>(ShaderPack.java:109) [iris-mc1.18.1-1.2.1-pre.jar:?]
	at net.coderbot.iris.Iris.loadExternalShaderpack(Iris.java:283) [iris-mc1.18.1-1.2.1-pre.jar:?]
	at net.coderbot.iris.Iris.loadShaderpack(Iris.java:207) [iris-mc1.18.1-1.2.1-pre.jar:?]
	at net.coderbot.iris.Iris.onRenderSystemInit(Iris.java:134) [iris-mc1.18.1-1.2.1-pre.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.handler$zpi000$iris$onRendererInit(RenderSystem.java:1926) [client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem.java:811) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:498) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:199) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

### Minecraft Version

Minecraft 1.18

### Iris Version

iris-mc-1.18.1-1.2.1

### Sodium Version

sodium 0.4 alpha 6

### Operating System

Ubuntu 20.04

### What is your GPU?

GTX 1070

### Java Version

Java 17

**Comment by coderbot16** [comment]
What shader does this happen with?

**Comment by Lolothepro** [comment]
Oceano Shaders 3.0.1
