### ISSUE TITLE
Shaders tilt my game.

### ISSUE THREAD

**Issue by efjnsamdg** [IrisShaders/Iris#1337]
### What happened?

Whenever I turn on shaders my entire perspective tilts.
   Shaderpack : SEUS Renewed

### Screenshots

-A screenshot of my perspective
![Error](https://user-images.githubusercontent.com/102440803/160261390-6269a9ad-0d5b-492a-8850-7d1547390261.png)

### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.2.2-build.32

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15

### Operating System

Windows 10

### What is your GPU?

Radeon RX 5500 XT

### Java Version

Java 17.0.2

### Additional context

MultiMc Log:
[log.txt](https://github.com/IrisShaders/Iris/files/8356565/log.txt)

Minecraft log: 

[19:24:03] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[19:24:03] [main/WARN]: Warnings were found!
 - Mod 'BetterF3' (betterf3) 1.2.3 recommends version 3.0.0 or later of modmenu, which is missing!
	 - You should install version 3.0.0 or later of modmenu for the optimal experience.
[19:24:03] [main/INFO]: Loading 62 mods:
	- betterf3 1.2.3
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.0.42 via betterf3
	- com_electronwill_night-config_core 3.6.5 via mcxr-core
	- com_electronwill_night-config_toml 3.6.5 via mcxr-core
	- essential-container 1.0.0
	- essential-loader 1.0.0 via essential-container
	- fabric 0.48.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.5.7+d7c144a860 via fabric
	- fabric-biome-api-v1 8.0.3+801ec85b60 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.2+d82b939260 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.13+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.3.3+691a79b560 via fabric
	- fabric-item-groups-v0 0.3.10+3ac43d9560 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-lifecycle-events-v1 2.0.2+2540745460 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.0.4+d1027f7d60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.0.3+40c91ec860 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.4.17+d8c7b9ae60 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.2+d1027f7d60 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.1.14+40c91ec860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.5.14+cca23f9360 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+40c91ec860 via fabric
	- fabricloader 0.13.3
	- fallingleaves 1.10.0+1.18.2
	- fart 1.0.0 via mcxr-play
	- iris 1.2.2-build.32
	- java 17
	- lithium 0.7.9
	- mcxr-core 0.2.1
	- mcxr-play 0.2.1
	- minecraft 1.18.2
	- org_anarres_jcpp 1.4.14 via iris
	- org_joml_joml 1.10.4 via mcxr-core
	- phosphor 0.8.1
	- sodium 0.4.1+build.15
[19:24:03] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/MultiMC/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[19:24:12] [main/INFO]: Compatibility level set to JAVA_17
[19:24:12] [main/INFO]: Loaded configuration file for Lithium: 100 options available, 0 override(s) found
[19:24:12] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[19:24:13] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[19:24:14] [main/WARN]: Registration of InjectionPoint ESSENTIAL:AFTER_INVOKE_IN_INIT with gg.essential.mixins.injection.points.AfterInvokeInInit without specifying namespace is deprecated.
[19:24:14] [main/WARN]: Registration of InjectionPoint ESSENTIAL:CONSTANT_IN_INIT with gg.essential.mixins.injection.points.BeforeConstantInInit without specifying namespace is deprecated.
[19:24:14] [main/WARN]: Error loading class: net/labymod/addons/custommainmenu/mainmenu/MenuImplementation (java.lang.ClassNotFoundException: net/labymod/addons/custommainmenu/mainmenu/MenuImplementation)
[19:24:14] [main/WARN]: Error loading class: games/thecodewarrior/bitfont/data/BitGrid (java.lang.ClassNotFoundException: games/thecodewarrior/bitfont/data/BitGrid)
[19:24:14] [main/WARN]: Error loading class: net/minecraftcapes/player/render/CapeLayer (java.lang.ClassNotFoundException: net/minecraftcapes/player/render/CapeLayer)
[19:24:14] [main/WARN]: Error loading class: net/minecraftcapes/player/render/Deadmau5 (java.lang.ClassNotFoundException: net/minecraftcapes/player/render/Deadmau5)
[19:24:14] [main/WARN]: Error loading class: dev/tr7zw/notenoughanimations/logic/ArmTransformer (java.lang.ClassNotFoundException: dev/tr7zw/notenoughanimations/logic/ArmTransformer)
[19:24:14] [main/WARN]: Error loading class: codes/biscuit/skyblockaddons/features/tablist/TabListRenderer (java.lang.ClassNotFoundException: codes/biscuit/skyblockaddons/features/tablist/TabListRenderer)
[19:24:14] [main/WARN]: MixinEnvironment::addTransformerExclusion is deprecated!
[19:24:14] [main/WARN]: MixinEnvironment::addTransformerExclusion is deprecated!
[19:24:14] [main/WARN]: MixinEnvironment::addTransformerExclusion is deprecated!
[19:24:14] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[19:24:15] [main/WARN]: Failed to add PDH Counter: \Paging File(_Total)\% Usage, Error code: 0xC0000BB8
[19:24:15] [main/WARN]: Failed to add counter for PDH counter: \Paging File(_Total)\% Usage
[19:24:15] [main/WARN]: Disabling further attempts to query Paging File.
[19:24:21] [main/WARN]: COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile
[19:24:22] [main/INFO]: mixins.essential.json:entity.player.EntityPlayerAccessor->@Accessor[FIELD_GETTER]::getPlayerModelFlag()Lnet/minecraft/class_2940; should be static as its target is
[19:24:25] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zdh000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[19:24:29] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[19:24:29] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:24:30] [Render thread/INFO]: Setting user: T360
[19:24:30] [Render thread/INFO]: [BetterF3] Loading...
[19:24:30] [Render thread/INFO]: [BetterF3] All done!
[19:24:30] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[19:24:31] [Render thread/INFO]: Using Default JreDnsResolver
[19:24:32] [Render thread/INFO]: OptiFine not detected.
[19:24:32] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[19:24:35] [Render thread/WARN]: Ignoring ambiguous boolean option GENERAL_GRASS_FIX
[19:24:35] [Render thread/WARN]: Ignoring ambiguous boolean option GENERAL_GRASS_FIX
[19:24:35] [Render thread/WARN]: Unable to resolve shader pack option menu element "ATMOSPHERIC_SCATTERING" defined in shaders.properties
[19:24:35] [Render thread/WARN]: Unable to resolve shader pack option menu element "ATMOSPHERIC_HAZE" defined in shaders.properties
[19:24:35] [Render thread/WARN]: Unable to resolve shader pack option menu element "CREPUSCULAR_RAYS" defined in shaders.properties
[19:24:35] [Render thread/WARN]: Unable to resolve shader pack option menu element "VOLUMETRIC_CLOUDS" defined in shaders.properties
[19:24:35] [Render thread/WARN]: Unable to resolve shader pack option menu element "HQ_VOLUMETRIC_CLOUDS" defined in shaders.properties
[19:24:35] [Render thread/WARN]: Unable to resolve shader pack option menu element "SMOOTH_CLOUDS" defined in shaders.properties
[19:24:35] [Render thread/WARN]: Unable to resolve shader pack option menu element "WATER_CAUSTICS" defined in shaders.properties
[19:24:35] [Render thread/WARN]: Unable to resolve shader pack option menu element "ENABLE_SOFT_SHADOWS" defined in shaders.properties
[19:24:35] [Render thread/WARN]: Unable to resolve shader pack option menu element "PIXEL_SHADOWS" defined in shaders.properties
[19:24:35] [Render thread/WARN]: Unable to resolve shader pack option menu element "TONEMAP_STRENGTH" defined in shaders.properties
[19:24:35] [Render thread/WARN]: Unable to resolve shader pack option menu element "BRIGHTNESS_LEVEL" defined in shaders.properties
[19:24:35] [Render thread/WARN]: Profile: Custom (+7 options changed by user)
[19:24:37] [Render thread/WARN]: Using shaderpack: SEUS-Renewed-v1.0.1.zip
[19:24:39] [Render thread/WARN]: Hardware information:
[19:24:39] [Render thread/WARN]: CPU: 8x AMD Ryzen 5 3400G with Radeon Vega Graphics 
[19:24:39] [Render thread/WARN]: GPU: Radeon RX 5500 XT (Supports OpenGL 3.2.14802 Core Profile Forward-Compatible Context 22.2.2 30.0.14029.1011)
[19:24:39] [Render thread/WARN]: OS: Windows 10 (10.0)
[19:24:41] [Render thread/WARN]: Method overwrite conflict for getNativeMemoryUsage in sodium.mixins.json:features.debug.MixinDebugHud, previously written by net.coderbot.iris.mixin.MixinDebugScreenOverlay. Skipping method.
[19:24:41] [Render thread/INFO]: Narrator library for x64 successfully loaded
[19:24:41] [Render thread/INFO]: Starting DI!
[19:24:41] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:24:42] [Thread 3/INFO]: Connecting to Essential Connection Manager...
[19:24:42] [Render thread/INFO]: Using Default JreSocketFactory
[19:24:42] [WebSocketConnectReadThread-120/INFO]: Opened connection to Essential ConnectionManager (code=101, message=Switching Protocols)
[19:24:42] [Render thread/INFO]: Essential Connection Manager connection established.
[19:24:43] [Render thread/INFO]: Reloading ResourceManager: Default, 3D compliment (C).zip, Fabric Mods (BetterF3, Cloth Config v6, essential-container, essential-loader, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Falling Leaves, Fart, Iris, Lithium, [MCXR] Core, [MCXR] Play, Phosphor, Sodium, Essential), AnotherBetterWolves_V5.1_MC1.16.X.zip, Water+Improved.zip, Clear_Glass_Pack_1.18.zip, Transparent + synthwave (C)-1.18.X.zip, Stargazer+Test11.zip, §6§lClassic+3D+v14.1+-+1.18.zip, Default Panorama Shaders.zip, Essential (fabric_1.18.2).jar
[19:24:44] [Render thread/WARN]: Shader 953babc61b7d3bc9bfd95a62e6dc933dc8629aeb could not find uniform named subpixel_amount in the specified shader program.
[19:24:54] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Realtek HD Audio 2nd output (Realtek(R) Audio)
[19:24:54] [Render thread/INFO]: Sound engine started
[19:24:55] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[19:24:55] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[19:24:55] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[19:24:55] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[19:24:55] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[19:24:55] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[19:24:55] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[19:24:57] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[19:24:57] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[19:24:57] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[19:25:02] [Render thread/ERROR]: Exception caught while initializing OpenXR
net.sorenon.mcxr.play.openxr.XrException: Failed to create xrInstance, are you sure your headset is plugged in?
	at net.sorenon.mcxr.play.openxr.OpenXRState.createOpenXRInstance(OpenXRState.java:143) ~[mcxr-play-0.2.1.jar:?]
	at net.sorenon.mcxr.play.openxr.OpenXRState.tryInitialize(OpenXRState.java:75) [mcxr-play-0.2.1.jar:?]
	at net.minecraft.class_442.handler$bdj001$render(class_442.java:1057) [client-intermediary.jar:?]
	at net.minecraft.class_442.method_25394(class_442.java:337) [client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:877) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1122) [client-intermediary.jar:?]
	at net.minecraft.class_310.redirect$bef000$loop(class_310.java:8142) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[19:25:04] [Render thread/ERROR]: Signature is missing from textures payload

**Comment by maximumpower55** [comment]
The issue is you are using mcxr without a headset

**Comment by maximumpower55** [comment]
Can you try without mcxr

**Comment by efjnsamdg** [comment]
> Can you try without mcxr

It tilts even with mcxr

**Comment by maximumpower55** [comment]
with? i said without

**Comment by efjnsamdg** [comment]
Tried it without mcxr, it works. Now I just need a way to fix the issue so I can use mcxr.

**Comment by AlsoSylv** [comment]
You're using MCXR without a headset, to use MCXR you need a VR headset, if this is an issue with MCXR not detecting your headset, it's best to report the bug there.
