### ISSUE TITLE
Iris Wont Load Slidur's Enhanced Default Shaders.

### ISSUE THREAD

**Issue by brasher21** [IrisShaders/Iris#1342]
### What happened?

Hello! 

Its just what I said in the topic. Slidurs Shaders (Fast - Enhanced Default) does not work when I try to load it with Iris.

I am using Iris as a Fabric Mod.

Shaders:
[Sildur's+Enhanced+Default+v1.131+Fast.zip](https://github.com/IrisShaders/Iris/files/8386374/Sildur.s%2BEnhanced%2BDefault%2Bv1.131%2BFast.zip)

### Screenshots

![image](https://user-images.githubusercontent.com/93966741/160986274-c42f612b-4550-4bd0-a680-9ac38396028d.png)
Whenever I load it, it just shows this. And when I check logs, ill send it below.

### Relevant log output

```shell
[09:54:13] [Render thread/WARN]: Destroying pipeline OVERWORLD
[09:54:13] [Render thread/INFO]: null:1:1: error: Unknown preprocessor directive Global
[09:54:13] [Render thread/INFO]: null:2:2: error: Unknown preprocessor directive Set
[09:54:13] [Render thread/INFO]: null:3:2: error: Unknown preprocessor directive The
[09:54:13] [Render thread/INFO]: null:4:2: error: Unknown preprocessor directive clouds
[09:54:13] [Render thread/INFO]: null:7:2: error: Unknown preprocessor directive Enable
[09:54:13] [Render thread/INFO]: null:8:2: error: Unknown preprocessor directive Backwards
[09:54:13] [Render thread/INFO]: null:9:2: error: Unknown preprocessor directive When
[09:54:13] [Render thread/INFO]: null:10:2: error: Unknown preprocessor directive The
[09:54:13] [Render thread/INFO]: null:11:1: error: Unknown preprocessor directive oldHandLight
[09:54:13] [Render thread/INFO]: null:13:2: error: Unknown preprocessor directive Enable
[09:54:13] [Render thread/INFO]: null:14:2: error: Unknown preprocessor directive The
[09:54:13] [Render thread/INFO]: null:15:2: error: Unknown preprocessor directive oldLighting
[09:54:13] [Render thread/INFO]: null:18:2: error: Unknown preprocessor directive Enable
[09:54:13] [Render thread/INFO]: null:19:2: error: Unknown preprocessor directive shadowTranslucent
[09:54:13] [Render thread/INFO]: null:24:2: error: Unknown preprocessor directive Enable
[09:54:13] [Render thread/INFO]: null:25:2: error: Unknown preprocessor directive This
[09:54:13] [Render thread/INFO]: null:26:2: error: Unknown preprocessor directive dynamicHandLight
[09:54:13] [Render thread/INFO]: null:28:2: error: Unknown preprocessor directive Enable
[09:54:13] [Render thread/INFO]: null:29:2: error: Unknown preprocessor directive underwaterOverlay
[09:54:13] [Render thread/INFO]: null:31:2: error: Unknown preprocessor directive Enable
[09:54:13] [Render thread/INFO]: null:32:2: error: Unknown preprocessor directive sun
[09:54:13] [Render thread/INFO]: null:35:2: error: Unknown preprocessor directive Enable
[09:54:13] [Render thread/INFO]: null:36:2: error: Unknown preprocessor directive moon
[09:54:13] [Render thread/INFO]: null:39:2: error: Unknown preprocessor directive Disable
[09:54:13] [Render thread/INFO]: null:42:1: error: Unknown preprocessor directive Final
[09:54:13] [Render thread/INFO]: null:45:1: error: Unknown preprocessor directive Sub
[09:54:13] [Render thread/INFO]: null:61:2: error: Unknown preprocessor directive Used
[09:54:13] [Render thread/INFO]: null:62:1: error: Preprocessor directive not a word #
[09:54:13] [Render thread/WARN]: Profile: Fast (+0 options changed by user)
[09:54:13] [Render thread/INFO]: null:1:1: error: Unknown preprocessor directive Forge
[09:54:13] [Render thread/INFO]: null:2:1: error: Unknown preprocessor directive Format
[09:54:13] [Render thread/INFO]: null:3:1: error: Unknown preprocessor directive Only
[09:54:13] [Render thread/INFO]: null:4:2: error: Unknown preprocessor directive Short
[09:54:13] [Render thread/INFO]: null:5:1: error: Preprocessor directive not a word #
[09:54:13] [Render thread/INFO]: null:6:2: error: Unknown preprocessor directive Long
[09:54:13] [Render thread/INFO]: null:7:1: error: Preprocessor directive not a word #
[09:54:13] [Render thread/INFO]: null:8:2: error: Unknown preprocessor directive Properties
[09:54:13] [Render thread/INFO]: null:9:1: error: Preprocessor directive not a word #
[09:54:13] [Render thread/INFO]: null:10:2: error: Unknown preprocessor directive Block
[09:54:13] [Render thread/INFO]: null:11:1: error: Preprocessor directive not a word #
[09:54:13] [Render thread/INFO]: null:12:1: error: Preprocessor directive not a word ==
[09:54:13] [Render thread/INFO]: null:14:2: error: Preprocessor directive not a word 1.13
[09:54:13] [Render thread/INFO]: null:17:2: error: Unknown preprocessor directive WAVING
[09:54:13] [Render thread/INFO]: null:18:2: error: Unknown preprocessor directive small
[09:54:13] [Render thread/INFO]: null:21:2: error: Unknown preprocessor directive Small
[09:54:13] [Render thread/INFO]: null:24:2: error: Unknown preprocessor directive Tall
[09:54:13] [Render thread/INFO]: null:27:2: error: Unknown preprocessor directive Inverted
[09:54:13] [Render thread/INFO]: null:30:2: error: Unknown preprocessor directive Leaves
[09:54:13] [Render thread/INFO]: null:32:2: error: Unknown preprocessor directive vines
[09:54:13] [Render thread/INFO]: null:35:2: error: Unknown preprocessor directive lilypad
[09:54:13] [Render thread/INFO]: null:38:2: error: Unknown preprocessor directive fire
[09:54:13] [Render thread/INFO]: null:41:2: error: Unknown preprocessor directive Lava
[09:54:13] [Render thread/INFO]: null:44:2: error: Unknown preprocessor directive REFLECTIONS
[09:54:13] [Render thread/INFO]: null:45:2: error: Unknown preprocessor directive Water
[09:54:13] [Render thread/INFO]: null:47:2: error: Unknown preprocessor directive Transparent
[09:54:13] [Render thread/INFO]: null:49:2: error: Unknown preprocessor directive Emissive
[09:54:13] [Render thread/INFO]: null:53:2: error: Unknown preprocessor directive blocks
[09:54:13] [Render thread/INFO]: null:74:6: warning: No newline before end of file
[09:54:13] [Render thread/WARN]: Using shaderpack: Sildur's+Enhanced+Default+v1.131+Fast.zip
[09:54:13] [Render thread/INFO]: [CHAT] Shaders Reloaded!
[09:54:13] [Render thread/WARN]: Creating pipeline for dimension OVERWORLD
[09:54:14] [Render thread/INFO]: OpenGL debug message: id=1, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='GLSL link failed for program 283, "": Attribute Position is bound to generic attribute 0, but gl_Vertex is also used.
'
[09:54:14] [Render thread/INFO]: OpenGL debug message: id=1, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='GLSL link failed: Attribute Position is bound to generic attribute 0, but gl_Vertex is also used.
'
[09:54:14] [Render thread/WARN]: Program link log for composite: Attribute Position is bound to generic attribute 0, but gl_Vertex is also used.

[09:54:14] [Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.RuntimeException: Shader compilation failed!
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:235) ~[iris-mc1.18.2-1.2.2-build.32.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:93) ~[iris-mc1.18.2-1.2.2-build.32.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:196) ~[iris-mc1.18.2-1.2.2-build.32.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:521) ~[iris-mc1.18.2-1.2.2-build.32.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) [iris-mc1.18.2-1.2.2-build.32.jar:?]
	at net.minecraft.class_761.handler$zji000$iris$beginLevelRender(class_761.java:6454) [client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1222) [client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1034) [client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:813) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1122) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
Caused by: java.lang.RuntimeException: Shader program linking failed, see log for details
	at net.coderbot.iris.gl.shader.ProgramCreator.create(ProgramCreator.java:47) ~[iris-mc1.18.2-1.2.2-build.32.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:87) ~[iris-mc1.18.2-1.2.2-build.32.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:231) ~[iris-mc1.18.2-1.2.2-build.32.jar:?]
	... 18 more
```

### Minecraft Version

Minecraft 1.18.2

### Iris Version

iris-mc1.18.2-1.2.2-build.32.jar

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15.jar

### Operating System

Windows 10

### What is your GPU?

Intel(R) HD Graphics 4000 

### Java Version

java version "11.0.11"

**Comment by Lolothepro** [comment]
https://github.com/IrisShaders/Iris/blob/trunk/docs/usage/drivers.md

**Comment by brasher21** [comment]
Thank you!
