### ISSUE TITLE
Iris causes aura shader in Arcanus to mess up

### ISSUE THREAD

**Issue by CammiePone** [IrisShaders/Iris#1367]
### What happened?

When using Iris, the aura shader from Arcanus will treat texture transparency as if it's opaque, when normally it would ignore it when rendering.

On top of that, Iris also causes armour to cut off the shader in weird ways, as if it's culling parts of the model but only sometimes.

Finally, when a shaderpack is enabled, the aura shader renders in front of all entities and blocks, but I'm not sure if that's something either of us can fix.

### Screenshots

Without Sodium & Iris:

![image](https://user-images.githubusercontent.com/16853086/163678533-3a055628-2473-4d69-8c12-a26d367c4581.png)
![image](https://user-images.githubusercontent.com/16853086/163678565-ddba7c30-4edc-456f-82e9-548323941948.png)

With Sodium but Without Iris:

![image](https://user-images.githubusercontent.com/16853086/163678654-96c7b713-ed11-42e4-99e3-66f7b48d090e.png)
![image](https://user-images.githubusercontent.com/16853086/163678659-c23ad8ec-d303-456a-84a7-c988a1e82dc8.png)

With Sodium & Iris:

![image](https://user-images.githubusercontent.com/16853086/163678731-8d4af3b5-884e-429c-8e4d-f04bf655745a.png)
![image](https://user-images.githubusercontent.com/16853086/163678742-416bffe3-8949-460b-bbc1-08f17c1d0cf7.png)

With Shaders:

![image](https://user-images.githubusercontent.com/16853086/163678768-877063a7-ee06-4117-86fd-9c82a6b2bc70.png)
![image](https://user-images.githubusercontent.com/16853086/163678776-1ded5963-bc2f-49be-9c9a-0348e00205fd.png)

### Relevant log output

```shell
[10:24:35] [Render thread/WARN]: Error loading class: net/minecraft/world/level/material/FluidState (java.lang.ClassNotFoundException: net/minecraft/world/level/material/FluidState)
[10:24:35] [Render thread/INFO]: Started 6 worker threads
[10:24:36] [Render thread/INFO]: [CHAT] Player280 has completed the challenge [Cover Me in Debris]
[10:24:36] [Render thread/INFO]: Loaded 3 advancements
[10:24:37] [Render thread/WARN]: Creating pipeline for dimension OVERWORLD
[10:24:37] [Render thread/INFO]: Stopping worker threads
[10:24:37] [Render thread/INFO]: Started 6 worker threads
[10:24:37] [Render thread/WARN]: Failed to load texture: minecraft:misc/white.png
java.io.FileNotFoundException: minecraft:misc/white.png
	at net.minecraft.resource.NamespaceResourceManager.getResource(NamespaceResourceManager.java:67) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.resource.LifecycledResourceManagerImpl.getResource(LifecycledResourceManagerImpl.java:47) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.resource.ReloadableResourceManagerImpl.getResource(ReloadableResourceManagerImpl.java:52) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.texture.ResourceTexture$TextureData.load(ResourceTexture.java:81) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.texture.ResourceTexture.loadTextureData(ResourceTexture.java:57) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.texture.ResourceTexture.load(ResourceTexture.java:28) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.texture.TextureManager.loadTexture(TextureManager.java:96) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.texture.TextureManager.registerTexture(TextureManager.java:68) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.texture.TextureManager.getTexture(TextureManager.java:118) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.render.RenderPhase$Texture.method_23563(RenderPhase.java:238) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.render.RenderPhase.startDrawing(RenderPhase.java:36) ~[minecraft-project-@-merged-named.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.client.render.RenderLayer$MultiPhase.method_23595(RenderLayer.java:929) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.render.RenderPhase.startDrawing(RenderPhase.java:36) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.render.RenderPhase.startDrawing(RenderPhase.java:36) [minecraft-project-@-merged-named.jar:?]
	at net.coderbot.iris.layer.OuterWrappedRenderType.startDrawing(OuterWrappedRenderType.java:28) [iris-1.2.2-build.32-64b5720b4b825f21.jar:?]
	at net.coderbot.batchedentityrendering.impl.FullyBufferedMultiBufferSource.draw(FullyBufferedMultiBufferSource.java:113) [iris-1.2.2-build.32-64b5720b4b825f21.jar:?]
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:528) [iris-1.2.2-build.32-64b5720b4b825f21.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:506) [iris-1.2.2-build.32-64b5720b4b825f21.jar:?]
	at net.minecraft.client.render.WorldRenderer.handler$zka000$iris$renderTerrainShadows(WorldRenderer.java:5471) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer.java:1235) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:1034) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:813) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1122) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:737) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [minecraft-project-@-merged-named.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
```

### Minecraft Version

Minecraft 1.18.2

### Iris Version

iris-mc1.18.2-1.2.2-build.32

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GTX 1660 Ti

### Java Version

Java 17

### Additional context

[latest.log](https://github.com/IrisShaders/Iris/files/8500081/latest.log)

**Comment by coderbot16** [comment]
From conversation on Discord, this seems to be fixed on the side of Iris as best we can. Some issues with armor still exist but should likely be fixed in Arcanus instead.
