### ISSUE TITLE
Incompatibility with Create (Fabric), Fabric Seasons and Iris

### ISSUE THREAD

**Issue by Gamemap** [IrisShaders/Iris#1368]
### Minecraft Version

Minecraft 1.18.1

### Iris Version

iris-mc1.18.1-1.2.0-pre

### Sodium Version

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14

### Operating System

Windows 11 64 Bit

### What is your GPU?

Nvidia GeForce GTX 11660 Ti

### Java Version

Java 17 (normal Java Version for Minecraft 1.18.x)

### Reproduction Steps

1. Use these Mods with Minecraft 1.18.1:
 - fabric-api-0.46.6+1.18.jar
 - iris-mc1.18.1-1.2.0-pre.jar
 - sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar
 - create-mc1.18.1_v0.4d+482.jar (https://github.com/Fabricators-of-Create/Create  (Fabric Version))
 - fabric-seasons-1.3-BETA+1.18.jar (https://github.com/lucaargolo/fabric-seasons)

2. Create a world (everything works)
3. Place a block from the Create Mod
4. Game Crashes

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 17.04.22, 01:38
Description: Unexpected error

java.lang.RuntimeException: Cannot use BufferBuilder with format: 9 elements: Position=3,Position,Float Color=4,Vertex Color,Unsigned Byte UV0=2,UV,Float UV2=2,UV,Short Normal=3,Normal,Byte Padding=1,Padding,Byte mc_Entity=4,Generic,Float mc_midTexCoord=2,Generic,Float at_tangent=4,Generic,Float
	at com.jozufozu.flywheel.core.vertex.BlockVertex.createReader(BlockVertex.java:72)
	at com.jozufozu.flywheel.core.model.BlockModel.<init>(BlockModel.java:32)
	at com.jozufozu.flywheel.core.model.BlockModel.<init>(BlockModel.java:28)
	at com.jozufozu.flywheel.core.model.BlockModel.<init>(BlockModel.java:22)
	at com.jozufozu.flywheel.api.Material.lambda$getModel$3(Material.java:43)
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancedMaterial.lambda$model$0(InstancedMaterial.java:43)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancedMaterial.model(InstancedMaterial.java:42)
	at com.jozufozu.flywheel.api.Material.getModel(Material.java:43)
	at com.simibubi.create.content.contraptions.base.SingleRotatingInstance.getModel(SingleRotatingInstance.java:42)
	at com.simibubi.create.content.contraptions.base.SingleRotatingInstance.init(SingleRotatingInstance.java:19)
	at com.jozufozu.flywheel.backend.instancing.InstanceManager.createInternal(InstanceManager.java:330)
	at com.jozufozu.flywheel.backend.instancing.InstanceManager.addInternal(InstanceManager.java:312)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.jozufozu.flywheel.backend.instancing.InstanceManager.processQueuedAdditions(InstanceManager.java:289)
	at com.jozufozu.flywheel.backend.instancing.InstanceManager.beginFrame(InstanceManager.java:146)
	at com.jozufozu.flywheel.backend.instancing.InstanceWorld.beginFrame(InstanceWorld.java:97)
	at com.jozufozu.flywheel.backend.instancing.InstancedRenderDispatcher.onBeginFrame(InstancedRenderDispatcher.java:83)
	at com.jozufozu.flywheel.fabric.event.FlywheelEvents.lambda$createSimple$0(FlywheelEvents.java:22)
	at net.minecraft.class_761.handler$zoi000$setupRender(class_761.java:12415)
	at net.minecraft.class_761.method_3273(class_761.java)
	at net.minecraft.class_761.method_22710(class_761.java:1253)
	at net.minecraft.class_757.method_3188(class_757.java:1031)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.jozufozu.flywheel.core.vertex.BlockVertex.createReader(BlockVertex.java:72)
	at com.jozufozu.flywheel.core.model.BlockModel.<init>(BlockModel.java:32)
	at com.jozufozu.flywheel.core.model.BlockModel.<init>(BlockModel.java:28)
	at com.jozufozu.flywheel.core.model.BlockModel.<init>(BlockModel.java:22)
	at com.jozufozu.flywheel.api.Material.lambda$getModel$3(Material.java:43)
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancedMaterial.lambda$model$0(InstancedMaterial.java:43)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancedMaterial.model(InstancedMaterial.java:42)
	at com.jozufozu.flywheel.api.Material.getModel(Material.java:43)
	at com.simibubi.create.content.contraptions.base.SingleRotatingInstance.getModel(SingleRotatingInstance.java:42)
	at com.simibubi.create.content.contraptions.base.SingleRotatingInstance.init(SingleRotatingInstance.java:19)
	at com.jozufozu.flywheel.backend.instancing.InstanceManager.createInternal(InstanceManager.java:330)
	at com.jozufozu.flywheel.backend.instancing.InstanceManager.addInternal(InstanceManager.java:312)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.jozufozu.flywheel.backend.instancing.InstanceManager.processQueuedAdditions(InstanceManager.java:289)
	at com.jozufozu.flywheel.backend.instancing.InstanceManager.beginFrame(InstanceManager.java:146)
	at com.jozufozu.flywheel.backend.instancing.InstanceWorld.beginFrame(InstanceWorld.java:97)
	at com.jozufozu.flywheel.backend.instancing.InstancedRenderDispatcher.onBeginFrame(InstancedRenderDispatcher.java:83)
	at com.jozufozu.flywheel.fabric.event.FlywheelEvents.lambda$createSimple$0(FlywheelEvents.java:22)
	at net.minecraft.class_761.handler$zoi000$setupRender(class_761.java:12415)
	at net.minecraft.class_761.method_3273(class_761.java)
	at net.minecraft.class_761.method_22710(class_761.java:1253)
	at net.minecraft.class_757.method_3188(class_757.java:1031)

-- Affected level --
Details:
	All players: 1 total; [class_746['_Estragon_'/188, l='ClientLevel', x=-23.60, y=65.12, z=-61.98]]
	Chunk stats: 4096, 915
	Level dimension: minecraft:overworld
	Level spawn location: World: (-16,68,-48), Section: (at 0,4,0 in -1,4,-3; chunk contains blocks -16,-64,-48 to -1,319,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 3073 game time, 9219327 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1986570480 bytes (1894 MiB) / 4697620480 bytes (4480 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 2,90
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce GTX 1660 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x2182
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1165
	Memory slot #0 capacity (MB): 16384,00
	Memory slot #0 clockSpeed (GHz): 3,20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 35706,62
	Virtual memory used (MB): 20046,44
	Swap memory total (MB): 19456,00
	Swap memory used (MB): 227,53
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_github_llamalad7_mixinextras: MixinExtras 0.0.6
		com_google_code_findbugs_jsr305: jsr305 3.0.2
		create: Create mc1.18.1_v0.4d+482
		dripstone_fluid_lib: Dripstone Fluid Lib 1.1.1
		fabric: Fabric API 0.46.6+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.9+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 1.0.0+3fec4ad9c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.7+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.7+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.12+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.5+737332ce65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.13+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.15+8906aafd65
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.9+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.9+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.10+c329913d65
		fabricloader: Fabric Loader 0.13.3
		fake-player-api: Fake Player API 0.3.0
		flywheel: Flywheel 1.18-0.6.1.24
		forge_tags: Forge Tags 2.0
		forgeconfigapiport: Forge Config API Port 3.1.0
		iris: Iris 1.2.0-pre
		java: OpenJDK 64-Bit Server VM 17
		milk: Milk Lib 0.1.6
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.3
		org_anarres_jcpp: jcpp 1.4.14
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		porting_lib: Porting Lib 0.1.0-interfacent+1.18-interfacent.a60bb1a
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		registrate-fabric: Registrate for Fabric MC1.18.1-1.0.7
		seasons: Fabric Seasons 1.3-BETA+1.18
		sodium: Sodium 0.4.0-alpha6+build.14
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: fabric-loader-0.13.3-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 511.65, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['_Estragon_'/188, l='ServerLevel[Create and Seasons]', x=-23.60, y=65.12, z=-61.98]]
	Data Packs: vanilla, Fabric Mods
```

### Additional context

[crash-2022-04-17_01.38.17-client.txt](https://github.com/IrisShaders/Iris/files/8500782/crash-2022-04-17_01.38.17-client.txt)
[latest.log](https://github.com/IrisShaders/Iris/files/8500783/latest.log)

Minecaft Launcher error message:
````
The game crashed whilst unexpected error
Error: java.lang.RuntimeException: Cannot use BufferBuilder with format: 9 elements: Position=3,Position,Float Color=4,Vertex Color,Unsigned Byte UV0=2,UV,Float UV2=2,UV,Short Normal=3,Normal,Byte Padding=1,Padding,Byte mc_Entity=4,Generic,Float mc_midTexCoord=2,Generic,Float at_tangent=4,Generic,Float
Exit-Code: -1
````
-----
If one of the mods (iris, create, seasons) is not loaded (removed from the mods folder), there is no error/crash.

**Comment by PepperCode1** [comment]
The only solution here is to run `/flywheel backend off` if you cannot update to 1.18.2. Iris 1.2.1 fixed this incompatibility, but since neither Iris nor Flywheel support 1.18.1, the fix cannot be ported back.

**Comment by coderbot16** [comment]
Ah, good to know that this is not an issue in 1.18.2. Closing.

**Comment by Gamemap** [comment]
Thank you
