### ISSUE TITLE
java.lang.NullPointerException: Cannot read field "field_3911" because "this.field_4015.field_1724" is null

### ISSUE THREAD

**Issue by Gilithrimm** [IrisShaders/Iris#1381]
### Minecraft Version

Minecraft 1.18.2

### Iris Version

iris-mc1.18.2-1.2.2-build.32.jar

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15.jar

### Operating System

Linux Ubuntu 20.04

### What is your GPU?

Intel Core i3-3220

### Java Version

Java 17

### Reproduction Steps

1. Join a world
2. Crash after load

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Why did you do that?

Time: 4/24/22, 9:01 PM
Description: Unexpected error

java.lang.NullPointerException: Cannot read field "field_3911" because "this.field_4015.field_1724" is null
  at net.minecraft.class_757.method_3188(class_757.java:1007)
  at net.minecraft.class_757.method_3192(class_757.java:813)
  at net.minecraft.class_310.method_1523(class_310.java:1122)
  at net.minecraft.class_310.method_1514(class_310.java:737)
  at net.minecraft.client.main.Main.main(Main.java:236)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
  at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
  at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29)
  at crystallauncher.MineClient.start(MineClient.java:206)
  at crystallauncher.MineClient.main(MineClient.java:36)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
  at net.minecraft.class_757.method_3188(class_757.java:1007)
Mixins in Stacktrace:
  net.minecraft.class_757:
    net.coderbot.iris.mixin.MixinTweakFarPlane (mixins.iris.json)
    dev.architectury.mixin.fabric.client.MixinGameRenderer (architectury.mixins.json)
    net.coderbot.iris.mixin.MixinGameRenderer (mixins.iris.json)
    net.coderbot.iris.mixin.GameRendererAccessor (mixins.iris.json)
    me.flashyreese.mods.sodiumextra.mixin.prevent_shaders.MixinGameRenderer (sodium-extra.mixins.json)
    com.logicalgeekboy.logical_zoom.mixin.LogicalZoomMixin (logical_zoom.client-mixins.json)
    net.coderbot.iris.mixin.MixinGameRenderer_NightVisionCompat (mixins.iris.json)
    net.fabricmc.fabric.mixin.screen.GameRendererMixin (fabric-screen-api-v1.mixins.json)
    net.coderbot.iris.mixin.MixinModelViewBobbing (mixins.iris.json)

-- Affected level --
Details:
  All players: 0 total; []
  Chunk stats: 256, 81
  Level dimension: minecraft:overworld
  Level spawn location: World: (32,72,-64), Section: (at 0,8,0 in 2,4,-4; chunk contains blocks 32,-64,-64 to 47,319,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
  Level time: 2 game time, 2 day time
  Server brand: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.class_746.method_3135()" because "this.field_3729.field_1724" is null
  Server type: Integrated singleplayer server
Stacktrace:
  at net.minecraft.class_638.method_8538(class_638.java:407)
  at net.minecraft.class_310.method_1587(class_310.java:2376)
  at net.minecraft.class_310.method_1514(class_310.java:761)
  at net.minecraft.client.main.Main.main(Main.java:236)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
  at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
  at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29)
  at crystallauncher.MineClient.start(MineClient.java:206)
  at crystallauncher.MineClient.main(MineClient.java:36)
Mixins in Stacktrace:
  net.minecraft.class_638:
    dev.tr7zw.entityculling.mixin.ClientWorldMixin (entityculling.mixins.json)
    me.jellysquid.mods.sodium.mixin.features.chunk_rendering.MixinClientWorld (sodium.mixins.json)
    dlovin.inventoryhud.mixin.UpdateNotifierMixin (inventoryhud.mixins.json)
    dev.lambdaurora.lambdynlights.mixin.ClientWorldMixin (lambdynlights.mixins.json)
    net.coderbot.iris.mixin.vertices.block_rendering.MixinClientLevel (mixins.iris.vertexformat.json)
    org.quiltmc.qsl.lifecycle.mixin.client.ClientWorldMixin (quilt_lifecycle_events.mixins.json)
    dev.architectury.mixin.fabric.client.MixinClientLevel (architectury.mixins.json)
    me.jellysquid.mods.sodium.mixin.features.fast_biome_colors.MixinClientWorld (sodium.mixins.json)
    ca.spottedleaf.starlight.mixin.client.world.ClientLevelMixin (starlight.mixins.json)
    me.jellysquid.mods.lithium.mixin.chunk.entity_class_groups.ClientWorldMixin (lithium.mixins.json)
  net.minecraft.class_310:
    net.fabricmc.fabric.mixin.registry.sync.client.MixinMinecraftClient (fabric-registry-sync-v0.mixins.json)
    io.grayray75.fabric.fpsdisplay.mixin.MinecraftClientMixin (fpsdisplay.mixins.json)
    dev.lambdaurora.lambdynlights.mixin.MinecraftClientMixin (lambdynlights.mixins.json)
    me.flashyreese.mods.sodiumextra.mixin.gui.MinecraftClientAccessor (sodium-extra.mixins.json)
    net.darkhax.bookshelf.mixin.client.AccessorMinecraft (bookshelf.mixins.json)
    com.minenash.monsters_in_the_closet.mixin.MinecraftClientMixin (monsters_in_the_closet.mixins.json)
    dev.architectury.mixin.fabric.client.MixinMinecraft (architectury.mixins.json)
    net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
    dlovin.inventoryhud.mixin.PlayerMixin (inventoryhud.mixins.json)
    dev.lambdaurora.spruceui.mixin.MinecraftClientMixin (spruceui.mixins.json)
    org.quiltmc.qsl.lifecycle.mixin.client.MinecraftClientMixin (quilt_lifecycle_events.mixins.json)
    xyz.rongmario.cleancut.MixinMinecraftClient (mixins.cleancut.json)
    dzwdz.chat_heads.mixin.MinecraftMixin (chat_heads.mixins.json)
    net.coderbot.iris.mixin.MixinMinecraft_PipelineDestruction (mixins.iris.json)
    me.jellysquid.mods.sodium.mixin.core.MixinMinecraftClient (sodium.mixins.json)
    net.fabricmc.fabric.mixin.event.interaction.MixinMinecraftClient (fabric-events-interaction-v0.mixins.json)
    net.fabricmc.fabric.mixin.networking.accessor.MinecraftClientAccessor (fabric-networking-api-v1.mixins.json)
    draylar.omegaconfig.mixin.ClientMixin (omega-config.mixins.json)
    org.quiltmc.qsl.base.mixin.client.MinecraftClientMixin (quilt_base.mixins.json)
    org.quiltmc.qsl.command.mixin.client.MinecraftClientMixin (quilt_client_command.mixins.json)
    net.coderbot.iris.mixin.MixinMinecraft (mixins.iris.json)
    org.quiltmc.qsl.resource.loader.mixin.client.MinecraftClientMixin (quilt_resource_loader.mixins.json)

-- Last reload --
Details:
  Reload number: 1
  Reload reason: initial
  Finished: Yes
  Packs: Default, charmonium/journeyman, lambdabettergrass/default

-- System Details --
Details:
  Minecraft Version: 1.18.2
  Minecraft Version ID: 1.18.2
  Operating System: Linux (amd64) version 5.13.0-40-generic
  Java Version: 17.0.1, Microsoft
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Microsoft
  Memory: 810725584 bytes (773 MiB) / 1677721600 bytes (1600 MiB) up to 2080374784 bytes (1984 MiB)
  CPUs: 2
  Processor Vendor: GenuineIntel
  Processor Name: Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz
  Identifier: Intel64 Family 6 Model 58 Stepping 9
  Microarchitecture: Ivy Bridge (Client)
  Frequency (GHz): 3.30
  Number of physical packages: 1
  Number of physical CPUs: 2
  Number of logical CPUs: 2
  Graphics card #0 name: Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller
  Graphics card #0 vendor: Intel Corporation (0x8086)
  Graphics card #0 VRAM (MB): 256.00
  Graphics card #0 deviceId: 0x0152
  Graphics card #0 versionInfo: unknown
  Virtual memory max (MB): 5975.24
  Virtual memory used (MB): 4606.57
  Swap memory total (MB): 2048.00
  Swap memory used (MB): 2.01
  JVM Flags: 7 total; -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Fabric Mods: 
    architectury: Architectury 4.0.30
    bookshelf: Bookshelf 13.0.7
    caffeineconfig: CaffeineConfig 1.1.0
    charmonium: Charmonium 4.0.0
    chat_heads: Chat Heads 0.6.0
    cleancut: CleanCut 1.18-4.0-fabric
    cloth-basic-math: cloth-basic-math 0.6.0
    cloth-config: Cloth Config v6 6.2.57
    com_electronwill_night-config_core: core 3.6.2
    com_electronwill_night-config_toml: toml 3.6.2
    com_moandjiezana_toml_toml4j: toml4j 0.7.2
    crowdin-translate: CrowdinTranslate 1.4+1.18.2
    cullleaves: Cull Leaves 2.3.2
    deathlog: DeathLog 0.2.7+1.18
    dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.18.2
    enchantment_lore: Enchantment Lore 1.2.6-1
    entity_texture_features: Entity Texture Features 2.6.0
    entityculling: EntityCulling-Fabric 1.5.1
    fabric: Fabric API 0.47.9+1.18.2
    fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.6+d7c144a860
    fabric-biome-api-v1: Fabric Biome API (v1) 8.0.2+801ec85b60
    fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.11+3ac43d9560
    fabric-commands-v0: Fabric Commands (v0) 0.2.7+b4f4f6cd60
    fabric-containers-v0: Fabric Containers (v0) 0.1.20+d7c144a860
    fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.1+d82b939260
    fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.10+3ac43d9560
    fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.16+2540745460
    fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.7+d7c144a860
    fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.18+d7c144a860
    fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.12+d7c144a860
    fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.12+d7c144a860
    fabric-item-api-v1: Fabric Item API (v1) 1.3.2+691a79b560
    fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.9+3ac43d9560
    fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.11+54e5b2ec60
    fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.9+b4f4f6cd60
    fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.10+d7c144a860
    fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.0.3+d1027f7d60
    fabric-models-v0: Fabric Models (v0) 0.3.5+d7c144a860
    fabric-networking-api-v1: Fabric Networking API (v1) 1.0.20+d882b91560
    fabric-networking-v0: Fabric Networking (v0) 0.3.7+b4f4f6cd60
    fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.0.2+34b2a0ce60
    fabric-particles-v1: Fabric Particles (v1) 0.2.11+526dc1ac60
    fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.6+ca4be9c960
    fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.12+d882b91560
    fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.16+d8c7b9ae60
    fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd60
    fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.6+d7c144a860
    fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.1+54e5b2ec60
    fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd60
    fabric-rendering-v1: Quilted Fabric Rendering (v1) 2.0.0+1.18.2-SNAPSHOT
    fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.1+d1027f7d60
    fabric-screen-api-v1: Fabric Screen API (v1) 1.0.9+d882b91560
    fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.13+d7c144a860
    fabric-textures-v0: Fabric Textures (v0) 1.0.11+3ac43d9560
    fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.13+cca23f9360
    fabricloader: Fabric Loader 0.13.3
    feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
    fpsdisplay: FPS-Display 1.4.2+1.18.2
    grindenchantments: Grind Enchantments 1.4.0+1.17.1
    indium: Indium 1.0.3+mc1.18.2
    inspecio: Inspecio 1.3.0+1.18
    inventoryhud: Inventory HUD + 3.4.2
    iris: Iris 1.2.2-build.32
    java: OpenJDK 64-Bit Server VM 17
    lambdabettergrass: LambdaBetterGrass 1.2.3+1.18
    lambdynlights: LambDynamicLights 2.1.0+1.17
    lazydfu: LazyDFU 0.1.2
    limitless: limitless 1.6.7
    lithium: Lithium 0.7.9
    logical_zoom: Logical Zoom 0.0.14
    midnightlib: MidnightLib 0.2.9
    minecraft: Minecraft 1.18.2
    mixintrace: MixinTrace 1.1.1+1.18.1
    modmenu: Mod Menu 3.1.0
    monsters_in_the_closet: Monsters in the Closet 1.0.3+1.18
    net_auoeke_reflect: reflect 4.6.0
    net_gudenau_lib_unsafe: unsafe 1.7.1
    no_fog: No Fog 1.2.2+1.16.5-1.18.2
    notes: Notes 1.0.10
    omega-config: OmegaConfig 1.0.8
    org_anarres_jcpp: jcpp 1.4.14
    org_joml_joml: joml 1.10.2
    pride: Pride Lib 1.1.0+1.17
    quilt_base: Quilt Base API 1.0.0+1.18.2-SNAPSHOT
    quilt_client_command: Quilt Client Command API 1.0.0+1.18.2-SNAPSHOT
    quilt_command: Quilt Command API 1.0.0+1.18.2-SNAPSHOT
    quilt_lifecycle_events: Quilt Lifecycle Events 1.0.0+1.18.2-SNAPSHOT
    quilt_resource_loader: Quilt Resource Loader 1.0.0+1.18.2-SNAPSHOT
    quilt_tags: Quilt Tags API 1.0.0+1.18.2-SNAPSHOT
    quilt_tooltip: Quilt Tooltip API 1.0.0+1.18.2-SNAPSHOT
    quilted-fabric-api-base: Quilted Fabric API Base 1.0.0+1.18.2-SNAPSHOT
    quilted-fabric-command-api-v1: Quilted Fabric Command API (v1) 2.0.0+1.18.2-SNAPSHOT
    quilted-fabric-lifecycle-events-v1: Quilted Fabric Lifecycle Events (v1) 2.0.1+1.18.2-SNAPSHOT
    quilted-fabric-resource-loader-v0: Quilted Fabric Resource Loader (v0) 1.0.0+1.18.2-SNAPSHOT
    reeses-sodium-options: Reese's Sodium Options 1.4.2
    repurposed_structures: Repurposed Structures 4.0.2+1.18.2
    roughlyenoughitems: Roughly Enough Items 8.0.442
    sodium: Sodium 0.4.1+build.15
    sodium-extra: Sodium Extra 0.4.3
    spruceui: SpruceUI 3.3.3+1.18
    starlight: Starlight 1.0.2+fabric.89b8d9f
    toolstats: ToolStats 9.0.1
    tooltipfix: ToolTip Fix 1.0.4-1.18
  Loaded Shaderpack: (off)
  Launched Version: fabric-loader-0.13.3-1.18.2
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: llvmpipe (LLVM 12.0.0, 256 bits) GL version 4.5 (Core Profile) Mesa 21.2.6, Mesa/X.org
  Window size: 1208x720
  GL Caps: Using framebuffer using OpenGL 3.2
  GL debug messages: 
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
  Type: Integrated Server (map_client.txt)
  Graphics mode: fast
  Resource Packs: charmonium/journeyman, lambdabettergrass/default
  Current Language: English (US)
  CPU: 2x Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz
  Server Running: true
  Player Count: 1 / 8; [class_3222['Gilithrimm'/197, l='ServerLevel[crashTest]', x=28.50, y=77.00, z=-55.50]]
  Data Packs: vanilla
  World Generation: Experimental
#@!@# Game crashed! Crash report saved to: #@!@# /home/gilithrimm/.crystalLauncher/bin/instances/u.fabric_18.2_x2_client/.minecraft/crash-reports/crash-2022-04-24_21.01.16-client.txt
```

### Additional context

installed either using iris installer or manually through curseforge, none works
tried loading with & without shaders, with & without datapacks- no change
any idea what it could be?
worldgen experimental cuz repurposed structures

**Comment by IMS212** [comment]
Please send a full log file.

**Comment by Gilithrimm** [comment]
[latest.log](https://github.com/IrisShaders/Iris/files/8550415/latest.log)

**Comment by IMS212** [comment]
Iris is not yet compatible with today's release of Indium; a fix will be coming soon.
