### ISSUE TITLE
runMinecraftServer fails on the command line because of a misplaced --assetIndex flag

### ISSUE THREAD

**Issue by douira** [IrisShaders/Iris#1382]
The following error happens:
```
% java -jar brachyura-bootstrap-0.jar runMinecraftClient
Using brachyura bootstrap 0
00:27:58.222 ERROR: Task Failed
00:27:58.222 ERROR: java.lang.IllegalArgumentException: error: invalid flag: --assetIndex
        at jdk.compiler/com.sun.tools.javac.main.Arguments.reportDiag(Arguments.java:889)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.doProcessArgs(Arguments.java:395)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Arguments.java:347)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Arguments.java:246)
        at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:191)
        at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:119)
        at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:68)
        at io.github.coolcrabs.brachyura.compiler.java.JavaCompilation.compile(JavaCompilation.java:132)
        at io.github.coolcrabs.brachyura.project.java.BaseJavaProject.runRunConfig(BaseJavaProject.java:88)
        at io.github.coolcrabs.brachyura.project.java.BaseJavaProject.lambda$getRunConfigTasks$1(BaseJavaProject.java:54)
        at io.github.coolcrabs.brachyura.project.Task$NoArgTask.doTask(Task.java:53)
        at io.github.coolcrabs.brachyura.project.BrachyuraEntry.main(BrachyuraEntry.java:45)
        at io.github.coolcrabs.brachyura.bootstrap.Main.main(Main.java:74)
```

In the .launch file there is this: `<stringAttribute key="org.eclipse.jdt.launching.PROGRAM_ARGUMENTS" value="&quot;--assetIndex&quot; &quot;1.17&quot; &quot;--assetsDir&quot; &quot;/Users/douira/.brachyura/cache/minecraft/assets&quot; "/>`. In the vscode launch config the flag also appears:

```
"args": [
        "--assetIndex",
        "1.17",
        "--assetsDir",
        "/Users/douira/.brachyura/cache/minecraft/assets"
      ],
```

The launch works through VSCode but not on the command line. @CoolMineman gave the following hint on what might be broken here:

> Ok looks like runtime flags are being passed to the compiler lmao

If this is an issue with Brachyura instead of Iris' buildscript, this issue could be migrated.

**Comment by douira** [comment]
is better suited in brachyura
