### ISSUE TITLE
[IMMERSIVE PORTAL] Iris crashes the game when two Nether portals face each other. 

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1449]
### What happened?

Video of what happens:
https://www.veed.io/view/6967fad8-baa8-4fa8-b683-aa8b8cc8d5a9?sharingWidget=true

Crash report:
[crash-2022-05-22_08.50.43-client.txt](https://github.com/IrisShaders/Iris/files/8748952/crash-2022-05-22_08.50.43-client.txt)

world file:
[I.P.zip](https://github.com/IrisShaders/Iris/files/8748954/I.P.zip)

### Relevant log output

```shell
[08:49:36] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.6
[08:49:36] [main/INFO]: Loading 55 mods:
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57 via immersive_portals
	- fabric 0.53.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.0+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.4+d82b939260 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.2.0+a6b0947860 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.15+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.5.0+85719ab760 via fabric
	- fabric-item-groups-v0 0.3.12+91896a4960 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-lifecycle-events-v1 2.0.3+2d83e92c60 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.1.1+81ea5b3c60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.1+032c981d60 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.5.0+7faf0d8860 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.5.0+2afceb2960 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.6.1+f4563ac860 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860 via fabric
	- fabricloader 0.14.6
	- imm_ptl_core 1.3.7 via immersive_portals
	- immersive_portals 1.3.7
	- iris 1.2.4-build.38
	- java 17
	- minecraft 1.18.2
	- org_anarres_jcpp 1.4.14 via iris
	- org_joml_joml 1.10.2 via sodium
	- q_misc_util 1.3.7 via immersive_portals
	- sodium 0.4.1+build.15
[08:49:36] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/loic/.local/share/PolyMC/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[08:49:36] [main/INFO]: Compatibility level set to JAVA_16
[08:49:36] [main/INFO]: Compatibility level set to JAVA_17
[08:49:36] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[08:49:37] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[08:49:37] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[08:49:38] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[08:49:43] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder from mod sodium, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[08:49:44] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[08:49:45] [Render thread/INFO]: Setting user: Lolothepro29
[08:49:45] [Render thread/INFO]: Immersive Portals Mod Initializing
[08:49:45] [Render thread/INFO]: Dimensional Threading is not present
[08:49:45] [Render thread/INFO]: Pehkui is not present
[08:49:45] [Render thread/INFO]: Gravity Changer is not present
[08:49:46] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[08:49:46] [Render thread/INFO]: IP Config Applied
[08:49:46] [Render thread/INFO]: Successfully initialized command /immersive_portals_debug
[08:49:46] [Render thread/INFO]: Sodium is present
[08:49:46] [Render thread/INFO]: Iris is present
[08:49:47] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[08:49:47] [Render thread/WARN]: OpenGL debug context activated.
[08:49:48] [Render thread/INFO]: [GL] Using KHR_debug for error logging.
[08:49:48] [Render thread/INFO]: Debug functionality is enabled, logging will be more verbose!
[08:49:48] [Render thread/INFO]: Shaders are disabled because enableShaders is set to false in iris.properties
[08:49:48] [Render thread/INFO]: Shaders are disabled
[08:49:49] [Render thread/INFO]: Hardware information:
[08:49:49] [Render thread/INFO]: CPU: 12x AMD Ryzen 5 1600 Six-Core Processor
[08:49:49] [Render thread/INFO]: GPU: NVIDIA GeForce GTX 1070/PCIe/SSE2 (Supports OpenGL 3.2.0 NVIDIA 515.43.04)
[08:49:49] [Render thread/INFO]: OS: Linux (5.17.0-9.1-liquorix-amd64)
[08:49:50] [Render thread/WARN]: Method overwrite conflict for getNativeMemoryUsage in sodium.mixins.json:features.debug.MixinDebugHud from mod sodium, previously written by net.coderbot.iris.mixin.MixinDebugScreenOverlay. Skipping method.
[08:49:50] [Render thread/INFO]: Narrator library successfully loaded
[08:49:50] [Render thread/INFO]: Shader Transform Skipping blit_screen
[08:49:50] [Render thread/INFO]: Shader Transform Skipping blit_screen
[08:49:50] [Render thread/INFO]: Shader Transform Skipping blit_screen
[08:49:50] [Render thread/INFO]: Shader Transform Skipping position
[08:49:50] [Render thread/INFO]: Shader Transform Skipping position
[08:49:50] [Render thread/INFO]: Shader Transform Skipping position
[08:49:50] [Render thread/INFO]: Shader Transform Skipping position_color
[08:49:50] [Render thread/INFO]: Shader Transform Skipping position_color
[08:49:50] [Render thread/INFO]: Shader Transform Skipping position_color
[08:49:50] [Render thread/INFO]: Shader Transform Skipping position_color_tex
[08:49:50] [Render thread/INFO]: Shader Transform Skipping position_color_tex
[08:49:50] [Render thread/INFO]: Shader Transform Skipping position_color_tex
[08:49:50] [Render thread/INFO]: Shader Transform Skipping position_tex
[08:49:50] [Render thread/INFO]: Shader Transform Skipping position_tex
[08:49:50] [Render thread/INFO]: Shader Transform Skipping position_tex
[08:49:50] [Render thread/INFO]: Shader Transform Skipping position_tex_color
[08:49:50] [Render thread/INFO]: Shader Transform Skipping position_tex_color
[08:49:50] [Render thread/INFO]: Shader Transform Skipping position_tex_color
[08:49:50] [Render thread/INFO]: Shader Transform Skipping rendertype_text
[08:49:50] [Render thread/INFO]: Shader Transform Skipping rendertype_text
[08:49:50] [Render thread/INFO]: Shader Transform Skipping rendertype_text
[08:49:50] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Cloth Config v6, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Immersive Portals Core, Immersive Portals, Iris, QMiscUtil, Sodium)
[08:49:51] [Render thread/INFO]: Loaded Shader Code Transformation
[08:49:54] [Render thread/INFO]: OpenAL initialized on device Family 17h (Models 00h-0fh) HD Audio Controller Stéréo analogique
[08:49:54] [Render thread/INFO]: Sound engine started
[08:49:55] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[08:49:55] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[08:49:55] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[08:49:55] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[08:49:55] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[08:49:55] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[08:49:55] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[08:49:56] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[08:49:56] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[08:49:56] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[08:50:30] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[08:50:30] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[08:50:30] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[08:50:30] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[08:50:30] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[08:50:30] [Render thread/INFO]: Loaded 7 recipes
[08:50:30] [Render thread/INFO]: Loaded 1141 advancements
[08:50:31] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[08:50:31] [Render thread/INFO]: Applied 0 biome modifications to 0 of 61 new biomes in 2.464 ms
[08:50:31] [Server thread/INFO]: Starting integrated minecraft server version 1.18.2
[08:50:31] [Server thread/INFO]: Generating keypair
[08:50:32] [Server thread/INFO]: Bedrock Replacement minecraft:overworld null
[08:50:32] [Server thread/INFO]: Bedrock Replacement immersive_portals:alternate1 null
[08:50:32] [Server thread/INFO]: Bedrock Replacement immersive_portals:alternate3 null
[08:50:32] [Server thread/INFO]: Bedrock Replacement minecraft:the_nether null
[08:50:32] [Server thread/INFO]: Bedrock Replacement immersive_portals:alternate4 null
[08:50:32] [Server thread/INFO]: Bedrock Replacement immersive_portals:alternate5 null
[08:50:32] [Server thread/INFO]: Bedrock Replacement immersive_portals:alternate2 null
[08:50:32] [Server thread/INFO]: Bedrock Replacement minecraft:the_end null
[08:50:32] [Server thread/INFO]: Successfully read IP's dimension id record
[08:50:32] [Server thread/INFO]: Start Completing Dimension Id Record
[08:50:32] [Server thread/INFO]: Before:
minecraft:overworld -> 0
immersive_portals:alternate1 -> 2
immersive_portals:alternate2 -> 3
minecraft:the_nether -> -1
immersive_portals:alternate3 -> 4
immersive_portals:alternate4 -> 5
minecraft:the_end -> 1
immersive_portals:alternate5 -> 6
[08:50:32] [Server thread/INFO]: Server Loaded Dimensions:
immersive_portals:alternate1
immersive_portals:alternate2
immersive_portals:alternate3
immersive_portals:alternate4
immersive_portals:alternate5
minecraft:overworld
minecraft:the_end
minecraft:the_nether

[08:50:32] [Server thread/INFO]: After:
minecraft:overworld -> 0
immersive_portals:alternate1 -> 2
immersive_portals:alternate2 -> 3
minecraft:the_nether -> -1
immersive_portals:alternate3 -> 4
immersive_portals:alternate4 -> 5
minecraft:the_end -> 1
immersive_portals:alternate5 -> 6
[08:50:32] [Server thread/INFO]: Dimension Id Info Saved to File
[08:50:32] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[08:50:32] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[08:50:32] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[08:50:33] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[08:50:33] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[08:50:34] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[08:50:34] [Render thread/INFO]: Préparation de la zone d'apparition : 5 %
[08:50:35] [Render thread/INFO]: Préparation de la zone d'apparition : 22 %
[08:50:35] [Server thread/INFO]: Loading custom portal generation
[08:50:35] [Render thread/INFO]: Time elapsed: 3653 ms
[08:50:35] [Server thread/INFO]: Server performance level: good
[08:50:35] [Server thread/INFO]: Changing view distance to 12, from 10
[08:50:35] [Server thread/INFO]: Changing simulation distance to 12, from 0
[08:50:36] [Server thread/INFO]: Lolothepro29[local:E:a98af57c] logged in with entity id 214 at (7.242917420969943, 83.23152379758702, -7.959932539882585)
[08:50:36] [Server thread/INFO]: Lolothepro29 a rejoint la partie
[08:50:36] [Render thread/INFO]: Received Dimension Type Sync
[08:50:36] [Render thread/INFO]: 
immersive_portals:alternate1 -> immersive_portals:surface_type
immersive_portals:alternate3 -> immersive_portals:surface_type
minecraft:the_nether -> minecraft:the_nether
minecraft:overworld -> minecraft:overworld
immersive_portals:alternate4 -> immersive_portals:surface_type
immersive_portals:alternate5 -> immersive_portals:surface_type
immersive_portals:alternate2 -> immersive_portals:surface_type
minecraft:the_end -> minecraft:the_end

[08:50:36] [Render thread/INFO]: Received Dimension Int Id Sync
[08:50:36] [Render thread/INFO]: 
minecraft:overworld -> 0
immersive_portals:alternate1 -> 2
immersive_portals:alternate2 -> 3
minecraft:the_nether -> -1
immersive_portals:alternate3 -> 4
immersive_portals:alternate4 -> 5
minecraft:the_end -> 1
immersive_portals:alternate5 -> 6
[08:50:36] [Render thread/INFO]: Reloading pipeline on dimension change: null => NETHER
[08:50:36] [Render thread/INFO]: Creating pipeline for dimension NETHER
[08:50:36] [Render thread/INFO]: WorldRenderer reloaded minecraft:the_nether
[08:50:36] [Render thread/INFO]: Started 6 worker threads
[08:50:37] [Render thread/INFO]: [CHAT] [Immersive Portals] You are using Sodium with Immersive Portals. The compatibility is not perfect. Rendering issues may occur. Disable warning
[08:50:37] [Render thread/INFO]: [CHAT] [Immersive Portals] You are using Iris with Immersive Portals. The compatibility is not perfect. Rendering issues may occur. Disable warning
[08:50:37] [Render thread/INFO]: Loaded 31 advancements
[08:50:37] [Render thread/INFO]: WorldRenderer reloaded minecraft:overworld
[08:50:37] [Render thread/INFO]: Started 6 worker threads
[08:50:37] [Render thread/INFO]: Client World Created minecraft:overworld
[08:50:38] [Render thread/WARN]: Unable to play empty soundEvent: minecraft:entity.cod.ambient
[08:50:39] [Render thread/INFO]: Created lightmap texture for minecraft:overworld
[08:50:39] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[08:50:39] [Render thread/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[08:50:39] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.coderbot.iris.pipeline.WorldRenderingPipeline.beginHand()" because "this.pipeline" is null
	at net.minecraft.class_761.handler$zpj000$iris$beginTranslucents(class_761.java:8350) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1483) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1034) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.redirect$zkp000$redirectRenderingWorld(class_757.java:2634) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:813) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1122) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[08:50:40] [Server thread/INFO]: Stopping server
[08:50:40] [Server thread/INFO]: Saving players
[08:50:40] [Server thread/INFO]: Lolothepro29 lost connection: Déconnecté(e)
[08:50:40] [Server thread/INFO]: Lolothepro29 a quitté la partie
[08:50:40] [Server thread/INFO]: Stopping singleplayer server as player logged out
[08:50:40] [Server thread/INFO]: Saving worlds
[08:50:41] [Server thread/INFO]: Saving chunks for level 'ServerWorld minecraft:overworld Nouveau monde'/minecraft:overworld
[08:50:42] [Server thread/INFO]: Saving chunks for level 'ServerWorld immersive_portals:alternate1 Nouveau monde'/immersive_portals:alternate1
[08:50:42] [Server thread/INFO]: Saving chunks for level 'ServerWorld immersive_portals:alternate3 Nouveau monde'/immersive_portals:alternate3
[08:50:42] [Server thread/INFO]: Saving chunks for level 'ServerWorld minecraft:the_nether Nouveau monde'/minecraft:the_nether
[08:50:42] [Server thread/INFO]: Saving chunks for level 'ServerWorld immersive_portals:alternate4 Nouveau monde'/immersive_portals:alternate4
[08:50:42] [Server thread/INFO]: Saving chunks for level 'ServerWorld immersive_portals:alternate5 Nouveau monde'/immersive_portals:alternate5
[08:50:42] [Server thread/INFO]: Saving chunks for level 'ServerWorld immersive_portals:alternate2 Nouveau monde'/immersive_portals:alternate2
[08:50:42] [Server thread/INFO]: Saving chunks for level 'ServerWorld minecraft:the_end Nouveau monde'/minecraft:the_end
[08:50:42] [Server thread/INFO]: ThreadedAnvilChunkStorage (Nouveau monde): All chunks are saved
[08:50:42] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate1): All chunks are saved
[08:50:42] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate3): All chunks are saved
[08:50:42] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[08:50:42] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate4): All chunks are saved
[08:50:42] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate5): All chunks are saved
[08:50:42] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate2): All chunks are saved
[08:50:42] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[08:50:42] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[08:50:42] [Render thread/INFO]: Stopping worker threads
[08:50:42] [Render thread/INFO]: Stopping worker threads
```

### Minecraft Version

Minecraft 1.18.2

### Iris Version

iris-mc-1.18.2

### Sodium Version

sodium 0.4.1

### Operating System

Ubuntu 22.04

### What is your GPU?

GTX 1070

### Java Version

Java 17

**Comment by qouteall** [comment]
Probably fixed in this version of immptl https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v1.3.9-1.18
