### ISSUE TITLE
Yshaders does not work with Iris

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1461]
### What happened?

Yshaders does not work with Iris

### Relevant log output

```shell
[17:08:16] [main/INFO]: Loading Minecraft 1.18.2 with Quilt Loader 0.16.0
[17:08:17] [main/INFO]: Loading 13 mods:
	- fabric-api-base 0.4.3+d7c144a8d2
	- fabric-command-api-v1 1.1.9+d7c144a860
	- fabric-key-binding-api-v1 1.0.11+54e5b2ecd2
	- fabric-rendering-data-attachment-v1 0.3.6+d7c144a8d2
	- fabric-rendering-fluids-v1 2.0.1+54e5b2ecd2
	- fabric-resource-loader-v0 0.4.16+55dca1a4d2
	- iris 1.2.4-build.38
	- java 17
	- minecraft 1.18.2
	- org_anarres_jcpp 1.4.14
	- org_joml_joml 1.10.2
	- quilt_loader 0.16.0
	- sodium 0.4.1+build.15
[17:08:17] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/********/.local/share/PolyMC/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[17:08:17] [main/INFO]: Compatibility level set to JAVA_16
[17:08:17] [main/INFO]: Compatibility level set to JAVA_17
[17:08:17] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[17:08:17] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[17:08:21] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[17:08:22] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:08:23] [Render thread/INFO]: Setting user: Lolothepro29
[17:08:23] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[17:08:23] [Render thread/WARN]: OpenGL debug context activated.
[17:08:24] [Render thread/INFO]: [GL] Using KHR_debug for error logging.
[17:08:24] [Render thread/INFO]: Debug functionality is enabled, logging will be more verbose!
[17:08:24] [Render thread/INFO]: Profile: Custom (+0 options changed by user)
[17:08:25] [Render thread/INFO]: Using shaderpack: §f» §e§lWerrus §8§lShaders §e§lV5.0.1 §4§lULTRA.zip
[17:08:25] [Render thread/WARN]: Couldn't get pack info for: net.minecraft.class_3266: 'pack.mcmeta' in ResourcePack '/mnt/76561DD3561D94C9/MultiMC/instances/1.18.2/.minecraft/resourcepacks/EM64D-main.zip'
[17:08:25] [Render thread/WARN]: Couldn't get pack info for: net.minecraft.class_3266: 'pack.mcmeta' in ResourcePack '/mnt/76561DD3561D94C9/MultiMC/instances/1.18.2/.minecraft/resourcepacks/BSL Minipacks.zip'
[17:08:26] [Render thread/INFO]: Hardware information:
[17:08:26] [Render thread/INFO]: CPU: 12x AMD Ryzen 5 1600 Six-Core Processor
[17:08:26] [Render thread/INFO]: GPU: NVIDIA GeForce GTX 1070/PCIe/SSE2 (Supports OpenGL 3.2.0 NVIDIA 515.43.04)
[17:08:26] [Render thread/INFO]: OS: Linux (5.17.0-9.1-liquorix-amd64)
[17:08:27] [Render thread/WARN]: Method overwrite conflict for getNativeMemoryUsage in sodium.mixins.json:features.debug.MixinDebugHud, previously written by net.coderbot.iris.mixin.MixinDebugScreenOverlay. Skipping method.
[17:08:27] [Render thread/INFO]: Narrator library successfully loaded
[17:08:27] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Rendering Data Attachment (v1), Fabric Resource Loader (v0), Fabric Command API (v1), Fabric Rendering Fluids (v1), Fabric API Base, Fabric Key Binding API (v1), Iris, Sodium, Quilt Loader)
[17:08:30] [Render thread/INFO]: OpenAL initialized on device Family 17h (Models 00h-0fh) HD Audio Controller Stéréo analogique
[17:08:30] [Render thread/INFO]: Sound engine started
[17:08:31] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[17:08:31] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[17:08:31] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[17:08:31] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[17:08:31] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[17:08:31] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[17:08:31] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[17:08:33] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[17:08:33] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[17:08:33] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[17:09:04] [Render thread/WARN]: Ignoring ambiguous boolean option WAVING_FIRE
[17:09:04] [Render thread/INFO]: Profile: Custom (+0 options changed by user)
[17:09:04] [Render thread/INFO]: Using shaderpack: yShaders - Ultra.zip
[17:09:04] [Render thread/WARN]: Ignoring ambiguous boolean option WAVING_FIRE
[17:09:04] [Render thread/INFO]: Profile: Custom (+0 options changed by user)
[17:09:04] [Render thread/INFO]: Using shaderpack: yShaders - Ultra.zip
[17:09:07] [Render thread/WARN]: Missing data pack mod:forge
[17:09:08] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[17:09:08] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[17:09:08] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[17:09:08] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[17:09:08] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[17:09:09] [Render thread/INFO]: Loaded 7 recipes
[17:09:09] [Render thread/INFO]: Loaded 1141 advancements
[17:09:10] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:09:10] [Server thread/INFO]: Starting integrated minecraft server version 1.18.2
[17:09:10] [Server thread/INFO]: Generating keypair
[17:09:10] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[17:09:11] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[17:09:11] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[17:09:11] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[17:09:12] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[17:09:12] [Render thread/INFO]: Préparation de la zone d'apparition : 4 %
[17:09:13] [Render thread/INFO]: Préparation de la zone d'apparition : 9 %
[17:09:13] [Render thread/INFO]: Préparation de la zone d'apparition : 24 %
[17:09:14] [Render thread/INFO]: Préparation de la zone d'apparition : 65 %
[17:09:14] [Render thread/INFO]: Time elapsed: 3952 ms
[17:09:14] [Server thread/INFO]: Changing view distance to 12, from 10
[17:09:14] [Server thread/INFO]: Changing simulation distance to 12, from 0
[17:09:15] [Server thread/WARN]: Ignoring unknown attribute 'forge:entity_gravity'
[17:09:15] [Server thread/INFO]: Lolothepro29[local:E:6dd48ba2] logged in with entity id 35 at (824.3000000119209, 64.7964188129728, 246.75677347417601)
[17:09:15] [Server thread/INFO]: Lolothepro29 a rejoint la partie
[17:09:15] [Render thread/INFO]: Reloading pipeline on dimension change: null => OVERWORLD
[17:09:15] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[17:09:15] [Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16
	at net.coderbot.iris.rendertarget.RenderTargets.get(RenderTargets.java:82) ~[iris-mc1.18.2-1.2.4-build.38.jar:?]
	at net.coderbot.iris.rendertarget.RenderTargets.createColorFramebuffer(RenderTargets.java:218) ~[iris-mc1.18.2-1.2.4-build.38.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:96) ~[iris-mc1.18.2-1.2.4-build.38.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:197) ~[iris-mc1.18.2-1.2.4-build.38.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:606) ~[iris-mc1.18.2-1.2.4-build.38.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) ~[iris-mc1.18.2-1.2.4-build.38.jar:?]
	at net.minecraft.class_310.handler$zbp000$iris$resetPipeline(class_310.java:3990) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_18097(class_310.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1481(class_310.java:2144) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11120(class_634.java:365) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1085) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.16.0.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.16.0.jar:?]
	at org.quiltmc.loader.launch.knot.KnotHelper.launchClient(KnotHelper.java:28) [quilt-loader-0.16.0.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:23) [quilt-loader-0.16.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[17:09:15] [Render thread/INFO]: Started 6 worker threads
[17:09:15] [Render thread/INFO]: [STDERR]: [LWJGL] OpenGL debug message
[17:09:15] [Render thread/INFO]: Loaded 292 advancements
[17:09:18] [Server thread/INFO]: Saving and pausing game...
[17:09:18] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Nouveau mondeftyhtfg]'/minecraft:overworld
[17:09:18] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Nouveau mondeftyhtfg]'/minecraft:the_nether
[17:09:18] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Nouveau mondeftyhtfg]'/minecraft:the_end
[17:09:18] [Server thread/INFO]: Lolothepro29 lost connection: Déconnecté(e)
[17:09:18] [Server thread/INFO]: Lolothepro29 a quitté la partie
[17:09:18] [Server thread/INFO]: Stopping singleplayer server as player logged out
[17:09:18] [Server thread/INFO]: Stopping server
[17:09:18] [Server thread/INFO]: Saving players
[17:09:18] [Server thread/INFO]: Saving worlds
[17:09:20] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Nouveau mondeftyhtfg]'/minecraft:overworld
[17:09:20] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Nouveau mondeftyhtfg]'/minecraft:the_nether
[17:09:20] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Nouveau mondeftyhtfg]'/minecraft:the_end
[17:09:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (Nouveau mondeftyhtfg): All chunks are saved
[17:09:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[17:09:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[17:09:20] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[17:09:20] [Render thread/INFO]: Stopping worker threads
[17:09:20] [Render thread/INFO]: Stopping!
```

### Minecraft Version

Minecraft 1.18.2

### Iris Version

iris-mc-1.18.2

### Sodium Version

sodium 0.4.1

### Operating System

Ubuntu 22.04

### What is your GPU?

GTX 1070

### Java Version

Java 17

**Comment by Lolothepro** [comment]
```
[13:11:28] [Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.ArrayIndexOutOfBoundsException: null
	at net.coderbot.iris.rendertarget.RenderTargets.get(RenderTargets.java:94) ~[iris-mc1.18.2-1.2.5-beta.1%20(1).jar:?]
	at net.coderbot.iris.rendertarget.RenderTargets.createColorFramebuffer(RenderTargets.java:259) ~[iris-mc1.18.2-1.2.5-beta.1%20(1).jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:97) ~[iris-mc1.18.2-1.2.5-beta.1%20(1).jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:221) ~[iris-mc1.18.2-1.2.5-beta.1%20(1).jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:635) [iris-mc1.18.2-1.2.5-beta.1%20(1).jar:?]
	at net.coderbot.iris.Iris$$Lambda$5137/0x00000000d02c5e40.apply(Unknown Source) [iris-mc1.18.2-1.2.5-beta.1%20(1).jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) [iris-mc1.18.2-1.2.5-beta.1%20(1).jar:?]
	at net.coderbot.iris.Iris.reload(Iris.java:577) [iris-mc1.18.2-1.2.5-beta.1%20(1).jar:?]
	at net.coderbot.iris.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:27) [iris-mc1.18.2-1.2.5-beta.1%20(1).jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:473) [iris-mc1.18.2-1.2.5-beta.1%20(1).jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.lambda$init$2(ShaderPackScreen.java:218) [iris-mc1.18.2-1.2.5-beta.1%20(1).jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen$$Lambda$9163/0x00000000a51570b0.onPress(Unknown Source) [iris-mc1.18.2-1.2.5-beta.1%20(1).jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:40) [client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) [client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:121) [client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) [client-intermediary.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.method_25402(ShaderPackScreen.java:172) [iris-mc1.18.2-1.2.5-beta.1%20(1).jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) [client-intermediary.jar:?]
	at net.minecraft.class_312$$Lambda$6309/0x0000000029528ff8.run(Unknown Source) [client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:492) [client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) [client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) [client-intermediary.jar:?]
	at net.minecraft.class_312$$Lambda$6308/0x0000000029527ca8.run(Unknown Source) [client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:103) [client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) [client-intermediary.jar:?]
	at net.minecraft.class_312$$Lambda$4986/0x00000000d01a6e10.invoke(Unknown Source) [client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) [lwjgl-glfw-3.3.1.jar:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) [lwjgl-3.3.1.jar:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) [lwjgl-glfw-3.3.1.jar:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197) [client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:310) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1147) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.16.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.16.1.jar:?]
	at org.quiltmc.loader.launch.knot.KnotHelper.launchClient(KnotHelper.java:28) [quilt-loader-0.16.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:23) [quilt-loader-0.16.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by Lolothepro** [comment]
[crash-2022-06-22_21.35.48-client.txt](https://github.com/IrisShaders/Iris/files/8960830/crash-2022-06-22_21.35.48-client.txt)

**Comment by coderbot16** [comment]
Relevant part:

```
/* DRAWBUFFERS:NNN3N5 */


    gl_FragData[5] = vec4(wspecmask,wave,GRa,visiblesun);
	gl_FragData[3] = vec4(color, land);
}
```

**Comment by Lolothepro** [comment]
https://bambosan.github.io/Water-Only-Shaders/ (1.0)
