### ISSUE TITLE
Potato Shaders crash the game

### ISSUE THREAD

**Issue by StereoMadnessss** [IrisShaders/Iris#1468]
### Minecraft Version

1.18.2

### Iris Version

iris-1.18.2-mc-1.2.4-build38

### Sodium Version

sodium-0.4.1-build15

### Operating System

MacOS 11.6.6

### What is your GPU?

Nvidia GT 750M

### Java Version

Java 18.0.1.1

### Reproduction Steps

1. Get Potato Shaders by RRe36
2. Put them in the shaders directory
3. Enable shaders and select it
4. The game will crash when trying to render the screen while joining a world

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 6/1/22, 9:15 PM
Description: Unexpected error

java.lang.RuntimeException: Shader program linking failed, see log for details
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at me.jellysquid.mods.sodium.client.gl.shader.GlProgram$Builder.link(GlProgram.java:113)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShader(IrisChunkProgramOverrides.java:155)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShaders(IrisChunkProgramOverrides.java:193)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.getProgramOverride(IrisChunkProgramOverrides.java:216)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.handler$ddn000$iris$begin(ShaderChunkRenderer.java:548)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:70)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:221)
	at net.minecraft.client.render.WorldRenderer.renderLayer(WorldRenderer:14466)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1241)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1034)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:813)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1122)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at net.minecraft.client.main.Main.main(Main:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.gl.shader.GlProgram$Builder.link(GlProgram.java:113)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShader(IrisChunkProgramOverrides.java:155)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShaders(IrisChunkProgramOverrides.java:193)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.getProgramOverride(IrisChunkProgramOverrides.java:216)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.handler$ddn000$iris$begin(ShaderChunkRenderer.java:548)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:70)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:221)
	at net.minecraft.class_761.method_3251(class_761.java:14466)
	at net.minecraft.class_761.method_22710(class_761.java:1241)
	at net.minecraft.class_757.method_3188(class_757.java:1034)

-- Affected level --
Details:
	All players: 1 total; [class_746['4194304'/1457, l='ClientLevel', x=4162.11, y=64.62, z=4001.75]]
	Chunk stats: 1024, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,63,14), Section: (at 0,15,14 in -2,3,0; chunk contains blocks -32,-64,0 to -17,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 16434 game time, 5085 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 7
	Reload reason: manual
	Finished: Yes
	Packs: Default, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, Programmer Art, Pre-Release Deepslate, golden-days-base-1.18-1.7.1 (2)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Mac OS X (x86_64) version 11.6.6
	Java Version: 18.0.1.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 806910672 bytes (769 MiB) / 1996488704 bytes (1904 MiB) up to 3221225472 bytes (3072 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
	Identifier: Intel64 Family 6 Model 70 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel Iris Pro
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 1536.00
	Graphics card #0 deviceId: 0x0d26
	Graphics card #0 versionInfo: Revision ID: 0x0008, gMux Version: 4.0.8 [3.2.8]
	Graphics card #1 name: NVIDIA GeForce GT 750M
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x0fe9
	Graphics card #1 versionInfo: Revision ID: 0x00a2, ROM Revision: 3776, gMux Version: 4.0.8 [3.2.8]
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 17408.00
	Virtual memory used (MB): 8801.33
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 54.50
	JVM Flags: 2 total; -Xms512m -Xmx3072m
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.18.2-fabric0.47.10-1.3.1
		animatica: Animatica 0.4+1.18
		architectury: Architectury 4.4.65
		betterf3: BetterF3 1.2.5
		bettermounthud: Better Mount HUD 1.1.4
		borderlessmining: Borderless Mining 1.1.2+1.18.2
		capes: Capes 1.3.1+1.18.2
			omega-config: OmegaConfig 1.2.3-1.18.1
		carpet: Carpet Mod 1.4.69
		cem: Custom Entity Models 0.7.1
		citresewn: CIT Resewn 1.0.1+1.18.2
			citresewn-defaults: CIT Resewn: Defaults 1.0.1+1.18.2
		cloth-api: Cloth API 3.2.64
			cloth-client-events-v0: Cloth Client Events v0 3.2.64
			cloth-common-events-v1: Cloth Common Events v1 3.2.64
			cloth-datagen-api-v1: Cloth Datagen v1 3.2.64
			cloth-scissors-api-v1: Cloth Scissors API v1 3.2.64
			cloth-utils-v1: Cloth Utils v1 3.2.64
		cloth-config: Cloth Config v6 6.2.57
			cloth-basic-math: cloth-basic-math 0.6.0
		colormatic: Colormatic 3.1.1+mc.1.18.2
		completeconfig: CompleteConfig 1.4.1
		continuity: Continuity 1.1.0+1.18.2
		cull-less-leaves: Cull Less Leaves 1.0.1
		custom-fog: Custom Fog 2.1.0-1.18.2
		customstars: Custom Stars 0.8+1.18.2
		customvoid: Custom Void 0.6+1.18.2
		damagetilt: Damage Tilt 1.18-fabric-0.1.2
		dcch: DCCH 2.0+1.17
		dynamicfps: Dynamic FPS 2.1.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		enhancedblockentities: Enhanced Block Entities 0.6+1.18.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		entity_texture_features: Entity Texture Features 3.0.0
		entityculling: EntityCulling-Fabric 1.5.1
		fabric: Fabric API 0.53.4+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.1+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.5+d82b939260
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.19+ffb2c71e60
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.16+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.0+85719ab760
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.12+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.4+d8d7804a60
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.1+81ea5b3c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
			fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.1+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.0+2afceb2960
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.2+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+bd8a4a1860
		fabric-language-kotlin: Fabric Language Kotlin 1.7.4+kotlin.1.6.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.21
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		fabrication: Fabrication 2.3.1-exp3
		fabricloader: Fabric Loader 0.14.5
		fabrishot: Fabrishot ${version}
		ferritecore: FerriteCore 4.2.1
		indium: Indium 1.0.3+mc1.18.2
		iris: Iris 1.2.4-build.38
			org_anarres_jcpp: jcpp 1.4.14
		isxander-main-menu-credits: Main Menu Credits 1.0.3
		itemmodelfix: Item Model Fix 1.0.3+1.18
		java: Java HotSpot(TM) 64-Bit Server VM 18
		lambdabettergrass: LambdaBetterGrass 1.2.3+1.18
			spruceui: SpruceUI 3.3.3+1.18
		lambdynlights: LambDynamicLights 2.1.0+1.17
			pride: Pride Lib 1.1.0+1.17
		languagereload: Language Reload 1.2.1
		lazydfu: LazyDFU 0.1.2
		lithium: Lithium 0.7.10
		midnightlib: MidnightLib 0.4.0
		minecraft: Minecraft 1.18.2
		modmenu: Mod Menu 3.2.2
		morechathistory: MoreChatHistory 1.1.0
		nofade: No Fade 1.18-2.0.1
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		optigui: OptiGUI 1.1.0
			org_apache_commons_commons-text: commons-text 1.9
		pling: Pling 1.5.0
		puzzle: Puzzle 1.2.1
			puzzle-base: Puzzle Base 1.2.1
			puzzle-gui: Puzzle GUI 1.2.1
			puzzle-models: Puzzle Models 1.2.1
			puzzle-splashscreen: Puzzle Splash Screen 1.2.1
		reeses-sodium-options: Reese's Sodium Options 1.4.2
		shaderreload: Shader Reload 1.7
		smoothboot: Smooth Boot 1.18.2-1.7.0
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		sodium-extra: Sodium Extra 0.4.4+mc1.18.2-build.39
			caffeineconfig: CaffeineConfig 1.1.0
		starlight: Starlight 1.0.2+fabric.89b8d9f
		tooltipfix: ToolTip Fix 1.0.4-1.18
		yosbr: YOSBR 0.1.1
		zoomify: Zoomify 1.6.0
			com_github_llamalad7_mixinextras: mixinextras 0.0.10
			dev_isxander_settxi: settxi 2.1.1
			settxicloth: Settxi Cloth Impl 1.0.2
	Loaded Shaderpack: Potato_v1.0b.zip
		Profile: Custom (+0 options changed by user)
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GT 750M OpenGL Engine GL version 4.1 NVIDIA-16.0.13 , NVIDIA Corporation
	Window size: 1708x960
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, programer_art, file/Pre-Release Deepslate (incompatible), file/golden-days-base-1.18-1.7.1 (2) (incompatible)
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['4194304'/1457, l='ServerLevel[New World]', x=4162.11, y=64.62, z=4001.75]]
	Data Packs: vanilla, Fabric Mods, file/hybrid-beta-1-18-2-v0-8-1.zip
	World Generation: Experimental
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Iris (iris), Sodium (sodium)
```

**Comment by coderbot16** [comment]
Caused by https://github.com/IrisShaders/Iris/issues/937, this is being worked on in https://github.com/IrisShaders/Iris/pull/1395 and related PRs.
