### ISSUE TITLE
[trunk] Error when compiling Iris without Sodium.

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1521]
### What happened?

\\

### Screenshots

\\

### Relevant log output

```shell
Using brachyura bootstrap 0
14:17:41.938 ERROR: /home/fujitsu/Iris-trunk/src/main/java/net/coderbot/iris/pipeline/PipelineManager.java:4: error: package me.jellysquid.mods.sodium.client.gl.device does not exist
import me.jellysquid.mods.sodium.client.gl.device.RenderDevice;
                                                 ^
14:17:41.943 ERROR: /home/fujitsu/Iris-trunk/src/main/java/net/coderbot/iris/pipeline/PipelineManager.java:5: error: package me.jellysquid.mods.sodium.client.render.chunk.passes does not exist
import me.jellysquid.mods.sodium.client.render.chunk.passes.BlockRenderPass;
                                                           ^
14:17:41.949 ERROR: /home/fujitsu/Iris-trunk/src/main/java/net/coderbot/iris/pipeline/PipelineManager.java:8: error: package net.coderbot.iris.compat.sodium.impl.shader_overrides does not exist
import net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides;
                                                            ^
14:17:43.066 ERROR: /home/fujitsu/Iris-trunk/src/main/java/net/coderbot/iris/vertices/IrisTextVertexSinkImpl.java:4: error: package net.coderbot.iris.compat.sodium.impl.vertex_format.entity_xhfp does not exist
import net.coderbot.iris.compat.sodium.impl.vertex_format.entity_xhfp.QuadViewEntity;
                                                                     ^
14:17:43.067 ERROR: /home/fujitsu/Iris-trunk/src/main/java/net/coderbot/iris/vertices/IrisTextVertexSinkImpl.java:15: error: package QuadViewEntity does not exist
        private final QuadViewEntity.QuadViewEntityUnsafe quad = new QuadViewEntity.QuadViewEntityUnsafe();
                                    ^
14:17:46.955 ERROR: /home/fujitsu/Iris-trunk/src/main/java/net/coderbot/iris/vertices/IrisTextVertexSinkImpl.java:15: error: package QuadViewEntity does not exist
        private final QuadViewEntity.QuadViewEntityUnsafe quad = new QuadViewEntity.QuadViewEntityUnsafe();
                                                                                   ^
14:17:47.715 INFO: Note: Some input files use or override a deprecated API.
14:17:47.715 INFO: Note: Recompile with -Xlint:deprecation for details.
14:17:47.715 INFO: Note: Some input files use unchecked or unsafe operations.
14:17:47.715 INFO: Note: Recompile with -Xlint:unchecked for details.
14:17:47.720 ERROR: Task Failed
14:17:47.720 ERROR: java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at io.github.coolcrabs.brachyura.project.java.BaseJavaProject.runRunConfig(BaseJavaProject.java:88)
        at io.github.coolcrabs.brachyura.project.java.BaseJavaProject.lambda$getRunConfigTasks$1(BaseJavaProject.java:54)
        at io.github.coolcrabs.brachyura.project.Task$NoArgTask.doTask(Task.java:53)
        at io.github.coolcrabs.brachyura.project.BrachyuraEntry.main(BrachyuraEntry.java:45)
        at io.github.coolcrabs.brachyura.bootstrap.Main.main(Main.java:74)
```

### Minecraft Version

1.16.5

### Iris Version

\\

### Sodium Version

\\

### Operating System

Ubuntu 22.04

### What is your GPU?

\\

### Java Version

Java 18

### Additional context

https://github.com/IrisShaders/Iris/blob/trunk/docs/development/sodium-compatibility.md

**Comment by NoComment1105** [comment]
Please provide more information, including the branch name in the form.

**Comment by Lolothepro** [comment]
?

**Comment by IMS212** [comment]
This is known, I need to fix this.
