### ISSUE TITLE
geometry shaders for gbuffers_entities will fail to compile

### ISSUE THREAD

**Issue by sonopsa** [IrisShaders/Iris#1525]
### What happened?

geometry shaders for gbuffers_entities that will work in opitifne will cause the pipeline to fail to compile in iris, ones for gbuffers_terrain will work fine

### Relevant log output

```shell
[13:20:44] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[13:20:44] [Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.RuntimeException: net.minecraft.class_2973: Invalid shaders/core/entities_alpha.json: Couldn't compile fragment program (<iris shaderpack shaders>, entities_alpha) : 0(78) : error C1503: undefined variable "iris_vertexColor"
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.lambda$new$9(NewWorldRenderingPipeline.java:319) ~[iris-mc1.19-1.2.5%20(1).jar:?]
	at net.coderbot.iris.pipeline.newshader.ShaderMap.<init>(ShaderMap.java:21) ~[iris-mc1.19-1.2.5%20(1).jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:306) ~[iris-mc1.19-1.2.5%20(1).jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:642) ~[iris-mc1.19-1.2.5%20(1).jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) [iris-mc1.19-1.2.5%20(1).jar:?]
	at net.coderbot.iris.Iris.reload(Iris.java:584) [iris-mc1.19-1.2.5%20(1).jar:?]
	at net.coderbot.iris.Iris.handleKeybinds(Iris.java:223) [iris-mc1.19-1.2.5%20(1).jar:?]
	at net.minecraft.class_310.handler$zcd000$iris$onTick(class_310.java:2877) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1869) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1101) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: net.minecraft.class_2973: Invalid shaders/core/entities_alpha.json: Couldn't compile fragment program (<iris shaderpack shaders>, entities_alpha) : 0(78) : error C1503: undefined variable "iris_vertexColor"
	at net.minecraft.class_2973.method_12856(class_2973.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:200) ~[client-intermediary.jar:?]
	at net.coderbot.iris.pipeline.newshader.ExtendedShader.<init>(ExtendedShader.java:52) ~[iris-mc1.19-1.2.5%20(1).jar:?]
	at net.coderbot.iris.pipeline.newshader.NewShaderTests.create(NewShaderTests.java:130) ~[iris-mc1.19-1.2.5%20(1).jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.createShader(NewWorldRenderingPipeline.java:392) ~[iris-mc1.19-1.2.5%20(1).jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.createShader(NewWorldRenderingPipeline.java:382) ~[iris-mc1.19-1.2.5%20(1).jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.lambda$new$9(NewWorldRenderingPipeline.java:315) ~[iris-mc1.19-1.2.5%20(1).jar:?]
	... 22 more
Caused by: java.io.IOException: Couldn't compile fragment program (<iris shaderpack shaders>, entities_alpha) : 0(78) : error C1503: undefined variable "iris_vertexColor"
	at net.minecraft.class_281.method_34416(class_281.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_281.method_1283(class_281.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.method_34579(class_5944.java:238) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:183) ~[client-intermediary.jar:?]
	at net.coderbot.iris.pipeline.newshader.ExtendedShader.<init>(ExtendedShader.java:52) ~[iris-mc1.19-1.2.5%20(1).jar:?]
	at net.coderbot.iris.pipeline.newshader.NewShaderTests.create(NewShaderTests.java:130) ~[iris-mc1.19-1.2.5%20(1).jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.createShader(NewWorldRenderingPipeline.java:392) ~[iris-mc1.19-1.2.5%20(1).jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.createShader(NewWorldRenderingPipeline.java:382) ~[iris-mc1.19-1.2.5%20(1).jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.lambda$new$9(NewWorldRenderingPipeline.java:315) ~[iris-mc1.19-1.2.5%20(1).jar:?]
	... 22 more
```

### Minecraft Version

Minecraft 1.19

### Iris Version

iris-mc1.19-1.2.5

### Sodium Version

sodium-fabric-mc1.19-0.4.2+build.16

### Operating System

Windows 10

### What is your GPU?

NVIDIA GeForce RTX 2060

### Java Version

Java 17

**Comment by coderbot16** [comment]
Please upload a full log file (`latest.log`). That will tell us the name of the shaderpack and other information needed to investigate the issue.

**Comment by IMS212** [comment]
I'm pretty sure I know the issue. We aren't passing through vertexColor and other attributes to the geometry stage correctly.

**Comment by sonopsa** [comment]
[entity_geometry_shader.zip](https://github.com/IrisShaders/Iris/files/9078116/entity_geometry_shader.zip)
[latest.log](https://github.com/IrisShaders/Iris/files/9078115/latest.log)

**Comment by IMS212** [comment]
Fixed in https://github.com/IrisShaders/Iris/commit/7c5565509a5849e832ca6a84dd55fe962e370e8e.
