### ISSUE TITLE
"GLSL source pre-processing failed" error when loading Chocapic13 Toaster shaders

### ISSUE THREAD

**Issue by MissingCiro** [IrisShaders/Iris#1537]
### What happened?

I'm playing on Minecraft 1.16.5

I placed my Shader on the shaderpacks folder, but when I made a new world, the shader didn't show up.

Using F3, there was a message that said "[Iris] shaderpack (off) check log"

I don't really know if there is something wrong in the log. (Maybe "Unable to download https://github.com/IrisShaders/Iris-Update-Index/releases/download/test/updateIndex.json"?)

So, here is the log.

### Minecraft Version

Minecraft 1.16.5

### Iris Version

Iris 1.16.5 - 1.2.5

### Sodium Version

sodium-fabric-mc1.16.5-0.2.0+build.4.jar

### Operating System

Linux (Debian)

### What is your GPU?

Integrated

### Java Version

Java 8

### Additional context

[00:42:51] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[00:42:51] [main/INFO]: Loading 10 mods:
	- fabric-api-base 0.4.0+3cc0f0907d via iris
	- fabric-key-binding-api-v1 1.0.5+3cc0f0907d via iris
	- fabric-resource-loader-v0 0.4.8+3cc0f0907d via iris
	- fabricloader 0.14.8
	- iris 1.2.5
	- java 8
	- minecraft 1.16.5
	- org_anarres_jcpp 1.4.14 via iris
	- org_slf4j_slf4j-api 1.7.12 via iris
	- sodium 0.2.0+build.4
[00:42:51] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/estudiante/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[00:42:52] [main/INFO]: Loaded configuration file for Sodium: 24 options available, 0 override(s) found
[00:43:05] [main/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder from mod sodium, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[00:43:07] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[00:43:07] [main/INFO]: Setting user: MissingCiroMC
[00:43:08] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[00:43:10] [main/INFO]: Debug functionality is disabled.
[00:43:10] [main/INFO]: Shaders are disabled because no valid shaderpack is selected
[00:43:10] [main/INFO]: Shaders are disabled
[00:43:10] [Thread-4/WARN]: [Iris Update Check] Unable to download https://github.com/IrisShaders/Iris-Update-Index/releases/download/test/updateIndex.json
[00:43:11] [main/WARN]: Removed resource pack file/VanillaTweaks_r235707.zip from options because it doesn't seem to exist anymore
[00:43:11] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=2 on mixins.iris.json:texture.MixinAbstractTexture from mod iris::handler$zdd000$iris$afterGenerateId exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[00:43:13] [main/INFO]: Hardware information:
[00:43:13] [main/INFO]: CPU: 2x Intel(R) Celeron(R) N4020 CPU @ 1.10GHz
[00:43:13] [main/INFO]: GPU: Mesa DRI Intel(R) UHD Graphics 600 (Geminilake 2x6)  (Supports OpenGL 3.0 Mesa 18.3.6)
[00:43:13] [main/INFO]: OS: Linux (4.19.0-18-amd64)
[00:43:15] [main/INFO]: Narrator library successfully loaded
[00:43:15] [main/INFO]: Creating pipeline for dimension OVERWORLD
[00:43:16] [main/INFO]: Reloading ResourceManager: Default, Saturated-v3.zip, Fabric Mods (Fabric API Base, Fabric Key Binding API (v1), Fabric Resource Loader (v0), Fabric Loader, Iris, Sodium)
[00:43:17] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[00:43:27] [Worker-Main-2/WARN]: Texture minecraft:entity/conduit/open_eye with size 8x8 limits mip level from 4 to 3
[00:43:27] [Worker-Main-2/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 3, because of minimum power of two: 8
[00:43:29] [main/INFO]: OpenAL initialized.
[00:43:29] [main/INFO]: Sound engine started
[00:43:32] [main/INFO]: Created: 512x1024x3 minecraft:textures/atlas/blocks.png-atlas
[00:43:32] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[00:43:32] [main/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[00:43:32] [main/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[00:43:32] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[00:43:32] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[00:43:32] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[00:43:34] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[00:43:34] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[00:43:34] [main/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[00:44:30] [main/INFO]: Destroying pipeline OVERWORLD
[00:44:31] [main/WARN]: Ignoring ambiguous string option shadowMapResolution
[00:44:31] [main/WARN]: Ignoring ambiguous string option ambientOcclusionLevel
[00:44:31] [main/WARN]: Unable to resolve shader pack option menu element "shadowMapResolution" defined in shaders.properties
[00:44:31] [main/WARN]: Unable to resolve shader pack option menu element "sunPathRotation" defined in shaders.properties
[00:44:31] [main/WARN]: Unable to resolve shader pack option menu element "ambientOcclusionLevel" defined in shaders.properties
[00:44:31] [main/WARN]: Unable to resolve shader pack option menu element "CLOUDS" defined in shaders.properties
[00:44:31] [main/WARN]: Unable to resolve shader pack option menu element "STARS" defined in shaders.properties
[00:44:31] [main/WARN]: Unable to resolve shader pack option menu element "DRAW_SUN" defined in shaders.properties
[00:44:31] [main/INFO]: Profile: Custom (+0 options changed by user)
[00:44:31] [main/ERROR]: Failed to load the shaderpack "Chocapic13_HighPerformance_Toaster.zip"!
[00:44:31] [main/ERROR]: 
java.lang.RuntimeException: GLSL source pre-processing failed
	at net.coderbot.iris.shaderpack.preprocessor.JcppProcessor.glslPreprocessSource(JcppProcessor.java:61) ~[iris-mc1.16.5-1.2.5.jar:?]
	at net.coderbot.iris.shaderpack.ShaderPack.lambda$new$4(ShaderPack.java:176) ~[iris-mc1.16.5-1.2.5.jar:?]
	at net.coderbot.iris.shaderpack.ProgramSet.readProgramSource(ProgramSet.java:323) ~[iris-mc1.16.5-1.2.5.jar:?]
	at net.coderbot.iris.shaderpack.ProgramSet.readProgramSource(ProgramSet.java:309) ~[iris-mc1.16.5-1.2.5.jar:?]
	at net.coderbot.iris.shaderpack.ProgramSet.readProgramArray(ProgramSet.java:129) ~[iris-mc1.16.5-1.2.5.jar:?]
	at net.coderbot.iris.shaderpack.ProgramSet.<init>(ProgramSet.java:94) ~[iris-mc1.16.5-1.2.5.jar:?]
	at net.coderbot.iris.shaderpack.ShaderPack.<init>(ShaderPack.java:181) ~[iris-mc1.16.5-1.2.5.jar:?]
	at net.coderbot.iris.Iris.loadExternalShaderpack(Iris.java:365) ~[iris-mc1.16.5-1.2.5.jar:?]
	at net.coderbot.iris.Iris.loadShaderpack(Iris.java:289) ~[iris-mc1.16.5-1.2.5.jar:?]
	at net.coderbot.iris.Iris.reload(Iris.java:576) ~[iris-mc1.16.5-1.2.5.jar:?]
	at net.coderbot.iris.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:27) ~[iris-mc1.16.5-1.2.5.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:471) ~[iris-mc1.16.5-1.2.5.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.lambda$init$2(ShaderPackScreen.java:216) ~[iris-mc1.16.5-1.2.5.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:149) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[client-intermediary.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.method_25402(ShaderPackScreen.java:170) ~[iris-mc1.16.5-1.2.5.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:92) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:435) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:92) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:162) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:162) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) [lwjgl-glfw-3.2.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102) [client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:308) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1068) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
Caused by: org.anarres.cpp.InternalException: Bad token [ @146,0]:" "
	at org.anarres.cpp.Preprocessor._token(Preprocessor.java:1919) ~[org_anarres_jcpp-1.4.14-63555bd60a187a13.jar:?]
	at org.anarres.cpp.Preprocessor.token(Preprocessor.java:2144) ~[org_anarres_jcpp-1.4.14-63555bd60a187a13.jar:?]
	at net.coderbot.iris.shaderpack.preprocessor.JcppProcessor.glslPreprocessSource(JcppProcessor.java:55) ~[iris-mc1.16.5-1.2.5.jar:?]
	... 34 more
[00:44:31] [main/WARN]: Falling back to normal rendering without shaders because the shaderpack could not be loaded
[00:44:31] [main/INFO]: Shaders are disabled
[00:45:54] [main/INFO]: Flushed changes to Minecraft configuration
[00:46:10] [main/INFO]: Reloading ResourceManager: Default, Saturated-v3.zip, Fabric Mods (Fabric API Base, Fabric Key Binding API (v1), Fabric Resource Loader (v0), Fabric Loader, Iris, Sodium), VanillaTweaks_r999605.zip
[00:46:13] [Worker-Main-9/WARN]: Found 'parent' loop while loading model 'minecraft:item/bow' in chain: minecraft:item/bow -> minecraft:item/bow
[00:46:13] [Worker-Main-11/ERROR]: Using missing texture, unable to load minecraft:textures/item/crossbow.png : java.io.FileNotFoundException: minecraft:textures/item/crossbow.png
[00:46:14] [Worker-Main-9/WARN]: Texture minecraft:block/lever_base_on with size 8x8 limits mip level from 4 to 3
[00:46:14] [Worker-Main-9/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 3, because of minimum power of two: 8
[00:46:15] [main/INFO]: OpenAL initialized.
[00:46:15] [main/INFO]: Sound engine started
[00:46:16] [main/INFO]: Created: 512x1024x3 minecraft:textures/atlas/blocks.png-atlas
[00:46:16] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[00:46:16] [main/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[00:46:16] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/shield_patterns.png-atlas
[00:46:16] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[00:46:16] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[00:46:16] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[00:46:17] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/particles.png-atlas
[00:46:17] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[00:46:17] [main/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[00:46:29] [main/INFO]: Attempt 1...
[00:46:31] [main/INFO]: Attempt 1...
[00:46:33] [main/INFO]: Attempt 1...
[00:46:50] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[00:46:50] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[00:46:50] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[00:46:50] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[00:46:50] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[00:46:50] [main/INFO]: Reloading ResourceManager: Default
[00:46:51] [main/INFO]: Loaded 7 recipes
[00:46:51] [main/INFO]: Loaded 927 advancements
[00:46:53] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[00:46:53] [Server thread/INFO]: Starting integrated minecraft server version 1.16.5
[00:46:53] [Server thread/INFO]: Generating keypair
[00:46:56] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[00:46:56] [main/INFO]: Preparing spawn area: 0%
[00:46:56] [main/INFO]: Preparing spawn area: 0%
[00:46:57] [main/INFO]: Preparing spawn area: 0%
[00:46:57] [main/INFO]: Preparing spawn area: 1%
[00:46:58] [main/INFO]: Preparing spawn area: 3%
[00:46:58] [main/INFO]: Preparing spawn area: 4%
[00:46:59] [main/INFO]: Preparing spawn area: 6%
[00:46:59] [main/INFO]: Preparing spawn area: 7%
[00:47:00] [main/INFO]: Preparing spawn area: 10%
[00:47:00] [main/INFO]: Preparing spawn area: 13%
[00:47:01] [main/INFO]: Preparing spawn area: 16%
[00:47:01] [main/INFO]: Preparing spawn area: 19%
[00:47:02] [main/INFO]: Preparing spawn area: 23%
[00:47:03] [main/INFO]: Preparing spawn area: 24%
[00:47:03] [main/INFO]: Preparing spawn area: 30%
[00:47:03] [main/INFO]: Preparing spawn area: 33%
[00:47:04] [main/INFO]: Preparing spawn area: 36%
[00:47:04] [main/INFO]: Preparing spawn area: 39%
[00:47:05] [main/INFO]: Preparing spawn area: 42%
[00:47:05] [main/INFO]: Preparing spawn area: 46%
[00:47:06] [main/INFO]: Preparing spawn area: 48%
[00:47:06] [main/INFO]: Preparing spawn area: 52%
[00:47:07] [main/INFO]: Preparing spawn area: 55%
[00:47:07] [main/INFO]: Preparing spawn area: 57%
[00:47:08] [main/INFO]: Preparing spawn area: 63%
[00:47:08] [main/INFO]: Preparing spawn area: 68%
[00:47:09] [main/INFO]: Preparing spawn area: 70%
[00:47:10] [main/INFO]: Preparing spawn area: 75%
[00:47:10] [main/INFO]: Preparing spawn area: 81%
[00:47:10] [main/INFO]: Preparing spawn area: 86%
[00:47:11] [main/INFO]: Preparing spawn area: 90%
[00:47:12] [main/INFO]: Preparing spawn area: 91%
[00:47:12] [main/INFO]: Preparing spawn area: 91%
[00:47:12] [main/INFO]: Time elapsed: 16055 ms
[00:47:12] [Server thread/INFO]: Changing view distance to 5, from 10
[00:47:18] [Server thread/INFO]: MissingCiroMC[local:E:920b6a4b] logged in with entity id 29 at (124.5, 4.0, -233.5)
[00:47:18] [Server thread/INFO]: MissingCiroMC joined the game
[00:47:20] [main/INFO]: Started 2 worker threads
[00:47:20] [Server thread/INFO]: Saving and pausing game...
[00:47:20] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:overworld
[00:47:20] [main/INFO]: Loaded 0 advancements
[00:47:20] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_nether
[00:47:20] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_end
[00:47:21] [main/INFO]: Creating pipeline for dimension OVERWORLD
[00:47:21] [main/INFO]: Stopping worker threads
[00:47:21] [main/INFO]: Started 2 worker threads
[00:47:46] [Server thread/INFO]: Saving and pausing game...
[00:47:46] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:overworld
[00:47:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_nether
[00:47:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_end
[00:48:25] [Server thread/INFO]: Saving and pausing game...
[00:48:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:overworld
[00:48:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_nether
[00:48:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_end
[00:48:36] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric API Base, Fabric Key Binding API (v1), Fabric Resource Loader (v0), Fabric Loader, Iris, Sodium)
[00:48:43] [main/INFO]: OpenAL initialized.
[00:48:43] [main/INFO]: Sound engine started
[00:48:44] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[00:48:44] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[00:48:44] [main/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[00:48:44] [main/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[00:48:44] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[00:48:44] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[00:48:44] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[00:48:45] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[00:48:45] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[00:48:45] [main/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[00:48:45] [main/INFO]: Stopping worker threads
[00:48:45] [main/INFO]: Started 2 worker threads
[00:48:57] [Server thread/INFO]: Saving and pausing game...
[00:48:57] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:overworld
[00:48:57] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_nether
[00:48:57] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_end
[00:49:56] [Server thread/INFO]: Saving and pausing game...
[00:49:56] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:overworld
[00:49:57] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_nether
[00:49:57] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_end
[00:50:38] [Server thread/INFO]: Saving and pausing game...
[00:50:38] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:overworld
[00:50:38] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_nether
[00:50:38] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_end
[00:50:41] [Server thread/INFO]: Saving and pausing game...
[00:50:41] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:overworld
[00:50:41] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_nether
[00:50:41] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_end
[00:50:46] [main/INFO]: Stopping worker threads
[00:50:46] [main/INFO]: Started 2 worker threads
[00:50:46] [main/INFO]: Flushed changes to Minecraft configuration
[00:50:47] [Server thread/INFO]: Changing view distance to 7, from 5
[00:50:59] [Server thread/INFO]: Saving and pausing game...
[00:50:59] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:overworld
[00:50:59] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_nether
[00:50:59] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_end
[00:51:07] [main/INFO]: Stopping worker threads
[00:51:07] [main/INFO]: Started 2 worker threads
[00:51:07] [main/INFO]: Flushed changes to Minecraft configuration
[00:51:28] [Server thread/INFO]: Saving and pausing game...
[00:51:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:overworld
[00:51:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_nether
[00:51:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_end
[00:51:32] [main/INFO]: Stopping worker threads
[00:51:32] [main/INFO]: Started 2 worker threads
[00:51:32] [main/INFO]: Flushed changes to Minecraft configuration
[00:51:47] [Server thread/INFO]: Saving and pausing game...
[00:51:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:overworld
[00:51:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_nether
[00:51:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_end
[00:51:53] [main/INFO]: Flushed changes to Minecraft configuration
[00:52:07] [Server thread/INFO]: Saving and pausing game...
[00:52:07] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:overworld
[00:52:07] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_nether
[00:52:07] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_end
[00:52:11] [Server thread/INFO]: Saving and pausing game...
[00:52:11] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:overworld
[00:52:11] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_nether
[00:52:11] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_end
[00:52:56] [Server thread/INFO]: MissingCiroMC lost connection: Disconnected
[00:52:56] [Server thread/INFO]: MissingCiroMC left the game
[00:52:56] [Server thread/INFO]: Stopping singleplayer server as player logged out
[00:52:56] [Server thread/INFO]: Stopping server
[00:52:56] [Server thread/INFO]: Saving players
[00:52:56] [Server thread/INFO]: Saving worlds
[00:52:56] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:overworld
[00:52:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (Flat): All chunks are saved
[00:52:56] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_nether
[00:52:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[00:52:56] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Flat]'/minecraft:the_end
[00:52:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[00:52:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (Flat): All chunks are saved
[00:52:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[00:52:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[00:52:56] [main/INFO]: Stopping worker threads
[00:53:12] [main/INFO]: Stopping!

**Comment by coderbot16** [comment]
The shaders you are trying to load are not supported, you should try another shader pack.

But this is certainly an interesting crash I haven't seen before:

```
[00:44:31] [main/ERROR]: Failed to load the shaderpack "Chocapic13_HighPerformance_Toaster.zip"!
[00:44:31] [main/ERROR]:
java.lang.RuntimeException: GLSL source pre-processing failed
at net.coderbot.iris.shaderpack.preprocessor.JcppProcessor.glslPreprocessSource(JcppProcessor.java:61) ~[iris-mc1.16.5-1.2.5.jar:?]
at net.coderbot.iris.shaderpack.ShaderPack.lambda$new$4(ShaderPack.java:176) ~[iris-mc1.16.5-1.2.5.jar:?]
at net.coderbot.iris.shaderpack.ProgramSet.readProgramSource(ProgramSet.java:323) ~[iris-mc1.16.5-1.2.5.jar:?]
at net.coderbot.iris.shaderpack.ProgramSet.readProgramSource(ProgramSet.java:309) ~[iris-mc1.16.5-1.2.5.jar:?]
at net.coderbot.iris.shaderpack.ProgramSet.readProgramArray(ProgramSet.java:129) ~[iris-mc1.16.5-1.2.5.jar:?]
at net.coderbot.iris.shaderpack.ProgramSet.(ProgramSet.java:94) ~[iris-mc1.16.5-1.2.5.jar:?]
at net.coderbot.iris.shaderpack.ShaderPack.(ShaderPack.java:181) ~[iris-mc1.16.5-1.2.5.jar:?]
at net.coderbot.iris.Iris.loadExternalShaderpack(Iris.java:365) ~[iris-mc1.16.5-1.2.5.jar:?]
at net.coderbot.iris.Iris.loadShaderpack(Iris.java:289) ~[iris-mc1.16.5-1.2.5.jar:?]
at net.coderbot.iris.Iris.reload(Iris.java:576) ~[iris-mc1.16.5-1.2.5.jar:?]
at net.coderbot.iris.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:27) ~[iris-mc1.16.5-1.2.5.jar:?]
at net.coderbot.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:471) ~[iris-mc1.16.5-1.2.5.jar:?]
at net.coderbot.iris.gui.screen.ShaderPackScreen.lambda$init$2(ShaderPackScreen.java:216) ~[iris-mc1.16.5-1.2.5.jar:?]
at net.minecraft.class_4185.method_25306(class_4185.java:33) ~[client-intermediary.jar:?]
at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[client-intermediary.jar:?]
at net.minecraft.class_339.method_25402(class_339.java:149) ~[client-intermediary.jar:?]
at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[client-intermediary.jar:?]
at net.coderbot.iris.gui.screen.ShaderPackScreen.method_25402(ShaderPackScreen.java:170) ~[iris-mc1.16.5-1.2.5.jar:?]
at net.minecraft.class_312.method_1611(class_312.java:92) ~[client-intermediary.jar:?]
at net.minecraft.class_437.method_25412(class_437.java:435) ~[client-intermediary.jar:?]
at net.minecraft.class_312.method_1601(class_312.java:92) ~[client-intermediary.jar:?]
at net.minecraft.class_312.method_22686(class_312.java:162) ~[client-intermediary.jar:?]
at net.minecraft.class_1255.execute(class_1255.java:94) ~[client-intermediary.jar:?]
at net.minecraft.class_312.method_22684(class_312.java:162) ~[client-intermediary.jar:?]
at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:?]
at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:?]
at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) [lwjgl-glfw-3.2.2.jar:?]
at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102) [client-intermediary.jar:?]
at net.minecraft.class_1041.method_15998(class_1041.java:308) [client-intermediary.jar:?]
at net.minecraft.class_310.method_1523(class_310.java:1068) [client-intermediary.jar:?]
at net.minecraft.class_310.method_1514(class_310.java:681) [client-intermediary.jar:?]
at net.minecraft.client.main.Main.main(Main.java:215) [client-intermediary.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
Caused by: org.anarres.cpp.InternalException: Bad token [ https://github.com/146,0]:" "
at org.anarres.cpp.Preprocessor._token(Preprocessor.java:1919) ~[org_anarres_jcpp-1.4.14-63555bd60a187a13.jar:?]
at org.anarres.cpp.Preprocessor.token(Preprocessor.java:2144) ~[org_anarres_jcpp-1.4.14-63555bd60a187a13.jar:?]
at net.coderbot.iris.shaderpack.preprocessor.JcppProcessor.glslPreprocessSource(JcppProcessor.java:55) ~[iris-mc1.16.5-1.2.5.jar:?]
... 34 more
```

**Comment by Lolothepro** [comment]
???

**Comment by coderbot16** [comment]
I don't understand.

**Comment by IMS212** [comment]
This has been fixed for a while.
