### ISSUE TITLE
Crash on Startup with AE2 alpha

### ISSUE THREAD

**Issue by SyndaKitty** [IrisShaders/Iris#1540]
### Minecraft Version

Minecraft 1.19

### Iris Version

iris-mc1.19-1.2.5.jar

### Sodium Version

sodium-fabric-mc1.19-0.4.2+build.16.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce 1080 Ti

### Java Version

Java 17?

### Reproduction Steps

1. Have Applied Energistics 2 installed: appliedenergistics2-12.0.1-alpha.jar
2. Try to launch the game
3. Game crashes on startup :(

### Crash Report file and latest.log

```shell
[10:56:07] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
[10:56:07] [main/INFO]: Loading 58 mods:
	- ae2 12.0.1-alpha
	- fabric 0.57.0+1.19
	- fabric-api-base 0.4.9+e62f51a3a9 via fabric
	- fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
	- fabric-biome-api-v1 9.0.14+b2a4a624a9 via fabric
	- fabric-blockrenderlayer-v1 1.1.18+9ff28f40a9 via fabric
	- fabric-command-api-v1 1.2.6+f71b366fa9 via fabric
	- fabric-command-api-v2 2.1.2+0d55f585a9 via fabric
	- fabric-commands-v0 0.2.23+df3654b3a9 via fabric
	- fabric-containers-v0 0.1.27+df3654b3a9 via fabric
	- fabric-content-registries-v0 3.2.0+07df213ea9 via fabric
	- fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
	- fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
	- fabric-data-generation-api-v1 5.1.1+a680b9b4a9 via fabric
	- fabric-dimensions-v1 2.1.28+a6d2f785a9 via fabric
	- fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
	- fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
	- fabric-events-lifecycle-v0 0.2.25+df3654b3a9 via fabric
	- fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
	- fabric-item-api-v1 1.5.4+767db26ea9 via fabric
	- fabric-item-groups-v0 0.3.25+9ff28f40a9 via fabric
	- fabric-key-binding-api-v1 1.0.18+9ff28f40a9 via fabric
	- fabric-keybindings-v0 0.2.16+df3654b3a9 via fabric
	- fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via fabric
	- fabric-loot-api-v2 1.1.0+03a4e568a9 via fabric
	- fabric-loot-tables-v1 1.1.3+9e7660c6a9 via fabric
	- fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
	- fabric-mining-level-api-v1 2.1.10+33fbc738a9 via fabric
	- fabric-models-v0 0.3.15+9ff28f40a9 via fabric
	- fabric-networking-api-v1 1.0.27+7fe97409a9 via fabric
	- fabric-networking-v0 0.3.14+df3654b3a9 via fabric
	- fabric-object-builder-api-v1 4.0.7+9ff28f40a9 via fabric
	- fabric-particles-v1 1.0.8+dc39553aa9 via fabric
	- fabric-registry-sync-v0 0.9.17+23c4cfefa9 via fabric
	- fabric-renderer-api-v1 1.0.8+9ff28f40a9 via fabric
	- fabric-renderer-indigo 0.6.9+1f92344ea9 via fabric
	- fabric-renderer-registries-v1 3.2.18+df3654b3a9 via fabric
	- fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
	- fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
	- fabric-rendering-v0 1.1.20+df3654b3a9 via fabric
	- fabric-rendering-v1 1.10.14+9ff28f40a9 via fabric
	- fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-resource-loader-v0 0.5.5+a6d2f785a9 via fabric
	- fabric-screen-api-v1 1.0.24+f05effafa9 via fabric
	- fabric-screen-handler-api-v1 1.2.6+9ff28f40a9 via fabric
	- fabric-textures-v0 1.0.18+9ff28f40a9 via fabric
	- fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
	- fabricloader 0.14.8
	- iris 1.2.5
	- java 17
	- minecraft 1.19
	- noindium 1.0.2+1.18.2 via ae2
	- omega-config 1.2.3-1.18.1 via noindium
	- org_anarres_jcpp 1.4.14 via iris
	- org_joml_joml 1.10.4 via sodium
	- sodium 0.4.2+build.16
	- team_reborn_energy 2.0.0-beta1 via ae2
[10:56:07] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/miste/curseforge/minecraft/Install/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[10:56:07] [main/INFO]: Compatibility level set to JAVA_11
[10:56:07] [main/INFO]: Compatibility level set to JAVA_16
[10:56:07] [main/INFO]: Compatibility level set to JAVA_17
[10:56:07] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[10:56:08] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[10:56:09] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[10:56:09] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[10:56:12] [main/INFO]: Building optimized datafixer
[10:56:16] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder from mod sodium, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[10:56:16] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10:56:17] [Render thread/INFO]: Setting user: SyndaKai
[10:56:19] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=2 on mixins.iris.json:texture.MixinAbstractTexture from mod iris::handler$znh000$iris$afterGenerateId exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[10:56:19] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_23182 in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[10:56:19] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[10:56:19] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[10:56:20] [ForkJoinPool.commonPool-worker-1/WARN]: [Iris Update Check] Unable to download https://github.com/IrisShaders/Iris-Update-Index/releases/download/test/updateIndex.json
[10:56:20] [Render thread/INFO]: Debug functionality is disabled.
[10:56:21] [Render thread/INFO]: Profile: HIGH (+0 options changed by user)
[10:56:23] [Render thread/INFO]: Using shaderpack: ComplementaryShaders_v4.3.3.zip
[10:56:24] [Render thread/INFO]: Hardware information:
[10:56:24] [Render thread/INFO]: CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
[10:56:24] [Render thread/INFO]: GPU: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2 (Supports OpenGL 3.2.0 NVIDIA 516.40)
[10:56:24] [Render thread/INFO]: OS: Windows 10 (10.0)
[10:56:24] [Render thread/INFO]: Narrator library for x64 successfully loaded
[10:56:25] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Applied Energistics 2, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Iris, No Indium?, OmegaConfig, Sodium, Energy)
[10:56:25] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[10:56:27] [Render thread/WARN]: [Triforce Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[10:56:29] [Render thread/ERROR]: Unhandled game exception
java.lang.NoClassDefFoundError: net/minecraft/class_2554
	at me.luligabi.noindium.NoIndium.lambda$onInitializeClient$0(NoIndium.java:17) ~[noindium-1.0.2+1.18.2-fc3085c44c283db4.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:38) ~[fabric-lifecycle-events-v1-2.1.0+33fbc738a9-c697e79f4c4115d8.jar:?]
	at net.minecraft.class_310.handler$zfh000$onStart(class_310.java:4901) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:713) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2554
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 8 more
[10:56:29] [Render thread/INFO]: Stopping!
[10:56:29] [Render thread/ERROR]: Shutdown failure!
java.util.ConcurrentModificationException: null
	at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?]
	at net.minecraft.class_1060.close(class_1060.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.close(class_310.java:1058) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1490(class_310.java:1034) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
```

**Comment by coderbot16** [comment]
This seems to be an issue with [No Indium](https://modrinth.com/mod/no-indium) which is likely included in the AE2 alpha. I don't think this is caused by Iris itself and is likely only indirectly caused by the presence of Sodium - since the whole point of the linked mod is to warn the user when Sodium is detected without Indium installed.

You might want to instead report this to the AE2 repository. You can probably work around the issue by installing Indium and bypassing the mod prompt.
