### ISSUE TITLE
Using SEUS Renewed on Steam Deck doesn't work

### ISSUE THREAD

**Issue by supaman360** [IrisShaders/Iris#1546]
### Minecraft Version

1.19

### Iris Version

iris-mc1.19-1.2.5

### Sodium Version

sodium-fabric-mc1.19-0.4.2+build.16

### Operating System

Steam OS

### What is your GPU?

AMD Custom GPU 0405

### Java Version

17.0.1

### Reproduction Steps

Just apply the shader pack and it will say somthing about checking the logs.

### Crash Report file and latest.log

```shell
[11:54:54] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
[11:54:55] [main/INFO]: Loading 54 mods:
	- fabric 0.57.0+1.19
	- fabric-api-base 0.4.9+e62f51a3a9 via fabric
	- fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
	- fabric-biome-api-v1 9.0.14+b2a4a624a9 via fabric
	- fabric-blockrenderlayer-v1 1.1.18+9ff28f40a9 via fabric
	- fabric-command-api-v1 1.2.6+f71b366fa9 via fabric
	- fabric-command-api-v2 2.1.2+0d55f585a9 via fabric
	- fabric-commands-v0 0.2.23+df3654b3a9 via fabric
	- fabric-containers-v0 0.1.27+df3654b3a9 via fabric
	- fabric-content-registries-v0 3.2.0+07df213ea9 via fabric
	- fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
	- fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
	- fabric-data-generation-api-v1 5.1.1+a680b9b4a9 via fabric
	- fabric-dimensions-v1 2.1.28+a6d2f785a9 via fabric
	- fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
	- fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
	- fabric-events-lifecycle-v0 0.2.25+df3654b3a9 via fabric
	- fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
	- fabric-item-api-v1 1.5.4+767db26ea9 via fabric
	- fabric-item-groups-v0 0.3.25+9ff28f40a9 via fabric
	- fabric-key-binding-api-v1 1.0.18+9ff28f40a9 via fabric
	- fabric-keybindings-v0 0.2.16+df3654b3a9 via fabric
	- fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via fabric
	- fabric-loot-api-v2 1.1.0+03a4e568a9 via fabric
	- fabric-loot-tables-v1 1.1.3+9e7660c6a9 via fabric
	- fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
	- fabric-mining-level-api-v1 2.1.10+33fbc738a9 via fabric
	- fabric-models-v0 0.3.15+9ff28f40a9 via fabric
	- fabric-networking-api-v1 1.0.27+7fe97409a9 via fabric
	- fabric-networking-v0 0.3.14+df3654b3a9 via fabric
	- fabric-object-builder-api-v1 4.0.7+9ff28f40a9 via fabric
	- fabric-particles-v1 1.0.8+dc39553aa9 via fabric
	- fabric-registry-sync-v0 0.9.17+23c4cfefa9 via fabric
	- fabric-renderer-api-v1 1.0.8+9ff28f40a9 via fabric
	- fabric-renderer-indigo 0.6.9+1f92344ea9 via fabric
	- fabric-renderer-registries-v1 3.2.18+df3654b3a9 via fabric
	- fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
	- fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
	- fabric-rendering-v0 1.1.20+df3654b3a9 via fabric
	- fabric-rendering-v1 1.10.14+9ff28f40a9 via fabric
	- fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-resource-loader-v0 0.5.5+a6d2f785a9 via fabric
	- fabric-screen-api-v1 1.0.24+f05effafa9 via fabric
	- fabric-screen-handler-api-v1 1.2.6+9ff28f40a9 via fabric
	- fabric-textures-v0 1.0.18+9ff28f40a9 via fabric
	- fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
	- fabricloader 0.14.8
	- iris 1.2.5
	- java 17
	- minecraft 1.19
	- org_anarres_jcpp 1.4.14 via iris
	- org_joml_joml 1.10.4 via sodium
	- sodium 0.4.2+build.16
[11:54:55] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/deck/.var/app/org.polymc.PolyMC/data/PolyMC/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[11:54:55] [main/INFO]: Compatibility level set to JAVA_16
[11:54:55] [main/INFO]: Compatibility level set to JAVA_17
[11:54:55] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[11:54:56] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[11:54:57] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[11:54:57] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[11:55:02] [main/INFO]: Building optimized datafixer
[11:55:10] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder from mod sodium, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[11:55:11] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11:55:12] [Render thread/INFO]: Setting user: AnonOne666
[11:55:13] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[11:55:13] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[11:55:13] [ForkJoinPool.commonPool-worker-1/WARN]: [Iris Update Check] Unable to download https://github.com/IrisShaders/Iris-Update-Index/releases/download/test/updateIndex.json
[11:55:14] [Render thread/INFO]: Debug functionality is disabled.
[11:55:14] [Render thread/ERROR]: Failed to load the shaderpack "SEUS-Renewed-v1.0.1.zip" because it does not exist in your shaderpacks folder!
[11:55:14] [Render thread/WARN]: Falling back to normal rendering without shaders because the shaderpack could not be loaded
[11:55:14] [Render thread/INFO]: Shaders are disabled
[11:55:15] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=2 on mixins.iris.json:texture.MixinAbstractTexture from mod iris::handler$zlo000$iris$afterGenerateId exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[11:55:16] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_23182 in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[11:55:17] [Render thread/INFO]: Hardware information:
[11:55:17] [Render thread/INFO]: CPU: 8x AMD Custom APU 0405
[11:55:17] [Render thread/INFO]: GPU: AMD VANGOGH (DRM 3.45.0, 5.13.0-valve15-1-neptune-02197-gf6ec7ad3762a, LLVM 12.0.1) (Supports OpenGL 4.6 (Core Profile) Mesa 21.3.8 (git-813ee839be))
[11:55:17] [Render thread/INFO]: OS: Linux (5.13.0-valve15-1-neptune-02197-gf6ec7ad3762a)
[11:55:18] [Render thread/INFO]: Narrator library successfully loaded
[11:55:19] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Iris, Sodium)
[11:55:19] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[11:55:24] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[11:55:24] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[11:55:24] [Render thread/INFO]: OpenAL initialized on device G435 Bluetooth Gaming Headset
[11:55:24] [Render thread/INFO]: Sound engine started
[11:55:25] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[11:55:25] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[11:55:25] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[11:55:25] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[11:55:25] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[11:55:25] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[11:55:25] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[11:55:27] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[11:55:27] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[11:55:27] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[11:55:27] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[11:55:34] [Render thread/INFO]: Destroying pipeline OVERWORLD
[11:55:34] [Render thread/WARN]: Ignoring ambiguous boolean option GENERAL_GRASS_FIX
[11:55:34] [Render thread/WARN]: Ignoring ambiguous boolean option GENERAL_GRASS_FIX
[11:55:34] [Render thread/WARN]: Unable to resolve shader pack option menu element "ATMOSPHERIC_SCATTERING" defined in shaders.properties
[11:55:34] [Render thread/WARN]: Unable to resolve shader pack option menu element "ATMOSPHERIC_HAZE" defined in shaders.properties
[11:55:34] [Render thread/WARN]: Unable to resolve shader pack option menu element "CREPUSCULAR_RAYS" defined in shaders.properties
[11:55:35] [Render thread/WARN]: Unable to resolve shader pack option menu element "VOLUMETRIC_CLOUDS" defined in shaders.properties
[11:55:35] [Render thread/WARN]: Unable to resolve shader pack option menu element "HQ_VOLUMETRIC_CLOUDS" defined in shaders.properties
[11:55:35] [Render thread/WARN]: Unable to resolve shader pack option menu element "SMOOTH_CLOUDS" defined in shaders.properties
[11:55:35] [Render thread/WARN]: Unable to resolve shader pack option menu element "WATER_CAUSTICS" defined in shaders.properties
[11:55:35] [Render thread/WARN]: Unable to resolve shader pack option menu element "ENABLE_SOFT_SHADOWS" defined in shaders.properties
[11:55:35] [Render thread/WARN]: Unable to resolve shader pack option menu element "PIXEL_SHADOWS" defined in shaders.properties
[11:55:35] [Render thread/WARN]: Unable to resolve shader pack option menu element "TONEMAP_STRENGTH" defined in shaders.properties
[11:55:35] [Render thread/WARN]: Unable to resolve shader pack option menu element "BRIGHTNESS_LEVEL" defined in shaders.properties
[11:55:35] [Render thread/INFO]: Profile: Custom (+0 options changed by user)
[11:55:36] [Render thread/INFO]: Using shaderpack: SEUS-Renewed-v1.0.1
[11:56:08] [Worker-Bootstrap-1/INFO]: 4256 Datafixer optimizations took 65684 milliseconds
[11:56:14] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Iris, Sodium), Steven's+Traditional+§8-§7+1.19.1§8.zip
[11:56:15] [Worker-Main-10/WARN]: Unused frames in sprite minecraft:entity/conduit/wind_vertical: [22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
[11:56:15] [Worker-Main-13/WARN]: Unused frames in sprite minecraft:entity/conduit/wind: [22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
[11:56:16] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[11:56:16] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[11:56:16] [Render thread/INFO]: OpenAL initialized on device G435 Bluetooth Gaming Headset
[11:56:16] [Render thread/INFO]: Sound engine started
[11:56:16] [Render thread/INFO]: Created: 4096x2048x4 minecraft:textures/atlas/blocks.png-atlas
[11:56:16] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/signs.png-atlas
[11:56:16] [Render thread/INFO]: Created: 2048x2048x4 minecraft:textures/atlas/banner_patterns.png-atlas
[11:56:16] [Render thread/INFO]: Created: 4096x4096x4 minecraft:textures/atlas/shield_patterns.png-atlas
[11:56:16] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/chest.png-atlas
[11:56:16] [Render thread/INFO]: Created: 2048x1024x4 minecraft:textures/atlas/beds.png-atlas
[11:56:16] [Render thread/INFO]: Created: 2048x1024x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[11:56:17] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[11:56:17] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/particles.png-atlas
[11:56:17] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/paintings.png-atlas
[11:56:17] [Render thread/INFO]: Created: 512x512x0 minecraft:textures/atlas/mob_effects.png-atlas
[11:56:23] [Render thread/INFO]: Connecting to SporkThingiEY4.aternos.me, 25565
[11:56:26] [Render thread/INFO]: Started 2 worker threads
[11:56:28] [Render thread/INFO]: Loaded 61 advancements
[11:56:28] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[11:56:28] [Render thread/INFO]: OpenGL debug message: id=2, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='0:261(20): error: initializer of const variable `K_R' must be a constant expression'
[11:56:28] [Render thread/INFO]: OpenGL debug message: id=3, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='0:262(20): error: initializer of const variable `K_M' must be a constant expression'
[11:56:28] [Render thread/WARN]: Shader compilation log for composite.fsh: 0:261(20): error: initializer of const variable `K_R' must be a constant expression
0:262(20): error: initializer of const variable `K_M' must be a constant expression

[11:56:28] [Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.RuntimeException: Shader compilation failed!
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:236) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:94) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:221) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:642) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) [iris-mc1.19-1.2.5.jar:?]
	at net.minecraft.class_761.handler$zka000$iris$beginLevelRender(class_761.java:6014) [client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1226) [client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1039) [client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:816) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1143) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:127) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:57) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Failed to compile FRAGMENT shader for program composite.fsh
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:78) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:49) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:232) ~[iris-mc1.19-1.2.5.jar:?]
	... 23 more
Caused by: java.lang.RuntimeException: Shader compilation failed, see log for details
	at net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:40) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:21) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:76) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:49) ~[iris-mc1.19-1.2.5.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:232) ~[iris-mc1.19-1.2.5.jar:?]
	... 23 more
[11:56:28] [Render thread/INFO]: Stopping worker threads
[11:56:28] [Render thread/INFO]: Started 2 worker threads
[12:01:05] [Render thread/INFO]: Stopping!
[12:01:05] [Render thread/INFO]: Stopping worker threads
```

### Additional context

Steam Deck

**Comment by supaman360** [comment]
Just realized this wouldnt be the crash tag lol

**Comment by IMS212** [comment]
This is a bug with SEUS Renewed itself, here’s a fix:

Open the shader pack (likely needs to be unzipped or extracted first) and open the shaders folder. Now open the Common.inc file with a text editor of your choice. Find and remove the const that immediately precedes the floats K_R and K_M, and save.
Before
const float K_R = 0.186 * rayleighAmount;
const float K_M = 0.035 * mieAmount;
After
float K_R = 0.186 * rayleighAmount;
float K_M = 0.035 * mieAmount;

**Comment by Lolothepro** [comment]
#1052

**Comment by IMS212** [comment]
We eventually want to fix these issues ourselves (#775), but for now, you’ll need to apply the fix manually.

**Comment by supaman360** [comment]
I get a thing saying that const variable K_M and K_R must be a constant variable

**Comment by IMS212** [comment]
please read what I posted

**Comment by supaman360** [comment]
I did what you said and it still gives me the error.
