### ISSUE TITLE
1.17+: Unable to use AirLoocke Shader

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1567]
### What happened?

Unable to use AirLoocke Shader

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/9193114/latest.log)

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

```
[22:28:29] [main/INFO]: Loading Minecraft 1.17.1 with Fabric Loader 0.14.6
[22:28:29] [ForkJoinPool-1-worker-6/WARN]: Mod forgetmechunk uses the version 1.17.X-1.0.3 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'X'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[22:28:29] [main/WARN]: Warnings were found!
 - Mod 'Ok Zoomer' (okzoomer) 5.0.0-beta.3+1.17.1 recommends version 2.0.0 or later of modmenu, which is missing!
	 - You should install version 2.0.0 or later of modmenu for the optimal experience.
[22:28:29] [main/INFO]: Loading 66 mods:
	- cloth-basic-math 0.6.1 via cloth-config2
	- cloth-config2 5.3.63
	- fabric 0.42.1+1.17
	- fabric-api-base 0.4.0+5847535018 via fabric
	- fabric-api-lookup-api-v1 1.3.1+5847535018 via fabric
	- fabric-biome-api-v1 3.2.2+5847535018 via fabric
	- fabric-blockrenderlayer-v1 1.1.6+5847535018 via fabric
	- fabric-command-api-v1 1.1.4+5847535018 via fabric
	- fabric-commands-v0 0.2.3+5847535018 via fabric
	- fabric-containers-v0 0.1.13+5847535018 via fabric
	- fabric-content-registries-v0 0.3.1+5847535018 via fabric
	- fabric-crash-report-info-v1 0.1.6+5847535018 via fabric
	- fabric-dimensions-v1 2.0.13+5847535018 via fabric
	- fabric-entity-events-v1 1.3.1+5847535018 via fabric
	- fabric-events-interaction-v0 0.4.11+5847535018 via fabric
	- fabric-events-lifecycle-v0 0.2.2+5847535018 via fabric
	- fabric-game-rule-api-v1 1.0.8+5847535018 via fabric
	- fabric-item-api-v1 1.2.5+5847535018 via fabric
	- fabric-item-groups-v0 0.3.1+5847535018 via fabric
	- fabric-key-binding-api-v1 1.0.6+2a2bb57318 via iris
	- fabric-keybindings-v0 0.2.3+5847535018 via fabric
	- fabric-lifecycle-events-v1 1.4.5+5847535018 via fabric
	- fabric-loot-tables-v1 1.0.5+5847535018 via fabric
	- fabric-mining-level-api-v1 1.0.2+6d0fac4218 via fabric
	- fabric-mining-levels-v0 0.1.5+6d0fac4218 via fabric
	- fabric-models-v0 0.3.1+5847535018 via fabric
	- fabric-networking-api-v1 1.0.14+5847535018 via fabric
	- fabric-networking-blockentity-v0 0.2.12+5847535018 via fabric
	- fabric-networking-v0 0.3.3+5847535018 via fabric
	- fabric-object-builder-api-v1 1.10.11+6d0fac4218 via fabric
	- fabric-object-builders-v0 0.7.5+6d0fac4218 via fabric
	- fabric-particles-v1 0.2.5+5847535018 via fabric
	- fabric-registry-sync-v0 0.7.13+5847535018 via fabric
	- fabric-renderer-api-v1 0.4.5+5847535018 via fabric
	- fabric-renderer-indigo 0.4.9+5847535018 via fabric
	- fabric-renderer-registries-v1 3.2.6+6d0fac4218 via fabric
	- fabric-rendering-data-attachment-v1 0.1.6+5847535018 via fabric
	- fabric-rendering-fluids-v1 0.2.1+6d0fac4218 via fabric
	- fabric-rendering-v0 1.1.7+6d0fac4218 via fabric
	- fabric-rendering-v1 1.10.1+6d0fac4218 via fabric
	- fabric-resource-loader-v0 0.4.10+f09604ce18 via iris
	- fabric-screen-api-v1 1.0.5+5847535018 via fabric
	- fabric-screen-handler-api-v1 1.1.9+5847535018 via fabric
	- fabric-structure-api-v1 1.1.14+5847535018 via fabric
	- fabric-tag-extensions-v0 1.2.2+5847535018 via fabric
	- fabric-textures-v0 1.0.7+5847535018 via fabric
	- fabric-tool-attribute-api-v1 1.3.1+eb76084f18 via fabric
	- fabric-transfer-api-v1 1.5.1+6d0fac4218 via fabric
	- fabricloader 0.14.6
	- fallingleaves 1.7.4+1.17.1
	- ferritecore 3.1.0
	- forgetmechunk 1.17.X-1.0.3
	- iris 1.2.6
	- java 17
	- lazydfu 0.1.2
	- libzoomer 0.3.0+1.17.1 via okzoomer
	- minecraft 1.17.1
	- okzoomer 5.0.0-beta.3+1.17.1
	- org_anarres_jcpp 1.4.14 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_joml_joml 1.10.2 via sodium
	- org_quiltmc_quilt-json5 1.0.0 via okzoomer
	- org_slf4j_slf4j-api 1.7.12 via iris
	- phosphor 0.8.0
	- sodium 0.3.4+build.13
	- spruceui 3.3.0+1.17 via okzoomer
[22:28:29] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/loic/.local/share/PolyMC/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[22:28:30] [main/INFO]: Compatibility level set to JAVA_16
[22:28:30] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[22:28:30] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[22:28:31] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[22:28:31] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[22:28:36] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder from mod sodium, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[22:28:37] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[22:28:37] [Render thread/INFO]: Setting user: Lolothepro29
[22:28:38] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin from mod fabric-lifecycle-events-v1::handler$zdc000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[22:28:38] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[22:28:38] [ForkJoinPool.commonPool-worker-1/WARN]: [Iris Update Check] Cached update file detected, using that!
[22:28:38] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[22:28:39] [Render thread/INFO]: Debug functionality is disabled.
[22:28:39] [Render thread/INFO]: Profile: Custom (+0 options changed by user)
[22:28:39] [Render thread/INFO]: Using shaderpack: AirLoocke Shader High v2.2.0.zip
[22:28:39] [Render thread/WARN]: Couldn't get pack info for: net.minecraft.class_3266: 'pack.mcmeta' in ResourcePack '/mnt/76561DD3561D94C9/MultiMC/instances/1.17.15/.minecraft/resourcepacks/Octray.zip'
[22:28:39] [Render thread/WARN]: Couldn't get pack info for: net.minecraft.class_3266: 'pack.mcmeta' in ResourcePack '/mnt/76561DD3561D94C9/MultiMC/instances/1.17.15/.minecraft/resourcepacks/EM64D-main.zip'
[22:28:39] [Render thread/WARN]: Couldn't get pack info for: net.minecraft.class_3266: 'pack.mcmeta' in ResourcePack '/mnt/76561DD3561D94C9/MultiMC/instances/1.17.15/.minecraft/resourcepacks/BSL Minipacks.zip'
[22:28:40] [Render thread/INFO]: Hardware information:
[22:28:40] [Render thread/INFO]: CPU: 12x AMD Ryzen 5 1600 Six-Core Processor
[22:28:40] [Render thread/INFO]: GPU: NVIDIA GeForce GTX 1070/PCIe/SSE2 (Supports OpenGL 3.2.0 NVIDIA 515.57)
[22:28:40] [Render thread/INFO]: OS: Linux (5.18.0-14.1-liquorix-amd64)
[22:28:40] [Render thread/INFO]: Narrator library successfully loaded
[22:28:41] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Cloth Config v5, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Level API (v1), Fabric Mining Levels (v0), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking Block Entity (v0), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Object Builders (v0), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Structure API (v1), Fabric Tag Extensions (v0), Fabric Textures (v0), Fabric Tool Attribute API (v1), Fabric Transfer API (v1), Fabric Loader, Falling Leaves, Iris, LazyDFU, LibZoomer, Ok Zoomer, Phosphor, Sodium, SpruceUI), Sama_Faithful v1.9 [Minecraft 1.17.x].zip
[22:28:41] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[22:28:41] [Render thread/WARN]: Shader compilation log for composite.fsh: 0(203) : error C0000: syntax error, unexpected reserved word "common", expecting ';' or '(' at token "common"
0(206) : error C1503: undefined variable "t"
0(220) : error C1503: undefined variable "t"
0(220) : error C1503: undefined variable "t"
0(223) : error C0000: syntax error, unexpected reserved word "common", expecting "::" at token "common"

[22:28:41] [Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.RuntimeException: Shader compilation failed!
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:238) ~[iris-mc1.17.1-1.2.6.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:95) ~[iris-mc1.17.1-1.2.6.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:227) ~[iris-mc1.17.1-1.2.6.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:639) ~[iris-mc1.17.1-1.2.6.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) [iris-mc1.17.1-1.2.6.jar:?]
	at net.coderbot.iris.Iris.onLoadingComplete(Iris.java:214) [iris-mc1.17.1-1.2.6.jar:?]
	at net.minecraft.class_442.handler$zki000$iris$showSodiumIncompatScreen(class_442.java:540) [client-intermediary.jar:?]
	at net.minecraft.class_442.method_25426(class_442.java:141) [client-intermediary.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:387) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:984) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:635) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:179) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Failed to compile FRAGMENT shader for program composite.fsh
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:78) ~[iris-mc1.17.1-1.2.6.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:49) ~[iris-mc1.17.1-1.2.6.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:234) ~[iris-mc1.17.1-1.2.6.jar:?]
	... 23 more
Caused by: java.lang.RuntimeException: Shader compilation failed, see log for details
	at net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:40) ~[iris-mc1.17.1-1.2.6.jar:?]
	at net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:21) ~[iris-mc1.17.1-1.2.6.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:76) ~[iris-mc1.17.1-1.2.6.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:49) ~[iris-mc1.17.1-1.2.6.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:234) ~[iris-mc1.17.1-1.2.6.jar:?]
	... 23 more
[22:28:41] [Render thread/INFO]: [Ok Zoomer] ÙwÚ what's this
[22:28:43] [Render thread/INFO]: OpenAL initialized.
[22:28:43] [Render thread/INFO]: Sound engine started
[22:28:43] [Render thread/INFO]: Created: 2048x1024x4 minecraft:textures/atlas/blocks.png-atlas
[22:28:43] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[22:28:43] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[22:28:43] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[22:28:43] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/chest.png-atlas
[22:28:43] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/beds.png-atlas
[22:28:43] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[22:28:44] [Render thread/INFO]: Created: 512x512x0 minecraft:textures/atlas/particles.png-atlas
[22:28:44] [Render thread/INFO]: Created: 512x512x0 minecraft:textures/atlas/paintings.png-atlas
[22:28:44] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/mob_effects.png-atlas
[22:28:47] [Render thread/INFO]: Stopping!
```

### Minecraft Version

Minecraft 1.17.1+

### Iris Version

Iris 1.2.6

### Operating System

Ubuntu 22.04

### What is your GPU?

GTX 1070

**Comment by leohu1** [comment]
@Lolothepro. Can this shader run in optifine? It think it might be the shader's issue.

**Comment by Lolothepro** [comment]
> @Lolothepro. Can this shader run in optifine? It think it might be the shader's issue.

Yes, it works with Optifine

**Comment by leohu1** [comment]
Well, this is strange.Maybe it has to do with the way iris compile shader.
