### ISSUE TITLE
Iris drops into fallback mode as soon as shaders are attempted to load.

### ISSUE THREAD

**Issue by glintty** [IrisShaders/Iris#1573]
### What happened?

I attempted to select either BSL or Complementary shaders in the Iris menu. Then Iris proceeded to go into fallback mode with the message `Toggled shaders to (off) [fallback, check your logs for details]!`. This also happens when I try to reload the shaders.

### Log output

[17:07:51] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
[17:07:51] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 3.0.4+9ff28f4057 recommends any version of fabric-textures-v0, which is missing!
	 - You should install any version of fabric-textures-v0 for the optimal experience.
[17:07:51] [main/INFO]: Loading 14 mods:
	- fabric-api-base 0.4.8+e62f51a357 via sodium
	- fabric-key-binding-api-v1 1.0.11+54e5b2ecd2 via iris
	- fabric-rendering-data-attachment-v1 0.3.11+9ff28f4057 via sodium
	- fabric-rendering-fluids-v1 3.0.4+9ff28f4057 via sodium
	- fabric-resource-loader-v0 0.5.3+9e7660c6a9 via malilib
	- fabricloader 0.14.8
	- iris 1.2.6
	- java 17
	- malilib 0.12.1
	- minecraft 1.19
	- minihud 0.22.0
	- org_anarres_jcpp 1.4.14 via iris
	- org_joml_joml 1.10.4 via sodium
	- sodium 0.4.2+build.16
[17:07:51] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/glint/.local/share/PolyMC/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[17:07:51] [main/INFO]: Compatibility level set to JAVA_16
[17:07:51] [main/INFO]: Compatibility level set to JAVA_17
[17:07:51] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[17:07:52] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[17:07:52] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[17:07:52] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[17:07:55] [main/INFO]: Building optimized datafixer
[17:07:57] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder from mod sodium, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[17:07:57] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:07:58] [Render thread/INFO]: Setting user: GiantGlint
[17:07:59] [ForkJoinPool.commonPool-worker-1/WARN]: [Iris Update Check] Cached update file detected, using that!
[17:07:59] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[17:08:00] [Render thread/INFO]: Debug functionality is disabled.
[17:08:00] [Render thread/INFO]: Profile: HIGH (+0 options changed by user)
[17:08:03] [Render thread/INFO]: Using shaderpack: ComplementaryShaders_v4.5.1.zip
[17:08:03] [Render thread/INFO]: Hardware information:
[17:08:03] [Render thread/INFO]: CPU: 4x Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
[17:08:03] [Render thread/INFO]: GPU: NV136 (Supports OpenGL 4.3 (Core Profile) Mesa 22.1.4)
[17:08:03] [Render thread/INFO]: OS: Linux (5.18.13-200.fc36.x86_64)
[17:08:04] [Render thread/WARN]: ERROR : Couldn't load Narrator library
java.lang.UnsatisfiedLinkError: libflite.so.1: cannot open shared object file: No such file or directory
	at com.sun.jna.Native.open(Native Method) ~[jna-5.10.0.jar:?]
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277) ~[jna-5.10.0.jar:?]
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461) ~[jna-5.10.0.jar:?]
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403) ~[jna-5.10.0.jar:?]
	at com.mojang.text2speech.NarratorLinux.<clinit>(NarratorLinux.java:18) [text2speech-1.13.9.jar:?]
	at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:21) [text2speech-1.13.9.jar:?]
	at net.minecraft.class_333.<init>(class_333.java:26) [client-intermediary.jar:?]
	at net.minecraft.class_333.<clinit>(class_333.java:24) [client-intermediary.jar:?]
	at net.minecraft.class_329.<init>(class_329.java:161) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:586) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:198) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
[17:08:04] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric API Base, Fabric Key Binding API (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Resource Loader (v0), Fabric Loader, Iris, MaLiLib, MiniHUD, Sodium)
[17:08:04] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[17:08:05] [Render thread/WARN]: [Triforce Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[17:08:06] [Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.IllegalStateException: Unexpected error while creating framebuffer
	at net.coderbot.iris.rendertarget.RenderTargets.createColorFramebuffer(RenderTargets.java:295) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.rendertarget.RenderTargets.createColorFramebufferWithDepth(RenderTargets.java:258) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.rendertarget.RenderTargets.createFullFramebuffer(RenderTargets.java:254) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.rendertarget.RenderTargets.createFramebufferWritingToAlt(RenderTargets.java:214) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.pipeline.ClearPassCreator.lambda$createClearPasses$2(ClearPassCreator.java:68) ~[iris-mc1.19.1-1.2.6.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at net.coderbot.iris.pipeline.ClearPassCreator.createClearPasses(ClearPassCreator.java:52) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:342) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:642) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) [iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.Iris.onLoadingComplete(Iris.java:217) [iris-mc1.19.1-1.2.6.jar:?]
	at net.minecraft.class_442.handler$zcm000$iris$showSodiumIncompatScreen(class_442.java:541) [client-intermediary.jar:?]
	at net.minecraft.class_442.method_25426(class_442.java:155) [client-intermediary.jar:?]
	at net.minecraft.class_437.method_41843(class_437.java:391) [client-intermediary.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:382) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1001) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:634) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:198) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
[17:08:06] [Render thread/INFO]: OpenGL debug message: id=3, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_FRAMEBUFFER_OPERATION in glClear(incomplete framebuffer)'
[17:08:07] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[17:08:07] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[17:08:08] [Render thread/INFO]: OpenAL initialized on device JACK Default
[17:08:08] [Render thread/INFO]: Sound engine started
[17:08:08] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[17:08:08] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[17:08:08] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[17:08:08] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[17:08:08] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[17:08:08] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[17:08:08] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[17:08:10] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[17:08:10] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[17:08:10] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[17:08:10] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[17:08:17] [Render thread/INFO]: Connecting to 10.1.1.2, 25565
[17:08:21] [Render thread/WARN]: @Redirect conflict. Skipping mixins.iris.compat.sodium.json:vertex_format.MixinFluidRenderer from mod iris->@Redirect::iris$fixSidewaysInnerFaceNormal(Lme/jellysquid/mods/sodium/client/model/IndexBufferBuilder;ILme/jellysquid/mods/sodium/client/model/quad/properties/ModelQuadWinding;Lnet/minecraft/class_1920;Lnet/minecraft/class_3610;Lnet/minecraft/class_2338;Lnet/minecraft/class_2338;Lme/jellysquid/mods/sodium/client/render/chunk/compile/buffers/ChunkModelBuilder;)V with priority 1000, already redirected by mixins.iris.compat.sodium.json:vertex_format.MixinFluidRenderer from mod iris->@Redirect::iris$fixBackwardUpFaceNormal(Lme/jellysquid/mods/sodium/client/model/IndexBufferBuilder;ILme/jellysquid/mods/sodium/client/model/quad/properties/ModelQuadWinding;Lnet/minecraft/class_1920;Lnet/minecraft/class_3610;Lnet/minecraft/class_2338;Lnet/minecraft/class_2338;Lme/jellysquid/mods/sodium/client/render/chunk/compile/buffers/ChunkModelBuilder;)V with priority 1000
[17:08:21] [Render thread/INFO]: Started 1 worker threads
[17:08:21] [Render thread/WARN]: Unknown custom packed identifier: minecraft:register
[17:08:23] [Render thread/WARN]: Received passengers for unknown entity
[17:08:23] [Render thread/INFO]: Loaded 581 advancements
[17:08:24] [Render thread/INFO]: Stopping worker threads
[17:08:24] [Render thread/INFO]: Started 1 worker threads
[17:08:27] [Render thread/INFO]: Destroying pipeline OVERWORLD
[17:08:27] [Render thread/INFO]: Shaders are disabled because enableShaders is set to false in iris.properties
[17:08:27] [Render thread/INFO]: Shaders are disabled
[17:08:27] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[17:08:27] [Render thread/INFO]: Stopping worker threads
[17:08:27] [Render thread/INFO]: Started 1 worker threads
[17:08:27] [Render thread/INFO]: [CHAT] Shaders disabled!
[17:08:27] [Render thread/INFO]: Destroying pipeline OVERWORLD
[17:08:27] [Render thread/INFO]: Profile: HIGH (+0 options changed by user)
[17:08:29] [Render thread/INFO]: Using shaderpack: ComplementaryShaders_v4.5.1.zip
[17:08:29] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[17:08:29] [Render thread/WARN]: [Triforce Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[17:08:29] [Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.IllegalStateException: Unexpected error while creating framebuffer
	at net.coderbot.iris.rendertarget.RenderTargets.createColorFramebuffer(RenderTargets.java:295) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.rendertarget.RenderTargets.createColorFramebufferWithDepth(RenderTargets.java:258) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.rendertarget.RenderTargets.createFullFramebuffer(RenderTargets.java:254) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.rendertarget.RenderTargets.createFramebufferWritingToAlt(RenderTargets.java:214) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.pipeline.ClearPassCreator.lambda$createClearPasses$2(ClearPassCreator.java:68) ~[iris-mc1.19.1-1.2.6.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at net.coderbot.iris.pipeline.ClearPassCreator.createClearPasses(ClearPassCreator.java:52) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:342) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:642) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) [iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.Iris.reload(Iris.java:584) [iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.Iris.toggleShaders(Iris.java:257) [iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.Iris.handleKeybinds(Iris.java:238) [iris-mc1.19.1-1.2.6.jar:?]
	at net.minecraft.class_310.handler$zcd000$iris$onTick(class_310.java:2877) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1869) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1101) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
[17:08:29] [Render thread/INFO]: Stopping worker threads
[17:08:29] [Render thread/INFO]: Started 1 worker threads
[17:08:29] [Render thread/INFO]: [CHAT] Toggled shaders to (off) [fallback, check your logs for details]!
[17:08:29] [Render thread/INFO]: OpenGL debug message: id=3, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_FRAMEBUFFER_OPERATION in glClear(incomplete framebuffer)'
[17:08:33] [Render thread/INFO]: Stopping worker threads
[17:08:59] [Render thread/INFO]: Connecting to 10.1.1.2, 25565
[17:09:02] [Render thread/INFO]: Started 1 worker threads
[17:09:02] [Render thread/WARN]: Unknown custom packed identifier: minecraft:register
[17:09:03] [Render thread/WARN]: Received passengers for unknown entity
[17:09:03] [Render thread/INFO]: Loaded 581 advancements
[17:09:04] [Render thread/INFO]: Destroying pipeline OVERWORLD
[17:09:04] [Render thread/INFO]: Shaders are disabled because enableShaders is set to false in iris.properties
[17:09:04] [Render thread/INFO]: Shaders are disabled
[17:09:04] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[17:09:04] [Render thread/INFO]: Stopping worker threads
[17:09:05] [Render thread/INFO]: Started 1 worker threads
[17:09:05] [Render thread/INFO]: [CHAT] Shaders disabled!
[17:09:05] [Render thread/INFO]: Destroying pipeline OVERWORLD
[17:09:06] [Render thread/INFO]: Profile: HIGH (+0 options changed by user)
[17:09:06] [Render thread/INFO]: Using shaderpack: ComplementaryShaders_v4.5.1.zip
[17:09:06] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[17:09:07] [Render thread/WARN]: [Triforce Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[17:09:07] [Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.IllegalStateException: Unexpected error while creating framebuffer
	at net.coderbot.iris.rendertarget.RenderTargets.createColorFramebuffer(RenderTargets.java:295) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.rendertarget.RenderTargets.createColorFramebufferWithDepth(RenderTargets.java:258) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.rendertarget.RenderTargets.createFullFramebuffer(RenderTargets.java:254) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.rendertarget.RenderTargets.createFramebufferWritingToAlt(RenderTargets.java:214) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.pipeline.ClearPassCreator.lambda$createClearPasses$2(ClearPassCreator.java:68) ~[iris-mc1.19.1-1.2.6.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at net.coderbot.iris.pipeline.ClearPassCreator.createClearPasses(ClearPassCreator.java:52) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:342) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:642) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) [iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.Iris.reload(Iris.java:584) [iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.Iris.toggleShaders(Iris.java:257) [iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.Iris.handleKeybinds(Iris.java:238) [iris-mc1.19.1-1.2.6.jar:?]
	at net.minecraft.class_310.handler$zcd000$iris$onTick(class_310.java:2877) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1869) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1101) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
[17:09:07] [Render thread/INFO]: Stopping worker threads
[17:09:07] [Render thread/INFO]: Started 1 worker threads
[17:09:07] [Render thread/INFO]: [CHAT] Toggled shaders to (off) [fallback, check your logs for details]!
[17:09:07] [Render thread/INFO]: OpenGL debug message: id=3, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_FRAMEBUFFER_OPERATION in glClear(incomplete framebuffer)'
[17:09:13] [Worker-Bootstrap-3/INFO]: 4256 Datafixer optimizations took 78555 milliseconds

### Minecraft Version

Minecraft 1.19 Fabric 

### Iris Version

iris-mc1.19-1.2.6.jar

### Operating System

Fedora 36 Workstation x86_64

### What is your GPU?

NVIDIA GeForce GTX 1060 Mobile

### Additional context

I'm using PolyMC 1.4.1 as my client if that helps at all.
Iris had successfully ran on my old installation Pop_OS! 22.04.
The issue persists with both Wayland and Xorg.

**Comment by Lolothepro** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/6890

**Comment by Lolothepro** [comment]
https://github.com/IrisShaders/Iris/blob/trunk/docs/usage/drivers.md

**Comment by glintty** [comment]
Ah, wish I had noticed I was using nouveau. I had assumed the proprietary drivers were installed as I allowed it during the installation process for Fedora. I installed the proprietary drivers and everything worked fine. Thanks.
