### ISSUE TITLE
iris crash 1.19.2 exit code 1

### ISSUE THREAD

**Issue by aloochops** [IrisShaders/Iris#1597]
### Minecraft Version

1.19.2

### Iris Version

iris-mc1.19.1-1.2.6

### Sodium Version

sodium-fabric-mc1.19-0.4.2build.16

### Operating System

Windows 10 Home

### What is your GPU?

Nvidia Geforce GTX 1060 6gb

### Java Version

java 16

### Reproduction Steps

1. Load Iris/Shaders 1.19.2 
2. Tries to load
3. Game Crashes and gives a fabric loader crash report

### Crash Report file and latest.log

```shell
Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to obtain root directory for mod 'fabric-rendering-data-attachment-v1'!
	at net.fabricmc.loader.impl.ModContainerImpl.obtainRootPaths(ModContainerImpl.java:148)
	at net.fabricmc.loader.impl.ModContainerImpl.getRootPaths(ModContainerImpl.java:100)
	at net.fabricmc.loader.api.ModContainer.findPath(ModContainer.java:62)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:435)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.io.IOException: Error accessing file:///C:/Users/user/AppData/Roaming/.minecraft/.fabric/processedMods/fabric-rendering-data-attachment+9ff28f4057-d01279f78d43cb2c.jar: java.util.zip.ZipException: zip END header not found
	at net.fabricmc.loader.impl.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:83)
	at net.fabricmc.loader.impl.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:59)
	at net.fabricmc.loader.impl.ModContainerImpl.obtainRootPath(ModContainerImpl.java:156)
	at net.fabricmc.loader.impl.ModContainerImpl.obtainRootPaths(ModContainerImpl.java:137)
	... 6 more
Caused by: java.util.zip.ZipException: zip END header not found
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1320)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1534)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:179)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:106)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288)
	at net.fabricmc.loader.impl.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:78)
	... 9 more
```

**Comment by coderbot16** [comment]
One of your mod files is corrupted. Fabric doesn't provide a useful diagnostic here, but try redownloading your mods.
