### ISSUE TITLE
Crashing in world

### ISSUE THREAD

**Issue by nijahplays** [IrisShaders/Iris#1614]
### Minecraft Version

1.19.2

### Iris Version

1.2.7

### Sodium Version

0.4.3 Build 17

### Operating System

Arch Linux with Gnome 42

### What is your GPU?

RX 570 8GB

### Java Version

OpenJDK 17

### Reproduction Steps

Open world- Crash

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2022-08-28 07:05:43
Description: Unexpected error

java.lang.IllegalStateException: Not building!
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.8)
	at net.minecraft.client.render.BufferBuilder.ensureBuilding(BufferBuilder:243)
	at net.minecraft.client.render.BufferBuilder.end(BufferBuilder:235)
	at net.coderbot.batchedentityrendering.impl.SegmentedBufferBuilder.getSegments(SegmentedBufferBuilder.java:66)
	at net.coderbot.batchedentityrendering.impl.FullyBufferedMultiBufferSource.draw(FullyBufferedMultiBufferSource.java:99)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1468)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1039)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:816)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1177)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$egc000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:20022)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:795)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$egc000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:20011)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:790)
	at net.minecraft.client.main.Main.main(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_287.method_43577(class_287.java:243)
	at net.minecraft.class_287.method_1326(class_287.java:235)
	at net.coderbot.batchedentityrendering.impl.SegmentedBufferBuilder.getSegments(SegmentedBufferBuilder.java:66)
	at net.coderbot.batchedentityrendering.impl.FullyBufferedMultiBufferSource.method_22993(FullyBufferedMultiBufferSource.java:99)
	at net.minecraft.class_761.method_22710(class_761.java:1468)
	at net.minecraft.class_757.method_3188(class_757.java:1039)

-- Affected level --
Details:
	All players: 1 total; [class_746['nijahplays'/3467, l='ClientLevel', x=23.51, y=86.17, z=198.86]]
	Chunk stats: 1024, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (32,64,64), Section: (at 0,0,0 in 2,4,4; chunk contains blocks 32,-64,64 to 47,319,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1176503 game time, 22304617 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$egc000$atTheEndOfSecondCatchBeforePrintingCrashReport(class_310.java:20022)
	at net.minecraft.class_310.method_1514(class_310.java:795)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$egc000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:20011)
	at net.minecraft.class_310.method_1514(class_310.java:790)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Unity-1.18.X-Dark-0.8.1.zip, Black Icons, midnightcontrols/bedrock, cullleaves/smartleaves, continuity/default, continuity/glass_pane_culling_fix, lambdabettergrass/default, minecraft/supporteatinganimation, §5AVPBR-1-7.zip, AVPBR Beta 8-1.zip, AVPBR Beta 8-2.zip, Essential (fabric_1.19.2).jar

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 5.19.4-arch1-1
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3825010464 bytes (3647 MiB) / 5708447744 bytes (5444 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 1700 Eight-Core Processor
	Identifier: AuthenticAMD Family 23 Model 1 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 8194.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 12048.30
	Virtual memory used (MB): 9652.90
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 135.50
	JVM Flags: 8 total; -Xss1M -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32
	Fabric Mods: 
		alternate-current: Alternate Current 1.4.0
		amplifiednether: Amplified nether 1.2
		appleskin: AppleSkin 2.4.1+mc1.19
		attributefix: AttributeFix 17.1.2
		badpackets: Bad Packets 0.2.0
		bedspreads: Bedspreads 6.0.0+1.19.2
		bettercontrols: Better Controls 1.2.3
		betterf3: BetterF3 1.3.2
		blanket-client-tweaks: Blanket Client-tweaks 1.1.1
		bookshelf: Bookshelf 16.1.4
		bsvsb: Better Sodium Video Settings Button 3.0.2
		capes: Capes 1.4.4+1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		carpet: Carpet Mod 1.4.83
		carpet-fixes: Carpet Fixes 1.19-1.11.2
			conditional-mixin: conditional mixin 0.3.0
		chat_heads: Chat Heads 0.7.1
		cleardespawn: Clear Despawn 1.1.9
		clickadv: Clickable Advancements Mod 2.9
		cloth-config: Cloth Config v8 8.0.75
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+11
		colouredtooltips: ColouredTooltips 18.1.3
		connectivity: Connectivity Mod 1.19-3.3
		continuity: Continuity 2.0.1+1.19
		creativecore: CreativeCore (Fabric) 2.7.2
		cull-less-leaves: Cull Less Leaves 1.0.5
			com_github_llamalad7_mixinextras: mixinextras 0.0.12
		cullleaves: Cull Leaves 2.3.4
		damagetilt: Damage Tilt 1.19-fabric-0.1.2
		dark-loading-screen: Dark Loading Screen 1.6.12
		dashloader: DashLoader 4.1.1+1.19
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		durabilityviewer: Giselbaers Durability Viewer 1.19.1-fabric0.58.5-1.10.3
			crowdin-translate: CrowdinTranslate 1.4+1.19
			gbfabrictools: GBfabrictools 1.3.4+1.19
		dusk: Dusk Mod 1.19.1-2.2
		eatinganimationid: Eating Animation 1.9
		elementa: Elementa 544
		enchdesc: EnchantmentDescriptions 13.0.3
		enhancedblockentities: Enhanced Block Entities 0.7.1+1.19
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
		entitycollisionfpsfix: Entity Collision FPS Fix 2.0.0.0
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		essential: Essential 4682+g6356ca49f
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.0.0
		fabric-api: Fabric API 0.60.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.11+e62f51a390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.9+9ff28f4090
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.17+aeb40ebe90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.20+aeb40ebe90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.1+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.11+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.7+0c17ea9690
			fabric-commands-v0: Fabric Commands (v0) 0.2.28+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.34+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.3+aeb40ebe90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.1+7cd20a1490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.5+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.8+a680b9b490
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.30+aeb40ebe90
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.18+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.28+aeb40ebe90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.28+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.21+aeb40ebe90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.7+35a03c4390
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.28+aeb40ebe90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.20+aeb40ebe90
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.18+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.2+aeb40ebe90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.3+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.6+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.3+176380a290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.14+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.17+aeb40ebe90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.4+5eb68ef290
			fabric-networking-v0: Fabric Networking (v0) 0.3.21+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.11+aeb40ebe90
			fabric-particles-v1: Fabric Particles (v1) 1.0.10+aeb40ebe90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.24+aeb40ebe90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.10+aeb40ebe90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.12+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.20+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.14+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.7+aeb40ebe90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.22+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.16+aeb40ebe90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.11+e62f51a390
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.6.1+aeb40ebe90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.26+f05effaf90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.13+9ff28f4090
			fabric-textures-v0: Fabric Textures (v0) 1.0.20+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.11+83a8659290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.0+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.3+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.0
		fabricloader: Fabric Loader 0.14.9
		fallingleaves: Falling Leaves 1.12.2+1.19.2
		fastload: Fast Load 1.1.5
		fastopenlinksandfolders: FastOpenResourcePacks 1.1.1
		ferritecore: FerriteCore 4.2.1
		forgetmechunk: Forget Me Chunk 1.0.4-1.18.X-1.19.X
		fpsreducer: FPS Reducer 1.19.2-2.1
		indium: Indium 1.0.8+mc1.19.2
		iris: Iris 1.2.7
			org_anarres_jcpp: jcpp 1.4.14
		itemmodelfix: Item Model Fix 1.0.3+1.19
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.2.0.256
		konkrete: Konkrete 1.5.0
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		lazy-language-loader: lazy-language-loader 0.3.1
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.8.3
		memoryleakfix: memory Leak Fix 1.19.1-0.7.0
		memorysettings: Memorysettings Mod 1.19.2-2.2
		midnightcontrols: MidnightControls 1.5.0+1.19
			org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
			spruceui: SpruceUI 4.0.0+1.19
		midnightcontrols-extra: MidnightControls Extra 1.0.0
		midnightlib: MidnightLib 0.6.0
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.0.6
		multiconnect: MultiConnect 1.6-beta.23
			multiconnect-api: MultiConnect API 1.6-beta.23
		no-telemetry: No Telemetry 1.4.0
		nochatreports: No Chat Reports 1.19.2-v1.10.2
		notenoughanimations: NotEnoughAnimations 1.6.1
		notenoughcrashes: Not Enough Crashes 4.1.8+1.19.2
		org_jetbrains_annotations: annotations 13.0
		polymorph: Polymorph 0.45.0+1.19.2
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			cardinal-components-item: Cardinal Components API (items) 5.0.1
		presencefootsteps: Presence Footsteps 1.6.1
			kirin: Kirin UI 1.11.0
		recipecache: recipecache 0.2.0-1.19
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.19.2-build.59
		shiftscrollfix: Shift-Scroll Fix 1.0.1
		simple-rpc: Simple RPC 3.1.1
			me_hypherionmc_simplerpc_simple-rpc-common: simple-rpc-common 4.0.3
		sit: Sit 1.19-20
		skinlayers: 3d Skin Layers 1.5.1-mc1.19.1
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.3+build.17
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.9+mc1.19.2-build.60
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.0.15
		starlight: Starlight 1.1.1+fabric.ae22326
		styledchat: Styled Chat 1.4.1+1.19.2
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			placeholder-api: Placeholder API 2.0.0-beta.7+1.19
		tiefix: TieFix 1.11.0
		title-fix: Title Fix 1.0.1+MC1.17.1
		tooltipfix: ToolTip Fix 1.0.5-1.19
		universalcraft: UniversalCraft 225
		vigilance: Vigilance 252
		vmp: Very Many Players 0.2.0+beta.6.56
		voicechat: Simple Voice Chat 1.19.2-2.3.8
		waterdripsound: Drip Sounds 1.19-0.3.0
		worldedit: WorldEdit 7.2.12+6240-87f4ae1
		xlpackets: XLPackets 2.1-1.17.1
		zoomify: Zoomify 2.4.2
			dev_isxander_settxi_settxi-core: settxi-core 2.7.4
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.7.4
			settxi-gui-cloth-config: Settxi Gui (Cloth Config) 2.7.4
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.14.9-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon RX 570 Series (polaris10, LLVM 14.0.6, DRM 3.47, 5.19.4-arch1-1) GL version 4.6 (Core Profile) Mesa 22.1.7, AMD
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=2, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM in glPolygonMode(face)' x 4
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fabulous
	Resource Packs: vanilla, Fabric Mods, file/Unity-1.18.X-Dark-0.8.1.zip (incompatible), Black Icons, midnightcontrols/bedrock, cullleaves/smartleaves, continuity/default, continuity/glass_pane_culling_fix, lambdabettergrass/default, minecraft/supporteatinganimation, file/§5AVPBR-1-7.zip (incompatible), file/AVPBR Beta 8-1.zip, file/AVPBR Beta 8-2.zip
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 1700 Eight-Core Processor
	Server Running: true
	Player Count: 1 / 8; [class_3222['nijahplays'/3467, l='ServerLevel[Minecraft Bench Mark]', x=23.51, y=86.17, z=198.86]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
	Client Crashes Since Restart: 3
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Iris (iris)
```

### Additional context

I am using crashy to see crash reports

**Comment by nijahplays** [comment]
https://crashy.net/5s7VQNN5tYrEFb0FYByB

Original Crashy link for more details

**Comment by IMS212** [comment]
Update Sodium. This is a mistake on my part, Sodium is not being detected as incompatible
