### ISSUE TITLE
Minecraft crashes on launch after installing iris

### ISSUE THREAD

**Issue by zaneisntsane** [IrisShaders/Iris#1618]
### Minecraft Version

Minecraft 1.19.2

### Iris Version

iris-mc1.19.2-1.2.8.jar

### Sodium Version

sodium-fabric-mc1.19.2-0.4.4+build.18.jar

### Operating System

Windows 10

### What is your GPU?

AMD Radeon(TM) Vega 8 Graphics

### Java Version

I dont know

### Reproduction Steps

1. Download Fabric API, Sodium, Lithium, Phosphor, Indium, and Iris
2. Open Minecraft launcher
3. Click on Fabric 1.19.2 version and press Play
4. Game crashes

### Crash Report file and latest.log

```shell
[16:59:00] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.9
[16:59:00] [main/INFO]: Loading 59 mods:
	- fabric-api 0.60.0+1.19.2
	- fabric-api-base 0.4.11+e62f51a390 via fabric-api
	- fabric-api-lookup-api-v1 1.6.9+9ff28f4090 via fabric-api
	- fabric-biome-api-v1 9.0.17+aeb40ebe90 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.20+aeb40ebe90 via fabric-api
	- fabric-client-tags-api-v1 1.0.1+b35fea8390 via fabric-api
	- fabric-command-api-v1 1.2.11+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.1.7+0c17ea9690 via fabric-api
	- fabric-commands-v0 0.2.28+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.34+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.2.3+aeb40ebe90 via fabric-api
	- fabric-convention-tags-v1 1.1.1+7cd20a1490 via fabric-api
	- fabric-crash-report-info-v1 0.2.5+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.1.8+a680b9b490 via fabric-api
	- fabric-dimensions-v1 2.1.30+aeb40ebe90 via fabric-api
	- fabric-entity-events-v1 1.4.18+9ff28f4090 via fabric-api
	- fabric-events-interaction-v0 0.4.28+aeb40ebe90 via fabric-api
	- fabric-events-lifecycle-v0 0.2.28+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.21+aeb40ebe90 via fabric-api
	- fabric-item-api-v1 1.5.7+35a03c4390 via fabric-api
	- fabric-item-groups-v0 0.3.28+aeb40ebe90 via fabric-api
	- fabric-key-binding-api-v1 1.0.20+aeb40ebe90 via fabric-api
	- fabric-keybindings-v0 0.2.18+df3654b390 via fabric-api
	- fabric-lifecycle-events-v1 2.1.2+aeb40ebe90 via fabric-api
	- fabric-loot-api-v2 1.1.3+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.6+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.3+176380a290 via fabric-api
	- fabric-mining-level-api-v1 2.1.14+33fbc73890 via fabric-api
	- fabric-models-v0 0.3.17+aeb40ebe90 via fabric-api
	- fabric-networking-api-v1 1.2.4+5eb68ef290 via fabric-api
	- fabric-networking-v0 0.3.21+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.0.11+aeb40ebe90 via fabric-api
	- fabric-particles-v1 1.0.10+aeb40ebe90 via fabric-api
	- fabric-registry-sync-v0 0.9.24+aeb40ebe90 via fabric-api
	- fabric-renderer-api-v1 1.0.10+aeb40ebe90 via fabric-api
	- fabric-renderer-indigo 0.6.12+aeb40ebe90 via fabric-api
	- fabric-renderer-registries-v1 3.2.20+df3654b390 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.14+aeb40ebe90 via fabric-api
	- fabric-rendering-fluids-v1 3.0.7+aeb40ebe90 via fabric-api
	- fabric-rendering-v0 1.1.22+df3654b390 via fabric-api
	- fabric-rendering-v1 1.10.16+aeb40ebe90 via fabric-api
	- fabric-resource-conditions-api-v1 2.0.11+e62f51a390 via fabric-api
	- fabric-resource-loader-v0 0.6.1+aeb40ebe90 via fabric-api
	- fabric-screen-api-v1 1.0.26+f05effaf90 via fabric-api
	- fabric-screen-handler-api-v1 1.2.13+9ff28f4090 via fabric-api
	- fabric-textures-v0 1.0.20+aeb40ebe90 via fabric-api
	- fabric-transfer-api-v1 2.0.11+83a8659290 via fabric-api
	- fabric-transitive-access-wideners-v1 1.3.0+42d99c3290 via fabric-api
	- fabricloader 0.14.9
	- indium 1.0.9+mc1.19.2
	- iris 1.2.8
	- java 17
	- lithium 0.8.3
	- minecraft 1.19.2
	- modmenu 4.0.4
	- org_anarres_jcpp 1.4.14 via iris
	- org_joml_joml 1.10.4 via sodium
	- phosphor 0.8.1
	- sodium 0.4.4+build.18
[16:59:00] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/crest/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[16:59:01] [main/INFO]: Compatibility level set to JAVA_16
[16:59:01] [main/INFO]: Compatibility level set to JAVA_17
[16:59:01] [main/INFO]: Loaded configuration file for Lithium: 94 options available, 0 override(s) found
[16:59:01] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[16:59:03] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[16:59:06] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[16:59:07] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[16:59:16] [main/INFO]: Building optimized datafixer
[16:59:25] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder from mod sodium, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[16:59:26] [Render thread/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[16:59:26] [Render thread/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_442 failed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_442 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:214) ~[fabric-loader-0.14.9-1.19.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.9-1.19.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:214) ~[fabric-loader-0.14.9-1.19.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.9-1.19.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method adjustRealmsHeight(I)I in mixins.modmenu.json:MixinTitleScreen from mod modmenu failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap modmenu-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:214) ~[fabric-loader-0.14.9-1.19.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.9-1.19.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 2 more
```

### Additional context

I had Optifine installed before Iris, so when it brought up the prompt to delete Optifine during the installation, I clicked Yes, but I don't know if that has anything to do with the crash.

**Comment by coderbot16** [comment]
It looks like your problem has nothing to do with Iris and is instead caused by an outdated version of Mod Menu. You have 4.0.4 but want https://modrinth.com/mod/modmenu/version/4.0.6
