### ISSUE TITLE
Incompatability with Iris 1.3 and Create Crafts & Additions

### ISSUE THREAD

**Issue by nebulazorua** [IrisShaders/Iris#1636]
### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.3.1.jar

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15

### Operating System

Windows 10

### What is your GPU?

NVIDIA GeForce RTX 3050

### Java Version

Java 17

### Reproduction Steps

1. Install Iris 1.3.1 and Create Crafts & Additions 20220911a
2. Place an Electric Motor or Alternator into the world
3. Crash

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// My bad.

Time: 9/13/22, 6:57 AM
Description: Unexpected error

java.lang.NoSuchMethodError: 'net.minecraft.class_2588 com.simibubi.create.foundation.utility.Lang.translateDirect(java.lang.String, java.lang.Object[])'
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4)
	at com.mrh0.createaddition.blocks.alternator.AlternatorTileEntity.addToGoggleTooltip(AlternatorTileEntity.java:56)
	at com.simibubi.create.content.contraptions.goggles.GoggleOverlayRenderer.renderOverlay(GoggleOverlayRenderer.java:94)
	at com.simibubi.create.CreateClient.lambda$registerOverlays$2(CreateClient.java:124)
	at io.github.fabricators_of_create.porting_lib.event.client.OverlayRenderCallback.lambda$static$0(OverlayRenderCallback.java:17)
	at net.minecraft.client.gui.hud.InGameHud.handler$zzn000$port_lib$renderCrosshair(InGameHud:2064)
	at net.minecraft.client.gui.hud.InGameHud.renderCrosshair(InGameHud)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud:235)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:858)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1122)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at net.minecraft.client.main.Main.main(Main:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mrh0.createaddition.blocks.alternator.AlternatorTileEntity.addToGoggleTooltip(AlternatorTileEntity.java:56)
	at com.simibubi.create.content.contraptions.goggles.GoggleOverlayRenderer.renderOverlay(GoggleOverlayRenderer.java:94)
	at com.simibubi.create.CreateClient.lambda$registerOverlays$2(CreateClient.java:124)
	at io.github.fabricators_of_create.porting_lib.event.client.OverlayRenderCallback.lambda$static$0(OverlayRenderCallback.java:17)
	at net.minecraft.class_329.handler$zzn000$port_lib$renderCrosshair(class_329.java:2064)
	at net.minecraft.class_329.method_1736(class_329.java)
	at net.minecraft.class_329.method_1753(class_329.java:235)

-- Affected level --
Details:
	All players: 2 total; [class_746['Nebula_Zorua'/34655, l='ClientLevel', x=9769.47, y=63.00, z=-13153.35], class_745['Shadowfi1385'/3817, l='ClientLevel', x=9754.62, y=63.00, z=-13162.48]]
	Chunk stats: 1024, 464
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,110,0), Section: (at 0,14,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 4818257 game time, 4157871 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Theinar Language, Vanilla-PBR-1-2-0 (1).zip

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1286545408 bytes (1226 MiB) / 3795845120 bytes (3620 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 6
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce RTX 3050
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2507
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1277
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37580.49
	Virtual memory used (MB): 30157.85
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 659.93
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6144m -Xms256m
	Fabric Mods: 
		adorn: Adorn 3.5.0+1.18.2
		ae2: Applied Energistics 2 11.1.7
			noindium: No Indium? 1.0.2+1.18.2
		amecs: Amecs 1.3.8+mc.1.18.2
			amecsapi: Amecs API 1.3.5+mc22w06a
		appleskin: AppleSkin 2.4.1+mc1.18.2
		architects_palette: Architect's Palette Fabric 2.2
		architectury: Architectury 4.9.83
		artifacts: Artifacts 7.0.3+fabric
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		attributefix: AttributeFix 14.0.2
		axesareweapons: Axes Are Weapons 1.6.0
		badpackets: Bad Packets 0.1.2
		badwithernocookiereloaded: Bad Wither No Cookie! Reloaded 3.10.18 (Fabric 1.18.2)
		balm-fabric: Balm 3.2.0+0
		bclib: BCLib 1.4.7
		bedspreads: Bedspreads 1.6.0-1.18
		bestylewither: BE Style Wither 1.2
		betteradvancements: Better Advancements 0.2.1.132
		betterend: Better End 1.1.1
		betterf3: BetterF3 1.2.5
		bettermineshafts: YUNG's Better Mineshafts 1.18.2-Fabric-2.2
		betternether: Better Nether 6.1.2
		betterthirdperson: Better Third Person 1.8.1
		biomemakeover: Biome Makeover 1.18.2-1.4.31
		bookshelf: Bookshelf 13.2.50
		botanypots: BotanyPots 8.0.12
		botanytrees: BotanyTrees 4.0.2
		capybara: Capybara 1.0.6
		carrier: Carrier 1.10.0
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		cccbridge: CC:C Bridge 1.2.0
		charm: Charm 4.2.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		chimes: Chimes 1.1.1
		chipped: Chipped 1.2
		cleancut: CleanCut 1.18.2-5.0-fabric
		cloth-config: Cloth Config v6 6.4.90
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 8.0.0+15
		comforts: Comforts 1.1.2-1.18.2
			cardinal-components-base: Cardinal Components API (base) 4.1.4
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		computercraft: CC: Restitched 1.100.8
			cloth-utils-v1: Cloth Utils v1 2.0.54
		continuity: Continuity 2.0.1+1.18.2
		controlling: Controlling For Fabric 9.0+22
		craftingtweaks: Crafting Tweaks 14.0.3
		crawl: Crawl 0.10.6
			mm: Manningham Mills 2.3
		create: Create 0.5.0d-731
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.3.0
			flywheel: Flywheel 0.6.4-30
			forge_tags: Forge Tags 2.1
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			porting_lib: Porting Lib 1.2.460-beta+1.18.2-dev.cca931b
				serialization_hooks: Serialization Hooks 0.3.23
			reach-entity-attributes: Reach Entity Attributes 2.1.1
			registrate-fabric: Registrate for Fabric MC1.18.2-1.1.4
				com_github_llamalad7_mixinextras: MixinExtras 0.0.11
		createaddition: Create Crafts & Additions ${version}
			team_reborn_energy: Energy 2.2.0
		createchunkloading: Create Chunkloading 1.2.1
		darkpaintings: DarkPaintings 10.0.3
		darkutils: DarkUtilities 10.0.5
		debugify: Debugify 1.11.0
		decorative_blocks: Decorative Blocks 2.1.1
		dragonloot: DragonLoot 1.1.0
		duckling: Duckling 1.0.7
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		dungeons_arise: When Dungeons Arise 2.1.50
		ellemes_container_lib: Ellemes' Container Library 1.4.0-beta.2
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		enchantedshulkers: Enchanted Shulkers 1.0.4
		endgoblintraders: End Goblin Traders 1.5 (Re-upload)
		entityculling: EntityCulling-Fabric 1.5.1
		enva: Environmental Armor 1.4.4
		examplemod: Secret Rooms 1.0.0r-1.18.2
		expanded_trident_enchanting: Expanded Trident Enchanting 1.0.3
		expandedstorage: Expanded Storage 7.4.0-beta.4
		experiencebugfix: Experience Bug Fix 18
		extraalchemy: Extra Alchemy 1.8.1
		extraorigins: Extra Origins 1.18-12
		fabric: Fabric API 0.58.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.23+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.1+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.19+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.2+17cbbd4360
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.23+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.10+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.10+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.3+41a02c8a60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.2+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-furnaces: Fabric Furnaces 2.1.1-1.18.2
			omega-config: OmegaConfig 1.2.3-1.18.1
		fabric-language-kotlin: Fabric Language Kotlin 1.8.3+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.0
		fabricloader: Fabric Loader 0.14.9
		fallingtree: FallingTree 3.5.4
		ferritecore: FerriteCore 4.2.1
		figura: Figura 0.1.0-rc.7+1.18.2
			com_github_moonlight-mc_luaj_luaj-core: luaj-core 3.0.4-figura
			com_github_moonlight-mc_luaj_luaj-jse: luaj-jse 3.0.4-figura
			org_java-websocket_java-websocket: Java-WebSocket 1.5.2
		forgeconfigapiport: Forge Config API Port 3.2.4
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		ftblibrary: FTB Library 1802.3.6-build.140
		ftbultimine: FTB Ultimine 1802.3.3-build.55
		geckolib3: Geckolib 3.0.60
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		genesis: Genesis 1.18.2-1.0.1
		goblintraders: Goblin Traders 1.5.1
		highlighter: Highlighter 1.1.2
		iceberg: Iceberg 1.0.38
		illuminations: Illuminations 1.10.4
		indium: Indium 1.0.7+mc1.18.2
		infusion_table: Infusion Table 1.1.0
		inmis: Inmis 2.6.0-1.18.2
		iris: Iris 1.3.1
			org_anarres_jcpp: jcpp 1.4.14
		itemmodelfix: Item Model Fix 1.0.3+1.18
		java: OpenJDK 64-Bit Server VM 17
		jecalculation: Just Enough Calculation 4.0.0
		kibe: Kibe 1.9.9-BETA+1.18
			playerabilitylib: Pal 1.5.0
		kleeslabs: KleeSlabs 11.1.1
		krypton: Krypton 0.1.9
			com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		lambdynlights: LambDynamicLights 2.1.0+1.17
			pride: Pride Lib 1.1.0+1.17
			spruceui: SpruceUI 3.3.0+1.17
				org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		lightoverlay: Light Overlay 6.0.5
		lithium: Lithium 0.7.10
		logprot: Logprot Mod 1.18-1.6
		lovely_snails: Lovely Snails 1.0.4+1.18
		magehand: Magehand 1.1.2
		mcwbridges: Macaw's Bridges 2.0.3
		mcwdoors: Macaw's Doors 1.0.7
		mcwfences: Macaw's Fences and Walls 1.0.6
		mcwlights: Macaw's Lights and Lamps 1.0.4
		mcwpaintings: Macaw's Paintings 1.0.4
		mcwpaths: Macaw's Paths and Pavings 1.0.1
		mcwroofs: Macaw's Roofs 2.2.0b
		mcwtrpdoors: Macaw's Trapdoors 1.0.7
		mcwwindows: Macaw's Windows 2.0.3
		megane: megane 7.9.0
			megane-api: megane-api 7.9.0
			megane-applied-energistics-2: megane-applied-energistics-2 7.9.0
			megane-create: megane-create 7.9.0
			megane-fabric-transfer: megane-fabric-transfer 7.9.0
			megane-kibe: megane-kibe 7.9.0
			megane-reborn-core: megane-reborn-core 7.9.0
			megane-reborn-energy: megane-reborn-energy 7.9.0
			megane-runtime: megane-runtime 7.9.0
			megane-tech-reborn: megane-tech-reborn 7.9.0
			megane-vanilla: megane-vanilla 7.9.0
		minecraft: Minecraft 1.18.2
		moborigins: Mob Origins 1.8.1
		modmenu: Mod Menu 3.2.3
		mousetweaks: Mouse Tweaks 2.22
		mythicmounts: Mythic Mounts 1.18.2-7.0
		naturescompass: Nature's Compass 1.18.2-2.0.3-fabric
		no_more_purple: No More Purple 1.0.1
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		opaccreatesupport: OPAC Create Mod Support 1.1.0
		openpartiesandclaims: Open Parties and Claims 0.12.0
		origins: Origins 1.4.1
			apoli: Apoli 2.3.3
				additionalentityattributes: Additionalentityattributes 1.0.0+1.18.2
				calio: Calio 1.5.1
		origins-classes: Origins: Classes 1.3.0
		originsumbrellas: Origins: Umbrellas 1.5.2
		paintings: Paintings++ 9.1.2.1
		patchouli: Patchouli 1.18.2-71.1-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.4.2+1.14.4-1.19.2
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		pigpen: PigPen 8.0.1
		placementpog: Survival Building Toolkit 1.1.0
		plushies: Plushie Mod 1.2
		polymorph: Polymorph 0.0.21-1.18.2
			cardinal-components-block: Cardinal Components API (blocks) 4.1.4
			cardinal-components-item: Cardinal Components API (items) 4.1.4
		powah: Powah! 3.0.4-beta
		purpeille: Purpeille 2.3.3+fabric-1.18.2
			cmods: Combined Modifiers 1.2.0
			voidcrafting: Void Crafting 1.6.4+fabric-1.18.2
		quartzelv: Quartz Elevator 2.1.2+1.18.2
		reborncore: Reborn Core 5.2.0
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.18.2-build.58
		roughlyenoughitems: Roughly Enough Items 8.3.529
			error_notifier: Error Notifier 1.0.9
		roughlyenoughprofessions: Roughly Enough Professions 1.0.2
		roughlyenoughresources: Roughly Enough Resources 2.5.0
		runelic: Runelic 11.0.1
		skylorlib: SkyLib 1.3.35
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		sodium-extra: Sodium Extra 0.4.10+mc1.18.2-build.63
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		spark: spark 1.9.11
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		spirit: Spirit 2.1.8
		starlight: Starlight 1.0.2+fabric.89b8d9f
		stoneholm: Stoneholm 1.4.3
		techreborn: Tech Reborn 5.2.0
		thonkutil: ThonkUtil 2.14.1+1.18
			thonkutil-base: ThonkUtil Base 1.12.2+23c1dc2c60
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.3.2+9e23427060
			thonkutil-coords-v1: ThonkUtil Coords (v1) 1.0.19+9b80223760
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.0.14+9b80223760
			thonkutil-legacy: ThonkUtil Legacy 1.0.20+9b80223760
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.0.12+9b80223760
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.4.1+9b80223760
			thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.1.9+9b80223760
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.1.20+9b80223760
		toms_storage: Tom's Simple Storage Mod 1.4.1
		toolstats: ToolStats 9.0.3
		toomanybinds: Too Many Binds 0.3.2+1.18.2
			toomanybinds-compat-1-19: Too Many Binds 1.19 Compat 0.3.2+1.19
				toomanybinds-compat-1-18-2: Too Many Binds 1.18.2 Compat 0.3.2+1.18.2
					toomanybinds-compat-1-17: Too Many Binds 1.17 Compat 0.3.2+1.17
						toomanybinds-compat-1-16: Too Many Binds 1.16 Compat 0.3.2+1.16
							toomanybinds-core: Too Many Binds Core 0.3.2
		transparent: Transparent 4.1.0
		trinkets: Trinkets 3.3.1
		twigs: Twigs 1.1.3-patch2+1.18.2
		voicechat: Simple Voice Chat 1.18.2-2.3.9
		waystones: Waystones 2.5.5+mc1.18.2
		wildfire_gender: Wildfire's Female Gender Mod 2.9
		wthit: wthit 4.13.3
		xaerominimap: Xaero's Minimap 22.14.1
		xaeroworldmap: Xaero's World Map 1.27.0
		yigd: You're in Grave Danger 1.3.9
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.8
		zoomify: Zoomify 1.6.0
			dev_isxander_settxi: settxi 2.1.1
			settxicloth: Settxi Cloth Impl 1.0.2
	Loaded Shaderpack: (off)
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: fabric-loader-0.14.9-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3050/PCIe/SSE2 GL version 3.2.0 NVIDIA 512.77, NVIDIA Corporation
	Window size: 1024x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, Theinar Language, file/Vanilla-PBR-1-2-0 (1).zip
	Current Language: English (US)
	CPU: 6x AMD Ryzen 5 3600 6-Core Processor 
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Porting Lib (porting_lib), Create (create), Create Crafts & Additions (createaddition)
```

### Additional context

Seems related to #1630 as its another translation issue

**Comment by coderbot16** [comment]
I don't see anything indicating that Iris is causing this crash... Are you sure you tested without it? I'm going to guess your Create Crafts & Additions version might be incompatible with your Create version.

**Comment by coderbot16** [comment]
Closing due to no response.
