### ISSUE TITLE
Crashes with feather launcher

### ISSUE THREAD

**Issue by utilityuser2048** [IrisShaders/Iris#1640]
### Minecraft Version

Minecraft 1.18.2

### Iris Version

iris-mc1.18.2-1.3.1.jar

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15.jar

### Operating System

Windows 11

### What is your GPU?

Intel(R) UHD Graphics

### Java Version

Java 18

### Reproduction Steps

1. Place a Redstone Lamp in front of a Redstone Repeater
2. Use a Lever to activate the Redstone Repeater
3. Game Crashes

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2022/9/20 下午7:38
Description: Unexpected error

java.lang.RuntimeException: Shader program linking failed, see log for details
	at me.jellysquid.mods.sodium.client.gl.shader.GlProgram$Builder.link(GlProgram.java:113)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShader(IrisChunkProgramOverrides.java:161)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShaders(IrisChunkProgramOverrides.java:209)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.getProgramOverride(IrisChunkProgramOverrides.java:233)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.handler$bii000$iris$begin(ShaderChunkRenderer.java:548)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:70)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:221)
	at net.minecraft.class_761.method_3251(class_761.java:14466)
	at net.minecraft.class_761.invokeRenderChunkLayer(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:425)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:696)
	at net.minecraft.class_761.handler$bdo000$iris$renderTerrainShadows(class_761.java:9467)
	at net.minecraft.class_761.method_22710(class_761.java:1235)
	at net.minecraft.class_757.method_3188(class_757.java:1034)
	at net.minecraft.class_757.method_3192(class_757.java:813)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.gl.shader.GlProgram$Builder.link(GlProgram.java:113)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShader(IrisChunkProgramOverrides.java:161)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShaders(IrisChunkProgramOverrides.java:209)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.getProgramOverride(IrisChunkProgramOverrides.java:233)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.handler$bii000$iris$begin(ShaderChunkRenderer.java:548)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:70)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:221)
	at net.minecraft.class_761.method_3251(class_761.java:14466)
	at net.minecraft.class_761.invokeRenderChunkLayer(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:425)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:696)
	at net.minecraft.class_761.handler$bdo000$iris$renderTerrainShadows(class_761.java:9467)
	at net.minecraft.class_761.method_22710(class_761.java:1235)
	at net.minecraft.class_757.method_3188(class_757.java:1034)

-- Affected level --
Details:
	All players: 10 total; [class_746['zumingis_smart'/6462, l='ClientLevel', x=0.50, y=100.50, z=0.50], class_745['Workstations'/6343, l='ClientLevel', x=3.76, y=100.00, z=-3.91], class_745['§4'/1, l='ClientLevel', x=-4.50, y=99.00, z=-40.50], class_745['§1'/2, l='ClientLevel', x=2.50, y=99.00, z=-37.50], class_745['§0'/3, l='ClientLevel', x=-1.50, y=99.00, z=-37.50], class_745['§2'/4, l='ClientLevel', x=-11.50, y=99.00, z=-36.50], class_745['§3'/5, l='ClientLevel', x=-8.50, y=99.00, z=-39.50], class_745['§5'/17, l='ClientLevel', x=5.50, y=99.00, z=-40.50], class_745['§6'/47, l='ClientLevel', x=9.50, y=99.00, z=-39.50], class_745['§7'/53, l='ClientLevel', x=12.50, y=99.00, z=-36.50]]
	Chunk stats: 1024, 169
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,100,0), Section: (at 0,4,0 in 0,6,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 30449 game time, 6000 day time
	Server brand: CheatBungee <- Tuinity
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, RasplinVanilla

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 320217696 bytes (305 MiB) / 905969664 bytes (864 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
	Identifier: Intel64 Family 6 Model 140 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9a78
	Graphics card #0 versionInfo: DriverVersion=30.0.101.2079
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 13223.32
	Virtual memory used (MB): 9108.75
	Swap memory total (MB): 5376.00
	Swap memory used (MB): 433.86
	JVM Flags: 8 total; -Xmx2048M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:ErrorFile=feather/java_error.log
	Fabric Mods: 
		architectury: Architectury 4.4.68
		badpackets: Bad Packets 0.1.2
		cloth-config: Cloth Config v6 6.2.62
			cloth-basic-math: cloth-basic-math 0.6.1
		durability101: Durability101 0.0.4
		ecs: Elytra/Chestplate Swapper 1.2.0-MC1.18
		entityculling: EntityCulling-Fabric 1.5.1
		fabric: Fabric API 0.57.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.22+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.0+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.18+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.1+6c4e5d0960
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.22+e6b169eb60
			fabric-networking-v0: Fabric Networking (v0) 0.3.9+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.9+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.2+d005b03a60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.1+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabricloader: Fabric Loader 0.14.9
		feather: Feather Client 1.0.0-SNAPSHOT
		illuminations: Illuminations 1.10.3
		iris: Iris 1.3.1
			org_anarres_jcpp: jcpp 1.4.14
		java: OpenJDK 64-Bit Server VM 17
		lazydfu: LazyDFU 0.1.2
		lithium: Lithium 0.7.9
		meteor-client: Meteor Client 0.4.8
			baritone: Baritone 1.18.2-SNAPSHOT
		meteor-rejects: Meteor Rejects 0.2
			com_github_19misterx98_seedcrackerx_seedcrackerx-api: seedcrackerx-api master-SNAPSHOT
		meteorplus: MeteorPlus 1.1
		minecraft: Minecraft 1.18.2
		modmenu: Mod Menu 3.1.0
		mousewheelie: Mouse Wheelie 1.9.1+mc1.18.2
			amecsapi: Amecs API 1.3.6+mc22w06a
			coat: Coat 1.0.0-beta.18+mc1.18.2
			tweed4_annotated: tweed4_annotated 1.3.0+mc1.18.2
			tweed4_base: tweed4_base 1.5.0+mc1.18.2
			tweed4_data: tweed4_data 1.2.1+mc1.18.2
			tweed4_data_hjson: tweed4_data_hjson 1.1.0+mc1.18.2
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.2+mc1.18.2
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc1.18.2
		roughlyenoughitems: Roughly Enough Items 8.2.471
		seedcrackerx: SeedCrackerX 2.12
			com_seedfinding_latticg: latticg 1.6
			com_seedfinding_mc_biome: mc_biome b2271807a047bb43ac60c8c20ad47e315f19b9a6
			com_seedfinding_mc_core: mc_core 88b246597e0147e37b38d1b33e9526e6c3eb1469
			com_seedfinding_mc_feature: mc_feature ef939c0dd7d66ab1bd290d6aab1e42a12cb3dbf1
			com_seedfinding_mc_math: mc_math 0eb505174da8a92550f8ec6efe254e0fa936cc0d
			com_seedfinding_mc_noise: mc_noise a6ab8e6c688491829f8d2adf845392da22ef8e9c
			com_seedfinding_mc_reversal: mc_reversal 2.0.0
			com_seedfinding_mc_seed: mc_seed 5518e3ba3ee567fb0b51c15958967f70a6a19e02
			com_seedfinding_mc_terrain: mc_terrain 9e937ddb838e28e79423c287fa18b1ce66f061d7
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		starlight: Starlight 1.0.2+fabric.89b8d9f
		wi_zoom: WI Zoom 1.4-MC1.18.2
		wthit: wthit 4.10.3
		xaerominimap: Xaero's Minimap 22.13.2
	Loaded Shaderpack: MakeUp-UltraFast-8.0.zip
		Profile: low (+1 option changed by user)
	Launched Version: 1.18.2-feather
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics GL version 3.2.0 - Build 30.0.101.2079, Intel
	Window size: 1920x1009
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='SHADER_ID_LINK error has been generated. GLSL link failed for program 183, "": Number of Fragment Outputs exceeds HW limits.

' x 1
id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3891749976) glGetUniformLocation- program 183, "" is not linked' x 200
id=1, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='SHADER_ID_LINK error has been generated. GLSL link failed for program 195, "": Number of Fragment Outputs exceeds HW limits.

' x 1
id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3891749976) glGetUniformLocation- program 195, "" is not linked' x 200
id=1, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='SHADER_ID_LINK error has been generated. GLSL link failed for program 198, "": Number of Fragment Outputs exceeds HW limits.

' x 1
id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3891749976) glGetUniformLocation- program 198, "" is not linked' x 200
id=1, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='SHADER_ID_LINK error has been generated. GLSL link failed for program 201, "": Number of Fragment Outputs exceeds HW limits.

' x 1
id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3891749976) glGetUniformLocation- program 201, "" is not linked' x 200
id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3891749976) glGetUniformLocation- program 162, "" is not linked' x 18
id=1, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='SHADER_ID_LINK error has been generated. GLSL link failed for program 393, "": Number of Fragment Outputs exceeds HW limits.

' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'Feather Fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, file/RasplinVanilla (incompatible)
	Current Language: English (US)
	CPU: 4x 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz

-- Meteor Client --
Version: 0.4.8

[Render]:
better-tooltips
camera-tweaks
entity-owner
fullbright
item-physics
nametags
no-render
search

[World]:
auto-mount

[Misc]:
middle-click-friend
server-spoof
```

**Comment by IMS212** [comment]
We do not support Feather.
