### ISSUE TITLE
Iris Crashed when I join a server

### ISSUE THREAD

**Issue by Progreymer** [IrisShaders/Iris#1649]
### Minecraft Version

1.19.2

### Iris Version

1.19.2-1.3.1

### Sodium Version

mc1.19-0.4.2+build.16

### Operating System

MacOSX

### What is your GPU?

M1

### Java Version

Java 18

### Reproduction Steps

1. Join a Server
3. Game Crashes

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 2022-09-25 15:00:44
Description: Unexpected error

java.lang.IllegalStateException: An invalid version of Sodium is installed, and the warning screen somehow didn't work. This is a bug! Please report it to the Iris developers.
	at net.minecraft.class_761.handler$zkh000$iris$beginLevelRender(class_761.java:6505)
	at net.minecraft.class_761.method_22710(class_761.java:1227)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_761.handler$zkh000$iris$beginLevelRender(class_761.java:6505)
	at net.minecraft.class_761.method_22710(class_761.java:1227)
	at net.minecraft.class_757.method_3188(class_757.java:1039)

-- Affected level --
Details:
	All players: 21 total; [class_746['Computeroid'/1467544, l='ClientLevel', x=124.26, y=167.06, z=175.63], class_745['Vuatex'/1443597, l='ClientLevel', x=118.92, y=167.00, z=161.67], class_745['Mowwow'/830340, l='ClientLevel', x=131.66, y=168.56, z=161.31], class_745['mrgeem'/997, l='ClientLevel', x=130.09, y=168.17, z=166.76], class_745['MilsonDev'/1252426, l='ClientLevel', x=129.99, y=167.00, z=162.90], class_745['whalo_the_goat'/1282850, l='ClientLevel', x=121.19, y=167.00, z=170.91], class_745['IRFender'/1467492, l='ClientLevel', x=122.50, y=167.00, z=164.50], class_745['Freddy_FrazBear8'/1349043, l='ClientLevel', x=122.26, y=172.19, z=176.71], class_745['Ace_Pringl_man69'/1325193, l='ClientLevel', x=107.60, y=164.63, z=169.26], class_745['surfbruh1234'/887006, l='ClientLevel', x=128.50, y=167.00, z=166.29], class_745['meruby'/909505, l='ClientLevel', x=130.06, y=167.00, z=174.01], class_745['FMF66'/1119373, l='ClientLevel', x=128.51, y=181.00, z=173.99], class_745['LegoDestroyer61'/611050, l='ClientLevel', x=143.86, y=166.00, z=168.48], class_745['MatDrazkow'/1048398, l='ClientLevel', x=116.76, y=167.00, z=172.21], class_745['Poolpuppy'/1359338, l='ClientLevel', x=122.38, y=167.00, z=167.65], class_745['DerMarabou'/1209279, l='ClientLevel', x=122.50, y=167.00, z=164.50], class_745['poopyhamster'/1401471, l='ClientLevel', x=128.13, y=167.00, z=162.53], class_745['LasseRosenalm'/1246560, l='ClientLevel', x=127.79, y=167.00, z=161.57], class_745['gutydu74'/1454745, l='ClientLevel', x=122.50, y=167.00, z=164.50], class_745['NotsavageXD'/1455607, l='ClientLevel', x=122.50, y=167.00, z=164.50], class_745['Xuancena1234'/1268692, l='ClientLevel', x=122.50, y=167.00, z=164.50]]
	Chunk stats: 1024, 201
	Level dimension: minecraft:spawn
	Level spawn location: World: (29199,110,29473), Section: (at 15,14,1 in 1824,6,1842; chunk contains blocks 29184,-64,29472 to 29199,319,29487), Region: (57,57; contains chunks 1824,1824 to 1855,1855, blocks 29184,-64,29184 to 29695,319,29695)
	Level time: 159999 game time, 142892907 day time
	Server brand: §emc.lifestealsmp.com§r
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, My VanillaTweaks pack, Fabric Mods, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Mac OS X (x86_64) version 12.3.1
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 646293200 bytes (616 MiB) / 1442840576 bytes (1376 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 16384.00
	Virtual memory used (MB): 10761.44
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.62.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.21+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.2+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.12+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.29+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.35+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.3.1+624e468e90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.0+b598f4ac90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.19+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.29+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.30+93d8cb8290
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.21+93d8cb8290
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.19+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.4+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.7+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.15+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.18+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90
			fabric-networking-v0: Fabric Networking (v0) 0.3.22+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.12+93d8cb8290
			fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.11+c6af733c90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.13+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.21+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.15+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.23+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.0+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.12+a29562c890
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.7.0+93d8cb8290
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.27+93d8cb8290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
			fabric-textures-v0: Fabric Textures (v0) 1.0.21+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290
		fabricloader: Fabric Loader 0.14.9
		fpsdisplay: FPS-Display 1.5.0+1.19
		inventorytabs: Inventory Tabs 0.8.1-1.19.x
		iris: Iris 1.3.1
			org_anarres_jcpp: jcpp 1.4.14
		java: OpenJDK 64-Bit Server VM 17
		logical_zoom: Logical Zoom 0.0.17
		malilib: MaLiLib 0.13.0
		minecraft: Minecraft 1.19.2
		minecraftcapes: MinecraftCapes Mod 12.2.0
		minihud: MiniHUD 0.23.3
		modmenu: Mod Menu 4.0.6
		mousetweaks: Mouse Tweaks 2.22
		multiconnect: MultiConnect 1.6-beta.23
			multiconnect-api: MultiConnect API 1.6-beta.23
		replaymod: Replay Mod 1.19.1-2.6.8
		seedcrackerx: SeedCrackerX 2.13
			com_seedfinding_latticg: latticg 1.6
			com_seedfinding_mc_biome: mc_biome b2271807a047bb43ac60c8c20ad47e315f19b9a6
			com_seedfinding_mc_core: mc_core 706e4f1b7aa6b42b3627f682a311d06280d80b5c
			com_seedfinding_mc_feature: mc_feature ef939c0dd7d66ab1bd290d6aab1e42a12cb3dbf1
			com_seedfinding_mc_math: mc_math 0eb505174da8a92550f8ec6efe254e0fa936cc0d
			com_seedfinding_mc_noise: mc_noise a6ab8e6c688491829f8d2adf845392da22ef8e9c
			com_seedfinding_mc_reversal: mc_reversal 2.0.0
			com_seedfinding_mc_seed: mc_seed 5518e3ba3ee567fb0b51c15958967f70a6a19e02
			com_seedfinding_mc_terrain: mc_terrain 9e937ddb838e28e79423c287fa18b1ce66f061d7
		shulkerboxtooltip: Shulker Box Tooltip 3.1.3+1.19.2
			cloth-config: Cloth Config v8 8.2.88
				cloth-basic-math: cloth-basic-math 0.6.1
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.6+mc1.19-build.47
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		tweakeroo: Tweakeroo 0.14.3
		xaerominimap: Xaero's Minimap 22.14.1
		xaeroworldmap: Xaero's World Map 1.27.0
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.14.9-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Apple M1 GL version 4.1 Metal - 76.3, Apple
	Window size: 2880x1800
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	GPU Warnings: version: Metal
	Graphics mode: fancy
	Resource Packs: vanilla, file/My VanillaTweaks pack (incompatible), Fabric Mods
	Current Language: English (US)
	CPU: 8x Apple M1
```

### Additional context

None

**Comment by Lolothepro** [comment]
update Sodium

**Comment by coderbot16** [comment]
How did you get to this point? Did Iris show you a warning screen? Did you click on a ReplayMod button?

**Comment by coderbot16** [comment]
Could be related to https://github.com/IrisShaders/Iris/issues/1622#issue-1360598925

**Comment by Progreymer** [comment]
I simply, started up minecraft, and join a server that I have been on many
times before with iris, but this time I used the newest version of iris and
sodium mods.
Nothing else.

**Comment by coderbot16** [comment]
Your log shows that you have Replay Mod installed, so this doesn't appear to be just an Iris and Sodium issue. Without any additional information or confirmation that this is separate, I'm going to mark this as a duplicate.
