### ISSUE TITLE
I am crashing on 1.19.2 on joining a world of any kind 

### ISSUE THREAD

**Issue by FacelessFace** [IrisShaders/Iris#1686]
### Minecraft Version

1.19.2

### Iris Version

iris-mc1.19.2-1.3.1.jar

### Sodium Version

sodium-fabric-mc1.19.2-0.4.4+build.18 (1).jar

### Operating System

windows 10

### What is your GPU?

Nvidia 2060

### Java Version

16

### Reproduction Steps

load game 
2.join world of some kind
3. Game Crashes

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2022-10-07 17:46:57
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_31548()" because "this.field_3712.field_1724" is null
	at net.minecraft.class_636.method_2911(class_636.java:312)
	at net.minecraft.class_636.method_2927(class_636.java:291)
	at net.minecraft.class_310.method_1574(class_310.java:1799)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_636.method_2911(class_636.java:312)
	at net.minecraft.class_636.method_2927(class_636.java:291)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 16384, 277
	Level dimension: minecraft:overworld
	Level spawn location: World: (-386,64,829), Section: (at 14,0,13 in -25,4,51; chunk contains blocks -400,-64,816 to -385,319,831), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,-64,512 to -1,319,1023)
	Level time: 99711 game time, 47109354 day time
	Server brand: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.class_746.method_3135()" because "this.field_3729.field_1724" is null
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1699490656 bytes (1620 MiB) / 2617245696 bytes (2496 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f15
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9bc4
	Graphics card #1 versionInfo: DriverVersion=27.20.100.9365
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 33580.87
	Virtual memory used (MB): 20610.53
	Swap memory total (MB): 17408.00
	Swap memory used (MB): 508.74
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.2.46
		balm-fabric: Balm 4.5.2+0
		baritone: Baritone 1.8.3-134-g43d6eadf
		bedrockminer: Bedrock Miner 1.0.0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.6.1+aeb40ebe90
		betterf3: BetterF3 1.3.2
		bettermounthud: Better Mount HUD 1.1.4
		bookshelf: Bookshelf 16.1.5
		carpet: Carpet Mod 1.4.83
		chat-up: Chat Up! 2.1
		clientsidenoteblocks: ClientSideNoteblocks 2.2
		clienttweaks: Client Tweaks 8.1.0
		cloth-config: Cloth Config v6 7.0.74
			cloth-basic-math: cloth-basic-math 0.6.1
		collective-fabric: Collective (Fabric) 4.64
			fiber: fiber 0.23.0-2
		controlling: Controlling For Fabric 10.0+6
		craftingtweaks: Crafting Tweaks 15.1.0
		fabric-api: Fabric API 0.59.0+1.19.2
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.8+9ff28f4090
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.16+83a8659290
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.19+9ff28f4090
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.0+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.10+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.6+0c17ea9690
			fabric-commands-v0: Fabric Commands (v0) 0.2.27+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.33+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.2+83a8659290
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.0+7cd20a1490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.4+bd0a0d4a90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.7+a680b9b490
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.29+a6d2f78590
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.17+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.27+9ff28f4090
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.27+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.20+1899036190
			fabric-item-api-v1: Fabric Item API (v1) 1.5.6+35a03c4390
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.27+6bee109e90
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.17+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.1+83a8659290
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.2+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.5+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.2+176380a290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.13+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.16+9ff28f4090
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.3+5eb68ef290
			fabric-networking-v0: Fabric Networking (v0) 0.3.20+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.10+7675279690
			fabric-particles-v1: Fabric Particles (v1) 1.0.9+dc39553a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.23+23c4cfef90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.9+84f79e9d90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.11+5187d39f90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.19+df3654b390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.21+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.15+9ff28f4090
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.10+e62f51a390
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.25+f05effaf90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.12+9ff28f4090
			fabric-textures-v0: Fabric Textures (v0) 1.0.19+9ff28f4090
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.10+83a8659290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.2.0+1e232e1390
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.9
		farsight: Farsight Mod 1.19.1-2.0
		geckolib3: Geckolib 3.1.20
			com_eliotlash_mclib_mclib: mclib 19
			com_eliotlash_molang_molang: molang 19
		inventoryprofilesnext: Inventory Profiles Next 1.6.3
		inventorytabs: Inventory Tabs 0.8.1-1.19.x
		iris: Iris 1.3.1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.20+aeb40ebe90
			org_anarres_jcpp: jcpp 1.4.14
		itemscroller: Item Scroller 0.17.1
		jamlib: JamLib 0.4.4
		java: OpenJDK 64-Bit Server VM 17
		jex: Jex Client 0.8.6
		litematica: Litematica 0.12.3
		lod: Distant Horizons 1.6.9a
		malilib: MaLiLib 0.13.0
		minecraft: Minecraft 1.19.2
		minihud: MiniHUD 0.23.3
		modmenu: Mod Menu 4.0.6
		owo: oωo 0.8.2+1.19
			blue_endless_jankson: jankson 1.2.1
		phosphor: Phosphor 0.8.1
		sodium: Sodium 0.4.4+build.18
			fabric-api-base: Fabric API Base 0.4.11+e62f51a390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.14+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.7+aeb40ebe90
			org_joml_joml: joml 1.10.4
		tweakeroo: Tweakeroo 0.14.3
		worldedit: WorldEdit 7.2.12+6240-87f4ae1
		wurst: Wurst Client v7.28-MC1.19.2
		xaerominimap: Xaero's Minimap 22.15.0
		xaeroworldmap: Xaero's World Map 1.28.0
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.14.9-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.94, NVIDIA Corporation
	Window size: 2560x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
```

**Comment by BrudiDog** [comment]
I am having the same issue, how did you fix this?
