### ISSUE TITLE
1.16.5: Lux does not work with some GPUs

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1715]
### What happened?

Lux does not work with some GPUs

### Log output

```
Shader compilation log for gbuffers_water.fsh: 0(1002) : error C1101: ambiguous overloaded function reference "clamp(int, int, int)"
    (0) : ps gp5 gp4 cp50 fp50 vp50 gp50 cpf fpf vpf gpf lowp vec4 clamp(lowp vec4, lowp float, lowp float)
    (0) : ps gp5 gp4 cp50 fp50 vp50 gp50 cpf fpf vpf gpf lowp vec3 clamp(lowp vec3, lowp float, lowp float)
    (0) : ps gp5 gp4 cp50 fp50 vp50 gp50 cpf fpf vpf gpf lowp vec2 clamp(lowp vec2, lowp float, lowp float)
    (0) : ps gp5 gp4 cp50 fp50 vp50 gp50 cpf fpf vpf gpf lowp vec1 clamp(lowp vec1, lowp float, lowp float)
    (0) : ps gp5 gp4 cp50 fp50 vp50 gp50 cpf fpf vpf gpf mediump vec4 clamp(mediump vec4, mediump float, mediump float)
    (0) : ps gp5 gp4 cp50 fp50 vp50 gp50 cpf fpf vpf gpf mediump vec3 clamp(mediump vec3, mediump float, mediump float)
    (0) : ps gp5 gp4 cp50 fp50 vp50 gp50 cpf fpf vpf gpf mediump vec2 clamp(mediump vec2, mediump float, mediump float)
    (0) : ps gp5 gp4 cp50 fp50 vp50 gp50 cpf fpf vpf gpf mediump vec1 clamp(mediump vec1, mediump float, mediump float)
    (0) : vec4 clamp(vec4, float, float)
    (0) : vec3 clamp(vec3, float, float)
    (0) : vec2 clamp(vec2, float, float)
    (0) : vec1 clamp(vec1, float, float)
    (0) : ps gp5 gp4 cp50 fp50 vp50 gp50 cpf fpf vpf gpf lowp float clamp(lowp float, lowp float, lowp float)
    (0) : ps gp5 gp4 cp50 fp50 vp50 gp50 cpf fpf vpf gpf mediump float clamp(mediump float, mediump float, mediump float)
    (0) : float clamp(float, float, float)
[18:00:29] [Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.RuntimeException: Failed to create pass for gbuffers_water for rendering condition TERRAIN_TRANSLUCENT specialized to input availability InputAvailability{texture=true, lightmap=true, overlay=false}
	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.lambda$new$1(DeferredWorldRenderingPipeline.java:323) ~[iris-mc1.16.5-1.3.1.jar:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.lambda$new$2(DeferredWorldRenderingPipeline.java:300) ~[iris-mc1.16.5-1.3.1.jar:?]
	at net.coderbot.iris.gbuffer_overrides.matching.ProgramTable.<init>(ProgramTable.java:16) ~[iris-mc1.16.5-1.3.1.jar:?]
	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.<init>(DeferredWorldRenderingPipeline.java:283) ~[iris-mc1.16.5-1.3.1.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:643) ~[iris-mc1.16.5-1.3.1.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) [iris-mc1.16.5-1.3.1.jar:?]
	at net.coderbot.iris.Iris.onLoadingComplete(Iris.java:217) [iris-mc1.16.5-1.3.1.jar:?]
	at net.minecraft.class_442.handler$zbm000$iris$showSodiumIncompatScreen(class_442.java:539) [client-intermediary.jar:?]
	at net.minecraft.class_442.method_25426(class_442.java:138) [client-intermediary.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:325) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:922) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:579) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:177) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) [NewLaunch.jar:?]
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Failed to compile FRAGMENT shader for program gbuffers_water.fsh
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:79) ~[iris-mc1.16.5-1.3.1.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:50) ~[iris-mc1.16.5-1.3.1.jar:?]
	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.createPass(DeferredWorldRenderingPipeline.java:578) ~[iris-mc1.16.5-1.3.1.jar:?]
	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.lambda$new$1(DeferredWorldRenderingPipeline.java:321) ~[iris-mc1.16.5-1.3.1.jar:?]
	... 25 more
Caused by: java.lang.RuntimeException: Shader compilation failed, see log for details
	at net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:40) ~[iris-mc1.16.5-1.3.1.jar:?]
	at net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:21) ~[iris-mc1.16.5-1.3.1.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:77) ~[iris-mc1.16.5-1.3.1.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:50) ~[iris-mc1.16.5-1.3.1.jar:?]
	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.createPass(DeferredWorldRenderingPipeline.java:578) ~[iris-mc1.16.5-1.3.1.jar:?]
	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.lambda$new$1(DeferredWorldRenderingPipeline.java:321) ~[iris-mc1.16.5-1.3.1.jar:?]
	... 25 more
```

### Minecraft Version

1.16.5

### Iris Version

Iris 1.4.0

### Operating System

Linux Mint 21

### What is your GPU?

GT 210

**Comment by Lolothepro** [comment]
fixed by https://github.com/TechDevOnGitHub/Lux-Shader/commit/66888fe6501aa0e98fe1974d9c59e6af67348c93
