### ISSUE TITLE
Memory leak after update to iris 1.4.2

### ISSUE THREAD

**Issue by 5ur3z** [IrisShaders/Iris#1762]
### Minecraft Version

Minecraft 1.18.2

### Iris Version

iris-mc1.18.2-1.4.2.jar

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar

### Operating System

Windows 11

### What is your GPU?

NVIDIA RTX 3050

### Java Version

Open JDK 17

### Reproduction Steps

Join a server
play for sometime 
crash with memory leak.

### Crash Report file and latest.log

```shell
[18:24:13] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.10
[18:24:13] [ForkJoinPool-1-worker-5/WARN]: Mod xercamusic uses the version fabric-1.18.2-1.0.0 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[18:24:13] [main/INFO]: Loading 225 mods:
	- additionaladditions 4.0.5
	- advanced_runtime_resource_pack 0.5.5 via extrasounds
	- adventure-platform-fabric 5.2.1 via tabtps-fabric
	- amecsapi 1.3.6+mc22w06a via big_items_duh
	- appleskin 2.4.1+mc1.18.2
	- architectury 4.10.86
	- bendy-lib 2.1.2 via emotecraft
	- better_loading_screen 1.4.0
	- betterf3 3.0.0
	- betterpingdisplay 1.1.1
	- betterstats 1.4.1
	- bettertags 1.18.2-Fabric-v1.1
	- big_items_duh 1.1.2+mc1.18.2
	- blue_endless_jankson 1.2.1 via jankson
	- blur 2.4.1
	- bookshelf 13.2.50
	- byg 1.4
	- caffeineconfig 1.0.0+1.17 via sodium-extra
	- cardinal-components-base 4.1.4 via pollen
	- cardinal-components-entity 4.1.4 via pollen
	- charmonium 4.1.0
	- chat_heads 0.6.0
	- chimes 1.1.1
	- cloth-api 3.2.64
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-client-events-v0 3.2.64 via cloth-api
	- cloth-common-events-v1 3.2.64 via cloth-api
	- cloth-config 6.4.90
	- cloth-datagen-api-v1 3.2.64 via cloth-api
	- cloth-scissors-api-v1 3.2.64 via cloth-api
	- cloth-utils-v1 3.2.64 via cloth-api
	- cloud 1.7.0-SNAPSHOT via tabtps-fabric
	- cloud_commandframework_cloud-brigadier_ 1.7.0-SNAPSHOT via cloud
	- cloud_commandframework_cloud-core_ 1.7.0-SNAPSHOT via cloud
	- cloud_commandframework_cloud-minecraft-extras 1.7.0-SNAPSHOT via tabtps-fabric
	- cloud_commandframework_cloud-services_ 1.7.0-SNAPSHOT via cloud
	- coat 1.0.0-beta.17+mc1.18.2 via big_items_duh
	- com_electronwill_night-config_core 3.6.5 via forgeconfigapiport
	- com_electronwill_night-config_toml 3.6.5 via forgeconfigapiport
	- com_github_llamalad7_mixinextras 0.1.0-rc5 via do_a_barrel_roll
	- com_moandjiezana_toml_toml4j 0.7.2 via charmonium
	- com_typesafe_config 1.4.2 via tabtps-fabric
	- continuity 2.0.1+1.18.2
	- creativecore 2.6.12
	- customskinloader 14.14
	- debugify 1.11.0
	- detailab 2.6.2+1.18-fabric
	- disguiselib 1.2.2
	- display_case 1.0.3
	- do_a_barrel_roll 2.2.1+1.18.2
	- dynamicfps 2.1.0
	- dynamicsoundfilters 1.3.0+1.18.2
	- eatinganimationid 1.8
	- elytra_physics 1.1.1
	- emotecraft 2.2.5
	- enhancedblockentities 0.7.1+1.18.2
	- entityculling 1.5.1
	- error_notifier 1.0.9 via roughlyenoughitems
	- etched 2.2.0
	- extrasounds 2.3.1+1.18.2
	- fabric-api 0.67.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric-api
	- fabric-api-lookup-api-v1 1.6.2+2373a54560 via fabric-api
	- fabric-biome-api-v1 8.0.6+651bcc5960 via fabric-api
	- fabric-block-api-v1 1.0.0+ee3621fc60 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric-api
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric-api
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric-api
	- fabric-containers-v0 0.1.23+d7c144a860 via fabric-api
	- fabric-content-registries-v0 3.1.1+c85f2e3860 via fabric-api
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric-api
	- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric-api
	- fabric-data-generation-api-v1 3.0.2+9fcb91d260 via fabric-api
	- fabric-dimensions-v1 2.1.20+489d6f8260 via fabric-api
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric-api
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric-api
	- fabric-events-lifecycle-v0 0.2.20+d7c144a860 via fabric-api
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric-api
	- fabric-item-api-v1 1.6.0+d8cf4e5a60 via fabric-api
	- fabric-item-groups-v0 0.3.14+91896a4960 via fabric-api
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via big_items_duh
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric-api
	- fabric-language-kotlin 1.8.5+kotlin.1.7.20
	- fabric-lifecycle-events-v1 2.1.0+cc71601c60 via fabric-api
	- fabric-loot-api-v2 1.1.0+1997ad1260 via fabric-api
	- fabric-loot-tables-v1 1.1.2+e747827960 via fabric-api
	- fabric-mining-level-api-v1 2.1.4+cc71601c60 via fabric-api
	- fabric-models-v0 0.3.6+d7c144a860 via fabric-api
	- fabric-networking-api-v1 1.0.23+2d30af4b60 via fabric-api
	- fabric-networking-v0 0.3.10+b4f4f6cd60 via fabric-api
	- fabric-object-builder-api-v1 2.1.3+032c981d60 via fabric-api
	- fabric-ofcapes 2.0.0
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric-api
	- fabric-permissions-api-v0 0.1-SNAPSHOT via cloud
	- fabric-registry-sync-v0 0.9.11+bb2e047760 via fabric-api
	- fabric-renderer-api-v1 0.4.15+ee3621fc60 via fabric-api
	- fabric-renderer-indigo 0.5.5+41a02c8a60 via fabric-api
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.8+ee3621fc60 via fabric-api
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric-api
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric-api
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric-api
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric-api
	- fabric-resource-loader-v0 0.5.2+446e059560 via fabric-api
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric-api
	- fabric-screen-handler-api-v1 1.2.2+1f6558e860 via fabric-api
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric-api
	- fabric-transfer-api-v1 1.6.3+f4563ac860 via fabric-api
	- fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric-api
	- fabricloader 0.14.10
	- farmersdelight 1.18.2-1.2.1
	- ferritecore 4.2.1
	- flighthud 1.18-fabric-2
	- forgeconfigapiport 3.2.4
	- freecam 1.1.6
	- goosik-config 0.2.0 via visuality
	- highlighter 1.1.2
	- iceberg 1.0.38
	- indium 1.0.7+mc1.18.2
	- ingameime 1.6.5
	- inventoryhud 3.4.2
	- inventoryprofilesnext 1.8.3
	- io_github_douira_glsl-transformer 1.0.0-pre21.2 via iris
	- io_leangen_geantyref_geantyref 1.3.13 via cloud
	- iris 1.4.2
	- itemmodelfix 1.0.3+1.18
	- itemphysiclite 1.5.0
	- jade 5.99.9
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- javazoom_jlayer 1.0.1 via etched
	- kirin 1.10.0 via presencefootsteps
	- lambdynlights 2.1.0+1.17
	- lazydfu 0.1.2
	- libgui 5.1.0+1.18 via additionaladditions
	- libipn 1.0.4
	- libninepatch 1.1.0 via libgui
	- litematica 0.11.3
	- lithium 0.7.10
	- logical_zoom 0.0.14
	- lychee 2.0.0
	- malilib 0.12.1
	- memoryleakfix 1.18.2-0.7.0
	- midnightcontrols 1.5.0+1.18
	- midnightlib 0.4.4
	- minecraft 1.18.2
	- modmenu 3.2.3
	- morechathistory 1.1.0
	- mousetweaks 2.22
	- net_kyori_adventure-api 4.10.1 via adventure-platform-fabric
	- net_kyori_adventure-key 4.10.1 via adventure-platform-fabric
	- net_kyori_adventure-platform-api 4.1.0 via adventure-platform-fabric
	- net_kyori_adventure-serializer-configurate4 4.10.1 via tabtps-fabric
	- net_kyori_adventure-text-feature-pagination 4.0.0-SNAPSHOT via tabtps-fabric
	- net_kyori_adventure-text-minimessage 4.10.1 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-gson 4.10.1 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-legacy 4.10.1 via tabtps-fabric
	- net_kyori_adventure-text-serializer-plain 4.10.1 via adventure-platform-fabric
	- net_kyori_examination-api 1.3.0 via adventure-platform-fabric
	- net_kyori_examination-string 1.3.0 via adventure-platform-fabric
	- notenoughanimations 1.6.0
	- opitems 1.2.1
	- org_anarres_jcpp 1.4.14 via iris
	- org_antlr_antlr4-runtime 4.10.1 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via midnightcontrols
	- org_javassist_javassist 3.28.0-GA via yungsapi
	- org_jetbrains_kotlin_kotlin-reflect 1.7.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.20 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- org_reflections_reflections 0.10.2 via yungsapi
	- org_spongepowered_configurate-core 4.1.2 via tabtps-fabric
	- org_spongepowered_configurate-hocon 4.1.2 via tabtps-fabric
	- player-animator 0.3.5
	- pollen 1.5.0
	- presencefootsteps 1.5.1
	- pride 1.1.0+1.17 via lambdynlights
	- quilt-loading-screen 2.2.1+1.17
	- raised 1.1.3
	- reeses-sodium-options 1.4.7+mc1.18.2-build.58
	- rfnaddition 1.0.0
	- roughly_enough_loot_tables 1.18-1.1
	- roughly_enough_trades 1.1.1
	- roughlyenoughitems 8.3.564
	- roughlyenoughprofessions 1.0.2
	- satin 1.7.0 via blur
	- screenshotclipboard 1.0.9
	- shouldersurfing 2.2.16
	- sit 1.18.2-19
	- skinlayers 1.5.2-mc1.18.2
	- slotlock 1.1.1-BETA+1.18
	- smoothboot 1.18.2-1.7.0
	- smwyg 1.0.1
	- sodium 0.4.1+replaymod.rev.23e83a1
	- sodium-extra 0.4.11+mc1.18.2-build.67
	- sodiumfix 1.0.2
	- soundcategories 1.2.4+1.18 via extrasounds
	- spruceui 3.3.2+1.17 via midnightcontrols
	- sspb 2.0.1
	- syncmatica 1.18.2-0.3.2
	- tabtps-fabric 1.3.13
	- terrablender 1.2.0.126
	- tipsmod 5.0.9
	- travelerstitles 1.18.2-Fabric-2.1.1
	- tweed4_annotated 1.3.0 via big_items_duh
	- tweed4_base 1.5.0+mc1.18.2 via big_items_duh
	- tweed4_data 1.2.1+mc1.18.2 via big_items_duh
	- tweed4_data_hjson 1.1.0 via big_items_duh
	- tweed4_tailor_coat 1.1.2+mc1.18.2 via big_items_duh
	- tweed4_tailor_screen 1.1.1+mc1.18.2 via big_items_duh
	- visuality 0.4.3
	- waveycapes 1.2.0
	- xaerominimap 22.16.0
	- xaeroworldmap 1.28.1
	- xercamusic fabric-1.18.2-1.0.0
	- xibaopp 0.1.0-release-mc1.18.2
	- yungsapi 1.18.2-Fabric-2.2.6
[18:24:14] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Program%20Files/Rainbow%20Fox%20Network%20Group/Rainbow%20Fox%20Network/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[18:24:14] [main/INFO]: Compatibility level set to JAVA_16
[18:24:14] [main/INFO]: Compatibility level set to JAVA_17
[18:24:15] [main/WARN]: Reference map 'chimes-refmap.json' for chimes.mixins.json could not be read. If this is a development environment you can ignore this message
[18:24:15] [main/INFO]: Preloading Debugify
[18:24:15] [main/INFO]: Done.
[18:24:15] [main/INFO]: Loaded configuration file for Lithium: 102 options available, 1 override(s) found
[18:24:15] [main/WARN]: Reference map 'jadeaddons.refmap.json' for jadeaddons.mixins.json could not be read. If this is a development environment you can ignore this message
[18:24:15] [main/WARN]: Reference map 'opitems-refmap.json' for opitems.mixins.json could not be read. If this is a development environment you can ignore this message
[18:24:15] [main/WARN]: Reference map 'RoughlyEnoughTrades-refmap.json' for roughly_enough_trades.mixins.json could not be read. If this is a development environment you can ignore this message
[18:24:15] [main/WARN]: [Satin] Sodium is present, custom block renders may not work
[18:24:15] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[18:24:15] [main/INFO]: Loaded configuration file for Sodium Extra: 29 options available, 0 override(s) found
[18:24:15] [main/WARN]: Reference map 'xercamusic-refmap.json' for xercamusic.mixins.json could not be read. If this is a development environment you can ignore this message
[18:24:16] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[18:24:16] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/components/structureMovement/interaction/controls/TrainHUD (java.lang.ClassNotFoundException: com/simibubi/create/content/contraptions/components/structureMovement/interaction/controls/TrainHUD)
[18:24:16] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.components.structureMovement.interaction.controls.TrainHUD was not found raised.mixins.json:mods.CreateMixin$ToolboxHandlerClientMixin from mod raised
[18:24:16] [main/WARN]: Error loading class: com/simibubi/create/content/curiosities/toolbox/ToolboxHandlerClient (java.lang.ClassNotFoundException: com/simibubi/create/content/curiosities/toolbox/ToolboxHandlerClient)
[18:24:16] [main/WARN]: @Mixin target com.simibubi.create.content.curiosities.toolbox.ToolboxHandlerClient was not found raised.mixins.json:mods.CreateMixin$TrainHUDMixin from mod raised
[18:24:16] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[18:24:16] [main/WARN]: [SSPB] Reese's Sodium Options >= 1.4.2 detected. Mixin 'rynnavinx.sspb.mixin.reeses_sodium_options.MixinSodiumVideoOptionsScreen' will not be enabled
[18:24:16] [main/WARN]: Error loading class: net/coderbot/iris/layer/IrisRenderLayerWrapper (java.lang.ClassNotFoundException: net/coderbot/iris/layer/IrisRenderLayerWrapper)
[18:24:16] [main/WARN]: @Mixin target net.coderbot.iris.layer.IrisRenderLayerWrapper was not found mixins.satin.client.json:iris.IrisRenderLayerWrapperMixin from mod satin
[18:24:16] [main/INFO]: I used the json to destroy the json
[18:24:18] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[18:24:19] [main/INFO]: Smooth Boot config initialized
[18:24:19] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[18:24:19] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[18:24:20] [main/WARN]: @Final field field_22786:Ljava/util/List; in mixins.ipnext.json:MixinScreen from mod inventoryprofilesnext should be final
[18:24:20] [main/WARN]: @Final field field_33815:Ljava/util/List; in mixins.ipnext.json:MixinScreen from mod inventoryprofilesnext should be final
[18:24:28] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder from mod sodium, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[18:24:28] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:24:29] [Render thread/INFO]: Setting user: Lurriiy
[18:24:29] [Render thread/INFO]: BetterPingDisplay mod loaded
[18:24:29] [Render thread/INFO]: [Big items, duh!] duh
[18:24:30] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:pufferfish_bucket is now minecraft:bucket.
[18:24:30] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:salmon_bucket is now minecraft:bucket.
[18:24:30] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:cod_bucket is now minecraft:bucket.
[18:24:30] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:tropical_fish_bucket is now minecraft:bucket.
[18:24:30] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:axolotl_bucket is now minecraft:bucket.
[18:24:30] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:powder_snow_bucket is now minecraft:bucket.
[18:24:30] [Render thread/INFO]: BYG registries bootstrapped
[18:24:30] [Render thread/ERROR]: No data fixer registered for byg:boat
[18:24:31] [Render thread/INFO]: Initializing BYG network...
[18:24:31] [Render thread/INFO]: Initialized BYG network!
[18:24:31] [Render thread/INFO]: Oh The Biomes You'll Go (BYG) was initialized from "Fabric Mod Initializer"
[18:24:31] [Render thread/INFO]: Successfully Debugify'd your game!
[18:24:31] [Render thread/INFO]: Proudly fixes 72 bugs!
[18:24:31] [Render thread/INFO]: DisguiseLib loaded.
[18:24:32] [Render thread/ERROR]: No data fixer registered for minecart_jukebox
[18:24:32] [Render thread/WARN]: Injection warning: LVT in net/minecraft/class_1059::method_18163(Lnet/minecraft/class_3300;Ljava/util/stream/Stream;Lnet/minecraft/class_3695;I)Lnet/minecraft/class_1059$class_4007; has incompatible changes at opcode 66 in callback better_loading_screen-common.mixins.json:MixinTextureAtlas from mod better_loading_screen->@Inject::prepareToStitchOptifine(Lnet/minecraft/class_3300;Ljava/util/stream/Stream;Lnet/minecraft/class_3695;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;ILjava/util/Set;)V.
 Expected: [I, Ljava/util/Set;]
    Found: [Ljava/util/Set;, I]
Available: [Ljava/util/Set;, I, Lnet/minecraft/class_1055;, I, I]
[18:24:32] [Render thread/WARN]: Injection warning: LVT in net/minecraft/class_1059::method_18163(Lnet/minecraft/class_3300;Ljava/util/stream/Stream;Lnet/minecraft/class_3695;I)Lnet/minecraft/class_1059$class_4007; has incompatible changes at opcode 236 in callback better_loading_screen-common.mixins.json:MixinTextureAtlas from mod better_loading_screen->@Inject::stitchOptifine(Lnet/minecraft/class_3300;Ljava/util/stream/Stream;Lnet/minecraft/class_3695;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;ILjava/util/Set;Ljava/util/Set;ILnet/minecraft/class_1055;)V.
 Expected: [I, Ljava/util/Set;, Ljava/util/Set;, I, Lnet/minecraft/class_1055;]
    Found: [Ljava/util/Set;, I, Lnet/minecraft/class_1055;, I]
Available: [Ljava/util/Set;, I, Lnet/minecraft/class_1055;, I]
[18:24:32] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=2 on IngameIME-fabric.mixins.json:MixinBookEditScreen from mod ingameime::handler$cbi000$onCaret_Book exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[18:24:32] [ForkJoinPool.commonPool-worker-1/ERROR]: Couldn't get latest version!
[18:24:33] [Render thread/INFO]: Start loading plugin from jade
[18:24:33] [Render thread/INFO]: Start loading plugin from jade
[18:24:33] [Render thread/INFO]: Start loading plugin from jade
[18:24:33] [Render thread/INFO]: Start loading plugin from lychee
[18:24:33] [Render thread/ERROR]: Error loading plugin at null
java.lang.NoClassDefFoundError: com/simibubi/create/content/logistics/trains/track/TrackTileEntity
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.10.jar:?]
	at snownee.jade.Jade.lambda$loadComplete$5(Jade.java:159) ~[Jade.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at snownee.jade.Jade.loadComplete(Jade.java:153) ~[Jade.jar:?]
	at snownee.jade.Jade.onInitialize(Jade.java:149) ~[Jade.jar:?]
	at net.minecraft.class_310.mdac4b01$lambda$init$1$4(class_310.java:4487) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.mdac4b01$lambda$invoke$5$0(class_310.java:4531) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.redirect$zga000$init(class_310.java:4499) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:452) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:197) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.10.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?]
Caused by: java.lang.ClassNotFoundException: com.simibubi.create.content.logistics.trains.track.TrackTileEntity
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 23 more
[18:24:33] [Render thread/INFO]: Start loading plugin from lychee
[18:24:33] [Render thread/INFO]: Start loading plugin from lychee
[18:24:33] [Render thread/ERROR]: Error loading plugin at null
java.lang.NoClassDefFoundError: com/github/spaceman/SolidAirBlock
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.10.jar:?]
	at snownee.jade.Jade.lambda$loadComplete$5(Jade.java:159) ~[Jade.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at snownee.jade.Jade.loadComplete(Jade.java:153) ~[Jade.jar:?]
	at snownee.jade.Jade.onInitialize(Jade.java:149) ~[Jade.jar:?]
	at net.minecraft.class_310.mdac4b01$lambda$init$1$4(class_310.java:4487) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.mdac4b01$lambda$invoke$5$0(class_310.java:4531) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.redirect$zga000$init(class_310.java:4499) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:452) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:197) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.10.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?]
Caused by: java.lang.ClassNotFoundException: com.github.spaceman.SolidAirBlock
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 23 more
[18:24:33] [Render thread/INFO]: [MidnightControls] Initializing MidnightControls...
[18:24:34] [Render thread/ERROR]: No data fixer registered for pollen:boat
[18:24:34] [Render thread/INFO]: Initializing RfnadditionMod


...


[18:25:14] [Render thread/INFO]: [STDOUT]: [Render thread INFO] ThreadDownloadImageData Class: net.minecraft.class_1046
[18:25:15] [Worker-Main-5/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[18:25:15] [Worker-Main-2/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[19:14:18] [Chunk Render Task Executor #5/ERROR]: Uncaught exception in thread "Chunk Render Task Executor #5"
java.lang.OutOfMemoryError: null
	at org.lwjgl.system.MemoryUtil.nmemReallocChecked(MemoryUtil.java:484) ~[lwjgl-3.2.2.jar:?]
	at org.lwjgl.system.MemoryUtil.memRealloc(MemoryUtil.java:517) ~[lwjgl-3.2.2.jar:?]
	at me.jellysquid.mods.sodium.client.model.vertex.buffer.VertexBufferBuilder.setBufferSize(VertexBufferBuilder.java:36) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.model.vertex.buffer.VertexBufferBuilder.grow(VertexBufferBuilder.java:32) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.model.vertex.buffer.VertexBufferBuilder.ensureBufferCapacity(VertexBufferBuilder.java:46) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.model.vertex.buffer.VertexBufferWriter.ensureCapacity(VertexBufferWriter.java:30) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderQuadList(BlockRenderer.java:97) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderModel(BlockRenderer.java:73) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.redirect$cbh000$onRenderBlock(ChunkRenderRebuildTask.java:550) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:99) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.processJob(ChunkBuilder.java:273) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:313) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Additional context

I also loaded lambdynlights 2.1.0+1.17 mod
only crash after update to iris 1.4.2 version

**Comment by 5ur3z** [comment]
[hs_err_pid5772.log](https://github.com/IrisShaders/Iris/files/10142150/hs_err_pid5772.log)
[latest.log](https://github.com/IrisShaders/Iris/files/10142151/latest.log)
