### ISSUE TITLE
Not entirely sure how to read and figure out why my game crahses everytime i try to turn on shaders. 

### ISSUE THREAD

**Issue by BadKarmaUHD** [IrisShaders/Iris#1780]
HERE IS THE CRASH REPORT

---- Minecraft Crash Report ----
// Sorry :(

Time: 2022-12-07 18:30:02
Description: Unexpected error

java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkShaderInterface failed
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShader(IrisChunkProgramOverrides.java:175)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShaders(IrisChunkProgramOverrides.java:224)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.getProgramOverride(IrisChunkProgramOverrides.java:253)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.handler$cio000$iris$begin(ShaderChunkRenderer.java:577)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:70)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:221)
	at net.minecraft.class_761.method_3251(class_761.java:15372)
	at net.minecraft.class_761.invokeRenderChunkLayer(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:421)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:761)
	at net.minecraft.class_761.handler$cee000$iris$renderTerrainShadows(class_761.java:9367)
	at net.minecraft.class_761.method_22710(class_761.java:1240)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.redirect$bpi000$redirectRenderingWorld(class_757.java:3150)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkShaderInterface failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 24 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 28 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [imm_ptl_compat.mixins.json:MixinIrisSodiumChunkShaderInterface from mod imm_ptl_core] from phase [DEFAULT] in config [imm_ptl_compat.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 31 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on imm_ptl_compat.mixins.json:MixinIrisSodiumChunkShaderInterface from mod imm_ptl_core->@Inject::onInit(ILnet/coderbot/iris/compat/sodium/impl/shader_overrides/ShaderBindingContextExt;Lnet/coderbot/iris/pipeline/SodiumTerrainPipeline;ZLnet/coderbot/iris/gl/blending/BlendModeOverride;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (ILnet/coderbot/iris/compat/sodium/impl/shader_overrides/ShaderBindingContextExt;Lnet/coderbot/iris/pipeline/SodiumTerrainPipeline;ZLnet/coderbot/iris/gl/blending/BlendModeOverride;Ljava/util/List;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (ILnet/coderbot/iris/compat/sodium/impl/shader_overrides/ShaderBindingContextExt;Lnet/coderbot/iris/pipeline/SodiumTerrainPipeline;ZLnet/coderbot/iris/gl/blending/BlendModeOverride;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [INJECT Applicator Phase -> imm_ptl_compat.mixins.json:MixinIrisSodiumChunkShaderInterface from mod imm_ptl_core -> Apply Injections ->  -> Inject -> imm_ptl_compat.mixins.json:MixinIrisSodiumChunkShaderInterface from mod imm_ptl_core->@Inject::onInit(ILnet/coderbot/iris/compat/sodium/impl/shader_overrides/ShaderBindingContextExt;Lnet/coderbot/iris/pipeline/SodiumTerrainPipeline;ZLnet/coderbot/iris/gl/blending/BlendModeOverride;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:567)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1378)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 31 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShader(IrisChunkProgramOverrides.java:175)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShaders(IrisChunkProgramOverrides.java:224)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.getProgramOverride(IrisChunkProgramOverrides.java:253)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.handler$cio000$iris$begin(ShaderChunkRenderer.java:577)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:70)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:221)
	at net.minecraft.class_761.method_3251(class_761.java:15372)
	at net.minecraft.class_761.invokeRenderChunkLayer(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:421)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:761)
	at net.minecraft.class_761.handler$cee000$iris$renderTerrainShadows(class_761.java:9367)
	at net.minecraft.class_761.method_22710(class_761.java:1240)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.redirect$bpi000$redirectRenderingWorld(class_757.java:3150)

-- Affected level --
Details:
	All players: 1 total; [class_746['BadKarmaUHD'/282, l='ClientWorld minecraft:overworld', x=36.25, y=63.00, z=7.96]]
	Chunk stats: Client Chunks (ImmPtl) 50
	Level dimension: minecraft:overworld
	Level spawn location: World: (-80,106,16), Section: (at 0,10,0 in -5,6,1; chunk contains blocks -80,-64,16 to -65,319,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 1489525 game time, 32693 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 23673890816 bytes (22577 MiB) / 28655484928 bytes (27328 MiB) up to 85899345920 bytes (81920 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon RX 6700 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x73df
	Graphics card #0 versionInfo: DriverVersion=31.0.12029.10015
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 32768.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 32768.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 93583.09
	Virtual memory used (MB): 48564.78
	Swap memory total (MB): 11776.00
	Swap memory used (MB): 75.19
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx80G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionaladditions: Additional Additions 5.1.0
			libgui: LibGui 6.0.0-beta.5+1.19-pre1
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		advancementplaques: Advancement Plaques 1.4.6
		architectury: Architectury 6.3.49
		bclib: BCLib 2.1.4
		bonezone: BoneZone 1.0.3
		bookshelf: Bookshelf 16.1.11
		celestial: Celestial 1.3.2
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		cloudboots: Cloud Boots 1.19.1-fabric-2.1.0
		creativecore: CreativeCore (Fabric) 2.9.3
		decorative_blocks: Decorative Blocks 3.0.0
		doomangelring: Doom Angel Ring 1.0.2
		drinkbeer: Drink Beer 3.2.2-1.19.2
		enderchests: EnderChests 1.1.0
		fabric-api: Fabric API 0.68.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.13+0d0f210290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.12+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.20+0d0f210290
			fabric-block-api-v1: Fabric Block API (v1) 1.0.1+12bfe4ea90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.22+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.3+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.13+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.9+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.30+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.38+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.3+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.3+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.7+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.2+ad31814d90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.33+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.2+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.31+6eb9a2a190
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.31+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.23+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.6.1+fa140d5990
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.35+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.23+aaaf9d3390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.21+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.2+9244241690
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.9+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.12+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.5+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.20+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.19+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.8+3b1d070f90
			fabric-networking-v0: Fabric Networking (v0) 0.3.25+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.2+06e0e25190
			fabric-particles-v1: Fabric Particles (v1) 1.0.12+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.29+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.1.0+e7aeff4590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.17+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.22+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.17+0d0f210290
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.9+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.25+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.1+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.1+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.1+0d0f210290
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.29+0d0f210290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.4+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.1+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.22+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.3+9d081d6490
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.2+42d99c3290
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabricloader: Fabric Loader 0.14.11
		forgeconfigapiport: Forge Config API Port 4.2.7
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		fpsdisplay: FPS-Display 1.5.0+1.19
		friendsandfoes: Friends&Foes 1.6.2
			com_github_llamalad7_mixinextras: MixinExtras 0.1.1
		ftblibrary: FTB Library 1902.3.10-build.156
		ftbultimine: FTB Ultimine 1902.3.5-build.65
		fwaystones: Fabric Waystones 3.0.5+mc1.19.2
		geckolib3: Geckolib 3.1.37
			com_eliotlash_mclib_mclib: mclib 20
		iceberg: Iceberg 1.0.46
		immersive_portals: Immersive Portals 2.2.3
			imm_ptl_core: Immersive Portals Core 2.2.3
			q_misc_util: QMiscUtil 2.2.3
		inventory_control_tweaks: Inventory Control Tweaks 1.3.19
			crowdin-translate: CrowdinTranslate 1.4+1.19
		iris: Iris 1.4.3
			io_github_douira_glsl-transformer: glsl-transformer 1.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.0beta1
			journeymap-api-fabric: JourneyMap API 1.19.1-1.9-fabric-SNAPSHOT
		malilib: MaLiLib 0.13.0
		mcwdoors: Macaw's Doors 1.0.7
		mcwlights: Macaw's Lights and Lamps 1.0.4
		mcwpaths: Macaw's Paths and Pavings 1.0.2
		mcwroofs: Macaw's Roofs 2.2.1
		mcwtrpdoors: Macaw's Trapdoors 1.0.7
		minecraft: Minecraft 1.19.2
		minihud: MiniHUD 0.23.3
		mob_catcher: Mob Catcher 1.2.15
		modmenu: Mod Menu 4.0.6
		morefrogs: More Frogs 1.19.x-1.2.3-fabric
		moretotems: More Totems 2.11.0
		owo: oωo 0.8.2+1.19
			blue_endless_jankson: jankson 1.2.1
		pickupnotifier: Pick Up Notifier 4.2.0
		probablychests: Probably Chests 0.5.5-1.19.2
		puzzleslib: Puzzles Lib 4.3.12
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		quarryplus: QuarryPlus 19.1.0
		roughlyenoughitems: Roughly Enough Items 9.1.577
			error_notifier: Error Notifier 1.0.9
		shetiphiancore: ShetiPhianCore 1.3.3
		simple_backpack: SimpleBackpack 1.3.25
		simplechunkloader: Simple Chunkloader 1.0.3
		simplyswords: Simply Swords 1.34-1.19.x
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		toms_storage: Tom's Simple Storage Mod 1.4.3
		trinkets: Trinkets 3.4.1
		weaponmaster: YDM's Weapon Master 3.0.0 
		wi_zoom: WI Zoom 1.4-MC1.19.2
		wolveswitharmor: Wolves With Armor 1.8.0-1.19
			maybe-data: Maybe data 1.3.2-1.19-rc2
			static-content: Static Content 1.0.1-1.16.2
				staticdata: Static Data 1.1.2
		wondrouswilds: Wondrous Wilds 1.19.2-1.1.5
		worldedit: WorldEdit 7.2.12+6240-87f4ae1
		yigd: You're in Grave Danger 1.4.6
	Loaded Shaderpack: ComplementaryShaders_v4.6 (1).zip
		Profile: HIGH (+9 options changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.11-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon RX 6700 XT GL version 3.2.0 Core Profile Context 22.11.2.221130, ATI Technologies Inc.
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['BadKarmaUHD'/282, l='ServerWorld minecraft:overworld OKay full mod list', x=36.25, y=63.00, z=7.96]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental

**Comment by coderbot16** [comment]
Your version of Immersive Portals is not compatible with the Iris version you are using. You will need to check for an update of Immersive Portals, and if there isn't one available, try going to the Immersive Portals discord for help.
