### ISSUE TITLE
Crash when load shaders

### ISSUE THREAD

**Issue by Liyze09** [IrisShaders/Iris#1816]
### Minecraft Version

Minecraft 1.19.3

### Iris Version

iris-mc1.19.3-1.5.0

### Sodium Version

sodium-fabric-mc1.19.3-0.4.7-build.21

### Operating System

macOS

### What is your GPU?

Apple M1

### Java Version

Java 19

### Reproduction Steps

1. Open a world.
2. Load a shaderpack.
3. Game Crashes.

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-01-01 16:40:00
Description: Unexpected error

java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkShaderInterface failed
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShader(IrisChunkProgramOverrides.java:175)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShaders(IrisChunkProgramOverrides.java:224)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.getProgramOverride(IrisChunkProgramOverrides.java:253)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.handler$ehe000$iris$begin(ShaderChunkRenderer.java:577)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:70)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:221)
	at net.minecraft.class_761.method_3251(class_761.java:15512)
	at net.minecraft.class_761.invokeRenderChunkLayer(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:428)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:808)
	at net.minecraft.class_761.handler$ecj000$iris$renderTerrainShadows(class_761.java:8009)
	at net.minecraft.class_761.method_22710(class_761.java:1234)
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.method_3192(class_757.java:864)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkShaderInterface failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 23 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 27 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [chunksfadein.mixins.json:iris.IrisChunkShaderInterfaceMixin from mod chunksfadein] from phase [DEFAULT] in config [chunksfadein.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 30 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on chunksfadein.mixins.json:iris.IrisChunkShaderInterfaceMixin from mod chunksfadein->@Inject::modifyConstructor(ILnet/coderbot/iris/compat/sodium/impl/shader_overrides/ShaderBindingContextExt;Lnet/coderbot/iris/pipeline/SodiumTerrainPipeline;ZLnet/coderbot/iris/gl/blending/BlendModeOverride;Ljava/util/List;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (ILnet/coderbot/iris/compat/sodium/impl/shader_overrides/ShaderBindingContextExt;Lnet/coderbot/iris/pipeline/SodiumTerrainPipeline;ZLnet/coderbot/iris/gl/blending/BlendModeOverride;Ljava/util/List;FLnet/coderbot/iris/uniforms/custom/CustomUniforms;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (ILnet/coderbot/iris/compat/sodium/impl/shader_overrides/ShaderBindingContextExt;Lnet/coderbot/iris/pipeline/SodiumTerrainPipeline;ZLnet/coderbot/iris/gl/blending/BlendModeOverride;Ljava/util/List;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [INJECT Applicator Phase -> chunksfadein.mixins.json:iris.IrisChunkShaderInterfaceMixin from mod chunksfadein -> Apply Injections ->  -> Inject -> chunksfadein.mixins.json:iris.IrisChunkShaderInterfaceMixin from mod chunksfadein->@Inject::modifyConstructor(ILnet/coderbot/iris/compat/sodium/impl/shader_overrides/ShaderBindingContextExt;Lnet/coderbot/iris/pipeline/SodiumTerrainPipeline;ZLnet/coderbot/iris/gl/blending/BlendModeOverride;Ljava/util/List;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:567)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1378)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 30 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShader(IrisChunkProgramOverrides.java:175)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShaders(IrisChunkProgramOverrides.java:224)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.getProgramOverride(IrisChunkProgramOverrides.java:253)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.handler$ehe000$iris$begin(ShaderChunkRenderer.java:577)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:70)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:221)
	at net.minecraft.class_761.method_3251(class_761.java:15512)
	at net.minecraft.class_761.invokeRenderChunkLayer(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:428)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:808)
	at net.minecraft.class_761.handler$ecj000$iris$renderTerrainShadows(class_761.java:8009)
	at net.minecraft.class_761.method_22710(class_761.java:1234)
	at net.minecraft.class_757.method_3188(class_757.java:1085)

-- Affected level --
Details:
	All players: 1 total; [class_746['Liyze'/13, l='ClientLevel', x=-2084.49, y=229.00, z=-1597.98]]
	Chunk stats: 4096, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,108,32), Section: (at 0,12,0 in 0,6,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 10939409 game time, 22594944 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2390)
	at net.minecraft.class_310.method_1514(class_310.java:805)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods, file/VanillaPlus, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Mac OS X (aarch64) version 13.1
	Java Version: 19, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 1315203248 bytes (1254 MiB) / 3221225472 bytes (3072 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Firestorm + Icestorm
	Frequency (GHz): 3.20
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 18432.00
	Virtual memory used (MB): 10788.38
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 744.06
	JVM Flags: 10 total; -Xmx6144m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.19.3-fabric0.68.1-1.3.1
		appleskin: AppleSkin 2.4.2+mc1.19.3
		badpackets: Bad Packets 0.3.4
		betterf3: BetterF3 5.1.0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.4+a91e48b785
		bobby: Bobby 4.0.3
			com_typesafe_config: config 1.4.2
			fabric-command-api-v2: Fabric Command API (v2) 2.1.15+49abcf7e72
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		capes: Capes 1.5.1+1.19.3
			omega-config: OmegaConfig 1.2.3-1.18.1
		carpet: Carpet Mod 1.4.93
		carpet-extra: Carpet Extra 1.4.91
		carpet-fixes: Carpet Fixes 1.19.3-1.13.0
		carpet-tis-addition: Carpet TIS Addition 1.44.0
			conditional-mixin: conditional mixin 0.3.2
		cem: Custom Entity Models 0.7.1
			completeconfig-base: completeconfig-base 2.2.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.2.0
		chat_heads: Chat Heads 0.8.1
		chunksfadein: Chunks Fade In 2.0.4-1.19.3
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cloth-config: Cloth Config v9 9.0.94
			cloth-basic-math: cloth-basic-math 0.6.1
		completeconfig: CompleteConfig 2.2.0
			coat: Coat 1.0.0-beta.19+mc22w44a
			completeconfig-gui-yacl: completeconfig-gui-yacl 2.2.0
		creativecore: CreativeCore (Fabric) 2.9.3
		debugify: Debugify 1.19.3+1.1
			com_github_llamalad7_mixinextras: mixinextras 0.1.1
		dynamicfps: Dynamic FPS 2.2.0
		easiervillagertrading: EasierVillagerTrading 1.19.3-fabric0.68.1-1.5.4
			gbfabrictools: GBfabrictools 1.3.4+1.19.3
		entity_texture_features: Entity Texture Features 4.3.0
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		fabric-api: Fabric API 0.69.1+1.19.3
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.18+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.0.0+689f5e7185
			fabric-block-api-v1: Fabric Block API (v1) 1.0.3+12bfe4ea85
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.28+c6af733c85
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.9+49abcf7e85
			fabric-command-api-v1: Fabric Command API (v1) 1.2.19+f71b366f85
			fabric-commands-v0: Fabric Commands (v0) 0.2.36+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.44+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.12+49abcf7e85
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.0+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.12+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.1.1+112a38be85
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.39+48349a3f85
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.5+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.37+422b77fb85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.39+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.28+2894d6df85
			fabric-item-api-v1: Fabric Item API (v1) 2.1.5+4d2c606385
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.8+d3d735d085
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.28+aaaf9d3385
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.26+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.8+2894d6df85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.18+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.22+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.12+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.29+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.25+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.14+d9ac3c3985
			fabric-networking-v0: Fabric Networking (v0) 0.3.31+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.2.0+e9dee00485
			fabric-particles-v1: Fabric Particles (v1) 1.0.18+fbde993d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.1+2608564685
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.1.0+2063beff85
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.23+11ba9c3b85
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.28+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.23+48349a3f85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.16+3067f46385
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.31+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.7+49abcf7e85
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.0+280be3ab85
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.39+1d4d0b5785
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.10+689f5e7185
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.6+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.12+82a2701785
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.1.0+0efcd39b85
		fabric-language-kotlin: Fabric Language Kotlin 1.9.0+kotlin.1.8.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.12
		fastload: Fast Load 2.6.10
		fastquit: FastQuit 1.2.2+1.19.3
		gca: GugleCarpetAddition 2.5.0-1.19
		held-item-info: Held Item Info 1.4.1
		ias: In-Game Account Switcher 8.0.1.1
		immediatelyfast: ImmediatelyFast 1.1.2
		inventoryhud: Inventory HUD + 3.4.7
		iris: Iris 1.5.0
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre8
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemphysiclite: ItemPhysic Lite (Fabric) 1.6.0
		itemscroller: Item Scroller 0.18.0
		java: OpenJDK 64-Bit Server VM 19
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdynlights: LambDynamicLights 2.2.0+1.19.3
			pride: Pride Lib 1.2.0+1.19.3
			spruceui: SpruceUI 4.1.0+1.19.3
		languagereload: Language Reload 1.5.1
		lazydfu: LazyDFU 0.1.3
		litematica: Litematica 0.13.1
		lithium: Lithium 0.10.4
		magiclib: MagicLib 0.6.194+3df5798-beta
			magiclib-1_19_3: MagicLib for 1.19.3 0.6.194+3df5798-beta
		malilib: MaLiLib 0.14.0
		masa_gadget_mod: Masa Gadget 3.0.0-beta+f5856ee
			masa_gadget_mod-1_19_3: Masa Gadget for 1.19.3 3.0.0-beta+f5856ee
		mcwifipnp: LAN World Plug-n-Play 1.6.3
		minecraft: Minecraft 1.19.3
		minihud: MiniHUD 0.25.0
		modelfix: Model Gap Fix 1.9
		modmenu: Mod Menu 5.0.2
		moreculling: More Culling 1.19.3-0.12.3
		morecullingextra: More Culling Extra 1.1
		nochatreports: No Chat Reports 1.19.3-v1.19.0
		ommc: Oh My Minecraft Client 0.5-beta+20ce4cc
			ommc-1_19_3: Oh My Minecraft Client for 1.19.3 0.5-beta+20ce4cc
		pca: Plusls carpet addition mod 0.2.5-beta+5fa8bc5
			multiconnect-api: MultiConnect API 1.5.10
		peek: Peek 1.19.3-1.0.3
		puzzle: Puzzle 1.4.2-1.19.3
			midnightlib: MidnightLib 1.1.0
			puzzle-base: Puzzle Base 1.4.2-1.19.3
			puzzle-gui: Puzzle GUI 1.4.2-1.19.3
			puzzle-models: Puzzle Models 1.4.2-1.19.3
			puzzle-splashscreen: Puzzle Splash Screen 1.4.2-1.19.3
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		replaymod: Replay Mod 1.19.3-2.6.10
		resolutioncontrol: ResolutionControl+ 1.19.3-3.0.0
		sodium: Sodium 0.4.7+build.21
			fabric-api-base: Fabric API Base 0.4.19+8d1895cf72
		sodium-extra: Sodium Extra 0.4.16+mc1.19.3-build.91
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		starlight: Starlight 1.1.1+fabric.ae22326
		subtitle-highlight: 字幕高亮 4_1.19.3
		syncmatica: Syncmatica 1.18.2-0.3.8
		technomodel: technomodel 1.0.3
		tweakermore: TweakerMore 3.9.2
		tweakeroo: Tweakeroo 0.15.0
		tweakmyclient: Tweak My Client 3.4.301+e882284-beta
			tweakmyclient-1_19_3: Tweak My Client for 1.19.3 3.4.301+e882284-beta
		waveycapes: WaveyCapes 1.2.2
		wthit: wthit 6.1.1
		xaero_map_addition: Xaero Map Addition 0.2.3-beta+43de4a4
			xaero_map_addition-1_19_3: Xaero Map Addition for 1.19.3 0.2.3-beta+43de4a4
		xaerominimap: Xaero's Minimap 22.17.0
		xaeroworldmap: Xaero's World Map 1.28.7
		yet-another-config-lib: YetAnotherConfigLib 2.2.0
		zoomify: Zoomify 2.9.2
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.3.0
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-gui: settxi-gui 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
			settxi-gui-yacl: Settxi Gui (YetAnotherConfigLib) 2.10.6
	Loaded Shaderpack: §r§lAstra§4§lLex§r§l_(§4§lBSL§r§l_Edit)_By_LexBoosT_§4§lV69.1§r§l.zip
		Profile: Custom (+20 options changed by user)
	NEC status: No NEC detected
	Launched Version: 1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Apple M1 GL version 4.1 Metal - 83, Apple
	Window size: 1680x1050
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	GPU Warnings: version: Metal
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/VanillaPlus
	Current Language: 简体中文 (中国大陆)
	CPU: 8x Apple M1
	Server Running: true
	Player Count: 1 / 8; [class_3222['Liyze'/13, l='ServerLevel[LRS]', x=-2084.49, y=229.00, z=-1597.98]]
	Data Packs: vanilla, file/graves v2.8.6.zip, file/more mob heads v2.10.1.zip, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
```

### Additional context

All the shaderpacks  have crashes.

**Comment by Lolothepro** [comment]
Seems to be caused by chunksfadein

**Comment by Liyze09** [comment]
That is OK.I will open a issue for chunks fade in.
