### ISSUE TITLE
Crash on mc1.18.2 when using shaders

### ISSUE THREAD

**Issue by 5ur3z** [IrisShaders/Iris#1828]
### Minecraft Version

1.18.2

### Iris Version

1.4.0

### Sodium Version

0.4.1+replaymod.rev.23e83a1

### Operating System

Windows10

### What is your GPU?

Nvidia Geforce RTX 3060 Laptop GPU

### Java Version

openjdk17

### Reproduction Steps

1. join a multi server
2. turn on shaders
3. Game Crashes
（I didn't upgrade the iris because I can't let players to downgrade there NVIDIA bad drivers）
（when upgrade to iris 1.4.2，some players will crash with memory crash

### Crash Report file and latest.log

```shell
20:22:11] [Render thread/INFO]: Stopping worker threads
[20:22:11] [Render thread/INFO]: Started 10 worker threads
[20:22:11] [Render thread/INFO]: Stopping worker threads
[20:22:11] [Render thread/INFO]: Started 10 worker threads
[20:22:11] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:22:11] [Render thread/WARN]: Received passengers for unknown entity
[20:22:11] [Render thread/WARN]: Received passengers for unknown entity
[20:22:11] [Render thread/WARN]: Removing unused function CheckForColor and omitting further such messages outside of debug mode. See debugging.md for more information.
[20:22:11] [Render thread/WARN]: Removing unused function stylisedGGX and omitting further such messages outside of debug mode. See debugging.md for more information.
[20:22:11] [Render thread/WARN]: Removing unused function stylisedGGX and omitting further such messages outside of debug mode. See debugging.md for more information.
[20:22:11] [Render thread/WARN]: Removing unused function WavingBlocks and omitting further such messages outside of debug mode. See debugging.md for more information.
[20:22:11] [Render thread/WARN]: Removing unused function stylisedGGX and omitting further such messages outside of debug mode. See debugging.md for more information.
[20:22:13] [Worker-Main-15/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[20:22:36] [Render thread/INFO]: [STDERR]: java.lang.RuntimeException
[20:22:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.redirect$zeo000$defaultErrorCallback(class_1041.java:589)
[20:22:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_4482(class_1041.java:222)
[20:22:36] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
[20:22:36] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokePI(Native Method)
[20:22:36] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwGetMouseButton(GLFW.java:3435)
[20:22:36] [Render thread/INFO]: [STDERR]: 	at fi.dy.masa.malilib.hotkeys.KeybindMulti.isKeyDown(KeybindMulti.java:430)
[20:22:36] [Render thread/INFO]: [STDERR]: 	at fi.dy.masa.malilib.hotkeys.KeybindMulti.reCheckPressedKeys(KeybindMulti.java:474)
[20:22:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.handler$ddh000$onPostKeyboardInput(class_310.java:20467)
[20:22:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1574(class_310.java:1817)
[20:22:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1091)
[20:22:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:737)
[20:22:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:236)
[20:22:36] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[20:22:36] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[20:22:36] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[20:22:36] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:22:36] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[20:22:36] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:22:36] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[20:22:36] [Render thread/INFO]: [STDERR]: 	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
[20:22:36] [Render thread/INFO]: [STDERR]: 	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
[20:22:36] [Render thread/ERROR]: ########## GL ERROR ##########
[20:22:36] [Render thread/ERROR]: @ Pre render
[20:22:36] [Render thread/ERROR]: 65539: Invalid mouse button 99
[20:22:36] [Render thread/INFO]: [CHAT] <YunzhuoH> 我来帮忙，挖到讷尔？
[20:22:53] [Render thread/INFO]: [CHAT] <Lurriiy> 你们看不到
[20:23:53] [Render thread/INFO]: [CHAT] <NeverCIKE> 准确的说）
[20:24:11] [Render thread/INFO]: [STDERR]: java.lang.RuntimeException
[20:24:11] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.redirect$zeo000$defaultErrorCallback(class_1041.java:589)
[20:24:11] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_4482(class_1041.java:222)
[20:24:11] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
[20:24:11] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokePI(Native Method)
[20:24:11] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwGetMouseButton(GLFW.java:3435)
[20:24:11] [Render thread/INFO]: [STDERR]: 	at fi.dy.masa.malilib.hotkeys.KeybindMulti.isKeyDown(KeybindMulti.java:430)
[20:24:11] [Render thread/INFO]: [STDERR]: 	at fi.dy.masa.malilib.hotkeys.KeybindMulti.reCheckPressedKeys(KeybindMulti.java:474)
[20:24:11] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.handler$ddh000$onPostKeyboardInput(class_310.java:20467)
[20:24:11] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1574(class_310.java:1817)
[20:24:11] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1091)
[20:24:11] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:737)
[20:24:11] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:236)
[20:24:11] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[20:24:11] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[20:24:11] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[20:24:11] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:24:11] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[20:24:11] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:24:11] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[20:24:11] [Render thread/INFO]: [STDERR]: 	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
[20:24:11] [Render thread/INFO]: [STDERR]: 	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
[20:24:11] [Render thread/ERROR]: ########## GL ERROR ##########
[20:24:11] [Render thread/ERROR]: @ Pre render
[20:24:11] [Render thread/ERROR]: 65539: Invalid mouse button 99
[20:24:11] [Render thread/INFO]: [CHAT] <YunzhuoH> 嗯？
[20:24:12] [Render thread/INFO]: [CHAT] <NeverCIKE> 这里应该离主城有很远的路）
[20:24:17] [Render thread/WARN]: Received passengers for unknown entity
[20:24:22] [Render thread/INFO]: [CHAT] <NeverCIKE> 等公共点会比较节约时间）
[20:25:14] [Render thread/WARN]: Received passengers for unknown entity
[20:25:45] [Render thread/INFO]: Loading slotlock file
[20:25:45] [Render thread/INFO]: Successfully loaded slotlock file
[20:25:45] [Render thread/INFO]: Reloading pipeline on dimension change: NETHER => OVERWORLD
[20:25:45] [Render thread/INFO]: Destroying pipeline NETHER
[20:25:45] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[20:25:45] [Render thread/INFO]: Stopping worker threads
[20:25:45] [Render thread/INFO]: Started 10 worker threads
[20:25:45] [Render thread/INFO]: Stopping worker threads
[20:25:45] [Render thread/INFO]: Started 10 worker threads
[20:25:45] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
```

**Comment by 5ur3z** [comment]
[latest.log](https://github.com/IrisShaders/Iris/files/10344227/latest.log)
[hs_err_pid22364.log](https://github.com/IrisShaders/Iris/files/10344228/hs_err_pid22364.log)

**Comment by coderbot16** [comment]
If the issue still occurs with those latest versions, please either reply to this issue so that it can be reopened or open a new issue.

**Comment by 5ur3z** [comment]
I didn't see any Sodium update for Minecraft 1.18.2，it crash still when I update to iris 1.5，last sodium update is before 10 months

**Comment by coderbot16** [comment]
Ah, right, no workaround is available for 1.18.x. You have no choice but to downgrade your drivers until the issue is fixed, even when using older versions of Iris and Sodium.

**Comment by 5ur3z** [comment]
> Ah, right, no workaround is available for 1.18.x. You have no choice but to downgrade your drivers until the issue is fixed, even when using older versions of Iris and Sodium.

I've upgrade my server and client to 1.19.2, it crash still..

**Comment by Lolothepro** [comment]
1.19.3...

**Comment by 5ur3z** [comment]
> 1.19.3..., use 1.19.3...

porting to 1.19.2 please....
I've just upgrade my server to 1.19.2, it's such a big job.... But players told me that it still crashes...
