### ISSUE TITLE
Kappa shaders dont work in End/Nether

### ISSUE THREAD

**Issue by Cr4zyy** [IrisShaders/Iris#1832]
### What happened?

Using iris 1.5 on MC 1.18.2, All of Fabric 5 2.0.6
Kappa Shader v5.0a

The Shader works perfectly fine in Overworld, but loading into Nether or The End produces this error.

`[02:17:10] [Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders! java.lang.IllegalStateException: Pass sizes must match for drawbuffers [0, 5] Original width: 3440 New width: 256 Original height: 1440 New height: 384 
	at net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:127) ~[iris-mc1.18.2-1.5.0.jar:?] 
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:261) ~[iris-mc1.18.2-1.5.0.jar:?] 	at net.coderbot.iris.Iris.createPipeline(Iris.java:653) ~[iris-mc1.18.2-1.5.0.jar:?] 
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) ~[iris-mc1.18.2-1.5.0.jar:?] 
	at net.minecraft.class_310.handler$fnp000$iris$resetPipeline(class_310.java:26990) ~[client-intermediary.jar:?] 
	at net.minecraft.class_310.method_18097(class_310.java) ~[client-intermediary.jar:?] 
	at net.minecraft.class_310.method_1481(class_310.java:2144) ~[client-intermediary.jar:?] 
	at net.minecraft.class_634.method_11117(class_634.java:940) ~[client-intermediary.jar:?] 
	at net.minecraft.class_2724.method_11782(class_2724.java:62) ~[client-intermediary.jar:?] 
	at net.minecraft.class_2724.method_11054(class_2724.java:15) ~[client-intermediary.jar:?] 
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?] 
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?] 
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?] 
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?] 
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?] 
	at net.minecraft.class_310.method_1523(class_310.java:1085) [client-intermediary.jar:?] 
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?] 
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?] 
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?] 
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?] 
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.10.jar:?] 
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] 
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] 
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] 
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] 
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?] 
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?] 
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?] 
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?] 
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
[02:17:10] [Render thread/INFO]: Stopping worker threads
 [02:17:10] [Render thread/INFO]: Started 10 worker threads
 [02:17:10] [Render thread/INFO]: Stopping worker threads 
[02:17:10] [Render thread/INFO]: Started 10 worker threads
 [02:17:10] [Render thread/INFO]: Stopping worker threads
 [02:17:10] [Render thread/INFO]: Started 10 worker threads`

Other shaders ive tested dont seem to have this issue. Complimentary, Ushader are fine, where as Kappa results in shader being disabled.

### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.5.0.jar

### Operating System

Windows 11

### What is your GPU?

nVidia RTX 3080

**Comment by Lolothepro** [comment]
it's a shaders bug, not Iris

**Comment by Timolino456** [comment]
On the Kappa Discord server there's a 5.0b build in the testing channel, you'd have to use that one for it to work
