### ISSUE TITLE
Crashing when loading into worlds with shaders on

### ISSUE THREAD

**Issue by keola-source** [IrisShaders/Iris#1844]
### Minecraft Version

1.19.2

### Iris Version

iris-mc1.19.2-1.5.0.jar

### Sodium Version

sodium-fabric-mc1.19.2-0.4.4+build.18.jar

### Operating System

Windows 11

### What is your GPU?

Nvidia Geforce RTX 3050 Mobile

### Java Version

Java 17

### Reproduction Steps

1. Load into a world
2. Turning on shaders either by key press or the shader menu
3. Game Crashes

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-01-14 20:16:03
Description: Unexpected error

java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkShaderInterface failed
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShader(IrisChunkProgramOverrides.java:175)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShaders(IrisChunkProgramOverrides.java:224)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.getProgramOverride(IrisChunkProgramOverrides.java:253)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.handler$cjc000$iris$begin(ShaderChunkRenderer.java:577)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:70)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:221)
	at net.minecraft.class_761.method_3251(class_761.java:17300)
	at net.minecraft.class_761.invokeRenderChunkLayer(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:431)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:801)
	at net.minecraft.class_761.handler$cei000$iris$renderTerrainShadows(class_761.java:11297)
	at net.minecraft.class_761.method_22710(class_761.java:1234)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.redirect$bpj000$redirectRenderingWorld(class_757.java:4154)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.RuntimeException: Mixin transformation of net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkShaderInterface failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 27 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 31 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [imm_ptl_compat.mixins.json:MixinIrisSodiumChunkShaderInterface from mod imm_ptl_core] from phase [DEFAULT] in config [imm_ptl_compat.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 34 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on imm_ptl_compat.mixins.json:MixinIrisSodiumChunkShaderInterface from mod imm_ptl_core->@Inject::onInit(ILnet/coderbot/iris/compat/sodium/impl/shader_overrides/ShaderBindingContextExt;Lnet/coderbot/iris/pipeline/SodiumTerrainPipeline;ZLnet/coderbot/iris/gl/blending/BlendModeOverride;Ljava/util/List;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (ILnet/coderbot/iris/compat/sodium/impl/shader_overrides/ShaderBindingContextExt;Lnet/coderbot/iris/pipeline/SodiumTerrainPipeline;ZLnet/coderbot/iris/gl/blending/BlendModeOverride;Ljava/util/List;FLnet/coderbot/iris/uniforms/custom/CustomUniforms;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (ILnet/coderbot/iris/compat/sodium/impl/shader_overrides/ShaderBindingContextExt;Lnet/coderbot/iris/pipeline/SodiumTerrainPipeline;ZLnet/coderbot/iris/gl/blending/BlendModeOverride;Ljava/util/List;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [INJECT Applicator Phase -> imm_ptl_compat.mixins.json:MixinIrisSodiumChunkShaderInterface from mod imm_ptl_core -> Apply Injections ->  -> Inject -> imm_ptl_compat.mixins.json:MixinIrisSodiumChunkShaderInterface from mod imm_ptl_core->@Inject::onInit(ILnet/coderbot/iris/compat/sodium/impl/shader_overrides/ShaderBindingContextExt;Lnet/coderbot/iris/pipeline/SodiumTerrainPipeline;ZLnet/coderbot/iris/gl/blending/BlendModeOverride;Ljava/util/List;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:567)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1378)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 34 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShader(IrisChunkProgramOverrides.java:175)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShaders(IrisChunkProgramOverrides.java:224)
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.getProgramOverride(IrisChunkProgramOverrides.java:253)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.handler$cjc000$iris$begin(ShaderChunkRenderer.java:577)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:70)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:221)
	at net.minecraft.class_761.method_3251(class_761.java:17300)
	at net.minecraft.class_761.invokeRenderChunkLayer(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:431)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:801)
	at net.minecraft.class_761.handler$cei000$iris$renderTerrainShadows(class_761.java:11297)
	at net.minecraft.class_761.method_22710(class_761.java:1234)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.redirect$bpj000$redirectRenderingWorld(class_757.java:4154)

-- Affected level --
Details:
	All players: 1 total; [class_746['KeolaAG'/62, l='ClientWorld minecraft:overworld', x=86.93, y=-60.00, z=-52.85]]
	Chunk stats: Client Chunks (ImmPtl) 1070
	Level dimension: minecraft:overworld
	Level spawn location: World: (-1,-60,0), Section: (at 15,4,0 in -1,-4,0; chunk contains blocks -16,-64,0 to -1,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 1988530 game time, 1019198 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, black_icons, continuity/default, continuity/glass_pane_culling_fix, lambdabettergrass/default, minecraft/supporteatinganimation, VanillaTweaks_r125662.zip, replaymod_lang, Essential (fabric_1.19.2).jar

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.5, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 761459880 bytes (726 MiB) / 2296381440 bytes (2190 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.69
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3050 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x25a2
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2802
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9a68
	Graphics card #1 versionInfo: DriverVersion=30.0.101.2079
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 20568.30
	Virtual memory used (MB): 18363.78
	Swap memory total (MB): 12738.33
	Swap memory used (MB): 1690.13
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx4096m
	Fabric Mods: 
		animatica: Animatica 0.5+1.19
		antighost: AntiGhost 1.19.1-fabric0.58.5-1.1.5
			crowdin-translate: CrowdinTranslate 1.4+1.19
		architectury: Architectury 6.4.62
		auditory: Auditory 0.0.4-1.19.x
		badpackets: Bad Packets 0.2.1
		betterbiomeblend: Better Biome Blend 1.19-1.3.6-fabric
		betterf3: BetterF3 4.0.0
		blur: Blur (Fabric) 2.6.0
			satin: Satin 1.8.0
		borderlessmining: Borderless Mining 1.1.5+1.19
		camerautils: Camera Utils 1.19.2-1.0.3
		capes: Capes 1.4.5+1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		chat_heads: Chat Heads 0.9.0
		chunksfadein: Chunks Fade In 3.0.7-1.19
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 2.0.1+1.19
		craftify: Craftify 1.6.0
			elementa: Elementa 559+pull-97
			universalcraft: UniversalCraft 251
			vigilance: Vigilance 273+pull-75
		cullleaves: Cull Leaves 3.0.1
			midnightlib: MidnightLib 1.0.0
		dark-loading-screen: Dark Loading Screen 1.6.12
		debugify: Debugify 2.8.0
			com_github_llamalad7_mixinextras: mixinextras 0.1.0
		detailab: Detail Armor Bar 2.6.2+1.19-fabric
		draggable-resource-packs: Draggable Resource Packs 3.0.1+build.9
		dynamiccrosshair: Dynamic Crosshair 5.0+1.19.2
		dynamicfps: Dynamic FPS 2.2.0
		eatinganimationid: Eating Animation 1.9
		effective: Effective 1.4
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.4+1.19
		enhancedblockentities: Enhanced Block Entities 0.7.2+1.19.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
		entity_texture_features: Entity Texture Features 4.3.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		essential: Essential 11642+deploy-staging+g7f637cfee
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.0.0
		extrasounds: ExtraSounds 2.3.1+1.19.2-1.19.1
			soundcategories: Sound Categories 1.2.4+1.19
		fabric-api: Fabric API 0.72.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.14+6e0787e690
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.13+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.23+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.4+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.15+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.0+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.32+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.40+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.6+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.34+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.3+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.33+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.33+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.3+9785ec3590
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.37+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.3+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.11+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.14+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.6+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.22+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.20+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.10+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.27+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.5+9785ec3590
			fabric-particles-v1: Fabric Particles (v1) 1.0.13+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.0+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.31+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.0+2e5408b590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.0+2e5408b590
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.23+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.18+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.10+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.26+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+08b73de490
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.31+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.6+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.23+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.5+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.9.0+kotlin.1.8.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.11
		fabricskyboxes: FabricSkyBoxes 0.6.1+mc1.19.2
		ferritecore: FerriteCore 5.0.3
		grindenchantments: Grind Enchantments 2.0.0-beta.2+1.19.2
		immersive_portals: Immersive Portals 2.3.1
			imm_ptl_core: Immersive Portals Core 2.3.1
			q_misc_util: QMiscUtil 2.3.1
		indium: Indium 1.0.9+mc1.19.2
		inventorytabs: Inventory Tabs 0.9.beta-1.19.x
		iris: Iris 1.5.0
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre8
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: Java HotSpot(TM) 64-Bit Server VM 17
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
		lambdynlights: LambDynamicLights 2.2.0+1.19.2
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.1.0+1.19.2
		lazydfu: LazyDFU 0.1.3
		lightoverlay: Light Overlay 7.0.0
		lithium: Lithium 0.10.4
		megane: megane 8.3.0
			megane-api: megane-api 8.3.0
			megane-fabric-transfer: megane-fabric-transfer 8.3.0
			megane-runtime: megane-runtime 8.3.0
			megane-vanilla: megane-vanilla 8.3.0
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.1.2
		mousetweaks: Mouse Tweaks 2.22
		mousewheelie: Mouse Wheelie 1.10.7+mc1.19.2
			amecsapi: Amecs API 1.3.7+mc22w17a
			coat: Coat 1.0.0-beta.19+mc22w17a
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.7.1+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.3+mc22w17a
		nochatreports: No Chat Reports 1.19.2-v1.13.12
		notenoughanimations: NotEnoughAnimations 1.6.2
		optigui: OptiGUI 1.1.6
			org_apache_commons_commons-text: commons-text 1.9
		org_jetbrains_annotations: annotations 13.0
		pehkui: Pehkui 3.6.3+1.14.4-1.19.3
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		phosphor: Phosphor 0.8.1
		presencefootsteps: Presence Footsteps 1.6.4
			kirin: Kirin UI 1.11.1
		raised: Raised 1.1.4
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		replaymod: Replay Mod 1.19.2-2.6.10
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.1
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.16+mc1.19.2-build.90
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.0.18
		spark: spark 1.10.17
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		technomodel: technomodel 1.0.3
		visuality: Visuality 0.5.5
		voicechat: Simple Voice Chat 1.19.2-2.3.26
		worldedit: WorldEdit 7.2.12+6240-87f4ae1
		wthit: wthit 5.13.4
		yet-another-config-lib: YetAnotherConfigLib 1.7.1
	Loaded Shaderpack: ComplementaryReimagined_r1.1.1.zip
		Profile: Custom (+8 options changed by user)
	NEC status: No NEC detected
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 528.02, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, black_icons, continuity/default, continuity/glass_pane_culling_fix, lambdabettergrass/default, minecraft/supporteatinganimation, file/VanillaTweaks_r125662.zip
	Current Language: English (US)
	CPU: 12x 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['KeolaAG'/62, l='ServerWorld minecraft:overworld Test World', x=86.93, y=-60.00, z=-52.85]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
```

**Comment by IMS212** [comment]
Immersive Portals on 1.19.2 isn't compatible with Iris 1.5, you'll need to update to 1.19.3 or remove Immersive Portals.
