### ISSUE TITLE
Shader compilation failed

### ISSUE THREAD

**Issue by SuSsyGuyYT** [IrisShaders/Iris#1898]
### Minecraft Version

Minecraft 1.19 (Fabric)

### Iris Version

iris-mc1.19.2-1.5.2.jar

### Sodium Version

sodium-fabric-mc1.19.2-0.4.4+build.18.jar

### Operating System

Windows 11

### What is your GPU?

NVIDIA GeForce RTX 3060 Laptop GPU

### Java Version

Java 17

### Reproduction Steps

1. Place a Redstone Lamp in front of a Redstone Repeater
2. Use a Lever to activate the Redstone Repeater
3. Game Crashes

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2/20/23, 10:24 PM
Description: Unexpected error

java.lang.RuntimeException: Shader compilation failed, see log for details
	at me.jellysquid.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:34)
	at me.jellysquid.mods.sodium.client.gl.shader.ShaderLoader.loadShader(ShaderLoader.java:534)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.redirect$bmj000$iris$redirectOriginalShader(ShaderChunkRenderer.java:571)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.createShader(ShaderChunkRenderer.java:47)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.compileProgram(ShaderChunkRenderer.java:38)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java:72)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:70)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:221)
	at net.minecraft.class_761.method_3251(class_761.java:14806)
	at net.minecraft.class_761.method_22710(class_761.java:1245)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.redirect$bcl000$redirectRenderingWorld(class_757.java:2650)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:34)
	at me.jellysquid.mods.sodium.client.gl.shader.ShaderLoader.loadShader(ShaderLoader.java:534)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.redirect$bmj000$iris$redirectOriginalShader(ShaderChunkRenderer.java:571)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.createShader(ShaderChunkRenderer.java:47)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.compileProgram(ShaderChunkRenderer.java:38)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java:72)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:70)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:221)
	at net.minecraft.class_761.method_3251(class_761.java:14806)
	at net.minecraft.class_761.method_22710(class_761.java:1245)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.redirect$bcl000$redirectRenderingWorld(class_757.java:2650)

-- Affected level --
Details:
	All players: 1 total; [class_746['SuSsyGuy_YT'/177, l='ClientWorld minecraft:overworld', x=-424.50, y=64.00, z=58.50]]
	Chunk stats: Client Chunks (ImmPtl) 295
	Level dimension: minecraft:overworld
	Level spawn location: World: (-432,66,64), Section: (at 0,2,0 in -27,4,4; chunk contains blocks -432,-64,64 to -417,319,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 614 game time, 614 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:758)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, black_icons, lambdabettergrass/default, Darkmode-Minecraft-MOD_SUPPORT-v2.4.0.zip, Stay_True_1.19.zip, FreshAnimations_v1.8.zip, Stay True Compats v7 [1.19].zip, NoCaveAmbience 1.19.zip, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 588568520 bytes (561 MiB) / 3110076416 bytes (2966 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 3.29
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2560
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1236
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 26476.06
	Virtual memory used (MB): 18402.31
	Swap memory total (MB): 10240.00
	Swap memory used (MB): 100.07
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		ambientsounds: Ambient Sounds (Fabric) 5.2.13
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 5.14.68
		betterf3: BetterF3 4.0.0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.6.1+aeb40ebe90
		bookshelf: Bookshelf 14.2.10
		chat_heads: Chat Heads 0.6.0
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+7
		continuity: Continuity 2.0.1+1.19
		controlling: Controlling For Fabric 10.0+3
		creativecore: CreativeCore (Fabric) 2.8.5
		darkpaintings: DarkPaintings 11.1.3
		fabric: Fabric API 0.58.0+1.19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.28+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.2+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c43a9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.1.0+442de8b8a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.15+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.18+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.10+5187d39fa9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.7+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.9.1+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.19.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.10
		fallingtree: FallingTree 3.7.4
		forgeconfigapiport: Forge Config API Port 4.2.11
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		frame: Frame 0.26.1+1.19-fabric
			frame-api-base: Frame Base 0.2.1+906ebc04a9
			frame-blocks-v0: Frame Blocks (v0) 0.1.3+233e7428a9
			frame-config-v0: Frame Config (v0) 0.3.1+0fa45150a9
			frame-content-registries-v0: Frame Content Registries (v0) 0.4.0+2876b511a9
			frame-enchantments-v0: Frame Enchantments (v0) 0.1.0+4093105da9
				mm: Manningham Mills 2.3
			frame-game-rules-v0: Frame Game Rules (v0) 0.2.4+e7ce56a6a9
			frame-items-v0: Frame Items (v0) 0.1.3+906ebc04a9
			frame-loot-tables-v0: Frame Loot Tables (v0) 0.1.4+4f7341eca9
			frame-registries-v0: Frame Registries (v0) 0.1.1+0e0ec74ea9
			frame-rendering-v0: Frame Rendering (v0) 0.1.5+906ebc04a9
			frame-tabbed-item-groups-v0: Frame Tabbed Item Groups (v0) 0.2.4+0aca9b56a9
			frame-toymaker-v0: Frame Data Generation Helpers (v0) 0.6.1+b13741c3a9
			frame-woods-v0: Frame Woods (v0) 0.2.1+6a33fbada9
		geckolib3: Geckolib 3.1.6
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		immersive_paintings: Immersive Paintings 0.2.0+1.19
		immersive_portals: Immersive Portals 2.0.5
			imm_ptl_core: Immersive Portals Core 2.0.5
			q_misc_util: QMiscUtil 2.0.5
		immersiveportalscrafting: Immersive-portals-crafting 1.0.0
		inventoryprofilesnext: Inventory Profiles Next 1.9.2
		iris: Iris 1.5.2
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.20+aeb40ebe90
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre9
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jameswebbpainting: James Webb's Paintings! 0.0.4-1.19
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.1.1.239
		jeresources: Just Enough Resources 1.0.0.176
		journeymap: Journeymap 5.8.5
			journeymap-api-fabric: JourneyMap API 1.19-1.8-fabric-SNAPSHOT
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
			spruceui: SpruceUI 4.0.0+1.19
		libipn: libIPN 2.0.2
		litematica: Litematica 0.12.1
		malilib: MaLiLib 0.13.0
		mcwpaintings: Macaw's Paintings 1.0.4
		minecraft: Minecraft 1.19
		modmenu: Mod Menu 4.0.4
		mousetweaks: Mouse Tweaks 2.22
		naturescompass: Nature's Compass 1.19-2.0.4-fabric
		oneblockrandomdrop: OneBlockRandomDrop 1.1.0
		paintings: Paintings++ 10.0.0.0
		pehkui: Pehkui 3.6.0+1.14.4-1.19.3
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		puzzleslib: Puzzles Lib 4.0.18
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		replaymod: Replay Mod 1.19-2.6.8
		sdrp: Simple Discord Rich Presence 2.0.1-build.16+mc1.19
		simple-rpc: Simple RPC 3.2.1
			me_hypherionmc_simplerpc_simple-rpc-common: simple-rpc-common 4.2.10
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.1
		sodium: Sodium 0.4.4+build.18
			fabric-api-base: Fabric API Base 0.4.11+e62f51a390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.14+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.7+aeb40ebe90
			org_joml_joml: joml 1.10.4
		terraria_paintings: terraria paintings 2.0.0
		transparent: Transparent 5.1.2
		twigs: Twigs 2.0.0-beta.9+1.19-fabric
		visualworkbench: Visual Workbench 4.0.0
		voicechat: Simple Voice Chat 1.19-2.3.28
		wi_zoom: WI Zoom 1.4-MC1.19
		worldedit: WorldEdit 7.2.11-beta-02+315c5d0
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.10-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 512.36, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, black_icons, lambdabettergrass/default, file/Darkmode-Minecraft-MOD_SUPPORT-v2.4.0.zip (incompatible), file/Stay_True_1.19.zip, file/FreshAnimations_v1.8.zip, file/Stay True Compats v7 [1.19].zip, file/NoCaveAmbience 1.19.zip
	Current Language: Deutsch (Deutschland)
	CPU: 12x AMD Ryzen 5 5600H with Radeon Graphics 
	Server Running: true
	Player Count: 1 / 8; [class_3222['SuSsyGuy_YT'/177, l='ServerWorld minecraft:overworld Minecraft Dorf', x=-424.50, y=64.00, z=58.50]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
```

### Additional context

It comes when i join a World,
Here is my Mod List:

3dskinlayers-fabric-1.5.2-mc1.19.1.jar
AmbientSounds_FABRIC_v5.2.13_mc1.19.2.jar
appleskin-fabric-mc1.19-2.4.1.jar
architectury-5.14.68-fabric.jar
BetterF3-4.0.0-Fabric-1.19.2.jar
Bookshelf-Fabric-1.19-14.2.10.jar
chat_heads-0.6.0-fabric-1.19.jar
cloth-config-8.2.88-fabric.jar
Clumps-fabric-1.19-9.0.0+7.jar
continuity-2.0.1+1.19.jar
Controlling-fabric-1.19-10.0+3.jar
CreativeCore_FABRIC_v2.8.5_mc1.19.2.jar
DarkPaintings-Fabric-1.19-11.1.3.jar
fabric-api-0.58.0+1.19.jar
fabric-language-kotlin-1.9.1+kotlin.1.8.10.jar
FallingTree-1.19-3.7.4.jar
ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric.jar
frame-0.26.1+1.19-fabric.jar
geckolib-fabric-1.19-3.1.6.jar
immersive_paintings-0.2.0+1.19.jar
immersive-portals-2.0.5-mc1.19-fabric.jar
immersive-portals-crafting.jar
InventoryProfilesNext-fabric-1.19-1.9.2.jar
iris-mc1.19.2-1.5.2.jar
jameswebbpainting-0.0.4-1.19.jar
jei-1.19-fabric-11.1.1.239.jar
journeymap-1.19-5.8.5-fabric.jar
JustEnoughResources-Fabric-1.19-1.0.0.176.jar
lambdabettergrass-1.3.0+1.19.jar
libIPN-fabric-1.19-2.0.2.jar
litematica-fabric-1.19.0-0.12.1.jar
malilib-fabric-1.19.0-0.13.0.jar
mcw-paintings-1.0.4fabric-mc1.19.jar
modmenu-4.0.4.jar
MouseTweaks-fabric-mc1.19-2.22.jar
NaturesCompass-1.19-2.0.4-fabric.jar
OneBlockRandomDrop-1.1.0.jar
Paintings-fabric-1.19-10.0.0.0.jar
Pehkui-3.6.0+1.14.4-1.19.3.jar
PuzzlesLib-v4.0.18-1.19-Fabric.jar
reeses_sodium_options-1.4.9+mc1.19.2-build.67.jar
replaymod-1.19-2.6.8.jar
SimpleDiscordRichPresence-fabric-2.0.1-build.16+mc1.19.jar
simple-rpc-fabric-1.19.x-3.2.1.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
Terraria Paintings Fabric 2.0.0 1.19.jar
transparent-5.1.2+1.19-fabric.jar
twigs-2.0.0-beta.9+1.19-fabric.jar
VisualWorkbench-v4.0.0-1.19-Fabric.jar
voicechat-fabric-1.19-2.3.28.jar
WI-Zoom-1.4-MC1.19.jar
worldedit-mod-7.2.11-beta-02-dist.jar

**Comment by SuSsyGuyYT** [comment]
In the Crash report it says Windows 10, but I installed the Minecraft Launcher before the upgrade, so i is Windows 11 and the Crash report says it wrong (i think)

**Comment by IMS212** [comment]
We need a full `latest.log` file of the crash.

**Comment by SuSsyGuyYT** [comment]
I fixed it, i reinstalled all mods

**Comment by sombrae** [comment]
> I fixed it, i reinstalled all mods

what mod was the issue? im having the same problem as u
