### ISSUE TITLE
"$$2" is null

### ISSUE THREAD

**Issue by kyber-6** [IrisShaders/Iris#1921]
### Minecraft Version

Minecraft 1.19.2

### Iris Version

iris-mc1.19.2-1.5.2

### Sodium Version

 sodium-fabric-mc1.19.2-0.4.4+build.18

### Operating System

Windows 11

### What is your GPU?

NVIDIA GeForce GTX 1650

### Java Version

OpenJDK 17.0.3

### Reproduction Steps

The game crashed once the loading screen finished, as the main menu of Minecraft was about to be displayed.

[crash-2023-03-15_12.37.41-client.txt](https://github.com/IrisShaders/Iris/files/11022504/crash-2023-03-15_12.37.41-client.txt)
[message.txt](https://github.com/IrisShaders/Iris/files/11022505/message.txt)

### Additional context

This crash was reported by many people who tried to play my modpack, [Fantasy Minecraft](https://www.curseforge.com/minecraft/modpacks/fantasy-minecraft-fabric). After disabling Iris, the crash would no longer occur. It probably occurs only on specific types of graphics cards, as most can play the modpack just fine. The modpack also contains FancyMenu, and there is a custom loading and main menu screen, but I do not know if this has something to do with it.

**Comment by IMS212** [comment]
Could you try disabling advancementplaques? I feel that could be a possible cause.

**Comment by kyber-6** [comment]
I told them to try disabling that before Iris, and they reported that it was still crashing. I also added [this mod](https://www.curseforge.com/minecraft/mc-mods/resource-pack-overrides) recently, which loads [this resource-pack](https://www.curseforge.com/minecraft/texture-packs/embellished-stone-advancement-plaques) for Advancement Plaques, but I am unsure if this has anything to do with it.

**Comment by coderbot16** [comment]
Stack trace remapped to Yarn:

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.client.render.Shader.addSampler(String, Object)" because "$$2" is null
	at net.minecraft.client.gl.VertexBuffer.drawInternal(VertexBuffer.java:128)
	at net.minecraft.client.gl.VertexBuffer.draw(VertexBuffer.java:121)
	at net.minecraft.client.render.BufferRenderer.drawWithShaderInternal(BufferRenderer.java:33)
	at net.minecraft.client.render.BufferRenderer.drawWithShader(BufferRenderer.java:26)
	at net.minecraft.client.render.RenderLayer.draw(RenderLayer.java:751)
	at net.minecraft.VertexConsumerProvider$Immediateclass_4598.draw(VertexConsumerProvider.java:96)
	at net.minecraft.VertexConsumerProvider$Immediateclass_4598.method_24213(VertexConsumerProvider.java:75)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.VertexConsumerProvider$Immediateclass_4598.draw(VertexConsumerProvider.java:72)
	at net.minecraft.client.font.TextRenderer.draw(TextRenderer.java:117)
	at net.minecraft.client.font.TextRenderer.drawWithShadow(TextRenderer.java:77)
	at io.wispforest.owo.ui.util.UIErrorToast.draw(UIErrorToast.java:64)
	at net.minecraft.client.toast.ToastManager$class_375.draw(ToastManager.java:154)
	at net.minecraft.client.toast.ToastManager.method_45074(ToastManager.java:38)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
	at net.minecraft.ToastManager.draw(ToastManager.java:37)
	at com.anthonyhilyard.advancementplaques.AdvancementPlaquesToastGui.draw(AdvancementPlaquesToastGui.java:59)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1179)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:768)
	at net.minecraft.client.main.Main.main(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
