### ISSUE TITLE
I dont know which mod is causing it but i see iris in it

### ISSUE THREAD

**Issue by DmTuv** [IrisShaders/Iris#1961]
### Minecraft Version

1.19.2 fabric

### Iris Version

1.19.4-1.6.1

### Sodium Version

1.19.4-0.4.10

### Operating System

windows 10

### What is your GPU?

GeForce GTX 1060 OC

### Java Version

Java 8

### Reproduction Steps

1. I launch game
2. Game crashes

### Crash Report file and latest.log

```shell
[00:58:10] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.14
[00:58:10] [main/INFO]: Loading 185 mods:
	- additionz 1.0.1
	- advanced_runtime_resource_pack 0.6.2 via extrasounds
	- advancementplaques 1.4.6
	- ambientsounds 5.2.13
	- amecsapi 1.3.7+mc22w17a via mousewheelie
	- amplifiednether 1.2
	- appleskin 2.4.1+mc1.19
	- areas 4.3
	- auditory 0.0.4-1.19.x
	- autotag 2.0.0+1.19 via autotag-convention
	- autotag-convention 2.0.0+1.19
	- bedspreads 6.0.0+1.19.2
	- betteradvancements 0.2.2.142
	- betterbiomeblend 1.19-1.3.6-fabric
	- betterdungeons 1.19.2-Fabric-3.2.1
	- bettermineshafts 1.19.2-Fabric-3.2.0
	- betterstrongholds 1.19.2-Fabric-3.2.0
	- betterthirdperson 1.9.0
	- camerautils 1.19.2-1.0.3
	- cardinal-components-base 5.0.2 via puzzleslib
	- cardinal-components-block 5.0.2 via puzzleslib
	- cardinal-components-chunk 5.0.2 via puzzleslib
	- cardinal-components-entity 5.0.2 via puzzleslib
	- cardinal-components-world 5.0.2 via puzzleslib
	- cherishedworlds 6.0.5+1.19.4
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 8.2.88 via shulkerboxtooltip
	- coat 1.0.0-beta.19+mc22w17a via mousewheelie
	- collective 6.53
	- com_electronwill_night-config_core 3.6.5 via forgeconfigapiport
	- com_electronwill_night-config_toml 3.6.5 via forgeconfigapiport
	- com_github_llamalad7_mixinextras 0.2.0-beta.6 via repurposed_structures
	- com_github_luben_zstd-jni 1.5.2-2 via dashloader
	- connectiblechains 2.1.4+1.19.2
	- continuity 2.0.2+1.19
	- creativecore 2.9.3
	- dashloader 4.1.3+1.19
	- deepslatecutting 1.5.0
	- dev_quantumfusion_hyphen 0.2.2 via dashloader
	- dev_quantumfusion_taski 1.1.0 via dashloader
	- diagonalfences 4.2.3
	- easyanvils 4.0.11
	- easymagic 4.3.3
	- eatinganimationid 1.9.1
	- effective 1.2.2
	- enhancedvisuals 1.5.9
	- extrasounds 2.3.1+1.19.2-1.19.1
	- fabric-api 0.76.0+1.19.2
	- fabric-api-base 0.4.23+9ff28bced8 via sodium
	- fabric-api-lookup-api-v1 1.6.14+93d8cb8290 via fabric-api
	- fabric-biome-api-v1 9.1.1+16f1e31390 via fabric-api
	- fabric-block-api-v1 1.0.2+e415d50e90 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90 via fabric-api
	- fabric-client-tags-api-v1 1.0.5+b35fea8390 via fabric-api
	- fabric-command-api-v1 1.2.16+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.2.1+413cbbc790 via fabric-api
	- fabric-commands-v0 0.2.33+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.41+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.5.2+7c6cd14d90 via fabric-api
	- fabric-convention-tags-v1 1.3.0+4bc6e26290 via fabric-api
	- fabric-crash-report-info-v1 0.2.8+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.3.8+413cbbc790 via fabric-api
	- fabric-dimensions-v1 2.1.35+0d0f210290 via fabric-api
	- fabric-entity-events-v1 1.5.4+9244241690 via fabric-api
	- fabric-events-interaction-v0 0.4.34+562bff6e90 via fabric-api
	- fabric-events-lifecycle-v0 0.2.36+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.24+b6b6abb490 via fabric-api
	- fabric-item-api-v1 1.6.6+b7d1888890 via fabric-api
	- fabric-item-groups-v0 0.3.39+9244241690 via fabric-api
	- fabric-key-binding-api-v1 1.0.25+5c4fce2890 via fabric-api
	- fabric-keybindings-v0 0.2.23+df3654b390 via fabric-api
	- fabric-language-kotlin 1.9.3+kotlin.1.8.20
	- fabric-lifecycle-events-v1 2.2.4+1b46dc7890 via fabric-api
	- fabric-loot-api-v2 1.1.13+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.16+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.7+93d8cb8290 via fabric-api
	- fabric-mining-level-api-v1 2.1.24+33fbc73890 via fabric-api
	- fabric-models-v0 0.3.21+c6af733c90 via fabric-api
	- fabric-networking-api-v1 1.2.11+10eb22f490 via fabric-api
	- fabric-networking-v0 0.3.28+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.2.2+d8ef690890 via fabric-api
	- fabric-particles-v1 1.0.14+4d0d570390 via fabric-api
	- fabric-recipe-api-v1 1.0.1+413cbbc790 via fabric-api
	- fabric-registry-sync-v0 0.9.32+9244241690 via fabric-api
	- fabric-renderer-api-v1 1.2.1+1adbf27790 via fabric-api
	- fabric-renderer-indigo 0.8.0+1adbf27790 via fabric-api
	- fabric-renderer-registries-v1 3.2.24+df3654b390 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.27+afca2f3ed8 via sodium
	- fabric-rendering-fluids-v1 3.0.20+f1e4495bd8 via sodium
	- fabric-rendering-v0 1.1.27+df3654b390 via fabric-api
	- fabric-rendering-v1 1.12.1+d8ef690890 via fabric-api
	- fabric-resource-conditions-api-v1 2.1.2+aae9039d90 via fabric-api
	- fabric-resource-loader-v0 0.10.9+711cde8ad8 via sodium
	- fabric-screen-api-v1 1.0.32+4d0d570390 via fabric-api
	- fabric-screen-handler-api-v1 1.3.7+1cc24b1b90 via fabric-api
	- fabric-sound-api-v1 1.0.2+c4f28df590 via fabric-api
	- fabric-textures-v0 1.0.24+aeb40ebe90 via fabric-api
	- fabric-transfer-api-v1 2.1.6+413cbbc790 via fabric-api
	- fabric-transitive-access-wideners-v1 1.3.3+08b73de490 via fabric-api
	- fabricloader 0.14.14
	- fabricshieldlib 1.7-1.19.2
	- fallingleaves 1.13.0+1.19.2
	- ferritecore 5.0.3
	- firstperson 2.2.0
	- forgeconfigapiport 4.2.11
	- herdspanic 1.0.6
	- highlighter 1.1.4
	- iceberg 1.0.46
	- illuminations 1.10.11
	- immersive_weathering 1.19.2-1.2.9
	- inmis 2.7.1-1.19
	- inmisaddon 1.0.4
	- io_github_douira_glsl-transformer 2.0.0-pre12 via iris
	- iris 1.6.1
	- itemborders 1.1.6
	- jamlib 0.6.0+1.19
	- java 17
	- kirin 1.11.1 via presencefootsteps
	- kiwi 8.3.3
	- lambdabettergrass 1.3.0+1.19
	- lazydfu 0.1.3
	- legendarytooltips 1.3.3
	- libz 1.0.0
	- lithium 0.11.1
	- maybe-data 1.3.2-1.19.2 via deepslatecutting
	- midnightlib 1.0.0
	- minecraft 1.19.2
	- mm 2.3 via fabricshieldlib
	- modmenu 4.2.0-beta.2
	- moonlight 1.19.2-2.2.31
	- morebannerfeatures 1.1.3
	- moremobvariants 1.0.1
	- mousewheelie 1.10.7+mc1.19.2
	- notenoughanimations 1.6.2
	- omega-config 1.2.3-1.18.1 via inmis
	- org_anarres_jcpp 1.4.14 via iris
	- org_antlr_antlr4-runtime 4.11.1 via iris
	- org_javassist_javassist 3.28.0-GA via yungsapi
	- org_jetbrains_kotlin_kotlin-reflect 1.8.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.8.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.20 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.20.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0 via fabric-language-kotlin
	- org_reflections_reflections 0.10.2 via yungsapi
	- paxi 1.19.2-Fabric-3.0.1
	- presencefootsteps 1.6.4
	- prism 1.0.3
	- puzzleslib 4.4.0
	- reach-entity-attributes 2.3.0 via tiered
	- repurposed_structures 6.3.24+1.19.2
	- rightclickharvest 3.1.0+1.19-1.19.2
	- seasons 2.0+1.19
	- shulkerboxtooltip 3.2.2+1.19.2
	- smoothswapping 0.6
	- snowrealmagic 5.1.0
	- sodium 0.4.10+build.24
	- soulfired 3.1.0.0-final
	- sound_physics_remastered 1.19.2-1.0.18
	- soundcategories 1.2.4+1.19 via extrasounds
	- spiderstpo 1.19.2-2.0.3
	- spruceui 4.0.0+1.19 via lambdabettergrass
	- starlight 1.1.1+fabric.ae22326
	- terralith 2.3
	- tiered 1.2.6
	- tooltiprareness 1.0.7
	- trinkets 3.4.2
	- tweed4_annotated 1.3.1+mc22w17a via mousewheelie
	- tweed4_base 1.7.1+mc22w17a via mousewheelie
	- tweed4_data 1.2.1+mc22w17a via mousewheelie
	- tweed4_data_hjson 1.1.1+mc22w17a via mousewheelie
	- tweed4_tailor_coat 1.1.3+mc22w17a via mousewheelie
	- tweed4_tailor_screen 1.1.3+mc22w17a via mousewheelie
	- vanillatweaks 1.5.65
	- villagernames 5.2
	- visuality 0.5.6
	- voidfog 2.7.0
	- weaponmaster 3.0.2
	- yungsapi 1.19.2-Fabric-3.8.9
	- yungsextras 1.19.2-Fabric-3.1.0
[00:58:10] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/manag/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[00:58:10] [main/INFO]: Compatibility level set to JAVA_17
[00:58:11] [main/INFO]: Bootstrapping DashLoader 4.1.3+1.19.
[00:58:11] [main/INFO]: Loaded configuration file for Lithium: 114 options available, 1 override(s) found
[00:58:11] [main/INFO]: Loaded configuration file for Sodium: 33 options available, 6 override(s) found
[00:58:11] [main/WARN]: Reference map 'yungsextras.refmap.json' for yungsextras.mixins.json could not be read. If this is a development environment you can ignore this message
[00:58:11] [main/WARN]: Reference map 'yungsextras.refmap.json' for yungsextras_fabric.mixins.json could not be read. If this is a development environment you can ignore this message
[00:58:12] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/pipeline/FluidRenderer (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/pipeline/FluidRenderer)
[00:58:12] [main/WARN]: @Mixin target me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer was not found effective.mixins.json:integration.sodium.FluidRendererMixin from mod effective
[00:58:12] [main/WARN]: Error loading class: net/minecraft/class_7678 (java.lang.ClassNotFoundException: net/minecraft/class_7678)
[00:58:12] [main/WARN]: @Mixin target net.minecraft.class_7678 was not found fabric-resource-loader-v0.client.mixins.json:VanillaResourcePackProviderMixin from mod fabric-resource-loader-v0
[00:58:12] [main/WARN]: Error loading class: org/joml/Matrix4f (java.lang.ClassNotFoundException: org/joml/Matrix4f)
[00:58:12] [main/WARN]: @Mixin target org.joml.Matrix4f was not found mixins.iris.json:math.MixinMatrix4f from mod iris
[00:58:12] [main/WARN]: Error loading class: net/minecraft/class_7764 (java.lang.ClassNotFoundException: net/minecraft/class_7764)
[00:58:12] [main/WARN]: @Mixin target net.minecraft.class_7764 was not found mixins.iris.json:texture.MixinSpriteContents from mod iris
[00:58:12] [main/WARN]: Error loading class: net/minecraft/class_7764 (java.lang.ClassNotFoundException: net/minecraft/class_7764)
[00:58:12] [main/WARN]: @Mixin target net.minecraft.class_7764 was not found mixins.iris.json:texture.SpriteContentsAccessor from mod iris
[00:58:12] [main/WARN]: Error loading class: net/minecraft/class_7764$class_5790 (java.lang.ClassNotFoundException: net/minecraft/class_7764$class_5790)
[00:58:12] [main/WARN]: @Mixin target net.minecraft.class_7764$class_5790 was not found mixins.iris.json:texture.SpriteContentsAnimatedTextureAccessor from mod iris
[00:58:12] [main/WARN]: Error loading class: net/minecraft/class_7764$class_5791 (java.lang.ClassNotFoundException: net/minecraft/class_7764$class_5791)
[00:58:12] [main/WARN]: @Mixin target net.minecraft.class_7764$class_5791 was not found mixins.iris.json:texture.SpriteContentsFrameInfoAccessor from mod iris
[00:58:12] [main/WARN]: Error loading class: net/minecraft/class_7764$class_7765 (java.lang.ClassNotFoundException: net/minecraft/class_7764$class_7765)
[00:58:12] [main/WARN]: @Mixin target net.minecraft.class_7764$class_7765 was not found mixins.iris.json:texture.SpriteContentsTickerAccessor from mod iris
[00:58:12] [main/WARN]: Error loading class: net/minecraft/class_7954 (java.lang.ClassNotFoundException: net/minecraft/class_7954)
[00:58:12] [main/WARN]: @Mixin target net.minecraft.class_7954 was not found mixins.iris.json:texture.pbr.MixinDirectoryLister from mod iris
[00:58:12] [main/WARN]: Error loading class: net/minecraft/class_7764 (java.lang.ClassNotFoundException: net/minecraft/class_7764)
[00:58:12] [main/WARN]: @Mixin target net.minecraft.class_7764 was not found mixins.iris.json:texture.pbr.MixinSpriteContents from mod iris
[00:58:12] [main/WARN]: Error loading class: net/minecraft/class_7764 (java.lang.ClassNotFoundException: net/minecraft/class_7764)
[00:58:12] [main/WARN]: @Mixin target net.minecraft.class_7764 was not found mixins.iris.bettermipmaps.json:MixinTextureAtlasSprite from mod iris
[00:58:12] [main/WARN]: Error loading class: net/minecraft/class_7764 (java.lang.ClassNotFoundException: net/minecraft/class_7764)
[00:58:12] [main/WARN]: @Mixin target net.minecraft.class_7764 was not found mixins.iris.compat.sodium.json:pbr_animation.MixinSpriteContents from mod iris
[00:58:12] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[00:58:12] [main/WARN]: Force-disabling mixin 'features.entity.fast_render.MixinCuboid' as rule 'mixin.features.entity.fast_render' (added by mods [iris]) disables it and children
[00:58:12] [main/WARN]: Force-disabling mixin 'features.entity.fast_render.MixinModelPart' as rule 'mixin.features.entity.fast_render' (added by mods [iris]) disables it and children
[00:58:12] [main/WARN]: Force-disabling mixin 'features.gui.font.MixinGlyphRenderer' as rule 'mixin.features.gui.font' (added by mods [iris]) disables it and children
[00:58:12] [main/WARN]: Force-disabling mixin 'features.model.MixinMultipartBakedModel' as rule 'mixin.features.model' (added by mods [dashloader]) disables it and children
[00:58:12] [main/WARN]: Force-disabling mixin 'features.model.MixinWeightedBakedModel' as rule 'mixin.features.model' (added by mods [dashloader]) disables it and children
[00:58:12] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[00:58:12] [main/WARN]: Force-disabling mixin 'features.texture_updates.AnimationAccessor' as rule 'mixin.features.texture_updates' (added by mods [dashloader]) disables it and children
[00:58:12] [main/WARN]: Force-disabling mixin 'features.texture_updates.AnimationFrameAccessor' as rule 'mixin.features.texture_updates' (added by mods [dashloader]) disables it and children
[00:58:12] [main/WARN]: Force-disabling mixin 'features.texture_updates.MixinSpriteInterpolated' as rule 'mixin.features.texture_updates' (added by mods [dashloader]) disables it and children
[00:58:12] [main/WARN]: Force-disabling mixin 'features.texture_updates.SpriteInfoAccessor' as rule 'mixin.features.texture_updates' (added by mods [dashloader]) disables it and children
[00:58:12] [main/WARN]: Force-disabling mixin 'features.texture_updates.SpriteInfoAnimationAccessor' as rule 'mixin.features.texture_updates' (added by mods [dashloader]) disables it and children
[00:58:12] [main/WARN]: Error loading class: net/minecraft/class_7764 (java.lang.ClassNotFoundException: net/minecraft/class_7764)
[00:58:12] [main/WARN]: @Mixin target net.minecraft.class_7764 was not found sodium.mixins.json:features.texture_tracking.MixinSpriteContents from mod sodium
[00:58:12] [main/WARN]: Error loading class: net/minecraft/class_7764$class_7765 (java.lang.ClassNotFoundException: net/minecraft/class_7764$class_7765)
[00:58:12] [main/WARN]: @Mixin target net.minecraft.class_7764$class_7765 was not found sodium.mixins.json:features.texture_tracking.MixinSpriteContentsAnimatorImpl from mod sodium
[00:58:12] [main/WARN]: Error loading class: net/minecraft/class_5253$class_8045 (java.lang.ClassNotFoundException: net/minecraft/class_5253$class_8045)
[00:58:12] [main/INFO]: I used the json to destroy the json
[00:58:13] [main/INFO]: Initializing DashLoader 4.1.3+1.19.
[00:58:13] [main/INFO]: [76ms] Initialized api.
[00:58:13] [main/ERROR]: Mixin apply for mod iris failed mixins.iris.json:texture.TextureAtlasAccessor from mod iris -> net.minecraft.class_1059: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching field_43115:I in net/minecraft/class_1059 for mixins.iris.json:texture.TextureAtlasAccessor from mod iris->@Accessor[FIELD_GETTER]::getMipLevel()I [INJECT Applicator Phase -> mixins.iris.json:texture.TextureAtlasAccessor from mod iris -> Apply Accessors ->  -> Locate -> mixins.iris.json:texture.TextureAtlasAccessor from mod iris->@Accessor[FIELD_GETTER]::getMipLevel()I]
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching field_43115:I in net/minecraft/class_1059 for mixins.iris.json:texture.TextureAtlasAccessor from mod iris->@Accessor[FIELD_GETTER]::getMipLevel()I [INJECT Applicator Phase -> mixins.iris.json:texture.TextureAtlasAccessor from mod iris -> Apply Accessors ->  -> Locate -> mixins.iris.json:texture.TextureAtlasAccessor from mod iris->@Accessor[FIELD_GETTER]::getMipLevel()I]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:518) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:501) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:475) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1412) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1061) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:398) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.14.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?]
	at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?]
	at java.lang.Class.getConstructor(Class.java:2271) ~[?:?]
	at dev.quantumfusion.hyphen.codegen.def.ClassDef.scan(ClassDef.java:59) ~[dev_quantumfusion_hyphen-0.2.2-a5cdfe90d6a758e0.jar:?]
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:112) ~[dev_quantumfusion_hyphen-0.2.2-a5cdfe90d6a758e0.jar:?]
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:101) ~[dev_quantumfusion_hyphen-0.2.2-a5cdfe90d6a758e0.jar:?]
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:101) ~[dev_quantumfusion_hyphen-0.2.2-a5cdfe90d6a758e0.jar:?]
	at dev.quantumfusion.hyphen.codegen.def.ClassDef.scan(ClassDef.java:43) ~[dev_quantumfusion_hyphen-0.2.2-a5cdfe90d6a758e0.jar:?]
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:112) ~[dev_quantumfusion_hyphen-0.2.2-a5cdfe90d6a758e0.jar:?]
	at dev.quantumfusion.hyphen.codegen.def.IndexedDef.<init>(IndexedDef.java:27) ~[dev_quantumfusion_hyphen-0.2.2-a5cdfe90d6a758e0.jar:?]
	at dev.quantumfusion.hyphen.codegen.def.ListDef.<init>(ListDef.java:16) ~[dev_quantumfusion_hyphen-0.2.2-a5cdfe90d6a758e0.jar:?]
	at dev.quantumfusion.hyphen.codegen.def.ListDef.<init>(ListDef.java:25) ~[dev_quantumfusion_hyphen-0.2.2-a5cdfe90d6a758e0.jar:?]
	at dev.quantumfusion.hyphen.SerializerHandler.lambda$static$1(SerializerHandler.java:35) ~[dev_quantumfusion_hyphen-0.2.2-a5cdfe90d6a758e0.jar:?]
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDefNew(SerializerHandler.java:125) [dev_quantumfusion_hyphen-0.2.2-a5cdfe90d6a758e0.jar:?]
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:109) [dev_quantumfusion_hyphen-0.2.2-a5cdfe90d6a758e0.jar:?]
	at dev.quantumfusion.hyphen.codegen.def.ClassDef.scan(ClassDef.java:43) [dev_quantumfusion_hyphen-0.2.2-a5cdfe90d6a758e0.jar:?]
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:112) [dev_quantumfusion_hyphen-0.2.2-a5cdfe90d6a758e0.jar:?]
	at dev.quantumfusion.hyphen.codegen.def.ClassDef.scan(ClassDef.java:43) [dev_quantumfusion_hyphen-0.2.2-a5cdfe90d6a758e0.jar:?]
	at dev.quantumfusion.hyphen.SerializerHandler.acquireDef(SerializerHandler.java:112) [dev_quantumfusion_hyphen-0.2.2-a5cdfe90d6a758e0.jar:?]
	at dev.quantumfusion.hyphen.codegen.def.ClassDef.scan(ClassDef.java:43) [dev_quantumfusion_hyphen-0.2.2-a5cdfe90d6a758e0.jar:?]
	at dev.quantumfusion.hyphen.SerializerHandler.scan(SerializerHandler.java:162) [dev_quantumfusion_hyphen-0.2.2-a5cdfe90d6a758e0.jar:?]
	at dev.quantumfusion.hyphen.SerializerHandler.build(SerializerHandler.java:169) [dev_quantumfusion_hyphen-0.2.2-a5cdfe90d6a758e0.jar:?]
	at dev.quantumfusion.hyphen.SerializerFactory.build(SerializerFactory.java:181) [dev_quantumfusion_hyphen-0.2.2-a5cdfe90d6a758e0.jar:?]
	at dev.quantumfusion.dashloader.io.serializer.DashSerializer.create(DashSerializer.java:73) [dashloader-4.1.3+1.19.jar:?]
	at dev.quantumfusion.dashloader.io.IOHandler.addSerializer(IOHandler.java:34) [dashloader-4.1.3+1.19.jar:?]
	at dev.quantumfusion.dashloader.DashLoader.initialize(DashLoader.java:105) [dashloader-4.1.3+1.19.jar:?]
	at net.minecraft.client.main.Main.handler$zla000$main(Main.java:520) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.14.jar:?]
[00:58:13] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: mc exception bad
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.14.jar:?]
Caused by: java.lang.RuntimeException: mc exception bad
	at dev.quantumfusion.dashloader.DashLoader.initialize(DashLoader.java:111) ~[dashloader-4.1.3+1.19.jar:?]
	at net.minecraft.client.main.Main.handler$zla000$main(Main.java:520) ~[fabric-loader-0.14.14-1.19.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java) ~[fabric-loader-0.14.14-1.19.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.14.jar:?]
	... 2 more
```

### Additional context

Error code 1

**Comment by Lolothepro** [comment]
You use Iris for Minecraft 1.19.4 with Minecraft 1.19.2
