### ISSUE TITLE
Consistent out of memory errors when developing shaders

### ISSUE THREAD

**Issue by ambrosia13** [IrisShaders/Iris#1962]
### Minecraft Version

1.19.4

### Iris Version

1.6.1

### Sodium Version

0.4.10+build.24

### Operating System

Windows 10

### What is your GPU?

Nvidia RTX 3060

### Java Version

Java 17

### Reproduction Steps

1. Load up the [base150 shaderpack](https://cdn.discordapp.com/attachments/960320448594329630/960695935837548695/base150.zip). This issue also happens with every other shaderpack I tested, like BSL.
2. Move around, maybe recompile shaders once or twice.
3. There will be an out of memory crash within a few minutes or seconds. (happens consistently for me)

In my (limited) testing, this only happens when shaders are enabled.

Note that in the attached log, there was no such exception, but on some occasions there has been an out of memory error from Sodium:
```
[22:34:23] [Chunk Render Task Executor #6/ERROR]: Uncaught exception in thread "Chunk Render Task Executor #6"
java.lang.OutOfMemoryError: null
	at org.lwjgl.system.MemoryUtil.nmemReallocChecked(MemoryUtil.java:496) ~[lwjgl-3.3.1.jar:build 7]
	at org.lwjgl.system.MemoryUtil.memRealloc(MemoryUtil.java:529) ~[lwjgl-3.3.1.jar:build 7]
	at me.jellysquid.mods.sodium.client.render.vertex.type.ChunkVertexBufferBuilder.setBufferSize(ChunkVertexBufferBuilder.java:57) ~[transformed-mod-sodium.i0:0/:?]
	at me.jellysquid.mods.sodium.client.render.vertex.type.ChunkVertexBufferBuilder.start(ChunkVertexBufferBuilder.java:65) ~[transformed-mod-sodium.i0:0/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuildBuffers.init(ChunkBuildBuffers.java:61) ~[transformed-mod-sodium.i0:0/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:56) ~[transformed-mod-sodium.i0:0/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.processJob(ChunkBuilder.java:286) ~[transformed-mod-sodium.i0:0/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:328) ~[transformed-mod-sodium.i0:0/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Crash Report file and latest.log

```shell
Log: https://mclo.gs/eWrahKi
No crash report is generated
```

**Comment by ambrosia13** [comment]
This also happens with Iris 1.5.2, so it might be a Sodium issue, but then again this only happened with shaders enabled

**Comment by ambrosia13** [comment]
Fixed after a PC restart
