### ISSUE TITLE
1.19.2 not loading shaders and a weird required sodium version

### ISSUE THREAD

**Issue by wackoamd1** [IrisShaders/Iris#1970]
### What happened?

not a single shader loads.
i can enable them but nothing happens.

below i pasted a part of the log which keeps repeating over and over and over.

i think it has something to do with iris 1.6.1+1.19.2 reqs, sodium 1.9.4-0.4.10 ( which doesnt work on 1.19.2)

which is weird because thats a 1.19.4 sodium which doesnt load on 1.19.2.

why would a 1.19.2 mod requires a 1.19.4 mod.?? (btw every single 1.6 iris needs that impossible sodium version)

[13:43:30] [Render thread/ERROR]: Mixin apply for mod imm_ptl_core failed imm_ptl_compat.mixins.json:MixinIrisSodiumSodiumTerrainPipeline from mod imm_ptl_core -> net.coderbot.iris.pipeline.SodiumTerrainPipeline: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on onGetTerrainVertexShaderSource could not find any targets matching 'getTerrainVertexShaderSource' in net.coderbot.iris.pipeline.SodiumTerrainPipeline. Using refmap imm_ptl_core-refmap.json [PREINJECT Applicator Phase -> imm_ptl_compat.mixins.json:MixinIrisSodiumSodiumTerrainPipeline from mod imm_ptl_core -> Prepare Injections ->  -> handler$dlj000$imm_ptl_core$onGetTerrainVertexShaderSource(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on onGetTerrainVertexShaderSource could not find any targets matching 'getTerrainVertexShaderSource' in net.coderbot.iris.pipeline.SodiumTerrainPipeline. Using refmap imm_ptl_core-refmap.json [PREINJECT Applicator Phase -> imm_ptl_compat.mixins.json:MixinIrisSodiumSodiumTerrainPipeline from mod imm_ptl_core -> Prepare Injections ->  -> handler$dlj000$imm_ptl_core$onGetTerrainVertexShaderSource(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at jdk.internal.reflect.GeneratedConstructorAccessor21.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) [fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.getSodiumTerrainPipeline(IrisChunkProgramOverrides.java:216) [iris-mc1.19.2-1.6.1.jar:?]
	at net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.bindFramebuffer(IrisChunkProgramOverrides.java:288) [iris-mc1.19.2-1.6.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.handler$edj000$iris$begin(ShaderChunkRenderer.java:564) [sodium-fabric-mc1.19.2-0.4.4+build.18.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java) [sodium-fabric-mc1.19.2-0.4.4+build.18.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:70) [sodium-fabric-mc1.19.2-0.4.4+build.18.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289) [sodium-fabric-mc1.19.2-0.4.4+build.18.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:221) [sodium-fabric-mc1.19.2-0.4.4+build.18.jar:?]
	at net.minecraft.class_761.method_3251(class_761.java:19800) [client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1246) [client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1039) [client-intermediary.jar:?]
	at net.minecraft.class_757.redirect$djf000$imm_ptl_core$redirectRenderingWorld(class_757.java:5154) [client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:816) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1177) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.19.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]

### Minecraft Version

1.19.2

### Iris Version

1.19.2=1.6.1

### Operating System

win10

### What is your GPU?

rtx 3060 ti

**Comment by IMS212** [comment]
This is caused by Immersive Portals not being updated for 1.19.2 anymore.
