### ISSUE TITLE
Iris crash when entering any world

### ISSUE THREAD

**Issue by LetalexAlexYT** [IrisShaders/Iris#1976]
### Minecraft Version

Fabric 1.19.4

### Iris Version

iris-mc1.19.4-1.6.1.jar

### Sodium Version

sodium-fabric-mc1.19.4-0.4.11+build.26.jar

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce RTX 3080

### Java Version

Java 17.0.3

### Reproduction Steps

1. Start up Fabric with: Fabric API, newest version of Sodium and Iris.
2. Game loads but text rendering is disabled (https://imgur.com/a/U53MFWw)
3. When entering any world, game crashes instantly.

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2023-05-01 14:46:00
Description: Unexpected error

java.lang.IllegalStateException: An invalid version of Sodium is installed, and the warning screen somehow didn't work. This is a bug! Please report it to the Iris developers.
	at net.minecraft.class_761.handler$bip000$iris$beginLevelRender(class_761.java:7947)
	at net.minecraft.class_761.method_22710(class_761.java:1232)
	at net.minecraft.class_757.method_3188(class_757.java:1100)
	at net.minecraft.class_757.method_3192(class_757.java:872)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_761.handler$bip000$iris$beginLevelRender(class_761.java:7947)
	at net.minecraft.class_761.method_22710(class_761.java:1232)
	at net.minecraft.class_757.method_3188(class_757.java:1100)

-- Affected level --
Details:
	All players: 1 total; [class_746['LetalexAlexYT'/30939, l='ClientLevel', x=583.55, y=63.00, z=-839.89]]
	Chunk stats: 4096, 103
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,74,-32), Section: (at 0,10,0 in 1,4,-2; chunk contains blocks 16,-64,-32 to 31,319,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 3185163 game time, 3701031 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, Fabric Mods
	Recovery: Yes
	Recovery reason: java.util.concurrent.CompletionException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_7764 failed
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_7764 failed
	at net.minecraft.class_7948$class_7949.method_47674(class_7948.java:22)
	at net.minecraft.class_7954.method_47683(class_7954.java:32)
	at net.minecraft.class_7954.md6e2e4a$iris$lambda$iris$modifyForEachAction$0$0(class_7954.java:529)
	at java.base/java.util.TreeMap.forEach(TreeMap.java:1282)
	at net.minecraft.class_7954.method_47673(class_7954.java:30)
	at net.minecraft.class_7947.method_47669(class_7947.java:61)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at net.minecraft.class_7947.method_47667(class_7947.java:61)
	at net.minecraft.class_7766.method_47660(class_7766.java:113)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more


-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 765328032 bytes (729 MiB) / 1931476992 bytes (1842 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5900X 12-Core Processor            
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 3080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2216
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2849
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 34737.00
	Virtual memory used (MB): 15576.99
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 0.50
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		betterf3: BetterF3 6.0.1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.2+1e1fb126f4
		bookshelf: Bookshelf 18.0.2
		carpet: Carpet Mod 1.4.101+v230319
		carpet-extra: Carpet Extra 1.4.100
		chat_heads: Chat Heads 0.10.12
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		entityculling: EntityCulling-Fabric 1.6.2-mc1.19.4
		fabric-api: Fabric API 0.79.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.24+9ff28bcef4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.25+49abcf7ef4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.7+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.6+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.34+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.15+1134c5b8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.27+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.6+e719b857f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.44+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.54+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.9+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.1+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.15+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.0+6cebf059f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.45+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.13+e45f7c65f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.43+a1ccd7bff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.52+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.33+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.17+09a3510cf4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.5+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.33+c477957ef4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.31+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.15+5da15ca1f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.27+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.31+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.1+1ee8be40f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.39+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.30+11ba9c3bf4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.1+a6f3ccfaf4
			fabric-networking-v0: Fabric Networking (v0) 0.3.41+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.3+63b515f4f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.23+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.8+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.0+670e8ac6f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.5+81e8c576f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.1+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.38+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.28+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.21+f1e4495bf4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.41+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.1+8f878217f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.1+e6c7d4eef4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.45+8c25edb4f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.20+5da15ca1f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.9+75e98211f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.1.1+da9bb835f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.3+63b515f4f4
		fabricloader: Fabric Loader 0.14.19
		iris: Iris 1.6.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre12
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		lithium: Lithium 0.11.1
		minecraft: Minecraft 1.19.4
		modmenu: Mod Menu 6.1.0-rc.4
		nochatreports: No Chat Reports 1.19.4-v2.1.1
		plasmovoice: Plasmo Voice 2.0.3
			aopalliance_aopalliance: aopalliance 1.0
			com_google_inject_guice: guice 5.0.1
			fabric-language-kotlin: Fabric Language Kotlin 1.9.1+kotlin.1.8.10
				org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
				org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
				org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
				org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
				org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.19.0
				org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
				org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
				org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
				org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
				org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
				org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			javax_inject_javax_inject: javax.inject 1
			universalcraft: UniversalCraft 262
			ustats: uStats 1.0.0
		skinlayers: 3d Skin Layers 1.5.3-mc1.19.4
		sodium: Sodium 0.4.11+build.26
		sodium-extra: Sodium Extra 0.4.19+mc1.19.3-build.101
			caffeineconfig: CaffeineConfig 1.1.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		starlight: Starlight 1.1.1+fabric.ae22326
		tipsmod: Tips 10.0.2
		worldedit: WorldEdit 7.2.14+6360-094b734
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.19-1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3080/PCIe/SSE2 GL version 3.2.0 NVIDIA 528.49, NVIDIA Corporation
	Window size: 2560x1417
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: en_us
	CPU: 24x AMD Ryzen 9 5900X 12-Core Processor
```

### Additional context

removing Iris from the mods fixes everything. It might be a compatibility issue with the newest version of Sodium.

**Comment by Lolothepro** [comment]
Update Iris

**Comment by IMS212** [comment]
Fixed in a future release, downgrade Sodium to 0.4.10 to fix it for now.
