### ISSUE TITLE
Crashes when loading a world. (Crashes both multiplayer and singleplayer worlds.

### ISSUE THREAD

**Issue by GalaxyDoge72** [IrisShaders/Iris#1990]
### Minecraft Version

Minecraft 1.19.4 Fabric Loader 0.14.19 

### Iris Version

iris-mc1.19.4-1.6.1

### Sodium Version

sodium-fabric-mc1.19.4-0.4.10+build.24.jar

### Operating System

Windows 10 

### What is your GPU?

AMD Ryzen 7 5700 Radeon Graphics

### Java Version

Java 19

### Reproduction Steps

Load into world or multiplayer mod.
Crashes

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-05-09 15:48:21
Description: Unexpected error

java.lang.NullPointerException: Cannot read field "field_3911" because "this.field_4015.field_1724" is null
	at net.minecraft.class_757.method_3188(class_757.java:1075)
	at net.minecraft.class_757.method_3192(class_757.java:872)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_757.method_3188(class_757.java:1075)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 16384, 813
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,79,0), Section: (at 0,15,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 38046 game time, 59317 day time
	Server brand: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.class_746.method_3135()" because "this.field_3729.field_1724" is null
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1529836288 bytes (1458 MiB) / 2885681152 bytes (2752 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5700U with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 104 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 1.80
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: DisplayLink USB Device
	Graphics card #0 vendor: DisplayLink (0x17e9)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: 0x6006
	Graphics card #0 versionInfo: DriverVersion=9.3.3324.0
	Graphics card #1 name: AMD Radeon(TM) Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 512.00
	Graphics card #1 deviceId: 0x164c
	Graphics card #1 versionInfo: DriverVersion=31.0.14043.7000
	Graphics card #2 name: DisplayLink USB Device
	Graphics card #2 vendor: DisplayLink (0x17e9)
	Graphics card #2 VRAM (MB): 0.00
	Graphics card #2 deviceId: 0x6006
	Graphics card #2 versionInfo: DriverVersion=9.3.3324.0
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 31581.99
	Virtual memory used (MB): 11729.33
	Swap memory total (MB): 15872.00
	Swap memory used (MB): 28.88
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 2.4.3+mc1.19.4
			cloth-config: Cloth Config v9 10.0.95
				cloth-basic-math: cloth-basic-math 0.6.1
		fabric-api: Fabric API 0.78.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.23+9ff28bcef4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.24+49abcf7ef4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.6+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.33+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.14+1134c5b8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.26+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.5+e719b857f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.43+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.53+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.8+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.0+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.7+5da15ca1f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.44+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.12+e45f7c65f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.42+a1ccd7bff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.51+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.32+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.16+09a3510cf4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.4+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.32+c477957ef4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.30+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.14+5da15ca1f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.26+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.30+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+1ee8be40f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.38+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.29+11ba9c3bf4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.0+a6f3ccfaf4
			fabric-networking-v0: Fabric Networking (v0) 0.3.40+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.2+63b515f4f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.22+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.7+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.3+a383ab97f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.4+81e8c576f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.0+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.37+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.27+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.20+f1e4495bf4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.40+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.0+8f878217f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.1+1e1fb126f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.44+8c25edb4f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.19+5da15ca1f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e98211f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.1.0+d51205dbf4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.2+63b515f4f4
		fabricloader: Fabric Loader 0.14.19
		iris: Iris 1.6.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre12
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		meteor-client: Meteor Client 0.5.3-1820
			baritone-meteor: Baritone 1.19.4-SNAPSHOT
		minecraft: Minecraft 1.19.4
		sodium: Sodium 0.4.10+build.24
	Loaded Shaderpack: ComplementaryShaders_v4.7.1
		Profile: VANILLA (+0 options changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.19-1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon(TM) Graphics GL version 3.2.0 Core Profile Context 23.4.1.230326, ATI Technologies Inc.
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric
	Current Language: fr_ca
	CPU: 16x AMD Ryzen 7 5700U with Radeon Graphics 
	Server Running: true
	Player Count: 1 / 8; [class_3222['GalaxyDoge72'/105, l='ServerLevel[DogeLand]', x=130.62, y=44.00, z=142.15]]
	Data Packs: vanilla, fabric, bundle
	Enabled Feature Flags: minecraft:bundle, minecraft:vanilla
	World Generation: Stable
```

**Comment by GalaxyDoge72** [comment]
> Same problem

use the iris installer instead of the jar file
