### ISSUE TITLE
Incompatible with Sodium 0.4.11, causing glyphs unable to render, but compatible with Sodium 0.4.10

### ISSUE THREAD

**Issue by SolidBlock-cn** [IrisShaders/Iris#1997]
### What happened?

If installed with Sodium 0.4.11+build.26, all glyphs render as □.
If installed with Sodium 0.4.10+build.24, everything is correct.
If installed Sodium 0.4.11+build.26 without Iris, everything is correct.

### Screenshots

Loading with Sodium 0.4.11+build.26:
![图片](https://github.com/IrisShaders/Iris/assets/32444848/dd021a97-5902-4ebd-926a-159e624c264b)

Loading with Sodium 0.4.10+build.24:
![图片](https://github.com/IrisShaders/Iris/assets/32444848/a4dd2ef8-0107-4254-89bb-ac29a4fee0d7)

### Log output

Related logs:
```
[18:38:19] [Worker-Main-4/WARN]: @Redirect conflict. Skipping sodium.mixins.json:features.mipmaps.MixinSpriteContents from mod sodium->@Redirect::sodium$beforeGenerateMipLevels(Lnet/minecraft/class_7764;Lnet/minecraft/class_1011;Lnet/minecraft/class_2960;)V with priority 1000, already redirected by mixins.iris.bettermipmaps.json:MixinTextureAtlasSprite from mod iris->@Redirect::iris$beforeGenerateMipLevels(Lnet/minecraft/class_7764;Lnet/minecraft/class_1011;Lnet/minecraft/class_2960;)V with priority 1000
[18:38:19] [Worker-Main-6/WARN]: @Redirect conflict. Skipping sodium.mixins.json:features.mipmaps.MixinSpriteContents from mod sodium->@Redirect::sodium$beforeGenerateMipLevels(Lnet/minecraft/class_7764;Lnet/minecraft/class_1011;Lnet/minecraft/class_2960;)V with priority 1000, already redirected by mixins.iris.bettermipmaps.json:MixinTextureAtlasSprite from mod iris->@Redirect::iris$beforeGenerateMipLevels(Lnet/minecraft/class_7764;Lnet/minecraft/class_1011;Lnet/minecraft/class_2960;)V with priority 1000
[18:38:19] [Worker-Main-4/WARN]: @Redirect conflict. Skipping sodium.mixins.json:features.mipmaps.MixinSpriteContents from mod sodium->@Redirect::sodium$beforeGenerateMipLevels(Lnet/minecraft/class_7764;Lnet/minecraft/class_1011;Lnet/minecraft/class_2960;)V with priority 1000, already redirected by mixins.iris.bettermipmaps.json:MixinTextureAtlasSprite from mod iris->@Redirect::iris$beforeGenerateMipLevels(Lnet/minecraft/class_7764;Lnet/minecraft/class_1011;Lnet/minecraft/class_2960;)V with priority 1000
[18:38:19] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_7764 failed
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_7764 failed
	at net.minecraft.class_7948$class_7949.method_47674(class_7948.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_7954.method_47683(class_7954.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_7954.md2f47d1$iris$lambda$iris$modifyForEachAction$0$0(class_7954.java:529) ~[client-intermediary.jar:?]
	at java.util.TreeMap.forEach(TreeMap.java:1282) ~[?:?]
	at net.minecraft.class_7954.method_47673(class_7954.java:30) ~[client-intermediary.jar:?]
	at net.minecraft.class_7947.method_47669(class_7947.java:61) ~[client-intermediary.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.minecraft.class_7947.method_47667(class_7947.java:61) ~[client-intermediary.jar:?]
	at net.minecraft.class_7766.method_47660(class_7766.java:113) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
```

### Minecraft Version

1.19.4

### Iris Version

1.19.4-1.6.3

### Operating System

Windows 11

### What is your GPU?

NVidia GeForge

**Comment by SolidBlock-cn** [comment]
Duplicate with #1994
