### ISSUE TITLE
Crashes when starting

### ISSUE THREAD

**Issue by Danyko03** [IrisShaders/Iris#2000]
### Minecraft Version

1.19.4

### Iris Version

3.0.1

### Sodium Version

0.4.10

### Operating System

windows 11

### What is your GPU?

RTX 3060 mobile

### Java Version

Java 8 I guess

### Reproduction Steps

1. Used the Iris installer to setup the mod
2. Opened mc launcher and selected the iris installation
3. Game Crashes

### Crash Report file and latest.log

```shell
Uncaught exception in thread "main"
java.lang.RuntimeException: Could not create directory C:\Users\----\Downloads\iris-reserved\1.19.4
	at net.fabricmc.loader.impl.discovery.DirectoryModCandidateFinder.findCandidates(DirectoryModCandidateFinder.java:46)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:113)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:212)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.nio.file.NoSuchFileException: C:\Users\---\Downloads\iris-reserved\1.19.4
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:521)
	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
	at net.fabricmc.loader.impl.discovery.DirectoryModCandidateFinder.findCandidates(DirectoryModCandidateFinder.java:44)
	... 6 more
```

### Additional context

yes

**Comment by IMS212** [comment]
There was a bug with the installation, reinstall without changing the "installation directory" option in the installer.
