### ISSUE TITLE
some sort of a bug

### ISSUE THREAD

**Issue by Ianzhao071102** [IrisShaders/Iris#2002]
### Minecraft Version

1.19.4

### Iris Version

iris-mc1.19.4-1.6.1

### Sodium Version

sodium-fabric-mc1.19.4-0.4.11+build.26.jar

### Operating System

windows 10

### What is your GPU?

NVIDIA MX250

### Java Version

JAVA 18

### Reproduction Steps

Just joining a server,a and it crashes.....
LOL
lOl

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-05-21 16:05:31
Description: Unexpected error

java.lang.IllegalStateException: An invalid version of Sodium is installed, and the warning screen somehow didn't work. This is a bug! Please report it to the Iris developers.
	at net.minecraft.class_761.handler$bmc000$iris$beginLevelRender(class_761.java:6947)
	at net.minecraft.class_761.method_22710(class_761.java:1232)
	at net.minecraft.class_757.method_3188(class_757.java:1100)
	at net.minecraft.class_757.method_3192(class_757.java:872)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_761.handler$bmc000$iris$beginLevelRender(class_761.java:6947)
	at net.minecraft.class_761.method_22710(class_761.java:1232)
	at net.minecraft.class_757.method_3188(class_757.java:1100)

-- Affected level --
Details:
	All players: 22 total; [class_746['Ian071102'/4609625, l='ClientLevel', x=-2561.44, y=54.00, z=743.07], class_745['0pxnfp1v2y'/67, l='ClientLevel', x=-2551.50, y=52.00, z=735.50], class_745['69nqb35078'/1, l='ClientLevel', x=-2536.50, y=54.00, z=733.50], class_745['55nszf95w5'/2, l='ClientLevel', x=-2529.50, y=54.50, z=735.50], class_745['81jmjz9yw9'/7, l='ClientLevel', x=-2530.50, y=54.50, z=732.50], class_745['699v14vz12'/9, l='ClientLevel', x=-2532.50, y=54.50, z=730.50], class_745['bu95j73l12'/19, l='ClientLevel', x=-2543.00, y=52.00, z=730.00], class_745['6gsb26kqx3'/12, l='ClientLevel', x=-2532.50, y=54.00, z=738.50], class_745['31csk3460t'/15, l='ClientLevel', x=-2531.50, y=54.00, z=741.50], class_745['v8y7531b2h'/16, l='ClientLevel', x=-2532.50, y=54.00, z=750.50], class_745['r0y1hw86w0'/17, l='ClientLevel', x=-2534.50, y=54.00, z=736.50], class_745['8815i1n43n'/18, l='ClientLevel', x=-2531.50, y=54.00, z=747.50], class_745['8mz292sz7b'/5, l='ClientLevel', x=-2529.50, y=54.50, z=753.50], class_745['q785vzke39'/8, l='ClientLevel', x=-2530.50, y=54.50, z=756.50], class_745['1bsdvf41cl'/10, l='ClientLevel', x=-2534.50, y=54.00, z=752.50], class_745['331h3tllp5'/11, l='ClientLevel', x=-2536.50, y=54.00, z=755.50], class_745['4uxanx74de'/14, l='ClientLevel', x=-2532.50, y=54.50, z=758.50], class_745['2o4991ccwf'/68, l='ClientLevel', x=-2561.50, y=52.00, z=769.00], class_745['2so44i6o66'/3, l='ClientLevel', x=-2527.50, y=54.50, z=742.50], class_745['1m74zhf70w'/4, l='ClientLevel', x=-2528.50, y=54.50, z=750.50], class_745['pc979xw718'/6, l='ClientLevel', x=-2527.50, y=54.50, z=746.50], class_745['49n5s1kgx4'/13, l='ClientLevel', x=-2528.50, y=54.50, z=738.50]]
	Chunk stats: 16384, 169
	Level dimension: minecraft:overworld
	Level spawn location: World: (-2562,54,743), Section: (at 14,6,7 in -161,3,46; chunk contains blocks -2576,0,736 to -2561,255,751), Region: (-6,1; contains chunks -192,32 to -161,63, blocks -3072,0,512 to -2561,255,1023)
	Level time: 1187988607 game time, 111000 day time
	Server brand: Hypixel BungeeCord (1.3.20) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, fabric, moreberries:modifiedsweetberrybushmodel

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 18.0.2.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1237028128 bytes (1179 MiB) / 1962934272 bytes (1872 MiB) up to 6765412352 bytes (6452 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 12
	Microarchitecture: Whiskey Lake
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9b41
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8984
	Graphics card #1 name: NVIDIA GeForce MX250
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x1d13
	Graphics card #1 versionInfo: DriverVersion=31.0.15.2824
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: LPDDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: LPDDR3
	Virtual memory max (MB): 24404.49
	Virtual memory used (MB): 14071.09
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 43.54
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx6451m
	Fabric Mods: 
		additionalstructures: Additional Structures 4.1.1
		appleskin: AppleSkin 2.4.3+mc1.19.4
		architectury: Architectury 8.1.80
		bclib: BCLib 2.3.2
		betterend: Better End 3.2.1
		betterf3: BetterF3 6.0.1
		bettermineshafts: YUNG's Better Mineshafts 1.19.4-Fabric-3.4.0
			org_reflections_reflections: reflections 0.10.2
		betternether: Better Nether 8.2.1
		betterstrongholds: YUNG's Better Strongholds 1.19.4-Fabric-3.4.0
		boathud: BoatHud 1.1.3
		bottledair: Bottled Air 2.1
		carryon: Carry On 2.0.5.20
		chunky: Chunky 1.3.74
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.54
		cristellib: Cristel Lib 1.0.1
			blue_endless_jankson: jankson 1.2.1
		do_a_barrel_roll: Do a Barrel Roll 2.7.2+1.19.4
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
			cicada: CICADA 0.4.0
				com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
		elytraslot: Elytra Slot 6.2.1+1.19.4
		fabric-api: Fabric API 0.81.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.26+1e9487d2f4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.27+504944c8f4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.8+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.7+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.36+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.17+504944c8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.29+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.8+504944c8f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.46+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.56+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.11+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.0+c98e6b27f4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.16+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.2+504944c8f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.47+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.15+504944c8f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.5.1+76ba65ebf4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.54+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.34+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.19+504944c8f4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.7+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.34+504944c8f4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.32+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.17+1e9487d2f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.29+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.33+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.3+504944c8f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.41+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.32+504944c8f4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.3+504944c8f4
			fabric-networking-v0: Fabric Networking (v0) 0.3.43+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.5+504944c8f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.25+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.10+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.2+504944c8f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.7+ebc93ff3f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.2.0+ebc93ff3f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.40+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.30+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.23+504944c8f4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.43+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.3+504944c8f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.2+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.4+5ade3c38f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.47+3bd4ab0ff4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.22+504944c8f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.10+504944c8f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.0+80d07a0af4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.1.0+03ba59cef4
		fabric-language-kotlin: Fabric Language Kotlin 1.9.4+kotlin.1.8.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricloader: Fabric Loader 0.14.19
		geckolib: Geckolib 4.1.3
			com_eliotlash_mclib_mclib: mclib 20
		graveyard: The Graveyard 2.8
			omega-config: OmegaConfig 1.2.2-1.18.1
		guardvillagers: Guard Villagers Fabric 1.19.4-1.1.0
		inventoryhud: Inventory HUD + 3.4.12
		iris: Iris 1.6.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre12
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: Java HotSpot(TM) 64-Bit Server VM 18
		jei: Just Enough Items 13.1.0.9
		ksyxis: Ksyxis 1.1
		liquidbounce: LiquidBounce 1.0.0
		lithium: Lithium 0.11.1
		midnightlib: MidnightLib 1.3.0
		minecraft: Minecraft 1.19.4
		moreberries: More Berries 1.5.4
		neat: Neat 1.19.4-34-FABRIC
			fiber: fiber 0.23.0-2
		philipsruins: Philip`s ruins 1.19.4
		phosphor: Phosphor 0.8.1
		resolutioncontrol: ResolutionControl+ 1.19.4-3.0.0
		simple-armor-hud: Simple armor hud 1.19.4-1.3.0
		sodium: Sodium 0.4.11+build.26
		sodium-extra: Sodium Extra 0.4.19+mc1.19.3-build.101
			caffeineconfig: CaffeineConfig 1.1.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		stoneholm: Stoneholm 1.4.4
		t_and_t: Towns and Towers 1.10.2
		the_bumblezone: The Bumblezone - Fabric 6.7.4+1.19.4-fabric
			fake-player-api: Fake Player API 0.5.0
		trinkets: Trinkets 3.6.0
		vinery: Vinery 1.2.5
		xaerominimap: Xaero's Minimap 23.4.2
		yungsapi: YUNG's API 1.19.4-Fabric-3.10.1
			org_javassist_javassist: javassist 3.29.2-GA
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: 1.19.4-Fabric 0.14.19-OptiFine_I4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce MX250/PCIe/SSE2 GL version 3.3.0 NVIDIA 528.24, NVIDIA Corporation
	Window size: 2160x1334
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	CPU: 8x Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
```

**Comment by purple512** [comment]
Iris 1.6.1 requires Sodium 0.4.10.
