### ISSUE TITLE
Minecraft "bounding box" lines for entity hitboxes and structure blocks render black instead of normal

### ISSUE THREAD

**Issue by Reber01Good** [IrisShaders/Iris#2045]
### What happened?

Minecraft's "bounding boxes" for entity hitboxes and structure blocks render black when enabling shaders (complementary 4.7.2). I know this is caused by iris since after updating from 1.19 this started happening. I tested past versions of complementary shaders all the way down to 4.6 and it still occurs, leaving iris the only possible culprit. Please fix this since I work a lot with these lines and they are very hard to see. 

### Screenshots

Behaviour
![image](https://github.com/IrisShaders/Iris/assets/93145739/8fbcff85-c6cf-4301-8362-e543884ae06d)

Expected behaviour:
![image](https://github.com/IrisShaders/Iris/assets/93145739/542230c3-a61e-4d72-b002-442af4654525)

Behaviour on 1.19 with iris 1.5.2 (not that the structure block lines are missing the red/green/blue colors)
![image](https://github.com/IrisShaders/Iris/assets/93145739/52dd10c4-8f98-4050-8940-ea6ed2d59891)

### Log output

[log.txt](https://github.com/IrisShaders/Iris/files/11991362/log.txt)

### Minecraft Version

1.20.1

### Iris Version

1.6.4

### Operating System

Windows 11

### What is your GPU?

RTX 2060 Mobile

### Additional context

The only relevant section i found in the log:

java.lang.Exception: Variable shadows build in uniform: rainStrength
	at net.coderbot.iris.uniforms.custom.CustomUniforms.addVariable(CustomUniforms.java:175) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms.<init>(CustomUniforms.java:56) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:317) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:329) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:254) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:676) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.Iris.reload(Iris.java:618) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.apiimpl.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:28) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:585) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.lambda$init$3(ShaderPackScreen.java:243) ~[iris-mc1.20-1.6.4.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.method_25402(ShaderPackScreen.java:197) ~[iris-mc1.20-1.6.4.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:212) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:288) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1241) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
[19:46:56] [Render thread/WARN]: [Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[19:46:59] [Render thread/INFO]: Destroying pipeline OVERWORLD
[19:46:59] [Render thread/INFO]: Profile: HIGH (+0 options changed by user)
[19:47:00] [Render thread/INFO]: Using shaderpack: ComplementaryShaders_v4.6.zip
[19:47:00] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[19:47:00] [Render thread/INFO]: Starting custom uniform resolving
[19:47:00] [Render thread/WARN]: Failed to resolve uniform rainStrength, reason: Variable shadows build in uniform: rainStrength ( = FunctionCall{clamp {[Id{rainStrength}, Number{0.0}, Number{1.0}]} })
java.lang.Exception: Variable shadows build in uniform: rainStrength
	at net.coderbot.iris.uniforms.custom.CustomUniforms.addVariable(CustomUniforms.java:175) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms.<init>(CustomUniforms.java:56) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:317) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:329) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:254) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:676) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.Iris.reload(Iris.java:618) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.apiimpl.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:28) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:585) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.lambda$init$3(ShaderPackScreen.java:243) ~[iris-mc1.20-1.6.4.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.method_25402(ShaderPackScreen.java:197) ~[iris-mc1.20-1.6.4.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:212) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:288) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1241) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
[19:47:00] [Render thread/WARN]: [Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[19:47:20] [Render thread/INFO]: [System] [CHAT] [Debug]: Hitboxes: shown
[19:47:21] [Render thread/INFO]: [System] [CHAT] [Debug]: Hitboxes: hidden
[19:47:29] [Render thread/INFO]: Destroying pipeline OVERWORLD
[19:47:29] [Render thread/INFO]: Profile: Custom (+110 options changed by user)
[19:47:30] [Render thread/INFO]: Using shaderpack: ComplementaryShaders_v4.7.2.zip
[19:47:30] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[19:47:30] [Render thread/INFO]: Starting custom uniform resolving
[19:47:30] [Render thread/WARN]: Failed to resolve uniform rainStrength, reason: Variable shadows build in uniform: rainStrength ( = FunctionCall{clamp {[Id{rainStrength}, Number{0.0}, Number{1.0}]} })
java.lang.Exception: Variable shadows build in uniform: rainStrength
	at net.coderbot.iris.uniforms.custom.CustomUniforms.addVariable(CustomUniforms.java:175) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms.<init>(CustomUniforms.java:56) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:317) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:329) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:254) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:676) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.Iris.reload(Iris.java:618) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.apiimpl.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:28) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:585) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.lambda$init$3(ShaderPackScreen.java:243) ~[iris-mc1.20-1.6.4.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.method_25402(ShaderPackScreen.java:197) ~[iris-mc1.20-1.6.4.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:288) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1241) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]

More errors (all of the output when disabling and enabling shaders):

[20:05:53] [Render thread/INFO]: Shaders are disabled
[20:05:53] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[20:05:53] [Render thread/INFO]: Stopping worker threads
[20:05:53] [Render thread/INFO]: Started 6 worker threads
[20:05:53] [Render thread/INFO]: [System] [CHAT] Shaders disabled!
[20:05:53] [Render thread/INFO]: Destroying pipeline OVERWORLD
[20:05:53] [Render thread/INFO]: Profile: Custom (+110 options changed by user)
[20:05:54] [Render thread/INFO]: Using shaderpack: ComplementaryShaders_v4.7.2.zip
[20:05:54] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[20:05:54] [Render thread/INFO]: Starting custom uniform resolving
[20:05:54] [Render thread/WARN]: Failed to resolve uniform rainStrength, reason: Variable shadows build in uniform: rainStrength ( = FunctionCall{clamp {[Id{rainStrength}, Number{0.0}, Number{1.0}]} })
java.lang.Exception: Variable shadows build in uniform: rainStrength
	at net.coderbot.iris.uniforms.custom.CustomUniforms.addVariable(CustomUniforms.java:175) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms.<init>(CustomUniforms.java:56) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:317) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:329) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:254) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:676) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.Iris.reload(Iris.java:618) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.Iris.toggleShaders(Iris.java:275) ~[iris-mc1.20-1.6.4.jar:?]
	at net.coderbot.iris.Iris.handleKeybinds(Iris.java:256) ~[iris-mc1.20-1.6.4.jar:?]
	at net.minecraft.class_310.handler$bkf003$iris$onTick(class_310.java:11012) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1957) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
[20:05:54] [Render thread/WARN]: [Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[20:05:55] [Render thread/INFO]: Stopping worker threads
[20:05:55] [Render thread/INFO]: Started 6 worker threads
[20:05:55] [Render thread/INFO]: [System] [CHAT] Toggled shaders to ComplementaryShaders_v4.7.2.zip!

**Comment by Reber01Good** [comment]
Updated issue with my discovery regarding night vision

**Comment by Lolothepro** [comment]
![image](https://github.com/IrisShaders/Iris/assets/68275908/d4dec6c4-fa72-410f-8c7d-fab0c8d984aa)

**Comment by Reber01Good** [comment]
Well that sucks

**Comment by EminGT** [comment]
It doesn't make sense to declare this as a shader issue when Optifine and older Iris work perfectly fine.
