### ISSUE TITLE
Crash when joining any world - singleplayer or multiplayer

### ISSUE THREAD

**Issue by adamcockell1** [IrisShaders/Iris#2097]
### Minecraft Version

Minecraft 1.20.1

### Iris Version

iris-mc1.20.1-1.6.7.jar

### Sodium Version

sodium-fabric-mc1.20.1-0.5.1.jar

### Operating System

Windows 10

### What is your GPU?

AMD Radeon RX 5700XT

### Java Version

Java 16

### Reproduction Steps

1. Try to load into world (singleplayer or multiplayer)

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Don't do that.

Time: 2023-08-13 22:24:44
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_31548()" because "this.field_3712.field_1724" is null
	at net.minecraft.class_636.method_2911(class_636.java:308)
	at net.minecraft.class_636.method_2927(class_636.java:291)
	at net.minecraft.class_310.method_1574(class_310.java:1853)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_636.method_2911(class_636.java:308)
	at net.minecraft.class_636.method_2927(class_636.java:291)

-- Affected level --
Details:
	All players: 55 total; [class_745['Draven29'/5423912, l='ClientLevel', x=-52.50, y=97.00, z=0.50], class_745['Jery'/5424117, l='ClientLevel', x=-52.50, y=97.00, z=0.50], class_745['_chili_cat'/5424316, l='ClientLevel', x=-52.50, y=97.00, z=0.50], class_745['Pavlov_TAS'/5424691, l='ClientLevel', x=-52.50, y=97.00, z=0.50], class_745['lhe_wp'/5424707, l='ClientLevel', x=-53.28, y=94.00, z=8.28], class_745['Fujitakuya'/5424709, l='ClientLevel', x=-52.50, y=97.00, z=0.50], class_745['hvhalkis666'/5424730, l='ClientLevel', x=-52.50, y=97.00, z=0.50], class_745['Senor_Trump'/5424743, l='ClientLevel', x=-52.50, y=97.00, z=0.50], class_745['7vp744ko14'/331, l='ClientLevel', x=-54.00, y=94.50, z=10.00], class_745['x98percentmilk'/5424024, l='ClientLevel', x=-41.13, y=100.34, z=12.22], class_745['Mung_ga'/5424131, l='ClientLevel', x=-32.63, y=92.00, z=2.47], class_745['Jikrab'/5424370, l='ClientLevel', x=-37.97, y=97.00, z=1.97], class_745['9p665c5d4i'/184, l='ClientLevel', x=-33.50, y=93.00, z=22.50], class_745['65496j63sy'/367, l='ClientLevel', x=-44.50, y=92.00, z=25.50], class_745['z8291c0s67'/187, l='ClientLevel', x=-52.50, y=92.00, z=28.50], class_745['yukichan9290'/5411885, l='ClientLevel', x=-68.50, y=135.22, z=-2.66], class_745['fkj3912km7'/186, l='ClientLevel', x=-54.00, y=94.50, z=-9.00], class_745['faziym'/5423874, l='ClientLevel', x=-39.56, y=92.00, z=-8.78], class_745['Psychosmia'/5424150, l='ClientLevel', x=-43.06, y=92.00, z=-6.31], class_745['Masny_mieciu'/5424657, l='ClientLevel', x=-44.16, y=95.47, z=-3.25], class_745['IKIts12Inch'/5424715, l='ClientLevel', x=-47.59, y=97.00, z=-5.25], class_745['881253gqri'/175, l='ClientLevel', x=-25.50, y=93.00, z=-1.50], class_745['z84c75680u'/178, l='ClientLevel', x=-25.50, y=93.00, z=-5.50], class_745['u52dw8t0m8'/180, l='ClientLevel', x=-27.50, y=93.00, z=-13.50], class_745['3a78ajnmb5'/182, l='ClientLevel', x=-26.50, y=93.00, z=-9.50], class_745['Dxceitful'/5424431, l='ClientLevel', x=-24.97, y=92.00, z=13.13], class_745['0i307tsmg5'/176, l='ClientLevel', x=-25.50, y=93.00, z=2.50], class_745['kwe06u1r6k'/177, l='ClientLevel', x=-25.50, y=93.00, z=6.50], class_745['4r61d86495'/181, l='ClientLevel', x=-27.50, y=93.00, z=14.50], class_745['fug19x2353'/183, l='ClientLevel', x=-26.50, y=93.00, z=10.50], class_745['3ct8v63l35'/185, l='ClientLevel', x=-29.50, y=93.00, z=18.50], class_745['udnrqic5f5'/201, l='ClientLevel', x=-39.50, y=87.00, z=42.50], class_745['ToeFeaster'/5424392, l='ClientLevel', x=-34.75, y=99.50, z=-23.28], class_745['LXYZO'/5424491, l='ClientLevel', x=-37.50, y=92.00, z=-20.50], class_745['50269z16r2'/258, l='ClientLevel', x=-35.50, y=93.00, z=-22.50], class_745['gcil1x88ti'/179, l='ClientLevel', x=-29.50, y=93.00, z=-17.50], class_745['joooyyy'/5424433, l='ClientLevel', x=-3.06, y=67.53, z=4.34], class_745['MommyMiwkies'/5423957, l='ClientLevel', x=-43.47, y=88.00, z=48.69], class_745['qn4xk6m06o'/202, l='ClientLevel', x=-45.50, y=87.00, z=55.50], class_745['85i9d6t523'/204, l='ClientLevel', x=-52.50, y=87.00, z=51.50], class_745['j1v09j2x10'/274, l='ClientLevel', x=15.50, y=64.00, z=-30.50], class_745['gj2p3b4d20'/190, l='ClientLevel', x=8.50, y=64.00, z=3.50], class_745['NightmareAYK'/5424248, l='ClientLevel', x=1.50, y=64.00, z=20.94], class_745['PeachArt5342415'/5424296, l='ClientLevel', x=-22.88, y=131.72, z=78.78], class_745['3pok91or4h'/203, l='ClientLevel', x=-52.50, y=86.00, z=66.59], class_745['smhquicke'/5424755, l='ClientLevel', x=-52.50, y=97.00, z=0.50], class_745['FreshBerries'/5424099, l='ClientLevel', x=15.66, y=64.75, z=-15.28], class_745['00e0v6lw7n'/273, l='ClientLevel', x=-61.50, y=79.00, z=-56.50], class_745['j5jm399699'/272, l='ClientLevel', x=23.50, y=62.00, z=-35.50], class_745['sallyluciano'/5423409, l='ClientLevel', x=16.44, y=64.50, z=11.72], class_745['ww7929d4b4'/261, l='ClientLevel', x=18.50, y=31.00, z=1.50], class_745['MONKEYEBOY'/5424435, l='ClientLevel', x=-60.00, y=83.00, z=83.59], class_745['StealthyBananaYT'/5424762, l='ClientLevel', x=-52.50, y=97.00, z=0.50], class_745['LinaStarPrincess'/5424540, l='ClientLevel', x=-48.06, y=93.00, z=-7.09], class_745['Aiden_436'/5424738, l='ClientLevel', x=-56.72, y=94.00, z=1.28]]
	Chunk stats: 16384, 115
	Level dimension: minecraft:overworld
	Level spawn location: World: (-53,97,0), Section: (at 11,1,0 in -4,6,0; chunk contains blocks -64,0,0 to -49,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 182791391 game time, 32000 day time
	Server brand: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.class_746.method_3135()" because "this.field_3729.field_1724" is null
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/Hypixel+.zip, fabric, __MoreMcmeta Internal__

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 979741992 bytes (934 MiB) / 1644167168 bytes (1568 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon RX 5700 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x731f
	Graphics card #0 versionInfo: DriverVersion=31.0.21001.45002
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 23722.24
	Virtual memory used (MB): 13539.59
	Swap memory total (MB): 7424.00
	Swap memory used (MB): 51.20
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		animatica: Animatica 0.6+1.20
		cem: Custom Entity Models 0.8.0
		citresewn: CIT Resewn 1.1.3+1.20
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.20
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.65
		continuity: Continuity 3.0.0-beta.3+1.20.1
		dynamicfps: Dynamic FPS 2.4.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		entity_texture_features: Entity Texture Features 4.5.0
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		fabric-api: Fabric API 0.86.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.62+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.1+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.52+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.9+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.49+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.19+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.1+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.1+9386d8a777
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.1+9172968c77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.28+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.8+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		immediatelyfast: ImmediatelyFast 1.1.27+1.20.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.9
			net_lenni0451_reflect: Reflect 1.2.1
		indium: Indium 1.0.24+mc1.20.1
		iris: Iris 1.6.7
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		jsonem: JsonEM 0.2.1+1.20
		lambdynlights: LambDynamicLights 2.3.1+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.0+1.20
		libipn: libIPN 3.0.2
		lithium: Lithium 0.11.2
		memoryleakfix: Memory Leak Fix 1.1.1
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.2.1
		moreculling: More Culling 1.20.1-0.19.0
			conditional-mixin: conditional mixin 0.3.2
		moremcmeta: MoreMcmeta 1.20.1-4.2.0
			moremcmeta_animation_plugin: MoreMcmeta Animation Plugin 1.20.1-1.0.0
			moremcmeta_json_parser_plugin: MoreMcmeta JSON Parser Plugin 1.20.1-1.1.0
			moremcmeta_properties_parser_plugin: MoreMcmeta Properties Parser Plugin 1.20.1-1.1.2
			moremcmeta_texture_plugin: MoreMcmeta Texture Plugin 1.20.1-1.0.0
		reeses-sodium-options: Reese's Sodium Options 1.6.4+mc1.20.1-build.94
		skyblocker: Skyblocker 1.11.1+1.20.1
			com_github_cbyrneee_betterinject: BetterInject 0.1.3
			com_logisticscraft_occlusionculling: occlusionculling 0.0.7-SNAPSHOT
			meteordevelopment_discord-ipc: discord-ipc 1.1
			org_eclipse_jgit_org_eclipse_jgit: org.eclipse.jgit 6.4.0.202211300538-r
			renderer: Renderer 1.0
				satin: Satin 1.13.0
		sodium: Sodium 0.5.1
		sodium-extra: Sodium Extra 0.5.0+mc1.20.1-build.111
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		tooltipscroll: Tooltip Scroll v1.2.5-1.20
		yet_another_config_lib_v3: YetAnotherConfigLib 3.1.0+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
		zoomify: Zoomify 2.11.0
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.4.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.21-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon RX 5700 XT GL version 3.2.0 Core Profile Context 23.7.1.230626, ATI Technologies Inc.
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, file/Hypixel+.zip, fabric
	Current Language: en_us
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor
```

**Comment by purple512** [comment]
You've got Sodium-dependent mods (Reese's Sodium options, Sodium Extra) that have not updated for Sodium 0.5.1. If you're going to update Sodium, you have to either disable all that other stuff or wait until it's updated.

**Comment by adamcockell1** [comment]
ah i see, apologies for the false issue!
