### ISSUE TITLE
Intense stuttering with shaders enabled and looking at shadows

### ISSUE THREAD

**Issue by brycerobertson** [IrisShaders/Iris#2105]
### What happened?

With just Iris and Sodium installed, enable a shader pack and looking at an area where there are lots of shadows, or at sunset or sunrise, there is intense stuttering in fps, which can be felt in the mouse movements quite painfully, the framerate stuttering seems to disappear when shadows are decreased in length or number.

When sitting through a sunrise with the stuttering to get a clean log file, I noticed my gpu jumping from 50% usage to 70%-100% usage every few seconds.

In the screenshots I have my fps locked at 160 but this behaviour is the same with fps unlocked, the first screenshot is looking away from the sun at sunrise and the second is looking at the sun at sunrise, so looking at shadows and away.

I have also tested and verified with other shaders, but am using complementary v4 in the screenshots.

### Screenshots

![2023-08-18_09 23 42](https://github.com/IrisShaders/Iris/assets/59671638/4f810071-8911-4558-b576-b9cfb3226c7a)
![2023-08-18_09 30 54](https://github.com/IrisShaders/Iris/assets/59671638/2c46342d-04b6-48fe-8b2d-e795dc7f4afb)

### Log output

[09:36:15] [main/INFO]: Loading Minecraft 1.20.1 with Quilt Loader 0.19.2
[09:36:15] [main/INFO]: Loading mappings: jar:file:/C:/Tools/Games/Prism%20Launcher/libraries/net/fabricmc/intermediary/1.20.1/intermediary-1.20.1.jar!/mappings/mappings.tiny
[09:36:16] [Quilt Loader Active User Beacon/WARN]: Failed to notify the beacon - trying again next launch.
java.net.UnknownHostException: beacon.quiltmc.org
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:572) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?]
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:533) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:638) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308) ~[?:?]
	at org.quiltmc.loader.impl.ActiveUserBeacon.runOnThread(ActiveUserBeacon.java:110) ~[quilt-loader-0.19.2.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:36:16] [main/INFO]: Loading 13 mods:
| Index | Mod                                   | ID                                  | Version           | Type    | File Hash (SHA-1)                        | File(s)                                                                                         | Sub-File                                                                 |
|------:|---------------------------------------|-------------------------------------|-------------------|---------|------------------------------------------|-------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------|
|     6 | antlr4-runtime                        | org_antlr_antlr4-runtime            | 4.11.1            | Fabric  | 942b1b3ea44a7880b55e3896d398a6c44a3e65be | <mods>\iris-mc1.20.1-1.6.8.jar                                                                  | /META-INF/jars/antlr4-runtime-4.11.1.jar                                 |
|     5 | Fabric API Base                       | fabric-api-base                     | 0.4.29+b04edc7a77 | Fabric  | 0bd317776db069f7ed1035f6b8ef628ebbe7779d | <mods>\sodium-fabric-mc1.20.1-0.5.2.jar                                                         | /META-INF/jars/fabric-api-base-0.4.29+b04edc7a77.jar                     |
|     0 | Fabric Key Binding API (v1)           | fabric-key-binding-api-v1           | 1.0.23+aaaf9d332d | Fabric  | 942b1b3ea44a7880b55e3896d398a6c44a3e65be | <mods>\iris-mc1.20.1-1.6.8.jar                                                                  | /META-INF/jars/fabric-key-binding-api-v1-1.0.23+aaaf9d332d.jar           |
|     2 | Fabric Rendering Data Attachment (v1) | fabric-rendering-data-attachment-v1 | 0.3.33+b3afc78b77 | Fabric  | 0bd317776db069f7ed1035f6b8ef628ebbe7779d | <mods>\sodium-fabric-mc1.20.1-0.5.2.jar                                                         | /META-INF/jars/fabric-rendering-data-attachment-v1-0.3.33+b3afc78b77.jar |
|     4 | Fabric Rendering Fluids (v1)          | fabric-rendering-fluids-v1          | 3.0.26+b3afc78b77 | Fabric  | 0bd317776db069f7ed1035f6b8ef628ebbe7779d | <mods>\sodium-fabric-mc1.20.1-0.5.2.jar                                                         | /META-INF/jars/fabric-rendering-fluids-v1-3.0.26+b3afc78b77.jar          |
|     9 | Fabric Resource Loader (v0)           | fabric-resource-loader-v0           | 0.11.8+e3d6ed2577 | Fabric  | 0bd317776db069f7ed1035f6b8ef628ebbe7779d | <mods>\sodium-fabric-mc1.20.1-0.5.2.jar                                                         | /META-INF/jars/fabric-resource-loader-v0-0.11.8+e3d6ed2577.jar           |
|     1 | glsl-transformer                      | io_github_douira_glsl-transformer   | 2.0.0-pre13       | Fabric  | 942b1b3ea44a7880b55e3896d398a6c44a3e65be | <mods>\iris-mc1.20.1-1.6.8.jar                                                                  | /META-INF/jars/glsl-transformer-2.0.0-pre13.jar                          |
|    10 | Iris                                  | iris                                | 1.6.8             | Fabric  | 942b1b3ea44a7880b55e3896d398a6c44a3e65be | <mods>\iris-mc1.20.1-1.6.8.jar                                                                  |                                                                          |
|     3 | jcpp                                  | org_anarres_jcpp                    | 1.4.14            | Fabric  | 942b1b3ea44a7880b55e3896d398a6c44a3e65be | <mods>\iris-mc1.20.1-1.6.8.jar                                                                  | /META-INF/jars/jcpp-1.4.14.jar                                           |
|    12 | Minecraft                             | minecraft                           | 1.20.1            | Builtin | a882e2cad29d8bfa674f8dbe850a5083b2b14a96 | <game>\.cache\quilt_loader\remappedJars\minecraft-1.20.1-0.19.2\client-intermediary.jar         |                                                                          |
|    11 | OpenJDK 64-Bit Server VM              | java                                | 17                | Builtin |                                          | C:\Program Files\Microsoft\jdk-17.0.8.7-hotspot                                                 |                                                                          |
|     7 | Quilt Loader                          | quilt_loader                        | 0.19.2            | Quilt   | e6f731f8b29707c37dc9c662219faf5daabedafc | C:\Tools\Games\Prism Launcher\libraries\org\quiltmc\quilt-loader\0.19.2\quilt-loader-0.19.2.jar |                                                                          |
|     8 | Sodium                                | sodium                              | 0.5.2             | Fabric  | 0bd317776db069f7ed1035f6b8ef628ebbe7779d | <mods>\sodium-fabric-mc1.20.1-0.5.2.jar                                                         |                                                                          |
|------:|---------------------------------------|-------------------------------------|-------------------|---------|------------------------------------------|-------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------|
Mod Table Version: 2
Plugin Types: {quilted_fabric_loader=[Fabric], quilt_loader=[Quilt, Builtin]}
[09:36:16] [QuiltClassPath ZipScanner#1/INFO]: Took 63661us to scan /
[09:36:16] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Tools/Games/Prism%20Launcher/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Quilt Env=CLIENT
[09:36:16] [main/INFO]: Compatibility level set to JAVA_16
[09:36:16] [main/INFO]: Compatibility level set to JAVA_17
[09:36:16] [main/INFO]: Loaded configuration file for Sodium: 41 options available, 3 override(s) found
[09:36:16] [main/WARN]: Force-disabling mixin 'features.render.entity.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[09:36:16] [main/WARN]: Force-disabling mixin 'features.render.entity.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[09:36:16] [main/WARN]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[09:36:16] [main/WARN]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[09:36:16] [main/WARN]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [iris]) disables it and children
[09:36:16] [main/WARN]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[09:36:16] [main/WARN]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[09:36:16] [main/WARN]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[09:36:17] [main/INFO]: Searching for graphics cards...
[09:36:17] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=AMD, name=AMD Radeon RX 7900 XTX, version=DriverVersion=31.0.21023.2010]
[09:36:19] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 128 milliseconds
[09:36:21] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[09:36:21] [Render thread/INFO]: Setting user: Nymphicus
[09:36:21] [ForkJoinPool.commonPool-worker-1/WARN]: [Iris Update Check] Cached update file detected, using that!
[09:36:21] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 build 7
[09:36:21] [Render thread/INFO]: OpenGL Vendor: ATI Technologies Inc.
[09:36:21] [Render thread/INFO]: OpenGL Renderer: AMD Radeon RX 7900 XTX
[09:36:21] [Render thread/INFO]: OpenGL Version: 3.2.0 Core Profile Context 23.7.2.230718
[09:36:21] [Render thread/INFO]: Debug functionality is disabled.
[09:36:21] [Render thread/INFO]: ARB_direct_state_access detected, enabling DSA.
[09:36:21] [Render thread/INFO]: Profile: Custom (+2 options changed by user)
[09:36:22] [Render thread/INFO]: Using shaderpack: Complementary v4
[09:36:22] [Render thread/INFO]: Hardware information:
[09:36:22] [Render thread/INFO]: CPU: 32x AMD Ryzen 9 5950X 16-Core Processor 
[09:36:22] [Render thread/INFO]: GPU: AMD Radeon RX 7900 XTX (Supports OpenGL 3.2.0 Core Profile Context 23.7.2.230718)
[09:36:22] [Render thread/INFO]: OS: Windows 10 (10.0)
[09:36:22] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (fabric-key-binding-api-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-api-base, quilt_loader, sodium, fabric-resource-loader-v0, iris)
[09:36:23] [Worker-Main-7/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[09:36:23] [Render thread/INFO]: Creating pipeline for dimension NamespacedId{namespace='minecraft', name='overworld'}
[09:36:23] [Render thread/INFO]: Starting custom uniform resolving
[09:36:23] [Render thread/WARN]: Failed to resolve uniform rainStrength, reason: Variable shadows build in uniform: rainStrength ( = FunctionCall{clamp {[Id{rainStrength}, Number{0.0}, Number{1.0}]} })
java.lang.Exception: Variable shadows build in uniform: rainStrength
	at net.coderbot.iris.uniforms.custom.CustomUniforms.addVariable(CustomUniforms.java:175) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms.<init>(CustomUniforms.java:56) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:317) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:329) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:254) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:661) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:35) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.Iris.onLoadingComplete(Iris.java:226) ~[transformed-mod-iris.i0:0/:?]
	at net.minecraft.class_442.handler$zeo000$iris$showSodiumIncompatScreen(class_442.java:566) ~[transformed-mod-minecraft-v1.20.1.jar:?]
	at net.minecraft.class_442.method_25426(class_442.java:156) ~[transformed-mod-minecraft-v1.20.1.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:297) ~[transformed-mod-minecraft-v1.20.1.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1080) ~[transformed-mod-minecraft-v1.20.1.jar:?]
	at net.minecraft.class_310.method_51251(class_310.java:690) ~[transformed-mod-minecraft-v1.20.1.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:674) ~[transformed-mod-minecraft-v1.20.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[minecraft-1.20.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.19.2.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
[09:36:24] [Render thread/WARN]: [Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[09:36:26] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[09:36:26] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[09:36:26] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (Realtek(R) Audio)
[09:36:26] [Render thread/INFO]: Sound engine started
[09:36:26] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[09:36:26] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[09:36:26] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[09:36:26] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[09:36:26] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[09:36:26] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[09:36:26] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[09:36:26] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[09:36:26] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[09:36:26] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[09:36:26] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[09:36:26] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[09:36:26] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[09:36:31] [Render thread/INFO]: Loaded 7 recipes
[09:36:31] [Render thread/INFO]: Loaded 1271 advancements
[09:36:31] [Server thread/INFO]: Starting integrated minecraft server version 1.20.1
[09:36:31] [Server thread/INFO]: Generating keypair
[09:36:32] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[09:36:34] [Render thread/INFO]: Preparing spawn area: 0%
[09:36:34] [Render thread/INFO]: Preparing spawn area: 0%
[09:36:34] [Render thread/INFO]: Preparing spawn area: 0%
[09:36:34] [Render thread/INFO]: Preparing spawn area: 0%
[09:36:34] [Render thread/INFO]: Preparing spawn area: 23%
[09:36:34] [Render thread/INFO]: Time elapsed: 2276 ms
[09:36:34] [Server thread/INFO]: Changing view distance to 20, from 10
[09:36:34] [Server thread/INFO]: Changing simulation distance to 12, from 0
[09:36:35] [Server thread/INFO]: Nymphicus[local:E:1015b35d] logged in with entity id 89 at (-1287.1563718331556, 103.0, -454.9963238103354)
[09:36:35] [Server thread/INFO]: Nymphicus joined the game
[09:36:35] [Render thread/INFO]: Reloading pipeline on dimension change: NamespacedId{namespace='minecraft', name='overworld'} => NamespacedId{namespace='minecraft', name='overworld'}
[09:36:35] [Render thread/INFO]: Destroying pipeline NamespacedId{namespace='minecraft', name='overworld'}
[09:36:35] [Render thread/INFO]: Creating pipeline for dimension NamespacedId{namespace='minecraft', name='overworld'}
[09:36:35] [Render thread/INFO]: Starting custom uniform resolving
[09:36:35] [Render thread/WARN]: Failed to resolve uniform rainStrength, reason: Variable shadows build in uniform: rainStrength ( = FunctionCall{clamp {[Id{rainStrength}, Number{0.0}, Number{1.0}]} })
java.lang.Exception: Variable shadows build in uniform: rainStrength
	at net.coderbot.iris.uniforms.custom.CustomUniforms.addVariable(CustomUniforms.java:175) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms.<init>(CustomUniforms.java:56) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:317) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:329) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:254) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:661) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:35) ~[transformed-mod-iris.i0:0/:?]
	at net.minecraft.class_310.handler$zeh000$iris$resetPipeline(class_310.java:4543) ~[transformed-mod-minecraft-v1.20.1.jar:?]
	at net.minecraft.class_310.method_18097(class_310.java) ~[transformed-mod-minecraft-v1.20.1.jar:?]
	at net.minecraft.class_310.method_1481(class_310.java:2147) ~[transformed-mod-minecraft-v1.20.1.jar:?]
	at net.minecraft.class_634.method_11120(class_634.java:424) ~[transformed-mod-minecraft-v1.20.1.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:95) ~[transformed-mod-minecraft-v1.20.1.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:25) ~[transformed-mod-minecraft-v1.20.1.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[transformed-mod-minecraft-v1.20.1.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[transformed-mod-minecraft-v1.20.1.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[transformed-mod-minecraft-v1.20.1.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[transformed-mod-minecraft-v1.20.1.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[transformed-mod-minecraft-v1.20.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[transformed-mod-minecraft-v1.20.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[transformed-mod-minecraft-v1.20.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.19.2.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
[09:36:35] [Render thread/WARN]: [Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[09:36:36] [Render thread/INFO]: Started 10 worker threads
[09:36:36] [Render thread/INFO]: Loaded 162 advancements
[09:36:37] [Render thread/WARN]: Shader clouds could not find uniform named ModelViewMat in the specified shader program.
[09:36:37] [Render thread/WARN]: Shader clouds could not find uniform named ProjMat in the specified shader program.
[09:36:37] [Render thread/WARN]: Shader clouds could not find uniform named ColorModulator in the specified shader program.
[09:36:37] [Render thread/WARN]: Shader clouds could not find uniform named FogStart in the specified shader program.
[09:36:37] [Render thread/WARN]: Shader clouds could not find uniform named FogEnd in the specified shader program.
[09:36:37] [Render thread/WARN]: Shader clouds could not find uniform named FogColor in the specified shader program.
[09:38:30] [Server thread/INFO]: Saving and pausing game...
[09:38:30] [Server thread/INFO]: Saving chunks for level 'ServerLevel[meinkraft]'/minecraft:overworld
[09:38:30] [Server thread/INFO]: Saving chunks for level 'ServerLevel[meinkraft]'/minecraft:the_end
[09:38:30] [Server thread/INFO]: Saving chunks for level 'ServerLevel[meinkraft]'/minecraft:the_nether
[09:38:31] [Server thread/INFO]: Nymphicus lost connection: Disconnected
[09:38:31] [Server thread/INFO]: Nymphicus left the game
[09:38:31] [Server thread/INFO]: Stopping singleplayer server as player logged out
[09:38:31] [Server thread/INFO]: Stopping server
[09:38:31] [Server thread/INFO]: Saving players
[09:38:31] [Server thread/INFO]: Saving worlds
[09:38:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[meinkraft]'/minecraft:overworld
[09:38:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[meinkraft]'/minecraft:the_end
[09:38:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[meinkraft]'/minecraft:the_nether
[09:38:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (meinkraft): All chunks are saved
[09:38:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[09:38:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[09:38:31] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[09:38:31] [Render thread/INFO]: Stopping worker threads
[09:38:32] [Render thread/INFO]: Stopping!

### Minecraft Version

1.20.1

### Iris Version

1.6.8

### Operating System

Windows 10

### What is your GPU?

AMD Radeon 7900xtx

**Comment by coderbot16** [comment]
This is because looking at shadows results in a much higher rendering load, because the shadow map renderer is able to cull many more chunks when you are looking away from the shadows and looking at the sun. When you look at the sun, Iris can skip rendering the chunks behind you into the shadow map since you cannot see the shadows that are cast by those chunks anyways. But when you look in the opposite direction to the sun, Iris isn't able to skip rendering those chunks which means there is a much higher load on the renderer.
