### ISSUE TITLE
Failed to resolve uniform rainStrength

### ISSUE THREAD

**Issue by AndroWolf** [IrisShaders/Iris#2116]
### What happened?

mods:
	- alternate-current 1.7.0
	- better_log4j_config 1.2.0
	- fabric-api 0.87.0+1.20.1
	- fabricloader 0.14.22
	- indium 1.0.25+mc1.20.1
	- iris 1.6.8
	- java 17
	- lithium 0.11.2
	- minecraft 1.20.1
	- sodium 0.5.2
	- starlight 1.1.2+fabric.dbc156f

### Log output

[07:32:49] [Render thread/WARN] (Iris) Failed to resolve uniform rainStrength, reason: Variable shadows build in uniform: rainStrength ( = FunctionCall{clamp {[Id{rainStrength}, Number{0.0}, Number{1.0}]} })
java.lang.Exception: Variable shadows build in uniform: rainStrength
	at net.coderbot.iris.uniforms.custom.CustomUniforms.addVariable(CustomUniforms.java:175) ~[iris-mc1.20.1-1.6.8.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms.<init>(CustomUniforms.java:56) ~[iris-mc1.20.1-1.6.8.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:317) ~[iris-mc1.20.1-1.6.8.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:329) ~[iris-mc1.20.1-1.6.8.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:254) ~[iris-mc1.20.1-1.6.8.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:661) ~[iris-mc1.20.1-1.6.8.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:35) ~[iris-mc1.20.1-1.6.8.jar:?]
	at net.minecraft.class_310.handler$zmf000$iris$resetPipeline(class_310.java:7043) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_18097(class_310.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1481(class_310.java:2147) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11120(class_634.java:424) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:95) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:25) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]

### Minecraft Version

1.20.1

### Iris Version

iris-mc1.20.1-1.6.8

### Operating System

win11

### What is your GPU?

nvidia4090

**Comment by IMS212** [comment]
Not a bug.

**Comment by AndroWolf** [comment]
what is it then?
