### ISSUE TITLE
Crash on 1.20.1 with shaders

### ISSUE THREAD

**Issue by Fleepe** [IrisShaders/Iris#2119]
### Minecraft Version

Minecraft 1.20.1

### Iris Version

iris-mc1.20.1-1.6.8.jar

### Sodium Version

sodium-extra-0.5.1+mc1.20.1-build.112.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 2060 (Mobile)

### Java Version

Adoptium Java 17 (17.0.8.7)

### Reproduction Steps

I'm not sure if anyone can reproduce this crash, maybe some mod(s) was causing it, but I have a guess that the game crashed due to the fact that it did not have enough video memory (not RAM), since this happened to me often in the past.

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-09-03 17:49:55
Description: Unexpected error

java.lang.RuntimeException: Exception thrown while executing job
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobResult.unwrap(ChunkJobResult.java:27)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.collectChunkBuildResults(RenderSectionManager.java:346)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.uploadChunks(RenderSectionManager.java:279)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.setupTerrain(SodiumWorldRenderer.java:191)
	at net.minecraft.class_761.method_3273(class_761.java:19533)
	at net.minecraft.class_761.invokeSetupRender(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:428)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:1036)
	at net.minecraft.class_761.handler$ecm000$iris$renderTerrainShadows(class_761.java:11537)
	at net.minecraft.class_761.method_22710(class_761.java:1241)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.OutOfMemoryError
	at org.lwjgl.system.MemoryUtil.nmemReallocChecked(MemoryUtil.java:496)
	at org.lwjgl.system.MemoryUtil.memRealloc(MemoryUtil.java:529)
	at me.jellysquid.mods.sodium.client.render.chunk.vertex.builder.ChunkMeshBufferBuilder.setBufferSize(ChunkMeshBufferBuilder.java:57)
	at me.jellysquid.mods.sodium.client.render.chunk.vertex.builder.ChunkMeshBufferBuilder.start(ChunkMeshBufferBuilder.java:65)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.buffers.BakedChunkModelBuilder.begin(BakedChunkModelBuilder.java:37)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuildBuffers.init(ChunkBuildBuffers.java:47)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:57)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobResult.unwrap(ChunkJobResult.java:27)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.collectChunkBuildResults(RenderSectionManager.java:346)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.uploadChunks(RenderSectionManager.java:279)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.setupTerrain(SodiumWorldRenderer.java:191)
	at net.minecraft.class_761.method_3273(class_761.java:19533)
	at net.minecraft.class_761.invokeSetupRender(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:428)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:1036)
	at net.minecraft.class_761.handler$ecm000$iris$renderTerrainShadows(class_761.java:11537)
	at net.minecraft.class_761.method_22710(class_761.java:1241)
	at net.minecraft.class_757.method_3188(class_757.java:1110)

-- Affected level --
Details:
	All players: 1 total; [class_746['PAP71'/1, l='ClientLevel', x=80.23, y=97.00, z=-215.64]]
	Chunk stats: 4096, 1089
	Level dimension: minecraft:overworld
	Level spawn location: World: (112,90,-208), Section: (at 0,10,0 in 7,5,-13; chunk contains blocks 112,-64,-208 to 127,319,-193), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 131441 game time, 21335 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/Faithful 64x - Beta 9.zip, file/VanillaTweaks_r310230.zip, file/LowOnFire_1.20.1.zip, file/KSEPSP+v8+2+cut.zip, file/Better+Skies+V0.9.zip, fabric, essential

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 7297945888 bytes (6959 MiB) / 8589934592 bytes (8192 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f15
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3713
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9bc4
	Graphics card #1 versionInfo: DriverVersion=31.0.101.1999
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 24411.45
	Virtual memory used (MB): 24287.64
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 508.04
	JVM Flags: 44 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=100 -XX:+UnlockDiagnosticVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:UseAVX=3 -XX:SoftRefLRUPolicyMSPerMB=2000 -XX:+EagerXrunInit -XX:+UseNewLongLShift -XX:+UseXmmI2D -XX:+UseXmmI2F -XX:+OptoScheduling -XX:+OptoBundling -XX:+UseStringDeduplication -XX:+UseFastUnorderedTimeStamps -XX:UseSSE=4 -XX:+UseAES -XX:+UseAESIntrinsics -XX:TargetSurvivorRatio=50 -XX:-DontCompileHugeMethods -XX:+UseLargePages -XX:LargePageSizeInBytes=2m -XX:+UseNUMA -XX:+UseVectorCmov -XX:+UseCriticalJavaThreadPriority -XX:ThreadPriorityPolicy=1 -XX:ReservedCodeCacheSize=64M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms8192m -Xmx8192m
	Fabric Mods: 
		advanced-xray-fabric: Advanced XRay (Fabric) 1.20.1-1.6.0-build.17
		advancementinfo: AdvancementInfo 1.20-fabric0.83.0-1.4
		animatica: Animatica 0.6+1.20
		antighost: AntiGhost 1.20-fabric0.83.0-1.1.5
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		appleskin: AppleSkin 2.5.0+mc1.20
		architectury: Architectury 9.1.12
		badpackets: Bad Packets 0.4.2
		betteranvil: Better Anvil 1.2.6+1.20
			com_github_mifmif_generex: generex 1.0.2
			dk_brics_automaton_automaton: automaton 1.11-8
			libgui: LibGui 8.0.1+1.20
				jankson: Jankson 5.0.1+j1.2.2
					blue_endless_jankson: jankson 1.2.2
				libninepatch: LibNinePatch 1.2.0
		betterbeds: Better Beds 1.3.0
		betterf3: BetterF3 7.0.1
		betterfpsdist: Better FPS distance Mod 1.20.1-3.9
		blanket-client-tweaks: Blanket Client-tweaks 1.1.4
		boatiview: Boat Item View Fabric 0.0.5
		bobby: Bobby 5.0.1
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		boostedbrightness: Boosted Brightness 2.2.0
		borderlessmining: Borderless Mining 1.1.8+1.20.1
		brb: Better Recipe Book 1.8.0
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.10.100
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.10.100
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.10.100
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.10.100
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.10.100
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.10.100
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.10.100
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.10.100
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.10.100
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.10.100
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.10.100
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.10.100
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.10.100
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.10.100
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.10.100
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.10.100
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.10.100
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.10.100
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.100
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.10.100
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.100
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		camerautils: Camera Utils 1.20.1-1.0.5
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da82
		capes: Capes 1.5.2+1.20
		carpet: Carpet Mod 1.4.112+v230608
		chat_heads: Chat Heads 0.10.20
		chatpatches: Chat Patches 201.5.5
		citresewn: CIT Resewn 1.1.3+1.20
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.20
		cleancut: CleanCut 6.0+mc1.19.1-mc1.20.x
		clickadv: Clickable Advancements Mod 1.20.1-3.3
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.3+1.20.1
		cupboard: cupboard 1.20.1-1.9
		dashloader: DashLoader 5.0.0-beta.2+1.20.0
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_notalpha_taski: Taski 2.1.0
			dev_quantumfusion_hyphen: Hyphen 0.4.0-rc.3
		debugify: Debugify 1.20.1+2.0
		detailab: Detail Armor Bar 2.6.3+1.20.1-fabric
		disable_custom_worlds_advice: Disable Custom Worlds Advice 4.1
		dynamic_fps: Dynamic FPS 3.0.0
		dynmus: Dynamic Music 2.3.2+1.20
		e4mc_minecraft: e4mc 4.0.1
		ears: Ears 1.4.6
		easiervillagertrading: EasierVillagerTrading 1.20-fabric0.83.0-1.5.4
			gbfabrictools: GBfabrictools 1.3.5+1.20
		elementa: Elementa 597
		emotecraft: Emotecraft 2.2.7-b.build.50
			bendy-lib: Bendy api 4.0.0
			player-animator: Player Animator 1.0.2-rc1+1.20
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		entity_model_features: Entity Model Features 0.2.13
		entity_texture_features: Entity Texture Features 4.5.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		essential: Essential 13792+deploy-staging+g3e03bf5da
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.1
		exordium: Exordium 1.1.4-mc1.20.1
		extrasounds: ExtraSounds 2.3.1+1.20.1~lonefelidae16-build.1
			soundcategories: Sound Categories 1.2.4+1.20~lonefelidae16-build.1
		fabric-api: Fabric API 0.88.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.2+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.3+92a0d36777
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.3+6bdb2ed077
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.35+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.1+195226a777
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		fabricloader: Fabric Loader 0.14.22
		fabricskyboxes: FabricSkyBoxes 0.7.2+mc1.20.1
		fallingleaves: Falling Leaves 1.15.2+1.20.1
		fastchest: FastChest 1.4+1.20
		faster_entity_animations: FastAnim 1.6
		fastload: Fast Load 3.4.0
			conditional-mixin: conditional mixin 0.3.2
			fastload-119-0-1-2-compat: Fastload 1.19-0-1-2 Compatibility 3.4.0
			fastload-1193-compat: Fastload 1.19.3 Compatibility 3.4.0
			fastload-1194-compat: Fastload 1.19.4 Compat 3.4.0
			fastload_fapi_forward: Fastload Fabric-api Forwarding 1.0.2
		fastopenlinksandfolders: FastOpenResourcePacks 1.1.1
		fastquit: FastQuit 3.0.0-beta.2+1.20+
		ferritecore: FerriteCore 6.0.0
		figura: Figura 0.1.2+1.20.1
			com_github_figuramc_luaj_luaj-core: luaj-core 3.0.6-figura
			com_github_figuramc_luaj_luaj-jse: luaj-jse 3.0.6-figura
			org_java-websocket_java-websocket: Java-WebSocket 1.5.4
		fsb-interop: FabricSkyBoxes Interop 1.3.4+mc1.20-build.47
		holdthatchunk: Hold That Chunk 2.0.1
		immediatelyfast: ImmediatelyFast 1.2.1+1.20.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.10
			net_lenni0451_reflect: Reflect 1.2.1
		indium: Indium 1.0.25+mc1.20.1
		inventory_control_tweaks: Inventory Control Tweaks 1.3.27
		inventoryprofilesnext: Inventory Profiles Next 1.10.7
		iris: Iris 1.6.8
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.12
			journeymap-api-fabric: JourneyMap API 1.20-1.9-fabric-SNAPSHOT
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lambdynlights: LambDynamicLights 2.3.1+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
		languagereload: Language Reload 1.5.8+1.20.1
		lazydfu: LazyDFU 0.1.3
		libipn: libIPN 4.0.0
		lightoverlay: Light Overlay 8.0.0
		litematica: Litematica 0.15.3
		lithium: Lithium 0.11.2
		malilib: MaLiLib 0.16.2
		memoryleakfix: Memory Leak Fix 1.1.2
		minecraft: Minecraft 1.20.1
		modelfix: Model Gap Fix 1.14
		modernfix: ModernFix 5.7.2+mc1.20.1
		modmenu: Mod Menu 7.2.1
		moreculling: More Culling 1.20.1-0.19.0
		no-resource-pack-warnings: No Resource Pack Warnings 1.3.0
		no_fog: No Fog 1.3.4+1.16.5-1.20.1
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		notenoughanimations: NotEnoughAnimations 1.6.4
		notenoughcrashes: Not Enough Crashes 4.4.6+1.20.1
		now-playing: Now Playing 1.4.4-blanketcon
		online_emotes: Online Emotes 2.1.0-fabric
			io_netty_netty-codec-http: netty-codec-http 4.1.82.Final
		org_jetbrains_annotations: annotations 13.0
		perspectivemod: Perspective Mod Redux 0.0.5_01
		plasmovoice: Plasmo Voice 2.0.6
			aopalliance_aopalliance: aopalliance 1.0
			com_google_inject_guice: guice 5.0.1
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			javax_inject_javax_inject: javax.inject 1
		puzzle: Puzzle 1.5.2+1.20
			puzzle-base: Puzzle Base 1.5.2+1.20
			puzzle-gui: Puzzle GUI 1.5.2+1.20
			puzzle-models: Puzzle Models 1.5.2+1.20
			puzzle-splashscreen: Puzzle Splash Screen 1.5.2+1.20
		raised: Raised 2.0.0
		raknetify: Raknetify (Fabric) 0.1.0+alpha.5.98
		recipe-book-is-pain: Recipe Book Is Pain 0.10.0-1.20.1
			dark-matter-base: Dark Matter Base 1.0.0-1.20
			dark-matter-enums: Dark Matter Enums 1.0.0-1.20
			dark-matter-minecraft: Dark Matter Minecraft 1.0.0-1.20
			dark-matter-recipe-book: Dark Matter Recipe Book 1.0.0-1.20
		reeses-sodium-options: Reese's Sodium Options 1.6.5+mc1.20.1-build.95
		roughlyenoughitems: Roughly Enough Items 12.0.652
			error_notifier: Error Notifier 1.0.9
		roughlyenoughresources: Roughly Enough Resources 2.9.0
		serverpingerfixer: Server Pinger Fixer 1.0.1
		skinlayers: 3d Skin Layers 1.5.4-mc1.20.1
		skiptransitions: Skip Transitions 1.3.3+mc1.20
		smoke_suppression: Smoke Suppression 1.0.16
		smoothchunk: Smooth chunk save Mod 1.20.1-3.1
		smoothswapping: Smooth Swapping 0.9.2
		sodium: Sodium 0.5.2
		sodium-extra: Sodium Extra 0.5.1+mc1.20.1-build.112
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.2.1
		starlight: Starlight 1.1.2+fabric.dbc156f
		status-effect-bars: Status Effect Bars 1.0.3
		threadtweak: ThreadTweak 1.20.1-0.1.0
		tiefix: TieFix 1.14.0
		toomanyplayers: Too Many Players 1.20-1.1.4
		torohealth: ToroHealth Damage Indicators 1.20.1-fabric-1
		universalcraft: UniversalCraft 277
		videotape: Video Tape 1.2.1
			com_github_krlite_pierced: Pierced v1.2
		vigilance: Vigilance 286
		vmp: Very Many Players 0.2.0+beta.7.101
		wildfire_gender: Wildfire's Female Gender Mod 1.20-3.0.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.1.1+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
	Loaded Shaderpack: Sildur's+Vibrant+Shaders+v1.51+High.zip
		Profile: Custom (+0 options changed by user)
	NEC status: No NEC detected
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 3.2.0 NVIDIA 537.13, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=0, source=API, type=ERROR, severity=HIGH, message='Unknown internal debug message. The NVIDIA OpenGL driver has encountered
an out of memory error. This application might
behave inconsistently and fail.
(pid=4448 javaw.exe 64bit)' x 1
id=1285, source=API, type=ERROR, severity=HIGH, message='GL_OUT_OF_MEMORY error generated. Failed to allocate CPU address space mapping for texture.' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/Faithful 64x - Beta 9.zip, file/VanillaTweaks_r310230.zip, file/LowOnFire_1.20.1.zip, file/KSEPSP+v8+2+cut.zip, file/Better+Skies+V0.9.zip, fabric
	Current Language: en_us
	CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['PAP71'/1, l='ServerLevel[New World]', x=80.23, y=97.00, z=-215.64]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Iris (iris), Sodium (sodium)
```

### Additional context

I tried to load shaders Sildur's Vibrant Shaders v1.51 High, but after a couple of seconds the game crashed, and in the logs there are a lot of errors related to the Sodium. Maybe the error is caused by the shader itself, since other shaders work with grief in half on my PC, but then the errors would be associated with Iris I think. I was told to create a bug report here too
Github wouldn't let me paste latest.log , so I'll just leave it as a file.
[latest.log](https://github.com/IrisShaders/Iris/files/12506475/latest.log)

**Comment by tanyaofei** [comment]
`Caused by: java.lang.OutOfMemoryError`, try give more memory

**Comment by Fleepe** [comment]
> `Caused by: java.lang.OutOfMemoryError`, try give more memory

8 GB is not enough these days?

**Comment by tanyaofei** [comment]
> > `Caused by: java.lang.OutOfMemoryError`, try give more memory
> 
> Damn, is 8 GB not enough these days?

lol, or it could be a dead loop and acquire memory forever until the program is dead. When i installed `caxton`, it happened to me. By the way, it seems that currently Iris is not compatible with `entities_model_feature` and `entity_texture_feature`, try removing them.

**Comment by Fleepe** [comment]
Well, someday I'll find the mod that causes this loop...
