### ISSUE TITLE
Outdated Fabric Loader (version 0.14.22 needed)

### ISSUE THREAD

**Issue by Vydexus** [IrisShaders/Iris#2133]
### Minecraft Version

Minecraft 1.20.2

### Iris Version

iris-mc1.20.2-1.6.9.jar

### Sodium Version

sodium-fabric-mc1.20.2-0.5.3.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 3070 Mobile

### Java Version

1.17 (Default Installation)

### Reproduction Steps

1. Install the newest version of Iris.
2. Add Fabric API version 0.89.0 or later to the Iris mods folder.
3. Launch the game.

### Crash Report file and latest.log

[15:26:33] [main/INFO]: Loading Minecraft 1.20.2 with Fabric Loader 0.14.21
[15:26:34] [main/WARN]: Mod resolution failed
[15:26:34] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE fabric-api 0.89.0+1.20.2 {depends fabricloader @ [>=0.14.22]}, ROOT_FORCELOAD_SINGLE fabric-api 0.89.0+1.20.2]
[15:26:34] [main/INFO]: Reason: [HARD_DEP fabric-api 0.89.0+1.20.2 {depends fabricloader @ [>=0.14.22]}]
[15:26:34] [main/INFO]: Fix: add [], remove [], replace [[fabricloader 0.14.21+local] -> add:fabricloader 0.14.22 ([[0.14.22,?)])]
[15:26:34] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Fabric Loader' (fabricloader) 0.14.21+local with version 0.14.22 or later.
Unmet dependency listing:
	 - Mod 'Fabric API' (fabric-api) 0.89.0+1.20.2 requires version 0.14.22 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.21+local!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[iris-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[iris-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[iris-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[iris-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[iris-loader-0.14.21.jar:?]

### Additional context

After updating to Minecraft 1.20.2, I was trying to install the newest version of the Fabric API since some of my mods needed it. However, Fabric (0.14.21+local) would not start, saying that Fabric API requires Fabric Loader 0.14.22 or later.

**Full Fabric Loader error below:**
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Fabric Loader' (fabricloader) 0.14.21+local with version 0.14.22 or later.
Unmet dependency listing:
	 - Mod 'Fabric API' (fabric-api) 0.89.0+1.20.2 requires version 0.14.22 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.21+local!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by IMS212** [comment]
Please do not put mods in iris-reserved, install Iris with normal Fabric if you wish to use mods.
