### ISSUE TITLE
Minecraft v1.20.1 Fabric Edition crashes using Shaders.

### ISSUE THREAD

**Issue by SirTwsted** [IrisShaders/Iris#2134]
### Minecraft Version

v1.20.1

### Iris Version

iris-mc1.20.1-1.6.9.jar

### Sodium Version

sodium-fabric-mc1.20.1-0.5.3.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce 1070-Ti

### Java Version

Java 20

### Reproduction Steps

1. Use Iris, indium-1.0.27+mc1.20.1 and Sodium with ComplementaryUnbound_r5.0.1.zip  Shader.
2. Start Minecraft wait until at Single Player window and go to options and turn on the Shader.
3. Go into the world.
4. Wait like 15 seconds and Boom, MC Game Crashes

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-09-25 06:33:28
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.coderbot.iris.pipeline.WorldRenderingPipeline.setPhase(net.coderbot.iris.pipeline.WorldRenderingPhase)" because "this.pipeline" is null
	at net.minecraft.class_761.handler$eid000$iris$renderSky$beginNormalSky(class_761.java:12061)
	at net.minecraft.class_761.method_3257(class_761.java:1987)
	at net.cerulan.blockofsky.client.BOSClient.renderActualSky(BOSClient.java:144)
	at net.cerulan.blockofsky.client.BOSClient.renderSky(BOSClient.java:109)
	at net.cerulan.blockofsky.fablike.client.BlockOfSkyFablikeClient.lambda$init$0(BlockOfSkyFablikeClient.java:10)
	at net.fabricmc.fabric.api.client.rendering.v1.WorldRenderEvents.lambda$static$28(WorldRenderEvents.java:251)
	at net.minecraft.class_761.handler$dkf000$fabric-rendering-v1$afterRender(class_761.java:9582)
	at net.minecraft.class_761.method_22710(class_761.java:1560)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_761.handler$eid000$iris$renderSky$beginNormalSky(class_761.java:12061)
	at net.minecraft.class_761.method_3257(class_761.java:1987)
	at net.cerulan.blockofsky.client.BOSClient.renderActualSky(BOSClient.java:144)
	at net.cerulan.blockofsky.client.BOSClient.renderSky(BOSClient.java:109)
	at net.cerulan.blockofsky.fablike.client.BlockOfSkyFablikeClient.lambda$init$0(BlockOfSkyFablikeClient.java:10)
	at net.fabricmc.fabric.api.client.rendering.v1.WorldRenderEvents.lambda$static$28(WorldRenderEvents.java:251)
	at net.minecraft.class_761.handler$dkf000$fabric-rendering-v1$afterRender(class_761.java:9582)
	at net.minecraft.class_761.method_22710(class_761.java:1560)
	at net.minecraft.class_757.method_3188(class_757.java:1110)

-- Affected level --
Details:
	All players: 1 total; [class_746['SirTwsted'/193, l='ClientLevel', x=-447.32, y=75.00, z=144.95]]
	Chunk stats: 1024, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (-416,63,176), Section: (at 0,15,0 in -26,3,11; chunk contains blocks -416,-64,176 to -401,319,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 282147 game time, 338253 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, Moonlight Mods Dynamic Assets, file/Default HD Alpha 1.2.8.zip, file/Icons v.1.9.1§7.zip, file/[1.3] Enhanced Boss Bars.zip, file/UniqueDark_1.20.1.zip, file/Repurposed_Structures-Better_Monuments_v6.zip, file/Dramatic Skys Demo 1.5.3.12.zip
```

### Additional context

Splash Screen Exit Error in CurseForge:

`The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.coderbot.iris.pipeline.WorldRenderingPipeline.setPhase(net.coderbot.iris.pipeline.WorldRenderingPhase)" because "this.pipeline" is null
`

**Comment by SirTwsted** [comment]
UPDATE:

I disabled Shaders all together and kept Iris installed.  and it still crashes with the same error above.
So its not the shaders themselves (which I thought) through processes of elimination.  
I also tested around 6 different shaders and I also get the same crash.
This is specifically iris.   🤔🤷‍♀️
Just giving a heads up  😋

**Comment by IMS212** [comment]
Block of Sky needs to change their Mixin injection to not be so late.
