### ISSUE TITLE
Crashes when pressing F5

### ISSUE THREAD

**Issue by Icey67** [IrisShaders/Iris#2144]
### Minecraft Version

1.20.2

### Iris Version

iris-mc1.20.2-1.6.10.jar

### Sodium Version

sodium-fabric-mc1.20.1-0.5.3.jar

### Operating System

Windows 11

### What is your GPU?

Nvidia Geforce GTX 770

### Java Version

Java 17

### Reproduction Steps

1. Place a Redstone Lamp in front of a Redstone Repeater
2. Use a Lever to activate the Redstone Repeater
3. Game Crashes

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-10-13 20:24:01
Description: Rendering entity in world

java.lang.RuntimeException: [Vertex] Unsupported format format: 10 elements: Position=3,Position,Float Color=4,Vertex Color,Unsigned Byte UV0=2,UV,Float UV2=2,UV,Short Normal=3,Normal,Byte Padding=1,Padding,Byte iris_Entity=3,UV,Unsigned Short mc_midTexCoord=2,Generic,Float at_tangent=4,Generic,Byte Padding2=1,Padding,Short
	at net.digitalingot.feather.dS.ri(FeatherSourceFile:63)
	at net.digitalingot.feather.dK$zt.zt(FeatherSourceFile:51)
	at net.digitalingot.feather.dL$zt.zt(FeatherSourceFile:209)
	at net.digitalingot.feather.dL$zt.zt(FeatherSourceFile:186)
	at net.digitalingot.feather.tb.zt(FeatherSourceFile:142)
	at net.digitalingot.feather.tb.zt(FeatherSourceFile:108)
	at net.digitalingot.feather.tb.zt(FeatherSourceFile:84)
	at net.digitalingot.feather.tr.zt(FeatherSourceFile:503)
	at net.digitalingot.feather.tr.zt(FeatherSourceFile:300)
	at net.digitalingot.feather.tr.zt(FeatherSourceFile:237)
	at net.minecraft.class_327.handler$cbi000$feather$ZtfyL(class_327.java:1078)
	at net.minecraft.class_327.method_30882(class_327.java)
	at net.minecraft.class_897.method_3926(class_897.java:113)
	at net.minecraft.class_1007.method_4213(class_1007.java:174)
	at net.minecraft.class_1007.method_3926(class_1007.java:44)
	at net.minecraft.class_897.method_3936(class_897.java:72)
	at net.minecraft.class_922.method_4054(class_922.java:149)
	at net.minecraft.class_1007.method_4215(class_1007.java:67)
	at net.minecraft.class_1007.method_3936(class_1007.java:44)
	at net.minecraft.class_898.method_3954(class_898.java:146)
	at net.minecraft.class_761.method_22977(class_761.java:1342)
	at net.minecraft.class_761.method_22710(class_761.java:1092)
	at net.minecraft.class_757.method_3188(class_757.java:1113)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.digitalingot.feather.dS.ri(FeatherSourceFile:63)
	at net.digitalingot.feather.dK$zt.zt(FeatherSourceFile:51)
	at net.digitalingot.feather.dL$zt.zt(FeatherSourceFile:209)
	at net.digitalingot.feather.dL$zt.zt(FeatherSourceFile:186)
	at net.digitalingot.feather.tb.zt(FeatherSourceFile:142)
	at net.digitalingot.feather.tb.zt(FeatherSourceFile:108)
	at net.digitalingot.feather.tb.zt(FeatherSourceFile:84)
	at net.digitalingot.feather.tr.zt(FeatherSourceFile:503)
	at net.digitalingot.feather.tr.zt(FeatherSourceFile:300)
	at net.digitalingot.feather.tr.zt(FeatherSourceFile:237)
	at net.minecraft.class_327.handler$cbi000$feather$ZtfyL(class_327.java:1078)
	at net.minecraft.class_327.method_30882(class_327.java)
	at net.minecraft.class_897.method_3926(class_897.java:113)
	at net.minecraft.class_1007.method_4213(class_1007.java:174)
	at net.minecraft.class_1007.method_3926(class_1007.java:44)
	at net.minecraft.class_897.method_3936(class_897.java:72)
	at net.minecraft.class_922.method_4054(class_922.java:149)
	at net.minecraft.class_1007.method_4215(class_1007.java:67)
	at net.minecraft.class_1007.method_3936(class_1007.java:44)
	at net.minecraft.class_898.method_3954(class_898.java:146)
	at net.minecraft.class_761.method_22977(class_761.java:1342)
	at net.minecraft.class_761.method_22710(class_761.java:1092)
	at net.minecraft.class_757.method_3188(class_757.java:1113)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 150
	Entity Name: Icey67
	Entity's Exact location: 103.64, 80.00, 11.36
	Entity's Block location: World: (103,80,11), Section: (at 7,0,11 in 6,5,0; chunk contains blocks 96,-64,0 to 111,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {AbsorptionAmount:0.0f,Air:300s,Attributes:[{Base:0.10000000149011612d,Name:"minecraft:generic.movement_speed"}],Brain:{memories:{}},DataVersion:3578,DeathTime:0s,EnderItems:[],FallDistance:0.0f,FallFlying:0b,Fire:-20s,Health:20.0f,HurtByTimestamp:0,HurtTime:0s,Inventory:[],Invulnerable:0b,Motion:[0.0d,-0.0784000015258789d,0.0d],OnGround:1b,PortalCooldown:0,Pos:[103.64081598477034d,80.0d,11.364537546311656d],Rotation:[-88.998375f,42.725143f],Score:0,SelectedItemSlot:0,SleepTimer:0s,UUID:[I;-1760148641,1327907676,-1213604907,1459521594],XpLevel:0,XpP:0.0f,XpSeed:0,XpTotal:0,abilities:{flySpeed:0.05f,flying:0b,instabuild:1b,invulnerable:1b,mayBuild:1b,mayfly:1b,walkSpeed:0.1f},foodExhaustionLevel:0.0f,foodLevel:20,foodSaturationLevel:5.0f,foodTickTimer:0}
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:146)
	at net.minecraft.class_761.method_22977(class_761.java:1342)
	at net.minecraft.class_761.method_22710(class_761.java:1092)
	at net.minecraft.class_757.method_3188(class_757.java:1113)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_1007@4e453ca4
	Location: 2.94,-4.33,0.05 - World: (2,-5,0), Section: (at 2,11,0 in 0,-1,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Rotation: -88.998375
	Delta: 0.060014606
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:146)
	at net.minecraft.class_761.method_22977(class_761.java:1342)
	at net.minecraft.class_761.method_22710(class_761.java:1092)
	at net.minecraft.class_757.method_3188(class_757.java:1113)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)

-- Affected level --
Details:
	All players: 1 total; [class_746['Icey67'/150, l='ClientLevel', x=103.64, y=80.00, z=11.36]]
	Chunk stats: 1024, 533
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,69,0), Section: (at 0,5,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 6496 game time, 6496 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:451)
	at net.minecraft.class_310.method_1587(class_310.java:2481)
	at net.minecraft.class_310.method_1514(class_310.java:875)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/VanillaTweaks_r208013.zip

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1296241864 bytes (1236 MiB) / 2583691264 bytes (2464 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 6
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Phenom(tm) II X6 1090T Processor
	Identifier: AuthenticAMD Family 16 Model 10 Stepping 0
	Microarchitecture: K10
	Frequency (GHz): 3.20
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 770
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1184
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7444
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: Other
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.33
	Memory slot #1 type: Other
	Virtual memory max (MB): 17451.96
	Virtual memory used (MB): 15174.86
	Swap memory total (MB): 1068.86
	Swap memory used (MB): 6.79
	JVM Flags: 8 total; -Xmx4096M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:ErrorFile=feather/java_error.log
	Fabric Mods: 
		axiom: Axiom 1.5.1
			com_moulberry_axiomclientapi_axiomclientapi_: axiomclientapi 1.0.0
		betterf3: BetterF3 8.0.1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.11+86b12645a0
		bobby: Bobby 5.0.2
			com_typesafe_config: config 1.4.2
			fabric-command-api-v2: Fabric Command API (v2) 2.2.14+86b12645a0
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		borderlessmining: Borderless Mining 1.1.9+1.20.2
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.10.126
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.10.126
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.10.126
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.10.126
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.10.126
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.10.126
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.10.126
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.10.126
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.10.126
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.10.126
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.10.126
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.10.126
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.10.126
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.10.126
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.10.126
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.10.126
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.10.126
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.10.126
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.126
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.10.126
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.126
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		camerautils: Camera Utils 1.20.2-1.0.5
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+f4b7e42403
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.25+3bafade303
		chesttracker: Chest Tracker 2.0.1+1.20.2
			searchables: Searchables 1.0.1
		cloth-config: Cloth Config v12 12.0.109
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 13.0.0.1
		collective: Collective 6.66
		continuity: Continuity 3.0.0-beta.4+1.20.2
		craftify: Craftify 1.12.0
			elementa: Elementa 590
			universalcraft: UniversalCraft 316
			vigilance: Vigilance 284
		cupboard: cupboard 1.20.2-2.0
		entity_model_features: Entity Model Features 1.0.2
		entity_texture_features: Entity Texture Features 4.5.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		fabric-api: Fabric API 0.89.2+1.20.2
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.40+fce67b32a0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.11+86b12645a0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+73761d2ea0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+73761d2ea0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.42+f4b7e424a0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.3+86b12645a0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.35+f71b366fa0
			fabric-commands-v0: Fabric Commands (v0) 0.2.52+df3654b3a0
			fabric-containers-v0: Fabric Containers (v0) 0.1.71+df3654b3a0
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.3+0ba8e9cea0
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.6+f4b7e424a0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+f4b7e424a0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.1+bbae80faa0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.55+b1229956a0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.24+f4b7e424a0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.8+daef22a2a0
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.67+df3654b3a0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+f4b7e424a0
			fabric-item-api-v1: Fabric Item API (v1) 2.1.31+43511215a0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+f4b7e424a0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b3a0
			fabric-loot-api-v2: Fabric Loot API (v2) 2.0.1+0ba8e9cea0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.0+fce67b32a0
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.53+f4b7e424a0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.4+f4b7e424a0
			fabric-models-v0: Fabric Models (v0) 0.4.3+9386d8a7a0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.0+b1b4f7b0a0
			fabric-particles-v1: Fabric Particles (v1) 1.1.3+f4b7e424a0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.4+43511215a0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.2+34a3e0e2a0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+2034447ca0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+2034447ca0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.47+df3654b3a0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.38+73761d2ea0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.29+f4b7e424a0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.50+df3654b3a0
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.9+86b12645a0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+43511215a0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.10+0ba8e9cea0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.37+86b12645a0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+f4b7e424a0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.7+109a65e5a0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.2+fce67b32a0
		fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		fabricloader: Fabric Loader 0.14.22
		feather: Feather Client release/8f9836bd
		forgeconfigapiport: Forge Config API Port 9.0.0
		indium: Indium 1.0.27+mc1.20.1
		inventoryprofilesnext: Inventory Profiles Next 1.10.7
		iris: Iris 1.6.10
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 16.0.0.28
		krypton: Krypton 0.2.4
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
		libipn: libIPN 4.0.0
		litematica: Litematica 0.16.0
		lithium: Lithium 0.12.0
		malilib: MaLiLib 0.17.0
			fabric-api-base: Fabric API Base 0.4.33+fce67b32a0
			fabric-networking-api-v1: Fabric Networking API (v1) 3.0.8+b18afef3a0
		midnightcontrols: MidnightControls 1.9.0+1.20.2
			midnightlib: MidnightLib 1.5.0
			org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
			spruceui: SpruceUI 5.0.3+1.20.2
		minecraft: Minecraft 1.20.2
		minihud: MiniHUD 0.27.0-nyan.6
		modmenu: Mod Menu 8.0.0
		notenoughcrashes: Not Enough Crashes 4.4.6+1.20.2
		noxesium: Noxesium 1.0.5+f253e35
			com_noxcrew_noxesium_api_: api 1.0.5+f253e35
		reacharound: Reacharound 1.1.2
		reeses-sodium-options: Reese's Sodium Options 1.6.5+mc1.20.2-build.96
		sodium: Sodium 0.5.3
		sodium-extra: Sodium Extra 0.5.2+mc1.20.2-build.113
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		starlight: Starlight 1.1.2+fabric.bdaeb21
		tweakeroo: Tweakeroo 0.17.1-nyan.6
		visuality: Visuality 0.7.1+1.20
		voicechat: Simple Voice Chat 1.20.2-2.4.26
		whereisit: WhereIsIt 2.2.1+1.20.2
			jackfredlib: JackFredLib 0.5.9+1.20.2
				jackfredlib-base: JackFredLib: Base 1.1.3+1.20.2
				jackfredlib-colour: JackFredLib: Colour 1.0.2+1.20.2
				jackfredlib-extracommandsourcedata: JackFredLib: Extra Command Source Data 1.0.4+1.20.2
					com_github_llamalad7_mixinextras: MixinExtras 0.2.0-rc.5
				jackfredlib-gps: JackFredLib: GPS 1.0.2+1.20.2
				jackfredlib-lying: JackFredLib: Lying 0.3.2+1.20.2
				jackfredlib-toasts: JackFredLib: Toasts 1.0.3+1.20.2
		wi_zoom: WI Zoom 1.5-MC1.20.2
		worldedit: WorldEdit 7.2.16+6534-2066eb4
		xaerominimap: Xaero's Minimap 23.8.2
		xaeroworldmap: Xaero's World Map 1.34.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20.2
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Loaded Shaderpack: ComplementaryReimagined_r5.0.1.zip
		Profile: POTATO (+0 options changed by user)
	NEC status: No NEC detected
	JVM uptime in seconds: 123.585
	Launched Version: 1.20.2-feather
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce GTX 770/PCIe/SSE2 GL version 3.2.0 NVIDIA 474.44, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'Feather Fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/VanillaTweaks_r208013.zip
	Current Language: en_us
	Locale: en_US
	CPU: 6x AMD Phenom(tm) II X6 1090T Processor
	Server Running: true
	Player Count: 1 / 8; [class_3222['Icey67'/150, l='ServerLevel[New World]', x=103.64, y=80.00, z=11.36]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Suspected Mods: Minecraft (minecraft), Feather Client (feather), Fabric Loader (fabricloader)
```

### Additional context

[crash-2023-10-13_20.24.01-client.txt](https://github.com/IrisShaders/Iris/files/12897372/crash-2023-10-13_20.24.01-client.txt)
[latest.log](https://github.com/IrisShaders/Iris/files/12897389/latest.log)
My Skin had transparent pixels in it, I tried removing those, that didn't work.
Doesn't crash when the shaders are off

**Comment by IMS212** [comment]
Don't use Feather.

**Comment by Icey67** [comment]
> Don't use Feather.

Why not?

**Comment by diarm56** [comment]
Feather client is not supported. It does stuff to minecraft sodium and iris can't account for and causes graphical corruption/crashes. Please use another launcher. Some launchers we support: prism/multimc, gdlauncher, atlauncher, the modrinth launcher, the vanilla launcher (using the installer), ...

**Comment by Icey67** [comment]
Just downgraded Iris to 1.6.9, that fixes the issue *shruggie*

**Comment by sheikh1233** [comment]
1.6.9 don't have pbr if you are ever going to use a resourcepack like that
