### ISSUE TITLE
Crash with Ad Astra space suit and Customizable Player Models

### ISSUE THREAD

**Issue by HiggsBonbon** [IrisShaders/Iris#2145]
### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.6.10.jar

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1 (replaymod compatible).jar

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce 970

### Java Version

Java 17

### Reproduction Steps

Attempting to wear a space suit causes the game to crash.

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3
Time: 10/13/23, 6:32 PM
Description: Unexpected error
java.lang.IllegalStateException: Already in a group
	at net.coderbot.batchedentityrendering.impl.ordering.GraphTranslucencyRenderOrderManager.startGroup(GraphTranslucencyRenderOrderManager.java:69)
	at net.coderbot.batchedentityrendering.impl.FullyBufferedMultiBufferSource.startGroup(FullyBufferedMultiBufferSource.java:245)
	at net.coderbot.batchedentityrendering.impl.FullyBufferedMultiBufferSource$UnflushableWrapper.startGroup(FullyBufferedMultiBufferSource.java:312)
	at com.tom.cpm.client.ClientBase.renderHand(ClientBase.java:195)
	at net.minecraft.class_1007.handler$zcl000$cpm$onRenderRightArmPre(class_1007.java:567)
	at net.minecraft.class_1007.method_4220(class_1007.java)
	at net.minecraft.class_759.method_3219(class_759.java:307)
	at net.minecraft.class_759.method_3228(class_759.java:447)
	at net.minecraft.class_759.method_22976(class_759.java:364)
	at net.coderbot.iris.pipeline.HandRenderer.renderSolid(HandRenderer.java:90)
	at net.minecraft.class_761.handler$znk000$iris$beginTranslucents(class_761.java:7625)
	at net.minecraft.class_761.method_22710(class_761.java:1483)
	at net.minecraft.class_757.method_3188(class_757.java:1034)
	at net.minecraft.class_757.method_3192(class_757.java:813)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at net.coderbot.batchedentityrendering.impl.ordering.GraphTranslucencyRenderOrderManager.startGroup(GraphTranslucencyRenderOrderManager.java:69)
	at net.coderbot.batchedentityrendering.impl.FullyBufferedMultiBufferSource.startGroup(FullyBufferedMultiBufferSource.java:245)
	at net.coderbot.batchedentityrendering.impl.FullyBufferedMultiBufferSource$UnflushableWrapper.startGroup(FullyBufferedMultiBufferSource.java:312)
	at com.tom.cpm.client.ClientBase.renderHand(ClientBase.java:195)
	at net.minecraft.class_1007.handler$zcl000$cpm$onRenderRightArmPre(class_1007.java:567)
	at net.minecraft.class_1007.method_4220(class_1007.java)
	at net.minecraft.class_759.method_3219(class_759.java:307)
	at net.minecraft.class_759.method_3228(class_759.java:447)
	at net.minecraft.class_759.method_22976(class_759.java:364)
	at net.coderbot.iris.pipeline.HandRenderer.renderSolid(HandRenderer.java:90)
	at net.minecraft.class_761.handler$znk000$iris$beginTranslucents(class_761.java:7625)
	at net.minecraft.class_761.method_22710(class_761.java:1483)
	at net.minecraft.class_757.method_3188(class_757.java:1034)
-- Affected level --
Details:
	All players: 1 total; [class_746['HiggsBonbon'/1, l='ClientLevel', x=1.50, y=-60.00, z=7.50]]
	Chunk stats: 1024, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 276 game time, 276 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods
-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8.1, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 886046720 bytes (845 MiB) / 2583691264 bytes (2464 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600X 6-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 970
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x13c2
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 29042.51
	Virtual memory used (MB): 13572.02
	Swap memory total (MB): 12734.91
	Swap memory used (MB): 118.73
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		ad_astra: Ad Astra 1.0.9
			team_reborn_energy: Energy 2.2.0
		cloth-config: Cloth Config v6 6.4.90
			cloth-basic-math: cloth-basic-math 0.6.1
		cpm: Customizable Player Models 0.6.11a
		fabric-api: Fabric API 0.76.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.5+64b7c69360
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.3+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.7+e83becad60
			fabric-block-api-v1: Fabric Block API (v1) 1.0.0+ee3621fc60
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.13+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.10+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.9+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.24+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.3+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.0+43ce63a460
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.1.0+6c70b68e60
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.21+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.9+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.20+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.22+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.6.2+8165403660
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.16+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.1+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.2+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.6+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.7+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.24+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.11+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.5+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.13+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.12+bb2e047760
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.5.0+bf48649860
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.1+03e2b68760
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.12+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.9+ee3621fc60
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.3+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.14+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.8+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.3+047a5ecb60
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.11+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.3+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.13+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.4+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabricloader: Fabric Loader 0.14.22
		iris: Iris 1.6.10
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.18.2
		pehkui: Pehkui 3.7.8+1.14.4-1.20.1
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		sodium: Sodium 0.4.1+replaymod.rev.23e83a1
			org_joml_joml: joml 1.10.2
		sodium-extra: Sodium Extra 0.4.16+mc1.18.2-build.89
			caffeineconfig: CaffeineConfig 1.0.0+1.17
	Loaded Shaderpack: ComplementaryReimagined_r2.3.zip
		Profile: Custom (+8 options changed by user)
	NEC status: No NEC detected
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 970/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.94, NVIDIA Corporation
	Window size: 1920x1027
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600X 6-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['HiggsBonbon'/1, l='ServerLevel[New World]', x=1.50, y=-60.00, z=7.50]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\higgs\AppData\Roaming\PolyMC\instances\1.18.2\.minecraft\crash-reports\crash-2023-10-13_18.32.53-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.
Clipboard copy at: 13 Oct 2023 18:40:01 -0400
```

### Additional context

Can't determine which mod is to blame for this, only occurs with all three. Reposting this issue on their respective githubs.

**Comment by Excalimbinhu** [comment]
Had the same error but at any time I try to enable shaders! It just crash my game at my server.

Running:
MC 1.19.2
Sodium 0.4.4
Iris 1.6.10
Fabric 0.14.22

<html>
<body>


[00:14:51] [Render thread/ERROR]: Unreported exception thrown!
--
1666 | java.lang.IllegalStateException: Already in a group
1667 | at net.coderbot.batchedentityrendering.impl.ordering.GraphTranslucencyRenderOrderManager.startGroup(GraphTranslucencyRenderOrderManager.java:69) ~[iris-mc1.19.2-1.6.10.jar:?]
1668 | at net.coderbot.batchedentityrendering.impl.FullyBufferedMultiBufferSource.startGroup(FullyBufferedMultiBufferSource.java:245) ~[iris-mc1.19.2-1.6.10.jar:?]
1669 | at net.coderbot.batchedentityrendering.impl.FullyBufferedMultiBufferSource$UnflushableWrapper.startGroup(FullyBufferedMultiBufferSource.java:312) ~[iris-mc1.19.2-1.6.10.jar:?]
1670 | at com.tom.cpm.client.ClientBase.renderHand(ClientBase.java:195) ~[CustomPlayerModels-Fabric-1.19-0.6.12a.jar:?]
1671 | at net.minecraft.client.render.entity.PlayerEntityRenderer.handler$cep000$cpm$onRenderRightArmPre(PlayerEntityRenderer.java:567) ~[client-intermediary.jar:?]
1672 | at net.minecraft.class_1007.method_4220(class_1007.java) ~[client-intermediary.jar:?]
1673 | at net.minecraft.client.render.item.HeldItemRenderer.renderArmHoldingItem(HeldItemRenderer.java:307) ~[client-intermediary.jar:?]
1674 | at net.minecraft.client.render.item.HeldItemRenderer.renderFirstPersonItem(HeldItemRenderer.java:447) ~[client-intermediary.jar:?]
1675 | at net.minecraft.client.render.item.HeldItemRenderer.renderItem(HeldItemRenderer.java:364) ~[client-intermediary.jar:?]
1676 | at net.coderbot.iris.pipeline.HandRenderer.renderSolid(HandRenderer.java:90) ~[iris-mc1.19.2-1.6.10.jar:?]
1677 | at net.minecraft.client.render.WorldRenderer.handler$fbg000$iris$beginTranslucents(WorldRenderer.java:10692) ~[client-intermediary.jar:?]
1678 | at net.minecraft.client.render.WorldRenderer.render(WorldRenderer.java:1488) ~[client-intermediary.jar:?]
1679 | at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:1039) ~[client-intermediary.jar:?]
1680 | at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:816) ~[client-intermediary.jar:?]
1681 | at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1177) ~[client-intermediary.jar:?]
1682 | at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:768) [client-intermediary.jar:?]
1683 | at net.minecraft.client.main.Main.main(Main.java:244) [client-intermediary.jar:?]
1684 | at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
1685 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.22.jar:?]
1686 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.22.jar:?]
1687 | at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.22.jar:?]


</body>
</html>
