### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library

### ISSUE THREAD

**Issue by MKrabs** [IrisShaders/Iris#2148]
### What happened?

When trying to install iris on Linux (Fedora Linux 38), I get the following error message: (see logs)

Same thing happens with Optifine 1.20.1 and other Iris versions.

I have never tinkered with minecraft before on Linux, so if any Info is needed I'll gladly help.

### Screenshots

![image](https://github.com/IrisShaders/Iris/assets/71791731/b8f06048-395f-441e-8ff3-60047f3e9b30)

### Log output

$ java -jar iris-mc1.20.2-1.6.10.jar 
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk-17.0.8.0.7-1.fc38.x86_64/lib/libawt_xawt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2403)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1392)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1390)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1389)
	at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1427)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1401)
	at java.desktop/javax.swing.UIManager.getSystemLookAndFeelClassName(UIManager.java:668)
	at net.coderbot.iris.LaunchWarn.main(LaunchWarn.java:20)
$ java --version
openjdk 17.0.8 2023-07-18
OpenJDK Runtime Environment (Red_Hat-17.0.8.0.7-1.fc38) (build 17.0.8+7)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.8.0.7-1.fc38) (build 17.0.8+7, mixed mode, sharing)

### Minecraft Version

1.20.2

### Iris Version

iris-mc1.20.2-1.6.10.jar

### Operating System

Fedora Linux 38

### What is your GPU?

NVIDIA GeForce RTX™ 3060

**Comment by IMS212** [comment]
You need a non-headless Java and Xorg installed.
