### ISSUE TITLE
Failed to create shader rendering pipeline

### ISSUE THREAD

**Issue by Nikitoonchik** [IrisShaders/Iris#2153]
### What happened?

Trying to use Iris shaders , but smth happend and it doesnt want to turn on shaders

### Log output

Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.RuntimeException: Shader compilation failed!
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:238)
	at net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:95)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:220)
	at net.coderbot.iris.Iris.createPipeline(Iris.java:639)
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34)
	at net.coderbot.iris.Iris.onLoadingComplete(Iris.java:214)
	at net.minecraft.class_442.handler$zkh000$iris$showSodiumIncompatScreen(class_442.java:540)
	at net.minecraft.class_442.method_25426(class_442.java:141)
	at net.minecraft.class_437.method_25423(class_437.java:387)
	at net.minecraft.class_310.method_1507(class_310.java:984)
	at net.minecraft.class_310.<init>(class_310.java:635)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Failed to compile FRAGMENT shader for program deferred.fsh
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:78)
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:49)
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:234)
	... 14 more
Caused by: java.lang.RuntimeException: Shader compilation failed, see log for details
	at net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:40)
	at net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:21)
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:76)
	... 16 more

### Minecraft Version

MC 1.17.1

### Iris Version

iris-mc1.17.1-1.2.7

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce GTX1070

**Comment by Lolothepro** [comment]
Minecraft 1.17.1 is not supported
