### ISSUE TITLE
Iris Crashes when joining worlds

### ISSUE THREAD

**Issue by TheWimpyShrimp** [IrisShaders/Iris#2159]
### Minecraft Version

1.19.2

### Iris Version

Iris-mc1.19.2-1.6.10

### Sodium Version

 sodium-fabric-mc1.19.2-0.4.4+build.18.jar

### Operating System

Windows 11

### What is your GPU?

Gefore RTX 3060

### Java Version

Java 18?

### Reproduction Steps

1. In menu
2. Open any game
3. almost instantly loads to 100% has a seisure and crashes

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 2023-11-04 12:08:41
Description: Unexpected error

java.lang.IllegalStateException: Tried to use a destroyed GlResource
	at net.coderbot.iris.gl.GlResource.assertValid(GlResource.java:21)
	at net.coderbot.iris.gl.GlResource.getGlId(GlResource.java:26)
	at net.coderbot.iris.rendertarget.DepthTexture.getTextureId(DepthTexture.java:32)
	at net.coderbot.iris.gl.sampler.SamplerBinding.updateSampler(SamplerBinding.java:37)
	at net.coderbot.iris.gl.sampler.SamplerBinding.update(SamplerBinding.java:28)
	at net.coderbot.iris.gl.program.ProgramSamplers.update(ProgramSamplers.java:60)
	at net.coderbot.iris.pipeline.newshader.ExtendedShader.method_34586(ExtendedShader.java:201)
	at net.minecraft.class_291.method_34431(class_291.java:175)
	at net.minecraft.class_291.method_34427(class_291.java:121)
	at net.minecraft.class_286.method_43438(class_286.java:33)
	at net.minecraft.class_286.method_43433(class_286.java:26)
	at org.vivecraft.provider.VRRenderer.drawMask(VRRenderer.java:328)
	at org.vivecraft.provider.VRRenderer.doStencil(VRRenderer.java:198)
	at net.minecraft.class_757.drawEyeStencil(class_757.java:6591)
	at net.minecraft.class_761.handler$ckc000$stencil(class_761.java:5628)
	at net.minecraft.class_761.method_22710(class_761.java:1229)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.renderSingleView(class_310.java:14996)
	at net.minecraft.class_310.newRunTick(class_310.java:14589)
	at net.minecraft.class_310.handler$cip000$replaceTick(class_310.java:14331)
	at net.minecraft.class_310.method_1523(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.coderbot.iris.gl.GlResource.assertValid(GlResource.java:21)
	at net.coderbot.iris.gl.GlResource.getGlId(GlResource.java:26)
	at net.coderbot.iris.rendertarget.DepthTexture.getTextureId(DepthTexture.java:32)
	at net.coderbot.iris.gl.sampler.SamplerBinding.updateSampler(SamplerBinding.java:37)
	at net.coderbot.iris.gl.sampler.SamplerBinding.update(SamplerBinding.java:28)
	at net.coderbot.iris.gl.program.ProgramSamplers.update(ProgramSamplers.java:60)
	at net.coderbot.iris.pipeline.newshader.ExtendedShader.method_34586(ExtendedShader.java:201)
	at net.minecraft.class_291.method_34431(class_291.java:175)
	at net.minecraft.class_291.method_34427(class_291.java:121)
	at net.minecraft.class_286.method_43438(class_286.java:33)
	at net.minecraft.class_286.method_43433(class_286.java:26)
	at org.vivecraft.provider.VRRenderer.drawMask(VRRenderer.java:328)
	at org.vivecraft.provider.VRRenderer.doStencil(VRRenderer.java:198)
	at net.minecraft.class_757.drawEyeStencil(class_757.java:6591)
	at net.minecraft.class_761.handler$ckc000$stencil(class_761.java:5628)
	at net.minecraft.class_761.method_22710(class_761.java:1229)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.renderSingleView(class_310.java:14996)
	at net.minecraft.class_310.newRunTick(class_310.java:14589)

-- Affected level --
Details:
	All players: 1 total; [class_746['Kapoojr'/238, l='ClientLevel', x=10.85, y=65.67, z=-15.89]]
	Chunk stats: 4096, 713
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,83,0), Section: (at 0,3,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 61078 game time, 61078 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, illuminations/lowerres, lambdabettergrass/default, minecraft/supporteatinganimation, FreshAnimations_v1.7_Add_S8

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 798227272 bytes (761 MiB) / 2451570688 bytes (2338 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3400G with Radeon Vega Graphics    
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 3.69
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon(TM) RX Vega 11 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: DriverVersion=31.0.12027.9001
	Graphics card #1 name: NVIDIA GeForce RTX 3060
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2504
	Graphics card #1 versionInfo: DriverVersion=31.0.15.3758
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.93
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.93
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 33714.61
	Virtual memory used (MB): 27362.76
	Swap memory total (MB): 19456.00
	Swap memory used (MB): 907.85
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		ambientsounds: Ambient Sounds (Fabric) 5.2.13
		amplifiednether: Amplified nether 1.2
		architectury: Architectury 6.4.62
		auditory: Auditory 0.0.4-1.19.x
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.2
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterfortresses: YUNG's Better Nether Fortresses 1.19.2-Fabric-1.0.5
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.0
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		betterwitchhuts: YUNG's Better Witch Huts 1.19.2-Fabric-2.1.0
		cem: Custom Entity Models 0.7.1_S7_1.19
			completeconfig-base: completeconfig-base 2.0.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 2.0.2+1.19
		creativecore: CreativeCore (Fabric) 2.9.3
		cull-less-leaves: Cull Less Leaves 1.0.6
			com_github_llamalad7_mixinextras: mixinextras 0.0.12
			conditional-mixin: conditional mixin 0.3.0
		eatinganimationid: Eating Animation 1.9.1
		effective: Effective 1.2.2
		entityculling: EntityCulling-Fabric 1.6.1-mc1.19.2
		extrasounds: ExtraSounds 2.3.1+1.19.2-1.19.1
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			soundcategories: Sound Categories 1.2.4+1.19
		fabric-api: Fabric API 0.72.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.14+6e0787e690
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.13+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.23+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.4+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.15+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.0+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.32+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.40+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.6+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.34+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.3+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.33+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.33+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.3+9785ec3590
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.37+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.3+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.11+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.14+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.6+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.22+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.20+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.10+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.27+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.5+9785ec3590
			fabric-particles-v1: Fabric Particles (v1) 1.0.13+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.0+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.31+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.0+2e5408b590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.0+2e5408b590
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.23+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.18+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.10+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.26+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+08b73de490
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.31+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.6+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.23+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.5+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabricloader: Fabric Loader 0.14.13
		fallingleaves: Falling Leaves 1.13.0+1.19.2
		ferritecore: FerriteCore 5.0.3
		forgeconfigapiport: Forge Config API Port 4.2.10
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		illuminations: Illuminations 1.10.8
		immersivemc: ImmersiveMC 1.2.0
		indium: Indium 1.0.9+mc1.19.2
		iris: Iris 1.6.5
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
		lambdynlights: LambDynamicLights 2.2.0+1.19.2
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.1.0+1.19.2
		lithium: Lithium 0.10.4
		minecraft: Minecraft 1.19.2
		moreculling: More Culling 1.19.1-0.16.0
		perfectaccuracy: Perfect Accuracy 1.2-1.19
		presencefootsteps: Presence Footsteps 1.6.4
			kirin: Kirin UI 1.11.1
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.0.18
		spiderstpo: Spiders 2.0 1.19.2-2.0.3
		starlight: Starlight 1.1.1+fabric.ae22326
		treechop: HT's TreeChop 0.17.6
		visuality: Visuality 0.5.5
		vivecraft: Vivecraft 1.19.2-0.0.13
		vrapi: mc-vr-api 2.1.1
		yet-another-config-lib: YetAnotherConfigLib 2.2.0-for-1.19.2
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.9
			org_javassist_javassist: javassist 3.28.0-GA
		yungsextras: YUNG's Extras 1.19.2-Fabric-3.1.0
	Loaded Shaderpack: ComplementaryUnbound_r5.0.1.zip
		Profile: HIGH (+0 options changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.13-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 537.58, NVIDIA Corporation
	Window size: 2232x2252
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, illuminations/lowerres, lambdabettergrass/default, minecraft/supporteatinganimation, file/FreshAnimations_v1.7_Add_S8
	Current Language: English (US)
	CPU: 8x AMD Ryzen 5 3400G with Radeon Vega Graphics 
	Server Running: true
	Player Count: 1 / 8; [class_3222['Kapoojr'/238, l='ServerLevel[New World]', x=10.91, y=64.00, z=-15.71]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
```

### Additional context

I am using Fabric on curseforge while running vivecraft and am trying to get shaders for my vr play through except when I install iris via putting it in my mod pack it crashes on me.

**Comment by JosephTheMan** [comment]
I had the same problem, after looking at my crash file I had an incompatible mod "Block of sky." You likely just have a mod that tampers with Iris systems, I would go through and thin them down till you find it.

**Comment by Krzykarek** [comment]
Have you tried disabling shaders before entering a world, and enabling them alfter joining?
