### ISSUE TITLE
Iris prevents minecraft from launching (Code -1)

### ISSUE THREAD

**Issue by PurplePumkiin** [IrisShaders/Iris#2164]
### Minecraft Version

1.19.2, 1.20.2

### Iris Version

iris-mc1.20.2-1.6.10

### Sodium Version

sodium-fabric-mc1.20.2-0.5.3

### Operating System

Windows 10

### What is your GPU?

RTX 3070

### Java Version

Java 19

### Reproduction Steps

Have any installation of iris (standalone or installer based) loaded.

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2023-11-07 18:25:47
Description: Initializing game

java.lang.RuntimeException: Failed to obtain root directory for mod 'org_antlr_antlr4-runtime'!
	at net.fabricmc.loader.impl.ModContainerImpl.obtainRootPaths(ModContainerImpl.java:148)
	at net.fabricmc.loader.impl.ModContainerImpl.getRootPaths(ModContainerImpl.java:100)
	at net.fabricmc.fabric.impl.resource.loader.ModNioResourcePack.create(ModNioResourcePack.java:70)
	at net.fabricmc.fabric.impl.resource.loader.ModResourcePackUtil.appendModResourcePacks(ModResourcePackUtil.java:70)
	at net.fabricmc.fabric.impl.resource.loader.ModResourcePackCreator.method_14453(ModResourcePackCreator.java:77)
	at net.minecraft.class_315.handler$zka000$fabric-resource-loader-v0$onLoad(class_315.java:2874)
	at net.minecraft.class_315.method_1636(class_315.java:1481)
	at net.minecraft.class_315.<init>(class_315.java:1237)
	at net.minecraft.class_310.<init>(class_310.java:468)
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.io.IOException: Error accessing file:///C:/Users/Purple/AppData/Roaming/.minecraft/.fabric/processedMods/org_antlr_antlr4-runtime-4.11.1-d9d901aa6c03fd48.jar: java.util.zip.ZipException: zip END header not found
	at net.fabricmc.loader.impl.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:83)
	at net.fabricmc.loader.impl.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:59)
	at net.fabricmc.loader.impl.ModContainerImpl.obtainRootPath(ModContainerImpl.java:156)
	at net.fabricmc.loader.impl.ModContainerImpl.obtainRootPaths(ModContainerImpl.java:137)
	... 12 more
Caused by: java.util.zip.ZipException: zip END header not found
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1320)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1534)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:179)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:106)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288)
	at net.fabricmc.loader.impl.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:78)
	... 15 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.ModContainerImpl.obtainRootPaths(ModContainerImpl.java:148)
	at net.fabricmc.loader.impl.ModContainerImpl.getRootPaths(ModContainerImpl.java:100)
	at net.fabricmc.fabric.impl.resource.loader.ModNioResourcePack.create(ModNioResourcePack.java:70)
	at net.fabricmc.fabric.impl.resource.loader.ModResourcePackUtil.appendModResourcePacks(ModResourcePackUtil.java:70)
	at net.fabricmc.fabric.impl.resource.loader.ModResourcePackCreator.method_14453(ModResourcePackCreator.java:77)
	at net.minecraft.class_315.handler$zka000$fabric-resource-loader-v0$onLoad(class_315.java:2874)
	at net.minecraft.class_315.method_1636(class_315.java:1481)
	at net.minecraft.class_315.<init>(class_315.java:1237)
	at net.minecraft.class_310.<init>(class_310.java:468)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.23100.2009 (8fcbd1c22d82af16ba34560e1a70591413e88d17):Microsoft Corporation
		NLAapi.dll:Network Location Awareness 2:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		OleAut32.dll:OLEAUT32.DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		POWRPROF.dll:Power Profile Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Wldp.dll:Windows Lockdown Policy:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		java.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.8.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jna17652548785801623002.dll:JNA native library:6.1.6:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:17.0.8.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		ntdll.dll:NT Layer DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		win32u.dll:Win32u:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 242845848 bytes (231 MiB) / 570425344 bytes (544 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 32
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5950X 16-Core Processor            
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2484
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3623
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37528.22
	Virtual memory used (MB): 25340.05
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 178.14
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.90.7+1.20.2
			fabric-api-base: Fabric API Base 0.4.33+fce67b32a0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.42+b1792f7da0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.14+b1792f7da0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.12+73761d2ea0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+73761d2ea0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.43+f4b7e424a0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.4+86b12645a0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.37+f71b366fa0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.16+b1792f7da0
			fabric-commands-v0: Fabric Commands (v0) 0.2.54+df3654b3a0
			fabric-containers-v0: Fabric Containers (v0) 0.1.75+df3654b3a0
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.5+b1792f7da0
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.8+b1792f7da0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.20+f4b7e424a0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.5+b1792f7da0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.57+b1792f7da0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.26+b1792f7da0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.10+b1792f7da0
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.69+df3654b3a0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.42+a44e16a6a0
			fabric-item-api-v1: Fabric Item API (v1) 2.1.33+b1792f7da0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.15+e3d2bf3fa0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.38+f4b7e424a0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.36+df3654b3a0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.27+b1792f7da0
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.1+3ba460fba0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.2+e3d2bf3fa0
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.55+f4b7e424a0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.6+b1792f7da0
			fabric-models-v0: Fabric Models (v0) 0.4.5+9386d8a7a0
			fabric-networking-api-v1: Fabric Networking API (v1) 3.0.11+bff13c85a0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.2+2ff98d3ba0
			fabric-particles-v1: Fabric Particles (v1) 1.1.4+f4b7e424a0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.8+52b3ebe5a0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.6+b1792f7da0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+2034447ca0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+2034447ca0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.49+df3654b3a0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.39+73761d2ea0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.30+f4b7e424a0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.52+df3654b3a0
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.11+b1792f7da0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.10+e3d2bf3fa0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.12+b1792f7da0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.12+b1792f7da0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.41+b1792f7da0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.14+f4b7e424a0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.10+bb1ee60ea0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.3+fce67b32a0
		fabricloader: Fabric Loader 0.14.24
		iris: Iris 1.6.10
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.2
		sodium: Sodium 0.5.3
	JVM uptime in seconds: 9.785
	Launched Version: fabric-loader-0.14.24-1.20.2
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Locale: en_US
	CPU: <unknown>
```

### Additional context

Issue is occurring across two devices, so its not just this install
My preferred install is with the iris.jar file, its what I've always used. Current mods in fabric loader dir are:
fabric-api-0.90.7+1.20.2.jar
iris-mc1.20.2-1.6.10.jar
sodium-fabric-mc1.20.2-0.5.3.jar

And yes, I know its iris, without iris the game launches just fine.

**Comment by james090500** [comment]
Your install is corrupted. Delete this file:

Caused by: java.io.IOException: Error accessing `C:/Users/Purple/AppData/Roaming/.minecraft/.fabric/processedMods/org_antlr_antlr4-runtime-4.11.1-d9d901aa6c03fd48.jar`

If that doesn't work delete the `.fabric` folder in your `.minecraft`

**Comment by coderbot16** [comment]
That's a correct diagnosis - nothing else we can do here. Fabric should have better diagnostics here really.
