### ISSUE TITLE
In version 1.20.4, charging with sodium

### ISSUE THREAD

**Issue by gustn5170** [IrisShaders/Iris#2188]
### Minecraft Version

Minecraft 1.20.4

### Iris Version

iris-mc1.20.4-1.6.13

### Sodium Version

sodium-fabric-mc1.20.3-0.5.5

### Operating System

windows 11

### What is your GPU?

nvidia geforce rtx 3060

### Java Version

java 18.0.2.1

### Reproduction Steps

1. Place a Redstone Lamp in front of a Redstone Repeater
2. Use a Lever to activate the Redstone Repeater
3. Game Crashes
![2023-12-11 21 12 46](https://github.com/IrisShaders/Iris/assets/89198308/77e3eba1-ecbf-47a3-9dfe-e503b0e94be4)

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-11-05 23:32:13
Description: Rendering screen

java.lang.NoSuchFieldError: field_22757
	at dev.lambdaurora.spruceui.widget.AbstractSpruceButtonWidget.renderBackground(AbstractSpruceButtonWidget.java:157)
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25394(AbstractSpruceWidget.java:263)
	at dev.lambdaurora.spruceui.widget.container.SpruceOptionListWidget$OptionEntry.lambda$renderWidget$1(SpruceOptionListWidget.java:222)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at dev.lambdaurora.spruceui.widget.container.SpruceOptionListWidget$OptionEntry.renderWidget(SpruceOptionListWidget.java:222)
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25394(AbstractSpruceWidget.java:264)
	at dev.lambdaurora.spruceui.widget.container.SpruceEntryListWidget.lambda$renderWidget$0(SpruceEntryListWidget.java:340)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at dev.lambdaurora.spruceui.widget.container.SpruceEntryListWidget.renderWidget(SpruceEntryListWidget.java:340)
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25394(AbstractSpruceWidget.java:264)
	at dev.lambdaurora.spruceui.widget.container.SpruceContainerWidget.lambda$renderWidget$0(SpruceContainerWidget.java:82)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at dev.lambdaurora.spruceui.widget.container.SpruceContainerWidget.renderWidget(SpruceContainerWidget.java:82)
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25394(AbstractSpruceWidget.java:264)
	at dev.lambdaurora.spruceui.widget.container.tabbed.SpruceTabbedWidget.renderWidget(SpruceTabbedWidget.java:161)
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25394(AbstractSpruceWidget.java:264)
	at dev.lambdaurora.spruceui.screen.SpruceScreen.renderWidgets(SpruceScreen.java:128)
	at dev.lambdaurora.spruceui.screen.SpruceScreen.method_25394(SpruceScreen.java:116)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:946)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.lambdaurora.spruceui.widget.AbstractSpruceButtonWidget.renderBackground(AbstractSpruceButtonWidget.java:157)
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25394(AbstractSpruceWidget.java:263)
	at dev.lambdaurora.spruceui.widget.container.SpruceOptionListWidget$OptionEntry.lambda$renderWidget$1(SpruceOptionListWidget.java:222)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at dev.lambdaurora.spruceui.widget.container.SpruceOptionListWidget$OptionEntry.renderWidget(SpruceOptionListWidget.java:222)
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25394(AbstractSpruceWidget.java:264)
	at dev.lambdaurora.spruceui.widget.container.SpruceEntryListWidget.lambda$renderWidget$0(SpruceEntryListWidget.java:340)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at dev.lambdaurora.spruceui.widget.container.SpruceEntryListWidget.renderWidget(SpruceEntryListWidget.java:340)
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25394(AbstractSpruceWidget.java:264)
	at dev.lambdaurora.spruceui.widget.container.SpruceContainerWidget.lambda$renderWidget$0(SpruceContainerWidget.java:82)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at dev.lambdaurora.spruceui.widget.container.SpruceContainerWidget.renderWidget(SpruceContainerWidget.java:82)
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25394(AbstractSpruceWidget.java:264)
	at dev.lambdaurora.spruceui.widget.container.tabbed.SpruceTabbedWidget.renderWidget(SpruceTabbedWidget.java:161)
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25394(AbstractSpruceWidget.java:264)
	at dev.lambdaurora.spruceui.screen.SpruceScreen.renderWidgets(SpruceScreen.java:128)
	at dev.lambdaurora.spruceui.screen.SpruceScreen.method_25394(SpruceScreen.java:116)
	at net.minecraft.class_437.method_47413(class_437.java:110)

-- Screen render details --
Details:
	Screen name: dev.lambdaurora.lambdynlights.gui.SettingsScreen
	Mouse location: Scaled: (946, 52). Absolute: (1893.000000, 104.000000)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:946)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2488)
	at net.minecraft.class_310.method_1514(class_310.java:875)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 319302992 bytes (304 MiB) / 738197504 bytes (704 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=31.0.15.4601
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.80
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.80
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 26549.00
	Virtual memory used (MB): 12985.16
	Swap memory total (MB): 10240.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		dynamic_fps: Dynamic FPS 3.2.0
		fabric-api: Fabric API 0.89.2+1.20.2
			fabric-api-base: Fabric API Base 0.4.32+fce67b32a0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.40+fce67b32a0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.11+86b12645a0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+73761d2ea0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+73761d2ea0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.42+f4b7e424a0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.3+86b12645a0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.35+f71b366fa0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.14+86b12645a0
			fabric-commands-v0: Fabric Commands (v0) 0.2.52+df3654b3a0
			fabric-containers-v0: Fabric Containers (v0) 0.1.71+df3654b3a0
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.3+0ba8e9cea0
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.6+f4b7e424a0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+f4b7e424a0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.1+bbae80faa0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.55+b1229956a0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.24+f4b7e424a0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.8+daef22a2a0
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.67+df3654b3a0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+f4b7e424a0
			fabric-item-api-v1: Fabric Item API (v1) 2.1.31+43511215a0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+f4b7e424a0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+f4b7e424a0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b3a0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.25+3bafade3a0
			fabric-loot-api-v2: Fabric Loot API (v2) 2.0.1+0ba8e9cea0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.0+fce67b32a0
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.53+f4b7e424a0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.4+f4b7e424a0
			fabric-models-v0: Fabric Models (v0) 0.4.3+9386d8a7a0
			fabric-networking-api-v1: Fabric Networking API (v1) 3.0.7+74a33ae7a0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.0+b1b4f7b0a0
			fabric-particles-v1: Fabric Particles (v1) 1.1.3+f4b7e424a0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.4+43511215a0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.2+34a3e0e2a0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+2034447ca0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+2034447ca0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.47+df3654b3a0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.38+73761d2ea0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.29+f4b7e424a0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.50+df3654b3a0
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.9+86b12645a0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+43511215a0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+86b12645a0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.10+0ba8e9cea0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.37+86b12645a0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+f4b7e424a0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.7+109a65e5a0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.2+fce67b32a0
		fabricloader: Fabric Loader 0.14.22
		fpsreducer: FPS Reducer 1.20.2-2.6
		indium: Indium 1.0.27+mc1.20.1
		iris: Iris 1.6.9
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.0+1.20
		minecraft: Minecraft 1.20.2
		modmenu: Mod Menu 8.0.0
		nbt_ac: NBT Autocomplete 1.1.8
		no_fog: No Fog 1.3.4+1.16.5-1.20.1
		reeses-sodium-options: Reese's Sodium Options 1.6.5+mc1.20.2-build.96
		simplehudenhanced: Simple Hud Enhanced v3.1.0
			cloth-config: Cloth Config v11 11.0.98
				cloth-basic-math: cloth-basic-math 0.6.1
		sodium: Sodium 0.5.3
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	JVM uptime in seconds: 22.677
	Launched Version: fabric-loader-0.14.22-1.20.2
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 546.01, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric
	Current Language: ko_kr
	Locale: ko_KR
	CPU: 12x AMD Ryzen 5 5600X 6-Core Processor
```

### Additional context
![2023-12-11 21 18 08](https://github.com/IrisShaders/Iris/assets/89198308/3555d437-4b6c-451e-b453-ba4ae250b743)

_No response_

**Comment by josephworks** [comment]
This has been an issue for a couple of days now. Could someone bump the version number and release a hotfix?
