### ISSUE TITLE
Crashed while teleporting

### ISSUE THREAD

**Issue by tanyaofei** [IrisShaders/Iris#2191]
### Minecraft Version

1.20.2

### Iris Version

iris-mc1.20.20-1.6.14

### Sodium Version

sodium-fabric-mc1.20.2-0.5.5

### Operating System

Windows 11

### What is your GPU?

RTX 4070

### Java Version

java 17

### Reproduction Steps

Well , It will crashed somettime while teleporting

### Crash Report file and latest.log

```shell
[11:39:33] [Render thread/INFO]: [STDOUT]: failed 3565683856
[11:39:33] [Render thread/ERROR]: Exception when calling the full entity renderer before rendering the icon. 50725a8e-4e9d-4d77-92a3-bac66283cf93
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1921.method_23033()" because "<parameter1>" is null
	at net.coderbot.batchedentityrendering.impl.RenderTypeUtil.isTriangleStripDrawMode(RenderTypeUtil.java:8) ~[iris-mc1.20.2-1.6.14.jar:?]
	at net.coderbot.batchedentityrendering.impl.SegmentedBufferBuilder.getBuffer(SegmentedBufferBuilder.java:47) ~[iris-mc1.20.2-1.6.14.jar:?]
	at net.coderbot.batchedentityrendering.impl.FullyBufferedMultiBufferSource.getBuffer(FullyBufferedMultiBufferSource.java:93) ~[iris-mc1.20.2-1.6.14.jar:?]
	at traben.entity_texture_features.features.ETFRenderContext.processVertexConsumer(ETFRenderContext.java:107) ~[entity_texture_features_fabric_1.20.2-5.0.jar:?]
	at traben.entity_model_features.models.EMFModelPart.renderWithTextureOverride(EMFModelPart.java:65) ~[entity_model_features_fabric_1.20.2-1.2.jar:?]
	at traben.entity_model_features.models.EMFModelPartCustom.method_22699(EMFModelPartCustom.java:129) ~[entity_model_features_fabric_1.20.2-1.2.jar:?]
	at traben.entity_model_features.models.EMFModelPart.renderLikeVanilla(EMFModelPart.java:81) ~[entity_model_features_fabric_1.20.2-1.2.jar:?]
	at traben.entity_model_features.models.EMFModelPart.renderLikeETF(EMFModelPart.java:94) ~[entity_model_features_fabric_1.20.2-1.2.jar:?]
	at traben.entity_model_features.models.EMFModelPart.renderWithTextureOverride(EMFModelPart.java:47) ~[entity_model_features_fabric_1.20.2-1.2.jar:?]
	at traben.entity_model_features.models.EMFModelPartWithState.method_22699(EMFModelPartWithState.java:46) ~[entity_model_features_fabric_1.20.2-1.2.jar:?]
	at traben.entity_model_features.models.EMFModelPartVanilla.method_22699(EMFModelPartVanilla.java:62) ~[entity_model_features_fabric_1.20.2-1.2.jar:?]
	at net.minecraft.class_4592.method_22947(class_4592.java:63) ~[client-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.2-jre.jar:?]
	at net.minecraft.class_4592.method_2828(class_4592.java:63) ~[client-intermediary.jar:?]
	at net.minecraft.class_922.method_4054(class_922.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.class_927.method_4072(class_927.java:45) ~[client-intermediary.jar:?]
	at net.minecraft.class_927.method_3936(class_927.java:18) ~[client-intermediary.jar:?]
	at xaero.common.minimap.render.radar.EntityIconPrerenderer.prerender(EntityIconPrerenderer.java:309) ~[Xaeros_Minimap_23.9.3_Fabric_1.20.2.jar:?]
	at xaero.common.minimap.render.radar.EntityIconManager.getEntityHeadTexture(EntityIconManager.java:158) ~[Xaeros_Minimap_23.9.3_Fabric_1.20.2.jar:?]
	at xaero.common.minimap.render.radar.element.RadarRenderer.renderElement(RadarRenderer.java:113) ~[Xaeros_Minimap_23.9.3_Fabric_1.20.2.jar:?]
	at xaero.common.minimap.render.radar.element.RadarRenderer.renderElement(RadarRenderer.java:35) ~[Xaeros_Minimap_23.9.3_Fabric_1.20.2.jar:?]
	at xaero.common.minimap.element.render.map.MinimapElementMapRendererHandler.transformAndRenderForRenderer(MinimapElementMapRendererHandler.java:61) ~[Xaeros_Minimap_23.9.3_Fabric_1.20.2.jar:?]
	at xaero.common.minimap.element.render.MinimapElementRendererHandler.renderForRenderer(MinimapElementRendererHandler.java:68) ~[Xaeros_Minimap_23.9.3_Fabric_1.20.2.jar:?]
	at xaero.common.minimap.element.render.MinimapElementRendererHandler.render(MinimapElementRendererHandler.java:43) ~[Xaeros_Minimap_23.9.3_Fabric_1.20.2.jar:?]
	at xaero.common.minimap.element.render.map.MinimapElementMapRendererHandler.render(MinimapElementMapRendererHandler.java:36) ~[Xaeros_Minimap_23.9.3_Fabric_1.20.2.jar:?]
	at xaero.common.minimap.render.MinimapFBORenderer.renderChunksToFBO(MinimapFBORenderer.java:319) ~[Xaeros_Minimap_23.9.3_Fabric_1.20.2.jar:?]
	at xaero.common.minimap.render.MinimapFBORenderer.renderChunks(MinimapFBORenderer.java:92) ~[Xaeros_Minimap_23.9.3_Fabric_1.20.2.jar:?]
	at xaero.common.minimap.render.MinimapRenderer.renderMinimap(MinimapRenderer.java:148) ~[Xaeros_Minimap_23.9.3_Fabric_1.20.2.jar:?]
	at xaero.common.minimap.MinimapProcessor.onRender(MinimapProcessor.java:152) ~[Xaeros_Minimap_23.9.3_Fabric_1.20.2.jar:?]
	at xaero.common.minimap.MinimapInterfaceInstance.render(MinimapInterfaceInstance.java:51) ~[Xaeros_Minimap_23.9.3_Fabric_1.20.2.jar:?]
	at xaero.common.interfaces.render.InterfaceRenderer.renderInterfaces(InterfaceRenderer.java:65) ~[Xaeros_Minimap_23.9.3_Fabric_1.20.2.jar:?]
	at xaero.common.events.ForgeEventHandler.handleRenderGameOverlayEventPreOverridable(ForgeEventHandler.java:114) ~[Xaeros_Minimap_23.9.3_Fabric_1.20.2.jar:?]
	at xaero.common.events.ForgeEventHandler.handleRenderGameOverlayEventPre(ForgeEventHandler.java:127) ~[Xaeros_Minimap_23.9.3_Fabric_1.20.2.jar:?]
	at net.minecraft.class_329.handler$cph001$xaerominimap$onRender(class_329.java:6470) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:227) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:927) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1275) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[1.20.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.1.jar:?]
[11:39:33] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1921.method_23516()" because "<local3>" is null
	at net.coderbot.batchedentityrendering.impl.FullyBufferedMultiBufferSource.method_22993(FullyBufferedMultiBufferSource.java:136) ~[iris-mc1.20.2-1.6.14.jar:?]
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:519) ~[iris-mc1.20.2-1.6.14.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:1039) ~[iris-mc1.20.2-1.6.14.jar:?]
	at net.minecraft.class_761.handler$bfm000$iris$renderTerrainShadows(class_761.java:6222) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1009) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1113) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:881) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1275) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[1.20.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.1.jar:?]
[11:39:34] [Render thread/INFO]: pcaSyncProtocol onDisconnect.
[11:39:34] [Render thread/INFO]: Minimap session finalized.
[11:39:34] [Render thread/INFO]: Finalizing world map session...
[11:39:34] [Thread-3/INFO]: World map force-cleaned!
[11:39:34] [Render thread/INFO]: World map session finalized.
[11:39:34] [Render thread/INFO]: Stopping worker threads
[11:39:34] [Render thread/INFO]: emissive suffixes loaded: {_e}.
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2023-12-16 11:39:34
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1921.method_23516()" because "<local3>" is null
	at net.coderbot.batchedentityrendering.impl.FullyBufferedMultiBufferSource.method_22993(FullyBufferedMultiBufferSource.java:136)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:519)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:1039)
	at net.minecraft.class_761.handler$bfm000$iris$renderTerrainShadows(class_761.java:6222)
	at net.minecraft.class_761.method_22710(class_761.java:1009)
	at net.minecraft.class_757.method_3188(class_757.java:1113)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.coderbot.batchedentityrendering.impl.FullyBufferedMultiBufferSource.method_22993(FullyBufferedMultiBufferSource.java:136)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:519)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:1039)
	at net.minecraft.class_761.handler$bfm000$iris$renderTerrainShadows(class_761.java:6222)
	at net.minecraft.class_761.method_22710(class_761.java:1009)
	at net.minecraft.class_757.method_3188(class_757.java:1113)

-- Affected level --
Details:
	All players: 2 total; [class_746['hello09x'/12802976, l='ClientLevel', x=1535.63, y=198.00, z=448.56], class_745['PackagePaper_'/12611422, l='ClientLevel', x=1535.40, y=198.00, z=448.30]]
	Chunk stats: 1024, 7
	Level dimension: minecraft:overworld
	Level spawn location: World: (64,68,-96), Section: (at 0,4,0 in 4,4,-6; chunk contains blocks 64,-64,-96 to 79,319,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 455560635 game time, 486962110 day time
	Server brand: XCord (git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4d16c9f:541)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:451)
	at net.minecraft.class_310.method_1587(class_310.java:2481)
	at net.minecraft.class_310.method_1514(class_310.java:880)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/[生物动画拓展]FA+All_Extensions-v1.2.zip, file/[生物动画]FreshAnimations_v1.8.1.zip, file/Minecraft-Mod-Language-Modpack-Converted-1.20.2.zip, file/QuickResources-612f8e6d457358ec5e8d32c5c453df6c3263b914.zip, file/§l梧桐加减法Re 2.1.zip

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 532121664 bytes (507 MiB) / 1677721600 bytes (1600 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i5-13600KF
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.49
	Number of physical packages: 1
	Number of physical CPUs: 14
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 4070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2786
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3742
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 5.60
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 5.60
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 34664.17
	Virtual memory used (MB): 21217.17
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 59.91
	JVM Flags: 11 total; -Xmx4096m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		advanced-xray-fabric: Advanced XRay (Fabric) 82.0.0
		architectury: Architectury 10.0.17
		chat_heads: Chat Heads 0.10.27
		cloth-config: Cloth Config v12 12.0.113
			cloth-basic-math: cloth-basic-math 0.6.1
		controlling: Controlling For Fabric 13.0.1
		customskinloader: CustomSkinLoader 14.18.3
		double_hotbar: Double Hotbar 1.3.1-mc1.20.2-fabric
		entity_model_features: Entity Model Features 1.2
		entity_texture_features: Entity Texture Features 5.0
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		fabric-api: Fabric API 0.91.2+1.20.2
			fabric-api-base: Fabric API Base 0.4.33+fce67b32a0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.42+b1792f7da0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.14+b1792f7da0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.12+73761d2ea0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+73761d2ea0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.43+f4b7e424a0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.4+86b12645a0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.37+f71b366fa0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.16+b1792f7da0
			fabric-commands-v0: Fabric Commands (v0) 0.2.54+df3654b3a0
			fabric-containers-v0: Fabric Containers (v0) 0.1.78+df3654b3a0
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.5+b1792f7da0
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.8+b1792f7da0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.20+f4b7e424a0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.8+b1792f7da0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.57+b1792f7da0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.26+b1792f7da0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.10+b1792f7da0
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.69+df3654b3a0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.42+a44e16a6a0
			fabric-item-api-v1: Fabric Item API (v1) 2.1.33+b1792f7da0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.15+e3d2bf3fa0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.38+f4b7e424a0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.36+df3654b3a0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.27+b1792f7da0
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.1+3ba460fba0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.2+e3d2bf3fa0
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.55+f4b7e424a0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.6+b1792f7da0
			fabric-models-v0: Fabric Models (v0) 0.4.5+9386d8a7a0
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.2+95a8ac51a0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.2+2ff98d3ba0
			fabric-particles-v1: Fabric Particles (v1) 1.1.4+f4b7e424a0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.11+52b3ebe5a0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.9+b1792f7da0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+2034447ca0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+2034447ca0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.49+df3654b3a0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.39+73761d2ea0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.30+f4b7e424a0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.52+df3654b3a0
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.11+b1792f7da0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.11+239dafd8a0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.12+b1792f7da0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.12+b1792f7da0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.44+b1792f7da0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.14+f4b7e424a0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.12+4944b5a5a0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.3+fce67b32a0
		fabric-language-kotlin: Fabric Language Kotlin 1.10.16+kotlin.1.9.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.1
			mixinextras: MixinExtras 0.3.1
		fpsreducer: FPS Reducer 1.20.2-2.6
		i18nupdatemod: I18nUpdateMod 3.5.2
		ias: In-Game Account Switcher 8.0.2
		ingameime: ContingameIME 1.0.6-1.20.1
		inventoryhud: Inventory HUD + 3.4.19
		inventoryprofilesnext: Inventory Profiles Next 1.10.9
		iris: Iris 1.6.14
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemscroller: Item Scroller 0.21.0
		java: Java HotSpot(TM) 64-Bit Server VM 17
		lazydfu: LazyDFU 0.1.3
		libgui: LibGui 9.2.1+1.20.2
			jankson: Jankson 6.0.0+j1.2.3
				blue_endless_jankson: jankson 1.2.3
			libninepatch: LibNinePatch 1.2.0
		libipn: libIPN 4.0.1
		litematica: Litematica 0.16.0
		magiclib: MagicLib 0.7.387+c02a0de-stable
			magiclib-1_20_2: MagicLib for 1.20.2 0.7.387+c02a0de-stable
		malilib: MaLiLib 0.17.0
		masa_gadget_mod: Masa Gadget 3.2.331+61c3583-stable
			masa_gadget_mod-1_20_2: Masa Gadget for 1.20.2 3.2.331+61c3583-stable
		minecraft: Minecraft 1.20.2
		minihud: MiniHUD 0.28.0
		modmenu: Mod Menu 8.0.0
		quickresources: QuickResources Fabric-1.20.2-0.0.1
		reeses-sodium-options: Reese's Sodium Options 1.7.0+mc1.20.2-build.97
		roughlyenoughitems: Roughly Enough Items 13.0.679
			error_notifier: Error Notifier 1.0.9
		searchables: Searchables 1.0.3
		skinlayers: 3d Skin Layers 1.5.6-mc1.20.2
		smoothscroll: Smooth Scrolling 1.8.1
		sodium: Sodium 0.5.5
		sodium-extra: Sodium Extra 0.5.3+mc1.20.2-build.114
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		tweakeroo: Tweakeroo 0.18.0
		wurst: Wurst Client v7.39-MC1.20.2
		xaerominimap: Xaero's Minimap 23.9.3
		xaeroworldmap: Xaero's World Map 1.37.2
	Loaded Shaderpack: [光影][汉化]ComplementaryShaders_v4.7.2.zip
		Profile: Custom (+10 options changed by user)
	JVM uptime in seconds: 440.598
	Launched Version: 1.20.2
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce RTX 4070/PCIe/SSE2 GL version 3.2.0 NVIDIA 537.42, NVIDIA Corporation
	Window size: 2530x1497
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/[生物动画拓展]FA+All_Extensions-v1.2.zip (incompatible), file/[生物动画]FreshAnimations_v1.8.1.zip (incompatible), file/Minecraft-Mod-Language-Modpack-Converted-1.20.2.zip, file/QuickResources-612f8e6d457358ec5e8d32c5c453df6c3263b914.zip (incompatible), file/§l梧桐加减法Re 2.1.zip
	Current Language: zh_cn
	Locale: zh_CN
	CPU: 20x 13th Gen Intel(R) Core(TM) i5-13600KF
```

**Comment by 2el222** [comment]
Had the same crash 
[latest.log](https://github.com/IrisShaders/Iris/files/13702280/latest.log)

**Comment by GeekyBakerBen** [comment]
Likewise, just had same crash on 1.20.1 when lightning hit an Enderman I was killing.

**Comment by KAGUYA-1137** [comment]
It crashes a short while after entering the world.
If deleted Iris, the crash does not occur, so there is no doubt that Iris is the cause.
[crash-2023-12-18_11.15.52-client.txt](https://github.com/IrisShaders/Iris/files/13758143/crash-2023-12-18_11.15.52-client.txt)

**Comment by IMS212** [comment]
Try removing Entity Texture Features.
