### ISSUE TITLE
Incompatibility with fabricmc's sponge-mixin 0.13.0+mixin.0.8.5

### ISSUE THREAD

**Issue by Kichura** [IrisShaders/Iris#2269]
### Minecraft Version

1.20.4

### Iris Version

iris-mc1.20.4-1.6.17

### Sodium Version

sodium-fabric-0.5.8+mc1.20.4

### Operating System

Fedora Linux 39

### What is your GPU?

AMD Radeon RX 6750 XT

### Java Version

Java 17.0.10 (BellSoft)

### Reproduction Steps

1. Create a new client instance using any launcher that also contains fabric,
2. Modify the fabric loader to make use of the latest sponge-mixin that fabricmc offers,
3. Install Iris and Sodium as normal and run the client,
4. Try to enter the video settings,
5. Expect the game to crash from here.

### Crash Report file and latest.log

```shell
[17:53:13] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.7
[17:53:13] [main/INFO]: Loading 15 mods:
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- iris 1.6.17
	   |-- fabric-key-binding-api-v1 1.0.23+aaaf9d332d
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- minecraft 1.20.4
	- sodium 0.5.8+mc1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.0.33+78d798af4f
	   \-- fabric-resource-loader-v0 0.11.17+707e4d1b4f
[17:53:13] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/kichura/.local/share/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.13.0+mixin.0.8.5/sponge-mixin-0.13.0+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[17:53:13] [main/INFO]: Compatibility level set to JAVA_17
[17:53:14] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 3 override(s) found
[17:53:14] [main/WARN]: Force-disabling mixin 'features.render.entity.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[17:53:14] [main/WARN]: Force-disabling mixin 'features.render.entity.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[17:53:14] [main/WARN]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[17:53:14] [main/WARN]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[17:53:14] [main/WARN]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [iris]) disables it and children
[17:53:14] [main/WARN]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[17:53:14] [main/WARN]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[17:53:14] [main/WARN]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[17:53:14] [main/INFO]: Searching for graphics cards...
[17:53:14] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=AMD, name=Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT], version=unknown]
[17:53:14] [main/WARN]: Sodium has applied one or more workarounds to prevent crashes or other issues on your system: [NO_ERROR_CONTEXT_UNSUPPORTED]
[17:53:14] [main/WARN]: This is not necessarily an issue, but it may result in certain features or optimizations being disabled. You can sometimes fix these issues by upgrading your graphics driver.
[17:53:14] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[17:53:17] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 125 milliseconds
[17:53:18] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[17:53:18] [Render thread/INFO]: Setting user: Mesa3D
[17:53:18] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[17:53:18] [Render thread/INFO]: OpenGL Vendor: AMD
[17:53:18] [Render thread/INFO]: OpenGL Renderer: AMD Radeon RX 6750 XT (radeonsi, navi22, LLVM 17.0.6, DRM 3.57, 6.7.7-200.fc39.x86_64)
[17:53:18] [Render thread/INFO]: OpenGL Version: 4.6 (Core Profile) Mesa 24.0.2
[17:53:18] [Render thread/INFO]: Debug functionality is disabled.
[17:53:18] [Render thread/INFO]: OpenGL 4.5 detected, enabling DSA.
[17:53:18] [Render thread/INFO]: Shaders are disabled because no valid shaderpack is selected
[17:53:18] [Render thread/INFO]: Shaders are disabled
[17:53:19] [Render thread/INFO]: Hardware information:
[17:53:19] [Render thread/INFO]: CPU: 16x AMD Ryzen 7 5700G with Radeon Graphics
[17:53:19] [Render thread/INFO]: GPU: AMD Radeon RX 6750 XT (radeonsi, navi22, LLVM 17.0.6, DRM 3.57, 6.7.7-200.fc39.x86_64) (Supports OpenGL 4.6 (Core Profile) Mesa 24.0.2)
[17:53:19] [Render thread/INFO]: OS: Linux (6.7.7-200.fc39.x86_64)
[17:53:19] [ForkJoinPool.commonPool-worker-1/WARN]: [Iris Update Check] This version doesn't have an update index, skipping.
[17:53:19] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric, fabric-api-base, fabric-block-view-api-v2, fabric-key-binding-api-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-resource-loader-v0, fabricloader, iris, sodium
[17:53:19] [Worker-Main-12/INFO]: Found unifont_all_no_pua-15.1.04.hex, loading
[17:53:20] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[17:53:20] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[17:53:20] [Render thread/INFO]: OpenAL initialized on device Teufel ZOLA Analog Stereo
[17:53:20] [Render thread/INFO]: Sound engine started
[17:53:20] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[17:53:20] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[17:53:20] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[17:53:20] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[17:53:20] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[17:53:20] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[17:53:20] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[17:53:20] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[17:53:20] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[17:53:21] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[17:53:21] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[17:53:21] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[17:53:21] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[17:53:21] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[17:53:21] [Render thread/INFO]: Creating pipeline for dimension NamespacedId{namespace='minecraft', name='overworld'}
[17:53:24] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:180) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:180) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509) ~[lwjgl-glfw-3.3.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:238) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1352) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    me/jellysquid/mods/sodium/client/gui/SodiumGameOptionPages.quality()Lme/jellysquid/mods/sodium/client/gui/options/OptionPage; @93: invokestatic
  Reason:
    Type 'me/jellysquid/mods/sodium/client/gui/options/Option' (current frame, stack[1]) is not assignable to 'me/jellysquid/mods/sodium/client/gui/options/OptionGroup$Builder'
  Current Frame:
    bci: @93
    flags: { }
    locals: { 'java/util/ArrayList', 'me/jellysquid/mods/sodium/client/gui/options/OptionGroup$Builder', 'me/jellysquid/mods/sodium/client/gui/options/OptionImpl' }
    stack: { 'java/util/ArrayList', 'me/jellysquid/mods/sodium/client/gui/options/Option', 'me/jellysquid/mods/sodium/client/gui/options/OptionImpl' }
  Bytecode:
    0000000: bb00 3659 b700 374b 2ab8 003b 1301 79b2
    0000010: 0043 b800 4613 017b b800 4eb6 0052 1301
    0000020: 7db8 004e b600 57ba 0182 0000 b600 6eba
    0000030: 0189 0000 ba01 9000 00b6 0085 b200 8bb6
    0000040: 008f 04bd 0091 5903 b200 9553 b600 99b6
    0000050: 009d 4d4c 2b2c 4d4c 2bb8 0194 2cb8 0197
    0000060: b600 ceb9 00d3 0200 572a b800 3b13 0199
    0000070: b200 43b8 0046 1301 9bb8 004e b600 5213
    0000080: 019d b800 4eb6 0057 ba01 a200 00b6 006e
    0000090: ba01 a900 00ba 01b0 0000 b600 85b2 01b3
    00000a0: b600 8fb6 009d b600 b812 11b2 01b5 b800
    00000b0: 4613 01b7 b800 4eb6 0052 1301 b9b8 004e
    00000c0: b600 57ba 01be 0000 b600 6eba 01c5 0000
    00000d0: ba01 cc00 00b6 0085 b201 cfb6 008f b600
    00000e0: 9db6 00b8 1211 b201 b5b8 0046 1301 d1b8
    00000f0: 004e b600 5213 01d3 b800 4eb6 0057 ba01
    0000100: d800 00b6 006e ba01 dd00 00ba 01e2 0000
    0000110: b600 85b2 01cf b600 8f04 bd00 9159 03b2
    0000120: 0095 53b6 0099 b600 9db6 00b8 1301 e4b2
    0000130: 0043 b800 4613 01e6 b800 4eb6 0052 1301
    0000140: e8b8 004e b600 57ba 01ed 0000 b600 6eba
    0000150: 01f4 0000 ba01 fb00 00b6 0085 b201 cfb6
    0000160: 008f b600 9db6 00b8 b200 e9b2 0043 b800
    0000170: 4613 01fd b800 4eb6 0052 1301 ffb8 004e
    0000180: b600 57ba 00f4 0000 b600 6eba 0204 0000
    0000190: ba02 0900 00b6 0085 b201 b3b6 008f 04bd
    00001a0: 0091 5903 b200 9553 b600 99b6 009d b600
    00001b0: b8b2 0041 b200 43b8 0046 1302 0bb8 004e
    00001c0: b600 5213 020d b800 4eb6 0057 ba02 1200
    00001d0: 00b6 006e ba02 1700 00ba 021c 0000 b600
    00001e0: 85b2 01b3 b600 8f04 bd00 9159 03b2 0095
    00001f0: 53b6 0099 b600 9db6 00b8 b200 41b2 0043
    0000200: b800 4613 021e b800 4eb6 0052 1302 20b8
    0000210: 004e b600 57ba 0225 0000 b600 6eba 022a
    0000220: 0000 ba02 2f00 00b6 0085 b200 8bb6 008f
    0000230: b600 9db6 00b8 b200 e9b2 0043 b800 4613
    0000240: 0231 b800 4eb6 0052 1302 33b8 004e b600
    0000250: 57ba 00f4 0000 b600 6eba 0238 0000 ba02
    0000260: 3d00 00b6 0085 b201 cfb6 008f b600 9db6
    0000270: 00b8 b200 e9b2 01b5 b800 4613 023f b800
    0000280: 4eb6 0052 1302 41b8 004e b600 57ba 00f4
    0000290: 0000 b600 6eba 0248 0000 ba02 4f00 00b6
    00002a0: 0085 b600 9db6 00b8 b600 ceb9 00d3 0200
    00002b0: 572a b800 3bb2 0041 b200 43b8 0046 1302
    00002c0: 51b8 004e b600 5213 0253 b800 4eb6 0057
    00002d0: ba02 5800 00b6 006e ba02 5d00 00ba 0262
    00002e0: 0000 b600 85b2 01cf b600 8f04 bd00 9159
    00002f0: 03b2 0265 53b6 0099 b600 9db6 00b8 b600
    0000300: ceb9 00d3 0200 57bb 0164 5913 0267 b800
    0000310: 4e2a b801 6cb7 016f b0

	at me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.<init>(SodiumOptionsGUI.java:63) ~[sodium-fabric-0.5.8+mc1.20.4.jar:?]
	at me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.createScreen(SodiumOptionsGUI.java:128) ~[sodium-fabric-0.5.8+mc1.20.4.jar:?]
	at net.minecraft.class_429.handler$zjj000$sodium$open(class_429.java:522) ~[client-intermediary.jar:?]
	at net.minecraft.class_429.method_19828(class_429.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_429.method_47624(class_429.java:152) ~[client-intermediary.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:95) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:414) ~[client-intermediary.jar:?]
	... 17 more
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2024-03-07 17:53:24
Description: mouseClicked event handler

java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    me/jellysquid/mods/sodium/client/gui/SodiumGameOptionPages.quality()Lme/jellysquid/mods/sodium/client/gui/options/OptionPage; @93: invokestatic
  Reason:
    Type 'me/jellysquid/mods/sodium/client/gui/options/Option' (current frame, stack[1]) is not assignable to 'me/jellysquid/mods/sodium/client/gui/options/OptionGroup$Builder'
  Current Frame:
    bci: @93
    flags: { }
    locals: { 'java/util/ArrayList', 'me/jellysquid/mods/sodium/client/gui/options/OptionGroup$Builder', 'me/jellysquid/mods/sodium/client/gui/options/OptionImpl' }
    stack: { 'java/util/ArrayList', 'me/jellysquid/mods/sodium/client/gui/options/Option', 'me/jellysquid/mods/sodium/client/gui/options/OptionImpl' }
  Bytecode:
    0000000: bb00 3659 b700 374b 2ab8 003b 1301 79b2
    0000010: 0043 b800 4613 017b b800 4eb6 0052 1301
    0000020: 7db8 004e b600 57ba 0182 0000 b600 6eba
    0000030: 0189 0000 ba01 9000 00b6 0085 b200 8bb6
    0000040: 008f 04bd 0091 5903 b200 9553 b600 99b6
    0000050: 009d 4d4c 2b2c 4d4c 2bb8 0194 2cb8 0197
    0000060: b600 ceb9 00d3 0200 572a b800 3b13 0199
    0000070: b200 43b8 0046 1301 9bb8 004e b600 5213
    0000080: 019d b800 4eb6 0057 ba01 a200 00b6 006e
    0000090: ba01 a900 00ba 01b0 0000 b600 85b2 01b3
    00000a0: b600 8fb6 009d b600 b812 11b2 01b5 b800
    00000b0: 4613 01b7 b800 4eb6 0052 1301 b9b8 004e
    00000c0: b600 57ba 01be 0000 b600 6eba 01c5 0000
    00000d0: ba01 cc00 00b6 0085 b201 cfb6 008f b600
    00000e0: 9db6 00b8 1211 b201 b5b8 0046 1301 d1b8
    00000f0: 004e b600 5213 01d3 b800 4eb6 0057 ba01
    0000100: d800 00b6 006e ba01 dd00 00ba 01e2 0000
    0000110: b600 85b2 01cf b600 8f04 bd00 9159 03b2
    0000120: 0095 53b6 0099 b600 9db6 00b8 1301 e4b2
    0000130: 0043 b800 4613 01e6 b800 4eb6 0052 1301
    0000140: e8b8 004e b600 57ba 01ed 0000 b600 6eba
    0000150: 01f4 0000 ba01 fb00 00b6 0085 b201 cfb6
    0000160: 008f b600 9db6 00b8 b200 e9b2 0043 b800
    0000170: 4613 01fd b800 4eb6 0052 1301 ffb8 004e
    0000180: b600 57ba 00f4 0000 b600 6eba 0204 0000
    0000190: ba02 0900 00b6 0085 b201 b3b6 008f 04bd
    00001a0: 0091 5903 b200 9553 b600 99b6 009d b600
    00001b0: b8b2 0041 b200 43b8 0046 1302 0bb8 004e
    00001c0: b600 5213 020d b800 4eb6 0057 ba02 1200
    00001d0: 00b6 006e ba02 1700 00ba 021c 0000 b600
    00001e0: 85b2 01b3 b600 8f04 bd00 9159 03b2 0095
    00001f0: 53b6 0099 b600 9db6 00b8 b200 41b2 0043
    0000200: b800 4613 021e b800 4eb6 0052 1302 20b8
    0000210: 004e b600 57ba 0225 0000 b600 6eba 022a
    0000220: 0000 ba02 2f00 00b6 0085 b200 8bb6 008f
    0000230: b600 9db6 00b8 b200 e9b2 0043 b800 4613
    0000240: 0231 b800 4eb6 0052 1302 33b8 004e b600
    0000250: 57ba 00f4 0000 b600 6eba 0238 0000 ba02
    0000260: 3d00 00b6 0085 b201 cfb6 008f b600 9db6
    0000270: 00b8 b200 e9b2 01b5 b800 4613 023f b800
    0000280: 4eb6 0052 1302 41b8 004e b600 57ba 00f4
    0000290: 0000 b600 6eba 0248 0000 ba02 4f00 00b6
    00002a0: 0085 b600 9db6 00b8 b600 ceb9 00d3 0200
    00002b0: 572a b800 3bb2 0041 b200 43b8 0046 1302
    00002c0: 51b8 004e b600 5213 0253 b800 4eb6 0057
    00002d0: ba02 5800 00b6 006e ba02 5d00 00ba 0262
    00002e0: 0000 b600 85b2 01cf b600 8f04 bd00 9159
    00002f0: 03b2 0265 53b6 0099 b600 9db6 00b8 b600
    0000300: ceb9 00d3 0200 57bb 0164 5913 0267 b800
    0000310: 4e2a b801 6cb7 016f b0

	at me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.<init>(SodiumOptionsGUI.java:63)
	at me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.createScreen(SodiumOptionsGUI.java:128)
	at net.minecraft.class_429.handler$zjj000$sodium$open(class_429.java:522)
	at net.minecraft.class_429.method_19828(class_429.java)
	at net.minecraft.class_429.method_47624(class_429.java:152)
	at net.minecraft.class_4185.method_25306(class_4185.java:95)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:145)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:99)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:238)
	at net.minecraft.class_310.method_1523(class_310.java:1352)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.<init>(SodiumOptionsGUI.java:63)
	at me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.createScreen(SodiumOptionsGUI.java:128)
	at net.minecraft.class_429.handler$zjj000$sodium$open(class_429.java:522)
	at net.minecraft.class_429.method_19828(class_429.java)
	at net.minecraft.class_429.method_47624(class_429.java:152)
	at net.minecraft.class_4185.method_25306(class_4185.java:95)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:145)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:99)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_429
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:238)
	at net.minecraft.class_310.method_1523(class_310.java:1352)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Uptime --
Details:
	JVM uptime: 11.073s
	Wall uptime: 6.026s
	High-res time: 5.649s
	Client ticks: 97 ticks / 4.850s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:908)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, fabric-api-base, fabric-block-view-api-v2, fabric-key-binding-api-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-resource-loader-v0, fabricloader, iris, sodium

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Linux (amd64) version 6.7.7-200.fc39.x86_64
	Java Version: 17.0.10, BellSoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), BellSoft
	Memory: 3629361384 bytes (3461 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5700G with Radeon Graphics
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 16386.00
	Graphics card #0 deviceId: 0x73df
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 24133.33
	Virtual memory used (MB): 6762.02
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 87.25
	JVM Flags: 8 total; -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xms4096m -Xmx4096m
	Loaded Shaderpack: (off)
	Launched Version: 1.20.4
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: AMD Radeon RX 6750 XT (radeonsi, navi22, LLVM 17.0.6, DRM 3.57, 6.7.7-200.fc39.x86_64) GL version 4.6 (Core Profile) Mesa 24.0.2, AMD
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages:
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: fabric
	Current Language: en_us
	Locale: en_US
	CPU: 16x AMD Ryzen 7 5700G with Radeon Graphics
```

### Additional context

The launcher i used for testing sponge-mixin was through prism launcher and then editing fabric loader's libraries in version page that way as it's quicker but can be pulled off in vanilla launcher aswell, This issue however will not occur when rolling back the sponge-mixin library to `0.12.5+mixin.0.8.5`.

**Comment by IMS212** [comment]
Issue on Fabric's side, being investigated.
