### ISSUE TITLE
Weird Errors in Log

### ISSUE THREAD

**Issue by TheCrafter8000** [IrisShaders/Iris#2314]
### What happened?

Iris is sending random errors in the log, these errors are the same errors ive been seeing for a while.

### Log output

[14:28:17] [Render thread/WARN]: Failed to resolve uniform rainStrength, reason: Variable shadows build in uniform: rainStrength ( = FunctionCall{clamp {[Id{rainStrength}, Number{0.0}, Number{1.0}]} })
java.lang.Exception: Variable shadows build in uniform: rainStrength
	at net.irisshaders.iris.uniforms.custom.CustomUniforms.addVariable(CustomUniforms.java:184) ~[iris-1.7.0+mc1.20.4.jar:?]
	at net.irisshaders.iris.uniforms.custom.CustomUniforms.<init>(CustomUniforms.java:65) ~[iris-1.7.0+mc1.20.4.jar:?]
	at net.irisshaders.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:334) ~[iris-1.7.0+mc1.20.4.jar:?]
	at net.irisshaders.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:345) ~[iris-1.7.0+mc1.20.4.jar:?]
	at net.irisshaders.iris.pipeline.IrisRenderingPipeline.<init>(IrisRenderingPipeline.java:261) ~[iris-1.7.0+mc1.20.4.jar:?]
	at net.irisshaders.iris.Iris.createPipeline(Iris.java:580) ~[iris-1.7.0+mc1.20.4.jar:?]
	at net.irisshaders.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:33) ~[iris-1.7.0+mc1.20.4.jar:?]
	at net.minecraft.class_310.handler$bmd000$iris$resetPipeline(class_310.java:15298) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_18097(class_310.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1481(class_310.java:2257) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11120(class_634.java:414) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[fabric-loader-0.15.3-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]

[14:28:17] [Render thread/WARN]: Shader clouds could not find uniform named ModelViewMat in the specified shader program.
[14:28:17] [Render thread/WARN]: Shader clouds could not find uniform named ProjMat in the specified shader program.
[14:28:17] [Render thread/WARN]: Shader clouds could not find uniform named ColorModulator in the specified shader program.
[14:28:17] [Render thread/WARN]: Shader clouds could not find uniform named FogStart in the specified shader program.
[14:28:17] [Render thread/WARN]: Shader clouds could not find uniform named FogEnd in the specified shader program.
[14:28:17] [Render thread/WARN]: Shader clouds could not find uniform named FogColor in the specified shader program.

### Minecraft Version

1.20.4

### Iris Version

Iris 1.7.0 for 1.20.4

### Operating System

Win 11

### What is your GPU?

3080

### Additional context

this might be off topic, but for a while now my game will have a lot of input lag. Things like jumping and switching perspectives would lag/delay. It seems to be only when loading chunks or when chunks or not fully loaded. For example I'm in my base and it would lag but as soon as i go outside and look around and get all the chunks fully loaded it seems to be fine. It wouldn't be issues with TPS cause I'm playing on a server with this happens and the server have 20 TPS all the time. I'm not sure if this relates to iris but its the only mod in my log that's sending errors

**Comment by IMS212** [comment]
not a bug
