### ISSUE TITLE
crash conflict with iris and physics mod

### ISSUE THREAD

**Issue by nekohacker591** [IrisShaders/Iris#2339]
### Minecraft Version

Minecraft 1.20.1

### Iris Version

oculus-mc1.20.1-1.7.0.jar

### Sodium Version

embeddium-0.3.19+mc1.20.1-all.jar

### Operating System

Windows 10

### What is your GPU?

RTX A4500

### Java Version

Java 16

### Reproduction Steps

org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: Illegal classload request for net.diebuddies.mixins.iris.MixinExtendedShaderAccessor. Mixin is defined in physicsmod.mixins.json and cannot be referenced directly

have both physics-mod-pro-v166b-forge-1.20.1.jar and oculus-mc1.20.1-1.7.0.jar installed

### Crash Report file and latest.log

```shell
Unreported exception thrown!
org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: Illegal classload request for net.diebuddies.mixins.iris.MixinExtendedShaderAccessor. Mixin is defined in physicsmod.mixins.json and cannot be referenced directly
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:334)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at TRANSFORMER/physicsmod@3.0.12/net.diebuddies.compat.Iris.setNormalMatrix(Iris.java:101)
	at TRANSFORMER/physicsmod@3.0.12/net.diebuddies.render.MainRenderer.setupModelViewMatrix(MainRenderer.java:451)
	at TRANSFORMER/physicsmod@3.0.12/net.diebuddies.render.MainRenderer.render(MainRenderer.java:407)
	at TRANSFORMER/physicsmod@3.0.12/net.diebuddies.render.MainRenderer.renderAll(MainRenderer.java:223)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.LevelRenderer.handler$hji000$physicsmod$renderMain(LevelRenderer.java:22115)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.LevelRenderer.m_172993_(LevelRenderer.java:34705)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.LevelRenderer.invokeRenderChunkLayer(LevelRenderer.java)
	at TRANSFORMER/oculus@1.7.0/net.irisshaders.iris.shadows.ShadowRenderer.renderShadows(ShadowRenderer.java:461)
	at TRANSFORMER/oculus@1.7.0/net.irisshaders.iris.pipeline.IrisRenderingPipeline.renderShadows(IrisRenderingPipeline.java:1010)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.LevelRenderer.handler$bdi000$oculus$iris$renderTerrainShadows(LevelRenderer.java:8696)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1155)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.1/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.1/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.1/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
```

### Additional context

this is for oculus mod but the issue lays with the source mod iris not occulus could you create a fix

**Comment by IMS212** [comment]
this literally isn't iris; if you can't cause this on Iris I cannot accept this
