### ISSUE TITLE
java.lang.IllegalStateException: Buffer mapping is already disposed

### ISSUE THREAD

**Issue by nekohacker591** [IrisShaders/Iris#2340]
### Minecraft Version

Minecraft 1.20.1

### Iris Version

oculus-mc1.20.1-1.7.0.jar

### Sodium Version

embeddium-0.3.19+mc1.20.1-all.jar

### Operating System

Windows 10

### What is your GPU?

RTX A4500

### Java Version

Java 16

### Reproduction Steps

unsure how to replicate

### Crash Report file and latest.log

```shell
Unreported exception thrown!
java.lang.IllegalStateException: Buffer mapping is already disposed
	at TRANSFORMER/embeddium@0.3.19+mc1.20.1/me.jellysquid.mods.sodium.client.gl.device.GLRenderDevice$ImmediateCommandList.checkMapDisposed(GLRenderDevice.java:235)
	at TRANSFORMER/embeddium@0.3.19+mc1.20.1/me.jellysquid.mods.sodium.client.gl.device.GLRenderDevice$ImmediateCommandList.flushMappedRange(GLRenderDevice.java:220)
	at TRANSFORMER/embeddium@0.3.19+mc1.20.1/me.jellysquid.mods.sodium.client.gl.arena.staging.MappedStagingBuffer.flush(MappedStagingBuffer.java:97)
	at TRANSFORMER/embeddium@0.3.19+mc1.20.1/me.jellysquid.mods.sodium.client.gl.arena.GlBufferArena.tryUploads(GlBufferArena.java:308)
	at TRANSFORMER/embeddium@0.3.19+mc1.20.1/me.jellysquid.mods.sodium.client.gl.arena.GlBufferArena.upload(GlBufferArena.java:280)
	at TRANSFORMER/embeddium@0.3.19+mc1.20.1/me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.uploadMeshes(RenderRegionManager.java:86)
	at TRANSFORMER/embeddium@0.3.19+mc1.20.1/me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.redirect$egi000$acedium$redirectUpload(RenderRegionManager.java:532)
	at TRANSFORMER/embeddium@0.3.19+mc1.20.1/me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.uploadMeshes(RenderRegionManager.java:53)
	at TRANSFORMER/embeddium@0.3.19+mc1.20.1/me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.processChunkBuildResults(RenderSectionManager.java:409)
	at TRANSFORMER/embeddium@0.3.19+mc1.20.1/me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.uploadChunks(RenderSectionManager.java:397)
	at TRANSFORMER/embeddium@0.3.19+mc1.20.1/me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.setupTerrain(SodiumWorldRenderer.java:218)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.LevelRenderer.m_194338_(LevelRenderer.java:32718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.LevelRenderer.invokeSetupRender(LevelRenderer.java)
	at TRANSFORMER/oculus@1.7.0/net.irisshaders.iris.shadows.ShadowRenderer.renderShadows(ShadowRenderer.java:424)
	at TRANSFORMER/oculus@1.7.0/net.irisshaders.iris.pipeline.IrisRenderingPipeline.renderShadows(IrisRenderingPipeline.java:1010)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.LevelRenderer.handler$bdi000$oculus$iris$renderTerrainShadows(LevelRenderer.java:8696)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1155)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.1/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.1/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.1/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
```

### Additional context

very likely exist inside iris code as well as occulus's so dont close this

**Comment by IMS212** [comment]
no
