### ISSUE TITLE
java.lang.RuntimeException: Unknown variable: BIOME_SWAMP_HILLS in Prism Launcher crash

### ISSUE THREAD

**Issue by DilutedOxygen1451** [IrisShaders/Iris#2430]
### Minecraft Version

Minecraft 1.20.1

### Iris Version

Iris 1.7.1+mc1.20.1

### Sodium Version

Sodium 0.5.10+mc1.20.1

### Operating System

Windows 11

### What is your GPU?

Nvidia GTX Titan X Pascal eGPU

### Java Version

Eclipse Adoptium jdk-17.0.11.9-hotspot

### Reproduction Steps

just playing the game like normal, I've had crashes 2 minutes and 20 minutes in, at seemingly random, but its always the same crash log

### Crash Report file and latest.log

```shell
[09:41:19] [Render thread/WARN]: Failed to resolve uniform inSwamp, reason: Unknown variable: BIOME_SWAMP_HILLS ( = FunctionCall{smooth {[Number{1}, FunctionCall{if {[FunctionCall{in {[Id{biome}, Number{6}, Id{BIOME_SWAMP_HILLS}]} }, Number{1}, Number{0}]} }, Number{5}]} })
java.lang.RuntimeException: Unknown variable: BIOME_SWAMP_HILLS
	at kroppeb.stareval.resolver.ExpressionResolver.resolveExpressionInternal(ExpressionResolver.java:220) ~[iris-1.7.1+mc1.20.1.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpressionInternal(ExpressionResolver.java:81) ~[iris-1.7.1+mc1.20.1.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpression(ExpressionResolver.java:140) ~[iris-1.7.1+mc1.20.1.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveExpressionInternal(ExpressionResolver.java:194) ~[iris-1.7.1+mc1.20.1.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpressionInternal(ExpressionResolver.java:81) ~[iris-1.7.1+mc1.20.1.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpression(ExpressionResolver.java:140) ~[iris-1.7.1+mc1.20.1.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpression(ExpressionResolver.java:127) ~[iris-1.7.1+mc1.20.1.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveExpressionInternal(ExpressionResolver.java:194) ~[iris-1.7.1+mc1.20.1.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpressionInternal(ExpressionResolver.java:81) ~[iris-1.7.1+mc1.20.1.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpression(ExpressionResolver.java:140) ~[iris-1.7.1+mc1.20.1.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveExpressionInternal(ExpressionResolver.java:194) ~[iris-1.7.1+mc1.20.1.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveExpression(ExpressionResolver.java:50) ~[iris-1.7.1+mc1.20.1.jar:?]
	at net.irisshaders.iris.uniforms.custom.CustomUniforms.<init>(CustomUniforms.java:62) ~[iris-1.7.1+mc1.20.1.jar:?]
	at net.irisshaders.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:333) ~[iris-1.7.1+mc1.20.1.jar:?]
	at net.irisshaders.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:344) ~[iris-1.7.1+mc1.20.1.jar:?]
	at net.irisshaders.iris.pipeline.IrisRenderingPipeline.<init>(IrisRenderingPipeline.java:264) ~[iris-1.7.1+mc1.20.1.jar:?]
	at net.irisshaders.iris.Iris.createPipeline(Iris.java:578) ~[iris-1.7.1+mc1.20.1.jar:?]
	at net.irisshaders.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:33) ~[iris-1.7.1+mc1.20.1.jar:?]
	at net.irisshaders.iris.Iris.reload(Iris.java:529) ~[iris-1.7.1+mc1.20.1.jar:?]
	at net.irisshaders.iris.Iris.toggleShaders(Iris.java:186) ~[iris-1.7.1+mc1.20.1.jar:?]
	at net.irisshaders.iris.Iris.handleKeybinds(Iris.java:159) ~[iris-1.7.1+mc1.20.1.jar:?]
	at net.minecraft.class_310.handler$cfg005$iris$onTick(class_310.java:16512) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1957) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
[09:41:20] [Render thread/WARN]: Patched fract(worldpos.y + 0.001) to fract(worldpos.y + 0.01) to fix waving water disconnecting from other water blocks; See https://github.com/IrisShaders/Iris/issues/509
[09:41:20] [Render thread/WARN]: Patched fract(worldpos.y + 0.001) to fract(worldpos.y + 0.01) to fix waving water disconnecting from other water blocks; See https://github.com/IrisShaders/Iris/issues/509
[09:41:20] [Render thread/WARN]: Patched fract(worldpos.y + 0.001) to fract(worldpos.y + 0.01) to fix waving water disconnecting from other water blocks; See https://github.com/IrisShaders/Iris/issues/509
[09:41:20] [Render thread/WARN]: Patched fract(worldpos.y + 0.001) to fract(worldpos.y + 0.01) to fix waving water disconnecting from other water blocks; See https://github.com/IrisShaders/Iris/issues/509
[09:41:20] [Render thread/INFO]: Stopping worker threads
[09:41:20] [Render thread/INFO]: Started 10 worker threads
[09:41:20] [Render thread/INFO]: [System] [CHAT] Toggled shaders to Sildur's Vibrant Shaders v1.52 Extreme-VL.zip!
[09:41:20] [Render thread/INFO]: Stopping worker threads
[09:41:20] [Render thread/INFO]: Started 10 worker threads
[09:41:20] [Render thread/WARN]: Patched fract(worldpos.y + 0.001) to fract(worldpos.y + 0.01) to fix waving water disconnecting from other water blocks; See https://github.com/IrisShaders/Iris/issues/509
[09:41:20] [Render thread/WARN]: Patched fract(worldpos.y + 0.001) to fract(worldpos.y + 0.01) to fix waving water disconnecting from other water blocks; See https://github.com/IrisShaders/Iris/issues/509
[09:41:20] [Render thread/WARN]: Patched fract(worldpos.y + 0.001) to fract(worldpos.y + 0.01) to fix waving water disconnecting from other water blocks; See https://github.com/IrisShaders/Iris/issues/509
[09:41:54] [Render thread/INFO]: Reloading pipeline on dimension change: minecraft:the_end => minecraft:overworld
[09:41:54] [Render thread/INFO]: Destroying pipeline minecraft:the_end
[09:41:54] [Render thread/INFO]: Creating pipeline for dimension minecraft:overworld
[09:41:54] [Render thread/WARN]: Failed to resolve uniform inSwamp, reason: Unknown variable: BIOME_SWAMP_HILLS ( = FunctionCall{smooth {[Number{1}, FunctionCall{if {[FunctionCall{in {[Id{biome}, Number{6}, Id{BIOME_SWAMP_HILLS}]} }, Number{1}, Number{0}]} }, Number{5}]} })
java.lang.RuntimeException: Unknown variable: BIOME_SWAMP_HILLS
	at kroppeb.stareval.resolver.ExpressionResolver.resolveExpressionInternal(ExpressionResolver.java:220) ~[iris-1.7.1+mc1.20.1.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpressionInternal(ExpressionResolver.java:81) ~[iris-1.7.1+mc1.20.1.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpression(ExpressionResolver.java:140) ~[iris-1.7.1+mc1.20.1.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveExpressionInternal(ExpressionResolver.java:194) ~[iris-1.7.1+mc1.20.1.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpressionInternal(ExpressionResolver.java:81) ~[iris-1.7.1+mc1.20.1.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpression(ExpressionResolver.java:140) ~[iris-1.7.1+mc1.20.1.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpression(ExpressionResolver.java:127) ~[iris-1.7.1+mc1.20.1.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveExpressionInternal(ExpressionResolver.java:194) ~[iris-1.7.1+mc1.20.1.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpressionInternal(ExpressionResolver.java:81) ~[iris-1.7.1+mc1.20.1.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpression(ExpressionResolver.java:140) ~[iris-1.7.1+mc1.20.1.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveExpressionInternal(ExpressionResolver.java:194) ~[iris-1.7.1+mc1.20.1.jar:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveExpression(ExpressionResolver.java:50) ~[iris-1.7.1+mc1.20.1.jar:?]
	at net.irisshaders.iris.uniforms.custom.CustomUniforms.<init>(CustomUniforms.java:62) ~[iris-1.7.1+mc1.20.1.jar:?]
	at net.irisshaders.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:333) ~[iris-1.7.1+mc1.20.1.jar:?]
	at net.irisshaders.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:344) ~[iris-1.7.1+mc1.20.1.jar:?]
	at net.irisshaders.iris.pipeline.IrisRenderingPipeline.<init>(IrisRenderingPipeline.java:264) ~[iris-1.7.1+mc1.20.1.jar:?]
	at net.irisshaders.iris.Iris.createPipeline(Iris.java:578) ~[iris-1.7.1+mc1.20.1.jar:?]
	at net.irisshaders.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:33) ~[iris-1.7.1+mc1.20.1.jar:?]
	at net.minecraft.class_310.handler$cfh000$iris$resetPipeline(class_310.java:17043) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_18097(class_310.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1481(class_310.java:2147) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11117(class_634.java:1114) ~[client-intermediary.jar:?]
	at net.minecraft.class_2724.method_11782(class_2724.java:78) ~[client-intermediary.jar:?]
	at net.minecraft.class_2724.method_11054(class_2724.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
[09:41:54] [Server thread/INFO]: Saving and pausing game...
[09:41:54] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Survival]'/minecraft:overworld
[09:41:54] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Survival]'/minecraft:the_end
[09:41:54] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Survival]'/minecraft:the_nether
[09:41:54] [Render thread/WARN]: Patched fract(worldpos.y + 0.001) to fract(worldpos.y + 0.01) to fix waving water disconnecting from other water blocks; See https://github.com/IrisShaders/Iris/issues/509
[09:41:54] [Render thread/WARN]: Patched fract(worldpos.y + 0.001) to fract(worldpos.y + 0.01) to fix waving water disconnecting from other water blocks; See https://github.com/IrisShaders/Iris/issues/509
[09:41:54] [Render thread/WARN]: Patched fract(worldpos.y + 0.001) to fract(worldpos.y + 0.01) to fix waving water disconnecting from other water blocks; See https://github.com/IrisShaders/Iris/issues/509
[09:41:54] [Render thread/WARN]: Patched fract(worldpos.y + 0.001) to fract(worldpos.y + 0.01) to fix waving water disconnecting from other water blocks; See https://github.com/IrisShaders/Iris/issues/509
[09:41:54] [Render thread/INFO]: Stopping worker threads
[09:41:54] [Render thread/INFO]: Started 10 worker threads
[09:41:54] [Render thread/INFO]: Stopping worker threads
[09:41:54] [Render thread/INFO]: Started 10 worker threads
[09:41:54] [Render thread/INFO]: Stopping worker threads
[09:41:54] [Render thread/INFO]: Started 10 worker threads
[09:41:54] [Render thread/INFO]: Minimap updated server level id: -1158505893 for world ResourceKey[minecraft:dimension / minecraft:overworld]
[09:41:54] [Render thread/INFO]: Stopping worker threads
[09:41:54] [Render thread/INFO]: Started 10 worker threads
[09:41:54] [Render thread/WARN]: Patched fract(worldpos.y + 0.001) to fract(worldpos.y + 0.01) to fix waving water disconnecting from other water blocks; See https://github.com/IrisShaders/Iris/issues/509
[09:41:54] [Render thread/WARN]: Patched fract(worldpos.y + 0.001) to fract(worldpos.y + 0.01) to fix waving water disconnecting from other water blocks; See https://github.com/IrisShaders/Iris/issues/509
[09:41:54] [Render thread/WARN]: Patched fract(worldpos.y + 0.001) to fract(worldpos.y + 0.01) to fix waving water disconnecting from other water blocks; See https://github.com/IrisShaders/Iris/issues/509
[09:46:55] [Render thread/ERROR]: Deleting stream buffers: Invalid operation.
Process crashed with exitcode -1073740791.
```

### Additional context

I am using Sildur's Vibrant shaders

**Comment by DilutedOxygen1451** [comment]
my game is contsnatly crashing after 1-10 minutes of playing, please help, I just want to use a shader pack that looks good without my PC crashing every 5 minutes

**Comment by IMS212** [comment]
The unknown variable message is unrelated to the crash. Is there another crash log?

**Comment by Bristopher** [comment]
Just had the same crash

**Comment by IMS212** [comment]
As said months ago, this isn’t a crash. Your issue is separate.

**Comment by Bristopher** [comment]
oh I know, unrelated or not just saying this error isn't a one off error.
