### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Shikuren** [IrisShaders/Iris#2436]
### Minecraft Version

1.20.1

### Iris Version

1.7.2

### Sodium Version

0.5.11

### Operating System

Windows 11

### What is your GPU?

RTX 3070

### Java Version

Java 11

### Reproduction Steps

Run the game

### Crash Report file and latest.log

```shell
Description: Initializing game

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_824 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.minecraft.class_310.<init>(class_310.java:561)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 9 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for cpm.mixins.compat.json:BlockEntityRenderDispatcherMixin_Iris from mod (unknown) during activity: [Transform -> Method prewrapBufferSource(Lnet/minecraft/class_4597;Lnet/minecraft/class_2586;)Lnet/minecraft/class_4597; -> GETSTATIC -> net/coderbot/iris/block_rendering/BlockRenderingSettings::INSTANCE:Lnet/coderbot/iris/block_rendering/BlockRenderingSettings;]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 12 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.coderbot.iris.block_rendering.BlockRenderingSettings
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:786)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformField(MixinPreProcessorStandard.java:777)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:740)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307)
	... 18 more
Caused by: java.lang.ClassNotFoundException: net.coderbot.iris.block_rendering.BlockRenderingSettings
	... 22 more
```

**Comment by Luracasmus** [comment]
Hello!

Could you please provide the log file from when the issue occurred?

> Usually this is found at .minecraft/logs/latest.log. If you are not sure how to find .minecraft, please see this article: https://minecraft.wiki/w/.minecraft#Locating_.minecraft. Please do not upload a compressed (.log.gz) file, they are very difficult for us to read when viewing issue reports. The log file instantly tells us important information like the versions of any other installed mods or if there are errors so it is very very important that you include it in your report.

The full crash report instead of just a snippet could be useful as well
