### ISSUE TITLE
Iris on sodium throwing version mismatch with Distant Horizons 2.2.0a

### ISSUE THREAD

**Issue by TeeJayBaker** [IrisShaders/Iris#2452]
### What happened?

On launch the fabric menu pops up and throws an Iris version mismatch for Distant Horizons <2.2.0 despite having 2.2.0a installed

### Log output

[16:00:06] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.16.2
[16:00:06] [main/WARN]: Mod resolution failed
[16:00:06] [main/INFO]: Immediate reason: [NEG_HARD_DEP iris 1.8.0-beta.2+mc1.21.1 {breaks distanthorizons @ [<=2.2.0]}, ROOT_FORCELOAD_SINGLE distanthorizons 2.2.0-a, ROOT_FORCELOAD_SINGLE iris 1.8.0-beta.2+mc1.21.1]
[16:00:06] [main/INFO]: Reason: [NEG_HARD_DEP iris 1.8.0-beta.2+mc1.21.1 {breaks distanthorizons @ [<=2.2.0]}]
[16:00:06] [main/INFO]: Fix: add [], remove [distanthorizons 2.2.0-a, distanthorizons 2.2.0-a], replace []
[16:00:06] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Remove mod 'Distant Horizons' (distanthorizons) 2.2.0-a (/Users/tom/Library/Application Support/PrismLauncher/instances/Vanilla-/.minecraft/mods/DistantHorizons-2.2.0-a-1.21.1-neo-fabric.jar).
	 - Remove mod 'Distant Horizons' (distanthorizons) 2.2.0-a (/Users/tom/Library/Application Support/PrismLauncher/instances/Vanilla-/.minecraft/mods/DistantHorizons-2.2.0-a-1.21.1-neo-fabric.jar).
More details:
	 - Mod 'Iris' (iris) 1.8.0-beta.2+mc1.21.1 is incompatible with version 2.2.0 or earlier of mod 'Distant Horizons' (distanthorizons), but a matching version is present: 2.2.0-a!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.2.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Process exited with code 1.

### Minecraft Version

Minecraft 1.21

### Iris Version

iris 1.8.0-beta.2+mc1.21.1

### Operating System

MacOS

### What is your GPU?

Apple M1

**Comment by enderprism** [comment]
from the logs it looks like the incompatibility is set to ≤2.2.0 instead of <2.2.0 or ≤2.1.x

**Comment by enderprism** [comment]
i checked the `fabric.mod.json` in all the `multiloader` branches
[`multiloader-1.21`](https://github.com/IrisShaders/Iris/blob/multiloader-1.21/fabric/src/main/resources/fabric.mod.json), [`multiloader-1.20.6`](https://github.com/IrisShaders/Iris/blob/multiloader-1.20.6/fabric/src/main/resources/fabric.mod.json) and [`multiloader-1.20.1`](https://github.com/IrisShaders/Iris/blob/multiloader-1.20.1/fabric/src/main/resources/fabric.mod.json) all set the incompatibility to `<=2.0.1`
but [`multiloader-new`](https://github.com/IrisShaders/Iris/blob/multiloader-new/fabric/src/main/resources/fabric.mod.json), which i assume was the one distributed for 1.21 and above (since it's marked as compatible with these versions), set the incompatibility to `<=2.2.0`
EDIT: it [`multiloader-new`](https://github.com/IrisShaders/Iris/blob/multiloader-new/fabric/src/main/resources/fabric.mod.json) was just corrected to `<=2.1.99` so i guess we just have to wait until it's rolled out

**Comment by Remco0o** [comment]
> i checked the `fabric.mod.json` in all the `multiloader` branches [`multiloader-1.21`](https://github.com/IrisShaders/Iris/blob/multiloader-1.21/fabric/src/main/resources/fabric.mod.json), [`multiloader-1.20.6`](https://github.com/IrisShaders/Iris/blob/multiloader-1.20.6/fabric/src/main/resources/fabric.mod.json) and [`multiloader-1.20.1`](https://github.com/IrisShaders/Iris/blob/multiloader-1.20.1/fabric/src/main/resources/fabric.mod.json) all set the incompatibility to `<=2.0.1` but [`multiloader-new`](https://github.com/IrisShaders/Iris/blob/multiloader-new/fabric/src/main/resources/fabric.mod.json), which i assume was the one distributed for 1.21 and above (since it's marked as compatible with these versions), set the incompatibility to `<=2.2.0` EDIT: it [`multiloader-new`](https://github.com/IrisShaders/Iris/blob/multiloader-new/fabric/src/main/resources/fabric.mod.json) was just corrected to `<=2.1.99` so i guess we just have to wait until it's rolled out

How long do you think when the update rolled out?

**Comment by enderprism** [comment]
the new release has been rolled out, you can close the issue @TeeJayBaker
