### ISSUE TITLE
Crash with Polytone

### ISSUE THREAD

**Issue by MehVahdJukaar** [IrisShaders/Iris#2461]
### Minecraft Version

1.21

### Iris Version

1.7.3+mc1.21

### Sodium Version

0.6

### Operating System

windows 10

### What is your GPU?

gtx 1060

### Java Version

22

### Reproduction Steps

Install Polytone and Iris. Then render a leash

Polytone is my mod but i dont think I'm doing anything wrong there. 
Crash comes directly from a mixin added by iris.

My code: https://github.com/MehVahdJukaar/polytone/blob/1.21/common/src/main/java/net/mehvahdjukaar/polytone/mixins/LeashMixin.java#L17

### Crash Report file and latest.log

```shell
[18:09:38] [main/INFO]: Loading Minecraft 1.21.1 with Fabric Loader 0.16.3
[18:09:39] [main/INFO]: Dependencies overridden for minecraft, lambdynlights, fabricloader, polytone, debugify
[18:09:39] [main/WARN]: Warnings were found!
 - 'Minecraft' (minecraft) 1.21.1 recommends any version after 6.1.0-beta.2 of Fabulously Optimized, which is missing!
	 - You should install any version after 6.1.0-beta.2 of Fabulously Optimized for the optimal experience.
[18:09:39] [main/INFO]: Loading 62 mods:
	- fabric-api 0.103.0+1.21.1
	   |-- fabric-api-base 0.4.42+6573ed8c19
	   |-- fabric-api-lookup-api-v1 1.6.68+b559734419
	   |-- fabric-biome-api-v1 13.0.29+5bd9f1bc19
	   |-- fabric-block-api-v1 1.0.22+0af3f5a719
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8c19
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a719
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8c19
	   |-- fabric-command-api-v1 1.2.49+f71b366f19
	   |-- fabric-command-api-v2 2.2.28+6ced4dd919
	   |-- fabric-commands-v0 0.2.66+df3654b319
	   |-- fabric-content-registries-v0 8.0.16+b559734419
	   |-- fabric-convention-tags-v1 2.0.21+7f945d5b19
	   |-- fabric-convention-tags-v2 2.6.1+9b16164119
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a719
	   |-- fabric-data-attachment-api-v1 1.1.28+1daea21519
	   |-- fabric-data-generation-api-v1 20.2.18+16c4ae2519
	   |-- fabric-dimensions-v1 4.0.0+6fc22b9919
	   |-- fabric-entity-events-v1 1.7.0+2122d82819
	   |-- fabric-events-interaction-v0 0.7.12+ba9dae0619
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd919
	   |-- fabric-item-api-v1 11.0.0+afdfc92119
	   |-- fabric-item-group-api-v1 4.1.5+3fc0e55219
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a719
	   |-- fabric-keybindings-v0 0.2.45+df3654b319
	   |-- fabric-lifecycle-events-v1 2.3.12+6c1df36019
	   |-- fabric-loot-api-v2 3.0.14+3f89f5a519
	   |-- fabric-loot-api-v3 1.0.2+3f89f5a519
	   |-- fabric-message-api-v1 6.0.13+6573ed8c19
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6b19
	   |-- fabric-networking-api-v1 4.2.2+60c3209b19
	   |-- fabric-object-builder-api-v1 15.2.0+40875a9319
	   |-- fabric-particles-v1 4.0.2+6573ed8c19
	   |-- fabric-recipe-api-v1 5.0.12+6508971219
	   |-- fabric-registry-sync-v0 5.1.2+60c3209b19
	   |-- fabric-renderer-api-v1 3.4.0+c705a49c19
	   |-- fabric-renderer-indigo 1.7.0+c705a49c19
	   |-- fabric-renderer-registries-v1 3.2.68+df3654b319
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e19
	   |-- fabric-rendering-fluids-v1 3.1.6+1daea21519
	   |-- fabric-rendering-v0 1.1.71+df3654b319
	   |-- fabric-rendering-v1 5.0.5+df16efd019
	   |-- fabric-resource-conditions-api-v1 4.3.0+8dc279b119
	   |-- fabric-resource-loader-v0 1.3.0+5659912919
	   |-- fabric-screen-api-v1 2.0.25+8b68f1c719
	   |-- fabric-screen-handler-api-v1 1.3.86+b559734419
	   |-- fabric-sound-api-v1 1.0.23+6573ed8c19
	   |-- fabric-transfer-api-v1 5.1.17+1db1cc1f19
	   \-- fabric-transitive-access-wideners-v1 6.1.0+1daea21519
	- fabricloader 0.16.3
	   \-- mixinextras 0.4.1
	- iris 1.7.3+mc1.21
	   |-- io_github_douira_glsl-transformer 2.0.1
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.13.1
	- java 21
	- minecraft 1.21.1
	- modmenu 11.0.2
	   \-- placeholder-api 2.4.0-pre.2+1.21
	- polytone 1.21-2.3.12
	   \-- net_objecthunter_exp4j 0.4.8
	- sodium 0.5.11+mc1.21
[18:09:39] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/C:/Users/Madis/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.15.2+mixin.0.8.7/sponge-mixin-0.15.2+mixin.0.8.7.jar Service=Knot/Fabric Env=CLIENT
[18:09:39] [main/INFO]: Compatibility level set to JAVA_17
[18:09:39] [main/INFO]: Compatibility level set to JAVA_21
[18:09:39] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 3 override(s) found
[18:09:40] [main/WARN]: Force-disabling mixin 'features.render.entity.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[18:09:40] [main/WARN]: Force-disabling mixin 'features.render.entity.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[18:09:40] [main/WARN]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[18:09:40] [main/WARN]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[18:09:40] [main/WARN]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [iris]) disables it and children
[18:09:40] [main/WARN]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[18:09:40] [main/WARN]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[18:09:40] [main/WARN]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[18:09:40] [main/INFO]: Searching for graphics cards...
[18:09:41] [main/INFO]: Found graphics adapter: AdapterInfo{vendor=INTEL, description='Intel(R) Iris(R) Plus Graphics', adapterType=0x0000232B, openglIcdFilePath='C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_27e3f997fcc85a29\ig11icd64.dll', openglIcdVersion=27.20.100.8783}
[18:09:41] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[18:09:43] [Datafixer Bootstrap/INFO]: 226 Datafixer optimizations took 445 milliseconds
[18:09:51] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[18:09:51] [Render thread/INFO]: Setting user: robotkoer
[18:09:51] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[18:09:52] [Render thread/INFO]: Backend library: LWJGL version 3.3.3-snapshot
[18:09:53] [Render thread/INFO]: Debug functionality is disabled.
[18:09:53] [Render thread/INFO]: ARB_direct_state_access detected, enabling DSA.
[18:09:53] [Render thread/INFO]: Shaders are disabled because enableShaders is set to false in iris.properties
[18:09:53] [Render thread/WARN]: Removed resource pack continuity:glass_pane_culling_fix from options because it doesn't seem to exist anymore
[18:09:53] [Render thread/WARN]: Removed resource pack continuity:default from options because it doesn't seem to exist anymore
[18:09:55] [Render thread/INFO]: Hardware information:
[18:09:55] [Render thread/INFO]: CPU: 8x Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
[18:09:55] [Render thread/INFO]: GPU: Intel(R) Iris(R) Plus Graphics (Supports OpenGL 3.2.0 - Build 27.20.100.8783)
[18:09:55] [Render thread/INFO]: OS: Windows 11 (10.0)
[18:09:55] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, modmenu, polytone, sodium, file/SodiumTranslations.zip, file/Mod Menu Helper.zip, file/Chat Reporting Helper.zip, file/Fast Better Grass.zip
[18:09:55] [Worker-Main-6/INFO]: Found unifont_all_no_pua-15.1.05.hex, loading
[18:09:56] [Worker-Main-2/INFO]: Found unifont_jp_patch-15.1.05.hex, loading
[18:09:58] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[18:09:58] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[18:09:59] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (Realtek(R) Audio)
[18:09:59] [Render thread/INFO]: Sound engine started
[18:09:59] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[18:09:59] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[18:09:59] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[18:09:59] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[18:09:59] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[18:09:59] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[18:09:59] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[18:09:59] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[18:09:59] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[18:09:59] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[18:09:59] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/paintings.png-atlas
[18:09:59] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[18:09:59] [Render thread/INFO]: Created: 64x64x0 minecraft:textures/atlas/map_decorations.png-atlas
[18:09:59] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[18:10:00] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[18:10:01] [Render thread/INFO]: Reloaded Polytone Resources in 8 ms
[18:10:01] [Render thread/INFO]: Creating pipeline for dimension minecraft:overworld
[18:10:06] [Render thread/INFO]: Loaded 1290 recipes
[18:10:06] [Render thread/INFO]: Loaded 1399 advancements
[18:10:08] [Render thread/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 1.961 ms
[18:10:08] [Server thread/INFO]: Starting integrated minecraft server version 1.21.1
[18:10:08] [Server thread/INFO]: Generating keypair
[18:10:15] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[18:10:15] [Render thread/INFO]: Preparing spawn area: 2%
[18:10:16] [Render thread/INFO]: Preparing spawn area: 2%
[18:10:16] [Render thread/INFO]: Preparing spawn area: 2%
[18:10:17] [Render thread/INFO]: Preparing spawn area: 2%
[18:10:17] [Render thread/INFO]: Preparing spawn area: 14%
[18:10:18] [Render thread/INFO]: Preparing spawn area: 18%
[18:10:18] [Render thread/INFO]: Preparing spawn area: 18%
[18:10:19] [Render thread/INFO]: Preparing spawn area: 51%
[18:10:19] [Render thread/INFO]: Preparing spawn area: 51%
[18:10:20] [Render thread/INFO]: Preparing spawn area: 51%
[18:10:20] [Render thread/INFO]: Preparing spawn area: 51%
[18:10:21] [Render thread/INFO]: Time elapsed: 5251 ms
[18:10:21] [Server thread/INFO]: Changing view distance to 12, from 10
[18:10:21] [Server thread/INFO]: Changing simulation distance to 6, from 0
[18:10:22] [Server thread/INFO]: robotkoer[local:E:f756bb4a] logged in with entity id 21 at (-63.5, 69.0, -54.5)
[18:10:22] [Render thread/INFO]: Reloading pipeline on dimension change: minecraft:overworld => minecraft:overworld
[18:10:22] [Render thread/INFO]: Destroying pipeline minecraft:overworld
[18:10:22] [Render thread/INFO]: Creating pipeline for dimension minecraft:overworld
[18:10:22] [Server thread/INFO]: robotkoer joined the game
[18:10:23] [Render thread/INFO]: Started 2 worker threads
[18:10:23] [Render thread/INFO]: Loaded 2 advancements
[18:10:35] [Server thread/INFO]: Saving and pausing game...
[18:10:36] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[18:10:36] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[18:10:36] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[18:10:40] [Server thread/INFO]: [robotkoer: Set own game mode to Creative Mode]
[18:10:40] [Render thread/INFO]: [System] [CHAT] Set own game mode to Creative Mode
[18:11:01] [Server thread/INFO]: Saving and pausing game...
[18:11:01] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[18:11:01] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[18:11:01] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[18:11:02] [Server thread/INFO]: Saving and pausing game...
[18:11:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[18:11:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[18:11:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[18:11:08] [Server thread/INFO]: Saving and pausing game...
[18:11:08] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[18:11:08] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[18:11:08] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[18:11:22] [Render thread/INFO]: Destroying pipeline minecraft:overworld
[18:11:22] [Render thread/INFO]: Shaders are disabled because no valid shaderpack is selected
[18:11:23] [Render thread/INFO]: Creating pipeline for dimension minecraft:overworld
[18:11:23] [Render thread/INFO]: Stopping worker threads
[18:11:23] [Render thread/INFO]: Started 2 worker threads
[18:11:23] [Render thread/INFO]: Destroying pipeline minecraft:overworld
[18:11:23] [Render thread/INFO]: Profile: Fancy (+0 options changed by user)
[18:11:23] [Render thread/INFO]: Using shaderpack: Sildur's Enhanced Default v1.171 Fancy.zip
[18:11:23] [Render thread/INFO]: Creating pipeline for dimension minecraft:overworld
[18:11:26] [Render thread/WARN]: The in declaration 'NdotLight' in the textured FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:26] [Render thread/WARN]: The in declaration 'NdotLight' in the textured_color FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:27] [Render thread/WARN]: The in declaration 'NdotLight' in the terrain_solid FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:27] [Render thread/WARN]: The in declaration 'NdotLight' in the terrain_cutout FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:27] [Render thread/WARN]: The in declaration 'NdotLight' in the terrain_translucent FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:27] [Render thread/WARN]: The in declaration 'NdotLight' in the moving_block FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:27] [Render thread/WARN]: The in declaration 'NdotLight' in the entities_alpha FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:28] [Render thread/WARN]: The in declaration 'NdotLight' in the entities_solid FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:28] [Render thread/WARN]: The in declaration 'NdotLight' in the entities_solid_diffuse FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:28] [Render thread/WARN]: The in declaration 'NdotLight' in the entities_solid_bright FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:28] [Render thread/WARN]: The in declaration 'NdotLight' in the entities_cutout FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:28] [Render thread/WARN]: The in declaration 'NdotLight' in the entities_cutout_diffuse FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:29] [Render thread/WARN]: The in declaration 'NdotLight' in the entities_translucent FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:29] [Render thread/WARN]: The in declaration 'NdotLight' in the entities_eyes FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:29] [Render thread/WARN]: The in declaration 'NdotLight' in the entities_eyes_trans FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:29] [Render thread/WARN]: The in declaration 'NdotLight' in the hand_cutout FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:30] [Render thread/WARN]: The in declaration 'NdotLight' in the hand_cutout_bright FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:30] [Render thread/WARN]: The in declaration 'NdotLight' in the hand_cutout_diffuse FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:30] [Render thread/WARN]: The in declaration 'NdotLight' in the hand_text FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:30] [Render thread/WARN]: The in declaration 'NdotLight' in the hand_text_intensity FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:30] [Render thread/WARN]: The in declaration 'NdotLight' in the hand_translucent FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:30] [Render thread/WARN]: The in declaration 'NdotLight' in the hand_water_bright FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:31] [Render thread/WARN]: The in declaration 'NdotLight' in the hand_water_diffuse FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:31] [Render thread/WARN]: The in declaration 'NdotLight' in the lightning FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:31] [Render thread/WARN]: The in declaration 'NdotLight' in the text_bg FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:31] [Render thread/WARN]: The in declaration 'NdotLight' in the particles FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:31] [Render thread/WARN]: The in declaration 'NdotLight' in the particles_trans FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:32] [Render thread/WARN]: The in declaration 'NdotLight' in the weather FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:32] [Render thread/WARN]: The in declaration 'NdotLight' in the crumbling FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:32] [Render thread/WARN]: The in declaration 'NdotLight' in the text FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:32] [Render thread/WARN]: The in declaration 'NdotLight' in the text_intensity FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:32] [Render thread/WARN]: The in declaration 'NdotLight' in the text_be FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:32] [Render thread/WARN]: The in declaration 'NdotLight' in the text_intensity_be FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:33] [Render thread/WARN]: The in declaration 'NdotLight' in the block_entity FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:33] [Render thread/WARN]: The in declaration 'NdotLight' in the block_entity_bright FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:33] [Render thread/WARN]: The in declaration 'NdotLight' in the block_entity_diffuse FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:33] [Render thread/WARN]: The in declaration 'NdotLight' in the be_translucent FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:33] [Render thread/WARN]: The in declaration 'NdotLight' in the beacon FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:34] [Render thread/WARN]: The in declaration 'NdotLight' in the glint FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:34] [Render thread/INFO]: Stopping worker threads
[18:11:34] [Render thread/INFO]: Started 2 worker threads
[18:11:34] [Render thread/INFO]: Stopping worker threads
[18:11:34] [Render thread/INFO]: Started 2 worker threads
[18:11:34] [Render thread/WARN]: The in declaration 'NdotLight' in the gbuffers_textured FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:35] [Render thread/WARN]: The in declaration 'NdotLight' in the gbuffers_textured FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:35] [Render thread/WARN]: The in declaration 'NdotLight' in the gbuffers_textured FRAGMENT shader that is never assigned to in the previous stage VERTEX has been compatibility-patched by adding an initialization for it. See debugging.md for more information.
[18:11:35] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering entity in world
	at net.minecraft.class_898.method_3954(class_898.java:185) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22977(class_761.java:1312) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.invokeRenderEntity(class_761.java) ~[client-intermediary.jar:?]
	at net.irisshaders.iris.shadows.ShadowRenderer.renderEntities(ShadowRenderer.java:636) ~[iris-1.7.3+mc1.21.jar:?]
	at net.irisshaders.iris.shadows.ShadowRenderer.renderShadows(ShadowRenderer.java:505) ~[iris-1.7.3+mc1.21.jar:?]
	at net.irisshaders.iris.pipeline.IrisRenderingPipeline.renderShadows(IrisRenderingPipeline.java:1020) ~[iris-1.7.3+mc1.21.jar:?]
	at net.minecraft.class_761.handler$zof000$iris$renderTerrainShadows(class_761.java:6277) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:977) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1087) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:850) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1285) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.3.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at net.minecraft.class_287.handler$bcg000$iris$beforeNext(class_287.java:1172) ~[client-intermediary.jar:?]
	at net.minecraft.class_287.method_60806(class_287.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_287.method_60805(class_287.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_287.method_22912(class_287.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4588.method_22918(class_4588.java:532) ~[client-intermediary.jar:?]
	at net.mehvahdjukaar.polytone.texture.LeashTexture.addVertexPair(LeashTexture.java:61) ~[polytone-1.21-2.3.12-fabric.jar:?]
	at net.minecraft.class_897.handler$bfo000$polytone$modifyLeashRender(class_897.java:1521) ~[client-intermediary.jar:?]
	at net.minecraft.class_897.method_61050(class_897.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_897.method_61049(class_897.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.class_897.method_3936(class_897.java:88) ~[client-intermediary.jar:?]
	at net.minecraft.class_922.method_4054(class_922.java:155) ~[client-intermediary.jar:?]
	at net.minecraft.class_922.method_3936(class_922.java:30) ~[client-intermediary.jar:?]
	at net.minecraft.class_898.method_3954(class_898.java:148) ~[client-intermediary.jar:?]
	... 18 more
[18:11:36] [Server thread/INFO]: Stopping server
[18:11:36] [Server thread/INFO]: Saving players
[18:11:36] [Server thread/INFO]: Saving worlds
[18:11:37] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[18:11:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[18:11:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[18:11:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[18:11:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[18:11:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[18:11:39] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[18:11:39] [Render thread/INFO]: Stopping worker threads
```

**Comment by IMS212** [comment]
Does this happen on Iris 1.8?

**Comment by MehVahdJukaar** [comment]
it does not. i assume its then fixed in the most recent version. i was sent this log by somebody using old sodium hence requiring this version here
