### ISSUE TITLE
sodium keeps crashing my game

### ISSUE THREAD

**Issue by that1guy88** [IrisShaders/Iris#2468]
### Minecraft Version

Minecrat 1.20.1

### Iris Version

none

### Sodium Version

sodium-fabric-0.5.11+mc1.20.1-build.101.jar

### Operating System

windows 11

### What is your GPU?

rtx 2070 super

### Java Version

java 11

### Reproduction Steps

i have a shit ton o mods installed and they all work together some what with out sodium, minus the bad fps. when i install sodium it completely crashes when loading into a world. ive installed reeses sodium options, sodium extra, and sodium/embeddium dynamic lights. Iris also doesnt seem to work but not a big deal. i have DH installed and have tried with out it and still crashes, also have indium installed

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-09-08 23:09:01
Description: Unexpected error

java.lang.RuntimeException: Exception thrown while executing job
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobResult.unwrap(ChunkJobResult.java:27)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.collectChunkBuildResults(RenderSectionManager.java:347)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.uploadChunks(RenderSectionManager.java:280)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.setupTerrain(SodiumWorldRenderer.java:191)
	at net.minecraft.class_761.method_3273(class_761.java:14035)
	at net.minecraft.class_761.method_22710(class_761.java:1247)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in me/jellysquid/mods/sodium/client/render/chunk/compile/tasks/ChunkBuilderMeshingTask::execute(Lme/jellysquid/mods/sodium/client/render/chunk/compile/ChunkBuildContext;Lme/jellysquid/mods/sodium/client/util/task/CancellationToken;)Lme/jellysquid/mods/sodium/client/render/chunk/compile/ChunkBuildOutput; has incompatible changes at opcode 150 in callback extra_details-common.mixins.json:client.sodium.ChunkBuilderMeshingTaskMixin from mod extra_details->@Inject::execute(Lme/jellysquid/mods/sodium/client/render/chunk/compile/ChunkBuildContext;Lme/jellysquid/mods/sodium/client/util/task/CancellationToken;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lme/jellysquid/mods/sodium/client/render/chunk/data/BuiltSectionInfo$Builder;Lnet/minecraft/class_852;Lme/jellysquid/mods/sodium/client/render/chunk/compile/ChunkBuildBuffers;Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderCache;Lme/jellysquid/mods/sodium/client/world/WorldSlice;IIIIIILnet/minecraft/class_2338$class_2339;Lnet/minecraft/class_2338$class_2339;Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderContext;IIILnet/minecraft/class_2680;Lnet/minecraft/class_3610;)V.
 Expected: [Lme/jellysquid/mods/sodium/client/render/chunk/data/BuiltSectionInfo$Builder;, Lnet/minecraft/class_852;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/ChunkBuildBuffers;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderCache;, Lme/jellysquid/mods/sodium/client/world/WorldSlice;, I, I, I, I, I, I, Lnet/minecraft/class_2338$class_2339;, Lnet/minecraft/class_2338$class_2339;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderContext;, I, I, I, Lnet/minecraft/class_2680;, Lnet/minecraft/class_3610;]
    Found: [Lme/jellysquid/mods/sodium/client/render/chunk/data/BuiltSectionInfo$Builder;, Lnet/minecraft/class_852;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/ChunkBuildBuffers;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderCache;, Lme/jellysquid/mods/sodium/client/world/WorldSlice;, I, I, I, I, I, I, Lnet/minecraft/class_2338$class_2339;, Lnet/minecraft/class_2338$class_2339;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderContext;, I, I, I, Lnet/minecraft/class_2680;]
Available: [Lme/jellysquid/mods/sodium/client/render/chunk/data/BuiltSectionInfo$Builder;, Lnet/minecraft/class_852;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/ChunkBuildBuffers;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderCache;, Lme/jellysquid/mods/sodium/client/world/WorldSlice;, I, I, I, I, I, I, Lnet/minecraft/class_2338$class_2339;, Lnet/minecraft/class_2338$class_2339;, Lme/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderContext;, I, I, I, Lnet/minecraft/class_2680;]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.handler$ceh000$extra_details$execute$missing(ChunkBuilderMeshingTask.java)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:88)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobResult.unwrap(ChunkJobResult.java:27)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.collectChunkBuildResults(RenderSectionManager.java:347)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.uploadChunks(RenderSectionManager.java:280)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.setupTerrain(SodiumWorldRenderer.java:191)
	at net.minecraft.class_761.method_3273(class_761.java:14035)
	at net.minecraft.class_761.method_22710(class_761.java:1247)
	at net.minecraft.class_757.method_3188(class_757.java:1110)

-- Affected level --
Details:
	All players: 1 total; [class_746['Erod88'/166, l='ClientLevel', x=-17.55, y=88.00, z=255.78]]
	Chunk stats: 4096, 401
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,108,0), Section: (at 0,12,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 4331 game time, 4331 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, Moonlight Mods Dynamic Assets, file/astraliyte-s-animated-textures-1-3.zip, seasons:seasonal_lush_caves, file/FreshAnimations_v1.9.2.zip, file/enchant icons 1.20 v1.3.zip

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1733429712 bytes (1653 MiB) / 5704253440 bytes (5440 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2070 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e84
	Graphics card #0 versionInfo: DriverVersion=32.0.15.6070
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 16384.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 69581.31
	Virtual memory used (MB): 28585.46
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 97.72
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -Xms256m
	Fabric Mods: 
		adorn: Adorn 5.0.1+1.20.1
		advancednetherite: Advanced Netherite 2.1.3-1.20.1
		advancementplaques: Advancement Plaques 1.4.11
		amendments: Amendments 1.20-1.2.11
		appleskin: AppleSkin 2.5.1+mc1.20
		architectury: Architectury 9.2.14
		athena: Athena 3.1.2
		attributefix: AttributeFix 21.0.4
		axiom: Axiom 1.5.1
			com_moulberry_axiomclientapi_axiomclientapi_: axiomclientapi 1.0.0
		badpackets: Bad Packets 0.4.3
		balm-fabric: Balm 7.3.9
			kuma_api: KumaAPI 20.1.8
		bcc: BetterCompatibilityChecker 4.0.8
		beaconoverhaul: Beacon Overhaul 1.8.4+1.20
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		better_totem_of_undying: Better Totem of Undying [FABRIC] 1.20.1-1.1.0
		betteradvancements: Better Advancements 0.4.2.10
		betteranimationscollection: Better Animations Collection 8.0.0
		betterchunkloading: Better chunk loading mod 1.20.1-4.3
		betterclouds: Better Clouds 1.3.13+1.20.1
		bettercombat: Better Combat 1.8.6+1.20.1
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.4
		betterendisland: YUNG's Better End Island 1.20-Fabric-2.0.6
		betterf3: BetterF3 7.0.2
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.6
		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.5
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.4
		bettersmithingtable: BetterSmithingTable 1.1.0
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		betterthanmending: BetterThanMending 1.3.0
		bettervillage: Better village 3.1.0
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
		biomemakeover: Biome Makeover 1.20.1-1.11.4
			taniwha: Taniwha 1.20.0-5.4.4
		bookshelf: Bookshelf 20.2.13
		botarium: Botarium 2.3.4
			team_reborn_energy: Energy 3.0.0
		bridgingmod: Bridging Mod 2.3.2+1.20.1
		carryon: Carry On 2.1.2.7
		chipped: Chipped 3.0.6
		chiselsandbits: chisels-and-bits 1.4.148
			org_lz4_lz4-pure-java: lz4-pure-java 1.8.0
			saeculariacaudices: Saecularia Caudices 1.0.23
			scena: Scena 1.0.103
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.4
		collective: Collective 7.84
		coloredendcrystals: ColoredEndCrystals 1.0.1
		connectedglass: Connected Glass 1.1.12
		connectiblechains: Connectible Chains 2.2.1+1.20.1
		connectivity: Connectivity Mod 1.20.1-5.6
		controlling: Controlling For Fabric 12.0.2
		craftify: Craftify 1.16.0
			elementa: Elementa 636
			universalcraft: UniversalCraft 342
			vigilance: Vigilance 295
		crafttweaker: CraftTweaker 14.0.43
		cupboard: cupboard 1.20.1-2.7
		detailab: Detail Armor Bar 2.6.3+1.20.1-fabric
		distanthorizons: Distant Horizons 2.2.1-a
		drippyloadingscreen: Drippy Loading Screen 2.2.5
		durabilitytooltip: Durability Tooltip 1.1.5
		easyanvils: Easy Anvils 8.0.2
		easymagic: Easy Magic 8.0.1
		easyshulkerboxes: Easy Shulker Boxes 8.0.2
			puzzlesapi: Puzzles Api 8.1.6
				cardinal-components-base: Cardinal Components API (base) 5.2.2
				cardinal-components-entity: Cardinal Components API (entities) 5.2.2
				puzzlesaccessapi: Puzzles Access Api 8.0.9
		elytraslot: Elytra Slot 6.4.2+1.20.1
			mixinsquared: MixinSquared 0.1.2-beta.6
		enchantinginfuser: Enchanting Infuser 8.0.3
		enchdesc: EnchantmentDescriptions 17.1.18
		entity_model_features: Entity Model Features 2.2.4
		entity_texture_features: Entity Texture Features 6.2.3
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.7.0
		euphoria_patcher: Euphoria Patcher 0.3.4-fabric
			io_sigpipe_jbsdiff: jbsdiff 1.0
		evs: Enchanted Vertical Slabs 2.2.1-backport1.20.1
		explorify: Explorify 1.6.1
		extra_details: Panda's Extra Detail's 0.3.1-beta
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.12.1+kotlin.2.0.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.3
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.3
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.1
		fabricloader: Fabric Loader 0.16.5
		fallingleaves: Falling Leaves 1.15.6
		fancymenu: FancyMenu 2.14.13
		faux-custom-entity-data: Faux-Custom-Entity-Data 6.0.1
		flow: Flow 2.1.2+1.20.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		forgeconfigscreens: Forge Config Screens 8.0.2
		fpsreducer: FPS Reducer 1.20-2.5
		framework: Framework 0.6.16
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			org_javassist_javassist: javassist 3.29.2-GA
		fusion: Fusion 1.1.1
		geckolib: GeckoLib 4 4.4.9
			com_eliotlash_mclib_mclib: mclib 20
		geophilic: Geophilic 3.1.1
		goblintraders: Goblin Traders 1.9.3
		gpumemleakfix: Gpu memory leak fix mod 1.20.1-1.8
		guardvillagers: GuardVillagers 2.0.9-1.20.1
		handcrafted: Handcrafted 3.0.6
		held-item-info: Held Item Info 1.5.0
		iceberg: Iceberg 1.1.18
		immersive_paintings: Immersive Paintings 0.6.7+1.20.1
		indium: Indium 1.0.34+mc1.20.1
		inventoryhud: Inventory HUD + 3.4.26
		inventoryprofilesnext: Inventory Profiles Next 1.10.10
		invmove: InvMove 0.8.4
		ironchest: Iron Chests 2.0.2
			libgui: LibGui 8.1.1+1.20.1
				jankson: Jankson 6.0.0+j1.2.3
					blue_endless_jankson: jankson 1.2.3
				libninepatch: LibNinePatch 1.2.0
		itemborders: Item Borders 1.2.2
		items_displayed: Items Displayed 1.2.2
		jade: Jade 11.11.0+fabric
		jamlib: JamLib 0.6.1+1.20.x
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.18.0.78
		jeresources: Just Enough Resources 1.4.0.247
		jewelry: Jewelry (RPG Series) 1.3.7+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
		journeymap: Journeymap 5.10.2
			journeymap-api-fabric: JourneyMap API 1.20-1.9-fabric-SNAPSHOT
		jumpoverfences: Jump Over Fences 1.3.1
		konkrete: Konkrete 1.8.1
		leahs-immersive-thunder: Immersive Thunder 1.20.1+1.2.2
		legendary_origins: Legendary Origins 1.24.5
		legendarytooltips: Legendary Tooltips 1.4.5
		libipn: libIPN 4.0.2
		libraryferret: Library ferret 4.0.0
		litematica: Litematica 0.15.3
		lootbeams: LootBeams 1.0.3
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		majruszlibrary: Majrusz Library 7.0.8
		majruszsenchantments: Majrusz's Enchantments 1.10.8
		malilib: MaLiLib 0.16.3
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20.1
		modernfix: ModernFix 5.19.4+mc1.20.1
		modmenu: Mod Menu 7.2.2
		moonlight: Moonlight 1.20-2.12.20
		moremobvariants: More Mob Variants 1.3.1
		mousetweaks: Mouse Tweaks 2.26
		mr_daycounter: Day Counter (Original) 1.1.1
		mru: Mineblock's Repeated Utilities 1.0.2+1.20.1+fabric
		neat: Neat 1.20-35-FABRIC
			fiber: fiber 0.23.0-2
		notenoughanimations: NotEnoughAnimations 1.7.6
		nullscape: Nullscape 1.2.7
		origins: Origins 1.10.0
			apoli: Apoli 2.9.0
				additionalentityattributes: Additional Entity Attributes 1.3.0+1.20.0
				calio: Calio 1.11.0
				playerabilitylib: Pal 1.8.0
		particlerain: Particle Rain 2.0.8
		pehkui: Pehkui 3.8.3+1.14.4-1.21
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		pickupnotifier: Pick Up Notifier 8.0.0
		player-animator: Player Animator 1.0.2-rc1+1.20
		presencefootsteps: Presence Footsteps 1.9.4+1.20.1
			kirin: Kirin UI 1.15.6+1.20.1
		prism: Prism 1.0.5
		puffish_skills: Pufferfish's Skills 0.13.2
		puzzleslib: Puzzles Lib 8.1.22
		ranged_weapon_api: RangedWeaponAPI 1.1.4+1.20.1
		rare-ice: Rare Ice 0.6.0
		rechiseled: Rechiseled 1.1.6
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.1-build.101
		repurposed_structures: Repurposed Structures 7.1.15+1.20.1-fabric
		resourcefullib: Resourceful Lib 2.1.29
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		rightclickharvest: Right Click Harvest 3.2.3+1.19.x-1.20.1-fabric
		rocks: This Rocks! 1.7.1
		searchables: Searchables 1.0.3
		seasons: Fabric Seasons 2.3+1.20
		seasonsterralithcompat: Fabric Seasons: Terralith Compat 1.0-2.3.7
		skinlayers3d: 3d-Skin-Layers 1.6.7
		smoothswapping: Smooth Swapping 0.9.3.1
		sodium: Sodium 0.5.11+mc1.20.1
		sodium-extra: Sodium Extra 0.5.4+mc1.20.1-build.115
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.4.5
		sounds: Sounds 2.0.4+1.20.1+fabric
			mixinextras: MixinExtras 0.5.0-beta.2
		spawn_animations_mr: Spawn Animations 1.9.1
		spell_power: Spell Power Attribute 0.12.0+1.20.1
		starlight: Starlight 1.1.2+fabric.dbc156f
		starterkit: Starter Kit 7.1
		structory: Structory 1.3.5
		structure_pool_api: Structure Pool API 1.0+1.20.1
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17+a
		supplementaries: Supplementaries 1.20-2.8.17
		tawct: Time & Wind Custom Ticker 1.4.8+1.20-1.20.1
		terralith: Terralith 2.5.4
		tia: Tiny Item Animations 1.20-1.1
		tipthescales: Tip The Scales 9.0.0.1
		toms_storage: Tom's Simple Storage Mod 1.6.8
		travelerstitles: Traveler's Titles 1.20-Fabric-4.0.2
		treeharvester: Tree Harvester 9.1
		trimeffects: TrimsEffects 1.3.5
		trinkets: Trinkets 3.7.2
		visuality: Visuality 0.7.1+1.20
		visualworkbench: Visual Workbench 8.0.0
		waystones: Waystones 14.1.5
		worldedit: WorldEdit 7.2.15+6463-5ca4dff
		wthit: wthit 8.15.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.20.1-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yungsapi: YUNG's API 1.20-Fabric-4.0.5
		yungsbridges: YUNG's Bridges 1.20-Fabric-4.0.3
		yungsextras: YUNG's Extras 1.20-Fabric-4.0.3
		yungsmenutweaks: YUNG's Menu Tweaks 1.20.1-Fabric-1.0.2
		zoomify: Zoomify 2.14.0+1.20.1
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.1
	Launched Version: fabric-loader-0.16.5-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 560.70, NVIDIA Corporation
	Window size: 1024x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, Moonlight Mods Dynamic Assets, file/astraliyte-s-animated-textures-1-3.zip, seasons:seasonal_lush_caves, file/FreshAnimations_v1.9.2.zip, file/enchant icons 1.20 v1.3.zip
	Current Language: en_us
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['Erod88'/166, l='ServerLevel[fuck it]', x=-17.55, y=88.00, z=255.78]]
	Data Packs: vanilla, fabric, Moonlight Mods Dynamic Assets, Supplementaries Generated Pack
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
```

**Comment by that1guy88** [comment]
java 8 not 11

**Comment by that1guy88** [comment]
going to leave this up. but i went mod by mod to see what the problem was and it was pandas extra details mod. or some reason it was crashing with sodium. with all my mods installed sodium was a must. at max 60ps without it and now 300 avg

**Comment by IMS212** [comment]
This bug is solely caused by Extra Details.
