### ISSUE TITLE
Iris crashes and the game closes on add shader

### ISSUE THREAD

**Issue by altheaws** [IrisShaders/Iris#2496]
### Minecraft Version

1.20.1

### Iris Version

1.7.5

### Sodium Version

0.5.11

### Operating System

Windows 11 

### What is your GPU?

AMD Ryzen 5 4600G

### Java Version

Java 8

### Reproduction Steps

> 1. Install Iris
> 2. Enter your world in Minecraft
> 3. Add a shader
> 4. Crash

### Crash Report file and latest.log

// Who set us up the TNT?
--
3 |  
4 | Time: 2024-10-21 14:51:23
5 | Description: Unexpected error
6 |  
7 | java.lang.NoSuchFieldError: TESSELATION_SHADERS
8 | at net.irisshaders.iris.shaderpack.programs.ProgramSet.handler$hne000$irisflw$initGBufferFlw(ProgramSet.java:536)
9 | at net.irisshaders.iris.shaderpack.programs.ProgramSet.<init>(ProgramSet.java:76)
10 | at net.irisshaders.iris.shaderpack.ShaderPack.<init>(ShaderPack.java:294)
11 | at net.irisshaders.iris.Iris.loadExternalShaderpack(Iris.java:319)
12 | at net.irisshaders.iris.Iris.loadShaderpack(Iris.java:237)
13 | at net.irisshaders.iris.Iris.handleKeybinds(Iris.java:155)
14 | at MC//net.minecraft.client.MinecraftClient.handler$hgj00b$iris$onTick(MinecraftClient.java:34533)
15 | at MC//net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1957)
16 | at MC//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1181)
17 | at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
18 | at net.minecraft.client.main.Main.main(Main.java:250)
19 | at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
20 | at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
21 | at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
22 |  
23 |  
24 | A detailed walkthrough of the error, its code path and all known details is as follows:
25 | ---------------------------------------------------------------------------------------
26 |  
27 | -- Head --
28 | Thread: Render thread
29 | Stacktrace:
30 | at net.irisshaders.iris.shaderpack.programs.ProgramSet.handler$hne000$irisflw$initGBufferFlw(ProgramSet.java:536)
31 | at net.irisshaders.iris.shaderpack.programs.ProgramSet.<init>(ProgramSet.java:76)
32 | at net.irisshaders.iris.shaderpack.ShaderPack.<init>(ShaderPack.java:294)
33 | at net.irisshaders.iris.Iris.loadExternalShaderpack(Iris.java:319)
34 | at net.irisshaders.iris.Iris.loadShaderpack(Iris.java:237)
35 | at net.irisshaders.iris.Iris.handleKeybinds(Iris.java:155)
36 | at MC//net.minecraft.client.MinecraftClient.handler$hgj00b$iris$onTick(MinecraftClient.java:34533)
37 | Mixins in Stacktrace:
38 | net.irisshaders.iris.shaderpack.programs.ProgramSet:
39 | top.leonx.irisflw.mixin.ProgramSetMixin (irisflw.mixins.iris.json)
40 |  
41 | -- Last reload --
42 | Details:
43 | Reload number: 1
44 | Reload reason: initial
45 | Finished: No
46 | Packs: vanilla, fabric, file/Ashen_1.8.2.zip, file/Ashen_Custom_Mobs.zip, file/Ashen_Mod_Compatibility.zip, file/Mandala_x_Prominent_UI.zip, file/Ashen_Simple_Foliage.zip, file/Prominent-UI-1.20.1.zip, file/Frosty-Deathchill.zip, file/Prominence-Custom-Lootr.zip, file/ProminenceFancyServerListing.zip, Moonlight Mods Dynamic Assets, convenientdecor:hydrated_farmland, tinyskeletons:main, prominent:archon, file/[1.3] Enhanced Boss Bars.zip, file/FreshAnimations_v1.9.2.zip, file/Ashen_Custom_Mobs_x_Fresh_Animations.zip, file/Mandalas_Legacy_Gui_Background.zip, file/HTP-Betterarcheology-TranslationPack-v1.0.0.zip, file/HTP-Invoke-TranslationPack-vunknown.zip, file/HTP-Minecells-TranslationPack-v1.0.0.zip, file/HTP-Spell_power-TranslationPack-vunknown.zip, file/Ashen_Advanced_Netherite_Support_1.0.zip, file/Ashen_Eldritch_End_Support_1.0.zip, file/Ashen_Lets_Do_Support_1.0.zip, file/Ashen_Regions_Unexplored_Support_1.0.zip, file/Ashen_Visuality_Support_1.0.zip, loadmyresources.hiddenpack
47 | Stacktrace:
48 | at MC//net.minecraft.client.resource.ResourceReloadLogger.addReloadSection(ResourceReloadLogger.java:49)
49 | at MC//net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2413)
50 | at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:826)
51 | at net.minecraft.client.main.Main.main(Main.java:250)
52 | at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
53 | at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
54 | at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
55 | Mixins in Stacktrace:
56 | net.minecraft.client.main.Main:
57 | com.jozufozu.flywheel.mixin.ClientMainMixin (flywheel.mixins.json)

</body>
</html>// Who set us up the TNT?

Time: 2024-10-21 14:51:2[3](https://mclo.gs/KS8A1yf#L3)
Description: Unexpected error

java.lang.NoSuchFieldError: TESSELATION_SHADERS
	at net.irisshaders.iris.shaderpack.programs.ProgramSet.handler$hne000$irisflw$initGBufferFlw(ProgramSet.java:536)
	at net.irisshaders.iris.shaderpack.programs.ProgramSet.<init>(ProgramSet.java:76)
	at net.irisshaders.iris.shaderpack.ShaderPack.<init>(ShaderPack.java:29[4](https://mclo.gs/KS8A1yf#L4))
	at net.irisshaders.iris.Iris.loadExternalShaderpack(Iris.java:319)
	at net.irisshaders.iris.Iris.loadShaderpack(Iris.java:237)
	at net.irisshaders.iris.Iris.handleKeybinds(Iris.java:1[5](https://mclo.gs/KS8A1yf#L5)5)
	at MC//net.minecraft.client.MinecraftClient.handler$hgj00b$iris$onTick(MinecraftClient.java:34533)
	at MC//net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1957)
	at MC//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1181)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.irisshaders.iris.shaderpack.programs.ProgramSet.handler$hne000$irisflw$initGBufferFlw(ProgramSet.java:53[6](https://mclo.gs/KS8A1yf#L6))
	at net.irisshaders.iris.shaderpack.programs.ProgramSet.<init>(ProgramSet.java:[7](https://mclo.gs/KS8A1yf#L7)6)
	at net.irisshaders.iris.shaderpack.ShaderPack.<init>(ShaderPack.java:294)
	at net.irisshaders.iris.Iris.loadExternalShaderpack(Iris.java:319)
	at net.irisshaders.iris.Iris.loadShaderpack(Iris.java:237)
	at net.irisshaders.iris.Iris.handleKeybinds(Iris.java:155)
	at MC//net.minecraft.client.MinecraftClient.handler$hgj00b$iris$onTick(MinecraftClient.java:34533)
Mixins in Stacktrace:
	net.irisshaders.iris.shaderpack.programs.ProgramSet:
		top.leonx.irisflw.mixin.ProgramSetMixin (irisflw.mixins.iris.json)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, fabric, file/Ashen_1.[8](https://mclo.gs/KS8A1yf#L8).2.zip, file/Ashen_Custom_Mobs.zip, file/Ashen_Mod_Compatibility.zip, file/Mandala_x_Prominent_UI.zip, file/Ashen_Simple_Foliage.zip, file/Prominent-UI-1.20.1.zip, file/Frosty-Deathchill.zip, file/Prominence-Custom-Lootr.zip, file/ProminenceFancyServerListing.zip, Moonlight Mods Dynamic Assets, convenientdecor:hydrated_farmland, tinyskeletons:main, prominent:archon, file/[1.3] Enhanced Boss Bars.zip, file/FreshAnimations_v1.[9](https://mclo.gs/KS8A1yf#L9).2.zip, file/Ashen_Custom_Mobs_x_Fresh_Animations.zip, file/Mandalas_Legacy_Gui_Background.zip, file/HTP-Betterarcheology-TranslationPack-v1.0.0.zip, file/HTP-Invoke-TranslationPack-vunknown.zip, file/HTP-Minecells-TranslationPack-v1.0.0.zip, file/HTP-Spell_power-TranslationPack-vunknown.zip, file/Ashen_Advanced_Netherite_Support_1.0.zip, file/Ashen_Eldritch_End_Support_1.0.zip, file/Ashen_Lets_Do_Support_1.0.zip, file/Ashen_Regions_Unexplored_Support_1.0.zip, file/Ashen_Visuality_Support_1.0.zip, loadmyresources.hiddenpack
Stacktrace:
	at MC//net.minecraft.client.resource.ResourceReloadLogger.addReloadSection(ResourceReloadLogger.java:49)
	at MC//net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:24[13](https://mclo.gs/KS8A1yf#L13))
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Mixins in Stacktrace:
	net.minecraft.client.main.Main:
		com.jozufozu.flywheel.mixin.ClientMainMixin (flywheel.mixins.json)

**Comment by Poopooracoocoo** [comment]
Make sure Iris Flywheel Compat is up to date.
