### ISSUE TITLE
Shaders stop working after reloading them

### ISSUE THREAD

**Issue by Mohawk1025** [IrisShaders/Iris#2517]
### Minecraft Version

1.21.1

### Iris Version

1.8.0-beta.7+mc1.21.1

### Sodium Version

0.6.0-beta.4+mc1.21.1

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce RTX 3080

### Java Version

Java 8

### Reproduction Steps

I am playing on All the Mods 10.  Everything was working fine until I updated to All the Mods 10 1.16. Now the shader pack works when I first start up the game, but if I travel to another dimension (e.g., the Mining Dimension), it stops working and cannot be reloaded. A message pops up that says:

"Iris encountered an issue trying to load the shader; please report this to Iris developers. Copy Info"

The info just says

"Shader compilation failed, see log for details"

I'm not sure which log to upload.

**Comment by Mohawk1025** [comment]
Just checked, and the issue also happens without traveling to a different dimension. I loaded up the game; shaders are working. I hit the hotkey to reload shaders, and after the second reload it stopped working and gave me the same error message.

**Comment by Mohawk1025** [comment]
I should also add this is happening with multiple shader packs (specifically BSL Original, and Complementary Unbound + Euphoria Patches).

**Comment by Mohawk1025** [comment]
OK, just checked again and it appears to be happening with every shader pack that's in All the Mods 10. As soon as I reload shaders it stops working.

**Comment by Mohawk1025** [comment]
I downgraded to ATM 10 1.15, and the issue disappeared, so it's something with version 1.16.

This is their changelog for 1.16.

• Added KeybindsPurger
• Added Mekanism Covers
• Removed Achievement Optimizer
• Made Omega Upgrade use unobtainium nuggets (Satherov)
• Added Stave's carts to the ATM Star (wtd)
• Added Nature's Aura Quests (Toblerone)
• Added Ore hammer dust from various modded ingots (pr0saic)
• Added Undergarden Quest (ToshibaEC0Microwave)
• Neoforge Version is 21.1.73

That's the same version of Neoforge as 1.15, so maybe it's something else in one of those updates? I suspected Mekanism Covers at one point, but I removed all the covers I had placed in the world, and issue still persisted.

**Comment by Luracasmus** [comment]
The relevant log file will be located at `.minecraft/logs/latest.log` when the issue occurs, and can be uploaded here in it's entirety

Are you sure you're running this version of Minecraft with Java 8, by the way? I'm pretty sure 1.21.1 requires Java 21+ unless there's some mod or Neoforge itself lowering that requirement. Both the vanilla launcher and the Modrinth app should install and use Java 21 by default, regardless of what Java version you might already have on your system

**Comment by IMS212** [comment]
I have confirmed this is a bug with Mekanism Covers. It edits the shader code of all shaders to try to make their covers change in real time.

**Comment by Mohawk1025** [comment]
> I have confirmed this is a bug with Mekanism Covers. It edits the shader code of all shaders to try to make their covers change in real time.

I had a suspicion it was that mod. Thanks for confirming. Hope it gets patched soon. I was super excited when I saw they had released Mekanism Covers.

**Comment by Mohawk1025** [comment]
> The relevant log file will be located at `.minecraft/logs/latest.log` when the issue occurs, and can be uploaded here in it's entirety
> 
> Are you sure you're running this version of Minecraft with Java 8, by the way? I'm pretty sure 1.21.1 requires Java 21+ unless there's some mod or Neoforge itself lowering that requirement. Both the vanilla launcher and the Modrinth app should install and use Java 21 by default, regardless of what Java version you might already have on your system

No, you're right. I had to download the JDK to run this modpack, and it's Version 23. I got confused because I checked the Java control panel, and for some reason it says Version 8. (I'm launching through Curseforge.)

Also I don't know if I still have the relevant log file since I downgraded to ATM 10 1.15. But another user commented in here that they confirmed the problem is with Mekanism Covers.

**Comment by IMS212** [comment]
(I’m the lead developer lol)

**Comment by Mohawk1025** [comment]
> (I’m the lead developer lol)

Oh, haha. Thanks for replying!

**Comment by Mobijuan** [comment]
I have set disableAdvancedCoverRendering to true in the mekanismcovers config and it seems to have stopped the crashes (though mekanism cables still become visually bugged after teleporting).

**Comment by Mohawk1025** [comment]
> I have set disableAdvancedCoverRendering to true in the mekanismcovers config and it seems to have stopped the crashes (though mekanism cables still become visually bugged after teleporting).

Does reloading the shaders fix the cable visual bug? I was having that issue even before Mekanism Covers. Reloading the shaders would fix it though.

**Comment by Mobijuan** [comment]
> > I have set disableAdvancedCoverRendering to true in the mekanismcovers config and it seems to have stopped the crashes (though mekanism cables still become visually bugged after teleporting).
> 
> Does reloading the shaders fix the cable visual bug? I was having that issue even before Mekanism Covers. Reloading the shaders would fix it though.

Reloading does indeed fix the visual bug.

**Comment by DefaultLP** [comment]
Indeed the `mekanismCoverInjectMat` seems to be the issue. I am using Craftoria 1.7.2 which uses Neoforge 21.1.76. Since the crash logs were never posted here I thought it might be useful.

```
[12Nov2024 11:38:59.987] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] Iris encountered an issue trying to load the shader; please report this to Iris developers. Copy Info
[12Nov2024 11:38:59.988] [Render thread/ERROR] [Iris/]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.RuntimeException: Shader compilation failed, see log for details
	at TRANSFORMER/sodium@0.6.0-beta.4+mc1.21.1/net.caffeinemc.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:34) ~[sodium-neoforge-0.6.0-beta.4+mc1.21.1.jar%23820!/:?]
	at TRANSFORMER/iris@1.8.0-beta.8+mc1.21.1/net.irisshaders.iris.pipeline.programs.SodiumPrograms.createGlShaders(SodiumPrograms.java:99) ~[iris-neoforge-1.8.0-beta.8+mc1.21.1.jar%23693!/:?]
	at TRANSFORMER/iris@1.8.0-beta.8+mc1.21.1/net.irisshaders.iris.pipeline.programs.SodiumPrograms.<init>(SodiumPrograms.java:66) ~[iris-neoforge-1.8.0-beta.8+mc1.21.1.jar%23693!/:?]
	at TRANSFORMER/iris@1.8.0-beta.8+mc1.21.1/net.irisshaders.iris.pipeline.IrisRenderingPipeline.<init>(IrisRenderingPipeline.java:451) ~[iris-neoforge-1.8.0-beta.8+mc1.21.1.jar%23693!/:?]
	at TRANSFORMER/iris@1.8.0-beta.8+mc1.21.1/net.irisshaders.iris.Iris.createPipeline(Iris.java:616) ~[iris-neoforge-1.8.0-beta.8+mc1.21.1.jar%23693!/:?]
	at TRANSFORMER/iris@1.8.0-beta.8+mc1.21.1/net.irisshaders.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:33) ~[iris-neoforge-1.8.0-beta.8+mc1.21.1.jar%23693!/:?]
	at TRANSFORMER/iris@1.8.0-beta.8+mc1.21.1/net.irisshaders.iris.Iris.reload(Iris.java:567) ~[iris-neoforge-1.8.0-beta.8+mc1.21.1.jar%23693!/:?]
	at TRANSFORMER/iris@1.8.0-beta.8+mc1.21.1/net.irisshaders.iris.Iris.handleKeybinds(Iris.java:161) ~[iris-neoforge-1.8.0-beta.8+mc1.21.1.jar%23693!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.handler$zgn000$iris$onTick(Minecraft.java:6511) ~[client-1.21.1-20240808.144430-srg.jar%23527!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.tick(Minecraft.java:1916) ~[client-1.21.1-20240808.144430-srg.jar%23527!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.runTick(Minecraft.java:1161) ~[client-1.21.1-20240808.144430-srg.jar%23527!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[client-1.21.1-20240808.144430-srg.jar%23527!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21.1-20240808.144430-srg.jar%23527!/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.31.jar%23128!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.31.jar%23128!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.31.jar%23128!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.31.jar%23128!/:4.0]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23101!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23101!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23101!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23101!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23101!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23101!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23101!/:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?]
[12Nov2024 11:38:59.991] [Render thread/INFO] [ChunkBuilder/]: Stopping worker threads
[12Nov2024 11:38:59.997] [Render thread/INFO] [ChunkBuilder/]: Started 10 worker threads
[12Nov2024 11:39:00.001] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] Shaders Reloaded!
[12Nov2024 11:39:04.396] [Render thread/INFO] [Iris/]: Destroying pipeline minecraft:overworld
[12Nov2024 11:39:04.455] [Render thread/INFO] [Iris/]: Profile: Custom (+1 option changed by user)
[12Nov2024 11:39:04.694] [Render thread/INFO] [Iris/]: Using shaderpack: ComplementaryReimagined_r5.3 + EuphoriaPatches_1.4.3
[12Nov2024 11:39:04.694] [Render thread/INFO] [Iris/]: Creating pipeline for dimension minecraft:overworld
[12Nov2024 11:39:04.912] [Render thread/WARN] [net.caffeinemc.mods.sodium.client.gl.shader.GlShader/]: Shader compilation log for iris:sodium-shader-translucent: 0(3) : error C1038: declaration of "mekanismCoverInjectMat" conflicts with previous declaration at 0(2)
0(4) : error C1038: declaration of "mekanismCoverInjectMat" conflicts with previous declaration at 0(2)
0(5) : error C1038: declaration of "mekanismCoverInjectMat" conflicts with previous declaration at 0(2)
0(6) : error C1038: declaration of "mekanismCoverInjectMat" conflicts with previous declaration at 0(2)
0(7) : error C1038: declaration of "mekanismCoverInjectMat" conflicts with previous declaration at 0(2)
```

**Comment by 19Arice** [comment]
A god send,

changing disableAdvancedCoverRendering false to true worked for me as well.
Located in \config\mekanismcovers.json for anyone else that has this issue on ATM 10 before its released as a patch
