### ISSUE TITLE
Can not enable shaders in Craftoria 1.61, shader compilation failed.

### ISSUE THREAD

**Issue by jpeaglesandkatz** [IrisShaders/Iris#2518]
### What happened?

Fully updated windows 11 24h2.. Fully updated nvidia drivers on a 5800x3d, 3060ti, 64gigs DDR4-4000 system.

```
[07Nov2024 08:12:45.792] [Render thread/INFO] [Iris/]: Using shaderpack: ComplementaryReimagined_r5.2.2.zip
[07Nov2024 08:12:45.792] [Render thread/INFO] [Iris/]: Creating pipeline for dimension minecraft:overworld
[07Nov2024 08:12:46.086] [Render thread/WARN] [net.caffeinemc.mods.sodium.client.gl.shader.GlShader/]: Shader compilation log for iris:sodium-shader-translucent: 0(3) : error C1038: declaration of "mekanismCoverInjectMat" conflicts with previous declaration at 0(2)

[07Nov2024 08:12:46.088] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] Iris encountered an issue trying to load the shader; please report this to Iris developers. Copy Info
[07Nov2024 08:12:46.088] [Render thread/ERROR] [Iris/]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.RuntimeException: Shader compilation failed, see log for details
	at TRANSFORMER/sodium@0.6.0-beta.4+mc1.21.1/net.caffeinemc.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:34) ~[sodium-neoforge-0.6.0-beta.4+mc1.21.1.jar%23832!/:?]
	at TRANSFORMER/iris@1.8.0-beta.7+mc1.21.1/net.irisshaders.iris.pipeline.programs.SodiumPrograms.createGlShaders(SodiumPrograms.java:99) ~[iris-neoforge-1.8.0-beta.7+mc1.21.1.jar%23701!/:?]
	at TRANSFORMER/iris@1.8.0-beta.7+mc1.21.1/net.irisshaders.iris.pipeline.programs.SodiumPrograms.<init>(SodiumPrograms.java:66) ~[iris-neoforge-1.8.0-beta.7+mc1.21.1.jar%23701!/:?]
	at TRANSFORMER/iris@1.8.0-beta.7+mc1.21.1/net.irisshaders.iris.pipeline.IrisRenderingPipeline.<init>(IrisRenderingPipeline.java:451) ~[iris-neoforge-1.8.0-beta.7+mc1.21.1.jar%23701!/:?]
	at TRANSFORMER/iris@1.8.0-beta.7+mc1.21.1/net.irisshaders.iris.Iris.createPipeline(Iris.java:616) ~[iris-neoforge-1.8.0-beta.7+mc1.21.1.jar%23701!/:?]
	at TRANSFORMER/iris@1.8.0-beta.7+mc1.21.1/net.irisshaders.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:33) ~[iris-neoforge-1.8.0-beta.7+mc1.21.1.jar%23701!/:?]
	at TRANSFORMER/iris@1.8.0-beta.7+mc1.21.1/net.irisshaders.iris.Iris.reload(Iris.java:567) ~[iris-neoforge-1.8.0-beta.7+mc1.21.1.jar%23701!/:?]
	at TRANSFORMER/iris@1.8.0-beta.7+mc1.21.1/net.irisshaders.iris.apiimpl.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:28) ~[iris-neoforge-1.8.0-beta.7+mc1.21.1.jar%23701!/:?]
	at TRANSFORMER/iris@1.8.0-beta.7+mc1.21.1/net.irisshaders.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:617) ~[iris-neoforge-1.8.0-beta.7+mc1.21.1.jar%23701!/:?]
	at TRANSFORMER/iris@1.8.0-beta.7+mc1.21.1/net.irisshaders.iris.gui.screen.ShaderPackScreen.lambda$init$6(ShaderPackScreen.java:258) ~[iris-neoforge-1.8.0-beta.7+mc1.21.1.jar%23701!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.components.Button.onPress(Button.java:41) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.components.AbstractButton.onClick(AbstractButton.java:47) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/neoforge@21.1.72/net.neoforged.neoforge.client.extensions.IAbstractWidgetExtension.onClick(IAbstractWidgetExtension.java:36) ~[neoforge-21.1.72-universal.jar%23536!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.components.AbstractWidget.mouseClicked(AbstractWidget.java:144) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.components.events.ContainerEventHandler.mouseClicked(ContainerEventHandler.java:38) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/iris@1.8.0-beta.7+mc1.21.1/net.irisshaders.iris.gui.screen.ShaderPackScreen.mouseClicked(ShaderPackScreen.java:219) ~[iris-neoforge-1.8.0-beta.7+mc1.21.1.jar%23701!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.MouseHandler.lambda$onPress$0(MouseHandler.java:98) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.Screen.wrapScreenError(Screen.java:449) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.MouseHandler.onPress(MouseHandler.java:95) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.MouseHandler.lambda$setup$4(MouseHandler.java:202) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:98) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.MouseHandler.lambda$setup$5(MouseHandler.java:202) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.3+5/org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.3.jar%23101!/:build 5]
	at MC-BOOTSTRAP/org.lwjgl@3.3.3+5/org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar%23113!/:build 5]
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.3+5/org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) ~[lwjgl-glfw-3.3.3.jar%23101!/:build 5]
	at TRANSFORMER/minecraft@1.21.1/com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:134) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:147) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/com.mojang.blaze3d.platform.Window.updateDisplay(Window.java:290) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.runTick(Minecraft.java:1217) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.29.jar%23174!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.29.jar%23174!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.29.jar%23174!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.29.jar%23174!/:4.0]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23167!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23167!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23167!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23167!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23167!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23167!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23167!/:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-prism-2024-02-29.jar:prism-2024-02-29]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
[07Nov2024 08:12:46.090] [Render thread/INFO] [ChunkBuilder/]: Stopping worker threads
```

### Log output

[latest.log](https://github.com/user-attachments/files/17657569/latest.log)
[debug.log](https://github.com/user-attachments/files/17657570/debug.log)

### Minecraft Version

1.21.1

### Iris Version

iris-neoforge-1.8.0-beta.7+mc1.21.1

### Operating System

Windows 11 24h2

### What is your GPU?

3060ti

**Comment by IMS212** [comment]
Caused by Mekanism Covers.
