### ISSUE TITLE
Incompatible with Pegasus shader

### ISSUE THREAD

**Issue by TheWhiteDog9487** [IrisShaders/Iris#2526]
### Minecraft Version

Minecraft 1.21.3

### Iris Version

iris-fabric-1.8.0-beta.8+mc1.21.3.jar

### Sodium Version

sodium-fabric-0.6.0-beta.5+mc1.21.3.jar

### Operating System

Windows 11 (amd64) version 10.0

### What is your GPU?

NVIDIA GeForce RTX 3060 Ti

### Java Version

21.0.4, Azul Systems, Inc.

### Reproduction Steps

1. Install the following mods:
- sodium-fabric-0.6.0-beta.5+mc1.21.3.jar
- fabric-api-0.108.0+1.21.3.jar
- iris-fabric-1.8.0-beta.8+mc1.21.3.jar
- Fabric Loader 0.16.9

2. Install and enable shader:
- Pegasus 2024-11-10.zip
https://modrinth.com/shader/pegasus/version/0.1.1

3. Enter a single player world
4. Game crashes

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-11-15 11:02:18
Description: Unexpected error

java.lang.RuntimeException: Exception thrown while executing job
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.executor.ChunkJobResult.unwrap(ChunkJobResult.java:27)
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.RenderSectionManager.collectChunkBuildResults(RenderSectionManager.java:384)
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.RenderSectionManager.uploadChunks(RenderSectionManager.java:294)
	at knot//net.caffeinemc.mods.sodium.client.render.SodiumWorldRenderer.setupTerrain(SodiumWorldRenderer.java:241)
	at knot//net.minecraft.class_761.method_3273(class_761.java:7697)
	at knot//net.minecraft.class_761.method_22710(class_761.java:482)
	at knot//net.minecraft.class_757.method_3188(class_757.java:731)
	at knot//net.minecraft.class_757.method_3192(class_757.java:491)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1352)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'int net.caffeinemc.mods.sodium.client.render.frapi.helper.ColorHelper.multiplyRGB(int, float)'
	at knot//net.irisshaders.iris.vertices.sodium.terrain.XHFPTerrainVertex.write(XHFPTerrainVertex.java:153)
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.vertex.builder.ChunkMeshBufferBuilder.push(ChunkMeshBufferBuilder.java:43)
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderer.bufferQuad(BlockRenderer.java:207)
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderer.processQuad(BlockRenderer.java:140)
	at knot//net.caffeinemc.mods.sodium.client.render.frapi.render.AbstractBlockRenderContext.bufferDefaultModel(AbstractBlockRenderContext.java:234)
	at knot//net.minecraft.class_1087.emitBlockQuads(class_1087.java:1021)
	at knot//net.minecraft.class_1097.emitBlockQuads(class_1097.java:570)
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderer.renderModel(BlockRenderer.java:105)
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:116)
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:52)
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:45)
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:220)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.executor.ChunkJobResult.unwrap(ChunkJobResult.java:27)
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.RenderSectionManager.collectChunkBuildResults(RenderSectionManager.java:384)
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.RenderSectionManager.uploadChunks(RenderSectionManager.java:294)
	at knot//net.caffeinemc.mods.sodium.client.render.SodiumWorldRenderer.setupTerrain(SodiumWorldRenderer.java:241)
	at knot//net.minecraft.class_761.method_3273(class_761.java:7697)
	at knot//net.minecraft.class_761.method_22710(class_761.java:482)
	at knot//net.minecraft.class_757.method_3188(class_757.java:731)

-- Uptime --
Details:
	JVM uptime: 24.938s
	Wall uptime: 17.444s
	High-res time: 16.580s
	Client ticks: 219 ticks / 10.950s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2443)
	at knot//net.minecraft.class_310.method_54580(class_310.java:1002)
	at knot//net.minecraft.class_310.method_1514(class_310.java:957)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['TheWhiteDog9487'/68, l='ClientLevel', x=-5.52, y=66.00, z=-4.29]]
	Chunk stats: 961, 224
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,64,0), Section: (at 0,0,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 557 game time, 557 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 87

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, sodium

-- System Details --
Details:
	Minecraft Version: 1.21.3
	Minecraft Version ID: 1.21.3
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.4, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 216862160 bytes (206 MiB) / 671088640 bytes (640 MiB) up to 5435817984 bytes (5184 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5500                               
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 8192.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6590
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 22162.49
	Virtual memory used (MiB): 17299.97
	Swap memory total (MiB): 5888.00
	Swap memory used (MiB): 344.32
	Space in storage for jna.tmpdir (MiB): available: 85945.52, total: 307202.97
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 85945.52, total: 307202.97
	Space in storage for io.netty.native.workdir (MiB): available: 85945.52, total: 307202.97
	Space in storage for java.io.tmpdir (MiB): available: 88537.06, total: 238458.00
	Space in storage for workdir (MiB): available: 85945.52, total: 307202.97
	JVM Flags: 11 total; -Xmx5162m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		fabric-api: Fabric API 0.108.0+1.21.3
			fabric-api-base: Fabric API Base 0.4.49+fd37071f40
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.80+fd37071f40
			fabric-biome-api-v1: Fabric Biome API (v1) 14.0.6+fd37071f40
			fabric-block-api-v1: Fabric Block API (v1) 1.0.28+fd37071f40
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.16+fd37071f40
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.3+fd37071f40
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.23+fd37071f40
			fabric-command-api-v1: Fabric Command API (v1) 1.2.57+f71b366f40
			fabric-command-api-v2: Fabric Command API (v2) 2.2.36+fd37071f40
			fabric-commands-v0: Fabric Commands (v0) 0.2.74+df3654b340
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.7+fd37071f40
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.2+7f945d5b40
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.2+84ebbb0e40
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.3+fd37071f40
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.3.0+e9d2cfc840
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 21.0.16+fd37071f40
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.7+fd37071f40
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.7+825023f840
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 2.0.11+c2c3ac4740
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.59+fd37071f40
			fabric-item-api-v1: Fabric Item API (v1) 11.1.6+fd37071f40
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.16+fd37071f40
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.53+fd37071f40
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.51+df3654b340
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.0+6da5ef6940
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.25+3f89f5a540
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.13+fd37071f40
			fabric-message-api-v1: Fabric Message API (v1) 6.0.20+fd37071f40
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 3.0.8+fd37071f40
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.4+fd37071f40
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 17.0.8+fd37071f40
			fabric-particles-v1: Fabric Particles (v1) 4.0.9+fd37071f40
			fabric-recipe-api-v1: Fabric Recipe API (v1) 7.0.3+fd37071f40
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.1+fd37071f40
			fabric-renderer-api-v1: Fabric Renderer API (v1) 4.0.4+fd37071f40
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.9.4+fd37071f40
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.54+73761d2e40
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.14+fd37071f40
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.82+df3654b340
			fabric-rendering-v1: Fabric Rendering (v1) 8.0.6+fd37071f40
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.8+fd37071f40
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.6+fd37071f40
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.33+fd37071f40
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.99+fd37071f40
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.29+fd37071f40
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.2+fd37071f40
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.8+fd37071f40
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		iris: Iris 1.8.0-beta.8+mc1.21.3
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21.3
		sodium: Sodium 0.6.0-beta.5+mc1.21.3
	Loaded Shaderpack: Pegasus 2024-11-10.zip
		Profile: Normal (+1 option changed by user)
	Launched Version: 1.21.3 Fabric
	Launcher name: HMCL
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 565.90, NVIDIA Corporation
	Window size: 854x480
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, sodium
	Current Language: zh_cn
	Locale: zh_CN
	System encoding: GBK
	File encoding: GB18030
	CPU: 12x AMD Ryzen 5 5500 
	Server Running: true
	Player Count: 1 / 8; [class_3222['TheWhiteDog9487'/68, l='ServerLevel[鏂扮殑涓栫晫]', x=-5.52, y=66.00, z=-4.29]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2
	Available Data Packs: fabric, fabric-convention-tags-v2, minecart_improvements, redstone_experiments, trade_rebalance, vanilla, winter_drop
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -7049882579638618564
	Suppressed Exceptions: ~~NONE~~
```

### Additional context

[minecraft-exported-crash-info-2024-11-15T11-03-43.zip](https://github.com/user-attachments/files/17762306/minecraft-exported-crash-info-2024-11-15T11-03-43.zip)

I can use this shader normally when using the following environment, and the game will not crash.
- iris-fabric-1.8.0-beta.8+mc1.21.1.jar
- sodium-fabric-0.6.0-beta.2+mc1.21.1.jar
- Fabric Loader 0.16.9
- Minecraft 1.21

**Comment by BlueGradientHorizon** [comment]
I've also experienced that exception, seems like Iris hasn't yet synced the codebase to the latest Sodium beta release. It has probably started to happen since [this particular commit](https://github.com/CaffeineMC/sodium/commit/16f612df2005b13555e6274019515ccd18b8a556).

Edit: it may be potentially fixed in [this build](https://github.com/IrisShaders/Iris/actions/runs/11851258786).

**Comment by TheWhiteDog9487** [comment]
> I've also experienced that exception, seems like Iris hasn't yet synced the codebase to the latest Sodium beta release. It has probably started to happen since [this particular commit](https://github.com/CaffeineMC/sodium/commit/16f612df2005b13555e6274019515ccd18b8a556).
> 
> Edit: it may be potentially fixed in [this build](https://github.com/IrisShaders/Iris/actions/runs/11851258786).

This worked for me, thanks for the reminder!

**Comment by IMS212** [comment]
fixed in beta 9, releasing soonTM
