### ISSUE TITLE
Compatibility Error

### ISSUE THREAD

**Issue by xbxct** [IrisShaders/Iris#2533]
### What happened?

When the shaders are launched, the screen turns black and crashes occur. 

### Log output

---- Minecraft Crash Report ----
// Oops.

Time: 2024-11-17 13:27:32
Description: Unexpected error

java.lang.NoClassDefFoundError: Could not initialize class net.caffeinemc.mods.sodium.client.render.immediate.CloudRenderer
	at net.minecraft.class_761.handler$cei000$sodium$renderClouds(class_761.java:12179)
	at net.minecraft.class_761.method_3259(class_761.java:1812)
	at net.minecraft.class_761.method_22710(class_761.java:1260)
	at net.minecraft.class_757.method_3188(class_757.java:1087)
	at net.minecraft.class_757.method_3192(class_757.java:850)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:557)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException: Mixin transformation of net.caffeinemc.mods.sodium.client.render.immediate.CloudRenderer$CloudFace failed [in thread "Worker-ResourceReload-3"]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:504)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:302)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:190)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:176)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.caffeinemc.mods.sodium.client.render.immediate.CloudRenderer.<clinit>(CloudRenderer.java:300)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at org.quiltmc.loader.impl.launch.knot.MixinServiceKnot.findClass(MixinServiceKnot.java:113)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.audit(MixinProcessor.java:254)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.audit(MixinTransformer.java:171)
	at org.spongepowered.asm.mixin.MixinEnvironment.audit(MixinEnvironment.java:1677)
	at org.embeddedt.modernfix.util.ClassInfoManager.doClear(ClassInfoManager.java:70)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

### Minecraft Version

1.21.1 

### Iris Version

Latest

### Operating System

W10

### What is your GPU?

Integrated

**Comment by xbxct** [comment]
Looks like a problem with clouds

**Comment by Poopooracoocoo** [comment]
Can you share the full crash report? And can you share the latest.log too? Share both as files please

**Comment by xbxct** [comment]
[latestlog.txt](https://github.com/user-attachments/files/17818039/latestlog.txt)
[crash-2024-11-19_19.06.00-client.txt](https://github.com/user-attachments/files/17818046/crash-2024-11-19_19.06.00-client.txt)

**Comment by xbxct** [comment]
https://github.com/user-attachments/assets/7118fdd2-ae23-4838-afef-0abe7e73efaa

**Comment by Luracasmus** [comment]
This seems to have been a known issue in [Simply No Shading 7.6.1](https://modrinth.com/mod/simply-no-shading) which has been fixed in more recent versions
