### ISSUE TITLE
Crashin upon launching a world

### ISSUE THREAD

**Issue by elMango7** [IrisShaders/Iris#2550]
### Minecraft Version

1.21

### Iris Version

iris-fabric-1.8.0+mc1.21.1

### Sodium Version

sodium-fabric-0.6.1+mc1.21.1

### Operating System

Windows 11

### What is your GPU?

RTX 4060 Ti

### Java Version

Java 23

### Reproduction Steps

1. Launched the game without a problem
2. Start a world, loads in without a problem
3. Goes to 100% quickly then says "Loading..."
4. A real quick "Saving world..." then crash

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-12-03 02:13:14
Description: Unexpected error

java.lang.RuntimeException: Mixin transformation of net.caffeinemc.mods.sodium.client.render.immediate.CloudRenderer failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at knot//net.minecraft.class_761.handler$cni000$sodium$renderClouds(class_761.java:14184)
	at knot//net.minecraft.class_761.method_3259(class_761.java:1812)
	at knot//net.minecraft.class_761.method_22710(class_761.java:1260)
	at knot//net.minecraft.class_757.method_3188(class_757.java:1087)
	at knot//net.minecraft.class_757.method_3192(class_757.java:850)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1285)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 15 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.iris.compat.sodium.json:MixinCloudRenderer from mod iris] from phase [DEFAULT] in config [mixins.iris.compat.sodium.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 18 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field cachedGeometry was not located in the target class net.caffeinemc.mods.sodium.client.render.immediate.CloudRenderer. Using refmap iris.refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1292)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:203)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 18 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at knot//net.minecraft.class_761.handler$cni000$sodium$renderClouds(class_761.java:14184)
	at knot//net.minecraft.class_761.method_3259(class_761.java:1812)
	at knot//net.minecraft.class_761.method_22710(class_761.java:1260)
	at knot//net.minecraft.class_757.method_3188(class_757.java:1087)

-- Uptime --
Details:
	JVM uptime: 30.066s
	Wall uptime: 18.569s
	High-res time: 15.115s
	Client ticks: 155 ticks / 7.750s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2501)
	at knot//net.minecraft.class_310.method_54580(class_310.java:949)
	at knot//net.minecraft.class_310.method_1514(class_310.java:905)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['elMango_'/1, l='ClientLevel', x=-529.11, y=330.41, z=1199.00]]
	Chunk stats: 5041, 1228
	Level dimension: minecraft:overworld
	Level spawn location: World: (-672,4,453), Section: (at 0,4,5 in -42,0,28; chunk contains blocks -672,-64,448 to -657,319,463), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,-64,0 to -513,319,511)
	Level time: 4531100 game time, 961 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 1

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/Dot Crosshair.zip, file/Low Fire.zip, file/Fancy, GUI Overhaul v0.1.2.8.zip, fabric, ambientsounds, axiom, camerautils, cloth-config, continuity, creativecore, distanthorizons, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fallingleaves, flashback, flow, forgeconfigapiport, freecam, ftblibrary, ftbultimine, iris, jade, jei, leahs-immersive-thunder, litematica, malilib, modmenu, mru, noisium, orthocamera, shulkerboxtooltip, smoothscroll, sodium, sound_physics_remastered, sounds, tectonic, vivecraft, worldedit, yet_another_config_lib_v3, file/+§bBetterGlint-Jade§8-[v1.5].zip

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 856936736 bytes (817 MiB) / 1811939328 bytes (1728 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: Rocket Lake
	Frequency (GHz): 3.91
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 4060 Ti
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 8188.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6094
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MiB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MiB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MiB): 34713.61
	Virtual memory used (MiB): 14475.23
	Swap memory total (MiB): 2048.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): available: 154343.80, total: 457087.31
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 154343.80, total: 457087.31
	Space in storage for io.netty.native.workdir (MiB): available: 154343.80, total: 457087.31
	Space in storage for java.io.tmpdir (MiB): available: 154343.80, total: 457087.31
	Space in storage for workdir (MiB): available: 154343.80, total: 457087.31
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ambientsounds: AmbientSounds 6.0.5
		architectury: Architectury 13.0.8
		axiom: Axiom 4.3.3
			com_moulberry_axiomclientapi: axiomclientapi 1.0.0
			com_moulberry_mixinconstraints: mixinconstraints 1.0.1
		camerautils: Camera Utils 1.21-1.0.14
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.5+1.21
		creativecore: CreativeCore 2.12.9
			net_neoforged_bus: bus 7.2.0
		distanthorizons: Distant Horizons 2.2.1-a
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b559734490
		fabric-api: Fabric API 0.102.0+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae06d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df360d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+a551f7a4d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209bd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49cd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49cd1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
		fabricloader: Fabric Loader 0.16.9
		fallingleaves: Falling Leaves 1.16.4
		flashback: Flashback 0.13.0
			mixinsquared: MixinSquared 0.2.0-beta.6
		flow: Flow 2.2.0+1.21
			yet_another_config_lib_v3: YetAnotherConfigLib 3.6.1+1.21-fabric
				com_twelvemonkeys_common_common-image: common-image 3.10.0
				com_twelvemonkeys_common_common-io: common-io 3.10.0
				com_twelvemonkeys_common_common-lang: common-lang 3.10.0
				com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
				com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
				com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
				org_quiltmc_parsers_gson: gson 0.2.1
				org_quiltmc_parsers_json: json 0.2.1
		forgeconfigapiport: Forge Config API Port 21.0.8
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		freecam: Freecam 1.3.0-beta1+mc1.21
		ftblibrary: FTB Library 2100.1.4
		ftbultimine: FTB Ultimine 2100.1.0
		iris: Iris 1.8.0+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		jade: Jade 15.1.4+fabric
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 19.21.0.247
		leahs-immersive-thunder: Immersive Thunder 1.21+1.2.2
		litematica: Litematica 0.19.2-alpha.1
		malilib: MaLiLib 0.20.2
		minecraft: Minecraft 1.21
		modmenu: Mod Menu 11.0.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		mousetweaks: Mouse Tweaks 2.26
		mru: Mineblock's Repeated Utilities 1.0.4+1.21+fabric
		noisium: Noisium 2.3.0+mc1.21-1.21.1
		orthocamera: OrthoCamera 0.1.8+1.21
		pickupnotifier: Pick Up Notifier 21.0.0
		puzzleslib: Puzzles Lib 21.0.28
		shulkerboxtooltip: Shulker Box Tooltip 5.0.4+1.21
		smoothscroll: Smooth Scroll 2.2.1
		sodium: Sodium 0.6.1+mc1.21.1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
		sound_physics_remastered: Sound Physics Remastered 1.21.1-1.4.6
		sounds: Sounds 2.2.1+1.21+fabric
			mixinextras: MixinExtras 0.5.0-beta.2
		tectonic: Tectonic 2.4.0
		tia: Tiny Item Animations 1.2.1
		vivecraft: Vivecraft 1.21-1.1.11-b3
			org_lwjgl_lwjgl-openvr: lwjgl-openvr 3.3.3
			org_lwjgl_lwjgl-openvr_natives-linux: lwjgl-openvr 3.3.3
			org_lwjgl_lwjgl-openvr_natives-macos: lwjgl-openvr 3.3.3
			org_lwjgl_lwjgl-openvr_natives-windows: lwjgl-openvr 3.3.3
		worldedit: WorldEdit 7.3.5+6880-8ba3d89
	Loaded Shaderpack: (off) (fallback)
	Launched Version: fabric-loader-0.16.9-1.21
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce RTX 4060 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 560.94, NVIDIA Corporation
	Window size: 3440x1440
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 32/32 chunks
	Resource Packs: vanilla, file/Dot Crosshair.zip, file/Low Fire.zip, file/Fancy, GUI Overhaul v0.1.2.8.zip (incompatible), fabric, ambientsounds, axiom, camerautils, cloth-config, continuity, creativecore, distanthorizons (incompatible), fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fallingleaves, flashback, flow, forgeconfigapiport, freecam, ftblibrary, ftbultimine, iris, jade (incompatible), jei (incompatible), leahs-immersive-thunder, litematica, malilib, modmenu, mru (incompatible), noisium, orthocamera, shulkerboxtooltip, smoothscroll, sodium, sound_physics_remastered, sounds, tectonic, vivecraft, worldedit (incompatible), yet_another_config_lib_v3 (incompatible), file/+§bBetterGlint-Jade§8-[v1.5].zip (incompatible)
	Current Language: en_us
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 12x 11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['elMango_'/1, l='ServerLevel[build_Tree Repository]', x=-529.11, y=330.41, z=1199.00]]
	Active Data Packs: vanilla, file/bukkit (incompatible), fabric, axiom, fabric-convention-tags-v2, ftbultimine, sounds (incompatible), vivecraft, tectonic (incompatible)
	Available Data Packs: vanilla, trade_rebalance, bundle, file/bukkit (incompatible), fabric, axiom, fabric-convention-tags-v2, ftbultimine, sounds (incompatible), vivecraft, tectonic (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	World Seed: 5059387027944085580
```

### Additional context

I've tried with just Iris and Sodium alone and I've tried with every mod I use, but the results stay the same.

**Comment by UberMcTuber** [comment]
same problem here

**Comment by BillCipher345** [comment]
Same, thats bcs sodium 0.6.1 is incompatible with iris 1.8.0, only 1.8.1, and 1.8.1 is not made for 1.21 only 1.21.3

**Comment by Seggan** [comment]
Can confirm

**Comment by Seggan** [comment]
Same here, using Iris 1.8 instead of 1.8.1 works

**Comment by moritzgrede** [comment]
I had the same issue using the same version of Iris you have. I tried going backwards with the Sodium versions. In version `sodium-fabric-0.6.0+mc1.21.1` the issue is gone.  In all later versions I have the same issue.
