### ISSUE TITLE
Crash on MacOS using any shader

### ISSUE THREAD

**Issue by Xpl0itU** [IrisShaders/Iris#2572]
### Minecraft Version

Minecraft 1.21.4

### Iris Version

iris-fabric-1.8.4+mc1.21.4.jar

### Sodium Version

sodium-fabric-0.6.5+mc1.21.4.jar

### Operating System

macOS 15.1

### What is your GPU?

Apple M1 Pro

### Java Version

Java 17

### Reproduction Steps

1. Add any shader pack
2. Try to go to settings
3. Only a screen with a "Back" button appears
4. Load a world
5. Iris error appears
6. Try to copy the log
7. Crash

**Video**
https://github.com/user-attachments/assets/d93dbe88-c14f-415a-990a-f8c7ac631ca9

### Crash Report file and latest.log

```shell

```

### Additional context

[2024-12-18-2.log.gz](https://github.com/user-attachments/files/18185587/2024-12-18-2.log.gz)
[latest.log](https://github.com/user-attachments/files/18185586/latest.log)

**Comment by jbritain** [comment]
Most shaderpacks are not supported on MacOS due to OpenGL being deprecated.

**Comment by mv-stns** [comment]
Stick to complementary shaders. they seem to "work" somewhat. Having big issues lately tho on macOS with whatever this is...![Image](https://github.com/user-attachments/assets/140d05e8-cab3-4b6d-b4e0-78e64daf812d)

**Comment by mv-stns** [comment]
Current Mod list:
```bash
───────┬───────────────────────────────────────────────────────────────
       │ mods
───────┼───────────────────────────────────────────────────────────────
   1   │ appleskin-fabric-mc1.21.3-3.0.6.jar
   2   │ architectury-14.0.4-fabric.jar
   3   │ Axiom-4.3.3-for-MC1.21.3.jar
   4   │ BetterF3-12.0.0-Fabric-1.21.3.jar
   5   │ bobby-5.2.5+mc1.21.2.jar
   6   │ c2me-fabric-mc1.21.3-0.3.1+alpha.0.25.jar
   7   │ carpet-tis-addition-v1.65.0-mc1.21.3.jar
   8   │ cloth-config-16.0.141-fabric.jar
   9   │ entity_model_features_fabric_1.21.3-2.4.1.jar
  10   │ entity_texture_features_fabric_1.21.3-6.2.9.jar
  11   │ entityculling-fabric-1.7.1-mc1.21.3.jar
  12   │ EuphoriaPatcher-1.4.3-r5.3-fabric.jar
  13   │ fabric-api-0.114.0+1.21.3.jar
  14   │ fabric-carpet-1.21.2-1.4.158+v241022.jar
  15   │ fabric-language-kotlin-1.13.0+kotlin.2.1.0.jar
  16   │ ferritecore-7.1.0-hotfix-fabric.jar
  17   │ ImmediatelyFast-Fabric-1.3.2+1.21.3.jar
  18   │ InventoryProfilesNext-fabric-1.21.3-2.1.0.jar
  19   │ iris-fabric-1.8.1+mc1.21.3.jar
  20   │ itemswapper-fabric-0.7.4-mc1.21.3.jar
  21   │ Jade-1.21.3-Fabric-16.0.4.jar
  22   │ language-reload-1.7.2+1.21.3.jar
  23   │ libIPN-fabric-1.21.3-6.2.0.jar
  24   │ litematica-fabric-1.21.3-0.20.3.jar
  25   │ lithium-fabric-0.14.2-snapshot+mc1.21.3-build.91.jar
  26   │ malilib-fabric-1.21.3-0.22.4.jar
  27   │ modmenu-12.0.0-beta.1.jar
  28   │ moreculling-fabric-1.21.3-1.1.0.jar
  29   │ NoChatReports-FABRIC-1.21.3-v2.10.1.jar
  30   │ OptiFine_1.21.3_HD_U_J2.jar
  31   │ peek-fabric-1.21.3-1.3.6.jar
  32   │ placeholder-api-2.5.1+1.21.3.jar
  33   │ reeses-sodium-options-fabric-1.8.0+mc1.21.3.jar
  34   │ 'Resourcify (1.21.3-4-fabric)-1.6.0.jar'
  35   │ RoughlyEnoughItems-17.0.794-fabric.jar
  36   │ sodium-extra-fabric-0.6.0+mc1.21.3.jar
  37   │ sodium-fabric-0.6.5+mc1.21.3.jar
  38   │ threadtweak-fabric-0.1.5+mc1.21.3.jar
  39   │ trade-cycling-fabric-1.21.3-1.0.15.jar
  40   │ tweakeroo-fabric-1.21.3-0.22.3.jar
  41   │ vmp-fabric-mc1.21.3-0.2.0+beta.7.180-all.jar
  42   │ WorldEditCUI-1.21.3+01-SNAPSHOT.jar
  43   │ Xaeros_Minimap_24.6.2_Fabric_1.21.3.jar
  44   │ XaerosWorldMap_1.39.1_Fabric_1.21.3.jar
  45   │ yosbr-0.1.2.jar
───────┴───────────────────────────────────────────────────────────────
```

**Comment by Rvhoyos** [comment]
im having similar issue on a Mac Studio M4 Max macOS Tahoe 26.2, Java 25

>**(mc 1.21.8, neoforge 21.8.47)**

- **Failing** while loading **ANY** shader pack and the app then **instantly crashes**.

### Logs

```bash
	at cpw.mods.bootstraplauncher/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:203) [bootstraplauncher-9.0.18.jar:?]
	at cpw.mods.bootstraplauncher/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:62) [bootstraplauncher-9.0.18.jar:?]
[09Feb2026 12:21:52.783] [Render thread/INFO][net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] Iris encountered an issue trying to load the shader; please report this to Iris developers. Copy Info
[09Feb2026 12:21:52.783] [Render thread/WARN][Iris/]: Falling back to normal rendering without shaders because the shaderpack could not be loaded
[09Feb2026 12:21:53.414] [Render thread/ERROR][net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Rendering screen
	at TRANSFORMER/minecraft@1.21.8/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:529) ~[client-1.21.8-20250717.133445-srg.jar%23212!/:?]
	at TRANSFORMER/minecraft@1.21.8/net.minecraft.client.Minecraft.runTick(Minecraft.java:1285) ~[client-1.21.8-20250717.133445-srg.jar%23212!/:?]
	at TRANSFORMER/minecraft@1.21.8/net.minecraft.client.Minecraft.run(Minecraft.java:882) ~[client-1.21.8-20250717.133445-srg.jar%23212!/:?]
	at TRANSFORMER/minecraft@1.21.8/net.minecraft.client.main.Main.main(Main.java:243) ~[client-1.21.8-20250717.133445-srg.jar%23212!/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@9.0.18/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:132) ~[loader-9.0.18.jar%23109!/:9.0]
	at MC-BOOTSTRAP/fml_loader@9.0.18/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:120) ~[loader-9.0.18.jar%23109!/:9.0]
	at MC-BOOTSTRAP/fml_loader@9.0.18/net.neoforged.fml.loading.targets.NeoForgeClientLaunchHandler.runService(NeoForgeClientLaunchHandler.java:41) ~[loader-9.0.18.jar%23109!/:9.0]
	at MC-BOOTSTRAP/fml_loader@9.0.18/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:114) ~[loader-9.0.18.jar%23109!/:9.0]
	at MC-BOOTSTRAP/fml_loader@9.0.18/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:25) [loader-9.0.18.jar%23109!/:9.0]
	at MC-BOOTSTRAP/fml_loader@9.0.18/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:55) [loader-9.0.18.jar%23109!/:9.0]
	at MC-BOOTSTRAP/fml_loader@9.0.18/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:73) [loader-9.0.18.jar%23109!/:9.0]
	at MC-BOOTSTRAP/fml_loader@9.0.18/cpw.mods.modlauncher.Launcher.run(Launcher.java:104) [loader-9.0.18.jar%23109!/:9.0]
	at MC-BOOTSTRAP/fml_loader@9.0.18/cpw.mods.modlauncher.Launcher.main(Launcher.java:75) [loader-9.0.18.jar%23109!/:9.0]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at cpw.mods.bootstraplauncher/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:203) [bootstraplauncher-9.0.18.jar:?]
	at cpw.mods.bootstraplauncher/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:62) [bootstraplauncher-9.0.18.jar:?]
Caused by: java.lang.IllegalStateException: Can only blur once per frame
	at TRANSFORMER/minecraft@1.21.8/net.minecraft.client.gui.render.state.GuiRenderState.blurBeforeThisStratum(GuiRenderState.java:37) ~[client-1.21.8-20250717.133445-srg.jar%23212!/:?]
	at TRANSFORMER/minecraft@1.21.8/net.minecraft.client.gui.GuiGraphics.blurBeforeThisStratum(GuiGraphics.java:110) ~[client-1.21.8-20250717.133445-srg.jar%23212!/:?]
	at TRANSFORMER/minecraft@1.21.8/net.minecraft.client.gui.screens.Screen.renderBlurredBackground(Screen.java:408) ~[client-1.21.8-20250717.133445-srg.jar%23212!/:?]
	at TRANSFORMER/minecraft@1.21.8/net.minecraft.client.gui.screens.Screen.renderBackground(Screen.java:401) ~[client-1.21.8-20250717.133445-srg.jar%23212!/:?]
	at TRANSFORMER/iris@1.9.6+mc1.21.8/net.irisshaders.iris.gui.FeatureMissingErrorScreen.render(FeatureMissingErrorScreen.java:30) ~[iris-neoforge-1.9.6+mc1.21.8.jar%23216!/:?]
	at TRANSFORMER/minecraft@1.21.8/net.minecraft.client.gui.screens.Screen.renderWithTooltip(Screen.java:112) ~[client-1.21.8-20250717.133445-srg.jar%23212!/:?]
	at TRANSFORMER/neoforge@21.8.47/net.neoforged.neoforge.client.ClientHooks.drawScreenInternal(ClientHooks.java:409) ~[neoforge-21.8.47-universal.jar%23213!/:?]
	at TRANSFORMER/neoforge@21.8.47/net.neoforged.neoforge.client.ClientHooks.drawScreen(ClientHooks.java:404) ~[neoforge-21.8.47-universal.jar%23213!/:?]
	at TRANSFORMER/minecraft@1.21.8/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:523) ~[client-1.21.8-20250717.133445-srg.jar%23212!/:?]
	... 18 more
[09Feb2026 12:21:53.563] [Render thread/INFO][xaero.hud.minimap.MinimapLogs/]: Xaero hud session finalized.
[09Feb2026 12:21:53.565] [Sound engine/ERROR][com.mojang.blaze3d.audio.OpenAlUtil/]: Stop: Invalid name parameter.
[09Feb2026 12:21:53.570] [Render thread/INFO][ChunkBuilder/]: Stopping worker threads
[09Feb2026 12:21:53.652] [Render thread/FATAL][net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID 8fd6df2b-a102-4a45-bcf1-e6c70b994c60
[09Feb2026 12:21:53.653] [Render thread/FATAL][net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID 8f65ca46-647f-4abf-8c00-ae36fb407e09
```

**Comment by Rvhoyos** [comment]
> Most shaderpacks are not supported on MacOS due to OpenGL being deprecated.

Will this ever be addressed?

**Comment by jbritain** [comment]
Ask Apple. The answer will be no.

**Comment by JesusChapman** [comment]
Same in MacOS Tahoe 26

**Comment by Rvhoyos** [comment]
@JesusChapman new MC versions 26.x dont have this issue. Thats when MC dropped OpenGL from their graphics API, which happens the be the cause of all this for Mac users.

There are some (slowly) moving projects trying to address this, one of them is this one https://github.com/openglonmetal/MGL but you are really better off playing on newer MC versions.
