### ISSUE TITLE
Game crashes on Complementary 4.0 pre1

### ISSUE THREAD

**Issue by Justsnoopy30** [IrisShaders/Iris#275]
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 8
	at net.coderbot.iris.shaderpack.PackDirectives.lambda$accept$1(PackDirectives.java:79)
	at java.base/java.util.OptionalInt.ifPresent(OptionalInt.java:165)
	at net.coderbot.iris.shaderpack.PackDirectives.accept(PackDirectives.java:78)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at net.coderbot.iris.shaderpack.ProgramSet.lambda$locateDirectives$0(ProgramSet.java:198)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.coderbot.iris.shaderpack.ProgramSet.locateDirectives(ProgramSet.java:198)
	at net.coderbot.iris.shaderpack.ProgramSet.<init>(ProgramSet.java:83)
	at net.coderbot.iris.shaderpack.ShaderPack.<init>(ShaderPack.java:48)
	at net.coderbot.iris.Iris.loadExternalShaderpack(Iris.java:231)
	at net.coderbot.iris.Iris.loadShaderpack(Iris.java:162)
	at net.coderbot.iris.Iris.onInitializeClient(Iris.java:85)```

**Comment by coderbot16** [comment]
The crash here has been fixed, though of course the extra color buffers are still not supported: https://github.com/IrisShaders/Iris/issues/280
