### ISSUE TITLE
Crash when reloading a shader that uses DOF (centerDepthSmooth)

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#283]
```
java.lang.IllegalStateException: Tried to use a destroyed GlResource 	at net.coderbot.iris.gl.GlResource.assertValid(GlResource.java:21) 	at net.coderbot.iris.gl.GlResource.getGlId(GlResource.java:26) 	at net.coderbot.iris.gl.framebuffer.GlFramebuffer.bind(GlFramebuffer.java:55) 	at net.coderbot.iris.postprocess.CenterDepthSampler.sampleCenterDepth(CenterDepthSampler.java:34) 	at net.coderbot.iris.uniforms.transforms.SmoothedFloat.update(SmoothedFloat.java:86) 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) 	at net.coderbot.iris.uniforms.FrameUpdateNotifier.onNewFrame(FrameUpdateNotifier.java:21) 	at net.minecraft.class_761.handler$zfo000$iris$beginWorldRender(class_761.java:5134) 	at net.minecraft.class_761.method_22710(class_761.java) 	at net.minecraft.class_757.method_3188(class_757.java:727) 	at net.minecraft.class_757.method_3192(class_757.java:546) 	at net.minecraft.class_310.method_1523(class_310.java:1048) 	at net.minecraft.class_310.method_1514(class_310.java:681) 	at net.minecraft.client.main.Main.main(Main.java:215) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.base/java.lang.reflect.Method.invoke(Method.java:566) 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
```

**Comment by coderbot16** [comment]
This looks to be caused by the fact that Iris doesn't reset the FrameUpdateNotifier on shader reloads.
