### ISSUE TITLE
Cannot open iris sodium gui

### ISSUE THREAD

**Issue by Canary233** [IrisShaders/Iris#303]
---- Minecraft Crash Report ----
// Don't do that.

Time: 2021/5/30 下午12:29
Description: Rendering screen

java.lang.NoSuchMethodError: 'void me.flashyreese.mods.reeses_sodium_options.client.gui.frame.OptionPageScrollFrame.drawRect(int, int, int, int, int)'
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.OptionPageScrollFrame.renderOptionTooltip(OptionPageScrollFrame.java:137)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.OptionPageScrollFrame.method_25394(OptionPageScrollFrame.java:99)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.AbstractFrame.method_25394(AbstractFrame.java:69)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.AbstractFrame.method_25394(AbstractFrame.java:69)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.BasicFrame.method_25394(BasicFrame.java:39)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.SodiumVideoOptionsScreen.method_25394(SodiumVideoOptionsScreen.java:78)
	at net.minecraft.class_757.method_3192(class_757.java:616)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.OptionPageScrollFrame.renderOptionTooltip(OptionPageScrollFrame.java:137)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.OptionPageScrollFrame.method_25394(OptionPageScrollFrame.java:99)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.AbstractFrame.method_25394(AbstractFrame.java:69)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.AbstractFrame.method_25394(AbstractFrame.java:69)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.BasicFrame.method_25394(BasicFrame.java:39)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.SodiumVideoOptionsScreen.method_25394(SodiumVideoOptionsScreen.java:78)

-- Screen render details --
Details:
	Screen name: me.flashyreese.mods.reeses_sodium_options.client.gui.SodiumVideoOptionsScreen
	Mouse location: Scaled: (190, 163). Absolute: (762.000000, 654.000000)
	Screen size: Scaled: (480, 257). Absolute: (1920, 1027). Scale factor of 4.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['Coolluyan'/435, l='ClientLevel', x=-179.66, y=65.00, z=-184.98]]
	Chunk stats: Client Chunk Cache: 1024, 515
	Level dimension: minecraft:overworld
	Level spawn location: World: (-256,70,-184), Chunk: (at 0,4,8 in -16,-12; contains blocks -256,0,-192 to -241,255,-177), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 117109 game time, 1274596 day time
	Server brand: Akarin
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by Canary233** [comment]
the bug comes from sodium-extra.
