### ISSUE TITLE
Shaders fail to compile on Mac when using Sodium

### ISSUE THREAD

**Issue by quaoz** [IrisShaders/Iris#314]
When using Iris and Sodium on Mac, Sildur's and BSL (these were the only ones I tested) don't compile with the same error, this only happens when using Sodium compiled against Iris-0.4.0 or later.

```
[20:03:00] [main/WARN]: Shader compilation log for iris:sodium-terrain.fsh: ERROR: 0:248: '' : syntax error: incorrect preprocessor directive
ERROR: 0:248: '' : syntax error: unexpected tokens following #if preprocessor directive - expected a newline

[20:03:00] [main/FATAL]: Error executing task on Client
java.lang.RuntimeException: Shader compilation failed, see log for details
	at me.jellysquid.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:39) ~[sodium-latest-trunk.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.oneshot.ChunkRenderBackendOneshot.createFragmentShader(ChunkRenderBackendOneshot.java:87) ~[sodium-latest-trunk.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.shader.ChunkRenderShaderBackend.createShader(ChunkRenderShaderBackend.java:53) ~[sodium-latest-trunk.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.shader.ChunkRenderShaderBackend.createShadersForFogMode(ChunkRenderShaderBackend.java:45) ~[sodium-latest-trunk.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.shader.ChunkRenderShaderBackend.createShaders(ChunkRenderShaderBackend.java:37) ~[sodium-latest-trunk.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.initRenderer(SodiumWorldRenderer.java:296) ~[sodium-latest-trunk.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.loadWorld(SodiumWorldRenderer.java:114) ~[sodium-latest-trunk.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.setWorld(SodiumWorldRenderer.java:105) ~[sodium-latest-trunk.jar:?]
	at net.minecraft.class_761.handler$zzk000$onWorldChanged(class_761.java:4129) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_761.method_3244(class_761.java:744) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_310.method_18097(class_310.java:2049) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_310.method_1481(class_310.java:1974) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_634.method_11120(class_634.java:382) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:110) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:18) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:103) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1015) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.5-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

[The full log](https://github.com/IrisShaders/Iris/files/6603096/2021-06-05-7.log)

**Comment by DestinyTheGreat** [comment]
This is still an issue, any shader (even internal) fails when trying to use Sodium + Iris. Using Rosetta2 allows Sildurs Enhanced Defaults to work, but not any other shader. Tested with Sildurs Vibrant, Complementary, BSL, and Skylec.
