### ISSUE TITLE
NullPointerException with shaders disabled on MacBook Pro with Intel Integrated graphics

### ISSUE THREAD

**Issue by wmakley** [IrisShaders/Iris#380]
Thank you for the amazing work on this mod. I don't expect you to fix every imaginable hardware combo, but here is a crash I am running into when trying to play with this mod without any shaders enabled on my 2016 MBP (running latest Mac OS Big Sur as of this writing), maybe it is fixable. I am happy to provide any more details, as "method_2911" looks quite useless for debugging:

The crash occurs immediately upon loading, and affects all game modes as far as I can tell. Normal Fabric+Sodium do not crash currently. Since this hardware+Apple's terrible OpenGL drivers probably can't run shaders at playable framerate it may be moot.

```
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 6/12/21 8:30 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.class_636.method_2911(class_636.java:281)
	at net.minecraft.class_636.method_2927(class_636.java:260)
	at net.minecraft.class_310.method_1574(class_310.java:1504)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_636.method_2911(class_636.java:281)
	at net.minecraft.class_636.method_2927(class_636.java:260)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: Client Chunk Cache: 1024, 441
	Level dimension: minecraft:overworld
	Level spawn location: World: (-208,66,192), Chunk: (at 0,4,0 in -13,12; contains blocks -208,0,192 to -193,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 711106810 game time, 2771466 day time
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1525510352 bytes (1454 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: iris-fabric-loader-0.11.3-1.16.5
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: Intel(R) Iris(TM) Graphics 540 GL version 2.1 INTEL-16.4.5, Intel Inc.
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	GPU Warnings: version: 2.1
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
```

**Comment by yitzy299** [comment]
Mapped:

```
-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.network.ClientPlayerInteractionManager.syncSelectedSlot(ClientPlayerInteractionManager.java:281)
	at net.minecraft.client.network.ClientPlayerInteractionManager.tick(ClientPlayerInteractionManager.java:260)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: Client Chunk Cache: 1024, 441
	Level dimension: minecraft:overworld
	Level spawn location: World: (-208,66,192), Chunk: (at 0,4,0 in -13,12; contains blocks -208,0,192 to -193,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 711106810 game time, 2771466 day time
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld.java:449)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2239)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
```

**Comment by coderbot16** [comment]
We'll need a latest.log file as well, please. I can't really point at anything that suggests that Iris is the cause from the crash, but the log might have more information.

**Comment by wmakley** [comment]
Reproduced the crash simply by starting a new game, here is the log:
[latest.log](https://github.com/IrisShaders/Iris/files/6644964/latest.log)

**Comment by DestinyTheGreat** [comment]
You are trying to use Kuda Shaders, which are not supported. Iris tries to fallback to no shader, but this is not yet implemented in Sodium, causing a crash. Either way, Kuda will not work, so try a different shaderpack.

**Comment by AlsoNiko** [comment]
Hey, it looks like you're using an unsupported shade pack, KUDA is known for crashing with iris
The currently fully supported shaders are
• Astralex
• BSL Shaders
• Complementary Shaders
• Continuum 1.3 
• Continuum 2.0.4
• PSXify
• SEUS V11
• SEUS Renewed
• Sildur's Enhanced Default
• Sildur's Vibrant Shaders
• Skylec v4.0
• Tea V1.5.3
• XorDev's shaders
Try one of those instead and see if it works!

**Comment by wmakley** [comment]
It should have been disabled. I explicitly turned off ALL
shaders. Regardless I will delete them and let you know.

On June 13, 2021, William Makley ***@***.***> wrote:
> Hey, it looks like you're using an unsupported shade pack, KUDA is
> known for crashing with iris
>  The currently fully supported shaders are
>  • Astralex
>  • BSL Shaders
>  • Complementary Shaders
>  • Continuum 1.3
>  • Continuum 2.0.4
>  • PSXify
>  • SEUS V11
>  • SEUS Renewed
>  • Sildur's Enhanced Default
>  • Sildur's Vibrant Shaders
>  • Skylec v4.0
>  • Tea V1.5.3
>  • XorDev's shaders
>  Try one of those instead and see if it works!
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/IrisShaders/Iris/issues/380#issuecomment-860314518>,
or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AAD5RDL7OANFBMINQA7QWI3TSVNIRANCNFSM46SWQRDA>.

**Comment by wmakley** [comment]
Had incompatible shader pack in shaderpacks folder.
