### ISSUE TITLE
Crashing at the end of loading

### ISSUE THREAD

**Issue by 0x346e3730** [IrisShaders/Iris#383]
Hello,

Looking into solutions for shader on fabric, I encountered Iris and tried to install it. However, the game crashes whenever I load Iris at the end of the game loading. I run Fabulously Optimized.

Here is the crash logs :

```
java.lang.NullPointerException: Rendering screen
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.9)
	at net.coderbot.iris.layer.GbufferPrograms.push(GbufferPrograms.java:8)
	at net.coderbot.iris.layer.UseProgramRenderPhase.lambda$new$0(UseProgramRenderPhase.java:11)
	at net.minecraft.client.render.RenderPhase.startDrawing(RenderPhase:32)
	at net.coderbot.iris.layer.IrisRenderLayerWrapper.startDrawing(IrisRenderLayerWrapper.java:27)
	at net.minecraft.client.render.RenderLayer.draw(RenderLayer:599)
	at net.minecraft.client.render.VertexConsumerProvider$Immediate.draw(VertexConsumerProvider:86)
	at net.minecraft.client.render.VertexConsumerProvider$Immediate.method_24213(VertexConsumerProvider:65)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraft.client.render.VertexConsumerProvider$Immediate.draw(VertexConsumerProvider:62)
	at net.minecraft.client.font.TextRenderer.draw(TextRenderer:109)
	at net.minecraft.client.font.TextRenderer.drawWithShadow(TextRenderer:58)
	at net.minecraft.client.gui.DrawableHelper.drawCenteredString(DrawableHelper:114)
	at fudge.notenoughcrashes.gui.InitErrorScreen.render(InitErrorScreen.java:44)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:616)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1048)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
	at net.minecraft.client.main.Main.main(Main:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
```

**Comment by ColdIce1605** [comment]
Not enough crashes leaves OGL in a weird state try removing it and see if you still have a problem.

**Comment by 0x346e3730** [comment]
Disabling not enough crashes fixed the crash indeed, thank you :)
