### ISSUE TITLE
Crashing with Satin API (used in dying effect in Requiem mod)

### ISSUE THREAD

**Issue by InsaanNotFound** [IrisShaders/Iris#385]
How to reproduce:
Install both newest Requiem and Iris mod versions and... literally die, A wavy slowmo effect should play, but game just insta crashes. Does not occur with just Sodium.
```
[13:14:42] [main/FATAL]: Unreported exception thrown!
java.lang.IllegalArgumentException: Unrecognized RenderLayer implementation class net.coderbot.iris.layer.IrisRenderLayerWrapper. Layer duplication is only applicable to the default (MultiPhase) implementation
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.6) ~[?:?]
	at ladysnake.satin.impl.RenderLayerDuplicator.checkDefaultImpl(RenderLayerDuplicator.java:123) ~[ab0d7f11-2d5b-4c76-b1a1-239070c9c55b.jar:?]
	at ladysnake.satin.impl.RenderLayerDuplicator.copy(RenderLayerDuplicator.java:82) ~[ab0d7f11-2d5b-4c76-b1a1-239070c9c55b.jar:?]
	at ladysnake.satin.api.util.RenderLayerHelper.copy(RenderLayerHelper.java:69) ~[ab0d7f11-2d5b-4c76-b1a1-239070c9c55b.jar:?]
	at ladysnake.requiem.client.ShadowPlayerFx.getRenderLayer(ShadowPlayerFx.java:132) ~[requiem-1.7.0.jar:?]
	at net.minecraft.client.render.entity.PlayerEntityRenderer.localvar$bbl000$requiem$replaceRenderLayer(PlayerEntityRenderer:3070) ~[?:?]
	at net.minecraft.client.render.entity.LivingEntityRenderer.render(LivingEntityRenderer:130) ~[?:?]
	at net.minecraft.client.render.entity.PlayerEntityRenderer.render(PlayerEntityRenderer:65) ~[?:?]
	at net.minecraft.client.render.entity.PlayerEntityRenderer.render(PlayerEntityRenderer:42) ~[?:?]
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:261) ~[?:?]
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer:1459) ~[?:?]
	at net.minecraft.client.render.WorldRenderer.invokeRenderEntity(WorldRenderer) ~[?:?]
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:368) ~[iris-mc1.16.5-1.0.0.jar:?]
	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.renderShadows(DeferredWorldRenderingPipeline.java:651) ~[iris-mc1.16.5-1.0.0.jar:?]
	at net.minecraft.client.render.WorldRenderer.handler$zoo000$iris$renderTerrainShadows(WorldRenderer:6652) ~[?:?]
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1149) ~[?:?]
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:727) ~[?:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:546) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1048) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:215) [intermediary-minecraft-1.16.5-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[13:14:42] [main/FATAL]: Minecraft ran into a problem! Report saved to: C:\Users\Seba\Desktop\Gry\MultiMC\instances\Technically-Retro-0.1.0\.minecraft\crash-reports\crash-2021-06-13_13.14.42-client.txt
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2021-06-13 13:14:42 CEST
Description: Rendering entity in world

java.lang.IllegalArgumentException: Unrecognized RenderLayer implementation class net.coderbot.iris.layer.IrisRenderLayerWrapper. Layer duplication is only applicable to the default (MultiPhase) implementation
    at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.6)
    at ladysnake.satin.impl.RenderLayerDuplicator.checkDefaultImpl(RenderLayerDuplicator.java:123)
    at ladysnake.satin.impl.RenderLayerDuplicator.copy(RenderLayerDuplicator.java:82)
    at ladysnake.satin.api.util.RenderLayerHelper.copy(RenderLayerHelper.java:69)
    at ladysnake.requiem.client.ShadowPlayerFx.getRenderLayer(ShadowPlayerFx.java:132)
    at net.minecraft.client.render.entity.PlayerEntityRenderer.localvar$bbl000$requiem$replaceRenderLayer(PlayerEntityRenderer:3070)
    at net.minecraft.client.render.entity.LivingEntityRenderer.render(LivingEntityRenderer:130)
    at net.minecraft.client.render.entity.PlayerEntityRenderer.render(PlayerEntityRenderer:65)
    at net.minecraft.client.render.entity.PlayerEntityRenderer.render(PlayerEntityRenderer:42)
    at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:261)
    at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer:1459)
    at net.minecraft.client.render.WorldRenderer.invokeRenderEntity(WorldRenderer)
    at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:368)
    at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.renderShadows(DeferredWorldRenderingPipeline.java:651)
    at net.minecraft.client.render.WorldRenderer.handler$zoo000$iris$renderTerrainShadows(WorldRenderer:6652)
    at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1149)
    at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:727)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:546)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1048)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
    at net.minecraft.client.main.Main.main(Main:215)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
    at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by InsaanNotFound** [comment]
It seems it happened because of a faulty .jar, after redownloading everything it works just fine
