### ISSUE TITLE
Comp doesnt work on macos

### ISSUE THREAD

**Issue by hellosway** [IrisShaders/Iris#400]
Using a macbookpro with iris 1.17 and 1.16.5. Happens with starline too. It looks is vanilla when enabled
[latest.log](https://github.com/IrisShaders/Iris/files/6672224/latest.log)

**Comment by AlsoNiko** [comment]
If we could get a few more testers/logs for this that would be helpful, it seems to work just fine on optifine, so probably a shader compile error?

**Comment by hellosway** [comment]
heres the actual error

    [10:45:21] [Render thread/ERROR]: Couldn't load NewWorldRenderingPipeline, falling back to vanilla shaders.
    java.lang.RuntimeException: Shader compilation failed!
	    at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:272) ~[iris-mc1.17-1.0.1-starline-beta1.jar:?]
	    at net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:73) ~[iris-mc1.17-1.0.1-starline-beta1.jar:?]
	    at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:164) ~[iris-mc1.17-1.0.1-starline-beta1.jar:?]
	    at net.coderbot.iris.Iris.createPipeline(Iris.java:408) [iris-mc1.17-1.0.1-starline-beta1.jar:?]
	    at net.coderbot.iris.Iris$$Lambda$2998/0x00000000661c96b0.apply(Unknown Source) [iris-mc1.17-1.0.1-starline-beta1.jar:?]
	    at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:42) [iris-mc1.17-1.0.1-starline-beta1.jar:?]
	    at net.minecraft.class_761.handler$zle000$iris$beginWorldRender(class_761.java:6292) [intermediary-minecraft-1.17-client.jar:?]
	    at net.minecraft.class_761.method_22710(class_761.java) [intermediary-minecraft-1.17-client.jar:?]
	    at net.minecraft.class_757.method_3188(class_757.java:1001) [intermediary-minecraft-1.17-client.jar:?]
	    at net.minecraft.class_757.method_3192(class_757.java:806) [intermediary-minecraft-1.17-client.jar:?]
	    at net.minecraft.class_310.method_1523(class_310.java:1114) [intermediary-minecraft-1.17-client.jar:?]
	    at net.minecraft.class_310.method_1514(class_310.java:730) [intermediary-minecraft-1.17-client.jar:?]
	    at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17-client.jar:?]
	    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	    at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	    at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
	    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	    at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	    at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	    at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
    Caused by: java.lang.RuntimeException: Failed to compile FRAGMENT shader for program composite.fsh
	    at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:90) ~[iris-mc1.17-1.0.1-starline-beta1.jar:?]
	    at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:61) ~[iris-mc1.17-1.0.1-starline-beta1.jar:?]
	    at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:269) ~[iris-mc1.17-1.0.1-starline-beta1.jar:?]
	    ... 27 more
    Caused by: java.lang.RuntimeException: Shader compilation failed, see log for details
	    at net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:44) ~[iris-mc1.17-1.0.1-starline-beta1.jar:?]
	    at net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:23) ~[iris-mc1.17-1.0.1-starline-beta1.jar:?]
	    at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:88) ~[iris-mc1.17-1.0.1-starline-beta1.jar:?]
	    at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:61) ~[iris-mc1.17-1.0.1-starline-beta1.jar:?]
	    at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:269) ~[iris-mc1.17-1.0.1-starline-beta1.jar:?]
	    ... 27 more

**Comment by yitzy299** [comment]
Same issue as #350
