### ISSUE TITLE
Heavy stuttering related to block updates + Buffer Crash

### ISSUE THREAD

**Issue by ruvaldak** [IrisShaders/Iris#465]
### What happened?

In some instances, especially extreme ones regarding block updates such as massive amounts of sugarcane growing, a bug/lack of optimization present in main Sodium causes increasingly heavy stuttering every few frames. In Iris, as this stuttering gets worse, the game will eventually crash.

### Screenshots

![unknown-2](https://user-images.githubusercontent.com/15901769/124040665-56a65400-d9d3-11eb-9a14-84187b03188e.png)

### Relevant log output

```shell
[14:02:57] [main/FATAL]: Unreported exception thrown!
java.lang.IllegalArgumentException: Not enough space in destination buffer (writeOffset + bytes > bufferSize)
    at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.9) ~[?:?]
    at me.jellysquid.mods.sodium.client.gl.device.GLRenderDevice$ImmediateCommandList.copyBufferSubData(GLRenderDevice.java:83) ~[sodium-fabric-mc1.16.5-0.2.0+IRIS3-rev.f3caed8.jar:?]
    at me.jellysquid.mods.sodium.client.gl.arena.GlBufferArena.uploadBuffer(GlBufferArena.java:62) ~[sodium-fabric-mc1.16.5-0.2.0+IRIS3-rev.f3caed8.jar:?]
    at me.jellysquid.mods.sodium.client.render.chunk.backends.multidraw.MultidrawChunkRenderBackend.upload(MultidrawChunkRenderBackend.java:144) ~[sodium-fabric-mc1.16.5-0.2.0+IRIS3-rev.f3caed8.jar:?]
    at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.updateChunks(ChunkRenderManager.java:494) ~[sodium-fabric-mc1.16.5-0.2.0+IRIS3-rev.f3caed8.jar:?]
    at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:227) ~[sodium-fabric-mc1.16.5-0.2.0+IRIS3-rev.f3caed8.jar:?]
    at net.minecraft.client.render.WorldRenderer.setupTerrain(WorldRenderer:4186) ~[?:?]
    at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1131) ~[?:?]
    at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:727) ~[?:?]
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:546) ~[?:?]
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1048) ~[?:?]
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:681) ~[?:?]
    at net.minecraft.client.main.Main.main(Main:215) [intermediary-minecraft-1.16.5-client.jar:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
    at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

### Iris and Minecraft Version

MC: 1.16.6, iris version: all

### Are you running Sodium along with Iris?

Yes

### Operating System

Arch Linux

### What is your GPU?

RTX 2080ti

### Java Version

Java 8, Java 11, Java 16

### Additional context

I am convinced the stuttering is related to the crashing, however I as of yet cannot get stock sodium to crash in the same manner as sodium+iris. Even with shaders disabled, sodium+iris will eventually crash if the stuttering goes on long enough. 

I believe that, while this only happens presently in extreme situations, the problem exists at all time and is merely brought to surface faster by extreme situations; similar to some sort of memory leak or program that isn't cleaning up properly after itself.

This issue should be linked to in sodium's GitHub issues as well, as it seems to be related to iris and sodium.

I've as of yet had no luck getting the game to crash on single player, but multiplayer seems to be quite constant in some situations, especially a sugar cane farm I've built on a Skyblock server. Thanks to a spigot plugin, I'm able to plant sugarcane without water nearby, which allows me to create a massively dense sugarcane farm which no doubt pulls a lot of shenanigans to prevent the sugar cane from exploding on block updates.

**Comment by rudensdash** [comment]
me too

**Comment by ftpopo** [comment]
Same issue for me on win10 with a gtx1650

- For me it doesn't need to be "extreme" block updates, casual mining will cause drops down to 4fps - where I exited before crash

**Comment by Kroppeb** [comment]
Is this also an issue on the one shot renderer?

**Comment by ruvaldak** [comment]
> Is this also an issue on the one shot renderer?

Yes, it is. In fact, it's much, much, much worse and crashes much faster.

**Comment by AndroidWG** [comment]
> 
> 
> Same issue for me on win10 with a gtx1650
> 
>     * For me it doesn't need to be "extreme" block updates, casual mining will cause drops down to 4fps - where I exited before crash

I opened an already generated creative world with no buildings and had massive drops just flying around on 1.17 on a GTX1650 too. The drops were from 105fps to around 4~10fps and happened continuously.

**Comment by AlsoNiko** [comment]
You're reporting this under the wrong ticket. This has been fixed in dev. Please do not use github issues for unrelated things to report issues.

**Comment by pokab** [comment]
I have successfully made a workaround for sodium 0.16.x in https://github.com/CaffeineMC/sodium-fabric/issues/740, if you're interested.

**Comment by coderbot16** [comment]
Since Iris now uses official Sodium (and has done so since 1.1.3), we probably won't be addressing this on our side now. https://github.com/CaffeineMC/sodium-fabric/issues/740 is probably the best place to continue discussing this.
