### ISSUE TITLE
Game Randomly crashes on sodium fork 

### ISSUE THREAD

**Issue by Blobanium** [IrisShaders/Iris#466]
### Iris and Minecraft Version

Iris 1.1.0+1.17

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

AMD Radeon RX 570

### Java Version

Java 16

### Reproduction Steps

1. Launch minecraft
2. get into a multiplayer game
3. Walk around for a little bit (i think you maybe have to change dimensions)
4. Game Crashes

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Why did you do that?

Time: 6/30/21, 5:27 PM
Description: Unexpected error

java.lang.IllegalStateException: Chunk is not loaded: 17592187092992
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.9)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.unloadSection(RenderSectionManager.java:331)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.processStatusChangeForSection(RenderSectionManager.java:203)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.processStatusChanges(RenderSectionManager.java:182)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.update(RenderSectionManager.java:163)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:228)
	at net.minecraft.client.render.WorldRenderer.setupTerrain(WorldRenderer:4339)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1143)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1001)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:806)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1114)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:730)
	at net.minecraft.client.MinecraftClient.handler$bek000$afterCrashHandled(MinecraftClient:12091)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:754)
	at net.minecraft.client.MinecraftClient.handler$bek000$afterCrashHandled(MinecraftClient:12091)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:754)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.unloadSection(RenderSectionManager.java:331)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.processStatusChangeForSection(RenderSectionManager.java:203)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.processStatusChanges(RenderSectionManager.java:182)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.update(RenderSectionManager.java:163)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:228)
	at net.minecraft.class_761.method_3273(class_761.java:4339)

-- Affected level --
Details:
	All players: 42 total; [class_746['Blobanium'/1668118, l='ClientLevel', x=-30.97, y=61.50, z=172.50], class_745['banker1'/2, l='ClientLevel', x=-18.30, y=61.00, z=160.21], class_745['chikeenugz'/1417975, l='ClientLevel', x=-36.70, y=61.50, z=165.15], class_745['market1'/1, l='ClientLevel', x=-18.51, y=61.00, z=182.62], class_745['__Dusk__'/1463298, l='ClientLevel', x=-35.50, y=61.00, z=162.50], class_745['FourAyces'/471403, l='ClientLevel', x=-35.50, y=61.00, z=160.50], class_745['ShyGuyRanger'/11119, l='ClientLevel', x=-35.50, y=61.00, z=180.50], class_745['PandaAbove'/1562461, l='ClientLevel', x=-36.50, y=61.00, z=178.50], class_745['stevenftw7'/772308, l='ClientLevel', x=-30.70, y=62.00, z=155.30], class_745['iPierre'/731966, l='ClientLevel', x=-24.50, y=61.00, z=156.50], class_745['sustran'/726462, l='ClientLevel', x=-30.50, y=61.00, z=156.50], class_745['Bullyin'/1534887, l='ClientLevel', x=-27.50, y=60.00, z=148.50], class_745['bradboss03'/1666213, l='ClientLevel', x=-26.65, y=60.00, z=151.46], class_745['QuePasa_'/1146199, l='ClientLevel', x=-29.93, y=61.50, z=175.92], class_745['PrimePug'/1621666, l='ClientLevel', x=-25.39, y=61.00, z=168.60], class_745['DanMyDear'/1678389, l='ClientLevel', x=-26.73, y=61.50, z=173.34], class_745['Multipurpose'/1608978, l='ClientLevel', x=-31.74, y=63.50, z=167.53], class_745['AkBlaziken'/1660216, l='ClientLevel', x=-24.29, y=61.42, z=160.80], class_745['TrollingWeek'/1655049, l='ClientLevel', x=-30.70, y=61.50, z=186.31], class_745['XxSimonPro'/1661307, l='ClientLevel', x=-20.30, y=61.00, z=181.72], class_745['Wylix'/396050, l='ClientLevel', x=-24.36, y=62.00, z=187.70], class_745['Misby1'/1635992, l='ClientLevel', x=-20.30, y=61.00, z=182.51], class_745['someon1_'/1681045, l='ClientLevel', x=-19.98, y=61.00, z=180.70], class_745['squ2d'/1669940, l='ClientLevel', x=-16.12, y=61.52, z=174.64], class_745['JpCuber109'/1677204, l='ClientLevel', x=-31.90, y=61.50, z=165.36], class_745['EphemeralAcid'/1682018, l='ClientLevel', x=-29.47, y=61.39, z=178.51], class_745['fuzion_doggo'/1680959, l='ClientLevel', x=-20.93, y=61.00, z=176.00], class_745['StarlightMoon32'/1677661, l='ClientLevel', x=-18.97, y=61.06, z=176.08], class_745['Flash_BCat'/11902, l='ClientLevel', x=-29.64, y=60.50, z=193.67], class_745['Bloo_Myriad'/1673655, l='ClientLevel', x=-26.50, y=60.00, z=194.50], class_745['CamGoBoom'/1675764, l='ClientLevel', x=-25.50, y=60.00, z=194.50], class_745['Rinigiri'/1640554, l='ClientLevel', x=-37.71, y=63.00, z=171.46], class_745['DuckOneTwo'/1657258, l='ClientLevel', x=-25.80, y=61.65, z=164.03], class_745['OhHated'/1581419, l='ClientLevel', x=-22.00, y=62.17, z=176.79], class_745['DigiBlitz'/1682248, l='ClientLevel', x=-34.94, y=63.50, z=169.07], class_745['P1lluws'/1658223, l='ClientLevel', x=-34.17, y=62.00, z=172.22], class_745['chqrri'/1345822, l='ClientLevel', x=-20.49, y=62.06, z=174.38], class_745['Hylix'/1395588, l='ClientLevel', x=-32.69, y=61.50, z=166.54], class_745['Owner'/1639494, l='ClientLevel', x=-28.99, y=61.50, z=170.98], class_745['zFrosTness'/1683475, l='ClientLevel', x=-22.50, y=62.03, z=175.90], class_745['Basi11e'/1682147, l='ClientLevel', x=-32.00, y=62.87, z=171.89], class_745['Bud'/1653411, l='ClientLevel', x=-34.89, y=62.54, z=172.62]]
	Chunk stats: 1024, 330 F: 66 L: 0 U: 143
	Level dimension: minecraft:overworld
	Level spawn location: World: (-42,61,171), Section: (at 6,13,11 in -3,3,10; chunk contains blocks -48,0,160 to -33,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 119752 game time, 18000 day time
	Server brand: ClubSpigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28)
	at net.minecraft.class_310.modify$bek000$onCrash(class_310.java:12099)
	at net.minecraft.class_310.method_1514(class_310.java:754)
	at net.minecraft.class_310.handler$bek000$afterCrashHandled(class_310.java:12091)
	at net.minecraft.class_310.method_1514(class_310.java:754)
	at net.minecraft.class_310.handler$bek000$afterCrashHandled(class_310.java:12091)
	at net.minecraft.class_310.method_1514(class_310.java:754)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 6
	Reload reason: manual
	Finished: Yes
	Packs: Default, Fabric Mods, CustomSounds.zip, Glowing+Ores+1.17.zip, bee-hotbar-selector.zip, 1-15-update-buzzy-bees-gui.zip, e1a86fd0ae8635fc24a31dd0b33935cd6ffbfd11

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1344274432 bytes (1282 MiB) / 2082471936 bytes (1986 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600X 6-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Radeon RX 570 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=27.20.22001.14011
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.00
	Memory slot #2 type: DDR4
	Virtual memory max (MB): 49633.75
	Virtual memory used (MB): 43416.84
	Swap memory total (MB): 16917.16
	Swap memory used (MB): 2089.78
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:ZUncommitDelay=30 -XX:ConcGCThreads=6 -XX:MaxGCPauseMillis=50 -XX:ZCollectionInterval=5
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		architectury: Architectury 2.0.7
		audiooutput: AudioOutput 0.0.4
		autoreconnect: AutoReconnect 1.2.0
		bendy-lib: Bendy api 2.0-SNAPSHOT11
		betterbeds: Better Beds 1.2.0
		betterdroppeditems: Better Dropped Items 1.3.0-1.17
		betterf3: BetterF3 1.1.4
		betterthirdperson: Better Third Person 1.5.0
		blue_endless_jankson: jankson 1.2.1
		bobby: Bobby 2.0.0
		boostedbrightness: Boosted Brightness 2.1.0
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v4 5.0.34
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		cmdkeybind: Command Macros 1.5.2-1.17
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
		com_typesafe_config: config 1.4.1
		confabricate: confabricate 2.1.0-SNAPSHOT+4.1.1
		craftpresence: CraftPresence 1.8.2
		damagetilt: Damage Tilt 1.17-fabric-0.1.2
		de_javagl_obj: obj 0.3.0
		dynamicfps: Dynamic FPS 2.0.3
		emotecraft: Emotecraft 2.0.5
		entityculling: EntityCulling-Fabric 1.2.3
		fabric: Fabric API 0.34.9+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b4463d5
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.2+a02b4463d5
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+9e521e13d5
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b4463d5
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b4463d5
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afad5
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b4463d5
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b4463d5
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da310d5
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b4463d5
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b4463d5
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.8+a02b4463d5
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afad5
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b4463d5
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b4463d5
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab6121d5
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b4463d5
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3ed5
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463d5
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b4463d5
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afad5
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b4463d5
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab6121d5
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b4463d5
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afad5
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab6121d5
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b4463d5
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b4463d5
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.9+a02b4463d5
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+a02b4463d5
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b4463d5
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b4463d5
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b4463d5
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b4463d5
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afad5
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b4463d5
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121a0
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.3+b7ab6121d5
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b4463d5
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.10+be9da310d5
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b4463d5
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b4463d5
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121d5
		fabricloader: Fabric Loader 0.11.3
		fabrishot: Fabrishot 1.5.0
		ferritecore: FerriteCore 3.0.0
		fiber: fiber 0.23.0-2
		figura: Figura 0.0.5f
		firstperson: FirstpersonModel ${version}
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.1.0+null
		java: OpenJDK 64-Bit Server VM 16
		kirin: Kirin UI 1.8.7-1.17
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lazydfu: LazyDFU 0.1.2
		libzoomer: LibZoomer 0.2.1+1.17
		loading-timer: Loading Timer 1.5.0-Beta1
		malilib: MaLiLib 0.10.0+dev.22
		minecraft: Minecraft 1.17
		mm: Manningham Mills 2.1
		modmenu: Mod Menu 2.0.0-beta.7
		multiconnect: MultiConnect 1.4.2
		multiconnect-api: MultiConnect API 1.4.2
		namepain: Name Pain 1.4.0
		notenoughanimations: NotEnoughAnimations 1.3.0
		notenoughcrashes: Not Enough Crashes 3.3.1+1.17
		numericping: Numeric Ping 1.0.0
		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		org_luaj_luaj-jse: luaj-jse 3.0.1
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		performacraft: Performacraft Manager 1.0.0
		presencefootsteps: Presence Footsteps r31-1.17-rc1
		reeses-sodium-options: Reese's Sodium Options 1.1.0
		respackopts: Resource Pack Options 2.0.0
		screenshotclipboard: Screenshot to Clipboard 1.0.6
		seamless_loading_screen: Seamless Loading Screen 1.3.5+1.17
		slight-gui-modifications: 'Slight' GUI Modifications 2.0.0
		smoothboot: Smooth Boot 1.16.5-1.6.0
		sodium: Sodium 0.3.0+IRIS1-unknown
		sodium-extra: Sodium Extra 0.3.2
		spark: spark ${pluginVersion}
		spruceui: SpruceUI 3.2.0+1.17
		starlight: Starlight fabric-1.0.0-RC2-3a77ed1
		thatorthis: ThatOrThis 0.2.3+1.17
		tooltipfix: ToolTip Fix 1.0.2-1.16
		transliterationlib: TRansliterationLib 1.1.0
	Launched Version: fabric-loader-0.11.3-1.17
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 570 Series GL version 3.2.14739 Core Profile Forward-Compatible Context 21.6.1 27.20.22001.14011, ATI Technologies Inc.
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/CustomSounds.zip (incompatible), file/Glowing+Ores+1.17.zip, file/bee-hotbar-selector.zip (incompatible), file/1-15-update-buzzy-bees-gui.zip (incompatible)
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600X 6-Core Processor 
	Client Crashes Since Restart: 3
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Sodium (sodium), Fabric Loader (fabricloader)
```

**Comment by AlsoNiko** [comment]
Known and duplicated issue
