### ISSUE TITLE
Cannot work with immersive-portals

### ISSUE THREAD

**Issue by yaxuan97** [IrisShaders/Iris#469]
### Iris and Minecraft Version

iris-mc1.17-1.1.0 for Minecraft 1.17

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 2060

### Java Version

Java 16

### Reproduction Steps

1. 安装这个mod
2. 安装immersive-portals-0.05-mc1.17-fabric
3. 启动游戏

### Crash Report file and latest.log

```shell
[20:17:32] [main/INFO]: Loading for game Minecraft 1.17
[20:17:33] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b44633d, also found 0.3.0+a02b4463d5
 - Conflicting versions found for fabric-rendering-data-attachment-v1: used 0.1.5+a02b4463d5, also found 0.1.5+a02b44633d
 - Conflicting versions found for fabric-rendering-fluids-v1: used 0.1.13+a02b4463d5, also found 0.1.13+a02b44633d
[20:17:33] [main/INFO]: [FabricLoader] Loading 54 mods: fabric-renderer-api-v1@0.4.3+676f40fa3d, fabric-keybindings-v0@0.2.2+36b77c3e3d, fabricloader@0.11.3, fabric-structure-api-v1@1.1.11+e36969833d, fabric-containers-v0@0.1.12+a02b44633d, fabric-dimensions-v1@2.0.10+a02b44633d, fabric-object-builder-api-v1@1.10.9+b7ab61213d, java@16, fabric-game-rule-api-v1@1.0.6+a02b44633d, fabric-api-base@0.3.0+a02b44633d, fabric-rendering-data-attachment-v1@0.1.5+a02b4463d5, iris@1.1.0+rev.f06a69d, fabric-textures-v0@1.0.6+a02b44633d, q_misc_util@0.5, fabric-rendering-fluids-v1@0.1.13+a02b4463d5, fabric-blockrenderlayer-v1@1.1.5+a02b44633d, fabric-lifecycle-events-v1@1.4.4+a02b44633d, sodium@0.3.0+IRIS1-rev.7491e3a, fabric-renderer-registries-v1@3.2.0+a02b44633d, immersive_portals@0.5, fabric-loot-tables-v1@1.0.4+a02b44633d, fabric@0.35.2+1.17, fabric-particles-v1@0.2.4+a02b44633d, fabric-networking-v0@0.3.2+92519afa3d, fabric-api-lookup-api-v1@1.1.0+1d383bb63d, imm_ptl_core@0.5, fabric-networking-blockentity-v0@0.2.11+a02b44633d, minecraft@1.17, fabric-screen-handler-api-v1@1.1.8+a02b44633d, fabric-command-api-v1@1.1.1+a02b44633d, cloth-basic-math@0.5.1, fabric-screen-api-v1@1.0.4+155f865c3d, fabric-tool-attribute-api-v1@1.2.12+b7ab61213d, fabric-renderer-indigo@0.4.8+a02b44633d, fabric-crash-report-info-v1@0.1.5+be9da3103d, fabric-events-interaction-v0@0.4.8+a02b44633d, fabric-item-api-v1@1.2.4+a02b44633d, fabric-entity-events-v1@1.1.0+a02b44633d, fabric-rendering-v0@1.1.2+92519afa3d, fabric-rendering-v1@1.6.0+a02b44633d, fabric-key-binding-api-v1@1.0.4+a02b44633d, cloth-config2@5.0.34, fabric-resource-loader-v0@0.4.7+b7ab61213d, fabric-content-registries-v0@0.2.2+a02b44633d, fabric-tag-extensions-v0@1.1.4+a02b44633d, fabric-biome-api-v1@3.1.11+c345aea83d, fabric-commands-v0@0.2.2+92519afa3d, fabric-registry-sync-v0@0.7.10+e2961fee3d, fabric-mining-levels-v0@0.1.3+92519afa3d, fabric-networking-api-v1@1.0.11+b7ab61213d, fabric-events-lifecycle-v0@0.2.1+92519afa3d, fabric-item-groups-v0@0.2.10+b7ab61213d, fabric-models-v0@0.3.0+a02b44633d, fabric-object-builders-v0@0.7.3+a02b44633d
[20:17:33] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/D:/MineCraft/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[20:17:33] [main/WARN]: The requested compatibility level JAVA_16 is higher than the level supported by the active subsystem 'Knot/Fabric' which supports JAVA_14. This is not a supported configuration and instability may occur.
[20:17:33] [main/INFO]: Compatibility level set to JAVA_16
[20:17:33] [main/INFO]: Loaded configuration file for Sodium: 24 options available, 0 override(s) found
[20:17:33] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[20:17:33] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in imm_ptl.mixins.json:common.entity_sync.MixinEntityTracker and should be specified in value
[20:17:33] [main/WARN]: @Mixin target net/minecraft/class_761$class_762 is public in imm_ptl.mixins.json:client.render.MixinWorldRendererChunkInfo and should be specified in value
[20:17:34] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
[20:17:39] [Render thread/WARN]: Method overwrite conflict for method_22920 in mixins.iris.vertexformat.json:block_rendering.MixinBufferBuilder_SeparateAo, previously written by me.jellysquid.mods.sodium.mixin.features.buffer_builder.intrinsics.MixinBufferBuilder. Skipping method.
[20:17:40] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:17:42] [Render thread/INFO]: Setting user: yaxuan97
[20:17:42] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zlh000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[20:17:42] [Render thread/INFO]: Immersive Portals Mod Initializing
[20:17:42] [Render thread/INFO]: Reach entity attributes mod is not present
[20:17:42] [Render thread/INFO]: Pehkui is not present
[20:17:42] [Render thread/INFO]: Shaders are disabled because no valid shaderpack is selected
[20:17:43] [Render thread/INFO]: IP Config Applied
[20:17:43] [Render thread/INFO]: Successfully initialized command /immersive_portals_debug
[20:17:43] [Render thread/INFO]: Optifine is not present
[20:17:43] [Render thread/FATAL]: Mixin apply failed imm_ptl.mixins.json:client.render.MixinWorldRenderer -> net.minecraft.class_761: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_761::onGetShaderInRenderingLayer with priority 1000 cannot inject into net/minecraft/class_761::method_3251(Lnet/minecraft/class_1921;Lnet/minecraft/class_4587;DDDLnet/minecraft/class_1159;)V merged by me.jellysquid.mods.sodium.mixin.features.chunk_rendering.MixinWorldRenderer with priority 1000 [PREINJECT Applicator Phase -> imm_ptl.mixins.json:client.render.MixinWorldRenderer -> Prepare Injections ->  -> handler$zhp000$onGetShaderInRenderingLayer(Lnet/minecraft/class_1921;Lnet/minecraft/class_4587;DDDLnet/minecraft/class_1159;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_761::onGetShaderInRenderingLayer with priority 1000 cannot inject into net/minecraft/class_761::method_3251(Lnet/minecraft/class_1921;Lnet/minecraft/class_4587;DDDLnet/minecraft/class_1159;)V merged by me.jellysquid.mods.sodium.mixin.features.chunk_rendering.MixinWorldRenderer with priority 1000 [PREINJECT Applicator Phase -> imm_ptl.mixins.json:client.render.MixinWorldRenderer -> Prepare Injections ->  -> handler$zhp000$onGetShaderInRenderingLayer(Lnet/minecraft/class_1921;Lnet/minecraft/class_4587;DDDLnet/minecraft/class_1159;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.11.3.jar:0.9.2+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-loader-0.11.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:1106) [?:?]
	at java.lang.Class.forNameImpl(Native Method) [?:?]
	at java.lang.Class.forName(Class.java:420) [?:?]
	at java.lang.invoke.MethodTypeHelper.nonPrimitiveClassFromString(MethodTypeHelper.java:182) [?:?]
	at java.lang.invoke.MethodTypeHelper.parseIntoClass(MethodTypeHelper.java:213) [?:?]
	at java.lang.invoke.MethodType.parseIntoClasses(MethodType.java:406) [?:?]
	at java.lang.invoke.MethodType.fromMethodDescriptorString(MethodType.java:318) [?:?]
	at java.lang.invoke.MethodTypeHelper.vmResolveFromMethodDescriptorString(MethodTypeHelper.java:253) [?:?]
	at java.lang.invoke.MethodHandleResolver.sendResolveMethodHandle(MethodHandleResolver.java:310) [?:?]
	at java.lang.invoke.MethodHandleResolver.getCPMethodHandleAt(Native Method) [?:?]
	at java.lang.invoke.MethodHandleResolver.getAdditionalBsmArg(MethodHandleResolver.java:465) [?:?]
	at java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:229) [?:?]
	at qouteall.imm_ptl.core.SodiumInterface.<clinit>(SodiumInterface.java:20) [a60c0151-2510-44cc-9535-0d57b98b1e45.jar:?]
	at qouteall.imm_ptl.core.platform_specific.IPModEntryClient.onInitializeClient(IPModEntryClient.java:69) [a60c0151-2510-44cc-9535-0d57b98b1e45.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$3174/0x00000000f0e85db0.accept(Unknown Source) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33) [fabric-loader-0.11.3.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:459) [intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:179) [intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
[20:17:43] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
```

### Additional context

immersive-portals有说明过无法与Sodium一起工作。我猜与这个有关。

**Comment by AlsoNiko** [comment]
This is a known thing for which compatability is being worked on.
