### ISSUE TITLE
Incompatibility with Kirin UI (Kirin UI/HD Skins/Mine Little Pony)

### ISSUE THREAD

**Issue by RowanSkie** [IrisShaders/Iris#489]
### Iris and Minecraft Version

iris-mc1.17-1.1.0.jar for Minecraft 1.17

### Are you running Sodium along with Iris?

No

### Operating System

Windows 10

### What is your GPU?

Nvidia GTX ZOTAC 1080ti

### Java Version

AdoptOpenJDK JRE Java 16.0.1

### Reproduction Steps

1. Install and run HD Skins with Minecraft + Iris
2. Open the skin selection tab by the lower right of the game.
3. If the screen is red with a rectangular shade by the center-left of the screen showing background dirt, crash imminent.

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Why did you do that?

Time: 05/07/2021, 4:47 pm
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.coderbot.iris.pipeline.WorldRenderingPipeline.shouldDisableVanillaEntityShadows()" because the return value of "net.coderbot.iris.pipeline.PipelineManager.getPipeline()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17+build.13)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.handler$cda000$iris$maybeSuppressEntityShadow(EntityRenderDispatcher:1528)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.renderShadow(EntityRenderDispatcher)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:147)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.renderPlayerEntity(PlayerPreview.java:261)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.renderPlayerModel(PlayerPreview.java:190)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.lambda$renderWorldAndPlayer$3(PlayerPreview.java:140)
	at com.minelittlepony.common.util.render.ClippingSpace.renderClipped(ClippingSpace.java:28)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.renderWorldAndPlayer(PlayerPreview.java:135)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.lambda$render$2(PlayerPreview.java:120)
	at com.minelittlepony.hdskins.client.dummy.DummyPlayerRenderer.wrap(DummyPlayerRenderer.java:45)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.render(PlayerPreview.java:110)
	at com.minelittlepony.hdskins.client.gui.GuiSkins.render(GuiSkins.java:394)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:875)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1114)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:730)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_898.handler$cda000$iris$maybeSuppressEntityShadow(class_898.java:1528)
	at net.minecraft.class_898.method_23166(class_898.java)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (com.minelittlepony.hdskins.client.dummy.DummyPlayer)
	Entity ID: 1
	Entity Name: YoshiiTxshi_
	Entity's Exact location: 0.50, 0.00, 0.50
	Entity's Block location: World: (0,0,0), Section: (at 0,0,0 in 0,0,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {AbsorptionAmount:0.0f,Air:300s,Attributes:[],Brain:{memories:{}},DataVersion:2724,DeathTime:0s,EnderItems:[],FallDistance:0.0f,FallFlying:0b,Fire:-20s,Health:20.0f,HurtByTimestamp:0,HurtTime:0s,Inventory:[],Invulnerable:0b,Motion:[0.0d,0.0d,0.0d],OnGround:1b,PortalCooldown:0,Pos:[0.5d,0.0d,0.5d],Rotation:[0.0f,26.871508f],Score:0,SelectedItemSlot:0,SleepTimer:0s,UUID:[I;-1838482964,1669221103,-2087679593,1868491046],XpLevel:0,XpP:0.0f,XpSeed:0,XpTotal:0,abilities:{flySpeed:0.05f,flying:0b,instabuild:0b,invulnerable:0b,mayBuild:1b,mayfly:0b,walkSpeed:0.1f},foodExhaustionLevel:0.0f,foodLevel:20,foodSaturationLevel:5.0f,foodTickTimer:0,thirstExhaustionLevel:0.0f,thirstLevel:20,thirstTickTimer:0}
Stacktrace:
	at Not Enough Crashes deobfuscated stack trace.(1.17+build.13)
	at java.lang.Thread.getStackTrace(Unknown Source)
	at net.minecraft.util.crash.CrashReportSection.trimStackTraceEnd(CrashReportSection:523)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:197)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:168)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:160)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.renderPlayerEntity(PlayerPreview.java:261)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.renderPlayerModel(PlayerPreview.java:190)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.lambda$renderWorldAndPlayer$3(PlayerPreview.java:140)
	at com.minelittlepony.common.util.render.ClippingSpace.renderClipped(ClippingSpace.java:28)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.renderWorldAndPlayer(PlayerPreview.java:135)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.lambda$render$2(PlayerPreview.java:120)
	at com.minelittlepony.hdskins.client.dummy.DummyPlayerRenderer.wrap(DummyPlayerRenderer.java:45)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.render(PlayerPreview.java:110)
	at com.minelittlepony.hdskins.client.gui.GuiSkins.render(GuiSkins.java:394)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:875)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1114)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:730)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_1007@cd38b34
	Location: 0.00,0.00,0.00 - World: (0,0,0), Section: (at 0,0,0 in 0,0,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at Not Enough Crashes deobfuscated stack trace.(1.17+build.13)
	at java.lang.Thread.getStackTrace(Unknown Source)
	at net.minecraft.util.crash.CrashReportSection.trimStackTraceEnd(CrashReportSection:523)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:197)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:168)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:878)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1114)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:730)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Screen render details --
Details:
	Screen name: com.minelittlepony.hdskins.client.gui.GuiSkins
	Mouse location: Scaled: (1236, 677). Absolute: (2472.000000, 1354.000000)
	Screen size: Scaled: (1280, 720). Absolute: (2560, 1440). Scale factor of 2.000000
Stacktrace:
	at Not Enough Crashes deobfuscated stack trace.(1.17+build.13)
	at java.lang.Thread.getStackTrace(Unknown Source)
	at net.minecraft.util.crash.CrashReportSection.trimStackTraceEnd(CrashReportSection:523)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:197)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:168)
	at net.minecraft.client.resource.ResourceReloadLogger.addReloadSection(ResourceReloadLogger:49)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient:2406)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28)
	at net.minecraft.client.MinecraftClient.modify$cae000$onCrash(MinecraftClient:10599)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:749)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, betterbeds/fancybeds, visualoverhaul/fancyfurnace, visualoverhaul/nobrewingbottles, lambdabettergrass/default, cullleaves/smartleaves, visualoverhaul/coloredwaterbucket
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28)
	at net.minecraft.class_310.modify$cae000$onCrash(class_310.java:10599)
	at net.minecraft.class_310.method_1514(class_310.java:749)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, betterbeds/fancybeds, visualoverhaul/fancyfurnace, visualoverhaul/nobrewingbottles, lambdabettergrass/default, cullleaves/smartleaves, visualoverhaul/coloredwaterbucket

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 10617528 bytes (10 MiB) / 3330277376 bytes (3176 MiB) up to 7516192768 bytes (7168 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1080 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b06
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7111
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 29116.99
	Virtual memory used (MB): 18536.38
	Swap memory total (MB): 12800.00
	Swap memory used (MB): 1015.02
	JVM Flags: 5 total; -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms640m -Xmx7168m
	Fabric Mods: 
		appleskin: AppleSkin mc1.17-2.0.0
		architectury: Architectury 2.0.8
		autopath: Automatic Path 1.4.3
		betterbeds: Better Beds 1.2.0
		betterf3: BetterF3 1.1.5
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.0
		betternether: Better Nether 5.1.0
		betterstrongholds: YUNG's Better Strongholds 1.17-1.0
		blue_endless_jankson: jankson 1.2.1
		cavebiomes: Cave Biomes 0.6.3
		cleardespawn: Clear Despawn 1.17-fabric0.34.9-1.1.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		craftpresence: CraftPresence 1.8.2
		crowdin-translate: CrowdinTranslate 1.3+1.17
		cullleaves: Cull Leaves 2.2.0
		day_dream: Day Dream 1.0.2
		daylight_mobs_reborn: Daylight Mobs Reborn 1.2.2
		dehydration: Dehydration 1.1.6
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dynamicfps: Dynamic FPS 2.0.4
		dynmus: Dynamic Music 1.3.0
		fabric: Fabric API 0.36.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+84310a227d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c03d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b44633d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab61213d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b4463d5
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b4463d5
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121d5
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabric-tree-chopper: Fabric Tree Chopper 0.7.0
		fabricloader: Fabric Loader 0.11.6
		fallingleaves: Falling Leaves 1.7.0+1.17
		fasttransferlib: Fast Transfer Lib 0.4.2
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.2.0
		gbfabrictools: GBfabrictools 1.3.4+1.17
		hdskins: HD Skins 6.4.10
		hydrogen: Hydrogen 0.3
		imm_ptl_core: Immersive Portals Core 0.7
		immersive_portals: Immersive Portals 0.7
		inventorysorter: Inventory Sorter 1.7.9-1.17
		iris: Iris 1.1.0+rev.f06a69d
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kirin: Kirin UI 1.9.1
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lambdabettergrass: LambdaBetterGrass 1.2.0+1.17
		lambdynlights: LambDynamicLights 2.0.1+1.17
		lazydfu: LazyDFU 0.1.2
		libgui: LibGui 4.0.0+1.17
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.2
		mavm: More Axolotl Variants Mod 1.0.2b
		megane: megane 5.0.0
		megane-base: megane-base 5.0.0
		megane-fast-transfer-lib: megane-fast-transfer-lib 5.0.0+0.4.2
		megane-runtime: megane-runtime 5.0.0
		megane-team-reborn-energy: megane-team-reborn-energy 5.0.0+0.1.1
		megane-vanilla: megane-vanilla 5.0.0+1.17
		megane-wireless-networks: megane-wireless-networks 5.0.0+1.1.1
		midnightlib: MidnightLib 0.2.2
		minecraft: Minecraft 1.17
		modern_beta: Modern Beta Fabric 2.0.0-1.17
		modmenu: Mod Menu 2.0.2
		notenoughcrashes: Not Enough Crashes 3.3.1+1.17
		omega-config: OmegaConfig 1.0.8
		org_apache_httpcomponents_httpmime: httpmime 4.3.2
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		pehkui: Pehkui 2.2.1+1.14.4-1.17
		q_misc_util: A Miscellaneous Utility Library from qouteall 0.7
		repurposed_structures: Repurposed Structures 2.0.3+1.17.0
		roughlyenoughitems: Roughly Enough Items 6.0.251-alpha
		seamless_loading_screen: Seamless Loading Screen 1.3.5+1.17
		seasons: Fabric Seasons 1.2.2-BETA+1.17
		sodium: Sodium 0.3.0+IRIS1-rev.7491e3a
		spruceui: SpruceUI 3.2.0+1.17
		stoneholm: Stoneholm 1.3
		team_reborn_energy: Energy 0.1.1
		villagernames: Villager Names 2.0.0
		visualoverhaul: VisualOverhaul 3.3.0
		wirelessnetworks: Wireless Networks 1.1.1
		worldtime: WorldTime 1.17-fabric0.34.9-1.3.1
		wthit: wthit 3.6.1
		yungsapi: YUNG's API 1.17-Fabric-11
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.11, NVIDIA Corporation
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.' x 2
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, betterbeds/fancybeds, visualoverhaul/fancyfurnace, visualoverhaul/nobrewingbottles, lambdabettergrass/default, cullleaves/smartleaves, visualoverhaul/coloredwaterbucket
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Kirin UI (kirin), Fabric Loader (fabricloader), HD Skins (hdskins)
```

### Additional context

Take notice that my crash log has Not Enough Crashes, which allows me to repeatedly actually create crash logs without dropping the game.

**Comment by AlsoNiko** [comment]
1. You are running sodium with iris
2. You need a mod called indium for that to work 
3. Can you confirm the crash happens with indium installed @RowanSkie

**Comment by RowanSkie** [comment]
I'm not running any Sodium jar since they're all on 1.16, that Sodium's part of Iris itself. Without Iris, I don't have Sodium either.

**Comment by AlsoNiko** [comment]
I am aware, that means you are in fact, running sodium, so please add indium and see if this persists

**Comment by DestinyTheGreat** [comment]
yes
you still need Indium because even when bundled with Iris, it's still Sodium, it still lacks FRAPI

**Comment by RowanSkie** [comment]
I'm gonna have to find a compile it, I don't see any available right now.

**Comment by AlsoNiko** [comment]
Check github actions

**Comment by RowanSkie** [comment]
It took a second rebuild with reconfigured Project Structures on my IntelliJ IDE, but it's working now with Indium installed.

**Comment by RowanSkie** [comment]
Okay, some after-issue problems I just realized.

1. After getting a custom skin via HD Skins, OpenGL breaks down and it doesn't render the player character.
2. The "working as intended" with Indium only works after loading in a normal world, otherwise, the same CTD apply.

**Comment by AlsoNiko** [comment]
Please, using only iris, sodium, and indium, and the one mod affected, recreate these issues and open a github issue

**Comment by RowanSkie** [comment]
> Please, using only iris, sodium, and indium, and the one mod affected, recreate these issues and open a github issue

I'm actually doing that right now.
