### ISSUE TITLE
Seemingly random Crash

### ISSUE THREAD

**Issue by Kitt3yL0v3r66** [IrisShaders/Iris#501]
### Iris and Minecraft Version

iris-mc1.17-1.1.0 Minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GTX 1660 Ti

### Java Version

Java 16

### Reproduction Steps

1. Login to Multiplayer World
2. Load in
3. Wait a few seconds
4. Crash

1. Login to Singleplayer World
2. (Sometimes) Fire bow/Crossbow, Hit a mob, Copy Block (Creative)
3. Crash

### Crash Report file and latest.log

```shell
https://gist.github.com/Kitt3yL0v3r66/722401c28c7d813c04f65da15fe84981
```

### Additional context

It seems to happen randomly, I've reinstalled Minecraft (Renamed .minecraft File and let it reinstall) and tried to see if it's a specific mod, no dice. Not Enough Crashes seems to think it's the Fabric Loader but I didn't have a problem until I tried Iris with Sodium so I'm wondering if it's the shaders, didn't know where to ask so I figured I'd start here, I added the whole Log just incase (seems to include stuff from before the crash). Just a heads up I know nothing about coding so I may not understand your questions/answers, thanks!

**Comment by CoderStone** [comment]
Issue seems to be due to figura, not iris, correct me if i'm wrong.

**Comment by JoeEnderman** [comment]
I went to play for the first time in a few months, and thought I'd try modded. I saw that Iris supported shaders and sodium, so I added it. Well, it crashed. I removed everything but Iris and tried again, crash. Here is the log, I don't know how to read it.

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 7/9/21, 5:18 PM
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.class_310.<init>(class_310.java:573)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector iris$alwaysRenderSky(Lnet/minecraft/class_315;)I in mixins.iris.json:MixinWorldRenderer failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap iris-mc1.17-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 15 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.class_310.<init>(class_310.java:573)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 420651296 bytes (401 MiB) / 1442840576 bytes (1376 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx  
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon(TM) RX Vega 10 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: DriverVersion=26.20.11028.0
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 16425.77
	Virtual memory used (MB): 9900.28
	Swap memory total (MB): 2176.00
	Swap memory used (MB): 61.01
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) RX Vega 10 Graphics GL version 3.2.13560 Core Profile Forward-Compatible Context 26.20.11028.0, ATI Technologies Inc.
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 8x AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx

**Comment by AlsoNiko** [comment]
We need a full log file, not a section of it

**Comment by DestinyTheGreat** [comment]
@JoeEnderman Iris for 1.17.1 is only available through the installer, which can be downloaded on [our website](https://irisshaders.net/). Try this version and if a crash still happens, join our discord server for further help. Also, please refrain from putting your issues in the comments of other issues, and check the discord first to see if there's a known fix.

@CoderStone Give us a full log file and a crash report if there is one.

**Comment by Kitt3yL0v3r66** [comment]
> Issue seems to be due to figura, not iris, correct me if i'm wrong.

Here's a full Log again;
https://gist.github.com/Kitt3yL0v3r66/3a9cde220d54ce560a363cee89dd9752

Tried it without Figura in the "Mod" Folder (iris-reserved) played around for a few minutes then it crashed while copying a block of Obsidian.

**Comment by Someone12132** [comment]
I also have this issue and own the same GPU and have the same Java version installed. Does this mean that Iris is not at fault here, but the GPU driver is the issue?

**Comment by Kitt3yL0v3r66** [comment]
I think I figured out the issue, It seems to have been an issue with the Chat Heads mod, once I removed it I stopped crashing. Currently have another problem with Sodium leaking memory but I'm pretty sure that's being looked at.
