### ISSUE TITLE
Incompatible with Colored Lights by Gegy

### ISSUE THREAD

**Issue by VoQZHD** [IrisShaders/Iris#507]
### Iris and Minecraft Version

iris-mc1.17-1.1.0 with 1.17

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

1060

### Java Version

Java 16

### Reproduction Steps

1. Launch game
2. Watch it crash

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2021/07/11 2:22
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'transliterationlib'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.class_1921.<clinit>(class_1921.java:415)
	at dev.tr7zw.transliterationlib.fabric.wrapper.WrapperImpl.lambda$static$0(WrapperImpl.java:97)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at net.minecraft.class_156$7.apply(class_156.java:744)
	at dev.tr7zw.transliterationlib.fabric.wrapper.WrapperImpl.getTextNoCull(WrapperImpl.java:110)
	at dev.tr7zw.transliterationlib.fabric.wrapper.WrapperImpl.<clinit>(WrapperImpl.java:103)
	at dev.tr7zw.transliterationlib.fabric.TRansliterationLibAPIImpl.<init>(TRansliterationLibAPIImpl.java:22)
	at dev.tr7zw.transliterationlib.fabric.TRansliterationLibMod.onInitialize(TRansliterationLibMod.java:12)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [colored_lights.mixins.json:render.entity.ItemRendererMixin] from phase [DEFAULT] in config [colored_lights.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 26 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_918::renderQuad with priority 1000 cannot inject into net/minecraft/class_918::method_23180(Lnet/minecraft/class_4587;Lnet/minecraft/class_4588;Ljava/util/List;Lnet/minecraft/class_1799;II)V merged by me.jellysquid.mods.sodium.mixin.features.item.MixinItemRenderer with priority 1000 [PREINJECT Applicator Phase -> colored_lights.mixins.json:render.entity.ItemRendererMixin -> Prepare Injections ->  -> redirect$cbd000$renderQuad(Lnet/minecraft/class_4588;Lnet/minecraft/class_4587$class_4665;Lnet/minecraft/class_777;FFFII)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 26 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:459)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1002535896 bytes (956 MiB) / 1342177280 bytes (1280 MiB) up to 5268045824 bytes (5024 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.81
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c03
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5751
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 23447.66
	Virtual memory used (MB): 15337.02
	Swap memory total (MB): 15328.94
	Swap memory used (MB): 772.02
	JVM Flags: 10 total; -Xmn128M -Xmx5000M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adapaxels: AdaPaxels 1.2.0+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		advancements-enlarger: Advancements Enlarger 0.2.4
		amecsapi: Amecs API 1.1.4+mc21w16a
		animal_feeding_trough: Animal Feeding Trough 1.0.2
		antighost: AntiGhost 1.17-fabric0.34.9-1.1.4
		apoli: Apoli 1.0.3
		appleskin: AppleSkin mc1.17-2.0.0
		architectury: Architectury 2.1.20
		bedrockify: BedrockIfy 1.1.1+mc1.17
		betterbeds: Better Beds 1.2.0
		betterbiomeblend: Better Biome Blend 1.17.0-1.1.6-fabric
		betterf3: BetterF3 1.1.5
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.0
		betterstrongholds: YUNG's Better Strongholds 1.17-1.0
		biome_locator: Biome Locator 1.1.2
		blue_endless_jankson: jankson 1.2.1
		blur: Blur (Fabric) 2.1.0
		bobby: Bobby 2.0.2
		calio: Calio 1.0.1
		cardinal-components-base: Cardinal Components API (base) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
		carrier: Carrier 1.8.0
		cleancut: CleanCut 1.17-4.0-fabric
		clickthrough: ClickThrough 1.17-fabric0.34.9-0.4
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		colored_lights: Colored Lights 1.0.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		confabricate: confabricate 2.1.0-SNAPSHOT+4.1.1
		controlling: Controlling For Fabric 1.1.2
		craftpresence: CraftPresence 1.8.2
		croptopia: Croptopia 1.5.0
		crowdin-translate: CrowdinTranslate 1.3+1.17
		culinaire: Culinaire 2.1
		dawn: Dawn API 2.0.3
		diggusmaximus: Diggus Maximus 1.4.5-1.17
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dynamicfps: Dynamic FPS 2.0.4
		dynmus: Dynamic Music 1.3.0
		easiervillagertrading: EasierVillagerTrading 1.17-fabric0.34.9-1.5.4
		entityculling: EntityCulling-Fabric 1.3.0
		expcontainer: Experience Container [XP] 1.15.2
		extraalchemy: Extra Alchemy 1.5.0
		fabric: Fabric API 0.36.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d03d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c03d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b4463a0
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463a0
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab6121a0
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b4463d5
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b4463d5
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121a0
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121a0
		fabricloader: Fabric Loader 0.11.3
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fallingtree: FallingTree 2.12.1
		fastchest: FastChest 1.2+1.17
		fenceplayerupper: Fence Player Upper 1.1.3+1.17.pre1
		ferritecore: FerriteCore 3.0.1
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 0.2.18
		gbfabrictools: GBfabrictools 1.3.4+1.17
		harvest_scythes: Harvest Scythes 2.0.5
		hydrogen: Hydrogen 0.3
		improved-stations: Improved Stations 2.0.6
		inmis: Inmis 2.3.1-1.17
		inventoryhud: Inventory HUD + 3.3.2
		inventorysorter: Inventory Sorter 1.7.9-1.17
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.1.0+rev.f06a69d
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lambdabettergrass: LambdaBetterGrass 1.2.0+1.17
		lambdynlights: LambDynamicLights 2.0.1+1.17
		lapisreserve: Lapis Reserve 1.0.8
		lazydfu: LazyDFU 0.1.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.0.0-beta.1+1.17-pre1
		libninepatch: LibNinePatch 1.1.0
		libzoomer: LibZoomer 0.2.1+1.17
		lightoverlay: Light Overlay 6.0.0
		lithium: Lithium 0.7.2
		magna: Magna 1.5.5-1.17-pre4
		maybe-data: Maybe data 1.0.1-1.17
		minecraft: Minecraft 1.17
		mm: Manningham Mills 2.2
		mo_glass: Mo Glass 1.5-MC1.17
		mocolors: Mo' Colors 1.2.0
		modmenu: Mod Menu 2.0.2
		morevillagers-fabric: MoreVillagersFabric 2.0.1-SNAPSHOT
		mostructures: Mo' Structures 1.2.1-1.17
		mousewheelie: Mouse Wheelie 1.7.3+mc1.17-rc1
		musicdr: Music Duration Reducer 1.2.1
		nofade: No Fade 1.17-2.0.0
		nomoreglowingpots: No More Glowing Pots 1.0.2
		notenoughanimations: NotEnoughAnimations 1.3.0
		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
		omega-config: OmegaConfig 1.0.8
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		origins: Origins 1.0.2
		origins-classes: Origins: Classes 1.2.1
		playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		repurposed_structures: Repurposed Structures 2.0.2+1.17.0
		roughlyenoughitems: Roughly Enough Items 6.0.262-alpha
		satin: Satin 1.6.0-nightly.1.17-pre3
		savemystronghold: Save My Stronghold! 1.16.4-1.0
		seamless_loading_screen: Seamless Loading Screen 1.3.5+1.17
		shulkerboxtooltip: Shulker Box Tooltip 3.0.0+1.17
		smootherbedrock: Smoother Bedrock 1.0.1
		sodium: Sodium 0.3.0+IRIS1-rev.7491e3a
		spruceui: SpruceUI 3.2.0+1.17
		staffofbuilding: Staff of Building 1.3.2-1.17
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		stoneholm: Stoneholm 1.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		torohealth: ToroHealth Damage Indicators 1.17-fabric-7
		transliterationlib: TRansliterationLib 1.1.0
		trinkets: Trinkets 3.0.0
		tweed: Tweed 3.0.0-beta.26
		vanilla-hammers: Vanilla Hammers 3.1.2-1.17
		vanillaexcavators: Vanilla Excavators 1.1.0
		waystones: Waystones 2.0.1
		wthit: wthit 3.6.1
		xaerominimap: Xaero's Minimap 21.12.5
		xaeroworldmap: Xaero's World Map 1.14.5.1
		yungsapi: YUNG's API 1.17-Fabric-11
	Launched Version: Fabric 1.17
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

### Additional context

Same error with:
Mo Glass 1.5-MC1.17
Improved Stations 2.0.6
Origins 1.0.2
...

**Comment by coderbot16** [comment]
Sodium is not compatible with Colored Lights: https://github.com/Gegy/colored-lights/issues/11

This needs to be fixed by either Sodium or Colored Lights, Iris itself can't do much, aside from stuff like this: https://github.com/IrisShaders/Iris/issues/191

**Comment by coderbot16** [comment]
Closed due to this not being an Iris issue, it's just Colored Lights not working with Sodium.
