### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by Imcaam** [IrisShaders/Iris#529]
### What happened?

I've used iris since 1.16.5 with no issues but when the update for 1.17.1 came out I changed to playing that but for some reason, after 10 minutes the games closes itself with either message:

''an unexpected error has occurred and the game has crashed exit code 0''
''The game crashed whilst rendering entity in world Error: java.lang.outofmemoryerror: Failed to allocate bytes Exit code -1''

While playing, task manager shows that the process javaw (OpenJDK Plataform Binary) continuously chugs memory, starting from the 2 GB up to 11 GB point at which the game closes itself.

Is this a known issue or is from something else? I looked on Github issues tab but saw no similar posts...

Thanks!

System:

Windows 10 Pro
i5 4690k
rx 5700
16 gb ram

### Screenshots

https://imgur.com/a/DaefH9J

<blockquote class="imgur-embed-pub" lang="en" data-id="a/DaefH9J"  ><a href="//imgur.com/a/DaefH9J">Memory leak?</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 13-07-21 17:31
Description: Rendering entity in world

java.lang.OutOfMemoryError: Failed to allocate 2098688 bytes
	at net.minecraft.class_311.method_1596(class_311.java:13)
	at net.minecraft.class_287.ensureBufferCapacity(class_287.java:559)
	at me.jellysquid.mods.sodium.client.model.vertex.buffer.VertexBufferWriter.ensureCapacity(VertexBufferWriter.java:30)
	at net.minecraft.class_630.method_22702(class_630.java:541)
	at net.minecraft.class_630.method_22699(class_630.java:92)
	at net.minecraft.class_578.method_22963(class_578.java:116)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
	at net.minecraft.class_578.method_2828(class_578.java:116)
	at net.minecraft.class_922.method_4054(class_922.java:134)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1482)
	at net.minecraft.class_761.invokeRenderEntity(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:394)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:460)
	at net.minecraft.class_761.handler$zdc000$iris$renderTerrainShadows(class_761.java:5808)
	at net.minecraft.class_761.method_22710(class_761.java:1160)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.method_3192(class_757.java:810)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_311.method_1596(class_311.java:13)
	at net.minecraft.class_287.ensureBufferCapacity(class_287.java:559)
	at me.jellysquid.mods.sodium.client.model.vertex.buffer.VertexBufferWriter.ensureCapacity(VertexBufferWriter.java:30)
	at net.minecraft.class_630.method_22702(class_630.java:541)
	at net.minecraft.class_630.method_22699(class_630.java:92)
	at net.minecraft.class_578.method_22963(class_578.java:116)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
	at net.minecraft.class_578.method_2828(class_578.java:116)
	at net.minecraft.class_922.method_4054(class_922.java:134)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)

-- Entity being rendered --
Details:
	Entity Type: minecraft:llama (net.minecraft.class_1501)
	Entity ID: 12264
	Entity Name: Llama
	Entity's Exact location: -2956.00, 89.00, -413.00
	Entity's Block location: World: (-2956,89,-413), Section: (at 4,9,3 in -185,5,-26; chunk contains blocks -2960,0,-416 to -2945,255,-401), Region: (-6,-1; contains chunks -192,-32 to -161,-1, blocks -3072,0,-512 to -2561,255,-1)
	Entity's Momentum: 0.00, -0.01, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_921@1b7e8b78
	Location: -80.93,-17.64,74.57 - World: (-81,-18,74), Section: (at 15,14,10 in -6,-2,4; chunk contains blocks -96,0,64 to -81,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: -75.9375
	Delta: 0.7000706
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1482)
	at net.minecraft.class_761.invokeRenderEntity(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:394)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:460)
	at net.minecraft.class_761.handler$zdc000$iris$renderTerrainShadows(class_761.java:5808)
	at net.minecraft.class_761.method_22710(class_761.java:1160)
	at net.minecraft.class_757.method_3188(class_757.java:1026)

-- Affected level --
Details:
	All players: 1 total; [class_746['Imcaam'/123, l='ClientLevel', x=-2875.15, y=104.64, z=-487.52]]
	Chunk stats: 4096, 779
	Level dimension: minecraft:overworld
	Level spawn location: World: (192,64,224), Section: (at 0,0,0 in 12,4,14; chunk contains blocks 192,0,224 to 207,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 77028 game time, 2024 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 991946096 bytes (945 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3,50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: AMD Radeon RX 5700
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x731f
	Graphics card #0 versionInfo: DriverVersion=27.20.1034.6
	Memory slot #0 capacity (MB): 4096,00
	Memory slot #0 clockSpeed (GHz): 1,60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096,00
	Memory slot #1 clockSpeed (GHz): 1,60
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 4096,00
	Memory slot #2 clockSpeed (GHz): 1,60
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 4096,00
	Memory slot #3 clockSpeed (GHz): 1,60
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 30561,08
	Virtual memory used (MB): 30536,25
	Swap memory total (MB): 14233,27
	Swap memory used (MB): 147,74
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: iris-fabric-loader-0.11.5-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon RX 5700 GL version 3.2.13596 Core Profile Forward-Compatible Context 20.10.35.02 27.20.1034.6, ATI Technologies Inc.
	Window size: 1920x1013
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
	Player Count: 1 / 8; [class_3222['Imcaam'/123, l='ServerLevel[New World]', x=-2875.15, y=104.64, z=-487.52]]
	Data Packs: vanilla
```

### Iris and Minecraft Version

iris-fabric-loader-0.11.5-1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

windows 10

### What is your GPU?

AMD rx 5700

### Java Version

java 16

**Comment by IMS212** [comment]
This is known, and a fix is currently being tested for Sodium.

**Comment by Imcaam** [comment]
> 
> 
> This is known, and a fix is currently being tested for Sodium.

Cool, thanks!
