### ISSUE TITLE
Cannot invoke "java.util.Random.nextInt(int)" because "â˜ƒ" is null

### ISSUE THREAD

**Issue by AzureMonument** [IrisShaders/Iris#537]
### Iris and Minecraft Version

Mc 1.17, and Iris 1.1.0+revf06a69d

### Are you running Sodium along with Iris?

No

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce RTX 2070super

### Java Version

Java 16

### Reproduction Steps

I am running multiple mods- Including lithium (not sodium), and mods like "sound filters (fabric)" and First Person Model. So this very well could be a compat. 

To reproduce I simply create a single player world and move around for a bit- the time taken seems somewhat random but I'll eventually crash, taking from between a couple seconds and a few minutes. 

Disabling Iris, as far as I can tell (game's been running for 30 minutes now with me covering a few thousand blocks), disables this crash.

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// My bad.

Time: 7/14/21, 4:02 PM
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "java.util.Random.nextInt(int)" because "â˜ƒ" is null
	at net.minecraft.class_3621.method_15776(class_3621.java:50)
	at net.minecraft.class_3610.method_15768(class_3610.java:80)
	at net.minecraft.class_638.method_2943(class_638.java:305)
	at net.minecraft.class_638.method_2941(class_638.java:274)
	at net.minecraft.class_310.method_1574(class_310.java:1793)
	at net.minecraft.class_310.method_1523(class_310.java:1083)
	at net.minecraft.class_310.method_1514(class_310.java:730)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_3621.method_15776(class_3621.java:50)
	at net.minecraft.class_3610.method_15768(class_3610.java:80)
	at net.minecraft.class_638.method_2943(class_638.java:305)
	at net.minecraft.class_638.method_2941(class_638.java:274)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$cgk000$fillPatchouliContext(class_128.java:521)
	at net.minecraft.class_128.<init>(class_128.java:36)
	at net.minecraft.class_310.method_1514(class_310.java:754)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Affected level --
Details:
	All players: 1 total; [class_746['Aojae'/133, l='ClientLevel', x=82.50, y=65.00, z=-263.50]]
	Chunk stats: 1024, 462
	Level dimension: minecraft:overworld
	Level spawn location: World: (92,63,-256), Section: (at 12,15,0 in 5,3,-16; chunk contains blocks 80,-64,-256 to 95,319,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 3 game time, 3 day time
	Server brand: fabric
	Server type: Integrated singleplayer server

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Generated Resources, Fabric Mods, No+Enchant+Glint.zip

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 2209685840 bytes (2107 MiB) / 4957667328 bytes (4728 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9bc4
	Graphics card #0 versionInfo: DriverVersion=27.20.100.9415
	Graphics card #1 name: NVIDIA GeForce RTX 2070 Super
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1e91
	Graphics card #1 versionInfo: DriverVersion=27.21.14.6677
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 77656.42
	Virtual memory used (MB): 40332.13
	Swap memory total (MB): 45056.00
	Swap memory used (MB): 416.01
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx10240m
	Fabric Mods: 
		adorn: Adorn 2.0.0+1.17
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		advancedcompass: Advanced Compass 1.2.1
		amecsapi: Amecs API 1.1.4+mc21w16a
		animal_feeding_trough: Animal Feeding Trough 1.0.2
		apoli: Apoli 1.0.3
		appleskin: AppleSkin mc1.17-2.0.0
		architectury: Architectury 2.2.21
		artifice: Artifice 0.15.3+21w07a
		attributefix: Attribute Fix {FABRIC} 1.0.1
		autoconfig1u: Auto Config v1 Updated 3.3.1
		axesareweapons: Axes Are Weapons 1.3-1.17
		bclib: BCLib 0.2.2
		betterend: Better End 0.10.4-pre
		betterf3: BetterF3 1.1.5
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.0
		bettermounthud: Better Mount HUD 1.1.1
		betternether: Better Nether 5.1.3
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1
		blast: BLAST 1.6.2
		blockus: Blockus 2.2.6+1.17.1
		caelus: Caelus API 0.0.16-1.17
		calio: Calio 1.0.1
		cardinal-components-base: Cardinal Components API (base) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
		carpet: Carpet Mod 1.4.40
		carpet-extra: Carpet Extra 1.4.43
		carrier: Carrier 1.8.0
		cauldronconcrete: Cauldron Concrete 1.0.0+21w16a-fabric
		centeredinventory: Centered inventory 1.0.3
		charm: Charm 3.3.0
		charmonium: Charmonium 3.3.0
		chat-up: Chat Up! 2.0
		cherishedworlds: Cherished Worlds 1.4.1-1.17
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		collectionorigins1: Imperium Origins Collection 1 2.0
		colormeoutlines: Color Me Outlines 1.0.1
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		comforts: Comforts 0.0.4-1.17
		controlling: Controlling For Fabric 1.1.2
		cpas: cpas 2.0.0
		cpas-api: cpas-api 2.0.0
		cpas-runtime: cpas-runtime 2.0.0
		crawl: Crawl 0.9.0
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customstars: Custom Stars 0.5
		dawn: Dawn API 2.0.2
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dual_riders: DualRiders 1.0.5
		ducts: Ducts 1.1.4
		dynamicfps: Dynamic FPS 2.0.4
		dynmus: Dynamic Music 1.3.0
		easyautocrafting: EasyAutoCrafting 1.1+1.17
		elytraboosters: Elytra Boosters Mod 1.2.0
		enchantmentdescriptions: Enchantment Descriptions 3.0.11
		enhancedblockentities: Enhanced Block Entities 0.4.1+1.17
		environmentz: EnvironmentZ 1.1.4
		expanded_trident_enchanting: Expanded Trident Enchanting 1.0.1
		extraorigins: Extra Origins 1.17-6
		fabric: Fabric API 0.36.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b4463d5
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d03d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c03d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b4463a0
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.1+kotlin.1.5.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463a0
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab6121a0
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afad5
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b4463d5
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b4463d5
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121a0
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b4463d5
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121a0
		fabricenchantments: Fabric Enchantments 0.2.3
		fabricloader: Fabric Loader 0.11.6
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fallingtree: FallingTree 2.12.1
		fiber: fiber 0.23.0-2
		firstperson: FirstpersonModel 2.0.2
		flonters: Flonters 1.2.0+1.17
		hydrogen: Hydrogen 0.3
		impaled: Impaled 1.0.1
		incantationem: Incantationem 1.1
		inventorio: Inventorio 1.6.1
		inventory_control_tweaks: Inventory Control Tweaks 1.3.6+MC1.17
		iris: Iris 1.1.0+rev.f06a69d
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		krypton: Krypton 0.1.3
		libblockattributes: LibBlockAttributes 0.9.0-pre.2
		libblockattributes_core: LibBlockAttributes (Core) 0.9.0-pre.2
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.0-pre.2
		libblockattributes_items: LibBlockAttributes (Items) 0.9.0-pre.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.0.0+1.17
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.3
		lovely_snails: Lovely Snails 1.0.2+1.17
		maelstrom_library: Maelstrom Library 1.2.1-1.17-pre1
		magick: Magick: Potions and Pearls 1.0.3
		malilib: MaLiLib 0.10.0+dev.22
		mavm: More Axolotl Variants Mod 1.0.2b
		maybe-data: Maybe data 1.0.1-1.17
		minecraft: Minecraft 1.17
		miniextras: Mini Extras Mod 1.3.0
		mm: Manningham Mills 2.3
		mobs_attempt_parkour: Mobs Attempt Parkour 0.2.3-1.17-pre1
		modid: freelook 1.0.0
		modmenu: Mod Menu 2.0.2
		mooblooms: Mooblooms 1.5.0
		mousewheelie: Mouse Wheelie 1.7.3+mc1.17-rc1
		nostrip: No Strip 1.2.1-1.17+
		notenoughanimations: NotEnoughAnimations 1.3.0
		notes: Notes 1.0.6
		npcvariety: NPC Variety 2.1.0
		omega-config: OmegaConfig 1.0.8
		onsoulfire: On Soul Fire 1.17-2
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		origins: Origins 1.0.2
		origins-classes: Origins: Classes 1.2.1
		overpoweredmending: OverpoweredMending 2.2.3
		paintingcycle: Painting Cycle 1.0.0
		patchouli: Patchouli 1.17-54-FABRIC
		paxi: Paxi 1.17-1.1
		pehkui: Pehkui 2.2.1+1.14.4-1.17
		pettable: Pettable 1.2.0
		playerabilitylib: Pal 1.3.0
		projectsavethepets: Project: Save the Pets! 1.0.2+minecraft-1.17
		quicksand: Quicksand 1.0.2
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		recipeconditions: Fabric Recipe Conditions 0.4.0
		respawnablepets: Respawnable Pets 1.17-2
		riverredux: River Redux 0.2.0
		roughlyenoughitems: Roughly Enough Items 6.0.258-alpha
		rpgdifficulty: Rpg Difficulty 1.0.6
		rpgstats: RPGStats 4.1.5+1.17.1-rc1
		rpgz: RPGZ 0.4.8
		scaffoldforever: Scaffold Forever 1.1+1.17.1
		scorch: Scorch 1.0.2
		secretrooms: Secret Rooms 1.0.0+1.17
		sentimentality3: Sentimentality 3 1.2.8
		sheepconsistency: Sheep Consistency 1.0.3
		sihywtcamc: sihywtcamc 1.3.1+1.17.1
		sihywtcamd: sihywtcamd 1.3.1+1.17.1
		simple_backpack: SimpleBackpack 1.1.12
		simplemeasuring: Simple Measuring 1.0.0
		skinshine: Skin Shine 1.1.9
		snowundertrees: Snow Under Trees 1.0.0
		sodium: Sodium 0.3.0+IRIS1-rev.7491e3a
		somnus: Somnus API 0.0.12-1.17
		soundphysics: Sound Physics 2.0.0
		staffofbuilding: Staff of Building 1.3.2-1.17
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		statuseffecttimer: Status Effect Timer 1.0.2
		taxfreelevels: Tax Free Levels 1.2.1
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		totemicoverhaul: Totemic Overhaul 1.1.7
		transliterationlib: TRansliterationLib 1.1.0
		transportables: Transportables 1.0.5
		tweakeroo: Tweakeroo 0.10.0-dev.20210710.155746
		tweed: Tweed 3.0.0-beta.26
		twigs: Twigs 1.0.1
		universal_ores: Universal Ores 1.0
		vanilla_essence: Vanilla essence 2.1.2
		vanillatweaks: VanillaTweaks 1.17-1.0.9
		villagernames: Villager Names 2.0.0
		waterdripsound: Drip Sounds 1.17-0.2.1
		wildfire_gender: Wildfire's Female Gender Mod 2.6.1
		windowedfullscreen: Windowed Fullscreen 1.0.0
		wolveswitharmor: Wolves With Armor 1.6.0-1.17
		yungsapi: YUNG's API 1.17-Fabric-13
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics GL version 3.2.0 - Build 27.20.100.9415, Intel
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, secretrooms:client_pack, Fabric Mods, file/No+Enchant+Glint.zip
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
	Player Count: 1 / 8; [class_3222['Aojae'/133, l='ServerLevel[New World]', x=82.50, y=65.00, z=-263.50]]
	Data Packs: secretrooms:server_pack, vanilla (incompatible), Fabric Mods, file/badPower_override.zip, file/william-wythers-overhauled-overworld-for-1-17-e1840.zip, file/william-wythers-caves-and-cliffs-add-on-for-overhauled-overw-e1840.zip
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Jayco\Desktop\Minecraft\MultiMC\instances\Fab 1.17 v3\.minecraft\crash-reports\crash-2021-07-14_16.02.55-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.
```

### Additional context

Thank you for your time.

**Comment by yitzy299** [comment]
This is a vanilla bug which was fixed in 1.17.1

**Comment by AzureMonument** [comment]
1.17.1 is unavailable. The curseforge page only has 1.17, while trying to run that version of iris on 1.17.1 produces this message:

[15:49:26] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: iris requires {minecraft @ [1.17 || 1.17-rc.2]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195) ~[fabric-loader-0.11.6.jar:?]
	... 13 more

And again, there is no other file under minecraft 1.17 on curseforge:
![image](https://user-images.githubusercontent.com/43318292/125809830-b9546c2f-cf2c-4a90-b48a-88637a309309.png)

**Comment by yitzy299** [comment]
The installer has 1.17.1, and GitHub is not for support, please ask on the discord
