### ISSUE TITLE
Crashes when loading world

### ISSUE THREAD

**Issue by boop-the-dog** [IrisShaders/Iris#539]
### Iris and Minecraft Version

iris-mc1.17-1.1.0.jar for 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia GTX 1660Ti

### Java Version

Java 16

### Reproduction Steps

1. Load up Iris with Iris Build of Sodium (One used is sodium-fabric-mc1.17.1-0.3.0+IRIS1-build.60)
2. Join a server or single player world
3. Crash

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// My bad.

Time: 7/14/21, 4:32 PM
Description: Unexpected error

java.lang.NullPointerException: No uniform block exists with name: ubo_DrawParameters
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.5)
	at me.jellysquid.mods.sodium.client.gl.shader.GlProgram.getUniformBlockIndex(GlProgram.java:66)
	at me.jellysquid.mods.sodium.client.render.chunk.shader.ChunkProgram.<init>(ChunkProgram.java:58)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.lambda$createShader$0(ShaderChunkRenderer.java:175)
	at me.jellysquid.mods.sodium.client.gl.shader.GlProgram$Builder.build(GlProgram.java:111)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.createShader(ShaderChunkRenderer.java:161)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.compileProgram(ShaderChunkRenderer.java:61)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java:200)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:100)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:330)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:252)
	at net.minecraft.client.render.WorldRenderer.renderLayer(WorldRenderer:4823)
	at net.minecraft.client.render.WorldRenderer.invokeRenderLayer(WorldRenderer)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:342)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:460)
	at net.minecraft.client.render.WorldRenderer.handler$blo000$iris$renderTerrainShadows(WorldRenderer:9808)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1160)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1026)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:810)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.gl.shader.GlProgram.getUniformBlockIndex(GlProgram.java:66)
	at me.jellysquid.mods.sodium.client.render.chunk.shader.ChunkProgram.<init>(ChunkProgram.java:58)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.lambda$createShader$0(ShaderChunkRenderer.java:175)
	at me.jellysquid.mods.sodium.client.gl.shader.GlProgram$Builder.build(GlProgram.java:111)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.createShader(ShaderChunkRenderer.java:161)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.compileProgram(ShaderChunkRenderer.java:61)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java:200)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:100)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:330)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:252)
	at net.minecraft.class_761.method_3251(class_761.java:4823)
	at net.minecraft.class_761.invokeRenderLayer(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:342)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:460)
	at net.minecraft.class_761.handler$blo000$iris$renderTerrainShadows(class_761.java:9808)

-- Affected level --
Details:
	All players: 72 total; [class_746['Cbble_'/50435, l='ClientLevel', x=41.50, y=87.50, z=22.50], class_745['Dezassete'/36911, l='ClientLevel', x=41.50, y=86.00, z=22.50], class_745['Mikemre'/42743, l='ClientLevel', x=41.50, y=86.00, z=22.50], class_745['mayu145'/42788, l='ClientLevel', x=41.50, y=86.00, z=22.50], class_745['CamaroHeed'/50003, l='ClientLevel', x=41.50, y=86.00, z=22.50], class_745['Reagro'/50046, l='ClientLevel', x=41.50, y=86.00, z=22.50], class_745['RyvalIbeam'/50062, l='ClientLevel', x=41.50, y=86.00, z=22.50], class_745['LegendsFade'/50221, l='ClientLevel', x=41.50, y=87.50, z=22.50], class_745['Eagles48'/50235, l='ClientLevel', x=41.50, y=86.00, z=22.50], class_745['JSAstroSlays'/50310, l='ClientLevel', x=35.06, y=88.59, z=22.47], class_745['Sterreee'/50323, l='ClientLevel', x=39.34, y=86.00, z=23.84], class_745['Alexlol_'/50336, l='ClientLevel', x=41.50, y=86.00, z=22.50], class_745['MegaMemer1'/50366, l='ClientLevel', x=39.91, y=86.00, z=21.16], class_745['ellra'/50386, l='ClientLevel', x=36.59, y=88.59, z=27.25], class_745['Creeperkiller_96'/50415, l='ClientLevel', x=41.50, y=86.00, z=22.50], class_745['RuinTheVibe'/50429, l='ClientLevel', x=40.81, y=86.00, z=22.56], class_745['LemonHero'/50433, l='ClientLevel', x=41.50, y=87.50, z=22.50], class_745['z273sn1m6d'/155, l='ClientLevel', x=37.50, y=86.00, z=19.50], class_745['6knncedunq'/310, l='ClientLevel', x=37.50, y=86.00, z=25.50], class_745['zachypooo8_yt'/49899, l='ClientLevel', x=58.69, y=86.00, z=34.28], class_745['uph02u2s31'/288, l='ClientLevel', x=24.50, y=81.00, z=34.50], class_745['clevver01'/47469, l='ClientLevel', x=25.44, y=82.50, z=33.50], class_745['famousgo'/50390, l='ClientLevel', x=25.44, y=81.00, z=33.50], class_745['9lx3smtmf0'/120, l='ClientLevel', x=16.50, y=80.00, z=34.50], class_745['Nuevada'/50377, l='ClientLevel', x=27.13, y=79.00, z=28.19], class_745['82mx'/50399, l='ClientLevel', x=30.66, y=87.50, z=22.50], class_745['_Aesther_'/50405, l='ClientLevel', x=17.38, y=79.00, z=23.81], class_745['lmGabby_'/50422, l='ClientLevel', x=30.50, y=81.88, z=23.31], class_745['de84er06kl'/49563, l='ClientLevel', x=24.50, y=81.00, z=10.50], class_745['u3ikg12772'/130, l='ClientLevel', x=16.50, y=80.00, z=10.50], class_745['qe880592g8'/135, l='ClientLevel', x=43.50, y=88.00, z=-0.50], class_745['fw7z'/50282, l='ClientLevel', x=3.44, y=79.00, z=47.16], class_745['h7hvu8jkn6'/55, l='ClientLevel', x=11.50, y=80.00, z=33.50], class_745['qb0012y4ie'/105, l='ClientLevel', x=9.50, y=80.00, z=32.50], class_745['536tq8q7w4'/140, l='ClientLevel', x=13.50, y=80.00, z=34.50], class_745['Jack2708'/49761, l='ClientLevel', x=12.88, y=79.00, z=24.94], class_745['DragonGamer4779'/50041, l='ClientLevel', x=12.53, y=79.00, z=22.25], class_745['Reprisal2'/50297, l='ClientLevel', x=12.47, y=79.00, z=22.50], class_745['PoshOBama'/50343, l='ClientLevel', x=12.94, y=79.00, z=27.13], class_745['jbq032101'/50371, l='ClientLevel', x=14.09, y=79.00, z=22.63], class_745['98t7ri9470'/38, l='ClientLevel', x=10.50, y=80.00, z=25.50], class_745['7vtf06r880'/44, l='ClientLevel', x=11.50, y=80.00, z=22.50], class_745['j3k01w8whd'/50, l='ClientLevel', x=5.50, y=81.00, z=22.50], class_745['4xudwuhsd0'/60, l='ClientLevel', x=10.50, y=80.00, z=19.50], class_745['57nv056pji'/65, l='ClientLevel', x=5.50, y=81.00, z=24.50], class_745['2e3uh0x75q'/70, l='ClientLevel', x=5.50, y=81.00, z=20.50], class_745['i0z5k3vhdu'/75, l='ClientLevel', x=6.50, y=81.00, z=26.50], class_745['7iin035893'/80, l='ClientLevel', x=6.50, y=81.00, z=18.50], class_745['rzer2ayc7d'/85, l='ClientLevel', x=6.50, y=81.00, z=28.50], class_745['8a841dvc8n'/90, l='ClientLevel', x=7.50, y=80.00, z=30.50], class_745['7493085ih2'/95, l='ClientLevel', x=6.50, y=81.00, z=16.50], class_745['xbjh0r0r1k'/145, l='ClientLevel', x=12.50, y=79.00, z=29.50], class_745['BriC2004'/34282, l='ClientLevel', x=9.50, y=79.00, z=9.50], class_745['5ls1p18378'/100, l='ClientLevel', x=7.50, y=80.00, z=14.50], class_745['bdtrxg3442'/110, l='ClientLevel', x=9.50, y=80.00, z=12.50], class_745['s6p1qb99zl'/115, l='ClientLevel', x=11.50, y=80.00, z=11.50], class_745['6bi11t21q9'/125, l='ClientLevel', x=13.50, y=80.00, z=10.50], class_745['d051o5z1s7'/150, l='ClientLevel', x=12.50, y=79.00, z=15.50], class_745['pswnup2bep'/292, l='ClientLevel', x=18.50, y=79.00, z=-7.50], class_745['HarambesNephew'/50001, l='ClientLevel', x=38.53, y=79.00, z=-0.28], class_745['Cowkiller000'/50150, l='ClientLevel', x=36.03, y=79.00, z=-6.31], class_745['GodIceBolt'/43880, l='ClientLevel', x=70.59, y=148.00, z=-8.19], class_745['Matf07'/50099, l='ClientLevel', x=84.69, y=71.50, z=70.06], class_745['UdrLyr'/18712, l='ClientLevel', x=76.78, y=71.00, z=71.09], class_745['n56to35rre'/158, l='ClientLevel', x=76.50, y=71.00, z=66.50], class_745['MangGamingMedia'/50287, l='ClientLevel', x=-7.38, y=83.00, z=20.22], class_745['17ugds0z2z'/231, l='ClientLevel', x=8.00, y=79.00, z=-24.50], class_745['CakeBayBay100'/50439, l='ClientLevel', x=41.50, y=87.50, z=22.50], class_745['Mariekm'/50090, l='ClientLevel', x=64.78, y=70.84, z=92.09], class_745['Catbirddragon'/36874, l='ClientLevel', x=-29.69, y=75.00, z=75.28], class_745['Pohakoogon'/49231, l='ClientLevel', x=-30.50, y=98.22, z=28.91], class_745['TallyHinni'/49607, l='ClientLevel', x=76.53, y=169.00, z=107.69]]
	Chunk stats: 16384, 150
	Level dimension: minecraft:overworld
	Level spawn location: World: (41,87,22), Section: (at 9,7,6 in 2,5,1; chunk contains blocks 32,0,16 to 47,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 84493700 game time, 8000 day time
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28)
	at net.minecraft.class_310.modify$bgm000$onCrash(class_310.java:11099)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, betterbeds/fancybeds, VanillaTweaks_r992002.zip

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 963191688 bytes (918 MiB) / 2237661184 bytes (2134 MiB) up to 3221225472 bytes (3072 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600X 6-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 4.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1660 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2182
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7111
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 65438.94
	Virtual memory used (MB): 15456.11
	Swap memory total (MB): 32768.00
	Swap memory used (MB): 0.00
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx3072m
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		antighost: AntiGhost 1.17-fabric0.34.9-1.1.4
		audiooutput: AudioOutput 0.0.4
		bebooks: Better Enchanted Books 1.2.9
		bedrockify: BedrockIfy 1.1.1+mc1.17
		bendy-lib: Bendy api 2.0-SNAPSHOT8
		betterbeds: Better Beds 1.2.0
		betterf3: BetterF3 1.1.5
		betterthirdperson: Better Third Person 1.5.0
		blur: Blur (Fabric) 2.1.0
		boostedbrightness: Boosted Brightness 2.0.0
		clickthrough: ClickThrough 1.17-fabric0.34.9-0.4
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config-lite: cloth-config-lite 2.0.6
		cloth-config2: Cloth Config v4 5.0.34
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		connected_block_textures: Connected Block Textures 0.1.5+1.17
		controlling: Controlling For Fabric 1.1.2
		craftpresence: CraftPresence 1.8.2
		crowdin-translate: CrowdinTranslate 1.3+1.17
		cullleaves: Cull Leaves 2.2.0
		damagetilt: Damage Tilt 1.17-fabric-0.1.2
		dark-loading-screen: Dark Loading Screen 1.6.5
		dcch: DCCH 2.0+1.17
		dynamicfps: Dynamic FPS 2.0.3
		easiervillagertrading: EasierVillagerTrading 1.17.1-fabric0.36.1-1.5.4
		emotecraft: Emotecraft 2.0.4
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.2+1.17
		enhancedblockentities: Enhanced Block Entities 0.4.1+1.17
		entityculling: EntityCulling-Fabric 1.2.3
		extrasounds: Extra Sounds 1.4.1
		fabric: Fabric API 0.37.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57718
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463a0
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121a0
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57718
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		fallingleaves: Falling Leaves 1.7.0+1.17
		ferritecore: FerriteCore 3.0.1
		flighthelper: FlightHelper 1.17-fabric0.34.9-1.2.1
		gbfabrictools: GBfabrictools 1.3.4+1.17
		indium: Indium 1.0.0+rev.beb4972
		inspecio: Inspecio 1.0.3+1.17
		iris: Iris 1.1.0
		itemmodelfix: Item Model Fix 1.0.2+1.17
		java: OpenJDK 64-Bit Server VM 16
		krypton: Krypton 0.1.4
		lambdynlights: LambDynamicLights 2.0.1+1.17
		lithium: Lithium 0.7.3
		logical_zoom: Logical Zoom 0.0.9
		mcemojis: MCEmojis 1.4
		memoryusagescreen: Memory Usage Screen 1.0
		minecraft: Minecraft 1.17.1
		minecraftcapes: MinecraftCapes Mod 10
		modmenu: Mod Menu 2.0.2
		multiconnect: MultiConnect 1.4.5
		multiconnect-api: MultiConnect API 1.4.5
		musicdr: Music Duration Reducer 1.2.1
		nostrip: No Strip 1.2.1-1.17+
		notenoughanimations: NotEnoughAnimations 1.3.0
		notenoughcrashes: Not Enough Crashes 3.3.1+1.17
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		orientation: Critical Orientation 2.0.1
		petowner: Pet Owner 1.8.1-1.17-rc1+
		satin: Satin 1.6.0-nightly.1.17-pre3
		sodium: Sodium 0.3.0+IRIS1-build.64
		spark: spark 1.6.1
		spruceui: SpruceUI 3.2.0+1.17
		starlight: Starlight 1.0.0-RC3+fabric.2b7d7ae
		terra: Terra 5.4.1-BETA+b85880fc
		tooltipfix: ToolTip Fix 1.0.3-1.16
		transliterationlib: TRansliterationLib 1.1.0
		viewbobbingmod: No Screen Bobbing 1.2
		xaerominimapfair: Xaero's Minimap 21.12.5.1
		xaeroworldmap: Xaero's World Map 1.14.5.2
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.11, NVIDIA Corporation
	Window size: 3840x2160
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, betterbeds/fancybeds, file/VanillaTweaks_r992002.zip
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600X 6-Core Processor 
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Fabric Loader (fabricloader), Iris (iris), Sodium (sodium)
```

### Additional context

As you can probably see from the crash report the client was heavily modded so it might be an incompatibility. This crash did not happen on a regular build of sodium but crashed on an iris build of sodium

**Comment by IMS212** [comment]
You need to recompile Iris, the actions build of sodium requires an updated version of Iris.
