### ISSUE TITLE
Crashes in video settings with sodium extra

### ISSUE THREAD

**Issue by xXKasmaXx** [IrisShaders/Iris#576]
### Iris and Minecraft Version

iris 1.1.0  minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia GTX 1660 Super

### Java Version

Java 16

### Reproduction Steps

I'm playing with [sodium extra](https://www.curseforge.com/minecraft/mc-mods/sodium-extra) and as soon as I enter the video settings, the game crashes.

Sodium extra adds a few tabs to the video settings gui so that might be the reason for the crash

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 18.07.21, 18:29
Description: mouseClicked event handler

java.lang.NoSuchMethodError: 'me.jellysquid.mods.sodium.client.gui.options.OptionImpl$Builder me.jellysquid.mods.sodium.client.gui.options.OptionImpl$Builder.setName(net.minecraft.class_2561)'
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.5)
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages.handler$bki000$general(SodiumGameOptionPages.java:535)
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages.general(SodiumGameOptionPages.java:29)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.SodiumVideoOptionsScreen.<init>(SodiumVideoOptionsScreen.java:50)
	at net.minecraft.client.gui.screen.options.OptionsScreen.handler$blc001$open(OptionsScreen:524)
	at net.minecraft.client.gui.screen.options.OptionsScreen.method_19828(OptionsScreen)
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:40)
	at net.minecraft.client.gui.widget.AbstractPressableButtonWidget.onClick(AbstractPressableButtonWidget:16)
	at net.minecraft.client.gui.widget.AbstractButtonWidget.mouseClicked(AbstractButtonWidget:121)
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27)
	at net.minecraft.client.Mouse.method_1611(Mouse:94)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:490)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94)
	at net.minecraft.client.Mouse.method_22686(Mouse:165)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
	at net.minecraft.client.Mouse.method_22684(Mouse:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem:190)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1140)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.MinecraftClient.handler$bjf000$afterCrashHandled(MinecraftClient:11591)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:747)
	at net.minecraft.client.MinecraftClient.handler$bjf000$afterCrashHandled(MinecraftClient:11591)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:747)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages.handler$bki000$general(SodiumGameOptionPages.java:535)
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages.general(SodiumGameOptionPages.java:29)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.SodiumVideoOptionsScreen.<init>(SodiumVideoOptionsScreen.java:50)
	at net.minecraft.class_429.handler$blc001$open(class_429.java:524)
	at net.minecraft.class_429.method_19828(class_429.java)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:121)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_429
Stacktrace:
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.5)
	at java.lang.Thread.getStackTrace(Thread.java:1596)
	at net.minecraft.util.crash.CrashReportSection.trimStackTraceEnd(CrashReportSection:523)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:198)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:169)
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient:2406)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28)
	at net.minecraft.client.MinecraftClient.modify$bjf000$onCrash(MinecraftClient:11599)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:747)
	at net.minecraft.client.MinecraftClient.handler$bjf000$afterCrashHandled(MinecraftClient:11591)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:747)
	at net.minecraft.client.MinecraftClient.handler$bjf000$afterCrashHandled(MinecraftClient:11591)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:747)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, lambdabettergrass/default, VanillaTweaks.zip, 3D.zip, Darkmode.zip, Better Clear Water 1.17.zip, Enchanted Books v0.6.zip, HD Paintings.zip, Dramatic Skys Demo 1.3.zip
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28)
	at net.minecraft.class_310.modify$bjf000$onCrash(class_310.java:11599)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.class_310.handler$bjf000$afterCrashHandled(class_310.java:11591)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.class_310.handler$bjf000$afterCrashHandled(class_310.java:11591)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 796411032 bytes (759 MiB) / 1677721600 bytes (1600 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2,90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) UHD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024,00
	Graphics card #0 deviceId: 0x9bc8
	Graphics card #0 versionInfo: DriverVersion=26.20.100.7642
	Graphics card #1 name: NVIDIA GeForce GTX 1660 SUPER
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095,00
	Graphics card #1 deviceId: 0x21c4
	Graphics card #1 versionInfo: DriverVersion=30.0.14.7111
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 3,20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 3,20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 29520,10
	Virtual memory used (MB): 19568,21
	Swap memory total (MB): 13312,00
	Swap memory used (MB): 1657,42
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		afktape: AFKTape 1.1.1
		amecsapi: Amecs API 1.1.4+mc21w16a
		appleskin: AppleSkin mc1.17-2.0.0
		architectury: Architectury 2.2.21
		cameraoverhaul: Camera Overhaul 1.2.2-fabric-universal
		chatemotes: ChatEmotes 1.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		damagetilt: Damage Tilt 1.17-fabric-0.1.2
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		elytra_bounce: Elytra Hopping 0.1.0+1.16.1
		fabric: Fabric API 0.37.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57718
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b4463d5
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57718
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		fiber: fiber 0.23.0-2
		infinitemusic: Infinite Music 1.3.0
		inventoryhotswap: Inventory Hotswap 1.3.0
		inventoryprofilesnext: Inventory Profiles Next 0.8.2
		iris: Iris 1.1.0
		java: OpenJDK 64-Bit Server VM 16
		kirin: Kirin UI 1.8.7-1.17
		lambdabettergrass: LambdaBetterGrass 1.2.0+1.17
		lambdynlights: LambDynamicLights 2.0.1+1.17
		libzoomer: LibZoomer 0.2.1+1.17
		lightoverlay: Light Overlay 6.0.0
		litematica: Litematica 0.0.0-dev.20210713.103711
		lithium: Lithium 0.7.3
		malilib: MaLiLib 0.10.0-dev.24
		minecraft: Minecraft 1.17.1
		minihud: MiniHUD 0.19.0-dev.20210707.150016
		modmenu: Mod Menu 2.0.2
		mousewheelie: Mouse Wheelie 1.7.3+mc1.17.1-pre1
		multiconnect: MultiConnect 1.4.8
		multiconnect-api: MultiConnect API 1.4.8
		notenoughcrashes: Not Enough Crashes 3.3.1+1.17
		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
		org_apache_httpcomponents_httpclient: httpclient 4.5.10
		org_apache_httpcomponents_httpcore: httpcore 4.4.12
		org_apache_httpcomponents_httpmime: httpmime 4.5.10
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		perspectivemod: Perspective Mod Redux 0.0.5_01
		presencefootsteps: Presence Footsteps r31-1.17-rc1
		reeses-sodium-options: Reese's Sodium Options 1.1.2
		skinswapper: Skin Swapper 2.1.0
		sodium: Sodium 0.3.0+IRIS1-rev.7491e3a
		sodium-extra: Sodium Extra 0.3.3
		spruceui: SpruceUI 3.2.0+1.17
		tweakeroo: Tweakeroo 0.10.0-dev.20210710.155746
		tweed: Tweed 3.0.0-beta.26
		worldedit: WorldEdit 7.2.6-beta-01+1415e6f
		wthit: wthit 3.7.0
		xaerominimap: Xaero's Minimap 21.13.0
		xaeroworldmap: Xaero's World Map 1.14.6.1
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.11, NVIDIA Corporation
	Window size: 2560x1417
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.' x 4
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, lambdabettergrass/default, file/VanillaTweaks.zip, file/3D.zip, file/Darkmode.zip, file/Better Clear Water 1.17.zip, file/Enchanted Books v0.6.zip, file/HD Paintings.zip, file/Dramatic Skys Demo 1.3.zip
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
	Client Crashes Since Restart: 3
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Reese's Sodium Options (reeses-sodium-options), Fabric Loader (fabricloader), Sodium (sodium)
```

**Comment by NoComment1105** [comment]
Are you running latest Sodium extra from Modrinth / cf?

**Comment by yitzy299** [comment]
This is a support issue and should be handled on the discord- you have a mismatched version of sodium extra
