### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by towersvault** [IrisShaders/Iris#588]
### Iris and Minecraft Version

iris-mc1.17-1.1.0.jar for Minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

AMD RX5700 XT

### Java Version

Java 16.0.1

### Reproduction Steps

1. Run Complementary Shaders v4.1 for roughly 20-40 minutes
2. The game will then eventually completely freeze requiring you to force quit it.

### Crash Report file and latest.log

```shell
[19:36:09] [Chunk Render Task Executor #10/INFO]: [STDERR]: java.lang.OutOfMemoryError: Failed to allocate 1523104 bytes
[19:36:09] [Chunk Render Task Executor #10/INFO]: [STDERR]: 	at net.minecraft.class_311.method_1596(class_311.java:13)
[19:36:09] [Chunk Render Task Executor #10/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuildBuffers.createMesh(ChunkBuildBuffers.java:109)
[19:36:09] [Chunk Render Task Executor #10/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:146)
[19:36:09] [Chunk Render Task Executor #10/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:207)
[19:36:09] [Chunk Render Task Executor #10/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[19:36:09] [Chunk Render Task Executor #2/INFO]: [STDERR]: java.lang.OutOfMemoryError: Failed to allocate 1550032 bytes
[19:36:09] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at net.minecraft.class_311.method_1596(class_311.java:13)
[19:36:09] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuildBuffers.createMesh(ChunkBuildBuffers.java:109)
[19:36:09] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:146)
[19:36:09] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:207)
[19:36:09] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[19:36:10] [Render thread/WARN]: COM exception querying Win32_VideoController, which might not be on your system. Will not attempt to query it again. Error was -2147217402: (HRESULT: 80041006)
[19:36:10] [Render thread/WARN]: COM exception querying Win32_PhysicalMemory, which might not be on your system. Will not attempt to query it again. Error was -2147217402: (HRESULT: 80041006)
[19:36:10] [Render thread/WARN]: COM exception querying Win32_PerfRawData_PerfOS_PagingFile, which might not be on your system. Will not attempt to query it again. Error was -2147217402: (HRESULT: 80041006)
```

### Additional context

From Task Manager, it seemed the JVM kept sucking up more and more RAM. At one point it had used about 10GB of RAM out of the total 16GB installed in my system. 
Minecraft would completely freeze up at one point as I suspect the GC then clears out actual things the game needs to properly run.

**Comment by NoComment1105** [comment]
Known
