### ISSUE TITLE
Exit code 0 

### ISSUE THREAD

**Issue by BallerTroy07** [IrisShaders/Iris#589]
### Iris and Minecraft Version

mc.1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

MacOS High Sierra version 10.13.6

### What is your GPU?

intel HD 3000 graphics processor

### Java Version

Java 1.17.1

### Reproduction Steps

1.Load up Minecraft Launcher
2.Hit 'play'
3. Game Crashes

### Crash Report file and latest.log

```shell
16:04:20.731
launcher
main
Preparing to launch minecraft client for fabric-loader-0.11.6-1.17.1
16:04:20.733
launcher
main
Prepared asset index
16:04:20.960
launcher
main
Have 3084 total files to check or download
16:04:20.962
launcher
main
Waiting for 3084 futures
16:04:22.327
launcher
main
Checking installations.
16:04:22.328
launcher
main
Minecraft client fabric-loader-0.11.6-1.17.1 is ready to start.
16:04:22.328
launcher
main
Starting!
16:04:22.328
launcher
main
Nothing to download!
16:04:22.328
launcher
main
Extracting 8 files!
16:04:22.380
launcher
main
Using default game log configuration client-1.12.xml (outputs XML)
16:04:22.380
launcher
main
Installing versions!
16:04:23.442
FabricLoader
main
Loading for game Minecraft 1.17.1
16:04:23.744
Fabric|Loader
main
A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: iris requires {minecraft @ [1.17 || 1.17-rc.2]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832)
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195)
	... 5 more
16:04:23.786
launcher
main

16:04:23.786
monitor
Process Monitor
Process crashed with exit code 1
```

### Additional context

If anyone could tell me how to fix this issue I would really appreciate it

**Comment by NoComment1105** [comment]
You're trying to launch the 1.17 version in 1.17.1, use the launcher to update

**Comment by BallerTroy07** [comment]
> You're trying to launch the 1.17 version in 1.17.1, use the launcher to update

THANK YOU SO MUCH!!

**Comment by BallerTroy07** [comment]
> You're trying to launch the 1.17 version in 1.17.1, use the launcher to update

Sorry not to be a bother, but how do I update with the launcher?

**Comment by AlsoNiko** [comment]
He meant the installer, run it, and uncheck custom loader

**Comment by BallerTroy07** [comment]
the loader version? because I have 0.11.6 selected

**Comment by AlsoNiko** [comment]
No, in the iris installer there is a custom loader option

**Comment by BallerTroy07** [comment]
Ily so much this was so incredibly useful oml
