### ISSUE TITLE
Iris 1.17.1: Failed to launch

### ISSUE THREAD

**Issue by markaabo** [IrisShaders/Iris#598]
### Iris and Minecraft Version

iris-mc1.17-1.1.0

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10 64bit

### What is your GPU?

ASUS Rog STRIX-GTX1080

### Java Version

Java 16

### Reproduction Steps

1. Install fabric on a different directory than default
2. Install Iris+Sodium
3. Launch fabric

### Crash Report file and latest.log

```shell
[11:29:50] [main/INFO]: Loading for game Minecraft 1.17.1
[11:29:50] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: iris requires {minecraft @ [1.17 || 1.17-rc.2]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195) ~[fabric-loader-0.11.6.jar:?]
	... 5 more
```

### Additional context

I cannot start fabric at all when having iris installed, it just pops up with a windows saying "Failed to launch!, Could not find required mod: iris requires {minecraft @ [1.17 || 1.17-rc.2]}, Creating Empty clause ?"

If i remove iris from the mod folder fabric starts up normally and works fine, i don't know if this is because i have the game directory as a different one than default, i have it like that since i have multiple minecraft installs which some are modded and some are different versions which can't have the same game directory :(

Kind Regards Mark

**Comment by NoComment1105** [comment]
Update your iris using the installer to play on 1.17.1
