### ISSUE TITLE
Iris crashing with the "Physics Mod"

### ISSUE THREAD

**Issue by McBlob** [IrisShaders/Iris#608]
### Iris and Minecraft Version

iris-mc1.17-1.1.0 for 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

GTX 1050ti

### Java Version

Java 16

### Reproduction Steps

1. Use the physics mod and iris with sodium
2. start minecraft
3. crash

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 22.07.21, 17:25
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.class_310.<init>(class_310.java:573)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.iris.yeetphysicsmod.json:MixinWorldRenderer] from phase [DEFAULT] in config [mixins.iris.yeetphysicsmod.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 15 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded IllegalStateException whilst transforming the mixin class: [PostApply Phase -> mixins.iris.yeetphysicsmod.json:MixinWorldRenderer -> Plugin Post-Application]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.postApply(MixinTargetContext.java:1204)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:339)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 15 more
Caused by: java.lang.IllegalStateException: Failed to redirect a method call in PhysicsMod rendering
	at net.coderbot.iris.compat.physicsmod.mixin.YeetPhysicsMod.redirect(YeetPhysicsMod.java:114)
	at net.coderbot.iris.compat.physicsmod.mixin.YeetPhysicsMod.postApply(YeetPhysicsMod.java:94)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.postApply(PluginHandle.java:189)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.postApply(MixinInfo.java:1355)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.postApply(MixinTargetContext.java:1193)
	... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.class_310.<init>(class_310.java:573)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 870795416 bytes (830 MiB) / 2181038080 bytes (2080 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3400G with Radeon Vega Graphics    
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 3,70
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1050 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1c82
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6192
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 2,67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 20149,48
	Virtual memory used (MB): 12363,00
	Swap memory total (MB): 3840,00
	Swap memory used (MB): 227,31
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.37.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b4463d5
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57718
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b4463d5
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57718
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		iris: Iris 1.1.0
		java: OpenJDK 64-Bit Server VM 16
		minecraft: Minecraft 1.17.1
		physicsmod: Physics Mod 2.3.3
		sodium: Sodium 0.3.0+IRIS1-rev.7491e3a
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 461.92, NVIDIA Corporation
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 8x AMD Ryzen 5 3400G with Radeon Vega Graphics
```

**Comment by McBlob** [comment]
https://www.curseforge.com/minecraft/mc-mods/physics-mod
This is the mod I was referring to.

**Comment by AlsoNiko** [comment]
There is already an issue for this
