### ISSUE TITLE
"Duplicate delegates" when opening inventory while taking damage

### ISSUE THREAD

**Issue by altrisi** [IrisShaders/Iris#618]
### Iris and Minecraft Version

iris-mc1.16.5-1.1.1-pre+rev.d4dd969.jar

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GTX 1050

### Java Version

Java 8

### Reproduction Steps

Tested only with shaders off.

- Survival wearing enchanted armor (tested with enchanted diamond boots)
- Take damage, by for example doing the following:
  - `/effect give @p instant_health 100000 100 true`
  - `/effect give @p poison 1000 100 true`
- Open your inventory (while taking damage)

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 23/07/21 22:52
Description: Rendering entity in world

java.lang.IllegalArgumentException: Duplicate delegates
	at net.minecraft.class_4720$class_4589.<init>(class_4720.java:29)
	at net.minecraft.class_4720.method_24037(class_4720.java:15)
	at net.minecraft.class_918.method_27952(class_918.java:169)
	at net.minecraft.class_970.method_23192(class_970.java:105)
	at net.minecraft.class_970.method_4169(class_970.java:70)
	at net.minecraft.class_970.method_17157(class_970.java:37)
	at net.minecraft.class_970.method_4199(class_970.java:22)
	at net.minecraft.class_922.method_4054(class_922.java:139)
	at net.minecraft.class_1007.method_4215(class_1007.java:65)
	at net.minecraft.class_1007.method_3936(class_1007.java:42)
	at net.minecraft.class_898.method_3954(class_898.java:261)
	at net.minecraft.class_490.method_29977(class_490.java:149)
	at net.minecraft.class_490$$Lambda$4979/8896147.run(Unknown Source)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1439)
	at net.minecraft.class_490.method_2486(class_490.java:149)
	at net.minecraft.class_490.method_2389(class_490.java:111)
	at net.minecraft.class_465.method_25394(class_465.java:101)
	at net.minecraft.class_485.method_25394(class_485.java:43)
	at net.minecraft.class_490.method_25394(class_490.java:92)
	at net.minecraft.class_757.method_3192(class_757.java:616)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_4720$class_4589.<init>(class_4720.java:29)
	at net.minecraft.class_4720.method_24037(class_4720.java:15)
	at net.minecraft.class_918.method_27952(class_918.java:169)
	at net.minecraft.class_970.method_23192(class_970.java:105)
	at net.minecraft.class_970.method_4169(class_970.java:70)
	at net.minecraft.class_970.method_17157(class_970.java:37)
	at net.minecraft.class_970.method_4199(class_970.java:22)
	at net.minecraft.class_922.method_4054(class_922.java:139)
	at net.minecraft.class_1007.method_4215(class_1007.java:65)
	at net.minecraft.class_1007.method_3936(class_1007.java:42)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 87
	Entity Name: altrisi
	Entity's Exact location: -26.10, 21.00, -23.51
	Entity's Block location: World: (-27,21,-24), Chunk: (at 5,1,8 in -2,-2; contains blocks -32,0,-32 to -17,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_1007@730e92ff
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:261)
	at net.minecraft.class_490.method_29977(class_490.java:149)
	at net.minecraft.class_490$$Lambda$4979/8896147.run(Unknown Source)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1439)
	at net.minecraft.class_490.method_2486(class_490.java:149)
	at net.minecraft.class_490.method_2389(class_490.java:111)
	at net.minecraft.class_465.method_25394(class_465.java:101)
	at net.minecraft.class_485.method_25394(class_485.java:43)
	at net.minecraft.class_490.method_25394(class_490.java:92)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_490
	Mouse location: Scaled: (213, 120). Absolute: (427.000000, 240.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['altrisi'/87, l='ClientLevel', x=-26.10, y=21.00, z=-23.51]]
	Chunk stats: Client Chunk Cache: 1024, 550
	Level dimension: minecraft:overworld
	Level spawn location: World: (101,21,-16), Chunk: (at 5,1,0 in 6,-1; contains blocks 96,0,-16 to 111,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 13764279 game time, 6000 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1010962672 bytes (964 MB) / 1577058304 bytes (1504 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.11.1-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.67, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/VanillaTweaks_r628177.zip
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
```

### Additional context

The crash report doesn't have a mods section since it was ran without Fabric API (only iris + iris-sodium), therefore without crash-report-info. Sodium is `sodium-fabric-mc1.16.5-0.2.0+IRIS3-build.49`.

Deobfuscated stacktrace from a run with Not Enough Crashes:

```java
java.lang.IllegalArgumentException: Duplicate delegates
    at net.minecraft.client.render.VertexConsumers$Dual.<init>(VertexConsumers:29)
    at net.minecraft.client.render.VertexConsumers.dual(VertexConsumers:15)
    at net.minecraft.client.render.item.ItemRenderer.getArmorGlintConsumer(ItemRenderer:169)
    at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.renderArmorParts(ArmorFeatureRenderer:105)
    at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.renderArmor(ArmorFeatureRenderer:70)
    at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.render(ArmorFeatureRenderer:36)
    at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.render(ArmorFeatureRenderer:22)
    at net.minecraft.client.render.entity.LivingEntityRenderer.render(LivingEntityRenderer:139)
    at net.minecraft.client.render.entity.PlayerEntityRenderer.render(PlayerEntityRenderer:65)
    at net.minecraft.client.render.entity.PlayerEntityRenderer.render(PlayerEntityRenderer:42)
    at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:261)
    at net.minecraft.client.gui.screen.ingame.InventoryScreen.method_29977(InventoryScreen:149)
    at net.minecraft.class_490$$Lambda$6843/1648736264.run(Unknown Source)
    at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem:1439)
    at net.minecraft.client.gui.screen.ingame.InventoryScreen.drawEntity(InventoryScreen:149)
    at net.minecraft.client.gui.screen.ingame.InventoryScreen.drawBackground(InventoryScreen:111)
    at net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen:101)
    at net.minecraft.client.gui.screen.ingame.AbstractInventoryScreen.render(AbstractInventoryScreen:43)
    at net.minecraft.client.gui.screen.ingame.InventoryScreen.render(InventoryScreen:92)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:616)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1048)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
    at net.minecraft.client.main.Main.main(Main:215)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

```

**Comment by AlsoNiko** [comment]
Can you try doing this in vanilla? I have a hard time figuring out how iris or sodium would cause this

**Comment by coderbot16** [comment]
Actually, I know exactly why this is caused. It'll be fixed with the new code I'm pushing soon.
