### ISSUE TITLE
Embedded Sodium possibly missing methods required by Indium

### ISSUE THREAD

**Issue by taisph** [IrisShaders/Iris#621]
### What happened?

Minecraft crashes when using blocks from Fabric mods requiring Indium to render blocks correctly, such as Industrial Revolution and Modern Industrialization. Replacing iris+sodium with sodium-fabric-mc1.17.1-0.3.0+build.5 make blocks render correctly and doesn't crash minecraft.

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Oops.

Time: 7/23/21, 11:42 PM
Description: Unexpected error

java.util.concurrent.CompletionException: net.minecraft.class_148: Tesselating block in world - Indium Renderer
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2114)
	at me.jellysquid.mods.sodium.common.util.collections.FutureQueueDrainingIterator.findNext(FutureQueueDrainingIterator.java:33)
	at me.jellysquid.mods.sodium.common.util.collections.FutureQueueDrainingIterator.hasNext(FutureQueueDrainingIterator.java:23)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.setupUploadBatches(RenderRegionManager.java:108)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:29)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:407)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:222)
	at net.minecraft.class_761.method_3273(class_761.java:4338)
	at net.minecraft.class_761.method_22710(class_761.java:1142)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.method_3192(class_757.java:810)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: net.minecraft.class_148: Tesselating block in world - Indium Renderer
	at link.infra.indium.renderer.render.IndiumTerrainRenderContext.tesselateBlock(IndiumTerrainRenderContext.java:85)
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.redirect$bhl000$onRenderBlock(ChunkRenderRebuildTask.java:560)
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:97)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:207)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.NoSuchMethodError: 'int me.jellysquid.mods.sodium.client.render.chunk.compile.buffers.ChunkModelBuilder.getChunkId()'
	at link.infra.indium.renderer.render.IndiumChunkRenderInfo.getInitializedBuffer(IndiumChunkRenderInfo.java:93)
	at link.infra.indium.renderer.render.AbstractQuadRenderer.bufferQuad(AbstractQuadRenderer.java:76)
	at link.infra.indium.renderer.render.AbstractQuadRenderer.tesselateSmooth(AbstractQuadRenderer.java:119)
	at link.infra.indium.renderer.render.AbstractMeshConsumer.tesselateQuad(AbstractMeshConsumer.java:118)
	at link.infra.indium.renderer.render.AbstractMeshConsumer.renderQuad(AbstractMeshConsumer.java:103)
	at link.infra.indium.renderer.render.AbstractMeshConsumer.accept(AbstractMeshConsumer.java:78)
	at link.infra.indium.renderer.render.AbstractMeshConsumer.accept(AbstractMeshConsumer.java:40)
	at me.steven.indrev.blocks.models.MachineBakedModel.emitBlockQuads(MachineBakedModel.java:162)
	at link.infra.indium.renderer.render.IndiumTerrainRenderContext.tesselateBlock(IndiumTerrainRenderContext.java:80)
	... 4 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2114)
	at me.jellysquid.mods.sodium.common.util.collections.FutureQueueDrainingIterator.findNext(FutureQueueDrainingIterator.java:33)
	at me.jellysquid.mods.sodium.common.util.collections.FutureQueueDrainingIterator.hasNext(FutureQueueDrainingIterator.java:23)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.setupUploadBatches(RenderRegionManager.java:108)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:29)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:407)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:222)
	at net.minecraft.class_761.method_3273(class_761.java:4338)
	at net.minecraft.class_761.method_22710(class_761.java:1142)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
```

### Iris and Minecraft Version

iris-mc1.17-1.1.0 for Minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Ubuntu 20.04.2 LTS

### What is your GPU?

NVIDIA GeForce GTX 1070

### Java Version

Java 16.0.1, Microsoft

**Comment by yitzy299** [comment]
The release version of iris sodium is based off an older version of sodium than indium, which is based off 0.3. This is fixed in dev

**Comment by taisph** [comment]
Just to confirm: A manual build of the Iris (iris-mc1.17-1.1.0+rev.d3beab3) and Sodium (sodium-fabric-mc1.17.1-0.3.0+IRIS1-rev.c52ee88) works with Indium (indium-1.0.0+mc1.17.1). Thanks!
