### ISSUE TITLE
"iris for mc 1.17 requires minecraft 1.17"

### ISSUE THREAD

**Issue by ProgWorld2021** [IrisShaders/Iris#641]
### What happened?

I use iris in Minecraft 1.17.1. The game crashed with the log below.
[08:17:19] [main/INFO]: Loading for game Minecraft 1.17.1
[08:17:20] [ForkJoinPool-1-worker-15/WARN]: Non-Fabric mod JAR at "D:\Program Files (x86)\PCLII\Release 2.0.5\.minecraft\versions\1.17.1-Fabric 0.11.6\mods\[苹果皮] appleskin-forge-mc1.17.1-2.1.0.jar", ignoring
[08:17:20] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: iris requires {minecraft @ [1.17 || 1.17-rc.2]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195) ~[fabric-loader-0.11.6.jar:?]
	... 5 more

### Iris and Minecraft Version

iris1.1.0 MInecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows10

### What is your GPU?

GTX 1660 ti

### Java Version

Java16

**Comment by AlsoNiko** [comment]
Use the iris installer and uncheck custom loader for 1.17.1
