### ISSUE TITLE
Slime & Honey blocks Not Rendering Properly Behind Stained Glass

### ISSUE THREAD

**Issue by FroggLeo** [IrisShaders/Iris#649]
### What happened?

it will happen only behind some stained glass and it seems quite unpredictable, the bug will work with the 1.17 tinted glass too.

### Screenshots

Vanilla ↓
![2021-07-28_19 37 14](https://user-images.githubusercontent.com/88123479/127423826-fdad9f93-8ae1-43ea-9fea-adba2c827545.png)

Iris ↓
![2021-07-28_19 37 59](https://user-images.githubusercontent.com/88123479/127423830-e513ed17-7ff0-49b2-95d0-69c41c53090a.png)

outer layer is gone
![2021-07-28_20 15 26](https://user-images.githubusercontent.com/88123479/127426180-bd0acced-958a-4f9c-a6d7-7a102b8df914.png)

### Relevant log output

```shell
[20:19:45] [main/INFO]: Loading for game Minecraft 1.17.1
[20:19:45] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-resource-loader-v0: used 0.4.7+b7ab61213d, also found 0.4.7+b7ab612113
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) recommends any version of mod fabric-textures-v0, which is missing!
	 - You must install any version of fabric-textures-v0.
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b446313, also found 0.3.0+a02b44633d
[20:19:45] [main/INFO]: [FabricLoader] Loading 11 mods:
	- fabric-api-base@0.3.0+a02b446313
	- fabric-key-binding-api-v1@1.0.4+a02b44633d
	- fabric-lifecycle-events-v1@1.4.4+a02b44633d
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446313
	- fabric-rendering-fluids-v1@0.1.13+a02b446313
	- fabric-resource-loader-v0@0.4.7+b7ab61213d
	- fabricloader@0.11.6
	- iris@1.1.1
	- java@16
	- minecraft@1.17.1
	- sodium@0.3.0+IRIS2
[20:19:45] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/xiangsaiyun/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[20:19:45] [main/INFO]: Compatibility level set to JAVA_16
[20:19:45] [main/INFO]: Loaded configuration file for Sodium: 28 options available, 0 override(s) found
[20:19:45] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[20:19:49] [Render thread/WARN]: Method overwrite conflict for method_22920 in mixins.iris.vertexformat.json:block_rendering.MixinBufferBuilder_SeparateAo, previously written by me.jellysquid.mods.sodium.mixin.features.buffer_builder.intrinsics.MixinBufferBuilder. Skipping method.
[20:19:50] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:19:50] [Render thread/INFO]: Setting user: FroggLeo
[20:19:50] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zcj000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[20:19:50] [Render thread/INFO]: Shaders are disabled because enableShaders is set to false in iris.properties
[20:19:51] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[20:19:52] [Render thread/INFO]: Hardware information:
[20:19:52] [Render thread/INFO]: CPU: 8x Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
[20:19:52] [Render thread/INFO]: GPU: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2 (Supports OpenGL 3.2.0 NVIDIA 466.84)
[20:19:52] [Render thread/INFO]: OS: Windows 10
[20:19:53] [Render thread/INFO]: Narrator library for x64 successfully loaded
[20:19:53] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Rendering Data Attachment (v1), Fabric Lifecycle Events (v1), Fabric Resource Loader (v0), Sodium, Iris, Fabric Loader, Fabric Rendering Fluids (v1), Fabric API Base, Fabric Key Binding API (v1)), §f§lyes§0.zip
[20:19:59] [Render thread/WARN]: Skipped language file: minecraft:lang/en_us.json (com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 12 column 2 path $.options.difficulty.hardcore)
[20:19:59] [Render thread/INFO]: OpenAL initialized.
[20:19:59] [Render thread/INFO]: Sound engine started
[20:19:59] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[20:19:59] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[20:19:59] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[20:19:59] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[20:19:59] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[20:19:59] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[20:19:59] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[20:20:00] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[20:20:00] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[20:20:00] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[20:20:06] [Render thread/ERROR]: Invalid icon for world Hallucination
java.lang.IllegalStateException: Must be 64 pixels wide
	at org.apache.commons.lang3.Validate.validState(Validate.java:829) ~[commons-lang3-3.5.jar:3.5]
	at net.minecraft.class_528$class_4272.method_20175(class_528.java:452) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_528$class_4272.<init>(class_528.java:180) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_528.method_2750(class_528.java:110) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_528.<init>(class_528.java:85) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_526.method_25426(class_526.java:63) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:387) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:984) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_442.method_19861(class_442.java:144) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:40) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:121) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_442.method_25402(class_442.java:311) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:490) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:165) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:310) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1137) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[20:20:08] [Render thread/WARN]: Missing data pack Fabric Mods
[20:20:09] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[20:20:09] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[20:20:09] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[20:20:09] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[20:20:09] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[20:20:09] [Render thread/INFO]: Reloading ResourceManager: Default
[20:20:09] [Render thread/INFO]: Loaded 7 recipes
[20:20:09] [Render thread/INFO]: Loaded 1137 advancements
[20:20:10] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:20:10] [Server thread/INFO]: Starting integrated minecraft server version 1.17.1
[20:20:10] [Server thread/INFO]: Generating keypair
[20:20:10] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[20:20:10] [Render thread/INFO]: Preparing spawn area: 0%
[20:20:10] [Render thread/INFO]: Preparing spawn area: 0%
[20:20:11] [Render thread/INFO]: Time elapsed: 1057 ms
[20:20:11] [Server thread/INFO]: Changing view distance to 7, from 10
[20:20:12] [Server thread/INFO]: FroggLeo[local:E:886c9cf0] logged in with entity id 212 at (-45.60955941235452, 18.0, 158.56525744362932)
[20:20:12] [Server thread/INFO]: FroggLeo joined the game
[20:20:12] [Render thread/INFO]: Started 8 worker threads
[20:20:12] [Server thread/INFO]: Saving and pausing game...
[20:20:12] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Quality world]'/minecraft:overworld
[20:20:12] [Render thread/INFO]: Loaded 539 advancements
[20:20:12] [Render thread/INFO]: Reloading shaderpack on dimension change (null -> OVERWORLD)
[20:20:12] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Quality world]'/minecraft:the_nether
[20:20:12] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Quality world]'/minecraft:the_end
[20:20:12] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ModelViewMatrix
[20:20:12] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ProjectionMatrix
[20:20:12] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_NormalMatrix
[20:20:12] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ModelViewMatrix
[20:20:12] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ProjectionMatrix
[20:20:12] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_NormalMatrix
[20:20:12] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ModelViewMatrix
[20:20:12] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ProjectionMatrix
[20:20:12] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_NormalMatrix
[20:20:12] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ModelViewMatrix
[20:20:12] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ProjectionMatrix
[20:20:12] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_NormalMatrix
[20:20:12] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ModelViewMatrix
[20:20:12] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ProjectionMatrix
[20:20:12] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_NormalMatrix
[20:21:37] [Server thread/INFO]: Saving and pausing game...
[20:21:37] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Quality world]'/minecraft:overworld
[20:21:37] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Quality world]'/minecraft:the_nether
[20:21:37] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Quality world]'/minecraft:the_end
[20:21:38] [Server thread/INFO]: FroggLeo lost connection: Disconnected
[20:21:38] [Server thread/INFO]: FroggLeo left the game
[20:21:38] [Server thread/INFO]: Stopping singleplayer server as player logged out
[20:21:38] [Server thread/INFO]: Stopping server
[20:21:38] [Server thread/INFO]: Saving players
[20:21:38] [Server thread/INFO]: Saving worlds
[20:21:38] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Quality world]'/minecraft:overworld
[20:21:38] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Quality world]'/minecraft:the_nether
[20:21:38] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Quality world]'/minecraft:the_end
[20:21:38] [Server thread/INFO]: ThreadedAnvilChunkStorage (DO NOT DELETE): All chunks are saved
[20:21:38] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[20:21:38] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[20:21:38] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[20:21:38] [Render thread/INFO]: Stopping worker threads
[20:21:44] [Render thread/INFO]: Stopping!
```

### Iris and Minecraft Version

iris-mc1.17-1.1.1

### Are you running Sodium along with Iris?

No

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GTX 1660 Ti

### Java Version

Java 16

### Additional context

Sometimes the blocks will stop rendering entirely behind stained glass & tinted glass.

**Comment by coderbot16** [comment]
Not an Iris bug: https://github.com/CaffeineMC/sodium-fabric/issues/38
