### ISSUE TITLE
Crashes when trying to scroll or search in REI (Roughly Enough Items)

### ISSUE THREAD

**Issue by Mimikikokiro** [IrisShaders/Iris#662]
### Iris and Minecraft Version

iris-mc1.17-1.1.1.jar for Minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

AMD Radeon 5700XT

### Java Version

Java 16

### Reproduction Steps

1: Open Game.
2: Open Inventory.
3: Try to scroll down REI or Search to get crash.

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 7/30/21, 1:24 AM
Description: Rendering screen

java.lang.reflect.UndeclaredThrowableException
	at jdk.proxy3/jdk.proxy3.$Proxy120.render(Unknown Source)
	at net.minecraft.class_757.handler$zeo000$renderScreenPost(class_757.java:2039)
	at net.minecraft.class_757.method_3192(class_757.java:874)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:57)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:84)
	... 13 more
Caused by: net.minecraft.class_148: Rendering background of entry
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderBatched(BatchedEntryRendererManager.java:181)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:110)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.method_25394(EntryListWidget.java:259)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:599)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:497)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$18(RoughlyEnoughItemsCoreClient.java:322)
	... 18 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "quads" is null
	at net.minecraft.class_918.method_23182(class_918.java:4048)
	at net.minecraft.class_918.method_23179(class_918.java:170)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.renderBase(ItemEntryDefinition.java:287)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.renderBase(ItemEntryDefinition.java:219)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderBatched(BatchedEntryRendererManager.java:176)
	... 23 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_128.handler$dai000$fillPatchouliContext(class_128.java:521)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$dai000$fillPatchouliContext(class_128.java:521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_128.method_560(class_128.java:267)
	at net.minecraft.class_757.method_3192(class_757.java:876)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_490
	Mouse location: Scaled: (443, 246). Absolute: (887.000000, 492.000000)
	Screen size: Scaled: (512, 384). Absolute: (1024, 768). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['MimikiKokiro'/9591, l='ClientLevel', x=-274.14, y=70.00, z=33.18]]
	Chunk stats: 1024, 249
	Level dimension: minecraft:overworld
	Level spawn location: World: (-192,70,144), Section: (at 0,6,0 in -12,4,9; chunk contains blocks -192,0,144 to -177,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 7106416 game time, 2245033 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Generated Resources, Fabric Mods, KubeJS Resource Pack [assets], charmonium/journeyman, 1-17-quadral-v-6-04-e2010.zip, Enchanted+Tools+v2.3.zip, Enchanted+Swords+v2.0.zip

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 482018816 bytes (459 MiB) / 1902116864 bytes (1814 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 4.10
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon RX 5700 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x731f
	Graphics card #0 versionInfo: DriverVersion=27.20.22017.1004
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 30650.69
	Virtual memory used (MB): 23074.84
	Swap memory total (MB): 14336.00
	Swap memory used (MB): 1264.39
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		addendum: Addendum 1.0.2
		adorn: Adorn 2.1.1+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		advancements-enlarger: Advancements Enlarger 0.2.4
		advdebug: Advancements Debug 2.3.0
		ambientenvironment: Ambient Environment fabric-1.17.1-6.0.13
		amecsapi: Amecs API 1.1.4+mc21w16a
		appleskin: AppleSkin mc1.17-2.1.0
		aqupd: Caracal mob 1.17-1.2.2
		aqupdgrizzly: Grizzly Bear mob 1.1.1
		architectury: Architectury 2.2.21
		artifality: Artifality 0.3.3
		artifice: Artifice 0.15.3+21w07a
		attributefix: Attribute Fix {FABRIC} 1.0.2
		authme: Auth Me 1.5.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		balm-fabric: Balm 1.3.0+0
		bannerpp: Banner++ 2.0.3+mc.1.17-rc1
		basicaiots: Basic AIOTs 1.3.1
		bclib: BCLib 0.2.4
		beenfo: Beenfo 1.17.1-fabric0.36.1-1.3.2
		betterend: Better End 0.10.5-pre
		betterf3: BetterF3 1.1.5
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.0
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1
		biome_locator: Biome Locator 1.1.3
		blast: BLAST 1.7
		blockus: Blockus 2.2.7+1.17.1
		blue_endless_jankson: jankson 1.2.1
		breakprogress: Break Progress 1.0.1
		builtinservers: Builtin Servers 1.0.1-BETA+1.17
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.1.0
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.0.0
		carrier: Carrier 1.8.0
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		cherishedworlds: Cherished Worlds 2.0.1-1.17.1
		cloth-api: Cloth API 2.0.54
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v4 5.0.34
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps fabric-1.17.1-7.0.4
		coat: Coat 1.0.0-beta.9
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_github_shevek_parallelgzip: parallelgzip master-SNAPSHOT
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		conjuring: Conjuring 1.0.5
		controlling: Controlling For Fabric 1.1.2
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		craftingtweaks: Crafting Tweaks 13.0.0+0
		croptopia: Croptopia 1.5.0
		crowdin-translate: CrowdinTranslate 1.3+1.17
		crusade: Crusade 1.2.4
		dankstorage: Dank Storage 2.0a-1.17
		dark-enchanting: Dark Enchanting 0.4.1-1.17.1
		dark-loading-screen: Dark Loading Screen 1.6.5
		darkpaintings: Dark Paintings 3.0.6
		dawn: Dawn API 2.0.3
		de_javagl_obj: obj 0.3.0
		deathlog: DeathLog 0.1.3
		defaultsettings: DefaultSettings 3.0.3
		diggusmaximus: Diggus Maximus 1.4.5-1.17
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dml-refabricated: Deep Mob Learning: Refabricated 0.4.4-beta
		dml-refabricated-base: DML: Refabricated - Base 0.4.4-beta
		dml-refabricated-events: DML: Refabricated - Vanilla Events 0.4.4-beta
		dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 0.4.4-beta
		dml-refabricated-rei: DML: Refabricated - REI Integration 0.4.4-beta
		dual_riders: DualRiders 1.0.5
		dynamicfps: Dynamic FPS 2.0.4
		ecotones: Ecotones 0.8.0
		eggtab: Egg Tab 2.1.0+1.16-fabric
		enchantmentdescriptions: Enchantment Descriptions 3.0.12
		entitybanners: Entity Banners 1.0.1-BETA+1.17
		expandedstorage: Expanded Storage 7.0.0-alpha.33
		extragenerators: Extra Generators 1.0.6-BETA+1.17
		fabric: Fabric API 0.37.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+b246072f13
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.3+kotlin.1.5.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.1.0-pre.04+648b8b6c18
		fabricloader: Fabric Loader 0.11.6
		fake-player-api: Fake Player API 0.2.0
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fasttransferlib: Fast Transfer Lib 0.5.6
		ferritecore: FerriteCore 3.0.1
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 0.2.21
		gateofbabylon: Gate Of Babylon 1.5.0-1.17
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.10
		glassential: Glassential 1.17-1.2.0
		golemsgalore: Golems Galore 1.0.2+mc.1.17
		goml: Get Off My Lawn 1.4.0-beta
		harvest_scythes: Harvest Scythes 2.0.5
		hologram-api: Hologram API 0.1.2+1.17.1
		horseinfo: Horse Info 0.3.0-1.17
		horsestatsvanilla: Horse Stats Vanilla 4.1.8
		impaled: Impaled 1.0.1
		improved-stations: Improved Stations 2.0.7
		incantationem: Incantationem 1.1
		indrev: Industrial Revolution 1.10.0-alpha.11
		inmis: Inmis 2.3.1-1.17
		inventorysorter: Inventory Sorter 1.7.9-1.17
		iris: Iris 1.1.1
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		jumpoverfences: JumpOverFences 1.16-0.0.3
		kibe: Kibe 1.8-BETA+1.17
		kjsextras: KubeJS Extras 1.3.2
		ktdatataglib: KtDataTagLib 1.5.4
		kubejs: KubeJS 1605.3.10-build.9999
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lakeside: Lakeside 1.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		libblockattributes_core: LibBlockAttributes (Core) 0.9.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.0
		libblockattributes_items: LibBlockAttributes (Items) 0.9.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.4+1.17.1
		libninepatch: LibNinePatch 1.1.0
		libzoomer: LibZoomer 0.2.1+1.17
		lifts: Lifts 1.2-BETA+1.17
		lightoverlay: Light Overlay 6.0.0
		lithium: Lithium 0.7.3
		lovely_snails: Lovely Snails 1.0.2+1.17
		magna: Magna 1.5.5-1.17-pre4
		maybe-data: Maybe data 1.0.1-1.17
		me_hypherionmc_simple-rpc-lib: simple-rpc-lib 2.0.3
		megane: megane 5.1.1
		megane-base: megane-base 5.1.1
		megane-extra-generators: megane-extra-generators 5.1.1+1.0.5-BETA-1.17
		megane-fast-transfer-lib: megane-fast-transfer-lib 5.1.1+0.4.2
		megane-industrial-revolution: megane-industrial-revolution 5.1.1+1.10.0-alpha.4
		megane-kibe: megane-kibe 5.1.1+1.7.2-BETA-1.17
		megane-lib-block-attributes: megane-lib-block-attributes 5.1.1+0.9.0
		megane-modern-industrialization: megane-modern-industrialization 5.1.1+0.5.2-alpha.02
		megane-runtime: megane-runtime 5.1.1
		megane-team-reborn-energy: megane-team-reborn-energy 5.1.1+0.1.1
		megane-tech-reborn: megane-tech-reborn 5.1.1+5.0.2-beta-build.38
		megane-vanilla: megane-vanilla 5.1.1+1.17.1
		megane-wireless-networks: megane-wireless-networks 5.1.1+1.1.1
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.2
		mo_glass: Mo Glass 1.5-MC1.17.1
		mocolors: Mo' Colors 1.2.2
		modern_industrialization: Modern Industrialization 0.5.3
		modmenu: Mod Menu 2.0.2
		morevillagers-fabric: MoreVillagersFabric 2.0.4-SNAPSHOT
		mostructures: Mo' Structures 1.2.1-1.17
		mousewheelie: Mouse Wheelie 1.7.3-newconfig+mc1.17.1-pre1
		myron: Myron 1.6.0
		naturescompass: Nature's Compass 1.17.1-2.0.0-fabric
		no-potion-offset: No Potion Offset ${version}
		noanglebrackets: NoAngleBrackets 1.1.0
		notes: Notes 1.0.6
		nyfsquivers: Nyf's Quivers Fabric-0.2.6
		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
		omega-config: OmegaConfig 1.0.8
		org_apache_commons_commons-compress: commons-compress 1.19
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		org_tukaani_xz: xz 1.8
		outvoted: Outvoted 2.0.0-alpha.9
		owo: OwO 0.1.1
		packages: Packages 1.2.1
		packet_tweaker: Packet Tweaker 0.2.0-1.17-pre1
		patchouli: Patchouli 1.17-54-FABRIC
		placeholder-api: Fabric Placeholder API 1.0.1+1.17
		playerabilitylib: Pal 1.3.0
		pling: Pling 1.4.0
		polymer: Polymer 0.1.0-pre9+1.17.1
		promenade: Promenade 2.1.2
		quickshulker: Quick Shulker 1.1.17-1.17
		ratsmischief: Rat's Mischief 1.2
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.0.5-beta+build.85
		redbits: Red Bits 1.9.0
		repurposed_structures: Repurposed Structures 2.1.2+1.17.1
		respawnablepets: Respawnable Pets 1.17-2
		rhino: Rhino 1605.1.1-build.23
		riverredux: River Redux 0.2.0
		roughlyenoughitems: Roughly Enough Items 6.0.264-alpha
		rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		runelic: Runelic 2.0.5
		secretrooms: Secret Rooms 1.0.0+1.17
		server_translations_api: Server Translations API 1.4.5+1.17
		sgui: SGui 1.0.0-rc3-1.17.1
		shulkerboxtooltip: Shulker Box Tooltip 3.0.0+1.17
		shulkerutils: shulkerutils 1.0.1-1.17
		simple-rpc: Simple Rpc 1.17-2.2.2-fabric
		slight-gui-modifications: 'Slight' GUI Modifications 2.0.1
		slotlock: SlotLock 1.0.4-BETA+1.17
		smootherbedrock: Smoother Bedrock 1.0.1
		sodium: Sodium 0.3.0+IRIS2
		someforgepatchesported: Some Forge Patches Ported 1.0.1
		spruceui: SpruceUI 3.2.0+1.17
		staffofbuilding: Staff of Building 1.3.2-1.17
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.2.7
		strawdummy: Straw Dummy 1.5.0
		structurized: Structurized 1.3.0
		survivalisland: Survival Island 0.1.5
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 5.0.5-beta+build.85
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 2.0.0
		terraform-config-api-v1: Terraform Config API (v1) 2.0.0
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 2.0.0
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 2.0.0
		terraform-tree-api-v1: Terraform Tree API (v1) 2.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.1
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.17
		textile_backup: Textile Backup 2.1.0-1.17
		toolstats: Tool Stats 2.0.1
		tooltipfix: ToolTip Fix 1.0.3-1.16
		totemmod: Wither Totems Mod 0.3.2
		traverse: Traverse 4.0.0-beta.1
		trident_return: TridentReturn 1.2.4
		trinkets: Trinkets 3.0.2
		truerooms: True Secret Rooms 1.1.5
		tweed4_annotated: tweed4_annotated 1.0.0
		tweed4_base: tweed4_base 1.0.0
		tweed4_data: tweed4_data 1.0.0
		tweed4_data_hjson: tweed4_data_hjson 1.0.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.0
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.0
		universal-graves: Universal Graves 1.0.7+1.17.1
		untitledduckmod: Untitled Duck Mod 0.3.0
		urns: Urns 1.0.1
		vanilla-hammers: Vanilla Hammers 3.1.2-1.17
		vanillaexcavators: Vanilla Excavators 1.1.0
		vanillaplusbiomes: Vanilla Plus Biomes 0.3.2
		villagershats: Goosik's Villager Hats 1.2.0
		waystones: Waystones 2.0.2
		winged: Winged Mod 1.17.1-3.0.0
		wirelessnetworks: Wireless Networks 1.1.2
		wolveswitharmor: Wolves With Armor 1.6.0-1.17
		woods_and_mires: Woods and Mires 1.1.0+1.17
		workings: Workings 1.0.7
		wthit: wthit 3.7.0
		xaerominimap: Xaero's Minimap 21.14.0
		xaeroworldmap: Xaero's World Map 1.15.0.1
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.17-Fabric-13
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon RX 5700 XT GL version 3.2.14741 Core Profile Forward-Compatible Context 21.7.1 27.20.22017.1004, ATI Technologies Inc.
	Window size: 1024x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, secretrooms:client_pack, Fabric Mods, kubejs:resource_pack (incompatible), charmonium/journeyman, file/1-17-quadral-v-6-04-e2010.zip, file/Enchanted+Tools+v2.3.zip, file/Enchanted+Swords+v2.0.zip
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor
```

**Comment by AlsoNiko** [comment]
How do you know iris is causing this?

**Comment by coderbot16** [comment]
You might need to install Indium. It's often needed for large packs such as yours to work with Sodium, which Iris bundles.

**Comment by Mimikikokiro** [comment]
> You might need to install Indium. It's often needed for large packs such as yours to work with Sodium, which Iris bundles.

This fixed the issue with REI and Iris perfectly! Thank you!

**Comment by coderbot16** [comment]
You're welcome!
