### ISSUE TITLE
Deleting Shaders causes error

### ISSUE THREAD

**Issue by Xemorr** [IrisShaders/Iris#694]
### What happened?

A bug happened!

I deleted my shaders to get a new version, and because they were selected as the shaders to use it caused a file not found exception.

### Relevant log output

```shell
[20:35:19] [Render thread/ERROR]: Failed to load the shaderpack "Optional[Sildurs Vibrant Shaders v1.27 Medium.zip]"!
[20:35:19] [Render thread/ERROR]: Catching
java.nio.file.NoSuchFileException: C:\Users\samue\AppData\Roaming\.minecraft\shaderpacks\Sildurs Vibrant Shaders v1.27 Medium.zip
	at jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:160) ~[jdk.zipfs:?]
	at jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125) ~[jdk.zipfs:?]
	at jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120) ~[jdk.zipfs:?]
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:527) ~[?:?]
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:399) ~[?:?]
	at net.coderbot.iris.Iris.loadExternalZipShaderpack(Iris.java:260) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.Iris.loadExternalShaderpack(Iris.java:205) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.Iris.loadShaderpack(Iris.java:169) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.Iris.reload(Iris.java:349) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.Iris.lambda$onInitializeClient$2(Iris.java:122) ~[iris-mc1.17-1.1.1.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65) ~[aa514b87-746d-4ce7-ba4f-2688ac0cb962.jar:?]
	at net.minecraft.class_310.handler$zmm000$onEndTick(class_310.java:4573) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1806) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1081) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[20:35:19] [Render thread/WARN]: Falling back to normal rendering without shaders because the external shaderpack could not be loaded
[20:35:19] [Render thread/INFO]: Shaders are disabled
```

### Iris and Minecraft Version

iris-mc1.17-1.1.1.jar

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

GTX 980 Ti

### Java Version

Java 16

**Comment by AlsoNiko** [comment]
This bug makes sense, but we should probably add a fall back system for it
