### ISSUE TITLE
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'iris'!

### ISSUE THREAD

**Issue by majjestro** [IrisShaders/Iris#709]
### Iris and Minecraft Version

iris-mc1.17-1.1.1.jar | Minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

GTX 960 4GB

### Java Version

Java 16

### Reproduction Steps

1. Start run Fabric 1.17.1.
2. Game Crashes

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 05.08.2021, 00:22
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'iris'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.<init>(class_310.java:457)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.IllegalStateException: You do not have a compatible version of Sodium installed! You have 0.3.0+build.5 but 0.3.0+IRIS1 is expected
	at net.coderbot.iris.Iris.lambda$onInitializeClient$0(Iris.java:67)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.coderbot.iris.Iris.onInitializeClient(Iris.java:60)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.<init>(class_310.java:457)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 831976752 bytes (793 MiB) / 1207959552 bytes (1152 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4,20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 960
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1401
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7111
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 2,40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 32849,48
	Virtual memory used (MB): 12571,46
	Swap memory total (MB): 17408,00
	Swap memory used (MB): 228,24
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.37.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.3+kotlin.1.5.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		iris: Iris 1.1.1
		java: OpenJDK 64-Bit Server VM 16
		minecraft: Minecraft 1.17.1
		multiconnect: MultiConnect 1.4.11
		multiconnect-api: MultiConnect API 1.4.11
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		sodium: Sodium 0.3.0+build.5
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>





[00:22:17] [main/INFO]: Loading for game Minecraft 1.17.1
[00:22:17] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b446313, also found 0.3.0+a02b44633d, 0.3.0+a02b446318
 - Conflicting versions found for fabric-rendering-data-attachment-v1: used 0.1.5+a02b446313, also found 0.1.5+a02b446318
 - Conflicting versions found for fabric-rendering-fluids-v1: used 0.1.13+a02b446318, also found 0.1.13+a02b446313
 - Conflicting versions found for fabric-lifecycle-events-v1: used 1.4.4+a02b44633d, also found 1.4.4+a02b446318
 - Conflicting versions found for fabric-key-binding-api-v1: used 1.0.4+a02b446318, also found 1.0.4+a02b44633d
[00:22:17] [main/INFO]: [FabricLoader] Loading 61 mods:
	- fabric@0.37.1+1.17
	- fabric-api-base@0.3.0+a02b446313
	- fabric-api-lookup-api-v1@1.2.0+2b5c62d018
	- fabric-biome-api-v1@3.1.11+c345aea818
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c18
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+a02b446318
	- fabric-content-registries-v0@0.2.2+a02b446318
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.1.0+a02b446318
	- fabric-events-interaction-v0@0.4.9+a722d8c018
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+6cefd57718
	- fabric-item-api-v1@1.2.4+a02b446318
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+a02b446318
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-language-kotlin@1.6.3+kotlin.1.5.21
	- fabric-lifecycle-events-v1@1.4.4+a02b44633d
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.12+6cefd57718
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa18
	- fabric-object-builder-api-v1@1.10.9+b7ab612118
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-registry-sync-v0@0.7.10+e2961fee18
	- fabric-renderer-api-v1@0.4.4+5f02c96918
	- fabric-renderer-indigo@0.4.8+a02b446318
	- fabric-renderer-registries-v1@3.2.0+a02b446318
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446313
	- fabric-rendering-fluids-v1@0.1.13+a02b446318
	- fabric-rendering-v0@1.1.2+92519afa18
	- fabric-rendering-v1@1.6.0+a02b446318
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+155f865c18
	- fabric-screen-handler-api-v1@1.1.8+a02b446318
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.1.4+a02b446318
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab612118
	- fabric-transfer-api-v1@1.0.0+3fe3c3f518
	- fabricloader@0.11.6
	- iris@1.1.1
	- java@16
	- minecraft@1.17.1
	- multiconnect@1.4.11
	- multiconnect-api@1.4.11
	- org_jetbrains_kotlin_kotlin-reflect@1.5.21
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.21
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.21
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.21
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.1
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.1
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.2
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.2
	- sodium@0.3.0+build.5
[00:22:17] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/HelloWorld/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[00:22:17] [main/INFO]: Compatibility level set to JAVA_16
[00:22:17] [main/INFO]: Loaded configuration file for Sodium: 28 options available, 0 override(s) found
[00:22:18] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[00:22:18] [main/WARN]: @Mixin target net/minecraft/class_5120$class_5121 is public in fabric-tag-extensions-v0.mixins.json:MixinTagImpl and should be specified in value
[00:22:18] [main/WARN]: @Mixin target net/minecraft/class_702$class_4090 is public in fabric-particles-v1.mixins.json:ParticleManagerAccessor$SimpleSpriteProviderAccessor and should be specified in value
[00:22:18] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[00:22:26] [Render thread/WARN]: Method overwrite conflict for method_22920 in mixins.iris.vertexformat.json:block_rendering.MixinBufferBuilder_SeparateAo, previously written by me.jellysquid.mods.sodium.mixin.features.buffer_builder.intrinsics.MixinBufferBuilder. Skipping method.
[00:22:27] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[00:22:28] [Render thread/INFO]: Setting user: BlockyBuddha
[00:22:28] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zji000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[00:22:29] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
```

### Additional context

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'iris'!

Mods: fabric-api-0.37.1+1.17, fabric-language-kotlin-1.6.3+kotlin.1.5.21, iris-mc1.17-1.1.1, multiconnect-1.4.11, sodium-fabric-mc1.17.1-0.3.0+build.5

**Comment by NoComment1105** [comment]
Remove Sodium release. Iris bundles its own sodium
