### ISSUE TITLE
Part of the shader fall back system isn't working

### ISSUE THREAD

**Issue by NoComment1105** [IrisShaders/Iris#748]
### What happened?

Following on from #743, It appears that the shader fall back system wasn't triggering for the user, resulting in a crash. 

### Relevant log output

```shell
[10:50:09] [Render thread/FATAL]: Unreported exception thrown!
java.lang.RuntimeException: Shader program linking failed, see log for details
    at me.jellysquid.mods.sodium.client.gl.shader.GlProgram$Builder.build(GlProgram.java:108) ~[074deceb-7591-4e26-bdfe-00d886579829.jar:?]
    at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.createShader(ShaderChunkRenderer.java:161) ~[074deceb-7591-4e26-bdfe-00d886579829.jar:?]
    at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.compileProgram(ShaderChunkRenderer.java:61) ~[074deceb-7591-4e26-bdfe-00d886579829.jar:?]
    at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java:200) ~[074deceb-7591-4e26-bdfe-00d886579829.jar:?]
    at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:100) ~[074deceb-7591-4e26-bdfe-00d886579829.jar:?]
    at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:335) ~[074deceb-7591-4e26-bdfe-00d886579829.jar:?]
    at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:235) ~[074deceb-7591-4e26-bdfe-00d886579829.jar:?]
    at net.minecraft.class_761.method_3251(class_761.java:4329) ~[intermediary-iris-fabric-loader-0.11.5-1.17.1.jar:?]
    at net.minecraft.class_761.method_22710(class_761.java:1406) ~[intermediary-iris-fabric-loader-0.11.5-1.17.1.jar:?]
    at net.minecraft.class_757.method_3188(class_757.java:1026) ~[intermediary-iris-fabric-loader-0.11.5-1.17.1.jar:?]
    at net.minecraft.class_757.method_3192(class_757.java:810) ~[intermediary-iris-fabric-loader-0.11.5-1.17.1.jar:?]
    at net.minecraft.class_310.method_1523(class_310.java:1112) ~[intermediary-iris-fabric-loader-0.11.5-1.17.1.jar:?]
    at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-iris-fabric-loader-0.11.5-1.17.1.jar:?](edited)
[06:19]
at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-iris-fabric-loader-0.11.5-1.17.1.jar:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [iris-loader-0.11.5.jar:?]
    at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [iris-loader-0.11.5.jar:?]
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [iris-loader-0.11.5.jar:?]
```

### Iris and Minecraft Version

Iris 1.1.1 from the installer

### Are you running Sodium along with Iris?

Yes

### Operating System

Ubuntu 18.04

### What is your GPU?

NVIDIA GeForce GT 720M/PCIe/SSE2

### Java Version

Java 16

### Additional context

Please not the system configurations are taken from that issue too.

the direct log file taken from that issue. The user is on AMD Linux
[2021-08-10-2.log](https://github.com/IrisShaders/Iris/files/6966203/2021-08-10-2.log)

**Comment by NoComment1105** [comment]
Closing as no further evidence of this has been seen

**Comment by LizIsTired** [comment]
Getting this exact error in Iris 1.1.2
