### ISSUE TITLE
Crash on Startup: java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Rektroth** [IrisShaders/Iris#751]
### Iris and Minecraft Version

iris-mc1.17-1.1.1.jar for Minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10 (amd64) version 10.0

### What is your GPU?

NVIDIA GeForce GTX 1070 with Max-Q Design

### Java Version

16.0.1, Microsoft

### Reproduction Steps

1. Install
2. Place "Apex Shaders" v1.4 in the shaderpacks folder
3. Launch

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 8/12/21, 4:55 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'iris'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.<init>(class_310.java:457)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 4
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3751)
	at java.base/java.lang.String.substring(String.java:1907)
	at net.coderbot.iris.shaderpack.ShaderPack.lambda$parseLangEntries$3(ShaderPack.java:131)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at net.coderbot.iris.shaderpack.ShaderPack.parseLangEntries(ShaderPack.java:124)
	at net.coderbot.iris.shaderpack.ShaderPack.<init>(ShaderPack.java:38)
	at net.coderbot.iris.Iris.loadExternalShaderpack(Iris.java:243)
	at net.coderbot.iris.Iris.loadShaderpack(Iris.java:169)
	at net.coderbot.iris.Iris.onInitializeClient(Iris.java:94)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.<init>(class_310.java:457)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 642712992 bytes (612 MiB) / 1241513984 bytes (1184 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.21
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1070 with Max-Q Design
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1ba1
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7168
	Graphics card #1 name: Intel(R) UHD Graphics 630
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x3e9b
	Graphics card #1 versionInfo: DriverVersion=23.20.16.4974
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18662.39
	Virtual memory used (MB): 8091.16
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

### Additional context

- No other mods installed.
- Only shaderpack installed is "Apex Shaders" v1.4 - game does not crash when this shaderpack is removed.

**Comment by IMS212** [comment]
What shader are you attempting to use?

**Comment by Rektroth** [comment]
Apex Shaders v1.4 was the only shaderpack installed.
Removing it solved the problem.
Does something in that shader cause a known problem?

**Comment by IMS212** [comment]
No, we’ll have to look into it. Thanks for the report, though!

**Comment by V1K1NGbg** [comment]
I have the same error, but removing the shaders didn't help

**Comment by V1K1NGbg** [comment]
I have 
- sodium-fabric-mc1.17.1-0.3.0+build.5
- sodium-extra-mc1.17.1-0.3.3
- indium-1.0.0+mc1.17.1
- lithium-fabric-mc1.17.1-0.7.3
- iris-mc1.17-1.1.1

**Comment by V1K1NGbg** [comment]
And also I used BSL shaders

**Comment by AlsoNiko** [comment]
Iris bundles sodium already, please remove it

**Comment by Rektroth** [comment]
I don't have Sodium separate.

**Comment by AlsoNiko** [comment]
Please move to our discord server for support then

**Comment by AlsoNiko** [comment]
Oh wait, someone else commented on this issue with a different error, which is annoying, my bad
