### ISSUE TITLE
Can't load a shader that is already built upon the core profile

### ISSUE THREAD

**Issue by JustSimplyKyle** [IrisShaders/Iris#779]
### What happened?

trying to load atlas shader
https://www.curseforge.com/minecraft/customization/atlas-shader-by-huajijun/

### Relevant log output

```shell
[23:30:58] [Render thread/WARN]: Custom blending mode directives are not supported, ignoring blend directive for blend.gbuffers_skybasic
[23:30:58] [Render thread/WARN]: Custom blending mode directives are not supported, ignoring blend directive for blend.gbuffers_weather
[23:30:58] [Render thread/WARN]: Unrecognized internal texture format RGB8F specified for colortex0Format, ignoring.
[23:30:58] [Render thread/WARN]: Unrecognized internal texture format RGB8F specified for colortex4Format, ignoring.
[23:30:58] [Render thread/WARN]: Unrecognized internal texture format RGBA8F specified for colortex6Format, ignoring.
[23:30:58] [Render thread/ERROR]: #elif conditions in block.properties are not yet supported, but the current shaderpack is trying to use them!
[23:30:58] [Render thread/WARN]: Failed to parse line in block.properties: invalid render layer type: layer.translucent
[23:30:58] [Render thread/INFO]: Using shaderpack: TEST+0.16+SUPPORT+PBR.zip
[23:30:58] [Render thread/ERROR]: Couldn't load NewWorldRenderingPipeline, falling back to vanilla shaders.
java.lang.IllegalStateException: Transforming a shader that is already built against the core profile???
	at net.coderbot.iris.pipeline.newshader.TriforceCompositePatcher.fixVersion(TriforceCompositePatcher.java:138) ~[iris-mc1.17-1.1.2-pre+rev.dcc1352.jar:?]
	at net.coderbot.iris.pipeline.newshader.TriforceCompositePatcher.patch(TriforceCompositePatcher.java:20) ~[iris-mc1.17-1.1.2-pre+rev.dcc1352.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:197) ~[iris-mc1.17-1.1.2-pre+rev.dcc1352.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:81) ~[iris-mc1.17-1.1.2-pre+rev.dcc1352.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:191) ~[iris-mc1.17-1.1.2-pre+rev.dcc1352.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:423) ~[iris-mc1.17-1.1.2-pre+rev.dcc1352.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:39) [iris-mc1.17-1.1.2-pre+rev.dcc1352.jar:?]
	at net.minecraft.class_761.handler$coa000$iris$beginWorldRender(class_761.java:10825) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1026) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:810) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1112) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[23:30:58] [Render thread/INFO]: Stopping worker threads
[23:30:58] [Render thread/INFO]: Started 24 worker threads
[23:30:58] [Render thread/WARN]: No uniform exists with name: u_ModelViewProjectionMatrix
[23:30:58] [Render thread/WARN]: No uniform exists with name: u_NormalMatrix
[23:30:58] [Render thread/WARN]: No uniform exists with name: u_ModelViewProjectionMatrix
[23:30:58] [Render thread/WARN]: No uniform exists with name: u_NormalMatrix
[23:30:58] [Render thread/WARN]: No uniform exists with name: u_ModelViewProjectionMatrix
[23:30:58] [Render thread/WARN]: No uniform exists with name: u_NormalMatrix
[23:30:58] [Render thread/WARN]: No uniform exists with name: u_ModelViewProjectionMatrix
[23:30:58] [Render thread/WARN]: No uniform exists with name: u_NormalMatrix
[23:30:58] [Render thread/WARN]: No uniform exists with name: u_ModelViewProjectionMatrix
[23:30:58] [Render thread/WARN]: No uniform exists with name: u_NormalMatrix
```

### Iris and Minecraft Version

iris-1.1.2-pre+rev.dcc1352+sodium 0.3.0+IRIS2-rev.6a84168

### Are you running Sodium along with Iris?

Yes

### Operating System

Arch linux

### What is your GPU?

MSI RX5700xt+mesa

### Java Version

adoptoopenjdk java 16

**Comment by IMS212** [comment]
Also this should go under a different issue, atlus shader is breaking for a different reason.
