### ISSUE TITLE
Crash on 1.17.1 launch

### ISSUE THREAD

**Issue by red2blue** [IrisShaders/Iris#782]
### What happened?

I know the crash says suspected plugins however once I removed iris the crash went away. When I: launch game it would load everything and then crash. 

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 8/21/21, 2:19 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'outvoted'!
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.40)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.client.MinecraftClient.redirect$bag000$catchFabricInit(MinecraftClient:7064)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:457)
	at net.minecraft.client.main.Main.main(Main:179)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
		at torcherino.blocks.ModBlocks.setRenderType(ModBlocks.java:71)
		at torcherino.blocks.ModBlocks.lambda$initialize$0(ModBlocks.java:53)
		at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:146)
		at torcherino.blocks.ModBlocks.initialize(ModBlocks.java:36)
		at torcherino.Torcherino.onInitialize(Torcherino.java:44)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 12 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
		at ninjaphenix.expandedstorage.barrel.Main.lambda$registerBlocks$1(Main.java:25)
		at com.google.common.collect.ImmutableSet$Indexed.forEach(ImmutableSet.java:392)
		at ninjaphenix.expandedstorage.barrel.Main.registerBlocks(Main.java:25)
		at ninjaphenix.expandedstorage.barrel.BarrelCommon.registerContent(BarrelCommon.java:86)
		at ninjaphenix.expandedstorage.barrel.Main.initialize(Main.java:35)
		at ninjaphenix.expandedstorage.base.Main.lambda$onInitialize$2(Main.java:33)
		at java.util.ArrayList.forEach(ArrayList.java:1511)
		at ninjaphenix.expandedstorage.base.Main.onInitialize(Main.java:33)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 12 more
	Suppressed: java.lang.ExceptionInInitializerError
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:466)
		at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
		at net.fabricmc.loader.EntrypointStorage$NewEntry.lambda$getOrCreate$0(EntrypointStorage.java:106)
		at java.util.HashMap.computeIfAbsent(HashMap.java:1224)
		at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:104)
		at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:191)
		at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 12 more
	Caused by: java.lang.RuntimeException: Attempted to register ID ResourceKey[minecraft:entity_type / aqupd:caracal] at different raw IDs (265, 269)! If you're trying to override an item, use .set(), not .register()!
		at net.minecraft.util.registry.SimpleRegistry.handler$bao000$setPre(SimpleRegistry:650)
		at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry)
		at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry:72)
		at net.minecraft.util.registry.DefaultedRegistry.set(DefaultedRegistry:28)
		at net.minecraft.util.registry.SimpleRegistry.add(SimpleRegistry:103)
		at net.minecraft.util.registry.Registry.register(Registry:430)
		at com.aqupd.caracalmob.CaracalMain.<clinit>(CaracalMain.java:42)
		... 21 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.client.render.RenderPhase.<clinit>(RenderPhase:125)
	at net.minecraft.client.render.TexturedRenderLayers.<clinit>(TexturedRenderLayers:32)
	at io.github.how_bout_no.outvoted.Outvoted.init(Outvoted.java:69)
	at io.github.how_bout_no.outvoted.OutvotedFabric.onInitialize(OutvotedFabric.java:18)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 12 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectGetUniformLocation(ILjava/lang/CharSequence;)I in sodium.mixins.json:features.shader.MixinShader failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.sodium.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 23 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_128.handler$fnk000$fillPatchouliContext(class_128.java:1521)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$fnk000$fillPatchouliContext(class_128.java:1521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_128.method_560(class_128.java:267)
	at fudge.notenoughcrashes.mixinhandlers.EntryPointCatcher.handleEntryPointError(EntryPointCatcher.java:37)
	at net.minecraft.class_310.redirect$bag000$catchFabricInit(class_310.java:7066)
	at net.minecraft.class_310.<init>(class_310.java:457)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Initialization --
Details:

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 427028360 bytes (407 MiB) / 1082130432 bytes (1032 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce RTX 2080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e87
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7141
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.47
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.47
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.47
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.47
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 40854.01
	Virtual memory used (MB): 34925.82
	Swap memory total (MB): 8154.55
	Swap memory used (MB): 771.00
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		advancementplaques: Advancement Plaques 1.3.1
		advancements-enlarger: Advancements Enlarger 0.2.4
		adventure-platform-fabric: adventure-platform-fabric 4.1.0-SNAPSHOT
		adventurez: AdventureZ 1.2.10
		agape_space: Space Dimensions 0.3.0
		ambientenvironment: Ambient Environment 6.0.21
		apoli: Apoli 1.0.4
		appleskin: AppleSkin mc1.17-2.1.3
		aqupd: Caracal mob 1.17-1.3.0
		aqupdcaracal: Caracal mob 1.17-1.3.11
		architectury: Architectury 2.4.25
		artifality: Artifality 0.3.3
		artofalchemy: Art of Alchemy: Memoriam 1.2.0+1.17.1
		audiooutput: AudioOutput 0.0.4
		balm-fabric: Balm 1.3.0+0
		bclib: BCLib 0.3.1
		better_wandering_trader: Better Wandering Trader 1.7.0
		betterbiomeblend: Better Biome Blend 1.17.0-1.2.9-fabric
		betterend: Better End 0.11.0-pre
		betterf3: BetterF3 1.1.5
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betternether: Better Nether 5.1.3
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.1
		bewitchment: Bewitchment 1.17-3
		blockus: Blockus 2.2.8+1.17.1
		blue_endless_jankson: jankson 1.2.1
		blur: Blur (Fabric) 2.1.0
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.2.3-1.17.1
		calio: Calio 1.0.2
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.1.0
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		carpet: Carpet Mod 1.4.45
		carpet-extra: Carpet Extra 1.4.43
		carpet-tis-addition: Carpet TIS Addition 1.21.0+build.642
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		chesttracker: Chest Tracker 1.0.13
		cleancut: CleanCut 1.17-4.0-fabric
		cleardespawn: Clear Despawn 1.17.1-fabric0.36.1-1.1.1
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.0.38
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		cloud: Cloud 1.5.0
		cloud_commandframework_cloud-brigadier_: cloud-brigadier 1.5.0
		cloud_commandframework_cloud-core_: cloud-core 1.5.0
		cloud_commandframework_cloud-minecraft-extras: cloud-minecraft-extras 1.5.0
		cloud_commandframework_cloud-services_: cloud-services 1.5.0
		clumps: Clumps fabric-1.17.1-7.0.4
		colorutility: ColorUtility 2.0.1
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		completeconfig: CompleteConfig 1.0.0
		confabricate: confabricate 2.1.0-SNAPSHOT+4.1.1
		craftingtweaks: Crafting Tweaks 13.0.0+0
		craftpresence: CraftPresence 1.8.2
		croptopia: Croptopia 1.6.1
		crowdin-translate: CrowdinTranslate 1.3+1.17
		cullleaves: Cull Leaves 2.2.0
		customportalapi: Custom Portal Api 0.0.1-beta39-1.17
		customportals: Custom Portals 2.1.0
		dankstorage: Dank Storage 2.1-1.17.1
		defaultsettings: DefaultSettings 3.0.3
		detailab: Detail Armor Bar 2.0.2+1.17.1
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dml-refabricated: Deep Mob Learning: Refabricated 0.4.4-beta
		dml-refabricated-base: DML: Refabricated - Base 0.4.4-beta
		dml-refabricated-events: DML: Refabricated - Vanilla Events 0.4.4-beta
		dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 0.4.4-beta
		dml-refabricated-rei: DML: Refabricated - REI Integration 0.4.4-beta
		doom: Doom Fabric 4.0.4
		dual_riders: DualRiders 1.0.5
		dungeons_arise: When Dungeons Arise 2.1.47-fabric
		eldritch_mobs: Eldritch Mobs 1.9.2
		emagnet: E Magnet 1.2.3
		enchant_giver: Enchant Giver 1.1.0
		enchantmentdescriptions: Enchantment Descriptions 4.0.1
		expandedstorage: Expanded Storage 7.0.0
		explorerscompass: Explorer's Compass 1.17.1-2.0.1-fabric
		extraorigins: Extra Origins 1.17-6
		fabric: Fabric API 0.37.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.4+2e8bd82f18
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.3+kotlin.1.5.21
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.7.0+2e8bd82f18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricenchantments: Fabric Enchantments 0.4.2
		fabricloader: Fabric Loader 0.11.6
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fallingtree: FallingTree 2.12.1
		fasttransferlib: Fast Transfer Lib 0.5.5
		ferritecore: FerriteCore 3.0.1
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 0.2.21
		food_highlight: FoodHighlight 1.0.1
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.13
		gobber2: Gobber2 2.4.38
		hctm-base: HCTM Base 3.6.2
		healthoverlay: Health Overlay 4.0.1
		heartbond: Heartbond 1.1.0
		hologram-api: Hologram API 0.2.1+1.17.1
		hookshot: Hookshot 18.0
		horseinfo: Horse Info 0.3.0-1.17
		iknowwhatimdoing: I Know What I'm Doing 3.1.0
		impersonate: Impersonate 2.3.3
		incantationem: Incantationem 1.1.2+1.17.1
		inventoryprofilesnext: Inventory Profiles Next 0.9.0
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.1.1
		itemscroller: Item Scroller 0.15.0-dev.20210707.005506
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		justenoughkeys: Just Enough Keys 0.2.2
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kibe: Kibe 1.8.1-BETA+1.17
		kirin: Kirin UI 1.9.1
		krypton: Krypton 0.1.4
		ktdatataglib: KtDataTagLib 1.5.4
		kubejs: KubeJS 1605.3.10-build.9999
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lambdynlights: LambDynamicLights 2.0.2+1.17
		lazydfu: LazyDFU 0.1.2
		libaddict: libaddict 0.3.0
		libblockattributes: LibBlockAttributes 0.8.17003
		libblockattributes_core: LibBlockAttributes (Core) 0.8.17003
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.17003
		libblockattributes_items: LibBlockAttributes (Items) 0.8.17003
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.6+1.17.1
		libninepatch: LibNinePatch 1.1.0
		libra: Libra 0.3.9.2
		lightoverlay: Light Overlay 6.0.0
		lithium: Lithium 0.7.3
		logical_zoom: Logical Zoom 0.0.11
		ltr: LilTaterReloaded 1.1.15+1.17.1
		maelstrom_library: Maelstrom Library 1.2.1-1.17
		magick: Magick: Potions and Pearls 1.0.5
		malilib: MaLiLib 0.10.0-dev.24
		mcda: MC Dungeons Armors 1.7.6
		mcdw: MC Dungeons Weapons 3.4.1
		megane: megane 5.2.0
		megane-base: megane-base 5.2.0
		megane-fabric-transfer: megane-fabric-transfer 5.2.0+1.0.0-3fe3c3f518
		megane-fast-transfer-lib: megane-fast-transfer-lib 5.2.0+0.4.2
		megane-kibe: megane-kibe 5.2.0+1.7.2-BETA-1.17
		megane-lib-block-attributes: megane-lib-block-attributes 5.2.0+0.9.0
		megane-runtime: megane-runtime 5.2.0
		megane-team-reborn-energy: megane-team-reborn-energy 5.2.0+0.1.1
		megane-tech-reborn: megane-tech-reborn 5.2.0+5.0.2-beta-build.38
		megane-vanilla: megane-vanilla 5.2.0+1.17.1
		megane-wireless-networks: megane-wireless-networks 5.2.0+1.1.1
		minecraft: Minecraft 1.17.1
		minecraftcapes: MinecraftCapes Mod 11.0.1
		mining_dims: Mining Dimensions 1.1.11
		mm: Manningham Mills 2.2
		modmenu: Mod Menu 2.0.4
		mods-command: Mods Command 1.0.4
		morevillagers-fabric: MoreVillagersFabric 2.0.4-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		multipart_entities: MultipartEntities 1.1.2-1.17
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		nbtcrafting: NBT Crafting 2.0.16+mc1.17
		nearsightedly: Near-Sightedly 1.2.0
		net_kyori_adventure-api: adventure-api 4.8.1
		net_kyori_adventure-key: adventure-key 4.8.1
		net_kyori_adventure-platform-api: adventure-platform-api 4.0.0-SNAPSHOT
		net_kyori_adventure-text-feature-pagination: adventure-text-feature-pagination 4.0.0-SNAPSHOT
		net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.8.1
		net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.8.1
		net_kyori_examination-api: examination-api 1.1.0
		net_kyori_examination-string: examination-string 1.1.0
		noanglebrackets: NoAngleBrackets 1.1.0
		notenoughcrashes: Not Enough Crashes 3.3.1+1.17
		nyfsquivers: Nyf's Quivers Fabric-0.2.6
		omega-config: OmegaConfig 1.0.8
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		org_objenesis_objenesis: objenesis 3.2
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		org_spongepowered_configurate-yaml: configurate-yaml 4.1.1
		org_yaml_snakeyaml: snakeyaml 1.30-SNAPSHOT
		origins: Origins 1.0.3
		origins-classes: Origins: Classes 1.2.2
		outvoted: Outvoted 2.0.0-alpha.12
		packet_tweaker: Packet Tweaker 0.2.0-1.17-pre1
		packetlogger: Packet Logger 1.0.0
		patchouli: Patchouli 1.17-54-FABRIC
		pehkui: Pehkui 2.3.0+1.14.4-1.17.1
		placeholder-api: Placeholder API 1.1.0+1.17.1
		plantinajar: Plant In A Jar 2.2.2
		playerabilitylib: Pal 1.3.0
		polymer: Polymer 0.1.0-rc.4+1.17.1
		presencefootsteps: Presence Footsteps r32-1.17-rc1
		pugh_lib: Pugh Lib ${version}
		pugh_tools: Pugh Tools ${version}
		qcommon-cfg-core: qcommon-cfg-core 3.3.0
		qcommon-croco: Croco 2.1.1
		quarryplus: QuarryPlus 17.0.347
		quickshulker: Quick Shulker 1.2.2-1.17
		ratsmischief: Rat's Mischief 1.2
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.0.6-beta+build.94
		redbits: Red Bits 1.10.0
		reeses-sodium-options: Reese's Sodium Options 1.1.5
		repurposed_structures: Repurposed Structures 2.3.0+1.17.1
		resourceful_tools: Resourceful Tools 1.1.19
		rhino: Rhino 1605.1.2-build.40
		right-click-clear: Right Click Clear 2.0.3
		roughlyenoughitems: Roughly Enough Items 6.0.268-alpha
		rpgstats: RPGStats 4.1.8+1.17.1
		rswires: RSWires 4.11.2
		runelic: Runelic 3.0.1
		satin: Satin 1.6.0-nightly.1.17-pre3
		schmucks: Schmucks 1.4.0
		seedy-behavior: Seedy Behavior 1.0.1
		server_translations_api: Server Translations API 1.4.5+1.17
		servertick: Server Tick 1.5
		sgui: SGui 1.0.0-rc4+1.17.1
		shulkerboxtooltip: Shulker Box Tooltip 3.0.1+1.17
		shulkerutils: shulkerutils 1.0.4-1.17
		simple_backpack: SimpleBackpack 1.1.18
		sodium: Sodium 0.3.0+build.5
		sodium-extra: Sodium Extra 0.3.3
		somnus: Somnus API 0.0.12-1.17
		spruceui: SpruceUI 3.2.0+1.17
		starlight: Starlight 1.0.0-RC3+fabric.2b7d7ae
		statuseffecttimer: Status Effect Timer 1.0.3
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 5.0.6-beta+build.94
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		the_aether: The Aether 1.17.1-1.5.0
		things: Things 0.2.3
		toms_storage: Tom's Simple Storage Mod 1.1.13-1.17.1
		toolstats: Tool Stats 2.0.1
		torcherino: Torcherino 15.1.0-alpha.3
		torohealth: ToroHealth Damage Indicators 1.17.1-fabric-12
		trinkets: Trinkets 3.0.2
		truerooms: True Secret Rooms 1.1.5
		universal-graves: Universal Graves 1.0.8+1.17.1
		voidtotem: Void Totem (Fabric) 1.17.0-1.0.0
		voidz: VoidZ 1.0.5
		ward_blocks: Ward Blocks 1.1.7
		waterdripsound: Drip Sounds 1.17-0.2.2
		waystones: Waystones 2.0.3
		whereisit: Where Is It 1.13.3
		winged: Winged Mod 1.17.1-3.0.0
		wirelessnetworks: Wireless Networks 1.1.2
		wthit: wthit 3.8.1
		xaerominimap: Xaero's Minimap 21.15.1
		xaeroworldmap: Xaero's World Map 1.16.1
		yungsapi: YUNG's API 1.17-Fabric-15
	Launched Version: 1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
	Suspected Mods: Torcherino (torcherino), Outvoted (outvoted), Fabric Loader (fabricloader), Expanded Storage (expandedstorage)

### Iris and Minecraft Version

latest iris and mc 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

10

### What is your GPU?

2080 rtx

### Java Version

16

**Comment by AlsoNiko** [comment]
Iris already bundles sodium, please remove it

**Comment by red2blue** [comment]
OH MY GOD.

DUH.

You just solved hours and hours  I spent of debugging my modpack.
