### ISSUE TITLE
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'iris'! Exit-Code: -1

### ISSUE THREAD

**Issue by Kibo186** [IrisShaders/Iris#789]
### Iris and Minecraft Version

iris-mc1.16.5-1.1.1.jar 1.16.5

### Are you running Sodium along with Iris?

Yes

### Operating System

W10

### What is your GPU?

Nvidia GTX 970

### Java Version

1.8.0_51

### Reproduction Steps

Installed Iris in th "Fabric Adventure Pack" Modpack through Curseforge
Client starts
Click on Play -> crash after 10 seconds loading time

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 8/22/21 7:34 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'iris'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.IllegalStateException: You do not have a compatible version of Sodium installed! You have 0.1.0 but 0.2.0+IRIS3 is expected
	at net.coderbot.iris.Iris.lambda$onInitializeClient$0(Iris.java:66)
	at net.coderbot.iris.Iris$$Lambda$6216/937704292.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.coderbot.iris.Iris.onInitializeClient(Iris.java:59)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$6168/1169326739.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1571244960 bytes (1498 MB) / 2515533824 bytes (2399 MB) up to 4772593664 bytes (4551 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5120m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		adorn: Adorn 1.13.0+1.16.5
		adventurez: AdventureZ 1.2.2
		amecsapi: Amecs API 1.1.4+mc1.16.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		anti_mob_cheese: Anti Mob Cheese 1.1.2
		aputils: AP Utils 1.0.4
		architects_palette: Architect's Palette Fabric 1.0
		architectury: Architectury 1.17.20
		artifice: Artifice 0.14.6+1.16.5
		autoconfig1u: Auto Config v1 Updated 3.3.1
		battletowers: Battle Towers 3.3.4-1.16.4
		bebooks: Better Enchanted Books 1.2.8
		bettercaves: YUNG's Better Caves 1.16.5-1.2
		betterend: Better End 0.9.6-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.1
		betternether: Better Nether 5.0.7
		bettersodiumvideosettingsbutton: Better Sodium Video Settings Button 1.0.3.1
		betterstrongholds: YUNG's Better Strongholds 1.16.5-1.0
		biome_locator: Biome Locator 1.0.0
		biomemakeover: Biome Makeover 1.16.5-1.3.8
		blockus: Blockus 2.1.5+1.16.5
		blue_endless_jankson: jankson 1.2.0
		bowinfinityfix: Bow Infinity Fix rv9
		byg: BYG 1.1.8
		cardinal-components: Cardinal Components API 2.8.3
		cardinal-components-base: Cardinal Components API (base) 2.8.3
		cardinal-components-block: Cardinal Components API (blocks) 2.8.3
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.3
		cardinal-components-entity: Cardinal Components API (entities) 2.8.3
		cardinal-components-item: Cardinal Components API (items) 2.8.3
		cardinal-components-level: Cardinal Components API (world saves) 2.8.3
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.3
		cardinal-components-util: Cardinal Components API (utilities) 2.8.3
		cardinal-components-world: Cardinal Components API (worlds) 2.8.3
		cavebiomes: Cave Biomes 0.6.2
		chainmail: Chainmail 0.5.0
		chains: Chains-Link 1.16.2-2.0.1
		charm: Charm 2.3.2
		chat_heads: Chat Heads 0.2.2+1.16.2
		chunky: Chunky 1.2.54
		cleancut: CleanCut mc1.16-2.1-fabric
		cleanview: CleanView 1.16.5-v1-fabric
		cloth-api: Cloth API 1.5.50
		cloth-armor-api-v1: Cloth Armor API v1 1.5.50
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.50
		cloth-common-events-v1: Cloth Common Events v1 1.5.50
		cloth-config-lite: cloth-config-lite 1.0.4
		cloth-config2: Cloth Config v4 4.11.26
		cloth-datagen-api-v1: Cloth Datagen v1 1.5.50
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.50
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.5.50
		cloth-scissors-api-v1: Cloth Scissors API v1 1.5.50
		cloth-utils-v1: Cloth Utils v1 1.5.50
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compressedblocks: Compressed Blocks 1.0
		controlling: Controlling For Fabric 1.1.2
		cosmetic-armor: Cosmetic Armor 1.0.0
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		craftpresence: CraftPresence 1.7.6
		crawl: Crawl 0.8.4
		curios: Curios API 0.0.13-1.16.5
		desolation: Desolation 1.1.1
		disable_elytra_flight: Disable Elytra Flight 1.0.0
		disable_riptide: Disable Riptide 1.0.0
		disguiselib: Disguise Library 1.0.3
		divine_missions: Divine Missions 1.0.0
		dynocaps: DynoCaps 1.7.3
		editsign: Edit Sign 2.2.0
		eldritch_mobs: Eldritch Mobs 1.8.0
		expandedstorage: ExpandedStorage 5.6.33
		extradoors: ExtraDoors 1.8.2-1.16.2
		fabric: Fabric API 0.34.6+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.10+3661eaa17d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-language-scala: Fabric Language Scala 1.0.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.6
		fallflyinglib: FallFlyingLib 1.1.0
		fancymenu: FancyMenu 2.0.5
		fatxporbs: Fat Experience Orbs 0.0.9
		fiber: fiber 0.23.0-2
		flan: Flan 1.16.5-1.5.4
		ftbguilibrary: FTB GUI Library 1605.2.1.41
		ftbquests: FTB Quests 1605.2.1-build.39
		geckolib3: Geckolib 3.0.22
		globalspawn: GlobalSpawn 1.1.2-1.16.5
		go-fish: Go Fish 1.2.3-beta-1.16.5
		goldensteak: Goldensteak 1.0.2
		grindenchantments: Grind Enchantments 1.1.3+1.16.3
		headshot: Headshot 1.0.6
		iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
		identity: Identity 1.13.2-1.16.5
		iknowwhatimdoing: I Know What I'm Doing 3.0.0
		inventoryhud: Inventory HUD + 3.2.2
		invtrashslot: InvTrashSlot 1.0.2
		io_github_onyxstudios_cardinal-components-api: Cardinal-Components-API 2.8.2
		iris: Iris 1.1.1
		itemfilters: Item Filters 1605.2.4-build.30
		itemflexer: ItemFlexer 1.1.4
		itemsfromtext: Items From Text 1.6.2
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kirin: Kirin UI 1.7-1.16.2
		konkrete: Konkrete 1.1.7
		kubejs: KubeJS 1605.3.8-build.198
		kyrptconfig: Kytpt Config 1.1.6-1.16
		lambdynlights: LambDynamicLights 1.3.4+1.16
		libblockattributes: LibBlockAttributes 0.8.8
		libblockattributes_core: LibBlockAttributes (Core) 0.8.8
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.8
		libblockattributes_items: LibBlockAttributes (Items) 0.8.8
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.4.0+1.16.5
		library_of_exile: Library of Exile 1.0.14
		libstructure: LibStructure 1.5
		lootbeams: Lootbeams 2.0.2
		lootcrates: Loot Crates 1.1.2
		mambience: MAmbience 3.0.0+1.16.5
		mcda: MC Dungeons Armors 1.5.0
		mcsa: MC Story Mode Armor 2.3.2
		microconfig: Microconfig 2.0.1
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.2
		mmorpg: Age of Exile 2.1.2
		mobz: MobZ 2.4.6
		modmenu: Mod Menu 1.16.8
		mostructures: Mo' Structures 1.1.1+mc.1.16.5
		mousewheelie: Mouse Wheelie 1.7.3+mc1.16.5
		nomoreglowingpots: No More Glowing Pots 1.0.2
		omega-config: OmegaConfig 1.0.4
		org_aeonbits_owner_owner: owner 1.0.12
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		origins: Origins 0.7.1
		overworld_two: Overworld 2 1.0.4
		patchouli: Patchouli 1.16.4-50-FABRIC
		petowner: Pet Owner 1.8.0-1.16.5+
		phosphor: Phosphor 0.7.1+build.11
		playerabilitylib: Pal 1.2.1
		pling: Pling 1.3.0
		polymorph: Polymorph 0.0.9-1.16.5
		presencefootsteps: Presence Footsteps r29+1.16.4
		programmerartinjector: Programmer Art Injector 1.2.1
		quickshulker: Quick Shulker 1.1.14-1.16
		randompatches: RandomPatches 1.16.1-0.0.0.5-fabric
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		repurposed_structures: Repurposed Structures 1.16.5-1.10.5-fabric
		rhino: Rhino 1.7.13-build.23
		roughlyenoughitems: Roughly Enough Items 5.12.235
		roughlyenoughitems-api: REI (API) 5.12.235
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.12.235
		roughlyenoughitems-runtime: REI (Runtime) 5.12.235
		secretrooms: Secret Rooms 0.9.3+1.16.5
		sgod: Save Gear on Death 0.0.2
		shulkerutils: shulkerutils 1.0.1-1.16
		simplevoidworld: Simple Void World 4.0.0
		sodium: Sodium 0.1.0
		someforgepatchesported: Some Forge Patches Ported 1.0.0
		spruceui: SpruceUI 2.0.4+1.16
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		structure-helpers: Structure Helpers 3.0.0
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.3
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.4
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrestria: Terrestria 2.2.0
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.6
		toms_storage: Tom's Simple Storage Mod 1.1.10
		trapexpansion: Trap Expansion 1.3.2
		traverse: Traverse 3.3.2
		tweed: Tweed 3.0.0-beta.26
		voyager: Voyager 1.0.0
		walljump: Wall-Jump! 1.3.3+1.16.1
		waystones: Waystones 2.0.0
		world_of_exile: World of Exile 1.2.4
		worldborderfix: Worldborderfix 1.1-SNAPSHOT-fabric-1.16.5
		worldedit: WorldEdit 7.2.4+5723-e3bfc64
		wthit: wthit 2.5.0
		xaerominimap: Xaero's Minimap 21.10.0.4
		xaeroworldmap: Xaero's World Map 1.14.1
		yungsapi: YUNG's API 1.16.5-Fabric-5
		zoob: Monster Of The Ocean Depths 3.0.0
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.11.6-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

**Comment by NoComment1105** [comment]
Remove sodium 0.1.0.iris bundles its own

**Comment by Kibo186** [comment]
> 
> 
> Remove sodium 0.1.0.iris bundles its own

That worked. thank you!

**Comment by NielsGx** [comment]
> 
> 
> Remove sodium 0.1.0.iris bundles its own

It bundles Sodium 0.3.0, but now there's sodium 0.3.1.
Can you do a new Iris build with it, or is it possible to replace it with 0.3.1 myself ? Or does it needs special patches from you?
Thanks

**Comment by IMS212** [comment]
We have testing builds for Sodium 0.3.1 support on our discord, however you cannot use normal 0.3.1. 0.3.1 will come with Iris 1.1.2, unless there are other issues.
