### ISSUE TITLE
Crash on a server custom modality (java.util.ConcurrentModificationException)

### ISSUE THREAD

**Issue by G1ov4** [IrisShaders/Iris#811]
### Iris and Minecraft Version

iris-0.11.5-1.16.5 for Minecraft 1.16.5

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce RTX 2060

### Java Version

Java 8

### Reproduction Steps

1. Play Waraccademy server (mc.waraccademy.it) metropolis modality

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Why did you do that?

Time: 30/08/21 16.44
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:394)
	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.renderShadows(DeferredWorldRenderingPipeline.java:688)
	at net.minecraft.class_761.handler$zdb000$iris$renderTerrainShadows(class_761.java:5649)
	at net.minecraft.class_761.method_22710(class_761.java:1149)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:394)
	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.renderShadows(DeferredWorldRenderingPipeline.java:688)
	at net.minecraft.class_761.handler$zdb000$iris$renderTerrainShadows(class_761.java:5649)
	at net.minecraft.class_761.method_22710(class_761.java:1149)
	at net.minecraft.class_757.method_3188(class_757.java:727)

-- Affected level --
Details:
	All players: 7 total; [class_746['Giov4_'/1389971, l='ClientLevel', x=8.50, y=65.00, z=8.50], class_745['BohGVNG'/1382533, l='ClientLevel', x=47.70, y=57.00, z=65.30], class_745['iLaxeer_'/1283088, l='ClientLevel', x=26.30, y=47.43, z=73.30], class_745['Im_Not_Al3'/1374215, l='ClientLevel', x=27.70, y=47.43, z=73.30], class_745['Complicato'/1147721, l='ClientLevel', x=26.49, y=57.43, z=66.59], class_745['TheBeat3r4963'/1372821, l='ClientLevel', x=23.55, y=57.00, z=67.28], class_745['DanieloPazzurdo'/1378349, l='ClientLevel', x=42.95, y=57.80, z=55.44]]
	Chunk stats: Client Chunk Cache: 65536, 7
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 16 game time, 16 day time
	Server brand: Waterfall <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7461678104 bytes (7116 MB) / 8959033344 bytes (8544 MB) up to 17179869184 bytes (16384 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: iris-fabric-loader-0.11.5-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 471.41, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3800X 8-Core Processor
```

### Additional context

I know that this is not very useful 'cause you don't actually know what's happening on the server and what the plugins are doing, but I hope that maybe the crash report will be enough to understand it.

**Comment by AlsoNiko** [comment]
We need a full log file as well

**Comment by G1ov4** [comment]
[Here it is](https://marspaste.com/raw/log-28883)

**Comment by coderbot16** [comment]
This seems to have happened while iterating over the world block entity list:

https://github.com/IrisShaders/Iris/blob/d1fc7aaa9b51e861e280cfb5f6183578920801dc/src/main/java/net/coderbot/iris/pipeline/ShadowRenderer.java#L394

We should probably use a simpler approach to block entity rendering as we do on 1.17, which would avoid iterating over the world's overall block entities list.

**Comment by coderbot16** [comment]
Resolved with the merge of https://github.com/IrisShaders/Iris/pull/1280
