### ISSUE TITLE
sodium

### ISSUE THREAD

**Issue by fassdragon2** [IrisShaders/Iris#818]
### What happened?

i launched 1.17 fabric with iris and sodium-fabric-mc1.17.1-0.3.2+build.7 and it crashes as soon as the game starts

### Relevant log output

```shell
i do not know what is relevant so here is the crash report.

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 9/2/21, 3:25 PM
Description: Initializing game

java.lang.NullPointerException: Cannot invoke "net.coderbot.iris.pipeline.PipelineManager.getPipeline()" because the return value of "net.coderbot.iris.Iris.getPipelineManager()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17+build.13)
	at net.minecraft.client.render.GameRenderer.isPhase(GameRenderer:9237)
	at net.minecraft.client.render.GameRenderer.handler$cig000$iris$overridePositionShader(GameRenderer:9018)
	at net.minecraft.client.render.GameRenderer.getPositionShader(GameRenderer)
	at com.mojang.blaze3d.systems.RenderSystem.setShader(RenderSystem:1137)
	at net.minecraft.client.render.WorldRenderer.renderStars(WorldRenderer:645)
	at net.minecraft.client.render.WorldRenderer.<init>(WorldRenderer:278)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:575)
	at net.minecraft.client.main.Main.main(Main:179)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_757.isPhase(class_757.java:9237)
	at net.minecraft.class_757.handler$cig000$iris$overridePositionShader(class_757.java:9018)
	at net.minecraft.class_757.method_34539(class_757.java)
	at com.mojang.blaze3d.systems.RenderSystem.setShader(RenderSystem.java:1137)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$blp000$fillPatchouliContext(class_128.java:1521)
	at net.minecraft.class_128.<init>(class_128.java:36)
	at net.minecraft.class_128.method_560(class_128.java:266)
	at net.minecraft.client.main.Main.main(Main.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Initialization --
Details:

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 460313512 bytes (438 MiB) / 926941184 bytes (884 MiB) up to 4292870144 bytes (4094 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2070 Super
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e91
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7196
	Graphics card #1 name: Intel(R) UHD Graphics 630
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9bc5
	Graphics card #1 versionInfo: DriverVersion=27.20.100.8935
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 29963.74
	Virtual memory used (MB): 21568.64
	Swap memory total (MB): 13824.00
	Swap memory used (MB): 296.21
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4094m
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.10
		adorn: Adorn 2.0.0+1.17
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		apoli: Apoli 1.0.4
		architectury: Architectury 2.5.27
		artifice: Artifice 0.15.3+21w07a
		autoconfig1u: Auto Config v1 Updated 3.3.1
		automated_crafting: Automated Crafting 1.3.24+MC1.17-1.17.1
		autosmeltenchant: AutosmeltEnchant 1.1.0
		betterbeds: Better Beds 1.2.0
		betterdroppeditems: Better Dropped Items 1.3.0-1.17
		bitsandchisels: BitsAndChisels 2.5.0
		blue_endless_jankson: jankson 1.2.1
		bno: Basic Nether Ores 1.17-6.0.0-Fabric
		boostedbrightness: Boosted Brightness 2.1.0
		calio: Calio 1.0.2
		cardinal-components-base: Cardinal Components API (base) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
		carpet: Carpet Mod 1.4.40
		charm: Charm 3.3.0
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.0.38
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.12.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		complete_bone_meal: Complete Bone Meal 1.2.0
		conjuring: Conjuring 1.0.7
		crowdin-translate: CrowdinTranslate 1.3+1.17
		ctm: ConnectedTexturesMod for Fabric 0.5.1+1.17
		custom-crosshair-mod: Custom Crosshair Mod 1.3.4-fabric
		custom_hud: CustomHud 1.2.3+1.17
		diggusmaximus: Diggus Maximus 1.4.5-1.17
		dynamicfps: Dynamic FPS 2.0.4
		ec-core: Essential Commands Core 1.0.0-mc1.17
		effect: Effect Enchants 1.0.0
		enchantedtooltips: Enchanted ToolTips 1.3.5-1.17
		entityculling: EntityCulling-Fabric 1.3.3
		essential_commands: Essential Commands 0.16.1-mc1.17
		ezpas: Ezpas 1.2.1
		fabric: Fabric API 0.36.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d03d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c03d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.3+kotlin.1.5.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b44633d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabricloader: Fabric Loader 0.11.6
		fabrishot: Fabrishot 1.5.0
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fiber: fiber 0.23.0-2
		flight_rings: Flight Rings 1.6
		gbfabrictools: GBfabrictools 1.2.2+1.16
		gildedarmor: Gilded Armor 1.3.0+fabric-1.17.1
		goldenhoppers: Golden Hoppers 1.1.0
		haema: Haema 1.7.3
		impaled: Impaled 1.0.1
		indium: Indium 1.0.0+mc1.17.1
		infinityfix: Infinity Fix 1.1.0
		invview: InvView 1.4.3-1.17+
		iris: Iris 1.1.1
		ironchests: Iron Chests for Fabric 1.0.3
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 16
		krypton: Krypton 0.1.3
		ktrl: Kontrolo 1.5.0+1.17
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lambdynlights: LambDynamicLights 2.0.1+1.17
		lazydfu: LazyDFU 0.1.2
		lchunkloader: Literally Chunk Loader 2.0.3
		libblockattributes: LibBlockAttributes 0.9.0
		libblockattributes_core: LibBlockAttributes (Core) 0.9.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.0
		libblockattributes_items: LibBlockAttributes (Items) 0.9.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.0+1.17
		libmultipart: LibMultiPart 0.6.0
		libnetworkstack: Lib Network Stack 0.5.0
		libninepatch: LibNinePatch 1.1.0
		litematica: Litematica 0.0.0-dev.20210616.033538
		lithium: Lithium 0.7.4
		lowfire: Low Fire 1.17-2.0.0
		malilib: MaLiLib 0.10.0+dev.22
		minecraft: Minecraft 1.17
		mm: Manningham Mills 2.2
		moborigins: Mob Origins 1.5.0
		mocolors: Mo' Colors 1.2.0
		modmenu: Mod Menu 2.0.2
		mostructures: Mo' Structures 1.2.1-1.17
		multisleep: Multiplayer Sleep 1.0
		nofade: No Fade 1.17-2.0.0
		notenoughcrashes: Not Enough Crashes 3.3.1+1.17
		omega-config: OmegaConfig 1.0.8
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		origins: Origins 1.0.3
		origins-classes: Origins: Classes 1.2.2
		overloadedarmorbar: Overloaded Armor Bar 5.0.0-fabric
		overpoweredmending: OverpoweredMending 2.2.3
		owo: OwO 0.1.1
		patchouli: Patchouli 1.17-55-FABRIC-SNAPSHOT
		placeholder-api: Placeholder API 1.1.0+1.17.1
		playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
		prefab: Prefab 2.0.2.1
		puzzle: Puzzle 0.3.0
		puzzle-base: Puzzle 0.3.0
		puzzle-blocks: Puzzle Blocks 0.3.0
		puzzle-gui: Puzzle GUI 0.3.0
		puzzle-models: Puzzle Models 0.3.0
		puzzle-splashscreen: Puzzle Splash Screen 0.3.0
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reeses-sodium-options: Reese's Sodium Options 1.2.0
		replaymod: Replay Mod 1.17.1-2.6.1
		roughlyenoughitems: Roughly Enough Items 6.0.279-alpha
		rpgstats: RPGStats 4.1.3
		satin: Satin 1.6.1
		secretrooms: Secret Rooms 1.0.0+1.17
		sgui: SGui 1.0.0-rc1-1.17
		shulkerboxtooltip: Shulker Box Tooltip 3.0.1+1.17
		shulkerutils: shulkerutils 1.0.1-1.17
		simple_pipes: SimplePipeTest 0.6.1
		simple_pipes_dep_container: SimplePipeTest (Dependency Container) 0.6.1
		slight-gui-modifications: 'Slight' GUI Modifications 2.0.0
		smoothboot: Smooth Boot 1.16.5-1.6.0
		sodium: Sodium 0.3.2+build.7
		somnus: Somnus API 0.0.11-1.17.0
		spellbound: Spellbound 1.4.0
		spruceui: SpruceUI 3.2.0+1.17
		stacc: Stacc 1.0.1
		starlight: Starlight 1.0.0+fabric.73f6d37
		truerooms: True Secret Rooms 1.1.5
		tweakeroo: Tweakeroo 0.10.0-dev.20210710.155746
		upgradedshulkers: Upgraded Shulkers 1.0.1-1.17
		wi_zoom: WI Zoom 1.3-MC1.17
		winged: Winged Mod 1.17-3.0.0-beta.2
		wthit: wthit 3.8.1
		xaerobetterpvp: Better PVP Mod 21.16.0
		xaeroworldmap: Xaero's World Map 1.17.0
		xlpackets: XLPackets 1.1
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2070 Super/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.96, NVIDIA Corporation
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 16x Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
	Suspected Mods: Fabric Loader (fabricloader)
```

### Iris and Minecraft Version

iris-mc1.17-1.1.1 (2).jar 1.17 fabric

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 2070 Super

### Java Version

Java 16

**Comment by IMS212** [comment]
Please remove sodium, as Iris bundles it.

**Comment by fassdragon2** [comment]
ok

**Comment by fassdragon2** [comment]
one other thing when i use shaders and a piston pushes a block it goes invisible what should i do?

**Comment by IMS212** [comment]
I believe this issue has been fixed in development builds.

**Comment by IMS212** [comment]
None right now, you just have to wait for a new release.

**Comment by fassdragon2** [comment]
ok thanks

**Comment by fassdragon2** [comment]
is it fixed now the slimeblocks?
