### ISSUE TITLE
Iris should a workaround for when OptiFine has set the maxFps to zero in options.txt

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#831]
This is crashing people's games when they try to switch to Iris with a divide by zero error:

```
java.lang.ArithmeticException: / by zero
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer.java:1142) ~[intermediary-iris-fabric-loader-0.11.5-1.16.5.jar:?]
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:727) ~[intermediary-iris-fabric-loader-0.11.5-1.16.5.jar:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:546) ~[intermediary-iris-fabric-loader-0.11.5-1.16.5.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1048) ~[intermediary-iris-fabric-loader-0.11.5-1.16.5.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:681) [intermediary-iris-fabric-loader-0.11.5-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-iris-fabric-loader-0.11.5-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [iris-loader-0.11.5.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [iris-loader-0.11.5.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [iris-loader-0.11.5.jar:?]
```

**Comment by coderbot16** [comment]
Reopened until the next release & tagged as fixed
