### ISSUE TITLE
Pipeline error. 

### ISSUE THREAD

**Issue by Hugelham** [IrisShaders/Iris#835]
### Iris and Minecraft Version

iris-mc.1.17-1.1.1 - Mc is 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce RTX 3080 ti Founders edition.

### Java Version

Java 16

### Reproduction Steps

I just had started downloading a bunch of mods, from here https://gist.github.com/SheepCommander/aac88c0ab4a6455756e08c3db3783321

I got to a point where it worked, added a few more mods, and then it didn't work anymore. 
![image](https://user-images.githubusercontent.com/90125053/132116237-4e6da81f-3916-4ec5-ba8e-c9f03da14a5a.png)

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 9/4/21, 11:10 PM
Description: Initializing game

java.lang.NullPointerException: Cannot invoke "net.coderbot.iris.pipeline.PipelineManager.getPipeline()" because the return value of "net.coderbot.iris.Iris.getPipelineManager()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.52)
	at net.minecraft.client.render.GameRenderer.isPhase(GameRenderer:5263)
	at net.minecraft.client.render.GameRenderer.handler$bkm000$iris$overridePositionShader(GameRenderer:5044)
	at net.minecraft.client.render.GameRenderer.getPositionShader(GameRenderer)
	at com.mojang.blaze3d.systems.RenderSystem.setShader(RenderSystem:1137)
	at net.minecraft.client.render.WorldRenderer.renderStars(WorldRenderer:645)
	at net.minecraft.client.render.WorldRenderer.<init>(WorldRenderer:278)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:573)
	at net.minecraft.client.main.Main.main(Main:179)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_757.isPhase(class_757.java:5263)
	at net.minecraft.class_757.handler$bkm000$iris$overridePositionShader(class_757.java:5044)
	at net.minecraft.class_757.method_34539(class_757.java)
	at com.mojang.blaze3d.systems.RenderSystem.setShader(RenderSystem.java:1137)
	at net.minecraft.class_761.method_3293(class_761.java:645)
	at net.minecraft.class_761.<init>(class_761.java:278)
	at net.minecraft.class_310.<init>(class_310.java:573)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 312619424 bytes (298 MiB) / 570425344 bytes (544 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 20
	Graphics card #0 name: Intel(R) UHD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9bc5
	Graphics card #0 versionInfo: DriverVersion=30.0.100.9684
	Graphics card #1 name: NVIDIA GeForce RTX 3080 Ti
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2208
	Graphics card #1 versionInfo: DriverVersion=30.0.14.7141
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 42121.18
	Virtual memory used (MB): 33289.96
	Swap memory total (MB): 9503.16
	Swap memory used (MB): 1058.66
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.10
		advancednbttooltip: Advanced NBT Tooltips 1.6.0+build.4-1.17
		amecsapi: Amecs API 1.1.4+mc21w16a
		appleskin: AppleSkin mc1.17-2.0.0
		architectury: Architectury 2.5.27
		armor_hud: BerdinskiyBear's ArmorHUD 0.3.4
		atmosfera: Atmosfera 2.0.0+mc1.17
		autoconfig1u: Auto Config v1 Updated 3.3.1
		axolotlitemfix: Axolotl Item Fix 1.1.2
		bettercontrols: Better Controls 1.2.0
		betterf3: BetterF3 1.1.5
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v5 5.0.38
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_squareup_moshi_moshi: moshi 1.9.2
		com_squareup_okio_okio: okio 1.16.0
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		connected-doors: Connected Doors 1.1+1.17
		crowdin-translate: CrowdinTranslate 1.3+1.17
		cullleaves: Cull Leaves 2.2.0
		dashloader: DashLoader 2.0
		dynamicfps: Dynamic FPS 2.0.5
		easiercrafting: EasierCrafting 1.17.1-fabric0.36.1-1.6.7
		easiervillagertrading: EasierVillagerTrading 1.17.1-fabric0.36.1-1.5.4
		entityculling: EntityCulling-Fabric 1.3.3
		fabric: Fabric API 0.37.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57718
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57718
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		fallingleaves: Falling Leaves 1.7.2+1.17
		ferritecore: FerriteCore 3.0.3
		fpsdisplay: FPS-Display 1.4.1+1.17
		fvt: Flour's Various Tweaks 1.7.0-mc1.17.1
		gbfabrictools: GBfabrictools 1.3.4+1.17
		hydrogen: Hydrogen 0.3
		illuminations: Illuminations 1.7
		indium: Indium 1.0.0+mc1.17.1
		io_activej_activej-codegen: activej-codegen 4.3
		io_activej_activej-serializer: activej-serializer 4.3
		iris: Iris 1.1.1
		java: OpenJDK 64-Bit Server VM 16
		jumpoverfences: JumpOverFences 1.16-0.0.3
		kirin: Kirin UI 1.8.7-1.17
		krypton: Krypton 0.1.4
		lazydfu: LazyDFU 0.1.2
		litematica: Litematica 0.0.0-dev.20210713.103711
		lithium: Lithium 0.7.4
		malilib: MaLiLib 0.10.0+dev.22
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.2
		modmenu: Mod Menu 2.0.9
		modupdater: ModUpdater 1.1.11+1.16.2-rc2
		mousewheelie: Mouse Wheelie 1.7.3+mc1.17.1-pre1
		notenoughcrashes: Not Enough Crashes 3.4.4+1.17
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		org_slf4j_slf4j-api: slf4j-api 1.7.29
		org_yaml_snakeyaml: snakeyaml 1.27
		presencefootsteps: Presence Footsteps r31-1.17-rc1
		shulkerboxtooltip: Shulker Box Tooltip 3.0.0+1.17
		smoothboot: Smooth Boot 1.16.5-1.6.0
		sodium: Sodium 0.3.0+IRIS2
		stepup: StepUp 1.17.1-fabric0.36.1-1.1
		tweed: Tweed 3.0.0-beta.26
		veinminer4bukkit: VeinMiner 4 Bukkit 1.17.9
		voxelmap: VoxelMap 1.10.15
		worldedit: WorldEdit 7.2.6-beta-01+1415e6f
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.41, NVIDIA Corporation
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 20x Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
	Suspected Mods: Fabric Loader (fabricloader)
```

**Comment by IMS212** [comment]
Please narrow down the list to a specific mod causing issues.
