### ISSUE TITLE
Issues creating the patched_shaders folder on Windows in some cases

### ISSUE THREAD

**Issue by Miss-Corruption** [IrisShaders/Iris#928]
### What happened?

Under certain circumstances Iris fails to create the patched_shaders folder and thus fails to load every shader. A workaround to this is deleting the patched_shaders folder in .minecraft.

### Relevant log output

```shell
[18:36:00] [Render thread/ERROR]: Couldn't load NewWorldRenderingPipeline, falling back to vanilla shaders.
java.lang.RuntimeException: java.nio.file.DirectoryNotEmptyException: C:\Users\fhfz3\AppData\Roaming\.minecraft\patched_shaders\config
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.lambda$new$0(NewWorldRenderingPipeline.java:138) ~[iris-and-sodium-mc1.17-1.1.2+build.9.jar:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:134) ~[iris-and-sodium-mc1.17-1.1.2+build.9.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:429) ~[iris-and-sodium-mc1.17-1.1.2+build.9.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:32) [iris-and-sodium-mc1.17-1.1.2+build.9.jar:?]
	at net.minecraft.class_761.handler$zee000$iris$beginWorldRender(class_761.java:6821) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1026) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:810) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1112) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
Caused by: java.nio.file.DirectoryNotEmptyException: C:\Users\fhfz3\AppData\Roaming\.minecraft\patched_shaders\config
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:272) ~[?:?]
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105) ~[?:?]
	at java.nio.file.Files.delete(Files.java:1146) ~[?:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.lambda$new$0(NewWorldRenderingPipeline.java:136) ~[iris-and-sodium-mc1.17-1.1.2+build.9.jar:?]
	... 20 more
[18:36:01] [Render thread/INFO]: Destroying pipeline OVERWORLD
[18:36:01] [Render thread/INFO]: Using shaderpack: Sildurs Vibrant Shaders v1.29 Medium.zip
[18:36:01] [Render thread/INFO]: Creating pipeline OVERWORLD
[18:36:01] [Render thread/ERROR]: Couldn't load NewWorldRenderingPipeline, falling back to vanilla shaders.
java.lang.RuntimeException: java.nio.file.DirectoryNotEmptyException: C:\Users\fhfz3\AppData\Roaming\.minecraft\patched_shaders\config
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.lambda$new$0(NewWorldRenderingPipeline.java:138) ~[iris-and-sodium-mc1.17-1.1.2+build.9.jar:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:134) ~[iris-and-sodium-mc1.17-1.1.2+build.9.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:429) ~[iris-and-sodium-mc1.17-1.1.2+build.9.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:32) [iris-and-sodium-mc1.17-1.1.2+build.9.jar:?]
	at net.minecraft.class_761.handler$zee000$iris$beginWorldRender(class_761.java:6821) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1026) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:810) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1112) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
Caused by: java.nio.file.DirectoryNotEmptyException: C:\Users\fhfz3\AppData\Roaming\.minecraft\patched_shaders\config
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:272) ~[?:?]
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105) ~[?:?]
	at java.nio.file.Files.delete(Files.java:1146) ~[?:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.lambda$new$0(NewWorldRenderingPipeline.java:136) ~[iris-and-sodium-mc1.17-1.1.2+build.9.jar:?]
	... 20 more
```

### Iris and Minecraft Version

Iris 1.1.2 for Minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

AMD Radeon Vega 7

### Java Version

Java 16

**Comment by IMS212** [comment]
As an extension to this, there's no reason Iris should be creating patched_shaders outside of a development environment, as it's not useful in almost any cases now.

**Comment by Miss-Corruption** [comment]
Another extension: This bug can be reproduced by setting the `shaderpacks` folder to `read-only`. Deleting the `patched_shaders` folder in `.minecraft `doesn't help in that case.
