### ISSUE TITLE
AoF4 Crashes when clicking "Tools" in the Creative Menu with Iris installed.

### ISSUE THREAD

**Issue by AlienXAXS** [IrisShaders/Iris#938]
### Iris and Minecraft Version

Iris 1.1.2+build.9 for Minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Win10

### What is your GPU?

ASUS STRIX RTX 3090

### Java Version

16

### Reproduction Steps

1. Install All Of Fabric 4
2. Install iris-and-sodium-mc1.17-1.1.2+build.9.jar
3. Start a new world with cheats, enable Creative Mode
4. Click the "Tools" button on the creative mode inventory screen
5. Crash

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 10/20/21, 8:22 PM
Description: Rendering item

java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "quads" is null
	at net.minecraft.class_918.method_23182(class_918.java:5048)
	at net.minecraft.class_918.method_23179(class_918.java:170)
	at net.minecraft.class_918.method_4021(class_918.java:306)
	at net.minecraft.class_918.method_4026(class_918.java:349)
	at net.minecraft.class_918.method_36543(class_918.java:339)
	at net.minecraft.class_918.method_27951(class_918.java:335)
	at net.minecraft.class_465.method_2385(class_465.java:265)
	at net.minecraft.class_465.method_25394(class_465.java:123)
	at net.minecraft.class_485.method_25394(class_485.java:43)
	at net.minecraft.class_481.method_25394(class_481.java:690)
	at net.minecraft.class_757.method_3192(class_757.java:874)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_918.method_23182(class_918.java:5048)
	at net.minecraft.class_918.method_23179(class_918.java:170)
	at net.minecraft.class_918.method_4021(class_918.java:306)

-- Item being rendered --
Details:
	Item Type: painter
	Item Damage: 0
	Item NBT: {Damage:0}
	Item Foil: false
Stacktrace:
	at net.minecraft.class_918.method_4026(class_918.java:349)
	at net.minecraft.class_918.method_36543(class_918.java:339)
	at net.minecraft.class_918.method_27951(class_918.java:335)
	at net.minecraft.class_465.method_2385(class_465.java:265)
	at net.minecraft.class_465.method_25394(class_465.java:123)
	at net.minecraft.class_485.method_25394(class_485.java:43)
	at net.minecraft.class_481.method_25394(class_481.java:690)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_481
	Mouse location: Scaled: (604, 350). Absolute: (1814.000000, 1050.000000)
	Screen size: Scaled: (1254, 526). Absolute: (3761, 1577). Scale factor of 3.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['AlienXAXS'/17876, l='ClientLevel', x=478.84, y=81.00, z=2039.08]]
	Chunk stats: 1024, 484
	Level dimension: minecraft:overworld
	Level spawn location: World: (176,70,192), Section: (at 0,6,0 in 11,4,12; chunk contains blocks 176,0,192 to 191,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1540672 game time, 38431 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Generated Resources, Fabric Mods, charmonium/journeyman, KubeJS Resource Pack [assets]

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 943467640 bytes (899 MiB) / 2298478592 bytes (2192 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 12
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3090
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2204
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7212
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.20
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 44458.41
	Virtual memory used (MB): 31748.62
	Swap memory total (MB): 11776.00
	Swap memory used (MB): 278.02
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx10240m
	Fabric Mods: 
		addendum: Addendum 1.0.2
		additionaladditions: Additional Additions 2.1.3
		adorn: Adorn 2.1.5+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		advancementplaques: Advancement Plaques 1.4.1
		advancements-enlarger: Advancements Enlarger 0.2.4
		advdebug: Advancements Debug 2.3.0
		alaskanativecraft: Alaska Native Craft 1.3.1
		ambientenvironment: Ambient Environment 6.0.22
		amecsapi: Amecs API 1.1.4+mc21w16a
		appleskin: AppleSkin mc1.17-2.1.3
		appliedenergistics2: Applied Energistics 2 9.0.0-alpha.2
		aqupdcaracal: Caracal mob 1.17-1.3.2
		aqupdgrizzly: Grizzly Bear mob 1.17-1.2.0
		arcanus: Arcanus 1.16
		architectury: Architectury 2.5.31
		artifacts: Artifacts 5.0.2+fabric
		artifice: Artifice 0.15.3+21w07a
		asa: Air Strafing Attribute 1.2
		attributefix: Attribute Fix {FABRIC} 1.0.3
		authme: Auth Me 1.5.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		axolotlitemfix: Axolotl Item Fix 1.1.2
		balm-fabric: Balm 1.3.0+0
		bannerpp: Banner++ 2.0.3+mc.1.17-rc1
		basicaiots: Basic AIOTs 1.3.1
		bclib: BCLib 0.3.1
		beenfo: Beenfo 1.17.1-fabric0.36.1-1.3.2
		betterdungeons: YUNG's Better Dungeons 1.17-1.0.2
		betterend: Better End 0.11.0-pre
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.2
		biome_locator: Biome Locator 1.3.0
		bitsandchisels: BitsAndChisels 2.5.3
		blast: BLAST 1.8
		blockus: Blockus 2.2.10+1.17.1
		blue_endless_jankson: jankson 1.2.1
		bountiful: Bountiful 1.0.0
		breakprogress: Break Progress 1.0.1
		builtinservers: Builtin Servers 1.0.1-BETA+1.17
		campanion: Campanion 2.0.0-beta.1
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.1.0
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.0.0
		carrier: Carrier 1.8.0
		chalk: Chalk 1.0.0
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		cherishedworlds: Cherished Worlds 2.0.1-1.17.1
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cloth-api: Cloth API 2.0.54
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.0.38
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps 7.0.8
		coat: Coat 1.0.0-beta.9
		colorfulsubtitles: Colorful Subtitles 1.0.0
		columns: Columns 1.2.0
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_github_shevek_parallelgzip: parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		conjuring: Conjuring 1.0.9
		controlling: Controlling For Fabric 1.1.2
		cosmetic-armor: Cosmetic Armor 1.1.0
		craftingtweaks: Crafting Tweaks 13.0.0+0
		croptopia: Croptopia 1.6.3
		crowdin-translate: CrowdinTranslate 1.3+1.17
		crusade: Crusade 1.2.4
		dankstorage: Dank Storage 2.2.1-1.17.1
		dark-enchanting: Dark Enchanting 0.4.1-1.17.1
		dark-loading-screen: Dark Loading Screen 1.6.11
		darkpaintings: Dark Paintings 4.0.2
		dawn: Dawn API 2.0.6
		deathlog: DeathLog 0.2.1
		defaultsettings: DefaultSettings 3.1.0
		diggusmaximus: Diggus Maximus 1.5.1-1.17
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dml-refabricated: Deep Mob Learning: Refabricated 0.4.4-beta
		dml-refabricated-base: DML: Refabricated - Base 0.4.4-beta
		dml-refabricated-events: DML: Refabricated - Vanilla Events 0.4.4-beta
		dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 0.4.4-beta
		dml-refabricated-rei: DML: Refabricated - REI Integration 0.4.4-beta
		dmlsimulacrum: Deep Mob Learning: Simulacrum 1.0.5
		dual_riders: DualRiders 1.0.5
		dynamicfps: Dynamic FPS 2.0.5
		ecotones: Ecotones 0.8.1
		eggtab: Egg Tab 2.1.0+1.16-fabric
		enchantmentdescriptions: Enchantment Descriptions 4.0.1
		entitybanners: Entity Banners 1.0.2-BETA+1.17
		exdel: Explorer's Delight 1.0.0-beta.1
		expandability: ExpandAbility 4.0.2
		expandedstorage: Expanded Storage 7.2.4
		extended_armor_bars: Extended Armor Bars 1.1.0
		extragenerators: Extra Generators 1.1-BETA+1.17
		fabric: Fabric API 0.40.8+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+87cc6e4c18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b4463d5
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda931818
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab6121d5
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.11+7931163218
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.4+7931163218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.5+7931163218
		fabric-rendering-v1: Fabric Rendering (v1) 1.9.0+7931163218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121d5
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.0+7931163218
		fabricloader: Fabric Loader 0.11.6
		fake-player-api: Fake Player API 0.2.0
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fasttransferlib: Fast Transfer Lib 0.5.6
		ferritecore: FerriteCore 3.1.0
		fiber: fiber 0.23.0-2
		fireworkfrenzy: Firework Frenzy 1.5
		flonters: Flonters 1.2.1+1.17.1
		flytre-lib-base: Flytre Lib - Base Module 1.2.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.1
		flytre_lib: Flytre Lib 1.3.9
		gateofbabylon: Gate Of Babylon 1.5.1-1.17.1
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.15
		glassential: Glassential 1.17-1.2.0
		go-fish: Go Fish 1.3.0-beta-1.17.1
		golemsgalore: Golems Galore 1.0.3-1.17.1
		goml: Get Off My Lawn 1.4.0-beta
		graveyard: The Graveyard 1.0
		guild: Guild 0.3.1
		harvest_scythes: Harvest Scythes 2.0.6
		hctm-base: HCTM Base 3.6.2
		hologram-api: Hologram API 0.2.1+1.17.1
		horseinfo: Horse Info 0.3.0-1.17
		horsestatsvanilla: Horse Stats Vanilla 4.1.8
		iknowwhatimdoing: I Know What I'm Doing 3.1.0
		impaled: Impaled 1.0.1
		improved-stations: Improved Stations 2.0.7
		incantationem: Incantationem 1.1.2+1.17.1
		indrev: Industrial Revolution 1.11.0-alpha.1
		inmis: Inmis 2.3.2-1.17.1
		inventorysorter: Inventory Sorter 1.8.0-1.17
		iris: Iris 1.1.2+build.9
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 16
		jumpoverfences: JumpOverFences 1.16-0.0.3
		kambrik: Kambrik 1.1.0
		kibe: Kibe 1.9.2-BETA+1.17
		kjsextras: KubeJS Extras 1.4.0
		ktdatataglib: KtDataTagLib 1.5.4
		kubejs: KubeJS 1701.3.10-build.9999
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lakeside: Lakeside 1.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		libaddict: libaddict 0.3.0
		libblockattributes_core: LibBlockAttributes (Core) 0.9.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.0
		libblockattributes_items: LibBlockAttributes (Items) 0.9.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.7+1.17.1
		libninepatch: LibNinePatch 1.1.0
		libzoomer: LibZoomer 0.2.1+1.17
		lifts: Lifts 1.3-BETA+1.17
		lightestlamp: Lightest Lamps 0.9.2
		lightoverlay: Light Overlay 6.0.0
		lithium: Lithium 0.7.4
		lovely_snails: Lovely Snails 1.0.3+1.17
		magicfungi: Magic Fungi 0.4.1-BETA+1.17.1
		magna: Magna 1.5.5-1.17-pre4
		mavm: More Axolotl Variants Mod 1.0.5
		maybe-data: Maybe data 1.0.1-1.17
		megane: megane 5.5.0
		megane-applied-energistics-2: megane-applied-energistics-2 5.5.0+9.0.0-alpha.2
		megane-base: megane-base 5.5.0
		megane-dml-simulacrum: megane-dml-simulacrum 5.5.0+1.0.5
		megane-extra-generators: megane-extra-generators 5.5.0+1.1-BETA-1.17
		megane-fabric-transfer: megane-fabric-transfer 5.5.0+1.3.0-fc40aa9d18
		megane-fast-transfer-lib: megane-fast-transfer-lib 5.5.0+0.5.7
		megane-industrial-revolution: megane-industrial-revolution 5.5.0+1.11.0-alpha.1
		megane-kibe: megane-kibe 5.5.0+1.9.1-BETA-1.17
		megane-lib-block-attributes: megane-lib-block-attributes 5.5.0+0.9.0
		megane-modern-industrialization: megane-modern-industrialization 5.5.0+0.5.12
		megane-reborn-core: megane-reborn-core 5.5.0+5.0.8-beta-build.111
		megane-runtime: megane-runtime 5.5.0
		megane-team-reborn-energy: megane-team-reborn-energy 5.5.0+2.0.0-beta1
		megane-tech-reborn: megane-tech-reborn 5.5.0+5.0.8-beta-build.111
		megane-vanilla: megane-vanilla 5.5.0+1.17.1
		megane-wireless-networks: megane-wireless-networks 5.5.0+1.3.0
		minecraft: Minecraft 1.17.1
		minershorizon: Miner's Horizon 1.7.0-1.17.1
		mm: Manningham Mills 2.3
		mo_glass: Mo Glass 1.5-MC1.17.1
		mocolors: Mo' Colors 1.2.2
		modern_industrialization: Modern Industrialization 0.6.0-alpha.02
		modmenu: Mod Menu 2.0.14
		morevillagers-fabric: MoreVillagersFabric 2.1.1-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		mousewheelie: Mouse Wheelie 1.7.3-newconfig+mc1.17.1-pre1
		mtmechs: Magitek Mechs 1.0.3
		myron: Myron 1.6.1
		mythic-mounts: Mythic Mounts 1.17.1-1.3
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.2.2
		no-potion-offset: No Potion Offset ${version}
		noanglebrackets: NoAngleBrackets 1.1.0
		notes: Notes 1.0.7
		nyfsquivers: Nyf's Quivers Fabric-0.2.6
		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
		omega-config: OmegaConfig 1.0.8
		org_apache_commons_commons-compress: commons-compress 1.19
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		org_tukaani_xz: xz 1.8
		outvoted: Outvoted 2.0.0-alpha.13
		owo: oωo 0.2.1
		packages: Packages 1.2.1
		packet_tweaker: Packet Tweaker 0.2.0+1.17.1
		patchouli: Patchouli 1.17.1-56-FABRIC
		placeholder-api: Placeholder API 1.1.1+1.17.1
		playerabilitylib: Pal 1.3.0
		pling: Pling 1.4.0
		polymer: Polymer 0.1.6+1.17.1
		promenade: Promenade 2.1.2
		qcommon-cfg-core: qcommon-cfg-core 3.3.0
		qcommon-croco: Croco 2.1.1
		quarrymod: Industial Quarry Mod 0.4.3
		quickshulker: Quick Shulker 1.2.5-1.17
		ratsmischief: Rat's Mischief 1.2.2
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.0.9-beta+build.131
		redbits: Red Bits 1.10.1
		repurposed_structures: Repurposed Structures 2.3.9+1.17.1
		respawnablepets: Respawnable Pets 1.17-3
		rhino: Rhino 1605.1.4-build.63
		riverredux: River Redux 0.2.0
		roughlyenoughitems: Roughly Enough Items 6.0.279-alpha
		rswires: RSWires 4.11.2
		rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		runelic: Runelic 3.0.1
		secretrooms: Secret Rooms 1.0.0+1.17
		server_translations_api: Server Translations API 1.4.5+1.17
		sgui: SGui 1.0.0-rc4+1.17.1
		shulkerboxtooltip: Shulker Box Tooltip 3.0.1+1.17
		shulkerutils: shulkerutils 1.0.4-1.17
		skinlayers: 3d Skin Layers 1.1.0
		slight-gui-modifications: 'Slight' GUI Modifications 2.0.1
		slotlock: SlotLock 1.0.4-BETA+1.17
		smootherbedrock: Smoother Bedrock 1.0.2
		sodium: Sodium 0.3.2+IRIS2-build.9
		someforgepatchesported: Some Forge Patches Ported 1.0.1
		spruceui: SpruceUI 3.2.0+1.17
		stacc: Stacc 1.2.3
		staffofbuilding: Staff of Building 1.3.2-1.17
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.3
		strawdummy: Straw Dummy 1.5.0
		structurized: Structurized 1.3.0
		survivalisland: Survival Island 0.1.5
		team_reborn_energy: Energy 2.0.0-beta1
		techreborn: Tech Reborn 5.0.9-beta+build.131
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 2.0.0
		terraform-config-api-v1: Terraform Config API (v1) 2.0.0
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 2.0.0
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 2.0.0
		terraform-tree-api-v1: Terraform Tree API (v1) 2.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.17
		textile_backup: Textile Backup 2.2.0-1.17
		toolstats: Tool Stats 2.0.1
		tooltipfix: ToolTip Fix 1.0.4-1.17.1
		totemmod: Wither Totems Mod 0.3.2
		transportables: Transportables 1.0.6
		traverse: Traverse 4.0.0
		trident_return: TridentReturn 1.2.4
		trinkets: Trinkets 3.0.4
		truerooms: True Secret Rooms 1.1.5
		tweed4_annotated: tweed4_annotated 1.0.0
		tweed4_base: tweed4_base 1.0.0
		tweed4_data: tweed4_data 1.0.0
		tweed4_data_hjson: tweed4_data_hjson 1.0.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.0
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.0
		universal-graves: Universal Graves 1.1.2+1.17.1
		untitledduckmod: Untitled Duck Mod 0.3.0
		urns: Urns 1.0.1
		vanilla-hammers: Vanilla Hammers 3.1.2-1.17
		vanilla_degus: Vanilla Degus 1.2.3
		vanillaexcavators: Vanilla Excavators 1.1.0
		vanillaplusbiomes: Vanilla Plus Biomes 0.3.2
		villager-hats: Villager Hats Mod 1.2.1
		waystones: Waystones 2.1.2
		winged: Winged Mod 1.17.1-3.0.0
		wirelessnetworks: Wireless Networks 1.3.0
		wolveswitharmor: Wolves With Armor 1.6.1-1.17.1
		woods_and_mires: Woods and Mires 1.1.1+1.17
		wthit: wthit 3.9.3
		xaerominimap: Xaero's Minimap 21.18.0
		xaeroworldmap: Xaero's World Map 1.17.2
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.17-Fabric-19
		zihlaunchpads: ZIHLaunchpads 1.1.1
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3090/PCIe/SSE2 GL version 3.2.0 NVIDIA 472.12, NVIDIA Corporation
	Window size: 3761x1577
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, secretrooms:client_pack, Fabric Mods, charmonium/journeyman, kubejs:resource_pack (incompatible)
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
```

### Additional context

I have ensured that Iris seems to be at fault here, as when Iris is uninstalled the "Tools" section now works.
I never did find what item it was that crashes the game, but it does cause the render thread to die.

I hope this helps.

**Comment by polski-g** [comment]
This happens in 1.18 as well. There is no Indium for 1.18
