### ISSUE TITLE
Wisdom Shaders causes a crash or don't work (works with optifine)

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#959]
### What happened?

Loading shaders causes a crash

### Relevant log output

```shell
[14:29:59] [main/INFO]: Loading for game Minecraft 1.17.1
[14:29:59] [main/INFO]: [FabricLoader] Loading 8 mods:
	- fabric-api-base@0.3.0+a02b44633d
	- fabric-key-binding-api-v1@1.0.4+a02b44633d
	- fabric-lifecycle-events-v1@1.4.4+a02b44633d
	- fabric-resource-loader-v0@0.4.7+b7ab61213d
	- fabricloader@0.11.7
	- iris@1.1.2+build.9
	- java@17
	- minecraft@1.17.1
[14:29:59] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/loic/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[14:29:59] [main/INFO]: Compatibility level set to JAVA_16
[14:30:03] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:30:04] [Render thread/INFO]: Setting user: Lolothepro29
[14:30:04] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zbj000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[14:30:05] [Render thread/WARN]: Failed to parse line in block.properties: invalid render layer type: layer.solid
[14:30:05] [Render thread/WARN]: Failed to parse line in block.properties: invalid render layer type: layer.translucent
[14:30:05] [Render thread/INFO]: Using shaderpack: Wisdom-Shaders-master.zip
[14:30:05] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[14:30:06] [Render thread/INFO]: Hardware information:
[14:30:06] [Render thread/INFO]: CPU: 12x AMD Ryzen 5 1600 Six-Core Processor
[14:30:06] [Render thread/INFO]: GPU: NVIDIA GeForce GTX 1070/PCIe/SSE2 (Supports OpenGL 3.2.0 NVIDIA 495.44)
[14:30:06] [Render thread/INFO]: OS: Linux
[14:30:07] [Render thread/INFO]: Narrator library successfully loaded
[14:30:07] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Lifecycle Events (v1), Fabric Resource Loader (v0), Iris, Fabric Loader, Fabric API Base, Fabric Key Binding API (v1))
[14:30:11] [Render thread/INFO]: OpenAL initialized.
[14:30:11] [Render thread/INFO]: Sound engine started
[14:30:11] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[14:30:11] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[14:30:11] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[14:30:11] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[14:30:11] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[14:30:11] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[14:30:11] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[14:30:12] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[14:30:12] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[14:30:12] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[14:30:22] [Render thread/WARN]: Failed to parse line in block.properties: invalid render layer type: layer.solid
[14:30:22] [Render thread/WARN]: Failed to parse line in block.properties: invalid render layer type: layer.translucent
[14:30:22] [Render thread/INFO]: Using shaderpack: Wisdom-Shaders-master.zip
[14:30:26] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:30:26] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:30:26] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[14:30:26] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[14:30:26] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:30:26] [Render thread/INFO]: Reloading ResourceManager: Default
[14:30:27] [Render thread/INFO]: Loaded 7 recipes
[14:30:27] [Render thread/INFO]: Loaded 1137 advancements
[14:30:28] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:30:28] [Server thread/INFO]: Starting integrated minecraft server version 1.17.1
[14:30:28] [Server thread/INFO]: Generating keypair
[14:30:29] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[14:30:29] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[14:30:29] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[14:30:31] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[14:30:31] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[14:30:31] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[14:30:31] [Render thread/INFO]: Préparation de la zone d'apparition : 0 %
[14:30:32] [Render thread/INFO]: Préparation de la zone d'apparition : 5 %
[14:30:32] [Render thread/INFO]: Préparation de la zone d'apparition : 85 %
[14:30:32] [Render thread/INFO]: Time elapsed: 3570 ms
[14:30:32] [Server thread/INFO]: Changing view distance to 13, from 10
[14:30:33] [Server thread/INFO]: Lolothepro29[local:E:791ac7ae] logged in with entity id 117 at (-1274.6526009097956, 77.0, -1084.090066121915)
[14:30:33] [Server thread/INFO]: Lolothepro29 a rejoint la partie
[14:30:33] [Render thread/INFO]: Creating pipeline OVERWORLD
[14:30:33] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Texture type and format combination is not valid.'
[14:30:33] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Texture type and format combination is not valid.'
[14:30:33] [Render thread/ERROR]: Couldn't load NewWorldRenderingPipeline, falling back to vanilla shaders.
java.lang.IllegalStateException: Unexpected error while creating framebuffer
	at net.coderbot.iris.rendertarget.RenderTargets.createColorFramebuffer(RenderTargets.java:184) ~[iris-and-sodium-mc1.17-1.1.2+build.9.jar:?]
	at net.coderbot.iris.rendertarget.RenderTargets.createFullFramebuffer(RenderTargets.java:152) ~[iris-and-sodium-mc1.17-1.1.2+build.9.jar:?]
	at net.coderbot.iris.rendertarget.RenderTargets.createFramebufferWritingToMain(RenderTargets.java:128) ~[iris-and-sodium-mc1.17-1.1.2+build.9.jar:?]
	at net.coderbot.iris.rendertarget.RenderTargets.<init>(RenderTargets.java:61) ~[iris-and-sodium-mc1.17-1.1.2+build.9.jar:?]
	at net.coderbot.iris.rendertarget.RenderTargets.<init>(RenderTargets.java:35) ~[iris-and-sodium-mc1.17-1.1.2+build.9.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:149) ~[iris-and-sodium-mc1.17-1.1.2+build.9.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:429) ~[iris-and-sodium-mc1.17-1.1.2+build.9.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:32) [iris-and-sodium-mc1.17-1.1.2+build.9.jar:?]
	at net.minecraft.class_761.handler$zcl000$iris$beginWorldRender(class_761.java:4321) [intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java) [intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1026) [intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:810) [intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1112) [intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.7.jar:?]
[14:30:33] [Server thread/INFO]: Saving and pausing game...
[14:30:33] [Server thread/INFO]: Saving chunks for level 'ServerLevel[1.17.1 Optimised]'/minecraft:overworld
[14:30:34] [Server thread/INFO]: Saving chunks for level 'ServerLevel[1.17.1 Optimised]'/minecraft:the_nether
[14:30:34] [Server thread/INFO]: Saving chunks for level 'ServerLevel[1.17.1 Optimised]'/minecraft:the_end
[14:30:55] [Server thread/INFO]: Lolothepro29 lost connection: Déconnecté(e)
[14:30:55] [Server thread/INFO]: Lolothepro29 a quitté la partie
[14:30:55] [Server thread/INFO]: Stopping singleplayer server as player logged out
[14:30:55] [Server thread/INFO]: Stopping server
[14:30:55] [Server thread/INFO]: Saving players
[14:30:55] [Server thread/INFO]: Saving worlds
[14:30:55] [Server thread/INFO]: Saving chunks for level 'ServerLevel[1.17.1 Optimised]'/minecraft:overworld
[14:30:56] [Server thread/INFO]: Saving chunks for level 'ServerLevel[1.17.1 Optimised]'/minecraft:the_nether
[14:30:56] [Server thread/INFO]: Saving chunks for level 'ServerLevel[1.17.1 Optimised]'/minecraft:the_end
[14:30:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (1_17_1 Optimised): All chunks are saved
[14:30:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[14:30:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[14:30:56] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[14:30:56] [Render thread/INFO]: Destroying pipeline OVERWORLD
[14:30:56] [Render thread/INFO]: Stopping!
```

### Iris and Minecraft Version

fabric-loader-1.17.1

### Are you running Sodium along with Iris?

No

### Operating System

Ubuntu 20.04

### What is your GPU?

GTX 1070

### Java Version

Java 17

**Comment by Lolothepro** [comment]
same problem with NV shader
[latest.log](https://github.com/IrisShaders/Iris/files/7491065/latest.log)
s

**Comment by coderbot16** [comment]
The crash was resolved in https://github.com/IrisShaders/Iris/commit/187571802eb4a44ed4dc299be5a2e62a49310846. Otherwise, general issues about packs not working that don't point at a specific bug or underlying issue are being tracked in https://github.com/IrisShaders/Iris/issues/1030.

**Comment by Lolothepro** [comment]
NVshaders:
- [1.16.5: Shadows are not correct and water moves relative to the player (1.1.4pre) (and others I haven't seen)]
- [<1.17.1: Vanilla, the shader does not load]
