### ISSUE TITLE
Game crashes when opening.

### ISSUE THREAD

**Issue by Kiraiyi** [IrisShaders/Iris#968]
### Iris and Minecraft Version

iris-and-sodium-mc1.17-1.1.2+build.9 for Minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 11

### What is your GPU?

AMD Radeon Rx580

### Java Version

Java 8

### Reproduction Steps

1. Put iris, Sodium and FabricAPI onto the mods folder.
2. Start the game.
3. Game Crashes.

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 11-11-21 15:03
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'indium'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:457)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5944 failed
	at net.minecraft.class_4668.<clinit>(class_4668.java:125)
	at net.fabricmc.fabric.api.renderer.v1.material.BlendMode.<clinit>(BlendMode.java:33)
	at link.infra.indium.renderer.RenderMaterialImpl.<clinit>(RenderMaterialImpl.java:34)
	at link.infra.indium.renderer.IndiumRenderer.materialFinder(IndiumRenderer.java:50)
	at link.infra.indium.renderer.IndiumRenderer.<clinit>(IndiumRenderer.java:33)
	at link.infra.indium.Indigo.onInitializeClient(Indigo.java:118)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5944 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:224)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 18 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222)
	... 21 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectGetUniformLocation(ILjava/lang/CharSequence;)I in sodium.mixins.json:features.shader.MixinShader from mod sodium failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.sodium.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1381)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 24 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:457)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 4114637320 bytes (3924 MiB) / 4462739456 bytes (4256 MiB) up to 19327352832 bytes (18432 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2,90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
```

### Additional context

It could sound stupid, but I've been trying everything and it just keeps happening.
There are only those three mods in the folder, nothing more than that.

**Comment by maximumpower55** [comment]
iris comes with sodium bundled in, remove the sodium jar in your mods folder

**Comment by NoComment1105** [comment]
That's not the issue

**Comment by NoComment1105** [comment]
It's a separate issue with indium, to which we need the full log please

**Comment by maximumpower55** [comment]
it looks like a issue with a sodium mixin and not indium

**Comment by NoComment1105** [comment]
Yep, tho a full crash report is needed to diagnose fully

**Comment by Kiraiyi** [comment]
[crash-2021-11-11_15.03.22-client.txt](https://github.com/IrisShaders/Iris/files/7522855/crash-2021-11-11_15.03.22-client.txt)

**Comment by Kiraiyi** [comment]
[crash-2021-11-11_15.03.22-client.txt](https://github.com/IrisShaders/Iris/files/7522877/crash-2021-11-11_15.03.22-client.txt)

**Comment by maximumpower55** [comment]
can you give latest.log too

**Comment by Kiraiyi** [comment]
[latest.log](https://github.com/IrisShaders/Iris/files/7522895/latest.log)
I'm not really sure if this is what you're asking for, but I hope it is. Sorry for the inconvenience.

**Comment by maximumpower55** [comment]
yep thats it

**Comment by maximumpower55** [comment]
can you try without indium

**Comment by Kiraiyi** [comment]
[crash-2021-11-11_15.03.22-client.txt](https://github.com/IrisShaders/Iris/files/7522932/crash-2021-11-11_15.03.22-client.txt)
It chrashes again.

**Comment by maximumpower55** [comment]
can you send your mods folder

**Comment by IMS212** [comment]
Please stop spamming this issue, this is a bug with the Shader mixin of Sodium combined with Iris, which is fixed by removing said Mixin (which will be done in a future release.) To fix this temporarily you will have to open up the Sodium jar file and remove MixinShader from the active mixin list.
